### ISSUE TITLE
Number of available and used private repositories should be displayed

### ISSUE THREAD

**Issue by kizbitz** [docker/hub-feedback#10]
New:
![screen shot 2015-06-04 at 10 46 12 am](https://cloud.githubusercontent.com/assets/201920/7986709/1a0351da-0aa7-11e5-93df-686cd6344d83.png)

Compared to current:
![screen shot 2015-06-04 at 10 47 04 am](https://cloud.githubusercontent.com/assets/201920/7986722/29b41060-0aa7-11e5-8f49-2110800ce024.png)

**Comment by kizbitz** [comment]
duplicate: https://github.com/docker/hub-beta-feedback/issues/168

**Comment by kristiehoward** [comment]
Closed as this has been fixed in production.
