### ISSUE TITLE
Retention period of a docker image

### ISSUE THREAD

**Issue by sprabhuanand** [docker/hub-feedback#1001]
Hi,

We have many repositories within Dockerhub - just wondering what's the retention policy of the images (how long can a built docker container can be in dockerhub)? like 6 months or 9 months - so that 

And also, a quick question on the number of builds/tags - How many builds/tags that I can have it within dockerhub for one repository?

Any pointers will be helpful.

Thanks!

**Comment by vanpelt** [comment]
I would love to understand how long layers are retained.  My usecase is to store the digest and I want to tell my users how long they'll be able to restore from it.
