### ISSUE TITLE
Building certain tags fails with "error" but no log or other output

### ISSUE THREAD

**Issue by bryanlatten** [docker/hub-feedback#1007]
No build failure message, either.

![screen shot 2017-04-04 at 3 01 16 pm](https://cloud.githubusercontent.com/assets/1202354/24673853/a7cb1e84-1947-11e7-88d5-ce1532cdaba0.png)

I've tried repeatedly over the course of several hours. Docker status looks clean, too. Have been generating tags/variants of this image for some time now, this is a new issue.

Example: 
https://hub.docker.com/r/bryanlatten/docker-php/builds/botymjgjpnns5uxsulga2wu/

**Comment by pchico83** [comment]
@bryanlatten We have released 17.03 this morning. I am investigating this issue as a possible regression. Will keep you posted.

**Comment by pchico83** [comment]
@bryanlatten could you check again?

**Comment by bryanlatten** [comment]
It's definitely gotten further. Thanks @pchico83 !
