### ISSUE TITLE
network issue in one docker compose with keycloak and tomcat container

### ISSUE THREAD

**Issue by cywang16** [docker/hub-feedback#1009]
Greeting,

I'm a beginner is learning web authentication, and would like to try with tomcat and keycloak in docker compose. I put them in one docker-compose.yml as follows:

<pre>
version: '2'

services:
    postgres:
        image: postgres
        ports:
            - "5432:5432"
        environment:
            POSTGRES_DATABASE: 'keycloak'
            POSTGRES_USER: 'keycloak'
            POSTGRES_PASSWORD: 'keycloak'
            POSTGRES_ROOT_PASSWORD: 'test'
        volumes:
            - ./postgres:/mnt/shares/postgres
    keycloak:
        image: jboss/keycloak-postgres
        ports:
            - "800:8080"
        links:
            - postgres
        environment:
            POSTGRES_PORT_5432_TCP_ADDR: 'postgres'
            POSTGRES_DATABASE: 'keycloak'
            POSTGRES_USER: 'keycloak'
            POSTGRES_PASSWORD: 'keycloak'
            KEYCLOAK_USER: 'admin'
            KEYCLOAK_PASSWORD: 'admin'
            POSTGRES_ROOT_PASSWORD: 'test'
        depends_on:
            - postgres
        volumes:
            - ./keycloak:/mnt/shares/keycloak
    tomcat_keycloak:
        build: .
        ports:
            - "880:8080"
        volumes:
            - ./web:/mnt/shares/web
            - ./scratches:/mnt/shares/scratches
</pre>

This can launch fine. Next I created the realm, client, and user in the keycloak, obtained a keycloak.json for tomcat as follows:

<pre>
{
    "realm": "TestRealm",
    "auth-server-url": "http://192.168.208.130:800/auth",
    "ssl-required": "external",
    "resource": "test-client",
    "public-client": true,
    "use-resource-role-mappings": true
}
</pre>

where 192.168.208.130 is my host ip address. Then I tried a static web link in my tomcat server. I could be redirected to the keycloak login page. But after entering user name and password, I got HTTP status 403. In the keycloak events I saw the logon was successful, and a session was established. I checked the tomcat output, and then found the following:

<pre>
07-Apr-2017 17:37:04.240 INFO [http-apr-8080-exec-4] org.apache.http.impl.client.DefaultHttpClient.tryConnect I/O exception (java.net.NoRouteToHostException) caught when connecting to {}->http://192.168.208.130:800: No route to host (Host unreachable)
07-Apr-2017 17:37:04.241 INFO [http-apr-8080-exec-4] org.apache.http.impl.client.DefaultHttpClient.tryConnect Retrying connect to {}->http://192.168.208.130:800
07-Apr-2017 17:37:05.243 INFO [http-apr-8080-exec-4] org.apache.http.impl.client.DefaultHttpClient.tryConnect I/O exception (java.net.NoRouteToHostException) caught when connecting to {}->http://192.168.208.130:800: No route to host (Host unreachable)
</pre>

Looks like from my tomcat container, I cannot do HTTP client connection to my keycloak server container via the URL in host ip address. I can ping the host ip from the tomcat container though.

Could you help me to find out what I'm missing in this configuration? Really appreciate.

**Comment by adrianRiobo** [comment]
At this point I suppose you have already solved your problem... but in case it helps anybody else...

It is probably related with your host iptables / firewalld. So if it is your dev environment may give a try disabling them or add a new rule to allow connections

**Comment by Lazzaro83** [comment]
I am having the same problem but with Express app. Although I have connection between express container and keycloack container, I always get Access denied and 403. 

Does anybody know what should I do?
