### ISSUE TITLE
Cannot Create Automated Build: The repository name is already taken.

### ISSUE THREAD

**Issue by markTward** [docker/hub-feedback#1012]
**Summary**: The automated build for this repo is caught in a contradictory state.  It isn't visible on the repo home page but cannot be recreated, even after deletion and recreation of the repo.

I have successfully linked my docker account with github and attempted to create an automated build via the UI.  After submitting the form to 'Create', I clicked on another link before it completed (my first automated build; slow response time; no feedback that I should wait).  

The 'Automated Build' label header did not appear on the repo home page.  I reattempted to create the automated build and received the following message: **The repository name `<user>/<repo>` is already taken.**

I deleted the repo and recreated it using the same name.  Reattempting to create the automated build failed with the same message.

I was able to successfully create an automated build for another repo after waiting for  the (slow) create process to complete.  

If I'm not missing something, I think this is a bug.  Given my 'user error' of not waiting for the creation process to complete, the automated build should again be available for creation.  Also, if the repo is deleted, all linked services should be freed from being tied from it.  In this case, it seems to be using <user>/<repo> as the key.

Is their anyway for docker to clear this block for me?  I can't find a way to do it via the UI.  Is their an API call that would work?

Cheers

**Repo Homepage Not Displaying 'Automated Build'**
![screen shot 2017-04-11 at 1 01 27 pm](https://cloud.githubusercontent.com/assets/4840338/24929528/1f0b0162-1ebb-11e7-8c12-1fc978b70a67.png)

**Failed Attempt to Create Automated Build**
![screen shot 2017-04-11 at 1 02 45 pm](https://cloud.githubusercontent.com/assets/4840338/24929502/08aece80-1ebb-11e7-9449-f55141161776.png)

**Comment by brandondoran** [comment]
The exact same thing happened to me. It seems there's not way to fix without some internal assistance.

**Comment by brandondoran** [comment]
Confirmed. Deleting the repo and re-creating does not clear the error.

**Comment by pmcgrath** [comment]
Confirmed, same failure

**Comment by pmcgrath** [comment]
I have just went through the following that resolved this for me
- Delete the dockerhub repository
- Create automated build - now I can use the repo name that matches my dockerhub repo

I had already created a dockerhub repo and then attempted to create an automated build, guessing the dockerhub repo must not already exist ? Worked for me but had seen nothing in the docs

See https://github.com/docker/hub-feedback/issues/450#issuecomment-155097245

**Comment by mhermosi** [comment]
Why it was not taken into consideration a flow that let add an automated build to an existing repo.
