### ISSUE TITLE
API to get Top Docker Hub images?

### ISSUE THREAD

**Issue by fluency03** [docker/hub-feedback#1016]
I would like to know is there an API to get the Top Docker Hub images?

Like what we can get when we open https://hub.docker.com/explore/ 

I have checked: 

https://docs.docker.com/engine/api/v1.28/# and 
https://docs.docker.com/registry/spec/api/

But did not find what I want.

**Comment by marcusmartins** [comment]
Hi @fluency03 ,

We don't currently have a public API for Docker Hub. We are evaluating the feature but we do not have a roadmap for it at this point.

Thanks for the feedback.
