### ISSUE TITLE
Delete automated build

### ISSUE THREAD

**Issue by varshavaradarajan** [docker/hub-feedback#1017]
Is there a way to get rid of the dockerhub automated build other than to delete the dockerhub repository or to deactivate the authorized service on github? 

We want to push the images ourselves and not have it show a stale Dockerfile on dockerhub.

**Comment by vveider** [comment]
+1

**Comment by thelamer** [comment]
+1
We at Linuxserver.io need this, we played with autobuilds on a couple repos some time back and did not understand that meant the Dockerfiles would be forever published from those test builds with no option to delete them.

**Comment by pom11** [comment]
+1
