### ISSUE TITLE
Build's not triggering

### ISSUE THREAD

**Issue by sean-abbott** [docker/hub-feedback#1018]
When attempting to manually trigger via the button in "build settings", I get this response:

"[{"source_type": "Branch", "source_name": "master", "evaluated_tag_name": "latest", "build_code": null, "msg": "Unhandled error while submitting build. The problem has been logged.", "queued_for_retry": false}]"

(captured via network debugging in my browser).

I'd love for it to 
A) queue for retry and
B) given some indication that it's failing without me needing to go into my browser dev tools.

**Comment by andrewgbliss** [comment]
Build's not triggering for me either. I have an automated build through github and when I pushed it didn't trigger a build. And when I hit the button under build settings, it says it triggered it, but nothing happens under build details.

**Comment by jchamberlain** [comment]
Found this searching for why my builds won't start. The error I get in the JSON though is, "A build for tag latest is already pending. Ignoring request." As @sean-abbott said, it'd be nice to display that.

**Comment by caervs** [comment]
Our apologies. The build system just had an outage which we just resolved and are monitoring. We're about to update [status.docker.io](status.docker.io). Any builds you triggered in that time should now be visible. Please let us know if you continue to have issues.

**Comment by sean-abbott** [comment]
Good to go.  It'd be nice to know how to trigger my tag build, though, rather than untagging and retagging it?

**Comment by caervs** [comment]
Yeah. Right now you can only trigger a rule manually which will build anything that matches that rule. We'll take your case into consideration. Thanks!
