### ISSUE TITLE
[Security] Able to create repos after being ejected from org.

### ISSUE THREAD

**Issue by jborrey** [docker/hub-feedback#1019]
Bob creates organization X.
Bob adds Alice to organization X.
Alice ejects Bob from organization X.

Organization X does not appear as an option in Bob's account anymore but he can go to the domain 
`https://hub.docker.com/u/X/dashboard/` anyway. From there he cannot edit the org info or read/write teams. These will show permission denied errors. Bob is however still able to create repositories.

Bob should just get another perm denied error for that.
They also shouldn't be able to view the dashboard in the first place.

**Comment by pkennedyr** [comment]
Hi @jborrey - Can you contact support.docker.com and share details of your account so the team can investigate this issue? Thanks.

**Comment by jborrey** [comment]
Sure
