### ISSUE TITLE
Hard to distinguish windows containers vs linux containers (unknown blobs)

### ISSUE THREAD

**Issue by martencassel** [docker/hub-feedback#1020]
Its hard today to distinguish wether images are built for linux runtime or windows runtimes.

If i try from a windows host pull a linux container... i get an unknown blob error which isn't that informative, or vice versa pulling a windows container on a linux host. This leads one to google ...

https://www.google.se/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=unknown+blob

It also gets more difficult as for example in microsoft docker hub repo they nowadays have ported .net to linux and also package .net for windows based containers. Its hard to distinguish them.

Would be great if there are some categorization or metadata so you can distinguish the platform this image is compatible.

Apparently the downloading and storing of images in the local storage of the docker host is 
OS dependent on what driver implements the storage.
 - Windows: windowsfilter
 - Linux: say: overlay

That leads me think think that docker today and implementations of docker on different platforms doesn't yet use conform to a shared standard for container formats and runtimes.. and we fall into gaps where try to move around our containers across different os platforms.

**Comment by taylorb-microsoft** [comment]
I agree...  See https://github.com/moby/moby/issues/25417 for a road map on this work... It's going to be even more critical as we start multi-platform work link Linux containers into Windows.

On the Store side (store.docker.com) you can select the platform but for repositories with images that for multiple platforms (go/node/.net/etc...) it's still quite messy.  For example what should be tagged latest?
