### ISSUE TITLE
Requesting a dead namespace

### ISSUE THREAD

**Issue by stelcheck** [docker/hub-feedback#1021]
Is there a procedure for requesting a username/organization namespace on docker hub which exists but has not been used for the last 2-3 years and holds no images (according to the profile page)? What is the point of contact for such requests

**Comment by schuer** [comment]
+1

**Comment by thaJeztah** [comment]
I suggest contacting support@docker.com - it's possible a seemingly empty namespace is in active use, but only has private repositories; they should be able to check that

**Comment by stelcheck** [comment]
Understood. Thank you!
