### ISSUE TITLE
pattern matching in .dockerignore broken (probably CE vs EE issue)

### ISSUE THREAD

**Issue by afri** [docker/hub-feedback#1026]
Some patterns in .dockerignore are breaking builds on dockerhub.
In particular, recently on dockerhub (17.03.1-ee-2), patterns such as `**/.gup` also capture `foo/bar/baz.gup`.
In all ce docker versions (up to at least 17.04.0-ce), the pattern works correctly and captures `foo/bar/.gup`, but not `foo/bar/baz.gup`

**Comment by mhutter** [comment]
This is still an issue. It's quite a pain because it means builds on hub.docker.com behave differently than local.
