### ISSUE TITLE
error when Deploy to Docker Swarm using Gitlab CI

### ISSUE THREAD

**Issue by offsidezzz** [docker/hub-feedback#1027]
hi all,

I'm beginner on docker, and I've got some problem.
I created my docker swarm on AWS using CloudFormation using template from https://editions-us-east-1.s3.amazonaws.com/aws/stable/Docker.tmpl

and my teammate created gitlab-ci-runner on other instance on AWS. our plan are to use CI/CD deployment on that docker swarm. so I follow instruction from this post https://morph027.gitlab.io/post/gitlab-ci-with-docker-swarm/

here is my yaml file :

_deploy-to-swarm:
  stage: deploy
  variables:
    DOCKER_HOST: tcp://<DNS of my docker swarm manager>:2377
    CI_DEBUG_TRACE: "true"
    SERVICE_NAME: foobar
    CI_PROJECT_NAMESPACE: root
    CI_PROJECT_NAME: keuber-demo
  image: docker:latest
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker stack deploy --with-registry-auth --compose-file=docker-stack-compose.yml ${CI_PROJECT_NAMESPACE}-${CI_PROJECT_NAME}-${SERVICE_NAME}
  environment:
    name: master
    url: http://${CI_BUILD_REF_NAME}.example.com
  only:
    - master_

when I commit and the pipeline ran, the result is failed. here is the error message
![error1](https://cloud.githubusercontent.com/assets/28127292/25519946/2f0a66e0-2c24-11e7-8fa7-1a23fb28dd64.PNG)

please help, thank you in advance.

**Comment by marcusmartins** [comment]
Hi @offsidezzz,

Please keep in mind that this GitHub issue tracker is not intended as a general support help forum,
but for reporting bugs and feature requests for Docker Hub. For other type of questions, consider using https://forums.docker.com as you will get more visibility into your issue.

I would also recommend contacting Gitlab directly as you are following their instructions to setup the service.

I am going to close this issue for now as it does not seem to be related to a bug on https://hub.docker.com
