### ISSUE TITLE
Explore View: Huge amounts of wasted space

### ISSUE THREAD

**Issue by Xorlev** [docker/hub-feedback#103]
![screen shot 2015-06-19 at 4 27 49 pm](https://cloud.githubusercontent.com/assets/348618/8264162/3c283550-16a0-11e5-987f-e4687a8c1710.PNG)

What I dislike about the Explore view is that each repo is a HUGE block item with a tiny bit of text. No details, description, nothing.

I'd love to see this blank area filled with a description of a sort so I can filter which projects I might be interested in without drilling in. Either that, or shrink the rows so I can see more in my limited vertical view.

**Comment by ChristopherBiscardi** [comment]
For the record; That is indeed the plan. This is the 'mvp' (so to speak) of the explore page and we will be developing it further.
