### ISSUE TITLE
organisation creation form has unclear restrictions

### ISSUE THREAD

**Issue by oulenz** [docker/hub-feedback#1033]
I tried to create an organisation and was mystified why it wouldn't let me.
* I received no error message, only subtle red outlines around the namespace and url boxes
* I have no idea why the namespace `epigram` wasn't accepted. Is it taken? [http://hub.docker.com/_/epigram](http://hub.docker.com/_/epigram) says that page doesn't exist
* The url box doesn't seem to accept `epigram.ai` or `http://epigram.ai`. No idea why

**Comment by sirockin** [comment]
+1
