### ISSUE TITLE
haven't receive the active mail

### ISSUE THREAD

**Issue by gifttang** [docker/hub-feedback#1034]
my id is gifttang.
the email is gifttang@sina.com.
But i have not received the active mail even yet.

**Comment by jonafrank** [comment]
id jonafrank
it happens to me too jonafrank@gmail.com

**Comment by romdim** [comment]
same here and I can tell it's not the first time:
https://github.com/docker/hub-feedback/issues/631

**Comment by dantebarba** [comment]
Same here

**Comment by dantebarba** [comment]
dantebarba my user is

**Comment by thaJeztah** [comment]
@dantebarba (and others) It's best to contact support@docker.com for this as they should have access to that information

**Comment by lnalex** [comment]
Can't change my email address in my settings, confirmation emails aren't sent.
