### ISSUE TITLE
Query : How to build an Image using Docker API?

### ISSUE THREAD

**Issue by Raghavendarlokineni** [docker/hub-feedback#1035]
I am trying to build a docker Image using the APIs mentioned in the [official link.](https://docs.docker.com/engine/api/v1.24/#images)

But I am unable to get what the document says: 

```
Example request:

POST /v1.24/build HTTP/1.1


{{ TAR STREAM }}
```
There are few things which are confusing me,

1) Where to mention the **path for the Dockerfile?**

2) "The archive must include a build instructions file, typically called Dockerfile at the archive’s root." This statement from docker docs, the confusion here is **what is archive's root**?

3) What is the **command in detail for building an Image?**

**Comment by marcusmartins** [comment]
Hi @Raghavendarlokineni,

It looks like you are having issues with the Docker API directly and it's not a service we expose directly on the Docker Hub platform. I would suggest posting a question on https://forums.docker.com and we will be able to help you better from there.

I am going to close this issue for now as it doesn't look like it's a problem related to hub.docker.com

**Comment by Raghavendarlokineni** [comment]
Thanks for your prompt reply.  

I do have raised the similar question in [docker forum](https://forums.docker.com/t/how-to-build-an-image-using-docker-api/31807/2). As I didn't get a reply from anyone I have raised the same issue here expecting an help from Docker team. Luckily I had found the solution for this and posted the same in the docker forum.
