### ISSUE TITLE
Add ability to use Ansible in hooks/build for building images instead of docker build

### ISSUE THREAD

**Issue by lorddaedra** [docker/hub-feedback#1036]
Please, add ability to use Ansible in hooks/build for building images instead of docker build

https://www.ansible.com/ansible-container

It may be used together with custom `hooks/build` as described in 
https://docs.docker.com/docker-cloud/builds/advanced/#override-build-test-or-push-commands

**Comment by marcusmartins** [comment]
Hi @lorddaedra,

That option is available on https://cloud.docker.com. Where you able to configure your build from there?
