### ISSUE TITLE
Private repositories filter only finds items from the first 100 repositories 

### ISSUE THREAD

**Issue by rreinurm** [docker/hub-feedback#1037]
In my company we use private registry plan with 250 private repositories and currently we have more than 100 private repositores. But if I want to filter out some specific repository using form `Type to filter repositories by name` then I can't search repositories which are out of sorted array of 100 items.

How to reproduce?
1. Own more than 100 private repositories under company/personal account
2. Have 1 private repository which has the smallest number of pulls compared to other repositories and is constantly the last item in the list
3. Try to filter it out via form `Type to filter repositories by name`

Workaround:
Navigate via pages until you find desired repository which is very user unfriendly. Think about customers who would like to filter out from 500 repositories using the largest plan you currently offer.

**Comment by rreinurm** [comment]
Operating system: OSX 10.12.4
Browser and Browser version: Google Chrome  57.0.2987.133 (64-bit)
URL for the page in question.: https://hub.docker.com/u/<account>/dashboard/
Any error messages (on screen or in browser console): No error message on screen or browser console

**Comment by thaJeztah** [comment]
Can you reach out to support@docker.com and open a ticket?

**Comment by rreinurm** [comment]
@thaJeztah sure, will do that :)

**Comment by SmokinJoe98TA** [comment]
Has there been a resolution for this?

**Comment by ratishm-cyb** [comment]
This issue is still present, Can't search repos created after 100 private repos.
