### ISSUE TITLE
Failing to add Slack webhook

### ISSUE THREAD

**Issue by sr-murthy** [docker/hub-feedback#1038]
I'm trying to add a Docker Hub - Slack webhook that will post updates to selected Docker Hub private repositories (owned by the organization I work for) to a dedicated Docker Hub channel in our organizational Slack team. I have tried to follow the instructions on Docker Hub to add webhooks: first I added an Incoming WebHooks integration in our Slack team settings, which provides a payload URL. I then went to one of our Docker Hub repositories and created a webbook by adding this payload URL and a label. I tested this by manually pushing a image to this repository from my local machine, but I can see that the webhook history shows an error without any detail.

Does anyone have a similar experience or know how to resolve this?

Thanks for any assistance.

Sandeep

**Comment by marcusmartins** [comment]
Hi @sr-murthy, can you file a ticket with https://support.docker.com and we can help you from there?

**Comment by sr-murthy** [comment]
OK, thanks, will do.
