### ISSUE TITLE
docker-compose different behaviours with "-d" option

### ISSUE THREAD

**Issue by emanuele-leopardi-dap** [docker/hub-feedback#1040]
Hi, 
I'm experiencing different behaviours when using docker-compose to link 2 containers.
I'm linking SonarQube with MySQL: if I run the same command id est:
`docker-compose -f docker-compose.yml up` 
then the 2 containers are regularly created without any issues.
if i add "-d" option id est:
`docker-compose -f docker-compose.yml up -d` 
the 2 containers are created but the one with sonarqube dies after 10 second because unable to find mysql.

you can test it with standard mysql and sonarqube containers

here's the compose file
`sonarqube:
  image: sonarqube
  ports:
   - "9000:9000"
   - "9092:9092"
   - "3306:3306"
  environment:
   - SONARQUBE_JDBC_USERNAME=test
   - SONARQUBE_JDBC_PASSWORD=test
   - SONARQUBE_JDBC_URL=jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true&useConfigs=maxPerformance
db:
  image: mysql:latest
  net: container:sonarqube
  environment:
   - MYSQL_ROOT_PASSWORD=test
   - MYSQL_DATABASE=test
   - MYSQL_USER=test
   - MYSQL_PASSWORD=test`

Thanks in advice

**Comment by marcusmartins** [comment]
Hi @emanuele-leopardi-dap,

Please keep in mind that this GitHub issue tracker is not intended as a general support help forum,
but for reporting bugs and feature requests. For other type of questions, consider using https://forums.docker.com for community support.

I am going to close this issue for now as it doesn't look like it's a problem related to hub.docker.com
