### ISSUE TITLE
Automated build are broken after renaming Github organization

### ISSUE THREAD

**Issue by marekaf** [docker/hub-feedback#1041]
Hi,
we renamed our GitHub Org from AckeeCZ -> AckeeDevOps (actually we split it into several suborgs)
Now this repo https://github.com/AckeeCZ/jenkins-android-docker-slave redirects you to the new one in the new organization. Github web and Git client handles the new origin without any problems. The automated builds (or the webhooks) on docker hub are broken though. 

The only workaround I though of was creating a new automated build with the new repo and linking the repo to the broken build of the original automated build. When I try to do exactly that, I get "Failed to link this repository to your Automated Build."

**Comment by pkennedyr** [comment]
Thanks for the feedback. Please feel free to contact support for assistance with your issue: support.docker.com
