### ISSUE TITLE
Check building on hub.docker.com or local machine, and execute corresponding code.

### ISSUE THREAD

**Issue by eromoe** [docker/hub-feedback#1042]
Hi,

I am in China, I need create a docker image with custom apt-get source ,pip source and so on.

I write a Dockfile here  https://github.com/eromoe/base/blob/master/Dockerfile

Local building is fine, but can not build on hub.docker.com for a long time, detail https://hub.docker.com/r/eromoe/base/builds/blen9qjpkxogo2bac5qq2nu/

Looks like some network error? (because apt-get is pointed to a China source, I need change source at first so that local build could success)

I only want to use one Dockerfile to support Local building and dockerhub host. So is there any way to check if building in hub.docker.com or local and execute corresponding code? Such as, when build in hub.docker.com, update source at last .

**Comment by marcusmartins** [comment]
Hi @eromoe,

The build performed in Hub are based in the US so it's possible that the custom source you're attempting to connect to is not available from our  infrastructure - based on the logs, I can see 404 being returned for some of the sources:
`W: Failed to fetch http://mirrors.aliyun.com/ubuntu/dists/trusty/multiverse/source/Sources  404  Not Found [IP: 115.28.122.210 80]`. It's possible that it's not available outside China or it's very slow.

Please keep in mind that this GitHub issue tracker is not intended as a general support help forum,
but for reporting bugs and feature requests. For other type of questions, consider using https://forums.docker.com. I am closing this issue for now as it doesn't look like a problem with our service.
