### ISSUE TITLE
Cannot reset password - don't get password reset email

### ISSUE THREAD

**Issue by imranq2** [docker/hub-feedback#1049]
I'm trying to reset the password for my account, imran.qureshi@healthcatalyst.com but I do not receive the email.  Is there any other way to reset the password, say phone or something?

**Comment by mhohai** [comment]
can't receive reset password email (@aim.com), but sign up can receive email (@gmail.com)

**Comment by logicethos** [comment]
Did you complete the registration? It occurred to me, I gave up waiting for the confirmation e-mail, and now having come back, I cant login, or reset.

I sent them a request here https://success.docker.com/Support but no reply

**Comment by kchrs** [comment]
No email is sent after resetting passwords. Guys check your mail servers

**Comment by davyzhang** [comment]
Can't get mail to gmail.com, for a LONG time

**Comment by andyl** [comment]
Broken for me as well.
