### ISSUE TITLE
building with a dockerfile in a different sub-folder fails

### ISSUE THREAD

**Issue by gingerlime** [docker/hub-feedback#1053]
We have a project with dockerfiles in a different folder, i.e.

`/dockerfiles/web`, `/dockerfiles/backend` etc

We can build just fine using docker-compose using

```
build:
  context: .
  dockerfile: ./dockerfiles/web
```

And I've set up the Dockerfile location to `/dockerfiles/web` under build settings.

It picks the right dockerfile and starts the build. However, when I try to build on docker hub, I get this error

```
...

Step 7/12 : ADD Gemfile $app/Gemfile

lstat Gemfile: no such file or directory
```

Any suggestions on how to work around it or resolve it?

Cheers,
Yoav

**Comment by pchico83** [comment]
@gingerlime you need to define `.` as the build context in your build rule. Build context support is not available in Hub, but it is available in Docker Cloud, which has other nice features over Docker Hub.

**Comment by gingerlime** [comment]
Hmm... Ok. Seems like a rather strange limitation. So that means we'll also need to pay for either our own nodes or use yours to build? whereas with docker hub it's included?

**Comment by pchico83** [comment]
Docker Cloud works the same than Docker Hub, but it has a superset of features. You can build in the docker infrastructure nodes for free.

**Comment by gingerlime** [comment]
Thanks @pchico83 I'll try it out. From the settings page it implies there's some cost, although 750 node hours are free per month? (so this should hopefully cover our build time, but I'm not sure how to estimate this).

**Comment by pchico83** [comment]
@gingerlime that costs is for running nodes where you deploy your own services, but CI is for free is you pick the "Build in Docker infra nodes" option.

**Comment by gingerlime** [comment]
Thanks. Good to know :)

The UI looks nice and definitely feels more powerful. Thanks for the quick response.
