### ISSUE TITLE
Errors on Build zlib_decode()

### ISSUE THREAD

**Issue by vrubiella** [docker/hub-feedback#1057]
Hello, 
Since yesterday I can't build images, always with the same error:

```bash
Failed to decode response: zlib_decode(): data error
```

This error is raised after "composer update" command.

I build the same Dockerfile in my local machine without errors.

**Comment by pchico83** [comment]
@vrubiella might I have the repo name?

**Comment by vrubiella** [comment]
hello! all repositories are private ...

**Comment by vrubiella** [comment]
I have the same problems with all repos, were I push images directory with docker push command.

**Comment by pchico83** [comment]
@vrubiella can I still have the repo name? or a build code where this error happened?

**Comment by vrubiella** [comment]
sorry @pchico83 i don't read your answer. 

Error commented previously, was launched after pulling images, buy I you try to build several times from web platform, finally it worked fine.  

Currently I'm building docker images locally/jenkins and push created image to dockerhub.

Building errors only on dockerhud and extremely slow building time forces me to this change.
