### ISSUE TITLE
is there a list of ips we can whitelist to?

### ISSUE THREAD

**Issue by hinling-ihealthlabs** [docker/hub-feedback#1058]
We need to set up a proxy server for our client and the proxy server only allows inbound traffic from https://index.docker.io . So for all the other instances, when it does `docker pull`, they will be going through the proxy server. I did a little googling and found an old post on stackoverflow about this: 
https://stackoverflow.com/questions/25399671/add-dockerhub-ip-addresses-on-whitelist

Is this still the case? Do you guys have something like github (https://help.github.com/articles/github-s-ip-addresses/) where I can just whitelist a CIDR block instead of all the possible ELB ips (http://docs.aws.amazon.com/general/latest/gr/aws-ip-ranges.html)?

**Comment by ace03uec** [comment]
Hey Folks! I see two conflicting messages in the following.

- https://success.docker.com/article/is-there-a-whitelist-of-ips-used-by-docker-hub
- https://success.docker.com/article/does-docker-cloud-have-a-list-of-ip-addresses-that-we-can-whitelist-on-our-firewall

Is it possible to confirm this one way or the other ? Also, what is Docker's recommended way to go forward if a whitelist needs to be setup ?
