### ISSUE TITLE
Unable to link AWS account with docker cloud

### ISSUE THREAD

**Issue by jarkt** [docker/hub-feedback#1062]
I have created the role "dockercloud-swarm-role" and added the inline policy "dockercloud-swarm-policy".
When I want to add the ARN in docker cloud, I only get the error message "Invalid AWS role or insufficient permissions".
As external ID I've used my docker user name.

Everything as described here: https://docs.docker.com/docker-cloud/cloud-swarm/link-aws-swarm/

**Comment by jarkt** [comment]
Ok, I have not read the note. That's a new step for new accounts.

> Note: Your AWS account must support EC2-VPC in order to deploy swarms, and you must also have an SSH key in each AWS region you will deploy swarms in.

**Comment by FabioBentoLuiz** [comment]
> As external ID I've used my docker user name.

That solved my problem. Thanks!

**Comment by srkadiyala** [comment]
Thanks @FabioBentoLuiz 

Your posting saved my time, and it fixed my same issue when I used my Docker cloud login ID as External ID.

**Comment by mokio8** [comment]
I have tried using both my userid and the id of my org and I'm still unable to link my AWS account.

**Comment by smokinjoe** [comment]
@jarkt where'd you find that Note? I'm running into a `Invalid AWS role or insufficient permissions` error and am going crazy trying to troubleshoot this.

**Comment by jarkt** [comment]
It's part of the official doc - linked above.

**Comment by smokinjoe** [comment]
Oh my god. It was right in front of me.

Thanks a ton!

**Comment by prashkotak** [comment]
Hello i have still same problem  my docker cloud id is prashkotak . Can you plese help me .
I have follow the documents as described

**Comment by jtara1** [comment]
ExternalId had to be my org id / name, not my username on docker cloud. It's easy to edit the trust relationship though.
