### ISSUE TITLE
Cannot add automated build for org owned repo on limited access GH token

### ISSUE THREAD

**Issue by farcaller** [docker/hub-feedback#1064]
I've added a Github token with limited access, and now I'm trying to set up a docker hub automated build of one of my org repos (repo is public) in docker hub org (public as well).

When I get to the `https://hub.docker.com/add/automated-build/farcaller/github/orgs/` step, the only account listed is myself (`farcaller`) and there are no github orgs I'm member of in the list.

I assume this is a bug, given docs describe this use case. Can you confirm?

If it's not a bug, what's a proper flow to add a public org repo to public build without giving docker hub full access token?

**Comment by tobiasbrunner** [comment]
This is a duplicate of #590. Strange nothing has been done about this yet.
