### ISSUE TITLE
Unable to reset password - email not arriving

### ISSUE THREAD

**Issue by mspanc** [docker/hub-feedback#1065]
I am trying to reset password to my docker account using the following address

https://id.docker.com/reset-password/?service=43f17c5f-9ba4-4f13-853d-9d0074e349a7

but the e-mail for password reset is never arriving.

I am using e-mail that was registered on hub.docker.com in 01.2016 and I still have e-mail sent from docker after account creation to the exact address I am typing in the form.

The e-mail is hosted on google apps, I've checked spam etc. - the message just does not arrive.

**Comment by christopherhex** [comment]
I am currently facing the same issue for two accounts (work and personal), both use gmail for mail. 

@mspanc, were you able to reset eventually?

**Comment by Deadolus** [comment]
I have the same issue - also for two unrelated E-mail accounts

**Comment by dantebarba** [comment]
Same here

**Comment by logicethos** [comment]
Did you complete the registration? It occurred to me, I gave up waiting for the confirmation e-mail, and now having come back, I cant login, or reset.

I sent them a request here https://success.docker.com/Support but no reply

**Comment by mspanc** [comment]
Yes I was just typing wrong email :)
