### ISSUE TITLE
Creating automated build from github fails: VCS repository name cannot exceed 50 chars

### ISSUE THREAD

**Issue by tobilarscheid** [docker/hub-feedback#1073]
Hi,

I am trying to set up an automated build for one of my projects: https://github.com/larscheid-schmitzhermes/prometheus-filesystem-exporter

The creation silently fails at https://hub.docker.com/add/automated-build/github/form/larscheid-schmitzhermes/prometheus-filesystem-exporter/?namespace=tobiaslarscheid (the final creation form). When I check out my browsers network tab I see that a `POST` request to `autobuild` fails with status code `400` and the reponse is `{"detail": {"vcs_repo_name": ["VCS repository name cannot exceed 50 chars"]}}`.

I think at least one of two things is entirely wrong:

- **The error message is not showing in the UI**
- **Why is the limit so arbitrarily low?** It feels strange that I can create a repository in github and the dockerhub stops me from actually building it.

**Comment by mspanc** [comment]
The same for me.

**Comment by jufemaiz** [comment]
Ditto. We just hit this. Only debugging console showed what the actual problem is…

**Comment by MihaiBogdanEugen** [comment]
Same for me...

**Comment by nico-herbig** [comment]
The same for me. 50 chars is really low. So please increase it.

**Comment by christophefromparis** [comment]
Same limitation for me!
