### ISSUE TITLE
Github Link Limited Access == Read/Write?

### ISSUE THREAD

**Issue by bannsec** [docker/hub-feedback#1079]
New to using docker hub, just set up an account. I went to link in my Github account and selected the "Limited Access" method, which claimed to only have read access. The link-up went fine, however when I went back to check that "Connect to Github" page, it claimed that it had Read/Write access to my account.

The issue is either, I'm being mislead by the icon saying "Read/Write", or I'm being mislead by the "Limited Account" actually getting read/write.

Also, I immediately unlinked the accounts (didn't want to give write access), however when I attempt limited again, I now get error messages:

```
There was a security error during the github account linking process.
```

EDIT: Just checked my Github account and it says it authorize Read only. So likely the description for the Icon on that link-up page was incorrect.

It's interesting to see that when I unlink my account using Docker, my OAuth key actually doesn't get removed from my github account... This seems like another problem.

**Comment by evillemez** [comment]
I may have a similar issue?  I unlinked my account accidentally when setting it up initially, and how I continually get the same `There was a security error during the github account linking process.` errors when I try to re-link it.

**Comment by Owlz** [comment]
I got past that by manually removing the keys from github. It appears
docker doesn't remove those keys correctly.
