### ISSUE TITLE
Push fails to index.docker.hub because tag does not exist

### ISSUE THREAD

**Issue by vindevoy** [docker/hub-feedback#1080]
I have an automated build that worked fine in 2 branches.  The sources are pulled from my github account.  Today I parameterized my script a bit more so I now need to use arguments in my build.  I created a hooks/build file.  The build goes well, but when the push to the repo is done, I get an error saying the tag does not exist, whereas it does.  At least, I can do a pull in Kitematic on the tag(s).  So I have no idea why this fails.  Extract from the logs below.

Sources on
https://hub.docker.com/r/vindevoy/debian-oraclejdk18/
and
https://github.com/vindevoy/dockerhub-debian-oraclejdk18

All is public.

Extract:

Successfully built 3fa1fdd9b471

Pushing index.docker.io/vindevoy/debian-oraclejdk18:develop...
Push failed. Attempt 2 in 60 seconds.
Push failed. Attempt 3 in 60 seconds.
Push failed. Attempt 4 in 60 seconds.
Push failed. Attempt 5 in 60 seconds.
{u'message': u'tag does not exist: vindevoy/debian-oraclejdk18:develop'}

**Comment by vindevoy** [comment]
I have already pushed my master branch, which links to latest, and that one works.  

Successfully built 7b43e337f8ed

Pushing index.docker.io/vindevoy/debian-oraclejdk18:latest...
Done!
Build finished

**Comment by vindevoy** [comment]
I guess this was not picked up.  Anybody reading ?

**Comment by eltiare** [comment]
I'm getting this error message from a private repo and I don't even know what it means.

**Comment by eltiare** [comment]
Classic me: I figure it out right after posting a message. In my case it meant the tag didn't exist on my local machine to push. 'Twas a typo.
