### ISSUE TITLE
Unable to pull images from docker hub it hangs at"verifying Checksum"

### ISSUE THREAD

**Issue by syndy1989** [docker/hub-feedback#1082]
Docker Version:
`PS C:\Users\Administrator\Documents> docker version
Client:
 Version:      17.03.1-ee-3
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   3fcee33
 Built:        Thu Mar 30 19:31:22 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.03.1-ee-3
 API version:  1.27 (minimum version 1.24)
 Go version:   go1.7.5
 Git commit:   3fcee33
 Built:        Thu Mar 30 19:31:22 2017
 OS/Arch:      windows/amd64
 Experimental: false`

`**OS Version**: Windows Server 2016`

I'm trying to pull my docker image from docker hub. it says "verifying checksum" and hangs 
Here is what i get:
`
[ec2-35-158-247-43.eu-central-1.compute.amazonaws.com]: PS C:\Users\Administrator\Documents> docker pull 474614/my_repo:Accessibility
Accessibility: Pulling from 474614/my_repo
3889bb8d808b: Pulling fs layer
1a106d48ef90: Pulling fs layer
eee6c1981d83: Pulling fs layer
04e06fdc0b20: Pulling fs layer
a16424b3ed95: Pulling fs layer
cbbfbc8f6397: Pulling fs layer
3eb28a462618: Pulling fs layer
322c0d94a46c: Pulling fs layer
39563ec257b4: Pulling fs layer
b0a659160b2c: Pulling fs layer
b165db76f031: Pulling fs layer
8559b660d824: Pulling fs layer
a7d700af550f: Pulling fs layer
8e2e442b61a2: Pulling fs layer
5c434d4684c7: Pulling fs layer
04e06fdc0b20: Waiting
a16424b3ed95: Waiting
cbbfbc8f6397: Waiting
3eb28a462618: Waiting
322c0d94a46c: Waiting
39563ec257b4: Waiting
b0a659160b2c: Waiting
b165db76f031: Waiting
8559b660d824: Waiting
a7d700af550f: Waiting
8e2e442b61a2: Waiting
5c434d4684c7: Waiting
eee6c1981d83: Verifying Checksum
eee6c1981d83: Download complete
04e06fdc0b20: Verifying Checksum
04e06fdc0b20: Download complete
a16424b3ed95: Verifying Checksum
a16424b3ed95: Download complete
cbbfbc8f6397: Verifying Checksum
cbbfbc8f6397: Download complete
3eb28a462618: Verifying Checksum
3eb28a462618: Download complete
322c0d94a46c: Verifying Checksum
322c0d94a46c: Download complete
39563ec257b4: Verifying Checksum
39563ec257b4: Download complete
b0a659160b2c: Verifying Checksum
b0a659160b2c: Download complete
b165db76f031: Verifying Checksum
b165db76f031: Download complete
8559b660d824: Verifying Checksum
8559b660d824: Download complete
a7d700af550f: Verifying Checksum
a7d700af550f: Download complete
8e2e442b61a2: Verifying Checksum
8e2e442b61a2: Download complete
5c434d4684c7: Verifying Checksum
5c434d4684c7: Download complete
1a106d48ef90: Verifying Checksum
1a106d48ef90: Download complete`

it won't proceed further. Any advise on this would be helpful

**Comment by zored** [comment]
Have the same error on Unix-server. Have you found any solution?
