### ISSUE TITLE
Forgot email to account. How can I recover it?

### ISSUE THREAD

**Issue by ferrerluis** [docker/hub-feedback#1083]
While working at Rigor, I created the `rigor` Docker Hub account. Now I forgot the email I used for it and they need the credentials. Is there any other authentication methods or any way I can get back into the account?

Thanks!

**Comment by kizbitz** [comment]
Hi @ferrerluis,

Could you have an admin open a request using the customer service form on this page. We'll get them taken care of: https://success.docker.com/Support

Thanks,

**Comment by artodeschini** [comment]
I lost my user's password but I changed jobs and I no longer have access to the original email, is there any way to recover my old account?
