### ISSUE TITLE
docker login failed

### ISSUE THREAD

**Issue by jq2252** [docker/hub-feedback#1084]
I use docker in windows 10. 
When I run
```
docker login
```
after I input username and password, it failed, the log is as following:
```
Error response from daemon: Get https://registry-1.docker.io/v2/: unauthorized: incorrect username or password
```
But I can use the username and password to login in by the website.

**Comment by migolo** [comment]
I have the same issue but on docker for Mac the symptom is the same, I cannot pull images.

Diagnostic ID 5009AB4A-6538-43BC-A1CD-24BD94A51FC5
