### ISSUE TITLE
Docker drive sharing blocked by Avast Firewall

### ISSUE THREAD

**Issue by avinashs95** [docker/hub-feedback#1088]
Docker Community Edition
Version 17.03.1-ce-win12 (12058)
Channel: stable
d1db126

I'm using Avast Internet Security (17.4.2294). Its firewall is blocking the drive sharing in Docker. Hence I am unable to use certain containers. I have to manually disable the firewall everytime when I use docker. If I don't I would get the following error,

> ERROR: for s3  Cannot create container for service s3: D: drive is not shared. Please share it in Docker for Windows Settings

Is there any exception rule that I could add in Avast Firewall, so that it excludes the Docker drive sharing permanently?

**Comment by lucaball** [comment]
Does your firewall allows the Docker Connections? You can look it up in Protection > Application Settings > Docker Inc.
![capture](https://user-images.githubusercontent.com/14766126/27809134-53cf20c6-604d-11e7-9a1b-dcd652aed0ce.PNG)

**Comment by lucaball** [comment]
Also make sure the Firewall Profile of your connection is set to "Private". Otherwise Avast will block sharing drives.
![capture](https://user-images.githubusercontent.com/14766126/27824799-f290b336-60ad-11e7-9c26-7ee0955d464a.PNG)

**Comment by avinashs95** [comment]
@lucaball Thank you very much. Making DockerNAT Adapter connection as "Private" did the trick. The drive sharing is working now.
