### ISSUE TITLE
Avoiding recursive cloning

### ISSUE THREAD

**Issue by qnzhou** [docker/hub-feedback#1089]
It seems dockerhub's auto build service clones the git repo before executing `dockerfile`.  I am wondering if there is any way to avoid cloning recursively since some of my git submodules also contain other (possibly duplicated) submodules.  Cloning the entire dependency tree is expensive and redundant.  Thanks a lot!

**Comment by qnzhou** [comment]
I just want to follow up on this issue to see if there is any walk around.

**Comment by edmcman** [comment]
I would also like to be able to disable recursive cloning

**Comment by Geod24** [comment]
Any update on this ? The lack of configuration for docker hub makes it very hard to use. Especially working with submodules, things tend to fail without adding a bit of boilerplate (e.g. [this issue](https://stackoverflow.com/questions/54055666/docker-hub-and-git-submodules)).
