### ISSUE TITLE
How do I update hub account with my email address if the account is brand new and hasn't been verified via email yet?

### ISSUE THREAD

**Issue by ajileso** [docker/hub-feedback#1091]
Ok, I made a mistake during my docker hub registration by using a non existing email address `xxx@yahoo.com` but I should have used the correct email address `xxx@yahoo.co.uk`

It is painful that Yahoo! won't deliver mail to my mailbox even though I can sign into the `.com` account

It is more painful that Docker hub would not allow me to change my account details because I haven't authenticated the email account. When I try to create a new account with the correct email address I get told that the username has already been taken. I want my username please!

**Comment by ahmni01** [comment]
I made the same mistake as well, I don't want to lose my userid and re-register. Looking forward to a solution for this problem.

**Comment by kizbitz** [comment]
Hi @ajileso and @ahmni01 - You can submit your details and the changes you want using the customer service form on this page and we'll get you taken care of: https://success.docker.com/Support

Thanks,

Jerry
