### ISSUE TITLE
web login to docker hub failed

### ISSUE THREAD

**Issue by rxnzero** [docker/hub-feedback#1092]
web login to docker hub failed (https://id.docker.com/login/)
message - An internal error has occured
but login with command is success.
![image](https://user-images.githubusercontent.com/26912743/27890998-bc11399a-6231-11e7-97c8-f788ba320718.png)

**Comment by fabianomenegidio** [comment]
At least I already know it's not just with my user:

https://github.com/docker/hub-feedback/issues/1093
