### ISSUE TITLE
How to retag an existing image via Rest API

### ISSUE THREAD

**Issue by pasali** [docker/hub-feedback#1096]
Steps i follow:
 
    $ TOKEN="$(curl -sSL -u user:pass "https://auth.docker.io/token?service=registry.docker.io&scope=repository:$REPO::pull,push" | jq --raw-output .token)"

    $ curl -i -H "Authorization: Bearer $TOKEN" -H "Accept: application/vnd.docker.distribution.manifest.v2+json"  https://registry-1.docker.io/v2/$REPO/manifests/latest > manifest.json

    $ curl -i -XPUT -H "Authorization: Bearer $TOKEN" -H "Content-type: application/vnd.docker.distribution.manifest.v2+json"  https://registry-1.docker.io/v2/$REPO/manifests/latest --data @manifest.json

And response of the last curl request is:

    {"errors":[{"code":"MANIFEST_INVALID","message":"manifest invalid","detail":{"Offset":1}}]}

I couldn't figure out how to do this by just reading docs. In the docs says if you put a manifest under a new tag then it will create a new tag for image. But it just doesn't work for me.

**Comment by lukasheinrich** [comment]
What was the solution of this? I see the same issue, but without a detail message in the error

```
{"errors":[{"code":"MANIFEST_INVALID","message":"manifest invalid","detail":{}}]}
```

**Comment by pasali** [comment]
curl -s -H "Authorization: Bearer $TOKEN" -H "Accept: application/vnd.docker.distribution.manifest.v2+json" https://index.docker.io/v2/$REPOSITORY/manifests/latest > manifest.json

after this request, whats your manifest.json look like ?

**Comment by lukasheinrich** [comment]
It's a v2 manifest:

[manifest.json.txt](https://github.com/docker/hub-feedback/files/1222203/manifest.json.txt)

**Comment by pasali** [comment]
@lukasheinrich in my case it was malformed manifest file. I think you should `https://registry-1.docker.io/v2` endpoint  instead of `https://index.docker.io/v2`.

**Comment by joshdk** [comment]
This thread was closed over a year ago, but if it's helpful to anyone in the future,
I wrote [joshdk/docker-retag](https://github.com/joshdk/docker-retag) to solve this specific problem.

Cheers!
