### ISSUE TITLE
Error unauthorized: incorrect username or password 

### ISSUE THREAD

**Issue by chespinoza** [docker/hub-feedback#1098]
Step 1/4 : FROM bitnami/minideb:stretch
Get https://registry-1.docker.io/v2/bitnami/minideb/manifests/stretch: unauthorized: incorrect username or password

```
Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:31:53 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:51:55 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

and also I can't login with my credentials using:
`docker login`
`Error response from daemon: Get https://registry-1.docker.io/v2/: unauthorized: incorrect username or password`

But I can login to https://hub.docker.com with the same credentials.

**Comment by edouardr** [comment]
Try:
`$ docker logout`

**Comment by chespinoza** [comment]
@edouardr  I've already tried that without success, I get the same error.

**Comment by zzzzail** [comment]
I also hava this problam

```
docker login
Login with your Docker ID to push and pull images from Docker Hub. If you don't have a Docker ID, head over to https://hub.docker.com to create one.
Username (zzzzail.mail@gmail.com):
Password:
Error response from daemon: Get https://registry-1.docker.io/v2/: unauthorized: incorrect username or password
```

```
➜  docker docker build .
Sending build context to Docker daemon   5.12kB
Step 1/12 : FROM node
Get https://registry-1.docker.io/v2/library/node/manifests/latest: unauthorized: incorrect username or password
```

**Comment by Gonkers** [comment]
I've been trying the to follow the [tutorial](https://docs.docker.com/get-started/part2/) and it's broken...
when I run `docker build -t friendlyhello .` I get 
> Get https://registry-1.docker.io/v2/library/python/manifests/2.7-slim: unauthorized: incorrect username or password

When I skip ahead in the tutorial and attempt to login with `docker login` I get a new wonderful error...
> Error response from daemon: Get https://registry-1.docker.io/v2/: unauthorized: incorrect username or password

**Comment by dutchakdev** [comment]
+1

**Comment by sonlichao** [comment]
+1

**Comment by DiveInto** [comment]
+1

**Comment by thaJeztah** [comment]
Be aware that logging in on the commandline requires your _username_, not _email address_

**Comment by Pathel** [comment]
Also getting this, trying to download the official mysql container.  Login/logout fixes it only once.  The next attempt to do an image fails again.

**Comment by SDShooter** [comment]
I had the same problem.. Login failed consistently using cli 'docker login user@domain.com'  The problem, as a couple people have pointed out is that you should use 'docker login user' without the @domain.com.  

I was banging my head on desk over this for several minutes, after repeatedly verifying that the typed credentials worked fine on hub.docker.com

**Comment by rijans** [comment]
In CLI, your Docker ID is your Docker username, not email. You can login to Docker site with your email and pass, and then from top-right corner, you can get docker ID/Username. Then in CLI, Type the following command:
`docker login
`
Now login with Docker ID and Password

**Comment by emmanuelcu** [comment]
As @edouardr said, you have to log out from your current docker credentials and log in again with the ID and password. After doing that you will be able to pull the images on your device.

**Comment by Soullivaneuh** [comment]
I also got the error here: https://hub.docker.com/r/nexylan/php-dev/builds/bywbpmp7868yeuobdlbnps7/

**Comment by gsagula** [comment]
annoying

**Comment by agafox** [comment]
Getting the same error. Strange thing is that I can login via App but not via CLI

**Comment by jdsampayo** [comment]
I also had the same problem, on hum.docker you can login with your email, but, on Docker CLI, you should avoid the @domain.com and use just your user if you want to login.

**Comment by faltdor** [comment]
I was running this 'docker pull mysql' and got this error : 

Error response from daemon: Get https://registry-1.docker.io/v2/library/mysql/manifests/latest: unauthorized: incorrect username or password 

I solved it just running this command "docker logout"

**Comment by Offerni** [comment]
As @DiveInto and @thaJeztah said, login with username instead of email worked for me!
Thank you guys

**Comment by idelfonsog2** [comment]
**the username is not the same as the first part of your email**

like email: idelfonso123@gmail.com username: idelfonso123❌ it actually was: idelfonso✅, go to hub.docker.com and see the top right-hand corner

**Comment by benzhonghai008** [comment]
check you login id and password again, I came across the same issue, it turned out to be the wrong password.

**Comment by shuchitaprasad** [comment]
I was facing the same issue where I was able to successfully login to website docker.hub.com, but docker cli login failed with invalid credentials, I found my dickered/username and when I logged though this in the cli, it worked for me

**Comment by mi2147** [comment]
docker login
Use "Username" not email.

**Comment by binoybcompany** [comment]
thanks@mi2147 using the username worked.

**Comment by xy83918** [comment]
I have encountered the same problem, and now it has been solved. I use the Windows version, the console has a small icon, right click to log out of the original mailbox login, use the docker id to log in again, you can normally pull resources.

**Comment by charles-cai** [comment]
docker logout solved my problem with other docker file...

**Comment by contactkkiran** [comment]
@ mi2147 docker login with username worked thanks a lot for sharing this useful info

**Comment by amenging** [comment]
I used my username and failed, and I tried `docker -u username -p password`, found that I can't type numbers after `-p`, I have no idea about that, then I changed my password, using letters instead of numbers, it worked...but this error just appeared before I login successed, maybe it was a special case or I did something wrong, after all, if someone has the same problem, you can have a try : )

**Comment by RobertAcksel** [comment]
> Try first:
> `$ docker logout`
> 
> and then pull again. As it is public repo you shouldn't need to login

thx

**Comment by jdjbarrios** [comment]
Hi! I had the same problem; I tried docker login with my docker Id and my password and it did not work. So I decided to change my password from https://hub.docker.com/ and it worked!

**Comment by bobzhen** [comment]
`docker logout`then re-login using your `system user` on mac os

**Comment by hidayatarg** [comment]
> Step 1/4 : FROM bitnami/minideb:stretch
> Get https://registry-1.docker.io/v2/bitnami/minideb/manifests/stretch: unauthorized: incorrect username or password
> 
> ```
> Client:
>  Version:      17.06.0-ce
>  API version:  1.30
>  Go version:   go1.8.3
>  Git commit:   02c1d87
>  Built:        Fri Jun 23 21:31:53 2017
>  OS/Arch:      darwin/amd64
> 
> Server:
>  Version:      17.06.0-ce
>  API version:  1.30 (minimum version 1.12)
>  Go version:   go1.8.3
>  Git commit:   02c1d87
>  Built:        Fri Jun 23 21:51:55 2017
>  OS/Arch:      linux/amd64
>  Experimental: true
> ```
> and also I can't login with my credentials using:
> `docker login`
> `Error response from daemon: Get https://registry-1.docker.io/v2/: unauthorized: incorrect username or password`
> 
> But I can login to https://hub.docker.com with the same credentials.

I solved it run the `docker login` command and enter the credentials

**Comment by hidayatarg** [comment]
Run the docker login command and enter your email and password it will work

**Comment by AkashicSeer** [comment]
It doesn't help that the login form on hub.docker.com is inconsistent. The form says userid but if you enter your user id then it complains that your login information does not match. So to login to hub.docker.com you have to use your username@domain.com. Also the sign up form on hub.docker.com should have a second row to confirm password before submitting to prevent the event of a user entering a password that they did not intend.

**Comment by AkashicSeer** [comment]
And here is another beautiful pain ITA. If you created your user name with any uppercase characters then those characters are apparently automagically converted to lowercase in the hub.docker.com
So if you are following the tutorial and the user id/name what ever it pretends to call it you use on hub.docker.com is JonhyTwoLegs19 then to login on the command line you would use johnytwolegs19  but to login to hub.docker.com you use johnytwolegs19@domain.com because without the @domain.com it fails ... IS THAT JUST A BIG BALL OF SPECIAL.  This is the problem with open source. No one central planning organization leads to mess. As much as I love open source this is always the case.

**Comment by felipe-altiscale** [comment]
why would docker let me login with my e-mail but only let me pull images if I'm logged using my username? WTF

**Comment by EdDeAlmeidaJr** [comment]
> This is the problem with open source. No one central planning organization leads to mess. As much as I love open source this is always the case, a bowl of spaghetti .

Agreed!

**Comment by andim27** [comment]
Win 10
docker -v
Docker version 18.09.1, build 4c52b90
docker login:
...........
Error response from daemon: Get https://registry-1.docker.io/v2/: unauthorized: incorrect username or password

I can't to solve.
Very bad.Problem still active....
Docker developers should be ashamed...

**Comment by equals215** [comment]
I got the same issue with my Mac, Docker desktop was running and logged in with my email/password combo. I logged out the GUI and logged in with `docker login` in CLI. Everything works fine now.

**Comment by ashutoshbhatt1** [comment]
Yes Same error since yesterday! I am using .travis.yml file and using below command/

"echo "DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin"
ERROR MESSAGE: Error response from daemon: Get https://registry-1.docker.io/v2/: unauthorized: incorrect username or password

Tried everything log out using UI and CLI and login in back but no luck.

**Comment by jayotirana** [comment]
Userid and email address, used to login to docker hub are basically two different things. Userid needs to get the images and not the email.
To resolve this use the following commands on the command line:

1. > docker logout
2. > docker login
and log in with your id (you can find the same on the docker site after logging with email). You will be prompted for the credentials. Enter Userid and then password. 
I did the same and its working for me.

**Comment by SabriJamal** [comment]
@thaJeztah  Cheers! Thanks for specifying that login from command line requires your username and password!! Never had an issue to begin with as I had already set up the docker user group for avoiding to have to sudo to pull images and run docker containers!

**Comment by juztinjames** [comment]
I solved this issue by following.

1. **On Terminal :** run _docker logout_
2. **On Browser :** login into https://hub.docker.com (Login with emailid & password)
3. **On Browser :** Change your current password.
4. **On Browser :** Login into https://hub.docker.com (Use your docker account id (not with your email) and new password).
5. **On Terminal :** run _docker login_ (with your credential used in step 4)
Thats it.. All set.. good to go !!

Following is my terminal commands & output

> ABC-iMac:~ justin$ docker login
> Login with your Docker ID to push and pull images from Docker Hub. If you don't have a Docker ID, head over to https://hub.docker.com to create one.
> Username: fooboocoo
> Password: 
> Login Succeeded

**Comment by JeetuVincent** [comment]
I ran into this same problem. Changing the password and logging in with the Docker ID instead of email worked for me. Hope it helps someone.

**Comment by malah-code** [comment]
> Be aware that logging in on the commandline requires your _username_, not _email address_

This works for me, but why error message not changed to display more useful error message.

**Comment by oveiya** [comment]
Very nice post here thanks for it. I always like and such super content of these post. Excellent and very cool idea and great content of different kinds of valuable information's.
<a href="https://www.gangboard.com/big-data-training/data-science-training?utm_source=backlinks&utm_medium=cmt&utm_campaign=coursepage&utm_term=datascience&utm_content=oveiya">data science online training</a>

**Comment by urielha** [comment]
@juztinjames - Thanks! 
That's worked but no need to change password, I just logged out and logged in only with docker ID

**Comment by xus** [comment]
> Try first:
> `$ docker logout`
> 
> and then pull again. As it is public repo you shouldn't need to login

It works for me, thanks a lot.

**Comment by varg90** [comment]
I faced the same issue, when I tried to use `docker login -u="username" -p="my$strong%password"` one line command but then I tried to `docker login` and answer to `Username:` and `Password:` questions and it works

**Comment by Deninc** [comment]
> I faced the same issue, when I tried to use `docker login -u="username" -p="my$strong%password"` one line command but then I tried to `docker login` and answer to `Username:` and `Password:` questions and it works

Same issue
Docker on Mac 2.3.0.3

**Comment by SushilG96** [comment]
I am facing the same issue, as I can successfully do
`# docker login`
Login Successful
But after that when I try to pull image getting the same issue 
`unauthorized: Invalid Username or Password`

**Comment by Deninc** [comment]
guys @varg90, @SushilG96 
in my case I used single quote like 'password' and it worked

**Comment by proligde** [comment]
I can confirm that is a bug - in my case my (very old) password was either not secure enough or just so old it was not propagated correctly somewhere in the docker hub infrastructure. In the end @juztinjames 's comment solved the issue: Just change your password - then you can log in.

**Comment by nishit93-hub** [comment]
Hi There,

I faced the same issue.

I was deploying Argo-worflow using this manifest file
https://raw.githubusercontent.com/argoproj/argo-workflows/master/manifests/quick-start-postgres.yaml. However minio didn’t came up . It is giving the below error.

`Failed to pull image "minio/minio": rpc error: code = Unknown desc = Error response from daemon: Head "https://registry-1.docker.io/v2/minio/minio/manifests/latest": unauthorized: incorrect username or password
`
Docker version is 20.10.8

What could be the issue, here i am trying to pull image from terminal or by login to any docker registry.

**Comment by equals215** [comment]
> Im here because I was prompted to give access to my keys when a command was attempting to pull a public image with docker. Weather I have a login or not my auth shouldnt be needed for public images.

Are you sure the image name is correct?

**Comment by b-hayes** [comment]
yes, I pulled the image after allowing it access to my outdated credentials.
