### ISSUE TITLE
Cannot create automated build

### ISSUE THREAD

**Issue by markdunning** [docker/hub-feedback#1099]
I have successfully linked my github and dockerhub accounts and am able to begin the setup process to create a new automated build.

I specify a name for the build, enter a description, and hit Create. Nothing happens. The create button changes to Creating for about a second and then goes back to create

![](https://i.imgur.com/gFJdcZf.png)

The github repo I'm trying to build is

https://github.com/bioinformatics-core-shared-training/cruk-summer-school-2017

Any help gratefully accepted

**Comment by cfriedtpv** [comment]
I've run into the same issue. It's incredibly annoying and hangs / is unresponsive more often than it succeeds.

**Comment by stevekm** [comment]
Exact same problem here. It worked fine yesterday.

**Comment by troykinsella** [comment]
Still happening. Any workaround for this?
