### ISSUE TITLE
Better contrast

### ISSUE THREAD

**Issue by ankushagarwal** [docker/hub-feedback#110]
Maybe opinionated, but the contrast of the website can be significantly be improved. The contrast is very less right now

Here is an example :

![image](https://cloud.githubusercontent.com/assets/796949/8321563/53a17fc6-19dd-11e5-9869-ed8f4880abe7.png)

**Comment by jsouth** [comment]
@ankushagarwal - Thank you for the feedback and totally agree.  :)
The overall contrast of hub will be increased for better readability.

**Comment by tiborvass** [comment]
:+1:
