### ISSUE TITLE
Docker images missing after reboot (mac os)

### ISSUE THREAD

**Issue by ghost** [docker/hub-feedback#1100]
I had a few docker images I was working with, and they all disappeared after a forced reboot. Unfortunately, I didn't use docker over the weekend at all, so I'm not sure what information I can give that could help reproduce the issue. I see that this issue has affected a few people over the past year or so, but none of them have been given answers because of a lack of ability to reproduce the issue. Any ideas?

**Comment by dartheide** [comment]
Same here, I lost all images after an forced reboot.
