### ISSUE TITLE
Required to login to pull public images?

### ISSUE THREAD

**Issue by magick93** [docker/hub-feedback#1103]
Why is it that I am required to login to pull a public image, for example:

```
docker pull  wodby/drupal-php:7.1-2.4.4

Please login prior to pull:
Login with your Docker ID to push and pull images from Docker Hub. If you don't have a Docker ID, head over to https://hub.docker.com to create one.
```

I have never had to do this before.

**Comment by Johannestegner** [comment]
I started seeing this a couple of days ago too, but not for all images, and just for some tags on some images.  
  
For example, I could use `FROM alpine:latest` in a Dockerfile but not `FROM alpine:3.6`.   
Is this intended (I mean that we have to be logged in to pull) or is this a bug?

**Comment by v9Chris** [comment]
Had a similar issue halfway through today (pulled several times fine and then all of a sudden...)

```
Step 1/15 : FROM ubuntu:16.04
ERROR: Service 'wagtail' failed to build: Get https://registry-1.docker.io/v2/library/ubuntu/manifests/16.04: unauthorized: incorrect username or password
```

I had to `docker login` to get it to work, never had to login for any repo in the past and not sure why this happened halfway through multiple clean builds.

**Comment by MatMaul** [comment]
Same here. This is really annoying, exceptially with skopeo which just get stuck in this case.
My public image is matmaul/kubernetes-kubelet:test.
One of the problematic layer is 8b56dcf16c5ac86dc93a383f5613d6557415639104ae3d01fc00fb3226125a68 for example.

**Comment by marcusmartins** [comment]
Hi - to help us troubleshoot, can you share your Docker version?

**Comment by MatMaul** [comment]
It was with skopeo and it got stuck on this layer. I saw a 401 in debug mode.
Last skopeo version of f25.
And now of course I can't reproduce. Perhaps some eventual-consistency issues in the ACLs of the layers ?
I'll try to have a more comprehensive test case tomorrow by pushing and trying right after.

Thanks for the feedback.

**Comment by ericcurtin** [comment]
Just got this same issue:

```
>docker pull curtine/sxx:centos6

Please login prior to pull:
Login with your Docker ID to push and pull images from Docker Hub. If you don't have a Docker ID, head over to https://hub.docker.com to create one.
Username (curtine): ^C
> docker version
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:10:54 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:10:54 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Comment by ericcurtin** [comment]
I have to login for every pull at the moment for some reason?

It seemed to start when I changed my dockerhub password..

**Comment by artischocke** [comment]
Same
```
Client:
 Version:	17.12.0-ce
 API version:	1.35
 Go version:	go1.9.2
 Git commit:	c97c6d6
 Built:	Wed Dec 27 20:11:19 2017
 OS/Arch:	linux/amd64

Server:
 Engine:
  Version:	17.12.0-ce
  API version:	1.35 (minimum version 1.12)
  Go version:	go1.9.2
  Git commit:	c97c6d6
  Built:	Wed Dec 27 20:09:53 2017
  OS/Arch:	linux/amd64
  Experimental:	false
```

**Comment by ericcurtin** [comment]
A docker login fixes it... But wonder why you have to login to pull public images

**Comment by adewes** [comment]
For me the problem was that I had an (apparently expired) authentication token in my `~/.docker/config.json` file, which the daemon then tried to use to pull the image from Dockerhub. Deleting the file resolved the problem. If you have the same problem try removing the file.

**Comment by ericcurtin** [comment]
@adewes thanks for the info, I suspect that's what happens in my case the authentication token was not longer valid.

I apologize for repetition but why do yoy need a valid auth token to pull a public image that does not require authentication?

**Comment by adewes** [comment]
@ericcurtin you don't need a valid auth token to pull a public image, but if the Docker client finds an auth token it will probably use it to pull images as I think it can't distinguish between a public and a non-public image on Dockerhub based on the image name/path alone.

You could configure the Docker client to not automatically use a credential from your home directory (https://docs.docker.com/engine/reference/commandline/login/#privileged-user-requirement), by default it seems that it will always use it though when available.

**Comment by ezwebcraft** [comment]
just curious why do docker need login and account info? is this required for CE edition or open source project?

**Comment by kurtfm** [comment]
A quick way to remove the old credential is to run `docker logout` .. if you really need to you can run `docker login` after that.

**Comment by luthor112** [comment]
The same problem still occurs in November 2018 on version 18.09.0.

**Comment by vinchauhan** [comment]
Changes the password for docker hub but the cli still cant access the public images. I tried restarting docker app on windows but still no luck. I new password works on docker hub but not on

docker login

Frustrating...!

**Comment by vinchauhan** [comment]
> Changed the password for docker hub but the cli still cant access the public images. I tried restarting docker app on windows but still no luck. I new password works on docker hub but not on
> 
> docker login
> 
> Frustrating...!

It worked later when I used docker id as username and not email

**Comment by pjmolina** [comment]
```sh
$ docker logout
Not logged in to https://index.docker.io/v1/

$ docker pull portainer
Using default tag: latest
Error response from daemon: pull access denied for portainer, repository does not exist or may require 'docker login'

$ docker version
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a215d7133c34aa18e3b72b4a21fd0c6136
 Built:             Fri Oct 26 23:38:29 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a/18.06.1-ce
  Built:            Fri Oct 26 23:39:57 2018
  OS/Arch:          linux/amd64
  Experimental:     false

$ date --iso-8601=seconds
2018-12-13T15:33:26+0000

$ uname -a
Linux machine1 4.14.72-73.55.amzn2.x86_64 #1 SMP Thu Sep 27 23:37:24 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by DMCHatRally** [comment]
Whether or not logged in, it won't let me pull a public Python image.

**Comment by vinchauhan** [comment]
@DMCHatRally try login with docker username and not email

**Comment by JoshBowdenConcepts** [comment]
I am running into the same issue.

**Comment by FontanyLegall-Brandon** [comment]
Same here 

```
Login with your Docker ID to push and pull images from Docker Hub. If you don't have a Docker ID, head over to https://hub.docker.com to create one.
```

On a pull of a public image ...

**Comment by punkosu** [comment]
I just noticed that if I use "centos7" I get the login error, but "centos:7" works fine.  Just in case someone else runs into this same issue.

**Comment by divadsn** [comment]
As this issue is open, although a solution has been posted, could I suggest maybe adding a fallback, so public images can still be pulled even with an expired auth token?

**Comment by AlbertoMQ** [comment]
This is still an issue

**Comment by ericcurtin** [comment]
I've since moved to podman and quay.io, having great joy! :smile:

**Comment by TheTomer** [comment]
> For me the problem was that I had an (apparently expired) authentication token in my `~/.docker/config.json` file, which the daemon then tried to use to pull the image from Dockerhub. Deleting the file resolved the problem. If you have the same problem try removing the file.

This fixed it for me, thanks!

**Comment by kelaja** [comment]
> For me the problem was that I had an (apparently expired) authentication token in my `~/.docker/config.json` file, which the daemon then tried to use to pull the image from Dockerhub. Deleting the file resolved the problem. If you have the same problem try removing the file.

For me the file `~/.docker/config.json` was recreated by docker after deletion, 
so I dropped  the value in the credStore Variable like this: ```"credsStore":""```

**Comment by bnhmn** [comment]
I had a similar problem. 
I use the "credsStore" "osxkeychain" and had an outdated password saved in the macOS Keychain app. A `docker logout` didn't help.
Opening the macOS Keychain app, finding the password called "Docker Credentials" for docker.io and deleting it solved the problem for me.

**Comment by b-hayes** [comment]
I get there is a workaround but again why does it matter when credentials are not required to pull a public image?
Thats the core issue reported here right?

**Comment by jcarter3** [comment]
Not really, no. On the Docker Hub registry, we have enterprise features that do additional checks and blocks. Business users are able to disable the use of public images for their members. So if credentials are sent, we must validate those _first_ so we can check for additional rules. This will always take priority over public access.

**Comment by b-hayes** [comment]
Ah right that makes more sense. Sounds silly to block something thats public based on auth but I can imagine the use cases.

**Comment by adamatnetrist** [comment]
I realize this is a closed issue, but I'm not sure how to proceed.  I am developing in a secure environment that does not have access to Dockerhub, but uses another private registry to host images.  I can use docker login to authenticate to the private registry, but when I attempt to pull from it I am forced to login to Dockerhub, which obviously fails because I can't reach it.  Is there some way around this?

**Comment by thaJeztah** [comment]
@adamatnetrist neither the CLI nor the docker engine (daemon) should require login to docker hub unless they're trying to pull content from it. There may be some caveats when using image-references that are normalised, e.g. 

- if you're trying to do a `docker run` or  `docker build` `FROM` an image that's tagged locally as `mylocalimage` and that image isn't found locally, the daemon will try to pull it; the `mylocalimage` reference would get normalised to `docker.io/library/mylocalimage:latest` and attempted to be pulled from Docker Hub registry.
- If you run a `docker build` and your Dockerfile contains a `# syntax=xxx` line (e.g. `# syntax=docker/dockerfile:1`) then BuildKit will attempt to download the given dockerfile syntax from Docker Hub.
- Finally, if you're using Docker Desktop, it's possible your Desktop installation is configured to enforce login (there's admin options for companies to enforce this).

If you're able to provide more details, it may be better to open a new ticket with details / steps in which situation you're running into this problem. At least it may be helpful to include errors you're seeing (which may help locate what part is attempting to access docker hub).

**Comment by adamatnetrist** [comment]
Scratch that, found the issue, I was mixing up sudo'd with non-sudo'd commands.  Thank you for the response!

**Comment by thaJeztah** [comment]
Oh! Yes, definitely fell into that issue a few times. `sudo -E` can help for some situations, but yeah, some things are associated with the home-directory (as default), so `sudo` may end up using a different location.

Good to hear it was resolved!
