### ISSUE TITLE
Docker plugins from images - cant pull them to put into a private registry...

### ISSUE THREAD

**Issue by obikay200** [docker/hub-feedback#1104]
when trying to use the weave network plugin i can install with docker plugin install, however when reading the plugin management it sais ....

 "Plugins are distributed as Docker images and can be hosted on Docker Hub or on a private registry."

But how can i down load the image to put on my registry? because i get the following errors

$ docker pull weaveworks/net-plugin:latest_release
Error response from daemon: repository weaveworks/net-plugin not found: does not exist or no pull access

$ docker pull store/weaveworks/net-plugin:latest_release
Error response from daemon: Encountered remote "application/vnd.docker.plugin.v1+json"(plugin) when fetching

I have logged in using my docker hub credentials and it doesnt make a difference.

Any thoughts?

**Comment by dwkerwin** [comment]
Seconded... For production hardening, we don't want to rely on a public repo, so I'm looking for a way to copy a Docker plugin to our private registry.
