### ISSUE TITLE
Automated build setup fails on longer repo names

### ISSUE THREAD

**Issue by raveious** [docker/hub-feedback#1109]
I tried adding an auto build of a repo with a very long name (31 characters) and the Automated Build prompt will not allow you to set it up. The "Create" button will change to "Creating..." and rapidly return to just "Create" with no error what so ever.

My work around was to change the name of the repo on Github to a much shorter name, then enable auto build, and then change the name of the repo back afterwards. Everything _seems_ to be working just fine now...

**Comment by kizbitz** [comment]
Hi @raveious,

Are you using https://hub.docker.com or https://cloud.docker.com when configuring your build?

**Comment by raveious** [comment]
I found this while using https://hub.docker.com, and I don't think https://cloud.docker.com have this issue.

**Comment by raveious** [comment]
I have noticed that cloud.docker.com will still allow you to create the automated build, but it has been nearly 30 mins after I manually triggered a build, and it hasn't updated the build section with a new build yet.
