### ISSUE TITLE
Automated build can't handle HEALTHCHECK flags

### ISSUE THREAD

**Issue by allcloud-johananl** [docker/hub-feedback#1116]
Hi,

We have a client who uses Docker Hub for automated Docker builds.
Recently they added HEALTHCHECK lines to their Dockerfiles similar to the following:

`HEALTHCHECK --start-period=60s --interval=10s --timeout=5s CMD curl http://localhost:8888/healthz || exit 1`

Building locally using Docker 1.12 works fine, however on Docker Hub the build exits with the following error:

`Unknown flag: start-period`

Any assistance would be appreciated.

**Comment by BrainDoctor** [comment]
I got the same error. I then tried it on docker Cloud using Edge 17.05.0-ce and that worked.

**Comment by allcloud-johananl** [comment]
Thanks for the feedback @BrainDoctor.
Could you elaborate what you mean please? Can you tell Docker Cloud which Docker version to use?

**Comment by BrainDoctor** [comment]
Yes exactly. In Docker Cloud, under the "Build" tab there you can configure automated builds. There is a dropdown menu which enables you to select the Docker version. Builds that happen on Docker cloud get pushed to Docker Hub as well. I usually disable the automated build in Hub and let cloud push to hub.  In Hub there is an option "When active, builds will happen automatically on pushes.", which I disable. It still gets updated by Cloud.

**Comment by allcloud-johananl** [comment]
Cool @BrainDoctor, I wasn't aware of that. Currently we're using Docker *Hub* for automated builds and I don't think this option is available there. In any case, this will probably be resolved when Hub's Docker runtime is upgraded. In the meantime we resorted to disabling `HEALTHCHECK` in the Dockerfile and configuring health checks in the orchestrator manifest files.
