### ISSUE TITLE
Build fails on starting MySQL

### ISSUE THREAD

**Issue by vindevoy** [docker/hub-feedback#1117]
I installed an older version (5.5) of MySQL on Debian.  When starting the server with a simple 
RUN /etc/init.d/mysql start
it fails.  It's an automated build on a Github repo.

I see no reason why:
1) It works locally on a Mac OSX.
2) It works locally on a Linux Mint
3) It actually worked before, as I just updated a script
4) When I download the image, with all commands commented out and I do a 'docker exec', I can perfectly start the MySQL daemon.

What command is docker using to build the image that could cause this problem ?
Why is it causing this problem ?  The logs only show "failed".
See: https://hub.docker.com/r/vindevoy/debian-redmine/builds/b43qjhyogjqt3jrhtjvg2eq/

Thanks for any help.

**Comment by vindevoy** [comment]
I removed the MySQL 5.5 package and put the MariaDB-server package.  This works.  The daemon starts without a problem.

Could it be that starting the MySQL 5.5 daemon interferes with another daemon, most likely from MariaDB then ?  I don't really understand why this could be, but that's about my only guess.  That you cannot run both on the same host ?

**Comment by Gariagi** [comment]
I have run into the same issue; I can build the docker image locally but the automated build on docker hub fails: https://hub.docker.com/r/gariagi/kamailio-base/builds/b7acapwmqi9fw8p5jknpipm/
