### ISSUE TITLE
Orphaned organization

### ISSUE THREAD

**Issue by DigitallyBorn** [docker/hub-feedback#1123]
A former intern created a hub organization for our company in an attempt to reserve the name. Now they're gone and, their hub account was tied to their company email, the organization is orphaned. After talking to them, we've tried to recover the password to their account, but we never receive the recovery email to their company address.

Is it possible to recover an organization either by gaining access to this account (with email verification) or by having it killed and recreating it?

**Comment by igortg** [comment]
I'm with a similar problem: my org name is already registered, but I can't know if was someone inside the company, or a random user with same name of my org. hub.docker.com/u/esss  doesn't contain any info about the registration.

Another similar problem was reported 4 months ago on #1004, but no response for Docker Hub support.

**Comment by emaildanwilson** [comment]
I have this issue as well... Is there a way to handle this through a support ticket perhaps? I believe that's the way it works with some other public code sharing projects like npm.
