### ISSUE TITLE
Docker account name squatting

### ISSUE THREAD

**Issue by cogitaria-admin** [docker/hub-feedback#1124]
Went to register an account for a company whose trademark is already being used as a docker account name.  Given that you can search based on the account name this is problematic for a company publishing public docker images.  How do we recover a trademarked account name in general?

Note this is an issue with both **NPM** and **GitHub** accounts and they are very responsive in terms of releasing trademark names to the owner for inactive accounts (immediate release) or for trademark violators (even if actively being used).

**Comment by mrocklin** [comment]
I am also interested in this question.  

Alternatively, is there a way that we can send a message to the person using a particular name?  I'm interested in the name `dask`, which seems to be held but inactive on docker-hub.  Dask is an open source project active in the Python data analytics space.  Historically I've found that people are usually pretty nice about releasing names when I ask them.  Unfortunately I don't see how to go about taking this step.

**Comment by gaboesquivel** [comment]
Hi, I'm also interested in claiming an inactive username

**Comment by m-d-johnson** [comment]
I am also interested in this.

**Comment by ahmadnassri** [comment]
is there any answer to this question? or at least any official support email to contact about such claims?

**Comment by p-s-dev** [comment]
Hello, 

Thank you for contacting Docker Support. 

Please send this request to legal@docker.com. They should be able to better assist you.

If you do not receive a response, please let me know.

Thanks,

Docker Support

**Comment by p-s-dev** [comment]
@mrocklin I have no idea.  I'm not giving advice.  I can not confirm anything.  I'm sharing information about the advice I got from docker support for my own case, regarding the similar topic of dockerhub name squatting.  Your case may or may not be legally relevant, I have no idea.  sorry.

**Comment by mrocklin** [comment]
Ah, I apologize, I only saw the e-mail part of your previous comment, and not the context that it was an e-mail from someone else.  My bad.  Thank you for clarifying!

**Comment by adamkdean** [comment]
This is interesting. When I enquired about an inactive username, I was simply told they can't delete accounts. I'm not asking for an account to be deleted, but I think the GitHub policy of renaming inactive accounts works well.

> Hi,
> 
> Unfortunarely we cannot delete user accounts without the account owners permission, please choose another username.
> 
> Thanks,
> 
> Docker Support
