### ISSUE TITLE
push speed for layers is too slow - even for paying customers

### ISSUE THREAD

**Issue by alexanderkjeldaas** [docker/hub-feedback#1125]
I'm pushing layers through docker hub that are in the 10GB range.  This enables a completely cloud-agnostic setup for me where I no longer need to rely on S3 for storing my stuff.

However, this breaks down with the extremely aggressive traffic shaping that happens on Docker Hub.  Typical transfer rates are 1-2Mbps.

I'm storing maybe 50GB of data and pushing maybe 0.2TB of data per month and pay $7 which isn't much, but for Docker Inc, bandwidth shouldn't cost more than approx $1/TB, and storage around 1c/GB*month.

My point is, if you want to enable a new, better way of deploying and working with data *and* have a profitable business model, at least stop with the traffic shaping of paying customers.  It *should not* be necessary for economic reasons and it definitively doesn't help professional users.

**Comment by vrubiella** [comment]
hello @alexanderkjeldaas pushing and building are extraordinarily slow. We have a paymant plan to.
