### ISSUE TITLE
Cannot pull public images - what's wrong?

### ISSUE THREAD

**Issue by MrBRUE** [docker/hub-feedback#1131]
Hello, 

I am trying to pull an open image and it gives me this error message:
<img width="658" alt="bildschirmfoto 2017-08-13 um 22 09 57" src="https://user-images.githubusercontent.com/16508636/29253137-15cbbfe8-8076-11e7-8b50-a35338d479ae.png">

Could you please give me a hint what is the matter?

Thanks
S.Mo

**Comment by reiz** [comment]
I have the same issue. On one of my machines I just tried to pull from this public repository: https://hub.docker.com/r/versioneye/mongodb/tags/. My pull command was: 

```
docker pull versioneye/mongodb:3.4.6
```

And the error message is: 

```
Error response from daemon: pull access denied for verisoneye/mongodb, repository does not exist or may require 'docker login'
```

Since then I need to be logged in to pull a public repo? That looks like a bug on Docker Hub.

**Comment by 1oglop1** [comment]
I have exactly same problem
Version 17.12.0-ce-mac47 (21805)
docker-compose version 1.18.0, build 8dd22a9

**Comment by artischocke** [comment]
Same
```
Client:
 Version:	17.12.0-ce
 API version:	1.35
 Go version:	go1.9.2
 Git commit:	c97c6d6
 Built:	Wed Dec 27 20:11:19 2017
 OS/Arch:	linux/amd64

Server:
 Engine:
  Version:	17.12.0-ce
  API version:	1.35 (minimum version 1.12)
  Go version:	go1.9.2
  Git commit:	c97c6d6
  Built:	Wed Dec 27 20:09:53 2017
  OS/Arch:	linux/amd64
  Experimental:	false
```

**Comment by docwho76** [comment]
Have the exact same issue too

> Client:
> 
>  Version:       17.12.0-ce
>  API version:   1.35
>  Go version:    go1.9.2
>  Git commit:    c97c6d6
>  Built: Wed Dec 27 20:11:19 2017
>  OS/Arch:       linux/amd64
> 
> Server:
>  Engine:
>   Version:      17.12.0-ce
>   API version:  1.35 (minimum version 1.12)
>   Go version:   go1.9.2
>   Git commit:   c97c6d6
>   Built:        Wed Dec 27 20:09:53 2017
>   OS/Arch:      linux/amd64
>   Experimental: false

**Comment by docwho76** [comment]
HELLO? ANYONE? THIS IS STILL BROKEN.

**Comment by adamwitherspoon** [comment]
If you are logged in to Docker on your local box and can't pull something from https://hub.docker.com/
try LOGGING OUT and re-pulling... I was looking at how the pull URLs were being formed and suddenly just thought this is account related somehow. And it worked for me.

**Comment by Davidian1024** [comment]
I'm seeing this issue as well. I'm logged in and I'm trying to pull the public jpbarto/boto3-docker image. I get the same result for any public image. But I am able to pull official images. I enabled debugging and I see these messages in the system log.

`Mar 30 15:54:49 ip-172-31-28-10 dockerd[9558]: time="2018-03-30T15:54:49.547562252Z" level=debug msg="Calling GET /_ping"
Mar 30 15:54:49 ip-172-31-28-10 dockerd[9558]: time="2018-03-30T15:54:49.548371586Z" level=debug msg="Calling GET /v1.37/info"
Mar 30 15:54:52 ip-172-31-28-10 dockerd[9558]: time="2018-03-30T15:54:52.939167617Z" level=debug msg="Calling POST /v1.37/auth"
Mar 30 15:54:52 ip-172-31-28-10 dockerd[9558]: time="2018-03-30T15:54:52.939861879Z" level=debug msg="form data: {"password":"*****","serveraddress":"https://index.docker.io/v1/\",\"username\":\"davidian1024\"}"
Mar 30 15:54:52 ip-172-31-28-10 dockerd[9558]: time="2018-03-30T15:54:52.940297256Z" level=debug msg="attempting v2 login to registry endpoint https://registry-1.docker.io/v2/"
Mar 30 15:54:54 ip-172-31-28-10 dockerd[9558]: time="2018-03-30T15:54:54.743986956Z" level=debug msg="Calling GET /_ping"
Mar 30 15:54:54 ip-172-31-28-10 dockerd[9558]: time="2018-03-30T15:54:54.745111985Z" level=debug msg="Calling GET /v1.37/info"
Mar 30 15:54:54 ip-172-31-28-10 dockerd[9558]: time="2018-03-30T15:54:54.753453621Z" level=debug msg="Calling POST /v1.37/images/create?fromImage=jpbarto%2Fboto3-docker&tag=latest"
Mar 30 15:54:54 ip-172-31-28-10 dockerd[9558]: time="2018-03-30T15:54:54.753859828Z" level=debug msg="Trying to pull jpbarto/boto3-docker from https://registry-1.docker.io v2"
Mar 30 15:54:54 ip-172-31-28-10 dockerd[9558]: time="2018-03-30T15:54:54.979651292Z" level=error msg="Not continuing with pull after error: errors:\ndenied: requested access to the resource is denied\nunauthorized: authentication required\n"
Mar 30 15:54:54 ip-172-31-28-10 dockerd[9558]: time="2018-03-30T15:54:54.980062011Z" level=info msg="Ignoring extra error returned from registry: unauthorized: authentication required"`

**Comment by shashanktyagi3192** [comment]
Hello, 
I am also facing the same issue for long.

docker: error pulling image configuration: error parsing HTTP 403 response body: invalid character '<' looking for beginning of value: "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>D634D3BBA357D010</RequestId><HostId>xFzYrWzhKFwkVlaPfjPGslggRdsgp6nFEtCJxy0NIB4lWTrVVUwv2q6iUeh7906MrZ+j5YdjE1Y=</HostId></Error>".
See 'docker run --help'.


I have tried doing docker login , upgrading/degrading the docker version.
Need help getting this sorted.

**Comment by jcook793** [comment]
I was having the same issue as @shashanktyagi3192 above, in my situation I was trying to pull an image from within an AWS VPC. Turns out that Docker is hosting their images on S3, and my VPC has an S3 endpoint with a policy attached (which is a good thing). I added this statement to the endpoint policy and then it started working:

```
{
  "Sid": "DockerImageAccess",
  "Effect": "Allow",
  "Principal": "*",
  "Action": "s3:GetObject",
  "Resource": "arn:aws:s3:::docker-images-prod/*"
}
```

Hopefully this helps someone in the future...

**Comment by RomanBush** [comment]
Today is 27 may 2020 and I have same issue. And I have no idea how to resolve this problem.
This is my error:

`May 27 17:06:29 gitlab-runner dockerd[810]: time="2020-05-27T17:06:29.831586238Z" level=error msg="Not continuing with pull after error: errors:\ndenied: requested access to the resource is denied\nunauthorized: authentication required\n"
`

**Comment by RomanBush** [comment]
I resolve my problem. Detail [here](https://stackoverflow.com/questions/62046542/trouble-with-install-configuring-ci-cd/63076373#63076373)
