### ISSUE TITLE
Single save button for Short Description and Full Description

### ISSUE THREAD

**Issue by charlesmims** [docker/hub-feedback#1132]
In the Repo Info section of docker hub, there is a field for Short Description and Full Description.  If you want to fill out both of these -- as I think is probably the way most people would use it -- you have to edit and save one, and then edit and save the other.  If you have entered text into both boxes and then click save on one of them, your changes on the other are lost.  
This could be improved by having a single save button for both of those text fields.

**Comment by pgensler** [comment]
Yes, this has happened to me, as I was making some changes to short description, and adding more detail all my changes were lost. It would be very nice to streamline this.
