### ISSUE TITLE
Docker Hub Servers Farm Location?

### ISSUE THREAD

**Issue by Voolkanus** [docker/hub-feedback#1136]
In order to reduce latency and response times I would like to know where is the physical location of the docker hub servers? I used to work with cloud env. and they all state clearly what is their physical location, however no such information regarding the docker hub.

Thanks in advance!

**Comment by TBK0000** [comment]
From the info on https://status.docker.com/ I found that the Docker Hub DC is NetDC IAD3 Data Center located in Reston, Virginia, USA - http://www.datacentermap.com/usa/virginia/reston/net2ez-iad3.html
