### ISSUE TITLE
404 on repository 'Details' page

### ISSUE THREAD

**Issue by korys** [docker/hub-feedback#1138]
Hi,
I've got one public repo. When trying to go to 'Details' page, I get '404 Page Not Found'.
Repo exists and I can pull/push to it with no issues.

**Comment by piotrkochan** [comment]
+1, every details page - 404. Chrome, Safari

**Comment by joshbodnar** [comment]
This is still an issue.. Can't view any page after clicking on a repository from the search results. "404 Page Not Found" every time. Is there an issue with the URL?
