### ISSUE TITLE
Dockerhub tag trigger looks for branch with tag name failing automated builds

### ISSUE THREAD

**Issue by TheYorkshireDev** [docker/hub-feedback#1145]
Hi all,

I have a couple of automated builds setup which I trigger using the build triggers api. Previous to the upgrade, everything worked fine with my setup of:

<img width="1265" alt="screen shot 2017-08-24 at 21 28 52" src="https://user-images.githubusercontent.com/30004860/29687161-512c855e-8913-11e7-8a36-81d35b5697e4.png">

But now with the exact same configuration the builds fail. As you can see from my setup the build should be on the master branch with the tag matching the regex. However, the error I see `Build failed: please ensure the remote branch exists (128)` implies a change has been made which looks for the branch name matching my tag regex which is not what I configured.

Below is the output of the [build](https://hub.docker.com/r/theyorkshiredev/trigger-dockerhub-build/builds/bfkudcmxy85c8zqmjd2tkrw/)

```
Building in Docker Cloud's infrastructure...
Cloning into '.'...

warning: Could not find remote branch 1.0.0 to clone.

fatal: Remote branch 1.0.0 not found in upstream origin

Unexpected end of command stream

please ensure the remote branch exists (128)
```

**Comment by TheYorkshireDev** [comment]
@pchico83 @pkennedyr I have been following #1039 and ever since the update to dockerhub to allow multi-stage builds my [automated builds](https://hub.docker.com/r/theyorkshiredev/trigger-dockerhub-build/builds/bfkudcmxy85c8zqmjd2tkrw/) have stopped working. Is this a known issue?

@sebagomez also seems to have this issue according to his [stackoverflow](https://stackoverflow.com/questions/45822972/build-failed-please-ensure-the-remote-branch-exists-128)

**Comment by caervs** [comment]
@TheYorkshireDev can you double check the request body you're sending to the trigger? It looks like you're sending

```
{u'source_type': u'Tag', u'source_name': u'0.3.0'}
```

which will not work if the tag does not exist. You'll have to push that tag to github and then a build will automatically be triggered for it.

**Comment by TheYorkshireDev** [comment]
Sorry for the delay @caervs 

I have tried again on another one of my repo's this evening and I am still having the same issue.

Firstly, my github has been tagged as appropriate see below or [here](https://github.com/TheYorkshireDev/npm-container/releases)
<img width="503" alt="screen shot 2017-09-15 at 21 45 39" src="https://user-images.githubusercontent.com/30004860/30502717-566defa0-9a5f-11e7-8ebc-401447823c3a.png">

I then triggered the dockerhub build through the api with the body `{u'source_type': u'Tag', u'source_name': u'1.0.0'}` you can see the api calls below
<img width="1002" alt="screen shot 2017-09-15 at 21 47 15" src="https://user-images.githubusercontent.com/30004860/30502776-8d4403b6-9a5f-11e7-9441-115158e742f3.png">

The builds are picked up within dockerhub (see below or [here)](https://hub.docker.com/r/theyorkshiredev/npm-container/builds/)
<img width="690" alt="screen shot 2017-09-15 at 21 49 47" src="https://user-images.githubusercontent.com/30004860/30502841-dc662302-9a5f-11e7-886b-cb13d969ae85.png">

The tagged image failed because it was looking for the branch rather than the tag (see below or [here](https://hub.docker.com/r/theyorkshiredev/npm-container/builds/b6hxxpg8kohypl5clzcl2h8/))
<img width="1045" alt="screen shot 2017-09-15 at 21 51 26" src="https://user-images.githubusercontent.com/30004860/30502905-12047da6-9a60-11e7-8686-d856de728521.png">

Hopefully, I am not doing something stupid and the info and links i have provided can help you assist me with whats going on.

**Comment by fikipollo** [comment]
I've the same problem here. I'm not able to build my images based on "Tags". Am I doing something wrong?
Same error message:
```
Building in Docker Cloud's infrastructure...
Cloning into '.'...

warning: Could not find remote branch v0.3r1 to clone.

fatal: Remote branch v0.3r1 not found in upstream origin

Unexpected end of command stream

please ensure the remote branch exists (128)
```

![screenshot_2017-09-26_08-42-39](https://user-images.githubusercontent.com/11427394/30846165-d7434f3c-a296-11e7-8366-f31bf069d9d1.png)

![screenshot_2017-09-26_08-43-22](https://user-images.githubusercontent.com/11427394/30846170-dba3db3c-a296-11e7-9271-fe48cc95558d.png)

**Comment by TheYorkshireDev** [comment]
I assume this has been fixed silently, I have recently done quite a few builds using the automated build feature and it is working as intended.
