### ISSUE TITLE
New tag in github project doesn't trigger an automated build in Docker cloud 

### ISSUE THREAD

**Issue by martinyunify** [docker/hub-feedback#1149]
my repo is github.com/yunify/hostnic-cni and I added a new tag v0.8.1 for the project but the new tag doesn't trigger an automated build in docker cloud. 
build rules are as below 

![screencapture-cloud-docker-app-qingcloud-repository-docker-qingcloud-hostnic-cni-builds-edit-1504158871004](https://user-images.githubusercontent.com/26962915/29908471-1f247882-8e54-11e7-9f21-b5c858e44393.png)

I updated rules, deleted tag and added it again but nothing happend. 
I redeliver the event in webhook configuration and nothing happend.

Could you please help me figure out why build rule doens't work? Thanks!

**Comment by zkamvar** [comment]
I am also having this issue
