### ISSUE TITLE
Option needed to flag spam and other inappropriate content

### ISSUE THREAD

**Issue by bmitch3020** [docker/hub-feedback#1152]
I've noticed that spammers are starting to pickup on the Docker Hub comments, e.g. user caramembuatwebsite hit a bunch of repos around 2017-08-22 as can be seen in [this google search result](https://www.google.com/search?q=caramembuatwebsite+site%3Ahub.docker.com&ie=utf-8&oe=utf-8). Affected repos included gitlab/gitlab-ce, gitlab/gitlab-ee, circleci/python, nginxdemos/hello, netflixoss/exhibitor, jetbrains/upsource-analyzer, and puppet/facter. It would be useful if Docker Hub had an option to flag spam posts for an administrator to remove.

**Comment by aelse** [comment]
Noticed this on atlassianlabs/gostatsd too.

**Comment by cswarth** [comment]
Dockerhub user `xanxan813` has porn-spammed the comments,
under https://hub.docker.com/r/_/busybox/ among others.

Just nuke the comment feature if you can't police it.

**Comment by perryprog** [comment]
Nuking the feature sounds like a good idea. Is there someway you could just have a link to the GitHub issues page, or a user defined link to where users should go with questions?

**Comment by zetaron** [comment]
Dockerhub user xanxan8juli postet porn-spamm under https://hub.docker.com/_/maven/.

**Comment by perryprog** [comment]
Seems like an alt to `xanxan813`. Does this mean the Docker Hub team is doing something?

**Comment by thaJeztah** [comment]
I raised an issue internally (based on https://github.com/docker/hub-feedback/issues/1178), and was notified the team was already looking into this (removing the comments section was one option being discussed).

ping @nandhini915  I see some example repositories are mentioned here

**Comment by koalaman** [comment]
I'm getting spam from a user kanzalia on https://hub.docker.com/r/koalaman/shellcheck/

I would also appreciate an option to disable comments for my repo. It seems like it would be simple to implement, and it would reduce pressure on getting moderation features in place.

Also, consider fixing the documentation which claims that flagging is already in place:

>You can interact with other members of the Docker community and maintainers by leaving comments on repositories. If you find any comments that are not appropriate, you can flag them for review.
- https://docs.docker.com/docker-hub/repos/#pushing-a-repository-image-to-docker-hub

**Comment by perryprog** [comment]
ping @nandhini915 re: @koalaman

**Comment by nandhini915** [comment]
FYI - spam comments have been deleted and the spammers deactivated.

**Comment by totalamateurhour** [comment]
user bangipan is spamming https://hub.docker.com/_/oraclelinux/

**Comment by ColinSullivan1** [comment]
FYI, user `senamqq` has spammed https://hub.docker.com/_/nats/  

Cleanup there would be much appreciated, a feature to clean up even more so.

**Comment by cswarth** [comment]
Unfortunately the senamqq user has spams dozens of repos,
https://www.google.com/search?q=site:hub.docker.com+senamqq

**Comment by kizbitz** [comment]
Closing...

**Comment by tianon** [comment]
The "Comments" functionality appears to now be completely gone from Docker Hub, which renders this issue obsolete! :tada: :heart:

**Comment by Rillke** [comment]
> The "Comments" functionality appears to now be completely gone from Docker Hub, which renders this issue obsolete!

Another potentially useful feature gone due to people who can't behave and those who try to monetize just everything.
