### ISSUE TITLE
Docker ubuntu image bash on windows keeps exiting while typing

### ISSUE THREAD

**Issue by satlal** [docker/hub-feedback#1155]
Here is how i created my container:
1. docker run -itd <ubuntu-image>
2. docker exec -it <instanceid> bash
this brings me to bash prompt.
I randomly exit out of bash prompt to my windows command prompt when I type into the terminal.
This happens more consistently when I type fast on the bash prompt.
My machine config : Windows 10 x64 
docker is configured to use: 2 cores and 4gb Memory.

**Comment by caoimhinb** [comment]
Same problem here - whenever I type very fast the shell exits, if I deliberately type slowly it seems to stay open permanently

**Comment by caoimhinb** [comment]
I don't think this belongs in docker/hub-feedback/ though, more than likely a windows specific issue?
 Suggest moving to @docker/for-win

**Comment by ivolucien** [comment]
I have what might be the same issue under ubuntu 17.04, usually happening after I paste text at the container's shell prompt, but sometimes either randomly or possibly just when I type quickly.

Docker version 17.12.0-ce, build c97c6d6

**Comment by Mariusz-Marciniak** [comment]
Also have this issue Engine: 19.03.5
