### ISSUE TITLE
Pull requests for hello-world failing

### ISSUE THREAD

**Issue by ra9hur** [docker/hub-feedback#1160]
Re-installed docker-ce and to test, tried pulling hello-world image from docker. Have consistently been getting this error message for the last 2 days.

--------------
$ sudo docker run hello-world
Unable to find image 'hello-world:latest' locally
latest: Pulling from library/hello-world
b04784fba78d: Pulling fs layer
docker: error pulling image configuration: Get https://dseasb33srnrn.cloudfront.net/registry-v2/docker/registry/v2/blobs/sha256/18/1815c82652c03bfd8644afda26fb184f2ed891d921b20a0703b46768f9755c57/data?Expires=1505122354&Signature=YxyKuU7W~di5tvvik-CvpSzUEJ0bjJWJxhGxTrqvoTIeH2ZnKE08pVSvUfZSHBpZY6YVZZbBmX-0wGmwn~LY8ChTm~H8ta0wBAqEH4CTpGTKs4eZ3g1rhoLLsq0LXiwOVY-mJVhY8O3jiTiL3TmrsSgDnQGE0ZDPnVRtF-PXRuc_&Key-Pair-Id=APKAJECH5M7VWIS5YZ6Q: dial tcp 218.248.255.164:443: i/o timeout.

--------------
Tried dig and seems like OK.

$ dig https://dseasb33srnrn.cloudfront.net

; <<>> DiG 9.10.3-P4-Ubuntu <<>> https://dseasb33srnrn.cloudfront.net
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 62123
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 1, ADDITIONAL: 0

;; QUESTION SECTION:
;https://dseasb33srnrn.cloudfront.net. IN A

;; ANSWER SECTION:
https://dseasb33srnrn.cloudfront.net. 3600 IN CNAME bsnlrpz.
bsnlrpz.        3600    IN    A    218.248.255.164

;; AUTHORITY SECTION:
rpz.blist.org.        3600    IN    SOA    bangalorerdns1.bsnl.co.in.rpz.blist.org. hostmaster.bangalorerdns1.bsnl.co.in.rpz.blist.org. 2017090106 10800 3600 604800 86400

;; Query time: 28 msec
;; SERVER: 127.0.1.1#53(127.0.1.1)
;; WHEN: Mon Sep 11 13:40:24 IST 2017
;; MSG SIZE  rcvd: 177

--------------
$ dig dseasb33srnrn.cloudfront.net 8.8.8.8

; <<>> DiG 9.10.3-P4-Ubuntu <<>> dseasb33srnrn.cloudfront.net 8.8.8.8
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 4132
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 1, ADDITIONAL: 0

;; QUESTION SECTION:
;dseasb33srnrn.cloudfront.net.    IN    A

;; ANSWER SECTION:
dseasb33srnrn.cloudfront.net. 3600 IN    CNAME    bsnlrpz.
bsnlrpz.        3600    IN    A    218.248.255.164

;; AUTHORITY SECTION:
rpz.blist.org.        3600    IN    SOA    bangalorerdns1.bsnl.co.in.rpz.blist.org. hostmaster.bangalorerdns1.bsnl.co.in.rpz.blist.org. 2017090106 10800 3600 604800 86400

;; Query time: 100 msec
;; SERVER: 127.0.1.1#53(127.0.1.1)
;; WHEN: Mon Sep 11 13:37:48 IST 2017
;; MSG SIZE  rcvd: 169

;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 62801
;; flags: qr aa rd ra ad; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1280
;; QUESTION SECTION:
;8.8.8.8.            IN    A

;; ANSWER SECTION:
8.8.8.8.        0    IN    A    8.8.8.8

;; Query time: 0 msec
;; SERVER: 127.0.1.1#53(127.0.1.1)
;; WHEN: Mon Sep 11 13:37:48 IST 2017
;; MSG SIZE  rcvd: 52

--------------
Here is my docker version details

$ sudo docker version

Client:
 Version:      17.06.2-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   cec0b72
 Built:        Tue Sep  5 20:00:17 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.2-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   cec0b72
 Built:        Tue Sep  5 19:59:11 2017
 OS/Arch:      linux/amd64
 Experimental: false
--------------

Have tried restarting docker services. Does not help much.

$ sudo docker login

$ sudo service docker stop
$ sudo service docker start

$ sudo systemctl restart docker
$ sudo systemctl stop docker
$ sudo systemctl start docker
$ sudo systemctl status docker

Status shows that the service has started

--------------

Need your help to resolve this.

**Comment by jabezwinston** [comment]
Thanks a lot ! :) @ra9hur  

I got two  problems solved , one with AWS Console and other with Docker.
Got the clue from your question.
Set your nameserver to 8.8.8.8 or 8.8.4.4 . 
It is the problem with BSNL . It has been nagging me for the past 2 weeks.

**Comment by ra9hur** [comment]
This is resolved, refer:

https://github.com/moby/moby/issues/34813
