### ISSUE TITLE
"incorrect username or password" on automated build process for public image access

### ISSUE THREAD

**Issue by debashisdeb** [docker/hub-feedback#1162]
Trying to pull java:8 , but seeing this error : 

Failed to execute goal com.spotify:docker-maven-plugin:0.4.10:build (build-image) on project myapp: Exception caught: Get https://registry-1.docker.io/v2/library/java/manifests/8: unauthorized: incorrect username or password -> [Help 1]

Have been trying since past 5 hours, still facing the same issue ! Any help ?

**Comment by jrottenberg** [comment]
Same issue for my automated build, I'm pretty sure a re-trigger will 'fix' it , but I have a lot of variants that makes new version very painful to release as one every other 10 is failing ;-/

https://hub.docker.com/r/jrottenberg/ffmpeg/builds/bnki9n7lwne2rwsmdaw92z/

```
GoVersion: go1.8.3
Starting build of index.docker.io/jrottenberg/ffmpeg:3.4-centos...
Step 1/44 : FROM centos:7 AS base

Get https://registry-1.docker.io/v2/library/centos/manifests/7: unauthorized: incorrect username or password
```
