### ISSUE TITLE
Security scanning blocks image publishing, and unable to disable security scanning. 

### ISSUE THREAD

**Issue by tnine** [docker/hub-feedback#1163]
Currently, security scanning is blocking our image from publishing.

<img width="1269" alt="screen shot 2017-09-12 at 7 05 17 pm" src="https://user-images.githubusercontent.com/249532/30354967-5e06ba04-97ed-11e7-8f73-b31f5ff4c8d3.png">

Unfortunately, disabling security scanning in billing settings does not work. Using the Chrome debugger, I'm able to see a 200 response on the PATCH call issued by unselecting the security scanning select box.  However, when I re-visit billing details, the option is re-selected.

**Comment by nandhini915** [comment]
We will look into it. 
Security scanning should not block your image from getting pushed. The image should be available irrespective of security scan success/failure.

Disabling security scan via your UI should've worked. If you still see it turned on, Could you provide your username? we'll look into confirming your security scan cancelation.

**Comment by nandhini915** [comment]
Closing this issue since the Security scanning preview feature has been discontinued as of March 31 '18.

https://success.docker.com/article/scanning-deprecation-faqs contains more details.
