### ISSUE TITLE
When is hooks/post_checkout run?

### ISSUE THREAD

**Issue by bkabrda** [docker/hub-feedback#1166]
Hi,
I have a Github repo where Dockerfile needs to be dynamically generated before building. I don't want to keep the generated file in my repo, since I'd constantly be forgetting to update it before committing. I figured out I could generate it in one of the hooks [1] and then build it.

The problem is that I need to provide a "Dockerfile Location" for an automated build and that file needs to exist otherwise the build fails. The test for existence of the provided dockerfile seems to be carried out even before the `post_checkout` hook, so I have to:

* point "Dockerfile Location" to a `Dockerfile.template` in my repository
* generate `Dockerfile` in `pre_build` hook
* execute `mv Dockerfile Dockerfile.template` to overwrite the template and make Docker Hub build the generated Dockerfile

Would it be possible to change the order of execution, so that the `post_checkout` hook would run *before* checking for existence of file referenced by "Dockerfile Location"? I think this would be much more convenient and would actually make more sense.

Thanks for considering!

[1] https://docs.docker.com/docker-cloud/builds/advanced/#override-build-test-or-push-commands

**Comment by mcamou** [comment]
+1, this would be very useful to us too
