### ISSUE TITLE
login page should auto-focus first input 

### ISSUE THREAD

**Issue by pmario** [docker/hub-feedback#117]
Login page for an existing account. 

If I click the input fields, the name and password animations look nice but imo the overall experience has room for improvement. If I already have an account, there is no need to impress me with animations. ... I want to log in as fast as possible. At the current state the login page hinders me!

to reproduce
- I come from: https://hub-beta.docker.com/
  - I need to click the "Log in" button top right.
- page opens: https://hub-beta.docker.com/login/
  - I need to click the username field, to start typing. <--- extremely inconvenient

expected behaviour 
- as soon as I enter the login page https://hub-beta.docker.com/login/ I want to start typing my name. 
- username field should be active
- no mouse or click interaction should be needed, to start enter the credentials.

I think, there are several advantages: 
- less mouse clicks needed
- For touch users, the on-screen keyboard will be opened automatically without any interaction
- for users, that use password managers, with auto type it would be possible to use the page again. At the moment it's broken. 

There is no problem, if the browser auto-fills the credentials. 

As I wrote, for me there is room for improvement, if real humans, or password managers have to fill the form.

**Comment by ChristopherBiscardi** [comment]
I agree, We *should* be focusing the input by default. I've changed the title of this issue to reflect it being about default focus.

**Comment by thaJeztah** [comment]
Adding an `autofocus` attribute to the input should probably resolve this; https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input

**Comment by pmario** [comment]
IMO the whole login mechanism has changed, so issue is outdated. So I'll close.
