### ISSUE TITLE
Security scan not showing results

### ISSUE THREAD

**Issue by abulford** [docker/hub-feedback#1171]
I've enabled Docker Security Scanning from the "Billing & Plans" page as per [the documentation](https://docs.docker.com/docker-cloud/builds/image-scan/#opt-in-to-docker-security-scanning) but after waiting 7 days I still can't see any scan results.

I feel like I must be doing something wrong but honestly don't know what.  According to the docs it should start scanning as soon as you enable it, or on subsequent pushes.  I could try pushing something else to see if that works but want to check I've not missed something before waiting another 48 hours.

The security scanning is enabled in an Org which I'm an admin of, which is paying for private repositories.

Does anyone have any ideas?

Sorry if this is the wrong place to ask this, I've had no response to my support request via the contact form on the [Support page](https://success.docker.com/Support) and this repo was linked to from the [Help page](https://hub.docker.com/help/).

**Comment by luiz-tavares** [comment]
I'm also having this same issue. I can't see any scanning results, even after waiting for over a week. 
we're also paying for private repositories, and I'm an administrator

**Comment by fareoffice-confluence** [comment]
Strange that this is being promoted openly on the org overview page even though it's apparently broken. really looking forward to an update on this!

**Comment by kribor** [comment]
Strange that this is being promoted openly on the org overview page even though it's apparently broken. really looking forward to an update on this!

**Comment by mihaitodor** [comment]
Not working for me either. Any update on this?

**Comment by erkolson** [comment]
Not working for me on new repositories.

**Comment by cog-qlik** [comment]
I have the same problem too. I can't see any result for the last 3 days even though several images have been pushed to the docker hub.
