### ISSUE TITLE
Sign up page needs to display all lower case requirement for Docker ID

### ISSUE THREAD

**Issue by wouterv4daikin** [docker/hub-feedback#1174]
The account creation page ( https://hub.docker.com/?next=https%3A%2F%2Fhub.docker.com%2F ) allows upper case letters to be used in the Docker ID.

The login page ( https://hub.docker.com/sso/start/?next=https://hub.docker.com/ ), however, does not allow login with a Docker ID that contains upper case letters.

Steps to reproduce:
1. create new account with at least one upper case letter in the Docker ID (e.g. NewTon)
2. try to login to Docker Hub with the credentials created in step 1
3. Failure with "Invalid credentials"

Proposed solution: provide clear warning about allowed characters for the Docker ID on the account creation page.

**Comment by FocusOnFoster** [comment]
Also had this issue. Seems to have finally logged me out today, after a year of being logged in with my ID formatted with capital letters in it. Tried logging in with it formatted all LC on a whim and now  my docker ID shows up in all lowercase in my profile. Seems like a heavy handed move, especially without alerting me that this change would be made...

Quite the headache, and no documentation! When was this change even made?
