### ISSUE TITLE
Password reset mail does not sent

### ISSUE THREAD

**Issue by sd-project** [docker/hub-feedback#1177]
hi, I try to reset my password because login failure (but it is already strange that I should input my password correctly). I enter exact same mail address that I registered when sign up. but mail never sent to my inbox. 

note that I usually use username+service@gmail.com to recognize which service send mail to me correctly. I guess account which has this kind of mail address banned to prevent from farming docker hub account.

**Comment by dbazuin** [comment]
The same thing happens for me with a regular email adress.

**Comment by logicethos** [comment]
Same here.  I cant login. Password reset sends nothing.

**Comment by depohmel** [comment]
Same here. I had to renter my email 6 times waiting for 5 mins between entries. only after that, I got 1.

**Comment by logicethos** [comment]
Did you guys complete the registration?  It occurred to me, I gave up waiting for the confirmation e-mail, and now having come back, I cant login, or reset.

I just sent them a request here https://success.docker.com/Support

**Comment by EternalSH** [comment]
@logicethos did the support fixed that thing for you? 
I am trying to reset my password, but no mail has come since over two days and the support does not seem to respond to tickets.

**Comment by logicethos** [comment]
Yes, but took several attempts to get a reply.  The problem was I had a typo in my e-mail address, so I didn't get the e-mail conformation when setting up a new account.  It left the account in a state of limbo.

**Comment by EternalSH** [comment]
Good to know, thanks!
