### ISSUE TITLE
Unable to select new GitHub organization for automated build

### ISSUE THREAD

**Issue by ntwrkguru** [docker/hub-feedback#1185]
I created a new organization in GitHub but it's not showing up as an option for automated builds. I am the owner of the new organization and can see my other organizations, but not the newest one. What is the "sync" interval?

I did unlink and link my GitHub account, but the issue persists.

**Comment by matzew** [comment]
I have the same issue here

**Comment by chriscohoat** [comment]
If you go into your organization and in the settings and you disable third-party access restrictions:

<img width="756" alt="screenshot 2018-05-29 10 37 38" src="https://user-images.githubusercontent.com/566461/40672645-a0f9c9ae-632c-11e8-86b4-0bc05bd62d59.png">

From there you should be able to view the organization in the Docker Hub.

**Comment by ntwrkguru** [comment]
The issue, @chriscohoat, is the timing of the refresh. It seems to take a day or so before it's usable.

**Comment by Zethson** [comment]
Just ran into the same issue. Couple of years later ^_^
