### ISSUE TITLE
Docker Windows, crash no Hyper V Docker NAT

### ISSUE THREAD

**Issue by 3th3r** [docker/hub-feedback#1190]
Hi,

I've some issue ti run Docker CE, on Windows 10 1703.

After every fresh installation of Docker, it will crash.

crash report:
Unable to create: L’exécution de la commande s’est arrêtée, car la variable de préférence « ErrorActionPreference » ou le paramètre courant a la valeur Stop : Hyper-V n'a trouvé aucun commutateur virtuel portant le nom « DockerNAT ».
à New-Switch, <Aucun fichier> : ligne 131
à <ScriptBlock>, <Aucun fichier> : ligne 385
   à Docker.Backend.HyperV.RunScript(String action, Dictionary`2 parameters) dans C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\HyperV.cs:ligne 177
   à Docker.Backend.ContainerEngine.Linux.Start(Settings settings, String daemonOptions) dans C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:ligne 123
   à Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters) dans C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:ligne 47
   à Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) dans C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:ligne 145

It seems to be a Hyper-V problem, no Docker NAT...

How can I resolve this problem ? I've already try to find some help.

Docker can be a very oowerfull tool, whenn it work ...

**Comment by thaJeztah** [comment]
This issue track is for feedback for Docker Hub; to report issues with Docker for Windows, use https://github.com/docker/for-win/issues
