### ISSUE TITLE
Unable to log in after account creation and activation

### ISSUE THREAD

**Issue by pascaldevink** [docker/hub-feedback#1192]
Steps to reproduce:
1. Create a new account
2. Click the link in the email to active the account
3. Try to log in

An error pops up `Account not active yet. Please check your email to activate your account`, preventing me to log in, even though I _just_ activated the account.

**Operating system**
macOS 10.12.6

**Browser and Browser version**
Safari 11.0

**URL for the page in question.**
https://id.docker.com/login

**Screenshots of the issue (if applicable)**
![screenshot 2017-10-03 14 07 43](https://user-images.githubusercontent.com/106844/31124309-3da57234-a844-11e7-97de-217ca782a062.png)

**Any error messages (on screen or in browser console)**
Account not active yet. Please check your email to activate your account

**The rough date and time the error occurred**
2017-10-03 14:02:00 Europe/Amsterdam

**Your hub username**
ticketswaprambo

**Comment by ArvinB** [comment]
Same issue, how can I get my account activated?

username: cakasky

**Comment by choyongsun** [comment]
go to the http://cloud.docker.com
