### ISSUE TITLE
I removed myself from owner team

### ISSUE THREAD

**Issue by igortg** [docker/hub-feedback#1193]
I was trying to remove a member from the owner team, but the remove button wasn't responding. I kept clicking on it and next thing the entire owner team was gone.

Now I have no more ownership for my org esssdev. Any fix for that?

**Comment by thaJeztah** [comment]
it's best to contact support@docker.com - the support team may have more insight in what happened

**Comment by urugang** [comment]
+1

**Comment by igortg** [comment]
This. Solved with support@docker.com
