### ISSUE TITLE
Unable to pull images in Germany - TLS handshake timeout

### ISSUE THREAD

**Issue by Eddman** [docker/hub-feedback#1195]
We're unable to pull images from docker hub:
```
docker run -it ubuntu /bin/bash
Unable to find image 'ubuntu:latest' locally
docker: Error response from daemon: Get https://registry-1.docker.io/v2/library/ubuntu/manifests/latest: net/http: TLS handshake timeout.
See 'docker run --help'.
```

**Comment by Eddman** [comment]
Seems to be resolved

**Comment by Davidrjx** [comment]
@Eddman i met with same issue, could you please contribute some specific steps

**Comment by Eddman** [comment]
@Davidrjx if I remember correctly it was an error in our local network setup. That day we had multiple network outages....

**Comment by Davidrjx** [comment]
@Eddman, suddenly i realised that our issue may be different though there was same as TLS timeout. in my case, it arose during local private registry deployment, but yet thanks.
