### ISSUE TITLE
unable to push/pull/build docker image 

### ISSUE THREAD

**Issue by pnandi** [docker/hub-feedback#1198]
Error response from daemon: Get https://registry-1.docker.io/v2/: unauthorized: incorrect username or password

**Comment by pnandi** [comment]
$docker login
Login with your Docker ID to push and pull images from Docker Hub. If you don't have a Docker ID, head over to https://hub.docker.com to create one.
Username (nandi.priyabrata@gmail.com): 
Password: 
Error response from daemon: Get https://registry-1.docker.io/v2/: unauthorized: incorrect username or password

**Comment by viniciusgalvao** [comment]
I'm having the same problem here!!

> Error response from daemon: Get https://registry-1.docker.io/v2/: unauthorized: incorrect username or password

**Comment by hguthrie** [comment]
This happened to me as well, but logging in fixed it. If it is still giving you grief, a possible workaround is to use something like Kitematic to pull the image.

**Comment by willgarcia** [comment]
I believe that the CLI only accept a username which is different from email. The email/username both work from the UI though.
