### ISSUE TITLE
responsive-design: menue problems.

### ISSUE THREAD

**Issue by pmario** [docker/hub-feedback#120]
In the responsive views the top menu is inconsistent. Please review the whole responsive design.
It took me about 5 minutes to find all the issues, and much longer to write this issue :/

to reproduce: 
- resize your browser to the following state. about 1400px wide. OK

![github-menu-ok](https://cloud.githubusercontent.com/assets/374655/8395673/6e85ffe2-1d7f-11e5-83cc-25ed499fd31d.gif)
- Select the "Explore" view
- make the width smaller: eg: 1300px ... the right menu goes one row down -> OK

![github-menu-explore-tools-menue-second-row](https://cloud.githubusercontent.com/assets/374655/8395697/21712866-1d80-11e5-82f2-7c1602d51ca1.gif)
- this seems to be ok, but **the "tools" popup has the wrong position**

![github-menu-explore-tools-menue-popup-wrong-position](https://cloud.githubusercontent.com/assets/374655/8395699/2da00b48-1d80-11e5-8fc4-30f00cec64e7.gif)
- select the Dashboard view
- **the top right menu is gone ... imo not ok**

![github-menu-dashboard-menu-gone](https://cloud.githubusercontent.com/assets/374655/8395708/92896cc0-1d80-11e5-93d2-884438d18c8a.gif)

**Comment by pmario** [comment]
Tested with FireFox and Chrome

**Comment by ChristopherBiscardi** [comment]
Thank you for the detailed writeup! It's extremely helpful.

This is essentially a dupe of #46 but I'm going to leave it open since it can be used to highlight a specific instance.
