### ISSUE TITLE
Codalab organization ownership

### ISSUE THREAD

**Issue by ckcollab** [docker/hub-feedback#1200]
Hello!

First of all: thanks for dockerhub/docker, we use it constantly -- has made my life much easier!

I help administrate/run the open source project Codalab.org and we have some images we'd like to put on dockerhub. The problem is the name Codalab was registered by a student some time ago and we cannot get a hold of them. If anyone has some free time, it'd be great if we could get access somehow (eric@ckcollab.com). I am an admin of the Codalab organization on GitHub and the codalab-competitions repo.

Thanks a ton,
Eric

**Comment by thaJeztah** [comment]
Can you try contacting support@docker.com ?

**Comment by ckcollab** [comment]
Will do, thank you.
