### ISSUE TITLE
Unexpected error during builds

### ISSUE THREAD

**Issue by rmb938** [docker/hub-feedback#1203]
Hub Username: rmb938
Hub Org: sandwichcloud
Repo: sandwichcloud/deli-menu

When a build starts it errors with "Unexpected error" and no logs, dockerfile or readme shown.

Example build codes: bpubzpjsyxdcfyjda3tpgqu, bw2nq6caqtwwnrx4pfqbg93, bnpgztq4iegyhewqccvdfym, b4bkbullsi97ezfeihlwedy

There has also been 2 builds that took over an hour to start and hanged until canceled: byl4nw22smfbja6ixbpjvpp, bswmulodnuth7wbxdxnbadk

This image builds locally perfectly fine and I don't see any hub issues in the status page. This has been happening on all builds since 2017-10-10T00:13:01.374Z 

I am assuming there is something wrong with the hub that is not reported in the status page. Any information would be great. :)

**Comment by rmb938** [comment]
Seems fixed now. Would be interesting to know what happened.

**Comment by danvaida** [comment]
FWIW, I’m also experiencing this... will keep an eye on it.

**Comment by mikemoate** [comment]
I'm also seeing this today e.g. https://hub.docker.com/r/countingup/filebeat-logzio/builds/bf3exwhg3susnwdhf4tp7dv/

**Comment by dis1** [comment]
I have same error

**Comment by mikemoate** [comment]
Nothing on https://status.docker.com, not sure how well the Docker team monitor these issues...

**Comment by phanir-menlo** [comment]
We are facing same error. Anyone have any updates?

**Comment by pchico83** [comment]
The issue should have been fixed by now. Could you confirm?

**Comment by mikemoate** [comment]
https://hub.docker.com/r/countingup/filebeat-logzio/builds/bm7tegckszcdigsykcvw2x7/ was successful for me.

**Comment by phanir-menlo** [comment]
Thanks. Now it is working for me.

**Comment by freignat91** [comment]
I got the same issue now:
https://hub.docker.com/r/axway/elasticsearch-docker-beat/builds/byxehcfyfk3gfl2frrlpjyj/
no log, just error status and "unxepected error" displayed.

**Comment by zaga1** [comment]
We seem to be getting these unexplained issues now on dockerhub.  It all builds locally okay and it built on dockerhub earlier today but no longer.

**Comment by jdavanne** [comment]
Same issue here "unexpected error":
https://hub.docker.com/r/davinci1976/docker-ci/builds/

**Comment by Coffei** [comment]
I am seeing these errors on our private repos too. It doesn't seem to be related to the actual build, since it sometimes builds just fine and sometimes fails with this unhelpful error.
I've tried building the image locally and that works flawlessly.
Additionally, it is an automated build built when a new tag is pushed to the GIT repo. And I see no easy option to restart the build. So, now I have to bump the version, push a new tag and hope the build executes fine this time, doesn't seem right.
It would be great to be able to trigger the build, just like a "branch" automated build, so that we could retry these builds.

**Comment by janhybs** [comment]
I guess the issue is till there, randomly selecting which builds are going to fail. https://hub.docker.com/r/flow123d/flow-libs-dev-dbg/builds/bhfdpguom9eqhbdluwtudmr/ 
Locally everything works fine.

**Comment by rmb938** [comment]
Just to update everyone. Since I opened this issue I have moved away from automated builds on Docker Hub. Instead I build my images in travis (or any other ci tool) and push them to docker hub. It isn't as integrated however it is much faster and more reliable. 

Since this issue has been open since October and others have experienced it with no response from the Docker team I suggest others do the same as I am move your builds elsewhere.

**Comment by rarkins** [comment]
"Unexpected error" happened to me just now too. Docker Hub autobuilds have been very unreliable so far - I'm having serious doubts they can be depended on. As someone mentioned above, the Docker team does not seem to be taking Docker Hub autobuild's reliability seriously. A few days ago many builds were taking hours or timing out and yet the status page still showed green and "fully operational".

**Comment by nancheal** [comment]
it happened to me the hole day,today

**Comment by zdm** [comment]
For me too.

**Comment by rarkins** [comment]
Confirmed mine are still erroring, yet again the Docker status page says fully operational:

![image](https://user-images.githubusercontent.com/6311784/38174177-c2116ff6-35c9-11e8-84d8-b295a5d27a80.png)

**Comment by Zenithar** [comment]
Same for me

**Comment by ChihChiu29** [comment]
Same for me as well, for two different repositories.

**Comment by thawk** [comment]
Same for me.  I tried delete and recreate the build, but no lucky.
https://hub.docker.com/r/thawk/router-guard/builds/bb9a5ctsqbskrhxyqfpwvjc/

**Comment by ritiek** [comment]
I tried again just a few moments ago and it built successfully for me.
https://hub.docker.com/r/ritiek/spotify-downloader/builds/

**Comment by chai2010** [comment]
https://hub.docker.com/r/openpitrix/openpitrix/builds/bo5fxtcamfbgedrcycrkcts/

**Comment by Robinlovelace** [comment]
Mine failed 4 days ago now and no subsequent commits have re-initiated the build process: https://hub.docker.com/r/robinlovelace/geocompr/builds/ - any ideas? Thanks.

**Comment by zdm** [comment]
Build process became slow and unreliable
I think, that docker support must, at least, describe the situation.
If they changed service agreement and public images builds now with
limitations they must inform us.

**Comment by Robinlovelace** [comment]
Heads-up - my docker builds are now working. Many thanks for sorting it.

**Comment by blizzz** [comment]
Experience the same issue today.

**Comment by rarkins** [comment]
Yep, same type of problems again
