### ISSUE TITLE
Hello,  When we use docker pull selenoid/firefox:55.0 version, I got the below error.  selenium.common.exceptions.WebDriverException: Message: TypeError: Given browserVersion [object String] "55.0", but current version is [object String] "55.0.1"

### ISSUE THREAD

**Issue by vedam1** [docker/hub-feedback#1204]
Hello, 

When I use selenoid/firefox:55.0 version, it throws an error below.

ERROR :
selenium.common.exceptions.WebDriverException: Message: TypeError: Given browserVersion [object String] "55.0", but current version is [object String] "55.0.1".

Could you help me out here.

**Comment by thaJeztah** [comment]
This is a support question for a specific image; https://hub.docker.com/r/selenoid/firefox/

You need to contact the person maintaining that image; I see two GitHub repositories mentioned in the readme of that image; I suggest opening an issue there
