### ISSUE TITLE
Unable to unlink github account

### ISSUE THREAD

**Issue by smarzola** [docker/hub-feedback#1206]
Hello, I'd like to link my github account to my personal docker hub account but I'm stuck because my github account is linked to a docker hub account that I don't use (kuldat), and unfortunately I don't recall the password of the old account and the email doesn't exist anymore (I know...). Can someone help me with this?

**Comment by fx-test** [comment]
having same issue

**Comment by w3s7y** [comment]
Same issue.  I linked my personal (primary) github account to a professional (work) docker account.  Now I have left that company (and therefore access to the email and password for the docker account) I cannot un-link my personal github from the old account and re-link it to my current one.

**Comment by tcnichol** [comment]
Same issue.
