### ISSUE TITLE
User must first leave all organizations and groups.

### ISSUE THREAD

**Issue by jadon1979** [docker/hub-feedback#1208]
When I attempt to convert an account to an organization then I get the above message.  According to the UI, my user has no associated orgs/groups.  After verifying there are no visible associations on either side, I'm left with the assumption that there are hidden associations stored in docker hub.  Is there an immediate fix to this?

**Comment by neilpeirce** [comment]
Same here. The user isn't in any groups or organizations according to the UI. Any work around for this?

**Comment by neilpeirce** [comment]
@jadon1979 I found a solution that worked for me. The original user that I was trying to convert to an organization was still in a Team (as an owner). Once I added a new owner to that team and removed the original user it all worked fine.

**Comment by mklarsen** [comment]
It still a problem i can´t convert my personaly- account (mpsoft) into a org. 

(All repos/etc. was handedover to brand new account) but still getting: User must first leave all organizations and groups.

Br.
Martin

**Comment by lozanet2005** [comment]
I have the same issue and both accounts are not part of any team, organization nor group =/

**Comment by steffen-wilke** [comment]
Same issue here.

**Comment by meowsbits** [comment]
Same issue here. The account I wish to convert _was_ a member of an Organization (as Owner), but I've deleted that organization, leaving the account I wish to convert with NO memberships or teams... but the problem persists: 

```
User must first leave all organizations and groups.
```

**Comment by xf4j** [comment]
Same issue here. Any solutions?

**Comment by lcunibertti** [comment]
I have the same issue! Is there any update on this??

**Comment by xf4j** [comment]
It seems it needs to be manually deleted by the Docker team as the "deactivated organization" might still be in their database. I tried to contact them using this https://hub.docker.com/support/contact/; but got no response. Very frustrating!

**Comment by lionafire** [comment]
I have the same problem. I deactivated an old organization that is probably still invisibly blocking the original owner from being upgraded to an organization.
I hate that there is no workaround for this since to my knowledge I have no chance to get access to that deactivated organization nor can I delete it completely.

**Comment by niolap** [comment]
Same issue here.

**Comment by rexhinvorpsi** [comment]
Same here. I mean the issue has been opened for 3 years. Please guys.

**Comment by oscillate123** [comment]
Same issue here, it doesnt work to convert the user account to an organisation account!

`User must first leave all organizations and groups.`

**Comment by idrissneumann** [comment]
Same here and no workaround found...

The user had an organization that was deleted and we need to directly turn this user in an organization.

Here's the user : https://hub.docker.com/u/comworkio

As you can see, he's not a member of an organization right now. And yet:

<img width="910" alt="Screen Shot 2020-12-11 at 11 39 39 AM" src="https://user-images.githubusercontent.com/12884347/101893824-93307080-3ba5-11eb-81f9-1c6887a68ea0.png">

The wanted owner is also not a member of another organization or group.

**Comment by phdleung** [comment]
> Same here and no workaround found...
> 
> The user had an organization that was deleted and we need to directly turn this user in an organization.
> 
> Here's the user : https://hub.docker.com/u/comworkio
> 
> As you can see, he's not a member of an organization right now. And yet:
> 
> <img alt="Screen Shot 2020-12-11 at 11 39 39 AM" width="910" src="https://user-images.githubusercontent.com/12884347/101893824-93307080-3ba5-11eb-81f9-1c6887a68ea0.png">
> 
> The wanted owner is also not a member of another organization or group.

I had the same problem and I fix it removing the account that I was trying to convert from any group/organization, not the new user.

**Comment by rexhinvorpsi** [comment]
Well i got it fixed after writting to support, but it did take a week for them to respond in my case
