### ISSUE TITLE
Create account

### ISSUE THREAD

**Issue by RicardoJSTeixeira** [docker/hub-feedback#1211]
Hi, I created my first ID on docker hub, and gratefully my nickname was free.
But for my blues, I never received the confirmation email nor the the forget password works.
My username is rteixeira and my email rteixeira@gocontact.pt.
Thank you for your attention.

**Comment by bigmeech** [comment]
Experiencing the same issue as well with no straight forward way to reach support. My id is vendex and email is vendexchange@gmail.com

**Comment by ArvinB** [comment]
Same issue here!

**Comment by sharath-yml** [comment]
Same issue here.
This thing sucks.

**Comment by BazaarMunchkin** [comment]
I'm also experiencing the exact same issue with account creation. No confirmation email sent.

**Comment by sharath-yml** [comment]
Someone in the [other thread](https://github.com/docker/hub-feedback/issues/1226) told me to mail my support request to support@docker.com.
I did that, got a support request ticket created yesterday, but no resolution yet to this issue.
