### ISSUE TITLE
Error: We were unable to populate your user namespaces

### ISSUE THREAD

**Issue by wjgilmore** [docker/hub-feedback#1213]
Hi,

I've successfully created and am actively using a container repository on Docker Hub, however all subsequent attempts to create a second repository have failed due to the error presented in the below screenshot. This error occurs when I login to one of my client's Docker Hub accounts and attempt to do the same.

![dockerhub-issue](https://user-images.githubusercontent.com/161522/31675598-1cd6f722-b333-11e7-9383-00c9cfdd77e2.png)

Any ideas? I emailed Docker Support 5 days ago but never heard back. Getting a bit antsy as we'd like to begin working on a new container right away. I'm new to this so maybe I'm doing something wrong? Sure seems straightforward though (in terms of creating a new repository on Docker Hub).

Thank you
Jason

PS. I've confirmed this isn't some strange browser issue. The error occurs on both Chrome and Safari on OS X Sierra.

PPS. Both my account and the client account are currently using the free edition.

**Comment by TimJarvis** [comment]
I am having this same issue, I also have not heard back from docker support. And like you this is also happening on multiple accounts (3)

Did you get any resolution ?

**Comment by Ruud-Zuiderlicht** [comment]
Same here

**Comment by sikanrong** [comment]
same... what the fuck :( very unimpressed by the lack of support
