### ISSUE TITLE
 image operating system "windows" cannot be used on this platform

### ISSUE THREAD

**Issue by dscho** [docker/hub-feedback#1214]
I am trying to set up an automated build, but it seems that Windows containers are not yet supported in that respect? Are there plans to do so?

**Comment by dscho** [comment]
You can see one of the failed builds [here](https://hub.docker.com/r/dscho/git-for-windows-vsts-agent-docker/builds/b5lkryj8rcvdm5zxy4hghhb/).

**Comment by cmeeren** [comment]
@dscho I'm struggling with the same error, but it seems like you got it working - at least there's a tag on your repo. How did you manage it?

**Comment by cmeeren** [comment]
On closer look, it still looks like all your builds still fail. How did you manage that?

**Comment by cmeeren** [comment]
Oh nevermind, I found out I could manually upload an image using `docker push`. Still learning the ropes. 😅 

In any case, it would be great if Docker Hub supported Windows builds.

**Comment by dscho** [comment]
@cmeeren indeed, I pushed my repo manually.

**Comment by cniekerk** [comment]
Has this thread died or are there still people who would like to see automated build support on the Docker Hub for Windows containers? I think this would be good to have.
