### ISSUE TITLE
New account registration confirmation not recieved

### ISSUE THREAD

**Issue by bigmeech** [docker/hub-feedback#1218]
Hi. It seems there has been a growing number of issues related to confirmation emails not being sent to new account openers with no straight forward way to contact support. Does anyone here have status on what is going on?

**Comment by Wes-Skeeter** [comment]
I am having the same issue

**Comment by danielflira** [comment]
the same

**Comment by williamzoop** [comment]
Same here. Docker hub ID is getzoop.
