### ISSUE TITLE
spam on dockerhub

### ISSUE THREAD

**Issue by AgentMeerkat** [docker/hub-feedback#1219]
https://hub.docker.com/r/marysadbrg19681/driversonyxperiaedfa8760/

I came across that repository today. Docker Hub should have a feature that allows a user to flag something as spam or otherwise inappropriate / malicious content. Without a proper reporting mechanism anyone could create a pseudo page using Docker Hub.

**Comment by nandhini915** [comment]
Thank you for reporting this issue.
We've deactivated this user and other spam accounts that bubbled up through our checks.

**Comment by toddkaufmann** [comment]
Here's another spammer:   `https://hub.docker.com/u/lingsuposti300/`

or this command to list them all (21 entries as of now):

    docker search --limit 30 lingsuposti300 | nl -v 0

One of the results popped up in my search for something else.

**Comment by nandhini915** [comment]
Thanks for pointing this out, we'll audit this account and other related accounts and deactivate users.

**Comment by flaviut** [comment]
another one: https://hub.docker.com/u/jydosoj/

**Comment by RattyDAVE** [comment]
Another one to check out. https://hub.docker.com/u/hrrisonblar17r2/

**Comment by mdkv4** [comment]
And another one: https://hub.docker.com/u/aqasigij/

**Comment by nandhini915** [comment]
Thank  you for flagging these repos. We've deactivated these users and are actively monitoring hub for similar spam content.

**Comment by RattyDAVE** [comment]
More...

https://hub.docker.com/u/asocowys/
https://hub.docker.com/u/yanapijy/
https://hub.docker.com/u/kypyyeba/
https://hub.docker.com/u/zigariny/
https://hub.docker.com/u/yepujupu/
https://hub.docker.com/u/gixyk/
https://hub.docker.com/u/yanapijy/

**Comment by nandhini915** [comment]
Thanks for reporting these repos. We've deactivated the repos above and will be going through a deeper cleanup in Jan '18. 
We've also observed a significant increase in spam repos over the last two months (November/December '17) and will be addressing this appropriately.

**Comment by daBONDi** [comment]
Another one:
https://hub.docker.com/u/uqehavo/

**Comment by jsminet** [comment]
Another one: https://hub.docker.com/u/enasopam/

**Comment by ericsmalling** [comment]
Another: https://hub.docker.com/u/eduxyruh/

**Comment by jnsl** [comment]
https://hub.docker.com/u/iwopah/

**Comment by ThauEx** [comment]
https://hub.docker.com/u/tydyweh/

**Comment by nick-andren** [comment]
https://hub.docker.com/u/okificu/

Lots of user names in this issue are 8 character alphabetic strings

**Comment by jackwilsdon** [comment]
https://hub.docker.com/u/sixacohy/

**Comment by SamyCoenen** [comment]
report https://hub.docker.com/u/vygypy/

**Comment by rillig** [comment]
https://hub.docker.com/u/tobake/

**Comment by rillig** [comment]
https://hub.docker.com/r/uledy/how-to-librivox-to-kindle-fire/

**Comment by jackwilsdon** [comment]
You can find a good 4 pages of spam accounts by searching for `iBooks`;

https://hub.docker.com/search/?isAutomated=0&isOfficial=0&page=1&pullCount=0&q=iBooks&starCount=0

**Comment by wawa19933** [comment]
I hope it make sense to report such accounts?
https://hub.docker.com/u/gojewebi/

**Comment by jackwilsdon** [comment]
They do seem to be getting deleted slowly (see mine and @SamyCoenen's links, which are now deleted).

**Comment by jackwilsdon** [comment]
They do seem to be getting deleted slowly (see mine and @SamyCoenen's links, which are now deleted).

**Comment by davidneudorfer** [comment]
@nandhini915 here's another one
https://hub.docker.com/r/obofugiwo/cleanser/

**Comment by lyonzy** [comment]
https://hub.docker.com/u/bellntatexli/

**Comment by eliezerlp** [comment]
https://hub.docker.com/u/vydub/

**Comment by AgentMeerkat** [comment]
https://hub.docker.com/r/ruwawad/brick-windows-activation-crack-2012r2/

**Comment by AgentMeerkat** [comment]
https://hub.docker.com/r/kuosearchnehoch/marlalaza/

**Comment by hamhut1066** [comment]
https://hub.docker.com/r/ulupe

**Comment by AgentMeerkat** [comment]
@hamhut1066 Some basic anti-spam implementations is a good idea. Maintaining a running thread of spam accounts just doesn't scale. @nandhini915 has docker considered a spam filter solution similar to what email providers use?

**Comment by nandhini915** [comment]
@AgentMeerkat ack -- here's what we've been up to over the last two months 
- Adding preventive measures to prevent Bots from signing up 
- Mass removal of content identified as spam from time to time.
- Blacklisting domains known to be malicious
- (Work in progress) Integrating with third anti-spam solutions. We're hoping to roll out some solutions over the next few weeks that should address this issue.

**Comment by hamhut1066** [comment]
@nandhini915 Thanks for the feedback.

I'm sure everyone here would appreciate you linking to any public announcements you make about how you are dealing with this as and when you you make them.

**Comment by peremen** [comment]
Yet another spam using terwa.ru domain: https://hub.docker.com/u/enytesof/

**Comment by nandhini915** [comment]
We've partnered with a third party spam detector, and as of now all known spam repositories have been taken down. 
Incoming repositories are continuously monitored for adult/spam content and moderated appropriately.

**Comment by liias** [comment]
some more:

https://hub.docker.com/u/murraybre1997f4
https://hub.docker.com/u/dnobissnnte1973/
https://hub.docker.com/u/ollndwinge193v9/
https://hub.docker.com/u/deonvhoos1986d1/
https://hub.docker.com/u/oumbusdedeaux8z/
https://hub.docker.com/u/cericmaziz160h6/
https://hub.docker.com/u/fredeistin170a8/

**Comment by BetaLeaf** [comment]
https://hub.docker.com/u/mariya15/

**Comment by hexbus** [comment]
Here's another one... https://hub.docker.com/r/itnemorrself1983/tripp-lite-usa-19hs-driver-download

**Comment by playitforless** [comment]
heres a few more

https://hub.docker.com/u/tairwancuhoofp1977
https://hub.docker.com/u/keletlema
https://hub.docker.com/u/totintipa
https://hub.docker.com/u/clocmachmega1978

**Comment by mkunz7** [comment]
https://hub.docker.com/u/ffenvalebit1988
