### ISSUE TITLE
Docker Hub not saving full description

### ISSUE THREAD

**Issue by pgensler** [docker/hub-feedback#1223]
It appears whenever I try to use Travis or CircleCI, my Full Description for my container is wiped away......

**Comment by pgensler** [comment]
Any way to not have this happen?

**Comment by manishtomar** [comment]
Can you please give more info? What do you mean by "full description of my container"? Do you mean description on repository's Docker Hub page?

**Comment by pgensler** [comment]
Sorry, my container: https://hub.docker.com/r/pgensler/sandboxr/
It seems like every time I push to it, my Full Description on Docker Hub is not saving.

**Comment by manishtomar** [comment]
Pushing an image should not affect the full description. It is only managed by Hub UI. Not docker commands. If you are expecting that it updates it with some kind of README file in the image (like Github) then I am sorry you are mistaken.

**Comment by pgensler** [comment]
I'm not expecting it to have this behaviour, but I've been trying to save contents to the full description, maybe it's too long?

**Comment by manishtomar** [comment]
Do you mean to say that editing full description on the Hub UI does not work? Also, too a description shouldn't be a concern. For example, https://hub.docker.com/_/python/ has pretty long description.

**Comment by pgensler** [comment]
I am saying when I make a long description, the changes are not saved on docker hub. I'm aware of other images that can do this.

**Comment by manishtomar** [comment]
I was able to make change to the description just now. It has `(test from manish)` in the end. Kindly refresh and see. Can you try it once again just now and let me know if you are able to edit it?

**Comment by pgensler** [comment]
Nope.

**Comment by manishtomar** [comment]
From the logs I see that you've pushed an image via `docker push` but it doesn't look like you edited the full description in Hub UI. Just to confirm did you trying doing this http://recordit.co/f1isj0qt6z ? If so, do you see any error on the browser and if possible on the browser console?
