### ISSUE TITLE
No verification email received

### ISSUE THREAD

**Issue by sharath-yml** [docker/hub-feedback#1226]
I just signed up for a new username: sharathyml
It says it has sent a verification email, but I haven't received anything. There is no option to resend verification email as well. It is not even allowing to create a fresh account with a different username.
I am stuck.

**Comment by bigmeech** [comment]
send an email support@docker.com.

They activated my account manually last night. I think they are having internal issues.

**Comment by nomadcalendar** [comment]
same issue, username is nomadcalendar.io

**Comment by RezaRassool** [comment]
same here

**Comment by Amaresheedara** [comment]
i am also having the same issue, user name is : satheesh1980

**Comment by ingshtrom** [comment]
Does [this information](https://github.com/docker/hub-feedback/issues/631#issuecomment-993582213) help you? Specifically, you can log into the site (without your email being verified) and resend the verification email.

**Comment by GaMalhot** [comment]
I am trying to activate my email on Docker hub but I am not able to receive the activation email on my email id. 
my username is : garimadell

Attached is the screenshot of my Docker Hub account.

![image](https://user-images.githubusercontent.com/106246924/177109312-3f0d2369-ef62-4b77-82ab-fa8c04fd0f60.png)
