### ISSUE TITLE
OSSEC rootcheck issues on docker machines

### ISSUE THREAD

**Issue by spencescu** [docker/hub-feedback#1228]
Hello,

We have the following OSSEC alerts on our servers running Docker:

Rule: 510 (level 7) -> 'Host-based anomaly detection event (rootcheck).'
Files hidden inside directory '/var/lib/docker/overlay2/7e2e883984c0f16a8a7c4bd5795fef5111c346fbe755f35a36e9a03149849607/merged/root/.ivy2/cache/com.google'. Link count does not match number of files (3,1).

Is this inherent to how Docker manages these files, and was this reported by other people too?

Thanks,
Sherman

**Comment by mlissner** [comment]
This is very much filed in the wrong place. It's a dup of: https://github.com/ossec/ossec-hids/issues/1855. Suggest closing.
