### ISSUE TITLE
Leave organization?

### ISSUE THREAD

**Issue by davidwaizer** [docker/hub-feedback#1230]
How can I leave an organization in which I am not an admin of?

**Comment by thbar** [comment]
I have this need too. How can we do that on our own without asking the organization admin? This is especially useful for outside contractors after a project is done.

**Comment by dangkaka** [comment]
I need it too

**Comment by kirill-andr** [comment]
Same here!
When Docker will finally fix the absolutely dysfunctional interface?! There is a TON of requests over the years regarding users unable to leave and remove organizations and Docker team seems to incapable to solve it for a number of years.

**Comment by stewartadam** [comment]
+1

**Comment by soupdiver** [comment]
same problem here

**Comment by nynhex** [comment]
Same problem

**Comment by 01e9** [comment]
Come on Docker, you can do it. You will revolutionize UX/UI with this functionality

**Comment by ardeearam** [comment]
+1

**Comment by xandermar** [comment]
+1

**Comment by guivazcabral** [comment]
it's ridiculous that you can't leave organizations. and the fact that you can't even deactivate your account without leaving your organizations (which you can't do) is even more astounding.

**Comment by bcomnes** [comment]
Ran into this today as well.

**Comment by soupdiver** [comment]
Crazy how much this is ignored 😅

**Comment by AlwaysMoreHats** [comment]
Docker, when can we leave organizations?

**Comment by gauthier** [comment]
+1 I'd like to leave an organization too, I can't understand why this should not be possible!

**Comment by Seb33300** [comment]
Here is the solution:

On your Docker account, go to `Organizations` and click on the organization you want to leave.
In the `Members` tab, search for your account and click on the `Leave organization` icon in the last column of the table.

![image](https://user-images.githubusercontent.com/915273/70847186-05d41680-1e94-11ea-9fdd-472d59816d15.png)

**Comment by soupdiver** [comment]
> Here is the solution:
> 
> On your Docker account, go to `Organizations` and click on the organization you want to leave.
> In the `Members` tab, search for your account and click on the `Leave organization` icon in the last column of the table.
> 
> ![image](https://user-images.githubusercontent.com/915273/70847186-05d41680-1e94-11ea-9fdd-472d59816d15.png)

Finally 😂 
Guess this issue can finally be closed
