### ISSUE TITLE
Account ownership questio

### ISSUE THREAD

**Issue by jwagantall** [docker/hub-feedback#1232]
Dear support team, 

I wanted to check with you if it is possible to let me know who is the author of the following spaces please?
https://hub.docker.com/u/onap/
https://hub.docker.com/u/openecomp/

Thank you so much!
Jess

**Comment by thaJeztah** [comment]
May be worth sending an email to support@docker.com, but I'm not sure if they're allowed to share that information.

**Comment by jwagantall** [comment]
Thank you ... will give it a try. 

Thanks!
Jess
