### ISSUE TITLE
Unexpected error

### ISSUE THREAD

**Issue by AbrahamArellano** [docker/hub-feedback#1237]
Hi I have a simple Dockerfile in my repository. However I'm getting an exception: "Unexpected error" without any log information. I already build it before without problems. Not sure what happened. 

My git repo is:
https://github.com/AbrahamArellano/payara-s2i-builder

**Comment by mikemoate** [comment]
See #1203 you aren't the only one suffering with this today.

**Comment by pchico83** [comment]
Fix has just been released
