### ISSUE TITLE
hub doesn't autobuild images anymore

### ISSUE THREAD

**Issue by avoinea** [docker/hub-feedback#1238]
https://hub.docker.com/r/eeacms/kgs/builds/bxxpjtdmzvmcsce6fphm5t/

```
Unexpected error

**Comment by maeb** [comment]
+1 https://hub.docker.com/r/norsknettarkiv/veidemann-api-gateway/builds/bt5b8w6akgmjcpwa8b57sqe/
`unexpected error`

**Comment by mikemoate** [comment]
See #1203 lots of us seeing this today

**Comment by pchico83** [comment]
Fix has just been released
