### ISSUE TITLE
Team members unable to create repos under org namespace?

### ISSUE THREAD

**Issue by 4everinbeta** [docker/hub-feedback#1239]
Hello all- I am new to docker hub and created an organization for my teams to create and manage our docker images. However, I have added several team members to my organization but when they try to create a repo they are only presented with the option of creating one under their personal namespace and not the namespace of our org. What am I messing? I am sure that there is some permissions setting I must have overlooked.

**Comment by nandhini915** [comment]
Hi, you can take a look at https://docs.docker.com/docker-hub/repos/#creating-a-new-repository-on-docker-hub that describes repo permissions.

Under the section `Creating a new repository on Docker Hub`

```
When creating a new repository, you can choose to put it in your Docker ID namespace, or that of any organization that you are in the “Owners” team. The Repository Name will need to be unique in that namespace, can be two to 255 characters, and can only contain lowercase letters, numbers or - and _.
```

**Comment by Riz-cros** [comment]
Hi,  could it be considered to add permission per-team as well rather than per-repo only, that would in this case make some teams other than `owners` being able to create repos under an organization namespace ?

**Comment by TheTrunk** [comment]
I feel like this should be put on high priority as it creates quite a lot of issues on bigger projects. Every time a dev needs a repo, they should go to bis guy asking... Big bottleneck.

**Comment by ivaaaan** [comment]
+1
