### ISSUE TITLE
Markdown issues

### ISSUE THREAD

**Issue by pedantic-git** [docker/hub-feedback#124]
I haven't seen any other threads talking about general Markdown formatting issues so I'm starting one here.

Compare the documentation for Jelly from: [Hub](https://registry.hub.docker.com/u/fishpercolator/jelly/) and [Beta Hub](https://hub-beta.docker.com/r/fishpercolator/jelly/).

On the Beta Hub I can see the following issues:

* All links are being rendered with the text 'undefined' and are not links.
* Newlines in the middle of paragraphs are being converted to &lt;br&gt; even though the Markdown spec says they won't be.
* The `postgres` in the second heading is being rendered as undefined`.
* The indented code blocks have alignment issues and generally look a bit uncomfortable.
* The &lt;title&gt; tag of the page is blank.

**Comment by ChristopherBiscardi** [comment]
- [ ] [links](https://github.com/docker/hub-beta-feedback/issues/122) are pending deploy
- [ ] newlines need to be revisited after the next deploy since we'll be changing markdown engines
- [x] The postgres heading is related to the links issue.
- [ ] code blocks have also been modified and are pending deploy (although there is no other issue created for this)
- [ ] title is something we're aware of but have not yet prioritized fixing

**Comment by pedantic-git** [comment]
Thanks for the update!

**Comment by jakirkham** [comment]
Links seem to be working.

**Comment by jakirkham** [comment]
Would add that headings don't have the right sizes. Subheadings appear bigger than headings.

# Heading

## Subheading

**Comment by tianon** [comment]
I think code blocks still have some issues:

Current Hub:
![image](https://cloud.githubusercontent.com/assets/161631/9050112/eea0e07a-39fe-11e5-997e-611a89914b1c.png)

Beta Hub:
![image](https://cloud.githubusercontent.com/assets/161631/9050115/f8d14c56-39fe-11e5-9e6f-b8e439c606c5.png)

(cc @yosifkit)

Each of those screenshots is from the same description rendered in each interface -- the first code block in each is a fenced code block with an explicit language of `dockerfile`, and the second block is a simple indented code block.

ie:

	```dockerfile
	FROM things
	
	RUN install
	```
	
	    FROM things
	    RUN install

**Comment by tianon** [comment]
(sorry if the fixes for this are still pending deploy :speak_no_evil: -- I see the label's still here, but it has been 25 days so an update on the status would be appreciated, especially given https://status.docker.com/pages/maintenance/533c6539221ae15e3f000031/55bfba859d97d77a450000e9)

**Comment by ChristopherBiscardi** [comment]
thanks @tianon The "pending deploy" label has indeed stretched on a bit long for this ticket. We were looking into a bug today relating to styling of code blocks which don't have a language specified which is exactly the bug you've described.

**Comment by tianon** [comment]
:metal: thanks!

**Comment by janeczku** [comment]
@ChristopherBiscardi , is the update concerning intended code blocks already deployed?
For me they still look kinda strange:
Multiline tab-intended blocks are being rendered as separate single line blocks. The bottom alignment  to next paragraph doesn't look right as well.
      
![comparison](https://dl.dropboxusercontent.com/u/2512901/screencap.png)

**Comment by ChristopherBiscardi** [comment]
@janeczku yes. The issue as seen is for code blocks that don't have a specific language associated with them, which fits the bill for any "indent-based" code blocks.

**Comment by mike-jumper** [comment]
Link processing appears to be broken for links which span multiple lines. If a newline character occurs anywhere between the square brackets denoting a link, the link is simply not rendered.

For example, take the following snippet of [our `README.md`](https://raw.githubusercontent.com/glyptodon/guacd-docker/master/README.md):

```
What is guacd?
==============

[guacd](https://github.com/glyptodon/guacamole-server/) is the native
server-side proxy used by the [Guacamole web
application](http://guac-dev.org/). If you wish to deploy Guacamole, or an
application using the [Guacamole core
APIs](http://guac-dev.org/api-documentation), you will need a copy of guacd
running.
```

Rendering seems fine on [GitHub](https://github.com/glyptodon/guacd-docker/blob/master/README.md):

> ![github-rendering](https://cloud.githubusercontent.com/assets/4632905/9238936/98cadf34-410b-11e5-903f-740781766d17.png)

While the [Docker Hub rendering](https://hub.docker.com/r/glyptodon/guacd/) of the same is strangely formatted and missing most of the links:

> ![docker-hub-rendering](https://cloud.githubusercontent.com/assets/4632905/9238939/a1a5cdd0-410b-11e5-8c47-7f51c7b07693.png)

From looking over the resulting HTML within Docker Hub, I see that line breaks not only affect links, but are also rendered explicitly as `<br>`:

```html
<h1 id="what-is-guacd-">What is guacd?</h1>
<p><a href="https://github.com/glyptodon/guacamole-server/">guacd</a> is the native<br>server-side proxy used by the . If you wish to deploy Guacamole, or an<br>application using the , you will need a copy of guacd<br>running.</p>
```

**Comment by bgruening** [comment]
The TOC of this dockerhub page seems also not to be rendered correctly: https://registry.hub.docker.com/u/bgruening/galaxy-blast/

**Comment by wzymaster** [comment]
I noticed that you guys upgrade Docker Hub and then found that description of my repo is totally disordered and all original markdown-based description is totally mis-formatted.

Can you advise me what type of markdown or related languages are used for Docker Hub Description in my repo by default now ?

Here is my repo:

https://hub.docker.com/r/bigdatauniversity/spark/~/settings/

**Comment by wzymaster** [comment]
@ChristopherBiscardi  my main page of repo still looks odd , any solution ?  

The title starting with "#" to indicate headline type doesn't work for me at all !

#   ...
##  ...
### ...

The Markdown syntax format like the above looks really bad on my home page !

**Comment by ChristopherBiscardi** [comment]
@wzymaster If you include a space after the hashes the headings are properly parsed. (This is how GitHub handles headings as well).

for example:

```
##Creating Docker host on your laptop to run this Docker image
```

would become

```
## Creating Docker host on your laptop to run this Docker image
```

**Comment by jakirkham** [comment]
You mean like this one ( https://github.com/jakirkham/docker_centos_drmaa_conda )? It still doesn't look right when it gets parsed ( https://hub.docker.com/r/jakirkham/centos_drmaa_conda ).

**Comment by jakirkham** [comment]
@wzymaster, it looks like you linked your settings by accident.

**Comment by wzymaster** [comment]
@ChristopherBiscardi yes, I just add one more space in my headings, however, the font sizes show no difference among "#", "##", "###" , why ?  The key question is that my old description looks different and format is missing.

**Comment by wzymaster** [comment]
@jakirkham Yeah, sorry, it's typo and just correct it !

**Comment by ChristopherBiscardi** [comment]
@wzymaster The heading tags are a different issue since they were redefined using some global style overrides and we are eliminating global styles in the near future (<1mo from now). Still an issue, but not a Markdown parsing issue

**Comment by wzymaster** [comment]
@ChristopherBiscardi  what I am looking for here is very simple, can you tell me what I can do to make the description of my repo work as before ? Since Docker Hub upgrade, it can't be displayed in good format properly any more !

**Comment by wzymaster** [comment]
In fact,  Heading tag is just one problem in Markdown based descrpition.

 URL doesn't work unless I hardcoded  "https" leading URL :  

[Large Scale Analytics with R](http://bigdatauniversity.com/bdu-wp/bdu-course/large-scale-analytics-with-r/)  --  doesn't work

[Large Scale Analytics with R](https://bigdatauniversity.com/bdu-wp/bdu-course/large-scale-analytics-with-r/)  -- works !

why does it like that ?

**Comment by ChristopherBiscardi** [comment]
These fixes have been deployed. Thanks everyone for taking the time here!

**Comment by jakirkham** [comment]
Missing badge ( https://hub.docker.com/r/jakirkham/ubuntu_drmaa_conda/ ). Should have two, but only shows one.

**Comment by jakirkham** [comment]
> Missing badge ( https://hub.docker.com/r/jakirkham/ubuntu_drmaa_conda/ ). Should have two, but only shows one.

Now appears fixed.

**Comment by jakirkham** [comment]
Should add images (e.g. badges) appear to be stacked in DockerHub even if they were placed on one line in Markdown. This seems pretty minor though.

**Comment by yosifkit** [comment]
Markdown is still a little broken, one block followed by another (fenced, by non-fenced) displays as one continuous block.  It should just be a css fix as they are rendered as separate code tags on the page. It looks like code blocks could use margins, since they have whitespace issues when followed by a paragraph or header.

Also, indented code block in a list does not work.  Styling of inline code that are links is not obvious (hover or otherwise).  All links' hover effect is not easy to distinguish.

**Comment by jakirkham** [comment]
Missing badge problem is now back. ( https://github.com/docker/hub-feedback/issues/124#issuecomment-145854684 )

**Comment by tianon** [comment]
Looks like code block styling broke again somewhat recently. :disappointed:

![image](https://cloud.githubusercontent.com/assets/161631/20685565/b675c73c-b569-11e6-9765-187fbed68708.png)

**Comment by jacknlliu** [comment]
html lables not supported

**Comment by geerlingguy** [comment]
@tianon - I'm seeing the same here; looks really gaudy:

<img width="492" alt="screen shot 2017-07-09 at 10 46 21 pm" src="https://user-images.githubusercontent.com/481677/28002206-7907cc94-64f8-11e7-906d-2aeafc15120a.png">

(from: https://hub.docker.com/r/geerlingguy/solr/)
