### ISSUE TITLE
Repository Statistics not being updated (.pull_count)

### ISSUE THREAD

**Issue by edsiper** [docker/hub-feedback#1246]
Looking at my [open source project statistics](https://hub.docker.com/v2/repositories/fluent/fluent-bit/) I realized that the last update was 4 days ago:

![hub_stats](https://user-images.githubusercontent.com/369718/32744523-5d59f66c-c875-11e7-98cb-eef1e7cbd822.png)

any feedback is appreciated.

**Comment by kizbitz** [comment]
Hi,

We were having issues with some of our backend services and the team needed to disable these pull counts at times.
