### ISSUE TITLE
CloudLinux Support

### ISSUE THREAD

**Issue by NexDog** [docker/hub-feedback#1248]
We are a web host and Plesk is our primary control panel. Docker is now included with Plesk but we use the CloudLinux OS and it's not supported. Are there any plans to support this operating system?

**Comment by thaJeztah** [comment]
There are no plans for adding support on CloudLinux that I'm aware of. It _may_ work if you install the CentOS or RHEL packages on CloudLinux (IIUC, CloudLinux advertises full compatibility with those), but it would definitely not a "supported" solution.

This issue tracker is for feedback for Docker Hub (the image registry), not for other Docker products; if you think there would be a lot of demand for adding CloudLinux, the https://github.com/docker/for-linux issue tracker may be a better place for that.
