### ISSUE TITLE
Request for official Hub repository using v2 API

### ISSUE THREAD

**Issue by CermakM** [docker/hub-feedback#1253]
Hello, I am trying to query tags from official Docker Hub repository.
What I am doing is getting response to 'GET' request on:

`https://hub.docker.com/v2/repositories/<namespace>/<repo>/tags/`

Which works just fine for public user repos like fedora/apache.
My question is how to query official repo, ie. fedora

I tried
`https://hub.docker.com/v2/repositories/fedora/tags/`

or using `_` and `official` as `<namespace>`

None of it works. I'd really appreciate your help.

Thank you,
Marek.

**Comment by thaJeztah** [comment]
Docker Hub (hub.docker.com) is not the registry you're pulling from; Docker Hub is a web interface that allows you to browse the repositories/images that are available to pull from the Docker Registry

The registry itself is at https://registry-1.docker.io

Also see https://github.com/moby/moby/blob/master/contrib/download-frozen-image-v2.sh which is a shell script to download images without using docker, and may provide some insight as to what docker does when pulling an image

**Comment by CermakM** [comment]
Hi, thank you for the answer. The link is useful, I'll check it out. 
However, what I was doing up until now was just searching through the repositories and tags, so I basicly didn't need the registry itself, since I did not need to push/pull - that way I avoided the authentication. Querying the hub.docker.com/v2 was sufficient. 
Are you telling me that* a)* this is not the right way to do it and *b)* there is no way to query an official repo like that? It works very well for the namespace/repository repos, tho.

**Comment by CermakM** [comment]
By the way, using the registry... could you help me out with authentication to the registry? I kinda tried to follow the [Docker guide](https://docs.docker.com/registry/spec/auth/token/#how-to-authenticate) I am still getting `error: invalid token` and `message: "authentication required"` ..
the ways I tried to query token:
`https://auth.docker.io/token?serivce=registry.docker.io&scope=repository:fedora:pull` for fedora repo
`https://auth.docker.io/token?serivce=registry.docker.io&scope=registry:catalog:*` and without `:*` at the end for registry catalog

I recieved the token in all cases, then I used it in the authorization header as `Authorization: Bearer <token>` for f.e `https://registry-1.docker.io/v2/fedora/tags/list` and `https://registry-1.docker.io/v2/_catalog` .. then I keep getting the error mentioned.
I appologize if this is kind of a stupid question, I am not very well-read in the topic of http requests etc. and I really appreciate your help.

**Comment by thaJeztah** [comment]
I think there's two tokens in use; a short-lived token for pulling each image, and an authorisation header if to access private repositories. What exactly are you trying to do? I this to get a list of tags for a repository?

**Comment by CermakM** [comment]
Yes, I know. At the moment I want to list tags and description of an official repository. It works for public repositories like fedora/apache, but not for the official ones, like fedora.

**Comment by thaJeztah** [comment]
Does it work if you use `library/fedora` instead of just `fedora`? Even though official images show up as `<somename>`, the actual images are located in `library/<somename>`

**Comment by CermakM** [comment]
Aaah there we go... Finally it works. If it is in docs and I missed it then well.. serves me right.. Otherwise this should really be stated somewhere.

Thank you very much.

**Comment by tmc9031** [comment]
@CermakM how to get registry image tag, i also try "curl https://registry-1.docker.io/v2/_catalog"
but not work

**Comment by CermakM** [comment]
@tmc9031 you need to provide authorization token to the curl as well, see the [example](https://github.com/moby/moby/blob/master/contrib/download-frozen-image-v2.sh) from this conversation, official [documentation](https://docs.docker.com/registry/spec/api/) or place a question on https://stackoverflow.com/. If you think there is an issue or bug in the implementation, open another issue ;).

**Comment by mlandisbqs** [comment]
I couldn't make this work and did not want to create an api token to query public information on available tags. I found this api URL works for GET or HEAD:

```js
  // omit the tag if you want a list...
  await axios.head(`https://hub.docker.com/v2/repositories/library/node/tags/${nodeLtsVersion}`);
```

YMMV

**Comment by thaJeztah** [comment]
@mlandisbqs that's the Docker Hub API (so specific to Docker Hub, not the registry); it's documented in the "reference" section of the documentation; https://docs.docker.com/reference/; 

That endpoint is documented here;

https://docs.docker.com/docker-hub/api/latest/#tag/repositories/paths/~1v2~1namespaces~1%7Bnamespace%7D~1repositories~1%7Brepository%7D~1tags/get

**Comment by mlandisbqs** [comment]
@thaJeztah -- this was my experience based on that doco...

<img width="1036" alt="image" src="https://github.com/docker/hub-feedback/assets/39845713/d5e15f27-62ce-440e-af15-319348feaf91">

not sure what the special sauce is to make that work

**Comment by thaJeztah** [comment]
`library` is the namespace for the official images; the `_` is something the router uses for the GUI (honestly, don't know where that came from, but it was introduced a long time ago)
