### ISSUE TITLE
Automated Builds: Hub gets description from latest build, NOT master/latest brach

### ISSUE THREAD

**Issue by izznogooood** [docker/hub-feedback#1256]
Lets say you have an automated build. /dev (:dev)and /latest (:latest) based on two different branches.

Now one would think Docker Hub pulls and published the dockerfile/readme from the main/latest/default branch. But instead it pulls these files from the _latest build_ resulting in my case izzno/plexconnect a wrong description for the :latest build as the :dev is the last built image.

**Comment by seanvree** [comment]
I have this same question...is there an answer to this?

**Comment by izznogooood** [comment]
> I have this same question...is there an answer to this?

Apparently not... 😂
