### ISSUE TITLE
Image taking forever to build.

### ISSUE THREAD

**Issue by ghost** [docker/hub-feedback#1258]
??????????????????
How is it going today guys?

Just curious. Anyone else having slow docker builds today?

**Comment by Gr1dd** [comment]
Is this from travisCI????
TravisCI is taking forever as well to scrape my github.

**Comment by mochadwi** [comment]
+1, this is overkill for only a simple Dockerfile like this:

```
FROM alpine:3.6

RUN apk add --no-cache \
  bash \
  curl \
  grep \
  jq

COPY merge-request.sh /usr/bin/

CMD ["merge-request.sh"]

```
