### ISSUE TITLE
Build canceled without any explanation

### ISSUE THREAD

**Issue by luigipertoldi** [docker/hub-feedback#1259]
Hello,

I have an image which build gets canceled without any explanation on the Docker Hub:
```
[ 81%] Building CXX object source/run/CMakeFiles/G4run.dir/src/G4VUserDetectorConstruction.cc.o
[ 81%] Building CXX object source/run/CMakeFiles/G4run.dir/src/G4VUserParallelWorld.cc.o
[ 81%] Building CXX object source/run/CMakeFiles/G4run.dir/src/G4VPhysicsConstructor.cc.o
[ 81%] Building CXX object source/run/CMakeFiles/G4run.dir/src/G4VUserPhysicsList.cc.o
Build canceled.
```
Though the other very similar one in the same repo build successfully.

My Docker ID is `gipert` and the repository is called [`baseos-containers`](https://hub.docker.com/r/gipert/baseos-containers/)

**Comment by pchico83** [comment]
Builds are automatically cancelled if they take more than 2 hours to complete.

**Comment by Borda** [comment]
So, is there another way how to build "larger" images, for example, I want to compile OpenCV with CUDA and the compilation takes on my notebook about 1h but for example on CircleCI 2.5h?
https://hub.docker.com/r/borda/docker_python-opencv-ffmpeg/builds/
https://circleci.com/workflow-run/d72fdfa4-861a-41d3-840d-c11509c9f4c1
