### ISSUE TITLE
Repo sub-nav highlight

### ISSUE THREAD

**Issue by TeckniX** [docker/hub-feedback#126]
Small thing, but upon initial selection (after a search) of a repository, the 'Repo Info' tab should be highlighted.
e.g.:
not highlighted: 
https://hub-beta.docker.com/_/ubuntu-debootstrap/

highlighted (same info displayed):
https://hub-beta.docker.com/r/library/ubuntu-debootstrap/

Consistent links would be good too :)

**Comment by ChristopherBiscardi** [comment]
Thanks for reporting this. The links should be consistent (the library namespace on official repos is an implementation detail and shouldn't be shown to users), which will fix the "active" state on the link.

**Comment by akshayvyas** [comment]
closing ticket.  highlight of tabs is working properly in both cases.
