### ISSUE TITLE
Automated build has cancel button enabled without login

### ISSUE THREAD

**Issue by bipindra** [docker/hub-feedback#1263]
Automated build triggered by change in dockerfile in github, the cancel button was enabled without login. I did not check if cancel works but I feel cancel button should not even be enabled for anonymous users. Right now anyone can click on cancel button for my build.

**Comment by JoeNyland** [comment]
I have just noticed this too and was about to report an issue. I did try clicking the cancel button whilst not signed in and I got no feedback from the UI which wasn't what I expected. However, the browser console logged a 401 from the Docker Hub API.

The Cancel button should not be displayed, unless you have write access to the repository and you are logged in.
