### ISSUE TITLE
Discourse Package on Synology RackStation - SMTP Configuration

### ISSUE THREAD

**Issue by 1tscott** [docker/hub-feedback#1269]
Been trying all day to get the Discourse package to work on a Synology RackStation. Installation is fine but it refuses to send the activation email. Has anyone gotten this to work?

**Comment by willemb2** [comment]
I did not even get to the activation step. When I try to run it an my DS216+II with DSM 6.1.5-15254, it opens http://<my-DS-IP>:30004/ with as result "502 Bad Gateway" and "nginx".
Synology support has escalated my case to the developers.
[This thread](https://meta.discourse.org/t/smtp-email-doesnt-work-on-synology-dsm-6/75531/5) ends with the conclusion: "the package is outdated".
