### ISSUE TITLE
More detailed webhook errors

### ISSUE THREAD

**Issue by swolf91** [docker/hub-feedback#1274]
I've one docker hub project having a webhook triggering a jenkins build. In some way the webhook stopped working but the status just says Error. It would be great to have a more detailed error message. Why didn't it work? If I request the url by myself the jenkins build will be triggered. so the url works. It just didn't work anymore as a webhook in Docker Hub.

**Comment by boeserwolf91** [comment]
@ichekrygin Unfortunately no, the problem still exists.
