### ISSUE TITLE
Unable to create organization on docker hub

### ISSUE THREAD

**Issue by ianuragsingh** [docker/hub-feedback#1275]
Hello All

I am trying to create one organization "delivery", i do not know what is the problem it always highlight as red. Please help me to move ahead.

I am free user now. is it for paid user? 

Regards,
Anurag

**Comment by thaJeztah** [comment]
@ianuragsingh looks like that name is taken already?  https://hub.docker.com/u/delivery/

**Comment by ianuragsingh** [comment]
thanks !! it is working. One more question what is the url to push docker image in organization repo?
is it username/organization-name?
