### ISSUE TITLE
Docker daemon reports status as "Crashed" immediately after starting

### ISSUE THREAD

**Issue by krshnmr4** [docker/hub-feedback#1277]
Docker daemon reports status as "Crashed" immediately after starting. 

Here is the script that is run on Alpine OS:
# Installing Docker
    sudo apk update
    sudo apk add --no-cache --repository http://dl-cdn.alpinelinux.org/alpine/edge/main --repository http://dl-cdn.alpinelinux.org/alpine/edge/community docker
    # Start docker
    sudo service docker start
    docker --version
    **service docker status**
    sudo rc-update add docker boot

The line in bold reports that it has crashed while it should report as "starting" or an equivalent state.
<img width="1153" alt="erroneous docker service status" src="https://user-images.githubusercontent.com/34561059/34025616-9d89ee24-e105-11e7-9a02-081f6bc6209a.png">

**Comment by thaJeztah** [comment]
The docker package for Alpine is managed by Alpine Linux; can you open an issue in their issue-tracker instead? https://bugs.alpinelinux.org/projects/alpine/issues
