### ISSUE TITLE
Unable to change timezone in jordan/icinga2 docker image

### ISSUE THREAD

**Issue by ajayan769** [docker/hub-feedback#1279]
Hi All,

 I am trying to test a monitoring tool using using icinga2 for that I have used the docker image "jordan/icinga2" (https://hub.docker.com/r/jordan/icinga2/). The installation were good and and am able to monitor my servers/hosts. But the issue I'm facing is timezone, the icinga2 showing the UTC timezone where I want to use IST (Asia/Kolkata)...... 
>>Changed the timezone from php.ini (/etc/php/7.0/cli/php.ini) but no luck
Can anyone please let me know the possible workaround in this issue?
Thanks in advance

**Comment by thaJeztah** [comment]
Can you open an issue in the issue tracker for that image instead? Docker Hub only facilitates hosting images, but does not manage their actual content. The GitHub repository for that image can be found here; https://github.com/jjethwa/icinga2

**Comment by ajayan769** [comment]
@thaJeztah Sorry for that.....
Thanks for the correct path :D
