### ISSUE TITLE
how to enable ipv6 in kernel 

### ISSUE THREAD

**Issue by rangarajancr** [docker/hub-feedback#1287]
Dear Team,

i need your assistance in order to rectify the below mentioned error.

[root@ipa /]# ipa-server-install 
ipa.ipapython.install.cli.install_tool(CompatServerMasterInstall): ERROR    IPv6 stack is enabled in the kernel but there is no interface that has ::1 address assigned. Add ::1 address resolution to 'lo' interface. You might need to enable IPv6 on the interface 'lo' in sysctl.conf.
ipa.ipapython.install.cli.install_tool(CompatServerMasterInstall): ERROR    The ipa-server-install command failed. See /var/log/ipaserver-install.log for more information

**Comment by thaJeztah** [comment]
This issue tracker is to provide feedback about Docker Hub (https://hub.docker.com). For questions on _using_ docker, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/) (register here: [http://dockr.ly/community](http://dockr.ly/community))
- [StackOverflow](https://stackoverflow.com)

**Comment by jpereira** [comment]
You should enable the ipv6 directly in the Docker.

try to create the file `/etc/docker/daemon.json` as the below sample.

```
{
        "ipv6": true,
        "fixed-cidr-v6": "2001:db8:1::/64"
}
```

Then restart the Docker daemon ` systemctl restart docker`

**Comment by guillermocol** [comment]
I think this solved it, but I get after that this error:


2021-04-19T11:29:06Z DEBUG The ipa-server-install command failed, exception: RuntimeError: failed to create DS instance Command '/usr/sbin/setup-ds.pl --silent --logfile - -f /tmp/tmp2Qw2HX' returned non-zero exit status 1
2021-04-19T11:29:06Z ERROR failed to create DS instance Command '/usr/sbin/setup-ds.pl --silent --logfile - -f /tmp/tmp2Qw2HX' returned non-zero exit status 1
2021-04-19T11:29:06Z ERROR The ipa-server-install command failed. See /var/log/ipaserver-install.log for more information

Did you see this error before?

Thank you for your help
