### ISSUE TITLE
Unable to create Automated Build (Error 400: Bad Request)

### ISSUE THREAD

**Issue by hazim1093** [docker/hub-feedback#1291]
I have been trying to create an automated build from a github repo, but can't succeed. 

When clicking on the `Create` button, the web console shows a `Bad Request` error: 

![image](https://user-images.githubusercontent.com/11160747/34371156-78e2a21e-eaec-11e7-8853-3d6450a1e3f3.png)

I have created a lot of automated build before never seen such an issue.

**Comment by hazim1093** [comment]
This error was due to: 
```
{"detail": {"vcs_repo_name": ["VCS repository name cannot exceed 50 chars"]}}
```

Shouldn't user get feedback on the UI?

**Comment by theAkito** [comment]
Same issue here, however my names are really short. Where can I see the debug information?
