### ISSUE TITLE
Failed to register layer...ImportLayer failed in Win32: The system cannot find the file specified

### ISSUE THREAD

**Issue by 935main** [docker/hub-feedback#1293]
Running in Server 2016, trying to pull microsoft/aspnet:4.7.1-windowsservercore-1709

Step 1/8 : FROM microsoft/aspnet:4.7.1-windowsservercore-1709
4.7.1-windowsservercore-1709: Pulling from microsoft/aspnet
5847a47b8593: Pull complete
e50cc21fbc56: Pull complete
0872816e4982: Extracting [==================================================>]  365.2MB/365.2MB
06e1605a7f44: Download complete
a4f34f3252b5: Download complete
e7af45d41a2a: Download complete
0cbda976828f: Download complete
134a13bb5d64: Download complete
c2bb75a5c2ec: Download complete
17130145e4e5: Download complete
failed to register layer: re-exec error: exit status 1: output: time="2017-12-27T08:19:12-07:00" level=error msg="hcsshim::ImportLayer failed in Win32: The system cannot find the file specified. (0x2) layerId=\\\\?\\C:\\ProgramData\\docker\
\windowsfilter\\ef0c8f87f8e1894283239765add6e96601394a376c505e7165f13aeb3b7ff3c6 flavour=1 folder=C:\\Windows\\TEMP\\hcs472145487"
hcsshim::ImportLayer failed in Win32: The system cannot find the file specified. (0x2) layerId=\\?\C:\ProgramData\docker\windowsfilter\ef0c8f87f8e1894283239765add6e96601394a376c505e7165f13aeb3b7ff3c6 flavour=1 folder=C:\Windows\TEMP\hcs472145487

**Comment by caokennedy** [comment]
@935main did you resolve this? 
I am getting the same issue when trying to pull microsoft/aspnet:4.7.1-windowsservercore-1709 and it fails to register at the same point too

**Comment by 935main** [comment]
Negatory.  I assumed it’s because I was running Server 2016 RTM and not 1709.
