### ISSUE TITLE
How to login to a container through ssh/Putty from another host 

### ISSUE THREAD

**Issue by joshlingard** [docker/hub-feedback#1298]
I have created a container with RHEL inside a host with RHEL as well.

I have used Macvlan network driver as shown in https://docs.docker.com/engine/userguide/networking/get-started-macvlan/

So now I can ping the IP of my container from another host in the same network.

My host's ip where docker is installed is 172.xx.xx.105 and another host's ip is 172.xx.xx.106 and my container's ip is 192.xx.x.10.

How can I ssh to my container's IP(192.xx.x.10) from another host (172.xx.xx.106) or just directly ssh to my container's ip directly from a putty?

**Comment by DivyaJyotiDas** [comment]
I too facing this issue. Any help would be appreciable ..
Thanks 
Divya Jyoti Das
