### ISSUE TITLE
Automated build stuck, cannot be canceled

### ISSUE THREAD

**Issue by yildiz-online** [docker/hub-feedback#1302]
https://hub.docker.com/r/moussavdb/webapp/builds/b3diaiub5pueffofqvthpvu/

The automated build seems in error, while it is displayed as queued, no way to cancel it nor to trigger another build.

**Comment by NeilClayton** [comment]
I also have a similar problem although I am able to cancel the build. The build just sits in a queue, i have tried on two different repos and both have the same issue

**Comment by pchico83** [comment]
We have had a outage, system should be back to normal now.

**Comment by yildiz-online** [comment]
Working, thx
