### ISSUE TITLE
Unable to signup for Docker ID

### ISSUE THREAD

**Issue by agilguil** [docker/hub-feedback#1304]
I am trying to signup for a Docker ID, the site allows me to type username/email/password combination. 
It doesn't give any feedback of success on screen
It doesn't email me(I don't know if it should)
I cannot then sign in with the username and password just registered.
Tried in Chrome and IE, (interestingly chrome does not warn that username can only contain letters, IE does)

**Comment by agilguil** [comment]
Success, it seems password needed a special character. But there was no indication on screen of this, or the fact that signup hadn't worked.

**Comment by zhaojinqiang** [comment]
what's the special character, I have the same issue

**Comment by SantaMinus** [comment]
@agilguil  Thank you so much! I was completely lost there, and the problem was in just 1 special character! :D
Would be nice to warn about it in the password field.

**Comment by divatemangesh** [comment]
I tried adding special characters in the password but still not able to signup

**Comment by mattcochrane1972** [comment]
When signing up there is no feedback on the screen to say it was successful. The confirmation email took 10 minutes to turn up so I was assuming it hadn't worked. Actually, it did work. There was no special character required in the password.

**Comment by Mirror1211** [comment]
When I signed up, the bottom of "sign up" was not valide. Could anybody help me ???

**Comment by IhorHoivaniuk** [comment]
The same for me. Tried in all Chrome, Opera and Edge. The same everywhere. 
I network section i see failed HTTP request
![image](https://user-images.githubusercontent.com/14124154/40707323-0a1d0b86-63f9-11e8-9881-d5d8d34508a1.png)

**Comment by aswanevelder** [comment]
Wow, this is quite unbelievable, not sure if a company can be trusted if their sign up page does not work... goodness.

**Comment by slimlime** [comment]
Extremely anxiety-inducing UX there. I kept clicking with my generated passwords and ended up just making an alt account to see if the signup form actually worked... 😕 😢 😥

**Comment by kungfu71186** [comment]
This is still occurring. Says my email is not activated. Doesn't show a link to resend activation. Submit for password reset. Get nothing. This is on 2 different emails as well. Get errors in console.

**Comment by nickp60** [comment]
If you have access to a Mac, try from there;  I tried several different browsers with no luck on Ubuntu.  Worked first time on the Mac.

**Comment by Patches5** [comment]
I was Using Chrome v66 - The Captcha was not displayed for me so couldnt proceed with signup
Tried using Edge and it worked correctly.

**Comment by ymoisan** [comment]
Tried Chrome, then FireFox and finally only MS Edge let me see the pictures to prove I'm not a robot.  Weird ...

**Comment by edenbuaa** [comment]
This problem also troubled me a few days. I found the issues is the connection to google to load the reCAPTCHA. and this solution solved my problem, wish help u with the same issue.

**Comment by Izrab** [comment]
I have same issue, I cannot create a simple Docker account. Why isn't there any feedback or a message to tell me if there is a mistake?
This should be a high priority issue.

**Comment by matebenyovszky** [comment]
I tried to register several times with different user names and emails, but I did not received password / account verification email and cannot log in.

Emails and dockerdID-s respectively:
benyovszky.mate.work@outlook.com   benyovszkym
mate.benyoszky@pyxelia.hu  matebenyovszky

My password contains numbers, small and big letters from the english ABC, but no special characters, more than 16 char.

**Comment by hertzigger** [comment]
I was having the same problem, seems like my email address was already used. If you are going to force us to create an account. At least provided useful feedback. Web design 101 imo. nearly 2 year old issue.

**Comment by jonathanarbely** [comment]
Also ran into this issue. Fixed by switching from Mac to Windows machine.

**Comment by JohnTzoumas** [comment]
Hello all,
I had the same issue and i used incognito in Chrome, worked like a charm!

**Comment by bergentroll** [comment]
@JohnTzoumas, thank you. It works for Firefox too. May be some privacy guard issue?..

**Comment by b-hayes** [comment]
Same problem now. Sign up button does nothing no matter what I do. special char or not.

**Comment by kearney-sp** [comment]
Also having this problem. Using Chrome.  Cursor disappears, no messages of confirmation or errors, just sits there.

**Comment by nodemadic** [comment]
Experiencing this problem as well. Tried up to date Firefox and Chrome browsers. Same issue as sited above:
* no error code in network tab of chrome dev tools
* "sign-up" button changes to lighter color, but hides cursor when hovered
* no response from page
* multiple different passwords attempted each using all configurations of required characters

**Comment by jl111** [comment]
https://github.com/docker/hub-feedback/issues/2234 

We should contact support. i did so already.

**Comment by en-ife** [comment]
> Hello all,
> I had the same issue and i used incognito in Chrome, worked like a charm!

Had this EXACt same issue - no permutation of passwords, capitalized letters, different browsers worked (I am running macOS Monterey, Apple M1 chip) and... only until I opened an INCOGNITO Chrome browser did this work. 

This should be fixed. 
Cue facepalm.

**Comment by jl111** [comment]
Incognito mode worked for me as well!

**Comment by raysefo** [comment]
Incognito mode did the trick, thank you.

**Comment by Ashish-singh-dev** [comment]
See feedbacks in browser's console, for me it was a "username already taken" warning in console

**Comment by guptashraddha2016** [comment]
When I signed up, the bottom of "sign up" was not working. Could anybody help me?

**Comment by Ashish-singh-dev** [comment]
> When I signed up, the bottom of "sign up" was not working. Could anybody help me?

See your browser's console for feedback, it has warning message from docker hub in console about what went wrong.

**Comment by guptashraddha2016** [comment]
> > When I signed up, the bottom of "sign up" was not working. Could anybody help me?
> 
> See your browser's console for feedback, it has warning message from docker hub in console about what went wrong.

It's Working, Thanks!!

**Comment by Jinmkook** [comment]
my English is not good, im success for this ploblem
if you have a ploblem 'sign up' not execute.
i use *@gmail.com, password is any number ex) '8416851858314' is success
and login gmail and fix my password.
i hope your succession! :)

**Comment by LennTea** [comment]
turns out that my problem was uppercase in the username! 
I found out through this page: https://docs.docker.com/accounts/create-account/

Create a Docker ID
Sign up with your email address
- Go to the Docker sign-up page
- Enter a unique, valid email address.
- Enter a username.
Your Docker ID must be between 4 and 30 characters long, and can only contain numbers and lowercase letters. Once you create your Docker ID you can't reuse it in the future if you deactivate this account.
- Enter a password that's at least 9 characters long.

**Comment by Obliviously** [comment]
Why is this issue closed? I just wasted 30 minutes to create an docker account.

Just add a message that tells you that capital letters are not allowed in the username.

**Comment by JinxLuckless** [comment]
I just ran into this same issue. It definitely needs to tell you why signup failed. I never would've guessed my username containing a capital letter was the problem.

**Comment by SyncGit12** [comment]
<img width="1120" height="510" alt="Image" src="https://github.com/user-attachments/assets/2b16351f-34c1-4345-8ce6-301be391584c" />

**Comment by SaymenAbbas** [comment]
> https://www.dockerstatus.com/

Thanks for the help! I wanted to get docker for sandboxing in Gemini CLI and was wondering why the hell it doesn't want me sign up. What bad timing I have...
