### ISSUE TITLE
Unexpected Error

### ISSUE THREAD

**Issue by madhukarbol** [docker/hub-feedback#1307]
We are getting Unexpected Error while docker build is being generated. Build code was bqwam6hexkxxjqpchntjyxe. Any help is highly appreciated.

**Comment by NeilClayton** [comment]
Similar issue also, now being stuck in a queue. Another outage like at the weekend???

**Comment by pchico83** [comment]
We have experience some scalability issues. It should be back to normal now.

**Comment by NeilClayton** [comment]
Showing as building now although so of the previous deploys that error out seem to have reactivated, but not a biggie. Thank you for resolving :)

**Comment by johnvcoleman-w24** [comment]
I've been seeing this unexpected error a lot over the last week.  Reference build codes:

bxvzkywpyqhdkdfbkbnkwbt
blk9xhp9y2lvpnioq5qao2h
budycgmp6opsphs3mjf6upc
bqgdynfgepael7ezkivj42k

Any insight would be great, thanks!
