### ISSUE TITLE
Delete and cleanup docker repository

### ISSUE THREAD

**Issue by dmenne** [docker/hub-feedback#1312]
One multiple occasions within the last 3 months I submitted a request to delete a repository (dmenne/gastro-docker) so I can recreate it from scratch.

I now have an empty repository, but whenever I try to re-create gastro-docker, I get a message that the repository already exists. 

This is a serious security bug. It should be possible to delete a repository without traces left.

**Comment by ysle** [comment]
same here, and seems like it's an old issue : 
https://forums.docker.com/t/cannot-delete-repository/22555
please advise.

**Comment by dmenne** [comment]
**Maybe we should use a bold font**

There seems to be no way to contact Docker support directly if you do not have a contract. I once was contacted, but nobody at Docker takes this issue seriously.
