### ISSUE TITLE
"No more private repositories available", but we do not have any private repositories.

### ISSUE THREAD

**Issue by WillGibson** [docker/hub-feedback#1313]
I'm trying to add a private repository, but it's saying "No more private repositories available".

We do not have any private repositories at present, so I think we should be able to use the free one.

We did have a private repository in the past, but that was no longer relevant so we deleted it.

We do not seem to be able to contact support directly so I'm asking here.

**Comment by ejo** [comment]
I just ran into this same problem. Then I found the following at [https://hub.docker.com/account/billing-plans/](https://hub.docker.com/account/billing-plans/) :

> "Do I have to pay to use your service?
> No, you only have to pay if you require one or more private repository."

But on that same page, the chart which is the main content of the page shows 1 private repo and 1 parallel build. This is confusing...

**Comment by hackel** [comment]
I just ran into this issue as well.  Turns out I was able to create a private repo under my own account, but not under the organization.  This is not well documented at all.
