### ISSUE TITLE
Clarify what triggers linked repository builds in the build settings UI

### ISSUE THREAD

**Issue by deviantintegral** [docker/hub-feedback#1314]
Following up from #518, the current UI isn't clear about the limitations of linked repositories. Currently, it reads like any image will be rebuilt automatically if it's upstream image is rebuilt, with no limitations (current UI for future reference):

<img width="923" alt="drupal_tests - docker hub 2018-01-10 09-09-47" src="https://user-images.githubusercontent.com/255023/34776820-1204c806-f5e6-11e7-884a-bdac1a669989.png">

This leaves images open to upstream security vulnerabilities if the maintainer isn't careful to check that images are rebuilt. Requiring image maintainers to manually tag a new image every time an upstream is rebuilt is error prone and adds delays to deploying security updates, so it's not a feasible strategy.

It would be best if the build configuration itself could indicate if a given automatic build will trigger on linked builds.

<img width="1224" alt="drupal_tests - docker hub 2018-01-10 09-11-27" src="https://user-images.githubusercontent.com/255023/34776893-67425428-f5e6-11e7-8218-e7d7c27e70a1.png">

Also, it's unclear if the default "all branches except master" and "all tags" settings will allow for linked repository rebuilds. That should be called out in the UI.

**Comment by zyndagj** [comment]
It would be great to have this documented outside of a github issue.

**Comment by shoeper** [comment]
+1
