### ISSUE TITLE
Multiple tags per build don't work

### ISSUE THREAD

**Issue by svengo** [docker/hub-feedback#1316]
I tried to specify multiple tags in `Docker Tag` field `{sourceref},latest`. This should work according to https://github.com/docker/hub-feedback/issues/341#issuecomment-263705074.

![screenshot-2017-12-2 docker cloud](https://user-images.githubusercontent.com/2502366/33516501-17e980c6-d774-11e7-98a9-8f927d7d0f8d.png)

...but the build failed:

    Successfully built 7cffb47442d4
    Successfully tagged svengo/tor:0.3.1.9
    Pushing index.docker.io/svengo/tor:0.3.1.9...
    Push failed. Attempt 2 in 60 seconds.
    Push failed. Attempt 3 in 60 seconds.
    Push failed. Attempt 4 in 60 seconds.
    Push failed. Attempt 5 in 60 seconds.
    {u'message': u'tag does not exist: svengo/tor:latest'}
    ERROR: Build failed: {u'message': u'tag does not exist: svengo/tor:latest'}
    ERROR: Build failed with exit code 2
    ERROR: Build in '0.3.1.9' (645a86de) failed in 0:13:55

**Comment by SkeLLLa** [comment]
It's strange. Yesterday they were working well. But today I have the same error as described above.
