### ISSUE TITLE
unable to reset password

### ISSUE THREAD

**Issue by jkarloz** [docker/hub-feedback#1317]
Hi! I was trying to reset my password account (docker hub) but in every try I get "There was an error! Your password has not been reset, please try again" I've tried with special characters too with the same result. Could anyone help me please? Thanks.

**Comment by baram204** [comment]
Me too.

![image](https://user-images.githubusercontent.com/11155414/36509164-238766f0-17a2-11e8-9c89-0c4dc54af071.png)
