### ISSUE TITLE
Meltdown/Spectrum Approach

### ISSUE THREAD

**Issue by gzamoran-ford** [docker/hub-feedback#1320]
Hi All,

I have some concerns about The Meltdown/Spectrum attack to the server and all that stuff.

I would like to know if this one was addressed for this particular url : https://hub.docker.com where our images are.
How Docker is mitigating this issue, and if there is impact to our images?

Any response from Docker team will be highly appreciated.

Gary

**Comment by nandhini915** [comment]
please check out https://success.docker.com/article/how-does-spectre-meltdown-affect-my-docker-installs. It contains Docker's official response.
