### ISSUE TITLE
Unable to login into docker hub

### ISSUE THREAD

**Issue by vraravam** [docker/hub-feedback#1321]
I'm trying to login from the command line, and this is what I get:
```
Login with your Docker ID to push and pull images from Docker Hub. If you don't have a Docker ID, head over to https://hub.docker.com to create one.
Username (avijayr@gmail.com):
Password:
Error response from daemon: Get https://registry-1.docker.io/v2/: unauthorized: incorrect username or password
```
Docker version 17.12.0-ce, build c97c6d6
When I logout and login using the "docker for mac" app, I'm able to login (ie it shows a green circle), but either way, I'm unable to pull images from the hub. Please help.

This is what I get if I try to pull any image:
```
docker pull alpine
Using default tag: latest
Error response from daemon: Get https://registry-1.docker.io/v2/library/alpine/manifests/latest: unauthorized: incorrect username or password
```
I have also tried deleting the whole file: `~/.docker/config.json` and also the whole directory `~/.docker` - no luck.

**Comment by g-marius** [comment]
I would check out on #935. username and docker id are different things.
just tripped out myself on the same thing.
ps: i would also edit the email address for spam reasons.
