### ISSUE TITLE
Build is failing while running the command /bin/bash -c apt-get update

### ISSUE THREAD

**Issue by madhukarbol** [docker/hub-feedback#1323]
Hi,
We are getting below error while docker build is being generated.
Build failed: The command '/bin/bash -c apt-get update' returned a non-zero code: 100.

Can you please look into it. Any solution or work around is highly appreciated.

**Comment by kevalpatel2106** [comment]
@madhukarbol I also having the same problem with my build. I am able to build container locally on my machine. Did you get any solution?
Here is the build log: https://hub.docker.com/r/kevalpatel2106/docker-android-raspbian/builds/bbqybgvzzmz24tkuupdsy7a/

**Comment by thaJeztah** [comment]
Looks like you’re trying to build an ARM (raspberry pi) image. Docker Hub autobuild only supports amd64 architecture

**Comment by kevalpatel2106** [comment]
@thaJeztah You are right!!! Thanks 🙏
