### ISSUE TITLE
See all official repositories button on landing page goes to page that is illegible on iPhone 

### ISSUE THREAD

**Issue by binduwavell** [docker/hub-feedback#133]

**Comment by ChristopherBiscardi** [comment]
Adding Screenshots

"See All Official Repos" is cut off on smaller devices.

<img width="373" alt="screenshot 2015-07-24 07 53 09" src="https://cloud.githubusercontent.com/assets/551247/8877230/2f2027a6-31d9-11e5-9c9b-86d9088022d5.png">

RepositoryListItem is non-responsive (which is the reason the /explore page is rendered as such)

<img width="322" alt="screenshot 2015-07-24 07 53 40" src="https://cloud.githubusercontent.com/assets/551247/8877252/4953b5b6-31d9-11e5-8926-c45218c24d19.png">

**Comment by rrarunan** [comment]
Related to #120 .. Responsive design fixes are on our radar.
