### ISSUE TITLE
Unable to disable security scanning

### ISSUE THREAD

**Issue by ntwrkguru** [docker/hub-feedback#1333]
Hello! I turned on security scanning in one of my organizations, just to try it. Now, I'd like to turn it off, but can't see an option to do so. Am I missing something?

**Comment by ntwrkguru** [comment]
Awesome customer service... 3 months with NO TRACTION and now just close it without so much as a comment.

**Comment by nandhini915** [comment]
My mistake - We have ended the Docker Security scanning preview service on Docker Hub, hence the ticket did not apply. 

https://success.docker.com/article/scanning-deprecation-faqs has further details.
