### ISSUE TITLE
All containers stuck on queue / unable to cancel.

### ISSUE THREAD

**Issue by cdrage** [docker/hub-feedback#1334]
After updating my Dockerfiles (https://github.com/cdrage/dockerfiles) all my containers are stuck on "Queue".

Pressing cancel does nothing.

Anyone else getting these issue(s)?

**Comment by omani** [comment]
yes me. docker hub is poorly programmed. sometimes the backend doesn't work. all you can do is get mad.

**Comment by MPJHorner** [comment]
Yah, but I pay. It still does this.

**Comment by roura356a** [comment]
Same here, paid account with parallel builds but nothing is getting built, all stuck and can't cancel them for hours.
