### ISSUE TITLE
Not able to connect a Docker container to MongoDB Atlas using uri connection string

### ISSUE THREAD

**Issue by juggydkorn** [docker/hub-feedback#1339]
I have a Linux VM in which Docker v18.0.0ce is installed.

I have a tomcat container in Docker with my java application installed on it. But when i try to use the connection string from the MongoDb Atlas in my database configuration file, its not even connecting to the MongoDb Atlas.

mongodb://smartdocs:******@cluster0-shard-00-00-ddxdd.mongodb.net:27017,cluster0-shard-00-01-ddxdd.mongodb.net:27017,cluster0-shard-00-02-ddxdd.mongodb.net:27017/test?ssl=true&replicaSet=Cluster0-shard-0&authSource=admin

The above is the connection string, i've replaced the ****** with my password and "test" with "admin" for database name.

**Comment by Shimwell** [comment]
Trying Docker and MongoDB Atlas for the first time and am also having this problem. It works from outside my Docker container but not inside

**Comment by juggydkorn** [comment]
@Shimwell Even i am trying since 1 week. if you find the solution please do let me know!!!!

**Comment by Shimwell** [comment]
Did you try the open all ports flag when running docker , I think it is -P

**Comment by juggydkorn** [comment]
Yes i did try that too.

**Comment by rdcm** [comment]
fix this problem with update net core runtime from 2.0 to 2.1 in project

**Comment by lanrion** [comment]
@rdcm How to fix?

**Comment by Asmau1234** [comment]
I wonder if anyone found a solution to this??

**Comment by lanrion** [comment]
fixed, check your **FROM**, and upgrade . alpine:3.11.6

**Comment by Asmau1234** [comment]
@lanrion i am using openjdk:8-jre-alpine
