### ISSUE TITLE
pip not found on image

### ISSUE THREAD

**Issue by Raphib737** [docker/hub-feedback#1340]
My dockerfile contains: 

FROM iron/python:2

WORKDIR /app
ADD . /app

RUN pip install --upgrade pip
RUN pip install -r ./requirements.txt

But when i run the image it gives this error:
/bin/sh: pip: not found
The command '/bin/sh -c pip install --upgrade pip' returned a non-zero code: 127

Any Suggestions?

**Comment by danmingyang** [comment]
why?

**Comment by thaJeztah** [comment]
Be aware that the iron/python image is not the official “python” image on docker hub; looking at that repository, I see the image hasn’t been updated for two years, so I’d discourage using it, unless there’s a specific reason to use that image.


I recommend using the official Python image instead; https://hub.docker.com/_/python/
