### ISSUE TITLE
Remove project from automated builds

### ISSUE THREAD

**Issue by rtfpessoa** [docker/hub-feedback#1344]
I have a [project](https://hub.docker.com/r/codacy/teamcity-agent/) which is an automated build.
Due to some requirements in versions and speed of builds in the hub we decided to use CircleCI to build and push to the hub.

Currently we disabled the trigger and it did the trick. What happened is that DockerHub still shows a [Dockerfile](https://hub.docker.com/r/codacy/teamcity-agent/~/dockerfile/) that is outdated and wrong causing confusion to people checking this image. The correct version should be [this one](https://github.com/codacy/teamcity-docker-agent/blob/master/Dockerfile)

How can I make this a normal image without removing the repo and loosing all the versions?

**Comment by bcardiff** [comment]
I share the same concern. Initially make a repo automated, but the project evolve and now the image are pushed from CI after some automated testing.

I would like to know how to remove the "automated build" status of a repo without loosing the current images.

**Comment by marius311** [comment]
> Initially make a repo automated, but the project evolve and now the image are pushed from CI after some automated testing.

I am in the identical situation. Did you by chance find a way to do this?

**Comment by bcardiff** [comment]
@marius311 , no I didn’t. On a repo with small history I deleted it and after recreation I uploaded manually the old docker images/tags.

That is as good as it gets. But downloading and pushing images using docker cli is straight forward.
