### ISSUE TITLE
List Organizations with docker hub API

### ISSUE THREAD

**Issue by Akhilkm** [docker/hub-feedback#1346]
I couldn't find a way to list down the Organizations in my docker hub account using version 2 API . Is there any way to do that.?

**Comment by vvrlw** [comment]
Is there an update on the issue ?

**Comment by trungutt** [comment]
Sorry for being late for the response. Actually the documentation is quite unclear about it but it's figured in [our public roadmap](https://github.com/docker/roadmap/issues/20).

I put a little script below, hope that could help.

```bash
#!/bin/bash

UNAME=""
UPASS=""

set -e
echo

TOKEN=$(curl -s -H "Content-Type: application/json" -X POST -d '{"username": "'${UNAME}'", "password": "'${UPASS}'"}' https://hub.docker.com/v2/users/login/ | jq -r .token)

echo ${TOKEN}

# get list of repos for the user account
ORGS_LIST=$(curl -s -H "Authorization: JWT ${TOKEN}" https://hub.docker.com/v2/user/orgs/?page_size=100 | jq -r '.results|.[]|.orgname')

for i in ${ORGS_LIST}
do
  echo $i
done
```
