### ISSUE TITLE
Merge apachesling/sling into apache/sling

### ISSUE THREAD

**Issue by rombert** [docker/hub-feedback#1357]
Hi,

For the [Apache Sling](https://sling.apache.org/) project we've initially pushed a docker hub image at https://hub.docker.com/r/apachesling/sling/ . However, it later became possible to host it under the official apache account at https://hub.docker.com/r/apache/sling/ .

We'd like to stop using the `apachesling/sling` image and ideally redirect people to `apache/sling`. Is there a way to do that?

**Comment by rombert** [comment]
Not stale, thanks for considering.

**Comment by rombert** [comment]
https://github.com/docker/hub-feedback/issues/1357#issuecomment-836361739

**Comment by rombert** [comment]
https://github.com/docker/hub-feedback/issues/1357#issuecomment-836361739

**Comment by milosgajdos** [comment]
Hi @rombert. Sorry about the super late response :-(

This isn't currently possible via Hub, I'm afraid.

**Comment by rombert** [comment]
Thanks for the info @milosgajdos , I'm going to close this then.
