### ISSUE TITLE
Crashed automated build

### ISSUE THREAD

**Issue by patterns** [docker/hub-feedback#1369]
My Docker Hub automated build for patterns/wordpress:gcp was stuck. I tried: 

- Cancel
- New github push which resulted in a Queued build that was blocked by the first
- Wait an hour
- Create a new automated build patterns/k8swp which became Queued and blocked
- Delete the entire patterns/wordpress automated build repository

Now the new patterns/k8swp automated build is still showing Queued.

**Comment by NicolasDorier** [comment]
Same problem here https://hub.docker.com/r/nicolasdorier/btcpayserver/builds/bxdf8xejrwp3x6mjn7ixzzp/

**Comment by NicolasDorier** [comment]
This one pending for 2 or 3 hours :(

https://hub.docker.com/r/nicolasdorier/btcpayserver/builds/bxdf8xejrwp3x6mjn7ixzzp/

**Comment by ttskch** [comment]
Me too... maybe same as https://github.com/docker/hub-feedback/issues/1352

**Comment by bsideup** [comment]
Same
https://hub.docker.com/r/bsideup/liiklus/builds/b6jchr2jtjetw2zncgthc7n/

**Comment by patterns** [comment]
Closing this issue, Auto-build is normal again.

**Comment by pytely** [comment]
Reopen in again, please.
