### ISSUE TITLE
I cannot regist. The signup button is gray!

### ISSUE THREAD

**Issue by dfmaster** [docker/hub-feedback#1378]
When I signup, cannot regist. The signup button is gray!  I cannot click it.
Why?
No any prompt
Help!!!
Id: datafusionmaster
email: ldfq@163.com
password: forexample1234@THIS
My explorer is chrome.

**Comment by xavierguihot** [comment]
Same for me on MAC:
Version 66.0.3359.139 (Official Build) (64-bit)
Had to use another browser to sign up.
In another browser, contrary to Chrome, the captcha appears.

**Comment by Mirror1211** [comment]
I have the same issue.

**Comment by liuguoguo** [comment]
I met the same problem. I tried Chrome, Edge. The signup button is always grey.

**Comment by asuraphel** [comment]
This is crazy. Sign up problem not solved for months!!

**Comment by mahidul-islam** [comment]
Still sign up problem on... tried for 3 days...

**Comment by asule90** [comment]
got [this](https://github.com/docker/hub-feedback/issues/1304#issuecomment-401976448) easy trick, wonderful :laughing: 
just inspect the button and remove the disabled attribute.

**Comment by Caihonghua** [comment]
> This is crazy. Sign up problem not solved for months!!

very crazy
