### ISSUE TITLE
Sudden "Account not active yet" message

### ISSUE THREAD

**Issue by adegtyarev** [docker/hub-feedback#1388]
I have just got my Docker Hub account & projects totally disappeared by an unknown reason.  The account was active until the system started to reject correct username and password with:
> Account not active yet. Please check your email to activate your account.

Help please?

**Comment by nandhini915** [comment]
We have been deactivating accounts reporting supicious activity - your account might have gotten flagged as a false positive, we will review and reinstate your account.

**Comment by nandhini915** [comment]
Your account is reinstated. We apologize for the inconvenience.
