### ISSUE TITLE
Ability to view enhanced information about Tags

### ISSUE THREAD

**Issue by n0mer** [docker/hub-feedback#139]
Currently it is not possible to see when each tag was pushed.

Please display it somewhere - on push log or on tag list.

**Comment by jakirkham** [comment]
+1

**Comment by n0mer** [comment]
generalized version of this ticket #344

**Comment by ChristopherBiscardi** [comment]
Various information is useful here (last pushed, size, image ids). We are investigating adding some additional set of information to the Tags page.

**Comment by n0mer** [comment]
@ChristopherBiscardi that's cool - and how far this investigation proceeded for 3.5 months since Jul 29 2015?

**Comment by n0mer** [comment]
ideally - just display results of "docker inspect _image_id", and maybe push history for recent push operations (date/time in user's timezone, who did this push). Anything that is above size and image tag name

**Comment by kenwdelong** [comment]
+1.  The time the tag was pushed, and the github tag (if any) it was built from would be fabulous.

**Comment by kop** [comment]
+1.
This is a very important feature to have. I'd say it's even critical for Docker community.

Today I was thinking about what is the most annoying thing in DockerHub for me. And the answer is that it's the way how we extend images. There are tons of similar images from different maintainers that are doing pretty much the same stuff. The only difference is base libraries versions (e.g. OS version, NodeJS/Python/PHP/Ruby version, etc) and whether images are supported or not.

The reason why there are so much dead (unsupported) images is that there is no easy way to update an image when base image is updated. Yes, we have repository links, but it works well only for `latest` tag. What if base repo added a new tag version and you want to make sure that your extended image will add that tag automatically too?

Let me give you an example from real word. We have `node` image. And I want to create a new image `node-supervisor` wich will just install one additional package and will change `CMD` instruction. But I want it to be something useful for the community and support all tags from the `node` image (e.g. when `node` will add a tag `v6`, `node-supervisor` should add that tag too). How can I do it without a lot of manual work or without coding some bots? There is no way.

So I came to an idea of service (in fact I'd like more to have it within DockerHub) that will allow the user an easy way to extend images. You just write a simple universal Dockerfile that extends a base image and service will give you an automated build which will be in sync with the base image.

So how all this related to the current issue? Well. How such service should track whether a tag has been updated? Current repository API (v2) gives no info about tag push time. Means there are no way to fetch new image releases.

**Comment by andebor** [comment]
It this ever going to happen? It still amazes me how limited the information available in docker hub is.

**Comment by kurtwheeler** [comment]
Is this a WontFix? It's been 2.5 years...

**Comment by meticulous-dft** [comment]
Hi @jfleck1 Thanks for the suggestion, will do that. Will also also try to surface git repo related info if using docker automated build.

**Comment by meticulous-dft** [comment]
We will be looking to add more tag related info. Right now a detailed timestamp is surfaced as tooltip for each tag.
