### ISSUE TITLE
Add the docker version somewhere in hub.docker.com

### ISSUE THREAD

**Issue by jmaitrehenry** [docker/hub-feedback#1391]
Hi, it could be great to have the docker version used for the builds somewhere.

Today, I register a new automated build with the `COPY --chown` flag added in Docker 17.12.0, but this flag is not yet available on Docker Hub.

The same thing happened in the past with multi-stage build.

Thanks!

**Comment by t3easy** [comment]
Just seen Docker's Cloud infrastructure is at 18.03.1.
