### ISSUE TITLE
Dockerfile Location not honoured

### ISSUE THREAD

**Issue by sylr** [docker/hub-feedback#1394]
Hi,

I've the following automated build settings :

type | name | Dockerfile Location | Docker Tag Name
---- | ----- | ------------------- | ------------------
branch | master | / | latest
branch | master | DockerfileDebug | latest-debug

If you look at this build https://hub.docker.com/r/sylr/unsee/builds/b4pmatumgcvd22pfczkq9ek/ you'll see in the `Dockerfile` section the content of **DockerfileDebug** but the `Logs` outputs show that it is the **Dockerfile** that is really executed (In the **DockerfileDebug** there is no copy to gcr.io/distroless/base:latest). 

Regards.

**Comment by sylr** [comment]
CC @ChristopherBiscardi @nhsiehgit

**Comment by nhsiehgit** [comment]
Lol sorry @sylr neither of us are at docker anymore.
Not sure who's maintaining this anymore.

cc @kristiehoward

**Comment by ChristopherBiscardi** [comment]
Kristie's not there anymore either :p Don't have a clue who to route this to. /me unsubs

**Comment by sylr** [comment]
I've tried removing `./Dockerfile` to see docker hub honours Dockerfile location if no default Dockerfile found: 

```
Building in Docker Cloud's infrastructure... Cloning into '.'... Executing build hook... unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /src/b49gbvtzj4unpfap2bqbcya/Dockerfile: no such file or directory build hook failed! (1)`
```
