### ISSUE TITLE
Fraudulent/Malware links in Repos

### ISSUE THREAD

**Issue by ironsalsa** [docker/hub-feedback#1395]
Hello Docker!

Is there a place to report obviously fake/possibly malicious repos? I ran into a few today that have some transparently risky links, and would like to flag them or whatever Docker Hub does for breaches of ToS. Here's the "users" I've found so far:
- https://hub.docker.com/u/vefonozeq/
- https://hub.docker.com/u/izukici/

**Comment by Nobody84** [comment]
I also recognized this some weeks ago, and today again. So I decided to extend the list.

- https://hub.docker.com/u/ilona90/

**Comment by thaJeztah** [comment]
Thanks for reporting; passing these on to the team

**Comment by manishtomar** [comment]
Thanks for reporting. The accounts have been deactivated.
