### ISSUE TITLE
docker build failed due to .gz files

### ISSUE THREAD

**Issue by tatianamc** [docker/hub-feedback#1398]
Hi, 
I try to build a docker  image for freqtrade program. It contains ta-lib files with .gz extension. Please advise how should i deal with this error? 
[freqtrade xxxx$ docker build -t freqtrade .
Sending build context to Docker daemon  28.16MB
Step 1/11 : FROM python:3.6.2
 ---> 26acbad26a2c
Step 2/11 : RUN apt-get update && apt-get -y install build-essential && apt-get clean
 ---> Using cache
 ---> 74126ef10bcb
Step 3/11 : RUN curl -L http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz |   tar xzvf - &&   cd ta-lib &&   ./configure && make && make install &&   cd .. && rm -rf ta-lib
 ---> Running in 6a5b8a81668b
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   551  100   551    0     0   4495      0 --:--:-- --:--:-- --:--:--  4516

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
The command '/bin/sh -c curl -L http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz |   tar xzvf - &&   cd ta-lib &&   ./configure && make && make install &&   cd .. && rm -rf ta-lib' returned a non-zero code: 2
(url)

**Comment by thaJeztah** [comment]
Sourceforge is having severe issues currently, so likely related to that; check their twitter account for status updates; https://mobile.twitter.com/sfnet_ops

![img_0770](https://user-images.githubusercontent.com/1804568/36940288-7d62c66a-1f40-11e8-9039-761ab29ef0d4.PNG)
