### ISSUE TITLE
Not all comments visible in repository

### ISSUE THREAD

**Issue by davidwilliamson** [docker/hub-feedback#14]
OS X Yosemite
Chrome 43.0.2357

Task 1 is to locate the official ubuntu repository. Once located, the bottom contains a comments section. As of this writing, the page says there are 47 comments, yet only the first (oldest?) ten comments are visible on the page, with no navigation buttons to see the remaining comments.

Moreover, since the comments appear to sort from oldest to newest, any newly created comments cannot be seen--so I cannot test whether new comments can be created.

Update: it appears that the comments database is shared with the production hub. I just saw my comment on the production hub ubuntu page.

**Comment by ChristopherBiscardi** [comment]
Comments are currently sorted in the wrong time-direction *and* have no pagination. Both of which are bugs.

**Comment by William-Olson** [comment]
bump.

Yes, I would like to see the newer comments as well.  This is still not fixed.
Looks like pagination is making progress though, yay!

###### Side Note: the pagination that is implemented in some areas needs some updates badly, all it shows is the current page number and right/left arrows (can't tell if there is 3 or 300 pages to step through.. oh yeah and incrementally 1 at a time? --> lame).

**Comment by ChristopherBiscardi** [comment]
@William-Olson We are working on the pagination 1-at-a-time issue. The current issue is related to the `count` being removed from the API we were using and thus, we do not actually know much beyond "there is a next page" and "there is a previous page".

**Comment by tianon** [comment]
The "Comments" functionality appears to now be completely gone from Docker Hub, which renders this issue obsolete! :tada: :heart:
