### ISSUE TITLE
freeradius org namespace taken

### ISSUE THREAD

**Issue by nwwells** [docker/hub-feedback#1401]
I think it's clear that the freeradius namespace should be in the hands of the FreeRADIUS project. It's unclear who currently owns it, but they have published a repository and no tags. I'm working with the [freeradius team to get images on Docker Hub](https://github.com/FreeRADIUS/freeradius-server/issues/2188#issuecomment-370371614) and it would help if we could use that org name.

Note that I don't necessarily belong in the org, but at least @arr2036, @mattrose and @mcnewton do.

**Comment by thaJeztah** [comment]
I'd recommend someone from the freeradius org to contact support@docker.com; they should be able to see who currently owns the name on Docker Hub.

**Comment by mcnewton** [comment]
I'll drop them a line, thanks.

**Comment by mcnewton** [comment]
All sorted, thanks. This can be closed.
