### ISSUE TITLE
It's not an issue. Just a question

### ISSUE THREAD

**Issue by sdewsr** [docker/hub-feedback#1405]
Hello.

What does mean the Parallel Builds here https://hub.docker.com/billing-plans/ ? I don't understand.

Thank you.

**Comment by thaJeztah** [comment]
parallel builds means the number of automated builds for your repositories that can be running at the same time. By default, only one automated build can be running, so if multiple automated builds are started, each one will have to wait for the previous build to finish. With more parallel builds, those automated builds can run at the same time (without having to wait for the previous one to finish)
