### ISSUE TITLE
Malicious entries

### ISSUE THREAD

**Issue by janwerner** [docker/hub-feedback#1415]
I think a link to report malicious uploads to Docker Hub should be provided.

This entry is definitely not legit:

[https://hub.docker.com/r/mevaj/tableau-dashboards/](https://hub.docker.com/r/mevaj/tableau-dashboards/)

**Comment by jmwong** [comment]
Thanks for the report. We've disabled the reported repos.

**Comment by janwerner** [comment]
Well, that only took you 4 months ... not good. What's the proper way to report malicious repos so they get removed quickly?
