### ISSUE TITLE
malicious entries

### ISSUE THREAD

**Issue by gabiera** [docker/hub-feedback#1417]
https://hub.docker.com/u/docker123321/

Images on this hub are definitely not what they say they are.

**Comment by nandhini915** [comment]
@gabiera could you elaborate on why you think these are malicious entries?

**Comment by fortiguard-lion** [comment]
Please check that blogpost it's related to the same attack https://www.fortinet.com/blog/threat-research/yet-another-crypto-mining-botnet.html

**Comment by jmwong** [comment]
Thanks for the report. We've disabled the user above.
