### ISSUE TITLE
Feature Request: DockerHub Auth Token for third party apps

### ISSUE THREAD

**Issue by ankitvgupta** [docker/hub-feedback#1419]
I'm hoping to use DockerHub with CircleCI to host private images and run builds. Right now, to do this, I have to put my DockerHub username and password in CircleCI, as explained here: https://circleci.com/docs/2.0/private-images/

Instead of this, is there a way to add an Auth token that I can share with CircleCI and not other applications? I'd rather not store my password in plain text everywhere.

**Comment by damm** [comment]
Amazing this issue has been idle for so long with no comments.  Please after getting docker hub usernames leaked this would have been a lifesaver 

Now I have to cycle my passwords and re-put them back into my CI and wait for you guys to get hacked again :(

Not right

**Comment by anguslees** [comment]
To put this in perspective: This is the primary reason I use quay.io to host images that I build externally (not using dockerhub's autobuilder)

**Comment by meticulous-dft** [comment]
This item is our top priority.

**Comment by ruffsl** [comment]
Any official response? I'd rather like to avoid having to create machine user/accounts for everything little thing and adding it to my team/org for it to gain access to our docker repositories. Such workarounds are not very tidy: https://stackoverflow.com/questions/41834554/access-token-for-dockerhub

**Comment by damm** [comment]
From the lack of response I would say quay.io is looking real good sure it's not free but https://docs.quay.io/glossary/access-token.html

**Comment by meticulous-dft** [comment]
Please use personal access tokens for CI systems. https://docs.docker.com/docker-hub/access-tokens/

**Comment by ankitvgupta** [comment]
Oh, has this always existed? Thanks very much - this is exactly what I wanted.

**Comment by ankitvgupta** [comment]
Ah, I see it's a new feature! Awesome job folks!
https://blog.docker.com/2019/09/docker-hub-new-personal-access-tokens/

**Comment by lizrice** [comment]
It's not a huge deal, but it would be nice if you could generate these access tokens for an organization so that they aren't just associated with and managed by a personal account

**Comment by ruffsl** [comment]
@lizrice , yep the personal access tokens don't seem to resolve the issue in having to make and endorse personal machine accounts to integrate third party services. This really complicates management of these services within an organization.

**Comment by ankitvgupta** [comment]
fwiw, I think this is the way Github does things too: https://developer.github.com/v3/guides/managing-deploy-keys/#machine-users

A little lame to have to pay for an extra seat to do this though.

**Comment by thaJeztah** [comment]
For further enhancements in this area, I'd recommend opening a ticket in our public roadmap; https://github.com/docker/roadmap. Try to describe your use-case, and why the current implementation does not match your use-case.
