### ISSUE TITLE
Highlight the whole "Docker Pull Command" by default

### ISSUE THREAD

**Issue by marcusmartins** [docker/hub-feedback#142]
It would be nice to be able to be able to select the whole docker pull command when double clicking on the input field instead of selecting individual words.
![Image]
(https://photos-6.dropbox.com/t/2/AADZHw80lqwb_kPz9p8t6pjIxqeSpXCzexozOlZDwG81xg/12/83577/png/32x32/1/1438304400/0/2/Screenshot%202015-07-30%2016.19.29.png/CPmMBSABIAIgAyAEIAUgBiAHKAEoAigH/7SzG1VK8Ur_PgNKA2jacAi1bdFLvUx2WhXhFypx78OE?size=2048x1536&size_mode=2)

That is the current behavior on the current Hub site and it makes easier to c&p to the CLI.

**Comment by ChristopherBiscardi** [comment]
@marcusmartins you can triple click to select the whole line for now. 

Ideally we'd have "click to copy", but [the problem](http://caniuse.com/#feat=clipboard) is

![screenshot 2015-07-30 23 05 14](https://cloud.githubusercontent.com/assets/551247/9001693/84fc8a6c-370f-11e5-9720-e028ad5e487c.png)

 It is typically implemented by using Flash and the current status of Flash on the team is roughly summarized as "nope".

We'll have to do some investigation into enabling click-to-copy type functionality.

**Comment by jakirkham** [comment]
+1 for the feature. +1 for staying away from Flash.

**Comment by jakirkham** [comment]
It looks like something was done on this front and it looks nice. 

<img width="441" alt="screen shot 2015-10-06 at 10 44 03" src="https://cloud.githubusercontent.com/assets/3019665/10311995/35c24dfa-6c17-11e5-8624-addefd19dae8.png">

Was this react.js?

**Comment by kristiehoward** [comment]
Closing as this is in production. 

Clicking on the input automatically selects the entire field. Clicking on the `copy` icon copies the command (in supported browsers like Chrome and Firefox 41+) and selects the entire command (if copying is not available) for easier manual copy/pasting if the browser does not support it. No Flash used :+1:
