### ISSUE TITLE
Can't get kubectl to pull from private docker hub repo

### ISSUE THREAD

**Issue by iDVB** [docker/hub-feedback#1424]
I want to rule out the docker permissions side of things.
I've ensured the proper user pass and email by logging into my account on the website.

I'm running this to create my secret...
`kubectl create secret docker-registry regcred --docker-server="https://index.docker.io/v1/" --docker-username=MYUSER --docker-password=MYPASS --docker-email=MYEMAIL`

I've also tried without the `docker-server` arg. 

I continue to get `ErrImagePull` from Kube. 

Which user should go into the `docker-username`? I'm using the one that I login with both on the site and on my local machine with `docker login`.

**Comment by joshbrw** [comment]
I'm having the same issue, did you manage to resolve it?

**Comment by emmasteimann** [comment]
Ditto. Same issue. Any insight?
