### ISSUE TITLE
Automated Builds failing to push: toomanyrequests: too many failed login attempts for username or IP address

### ISSUE THREAD

**Issue by ju2wheels** [docker/hub-feedback#1436]
I have seen other issues about this, but in my case, these are automated build and im not trying to login remotely so its not me actually causing the error by trying to login but rather the automated build itself trying to login to push. Others have suggested characters in the password could be at fault in other reports of the issue, but obviously in this case  this is Docker Hub internal login so that wont help.

```
Pushing index.docker.io/ju2wheels/ansible:2.x-ubuntu-12.04...
Push failed. Attempt 2 in 60 seconds.
Push failed. Attempt 3 in 60 seconds.
Push failed. Attempt 4 in 60 seconds.
Push failed. Attempt 5 in 60 seconds.
{u'message': u'toomanyrequests: too many failed login attempts for username or IP address'}
```

Its happening for a large number of my automated builds.

**Comment by branepar** [comment]
Have same issue.
Does anyone know what criterias Docker Hub use to trigger "toomanyrequests"?
As customer we dont even have access to any log to look at what login attempts have been done. So very hard to find out with X number of build servers and X number of swarms using the same docker account (might be a fault in itself to reuse the same account, but anyway the definition of the limitation should be public)

**Comment by Gaura** [comment]
Did anyone solve the issue?
