### ISSUE TITLE
queue and build is taking forever

### ISSUE THREAD

**Issue by bill12252016** [docker/hub-feedback#1437]
it's waiting in queue for over 30 minutes.  it's building for over an hour.  how do you report these problems when you can't call?  i have a paid account for my private registries.  thanks!

**Comment by dis1** [comment]
I have same problem. After 3 hours of waiting I got "Unexpected error"

**Comment by marcelkobainGIT** [comment]
+1

**Comment by cmsalmeida** [comment]
It's giving that error in a version that was being build before.
No logs or errors reported in Build Details, except "Unexpected error".

**Comment by MPJHorner** [comment]
👍  +1, I also pay not happy that I have these issues. Can't deploy..

**Comment by adegtyarev** [comment]
+1 here, some automated builds got into a stale state "Queued". "Cancel" button not working too, so there is no way to update hosted software for a few days now.  🤔

**Comment by stepansib** [comment]
Same for me ( Cant cancel queued builds and cant trigger new ones. 
Build queued status is still showing for three days

**Comment by johnshew** [comment]
Gave up and switched to Azure DevOps to automatically do the build and deploy to Docker Hub.  It is also free and seems more reliable currently.
