### ISSUE TITLE
can edit official image's details

### ISSUE THREAD

**Issue by cpuguy83** [docker/hub-feedback#144]
I'm not sure I should be able to edit the details of an official image from the GUI, even if I do have some extra rights not granted to a normal user.

![screen shot 2015-08-03 at 3 16 39 pm](https://cloud.githubusercontent.com/assets/799078/9045656/d73e9e4c-39f2-11e5-902b-961366eb047e.png)

**Comment by rrarunan** [comment]
@cpuguy83 this feature is in parity with the current hub at the moment. Admin/staff do have access to edit the official repositories (Just an FYI). We need to discuss this further though.
