### ISSUE TITLE
Docker System Status is inaccurate / misleading

### ISSUE THREAD

**Issue by cwedgwood** [docker/hub-feedback#1440]
As experienced and reported by many people in #1203, #1237, #1238 builds are failing with an `Unexpected Error` message.

The https://status.docker.com/ claims things are `Operational` though that is not the case.

However this metric is derived it seems there is room for improvement.

**Comment by cmsalmeida** [comment]
It's true, I've spend some hours trying to figure it out.
But it's giving that error in a version that was being build before.
No logs or errors reported in Build Details, except "Unexpected error".

**Comment by nandhini915** [comment]
Closing this issue since operational errors were identified and resolved.
