### ISSUE TITLE
Docker Hub's automated builds are not working

### ISSUE THREAD

**Issue by jhsu802701** [docker/hub-feedback#1441]
Docker Hub automated builds are not currently working.  I get the message "Unexpected error" with no log that I can use to troubleshoot.

https://hub.docker.com/r/rubyonracetracks/debian-stretch-jekyll-general/builds/

**Comment by fia5000** [comment]
Seeing the same thing

**Comment by tarunmittal** [comment]
Seeing the same thing on my private Repos.

**Comment by cmsalmeida** [comment]
Same thing, I've spend some hours trying to figure it out.
But it's giving that error in a version that was being build before.

**Comment by thuandt** [comment]
I have same problem since yesterday. Any update?

**Comment by juliangut** [comment]
I'm facing a similar problem, builds are frozen in "queued" and I cannot cancel them

Is there someone giving support? or we just have to pay for support on such a matter that "should just be working"?

**Comment by tyranron** [comment]
>>>
builds are frozen in "queued" and I cannot cancel them
>>>

The similar issue is here:

https://hub.docker.com/r/instrumentisto/roundcube/builds/  
https://hub.docker.com/r/kahlan/kahlan/builds/

Even more, __we cannot release new tags for that builds__ as "queued" blocks the whole branch and __re-triggering build just doesn't work__.

**Comment by juliangut** [comment]
@Alexwijn Two months man!! are you serious? what is going on here?? nobody cares???

**Comment by tyranron** [comment]
@juliangut it seems that yes. 😕No answers [on Slack](https://dockercommunity.slack.com) too.

**Comment by tyranron** [comment]
__Update:__ [the issues is solving](https://dockercommunity.slack.com/archives/C7GKACWDV/p1523472998000112):

> HI @tyranron we are looking at it and hope to have an update soon.

**Comment by juliangut** [comment]
I'm not in the slack channel, please @tyranron keep up posted

**Comment by HenryQW** [comment]
# Automated build never worked for me since Aug 2016

This is just unbelievable. I tried everything possible, even created another pair of accounts on GitHub and Docker Hub.

I have to setup GitHub webhook which posts to Docker Hub `Build Triggers` manually, but that triggers every build settings I've got.

**Comment by tyranron** [comment]
It seems that issue is resolved. All stuck `Queued` builds are `Errored` now and can be re-triggered.

**Comment by juliangut** [comment]
Indeed queued builds are now errored, I've just re-triggered the builds, if it all goes well we should close this issue and #1454 too

**Comment by tyranron** [comment]
ping @jhsu802701

**Comment by CrimsonGlory** [comment]
I had one frozen tag (pushes did not triggered a build). The fix was to delete and re-create the tag.

**Comment by wader** [comment]
Remove whole build and recreate it fixed it for me

**Comment by Alexwijn** [comment]
And it's stuck again...

**Comment by acirulis** [comment]
I am also having 4 days old build, which is queued with "Unexpected error". Cannot cancel, cannot retrigger. Tried to remove and add all automated builds, no luck.

**Comment by juliangut** [comment]
I got the automated builds working just after my last comment on this issue, about a month ago, what I've just noticed is that automated build doesn't work for linked repositories, when a linked is updated my build is not triggered automatically

Anyone facing this?
