### ISSUE TITLE
Recover Docker Hub account

### ISSUE THREAD

**Issue by kinghuang** [docker/hub-feedback#1444]
I'm trying to recover the [oildex](https://hub.docker.com/u/oildex/) account on Docker Hub. Not sure of the email address used to register, so can't use the reset password page. I emailed support@docker.com last Tuesday and got an auto-reply support ticket number, but haven't heard anything further. Is there some other way to recover the account?

**Comment by nandhini915** [comment]
I'm assuming you've been able to recover your account. Letting Docker Support know is the right thing to do. Please open another ticket if you continue having an issue.
