### ISSUE TITLE
Pulls are extremely slow in eu-west-3 and on our local network

### ISSUE THREAD

**Issue by elafarge** [docker/hub-feedback#1449]
Hello,

For the past two hours, image pulls from DockerHub have been really slow (under 1MiB/s) in both the `eu-west-3` AWS region and on our local network.
Pulls from other repositories (quay.io, gcr.io and ECR) work fine.
Is there an outage on your end ?

**Comment by chrissound** [comment]
I'm getting 0.5MB/s over here with the `fpco/stack-build:latest` image.
