### ISSUE TITLE
Collaborators Page missing Data

### ISSUE THREAD

**Issue by cpuguy83** [docker/hub-feedback#145]
See the linked video for details
https://s3.amazonaws.com/files.container42.com/hub-beta-official-image-page-links-issues.mov

**Comment by ChristopherBiscardi** [comment]
The Collaborators page is throwing due to missing data:

<img width="1428" alt="screenshot 2015-08-03 13 30 42" src="https://cloud.githubusercontent.com/assets/551247/9047053/040f82ba-39e4-11e5-8664-575d24ec135e.png">

**Comment by nhsiehgit** [comment]
slightly related: https://github.com/docker/hub-feedback/issues/351
