### ISSUE TITLE
Unexpected Error - Build Never Completes

### ISSUE THREAD

**Issue by rcoundon** [docker/hub-feedback#1454]
I have an automated build set up from GitHub to a private repository.  This was triggered 4 hours ago and the UI still shows 'Building'.  If I click on 'Building' I get 'Unexpected Error'

**Comment by roura356a** [comment]
Same here. Can't cancel and can't make them work.

**Comment by diasgurjao** [comment]
Same here, it's been five hours.

**Comment by everflux** [comment]
I have the same with two public repos, can not cancel nor schedule a new build.
https://hub.docker.com/r/trion/ng-cli/builds/
https://hub.docker.com/r/trion/ng-cli-e2e/builds/

**Comment by juliangut** [comment]
Same situation here for 5 days (https://hub.docker.com/r/juliangut/phpdev/builds/)
I was able to cancel 2 builds but the rest are still frozen, and I can bump new builds. What is happening?

**Comment by tyranron** [comment]
It seems that issue is resolved. All stuck `Queued` builds are `Errored` now and can be re-triggered.

🎉🎉🎉🎉

**Comment by tyranron** [comment]
ping @rcoundon
