### ISSUE TITLE
Unable to connect to my docker hosted mssql

### ISSUE THREAD

**Issue by csamleong** [docker/hub-feedback#1455]
have a problem followng this tutorial where i try to connect to my docker hosted MSSQL via sqlcmd. https://hub.docker.com/r/microsoft/mssql-server-linux/

I executed the following:

docker run -e 'ACCEPT_EULA=Y' --name mssql -e 'SA_PASSWORD=yourStrong(!)Password' -p 1433:1433 -it -d microsoft/mss ql- server-linux:latest /bin/bash

Note: "-it" and "/bin/bash" is added due to docker will be stopped automatically if there is no any activity detected.

I ran docker container ls -a, i got:
![snap 2018-04-06 at 14 32 59](https://user-images.githubusercontent.com/27395698/38407163-fb622400-39aa-11e8-8982-57f494dbcad7.png)

It is running. I ran telnet local-ip:1433 on my host, it is working fine.

Problem lies when i do the following:

> docker exec -it mssql /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P yourStrong(!)Password

Error:

> Sqlcmd: Error: Microsoft ODBC Driver 17 for SQL Server : Login timeout expired. Sqlcmd: Error: Microsoft ODBC Driver 17 for SQL Server : TCP Provider: Error code 0x2749. Sqlcmd: Error: Microsoft ODBC Driver 17 for SQL Server : A network-related or instance-specific error has occurred while establishing a connection to SQL Server. Server is not found or not accessible. Check if instance name is correct and if SQL Server is configured to allow remote connections. For more information see SQL Server Books Online..

I also tried to connect in using powershell via my host Link:https://docs.microsoft.com/en-us/sql/linux/quickstart-install-connect-docker

Command:

> sqlcmd -S 192.168.0.110,1433 -U SA -P yourStrong(!)Password

Note: 192.168.0.110(got this from running ipconfig in host machine.)

Any help ? Thanks

**Comment by thaJeztah** [comment]
Docker Hub is only hosting those images, but does not provide support for the image itself; the MS SQL Server image is built by Microsoft; issues can be reported here: https://github.com/Microsoft/mssql-docker/issues
