### ISSUE TITLE
Multiple tags in docker cloud don't work with hooks

### ISSUE THREAD

**Issue by SkeLLLa** [docker/hub-feedback#1457]
Specifying multiple tags like `abc,abc-{sourceref},latest` cause build to fail with error:
```
Successfully tagged user/repo:abc
Pushing index.docker.io/user/repo:abc...
Push failed. Attempt 2 in 60 seconds.
Push failed. Attempt 3 in 60 seconds.
Push failed. Attempt 4 in 60 seconds.
Push failed. Attempt 5 in 60 seconds.
{u'message': u'tag does not exist: user/repo:abc-1.2.3'}
```
if build hook is present:
```
#!/usr/bin/env bash
docker build --build-arg=MY_ARG=123 -f $DOCKERFILE_PATH -t $IMAGE_NAME .
```

The only first tag is pushed and the whole build fails.

**Comment by puittenbroek** [comment]
I ran into this problem as well, it works fine for the `baseimage` I'm building.
But the `post_push` hook, which builds two other images based on this baseimage, only builds the first tag.. not the other tag(s).

**Current situation**

- Automated rule to build `baseimage`, docker tag: `test,test2`
- Build and tags `baseimage` with both 'test' and 'test2' tags
- `post_build` hook to build + push two other images (their Docker file's are in different directory in the same repo)
- Other two images are only tagged with 'test' tag.


**Expected situation**

- Automated rule to build baseimage, docker tag: `test, test2`
- Build and tags `baseimage` with both 'test' and 'test2' tags
- post_build hook to build + push two other images (their Docker file's are in different directory in the same repo)
- Other images are tagged with 'test' **and** 'test2' tags.
