### ISSUE TITLE
Latest tag image not being scanned. 

### ISSUE THREAD

**Issue by iantsai220** [docker/hub-feedback#1462]
Hi Guys,

I understand after March 31 Dockerhub will only perform Security Scan on image with Latest tag. However I don't see any scanned result. Anyone know how to get the Security scan results ?

Thanks

**Comment by nandhini915** [comment]
Per https://success.docker.com/article/scanning-deprecation-faqs - The preview security scanning for all private repositories has been removed. This includes removing visibility into any existing results via your private repositories.

Docker Security Scanning capabilities continue being available as part of our Docker Enterprise Edition container platform.
