### ISSUE TITLE
Some building can not be cancelled while some build never be triggered

### ISSUE THREAD

**Issue by winkingzhang** [docker/hub-feedback#1465]
I have an automated build project on docker hub, it was great and every well before I did change some triggers serval days ago, there are two confusing in the phenomenon, any ideas or workaround?

1. there are some builds can not be cancelled, the page reported me that cancelling was successfully accepted, but the build will be appeared again if I refresh page in next minutes.
![image](https://user-images.githubusercontent.com/1261918/38710846-d58bc0f2-3ef4-11e8-95d7-c56f7325bfbe.png)
the cancelling request in chrome
![image](https://user-images.githubusercontent.com/1261918/38710912-2eb1a372-3ef5-11e8-8b1c-08fc6bde4f6d.png)

2. some build never be triggered, I my case, the build trigger for tag 'RA-cn' was accepted, but build never started, this phenomenon first came in 5 days ago.
![image](https://user-images.githubusercontent.com/1261918/38711096-3238d794-3ef6-11e8-8379-953b72ced5eb.png)
while I manually triggered build by docker hub api, it gave me below error, seem some building were not in list.
![image](https://user-images.githubusercontent.com/1261918/38711135-7b93645e-3ef6-11e8-856c-2b8669c589a3.png)

**Comment by jakirkham** [comment]
Have also been running into this a lot lately. IDK what recourse there is other than get an admin to cancel the builds internally (which I have been unsuccessful at getting either). 😞

Not to mention, it seems that canceling queued builds causes them to end up in some weird limbo where they stay for ~24hrs and then finally error. It would be one thing if they had no other effect, but it seems these "Queued" builds block starting new ones as well, which really hurts usability of the service as a whole. 😢

Any help on this would be greatly appreciated.

**Comment by binhex** [comment]
https://github.com/docker/hub-feedback/issues/1352

**Comment by magwas** [comment]
I don't even see a way to cancel a build:
The build tab shows "BUILDING" where it lists tags, but there is no cancel button here.
After that there is a section of recent builds, but the current build does not show up.
