### ISSUE TITLE
Cannot trigger build manually or via push

### ISSUE THREAD

**Issue by dclong** [docker/hub-feedback#1467]
I have an automated-build docker image at https://hub.docker.com/r/dclong/conda/. I cannot trigger build manually or via GitHub push now!

**Comment by eddielisands** [comment]
Same here...

**Comment by mcedica** [comment]
same here

**Comment by winkingzhang** [comment]
Same here,  my issue #1465

**Comment by karalabe** [comment]
Another case where triggering fails: https://hub.docker.com/r/ethereum/client-go/builds/. Here docker hub properly triggers `latest` and `alpine-develop` but not `alltools-latest`. I can't manually trigger the offending one either.

**Comment by ChristophWurst** [comment]
Same here. Attempting to trigger a manual build gives me this API response:
![bildschirmfoto von 2018-04-17 16-01-24](https://user-images.githubusercontent.com/1374172/38874552-ab938638-4258-11e8-8533-af3745cbfe53.png)

> A build for tag latest is already pending. Ignoring request.

But the last build was triggered 10 days ago. There are no pending builds.

**Comment by goofball222** [comment]
Automated build system is definitely having issues. https://hub.docker.com/r/goofball222/unifi/builds/bfqkwcwpq74m5ksvlwtlpnp/ has been stuck "Queued" for ~24h at this point, unable to cancel.

Also had this build hang up, finally errored out or was cancelled on the hub side: https://hub.docker.com/r/goofball222/murmur/builds/bwxbaswqxk7vwdslm5ufvxk/

Not doing anything special, just auto-building tags based on git commits. My repositories and hub setups have been fine like this for months up to this point.

**Comment by cswl** [comment]
Having the same issue.. 
However I can trigger the builds from Docker Cloud..

**Comment by ChristophWurst** [comment]
> Having the same issue..
> However I can trigger the builds from Docker Cloud..

Thanks for the tip! I configured my automated builds on cloud.docker.com and now I can trigger new builds again.

**Comment by gdvalderrama** [comment]
@ChristophWurst I'm a bit unsure about the relation of the automated builds in Docker Hub and Docker Cloud.
I see my automated build from Docker Hub appears in Docker Cloud with no configuration (not linked to git repo, no trigger, etc), how did you manage this? Did you just configure the automated build in Docker Cloud too?

**Comment by ChristophWurst** [comment]
> I'm a bit unsure about the relation of the automated builds in Docker Hub and Docker Cloud.

I have no clue. It's the first time I'm using Docker Cloud ¯\\_(ツ)_/¯

> Did you just configure the automated build in Docker Cloud too?

Yes, that's what I did. Although now Docker Cloud creates my builds, they are not listed on Docker Hub's build page. It only shows that there was a recent push.

**Comment by burakince** [comment]
Same issue here...

**Comment by cswl** [comment]
Today I pushed to my github repo. And it showed build started on Docker hub..
It's also building on Docker cloud.. 

Dont know if the two are the same

**Comment by adegtyarev** [comment]
On 'Build Settings' tab on Docker Hub there is checkbox to disable automated builds on pushes. Just did that followed after migration to Travis + Docker Cloud, and got my CI workflow back to work again.

Bye-bye Docker Hub!

**Comment by zaga1** [comment]
My automated builds have also stopped working. Will try disabling and re-enabling the automated builds flag.

**Comment by zaga1** [comment]
Made no difference. Even manually triggering a build causes nothing to happen.

**Comment by karalabe** [comment]
You might want to contact support@docker.com with some details. They solved the issue for our builds.

**Comment by gdvalderrama** [comment]
@karalabe Lucky you, I wrote them an email 7 days ago and then another 2 days ago and I've received no answer whatsoever.

Could you share your solution? Or is it very specific to your case?

**Comment by karalabe** [comment]
There was nothing to do from my part really. They said they'll look into it, and a couple days later came back saying that they found and fixed the issue. I tried to trigger my stuck build, it worked.

**Comment by iolufemi** [comment]
This issue is still happening. I cannot trigger a build. Manually and via repository push.

**Comment by markg85** [comment]
2 years later..
I just had this very same issue.

Note that GitHub (due to the black lives matter) changes the master branch to **main** for new repositories.
Also note that docker hub by default tries the **master** branch still. It sadly gives no warning at all. It just allows you to name it as such and you can click the "trigger" button all you want, but nothing will work. Just when inspecting network data i happend to see a error message that the master branch could not be found.

So in my case changing to the **main** branch worked and fixed this whole issue for me.

**Comment by gdvalderrama** [comment]
@markg85 Hey Mark, that sounds like something Docker should change (change default to main), maybe you should open a new issue to address that.

**Comment by jeffheaton** [comment]
Ran into the same issue.  DockerHub really needs to either have a better error message, like can't find branch "master".  Or a more intelligent defaulting between "main" and "master" depending on the age of the repo, I guess.
