### ISSUE TITLE
It's all proprietary JavaScript

### ISSUE THREAD

**Issue by jorgesumle** [docker/hub-feedback#1477]
See the [problems with proprietary JavaScript](https://www.gnu.org/philosophy/javascript-trap.html), and it doesn't work with JavaScript disabled so there is no workaround for people who value software freedom.

**Comment by jorgesumle** [comment]
Docker Hub only works with JavaScript enabled, and that code isn't free software. You can make the source code free software in a Git repository or make the website so that it could work for people who don't surf with JavaScript enabled. That's the case for most text-based browsers (very used on servers), where you don't execute JavaScript and don't have a GUI.

**Comment by nandhini915** [comment]
Hi, As of now, we do not have plans to update Docker Hub so it can run without JS enabled. https://forums.docker.com should have community information on a potential analogous use of the Docker CLI - we would suggest this as an alternative.
