### ISSUE TITLE
SSL Certificate reporting invalid

### ISSUE THREAD

**Issue by bruskiza** [docker/hub-feedback#1479]
When doing an automated build on hub.docker.com,:

On build: https://hub.docker.com/r/bruskiza/speebee-reporter/builds/bejvdgnehdv2atl9saw5pbr/

It's failing with a report saying:

```Complete output from command python setup.py egg_info:
    Download error on https://pypi.python.org/simple/numpy/: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:661) -- Some packages may not be found!
    Couldn't find index page for 'numpy' (maybe misspelled?)
    Download error on https://pypi.python.org/simple/: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:661) -- Some packages may not be found!
    No local packages or working download links found for numpy>=1.9.0
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
```

Going directly to https://pypi.python.org/simple/numpy/ gives a valid certificate.

Strange indeed.

**Comment by brainwane** [comment]
https://warehouse.readthedocs.io/api-reference/integration-guide/#migrating-to-the-new-pypi might help; maybe there's a [TLS version issue](https://mail.python.org/pipermail/python-announce-list/2018-April/011885.html) and/or some component not being able to deal with the pypi.python.org -> pypi.org redirect.

**Comment by nandhini915** [comment]
Hi @bruskiza 
If you are a community user using our Docker Engine product, Please go to https://forums.docker.com/ and verify if other members in the community have run into this issue, or post an issue back to the community.
If you are a user with a subscription to Docker Enterprise, you can go to https://success.docker.com/ and obtain help.
