### ISSUE TITLE
Unable to share drive with Docker due to Windows Pin Login

### ISSUE THREAD

**Issue by MikkelVinther** [docker/hub-feedback#1480]
Hello, 

I have the issue that i am trying to set up docker on my work computer, that due to company policy does not have a password, but instead has a pin-code. 
This has resulted in my being unable to share my computers drive with docker, as it will only accept my non-existing password, and not my pin.
I have seen people work around similar issues, by creating a local user, with a password, on their computer. unfortunately i am also restricted from doing this, again, due to company policy. 
Does anyone, have any idea, on how i could possibly fix this? 

Thank you very much!

**Comment by nandhini915** [comment]
Hi @MikkelVinther 
If you are a community user using our Docker Engine product, Please go to https://forums.docker.com/ and verify if other members in the community have run into this issue, or post an issue back to the community.
If you are a user with a subscription to Docker Enterprise, you can go to https://success.docker.com/ and obtain help.

**Comment by vbisbest** [comment]
@MikkelVinther did you find a solution to this?
