### ISSUE TITLE
Please remove IP from blacklist

### ISSUE THREAD

**Issue by tehut** [docker/hub-feedback#1482]
Looks like dockerhub is blacklisting IP == 216.169.250.60.  It's the public IP coming out of our datacenter and currently blocking  a number of services.  Please help!

Related issues:
#1305 
#298

**Comment by nandhini915** [comment]
I believe your IP addresses should be unblocked by now. We have been receiving an increased rate of pulls from various sources - and as part of our mitigation strategy end up blocking IPs that appear to be strong offenders.
Closing this issue. If you continue having an issue with your pulls being blocked, please open a ticket and specify the IP you're getting blocked on.
