### ISSUE TITLE
docker unauthorized: authentication required - upon pulling a public image

### ISSUE THREAD

**Issue by arpanda** [docker/hub-feedback#1484]
I have created and uploaded a docker image in docker hub. I have made it public.
But sometimes, While pulling the docker image, I am getting the below error.

    unauthorized: authentication required
Need help to fix this issue of my docker image.

**Comment by sara-02** [comment]
@rjit17 Is it possible that you changed your DockerHub password in between pushing and pulling these images? Could that be the reason for `un-authorization`.  Can you do a `docker login` from CLI using your new credentials,  and then try pulling the image?

**Comment by rjit17** [comment]
I have made it as a public repository and tested on some PCs. Its working fine in those systems. But in some system, it showing that error.

**Comment by yassinechabli** [comment]
check your ~/.docker/config.json , change from : 
```
{
        "auths": {
                "docker.io": {
                        "auth": "XXXXX",
                        "email": "your email"
                }
        }
}
```

to 
```
{
        "auths": {
                "https://index.docker.io/v1/": {
                        "auth": "XXX",
                        "email": "your email"
                }
        }
}
```

**Comment by GuptaPiush** [comment]
It worked for me after checking the ~/.docker/config.json file..
Thanks,

**Comment by chrisdev2018** [comment]
I don't see directory ~/.docker/ on my machine
I'm using Ubuntu 18

**Comment by jonseymour** [comment]
I am seeing this error:

```
docker pull tryretool/backend:2.63.5
2.63.5: Pulling from tryretool/backend
e9afc4f90ab0: Already exists 
989e6b19a265: Already exists 
af14b6c2f878: Already exists 
5573c4b30949: Already exists 
11a88e764313: Downloading [================================>                  ]    123MB/192.2MB
11a88e764313: Downloading [================================================>  ]  184.5MB/192.2MB
cb0e1ed30eeb: Download complete 
0b9c9c21cd20: Download complete 
54e8a3ee7d4f: Download complete 
4ac7f1cac0b4: Download complete 
7e75f382a198: Downloading [===============>                                   ]  123.2MB/388.8MB
7e75f382a198: Downloading [=======================>                           ]  186.3MB/388.8MB
1c33ad28db5d: Download complete 
7bab2c3ebdf5: Download complete 
851863d6793e: Downloading [==========>                                        ]  15.53MB/75.56MB
851863d6793e: Download complete 
5a840ab65046: Downloading 
e76dc5738f04: Waiting 
3504aaff1fc5: Waiting 
3c4d87b73310: Waiting 
01cfc24ca80d: Waiting 
65815ffbce30: Waiting 
dfb85f79de02: Waiting 
a554fcfc19f5: Waiting 
effe81583c81: Waiting 
2c591f71baef: Waiting 
08a9eae6122d: Waiting 

unauthorized: authentication required

```

when pulling the image tryretool/backend:2.63.5 using these versions of docker client and server.

```
Client: Docker Engine - Community
 Version:           18.09.0
 API version:       1.39
 Go version:        go1.10.4
 Git commit:        4d60db4
 Built:             Wed Nov  7 00:46:51 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.0
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       4d60db4
  Built:            Wed Nov  7 00:52:55 2018
  OS/Arch:          linux/amd64
  Experimental:     false
```

It works fine when I pull using these versions of client and server (on another machine):

```
Client: Docker Engine - Community
 Version:           19.03.12
 API version:       1.39
 Go version:        go1.14.4
 Git commit:        48a6621
 Built:             Sat Jul  4 17:04:36 2020
 OS/Arch:           darwin/amd64
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          18.09.0
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       4d60db4
  Built:            Wed Nov  7 00:52:55 2018
  OS/Arch:          linux/amd64
  Experimental:     false
```

The error occurs whether I have logged in (with docker login) or not.

**Comment by jonseymour** [comment]
It looks like my issue above may have been clock-drift in the VM hosting my docker host. Thanks to https://github.com/docker/hub-feedback/issues/645#issuecomment-536198753 for reminding me about such things!

**Comment by thaJeztah** [comment]
@jonseymour I would also highly recommend updating the machine with docker 18.09.0 installed (if possible); Docker 18.09 reached EOL, so won't receive updates anymore (including security updates). If you're not able to upgrade to a current version (19.03.x at time of writing), at least try updating to the latest 18.09.x patch release (v18.09.9)

**Comment by ThejYapa** [comment]
Check for updates and update docker. Then logout and login again. 
If you are working on windows verify with "docker login".

**Comment by masoodmortazavi** [comment]
> It looks like my issue above may have been clock-drift in the VM hosting my docker host. Thanks to [#645 (comment)](https://github.com/docker/hub-feedback/issues/645#issuecomment-536198753) for reminding me about such things!

Same here.

**Comment by rezshar** [comment]
after changing the  ~/.docker/config.json file you need to restart docker service.
service docker restart.
it worked for me.

**Comment by ankushDhawan5812** [comment]
> 
What does the XXX here refer to? Is it the password, or literally "XXX"

**Comment by GuptaPiush** [comment]
When you successfully login to docker using docker login <<hostname>> then it will automatically create an authentication code in this file.

**Comment by GuptaPiush** [comment]
Please follow these steps then
1. Encrypt your username and password.
    echo -n 'username:password' | base64
2. Open ./docker/config.json
       {
	"auths": {
		"<<dockerregistryurl>>": {
			"auth": "encyrptedpassword"
		}
	}
}

**Comment by katib03** [comment]
I used Docker Desktop application and pulled the image to my local machine. Then with the help of the command below I generated a tar file:
> docker save -o *.tar <imageName>

after copying tar file to new location ( VM):

> docker load ...
