### ISSUE TITLE
uubuntu image: Couldn't find any package by glob 'libboost-thread1.58.0'

### ISSUE THREAD

**Issue by SergiyIvanovAtGTI** [docker/hub-feedback#1485]
FROM ubuntu
RUN apt-get -y update && apt-get install -y libboost-thread1.58.0 fails with 💯 

uubuntu image: Couldn't find any package by glob 'libboost-thread1.58.0'

**Comment by nandhini915** [comment]
- If you are a community user using our Docker Engine product, Please go to https://forums.docker.com/ and verify if other members in the community have run into this issue, or post an issue back to the community.
- If you are a user with a subscription to Docker Enterprise, you can go to https://success.docker.com/ and obtain help.
