### ISSUE TITLE
Docker With Windows Services

### ISSUE THREAD

**Issue by pchandra0312** [docker/hub-feedback#1487]
Hi Team,
             I have two windows service in .net framework 4.6  and I want to implement a docker support on them, can you please guide me how can I create a docker support for these windows service.

I have already install a docker for windows on my machine.

Thanks in advance.

**Comment by nandhini915** [comment]
Hi @pchandra0312 
- If you are a community user using our Docker Engine product, Please go to https://forums.docker.com/ and verify if other members in the community have run into this issue, or post an issue back to the community.
- If you are a user with a subscription to Docker Enterprise, you can go to https://success.docker.com/ and obtain help.
