### ISSUE TITLE
CRITICAL BUG: Unable to link new GitHub account

### ISSUE THREAD

**Issue by jmederer** [docker/hub-feedback#1492]
Hi, 

i want to link to a new github organisation. The Linked Account Overview at hub.docker.com doesn't show any Accounts. The Github Linked Account is also empty - i removed all Linked Accounts.

The Errormessage from hub.docker.com:
`Your Github account is already associated with the Docker Hub account 'confirmed'. 
`

Any Ideas ?

regards
Jan

**Comment by nandhini915** [comment]
Hi, could you provide your docker ID, and the organization you're trying to link the given github account to?

**Comment by jmederer** [comment]
any Updates? 
still not able to link to a new organization.
