### ISSUE TITLE
The api used to get the pull_count is not working any more

### ISSUE THREAD

**Issue by lospringliu** [docker/hub-feedback#1494]
if I call the api http https://hub.docker.com/v2/repositories/lospringliu/moac/, the "pull_account" always keep the same for several days. In the past months it works well.

**Comment by thaJeztah** [comment]
Looks like this is a duplicate of https://github.com/docker/hub-feedback/issues/1490

**Comment by lospringliu** [comment]
yes, a duplicate, let me close

**Comment by thaJeztah** [comment]
Thanks!
