### ISSUE TITLE
How to contact a user with no profile information

### ISSUE THREAD

**Issue by stsquad** [docker/hub-feedback#1502]
The QEMU project has been slowly growing it's use of docker over the last year or so. We are reaching the stage that we want to start using the hub to store prebuilt images so developers don't have to keep re-creating their images. I wanted to create a QEMU organisation but the form would let me. I assume this is because it would clash with:

  https://hub.docker.com/u/qemu

However we have no idea who this user is and as there is no obvious way to contact them we are stuck.  The repository is also quite old. So:

  1. Must organisational names not clash with user names?
  2. What's the process for contacting users of defunct repositories?

**Comment by conradoqg** [comment]
We have the same problem here. We know that someone from inside the company created the user but as the company is quite large it's hard to find the owner.

Did you find a solution?

Thanks,

**Comment by stsquad** [comment]
@conradoqg no unfortunately not. It doesn't seem as though the Docker Hub team monitor these issues but I'm not sure how else to contact them.

**Comment by thaJeztah** [comment]
I'd recommend opening a ticket through support@docker.com

**Comment by nandhini915** [comment]
Hi folks, unless you haven't already done so - please reach out to Docker support via support@docker.com or via https://success.docker.com/support (screenshot attached).  ![Screenshot](https://user-images.githubusercontent.com/2453622/42834230-695d1064-89ab-11e8-9e27-6ead616cfe92.png)
