### ISSUE TITLE
SAML authentication for Dockerhub?

### ISSUE THREAD

**Issue by mallyvai** [docker/hub-feedback#1505]
We've been growing our company and hardening our IT practices. Is there a SAML authentication option Dockerhub offers for enterprises, with Okta support?

**Comment by ChefAustin** [comment]
+1

Would love to see this functionality implemented for our organization. Especially with automated provisioning/deprovisioning.

**Comment by danielhfriedman** [comment]
+1 to both points above. This would be huge step-up in security/IT process.

**Comment by moshebs** [comment]
+1. 

Actually this becomes a mandatory requirement for us, will be forced to leave Docker Hub if it doesn't happen...

**Comment by abilous-ti** [comment]
+1

**Comment by vdel** [comment]
+1

**Comment by tproenca** [comment]
+1

**Comment by noaginzbursky** [comment]
+1

**Comment by chrissalomon** [comment]
+1

**Comment by enorlando** [comment]
+ 1 with Azure

**Comment by mojtabacazi** [comment]
+1

**Comment by Oskoss** [comment]
+1

**Comment by ace03uec** [comment]
+1. Not necessarily Okta.

**Comment by mefi5to** [comment]
+1
