### ISSUE TITLE
Examples of default code for the advanced hooks as they are run by default on hub

### ISSUE THREAD

**Issue by MetalArend** [docker/hub-feedback#1510]
There's a bit of documentation on the advanced page on how to set up a build hook, but the other hooks don't get that much love. Is there a place to check what commands are being run as defaults for the other hooks? I mean, some sort of example code that I could put in a hooks file, and it would not change the behaviour of the build at all, basically doing the same thing it would already be doing without that hooks file in place.

The reason I'm asking is that I see a lot of repositories using `$NEXT_BUILD_TRIGGERS` in the `post_push` file to "invoke all downstream build triggers", and I was just thinking "how the hell do they know about that?".

**Comment by puittenbroek** [comment]
Well this is actually a self made thing, I came up with the same thing (doing a curl -X POST). Hadn't thought to go as far yet as making a variable of it :)

https://github.com/jupyter/docker-stacks/blob/master/docs/maintaining/tasks.md
https://github.com/jupyter/docker-stacks/blob/master/datascience-notebook/hooks/post_push
