### ISSUE TITLE
Add system for automated build node selection

### ISSUE THREAD

**Issue by jproctor10** [docker/hub-feedback#1511]
I'd like to suggest a feature of being able to tag your repository if your Dockerfile uses features from a certain build. I'm coming from similar issues to #1427, however I think it's been a recurring issue as new features come out.

The docker version tag in the docker-hub repo could initially be used just to prevent autobuilds that will otherwise fail from even being queued. In the future this could be expanded as outlined below.

I also imagine that the updating of these nodes is probably a hassle, so perhaps as a future option these nodes could run different versions of docker. Hopefully making deployment of new versions somewhat less risky. In this case the previously implemented tags could be used to determine which nodes could be used.

**Comment by programingnotes** [comment]
Can we get feedback on this please?

**Comment by jproctor10** [comment]
This issue remains valid to my knowledge. It is a suggestion to solve a likely recurring issue. At minimum, I would expect the issue to be documented as I suggested  in https://github.com/docker/hub-feedback/issues/1427#issuecomment-422889726. Otherwise, I would hope for a real fix or perhaps even an autodetection but I would expect that to be prohibitively difficult on dockerhub's part.
