### ISSUE TITLE
Unable to login into my docker hub account or reset password

### ISSUE THREAD

**Issue by shivaprasadlk** [docker/hub-feedback#1512]
Username :shivaprasadlk
email :shivaprasadlk@yahoo.com

**Comment by KeyboardInterrupt** [comment]
Same for me, Is this really the Way to ask for Help?
[this here](https://success.docker.com/article/password-reset-email-not-received states) I should contact support.

As I cannot login, into the support center, I will contact Docker via **[mail](mailto:support@docker.com)**

You could tr to do the same :)

**Comment by nandhini915** [comment]
If you're still blocked, please check out https://success.docker.com/q/account-access-blocked and verify if this describes your issue and fix. If your specific issue is not listed here, you can open a ticket at https://success.docker.com/support (screenshot attached).  ![Screenshot](https://user-images.githubusercontent.com/2453622/42834230-695d1064-89ab-11e8-9e27-6ead616cfe92.png)
