### ISSUE TITLE
no space left on device

### ISSUE THREAD

**Issue by Serux** [docker/hub-feedback#1515]
Docker outputs this error message when trying to auto-build the docker image. 
https://hub.docker.com/r/serux/docker-galaxy-bioinfworkflow/builds/bxuvhhldvnb6xmgrubxe9lh/

As there is not limit for size in docker hub, I don't know what may be the problem. Is there something I can do to solve this problem? or is a docker hub bug?
https://forums.docker.com/t/does-docker-hub-have-a-size-limitation-on-repos-or-images/10154

**Comment by CM2Walki** [comment]
Duplicate of #677
That said, I have the same problem (see #677).

**Comment by Serux** [comment]
> Duplicate of #677 and #1010
> That said, I have the same problem (see #677).

This was some time ago, and I have left aside this project since then.
I think I remember that, as a workaround, I ended building the image locally and then uploading it to Dockerhub. 
Then, I reduced the size of the image to be able to use it in dockerhub, and used some scripts to install extra dependencies directly in the container. 

Hope you luck with this issue!

**Comment by CM2Walki** [comment]
> > Duplicate of #677 and #1010
> > That said, I have the same problem (see #677).
> 
> This was some time ago, and I have left aside this project since then.
> I think I remember that, as a workaround, I ended building the image locally and then uploading it to Dockerhub.

Yeah, that's pretty much the same approach I took as well, but my images are all dependent on each other and retrigger via Webhooks if a base image has been changed. So having to update them manually is quiet impractical for me.

Unfortunalty, I can't minimise the image. It's already as small as it can get :(.

**Comment by erikliland** [comment]
I'm experiencing the same issue when building ~18GB on top of Ubuntu in automated builds.

**Comment by vebaev** [comment]
Mine builds was fine when suddenly I cannot rid of that error and I did not change much related to size (6-8GB). Does anybody know how to fix this?

**Comment by glenn-jocher** [comment]
We are using autobuild with the YOLOv5 repo https://github.com/ultralytics/yolov5 on a paid plan and keep getting this error message.
https://hub.docker.com/repository/registry-1.docker.io/ultralytics/yolov5/builds/aab1d85d-fc72-4321-a33b-ae858935d50d

<img width="1764" alt="Screenshot 2022-02-17 at 14 42 55" src="https://user-images.githubusercontent.com/26833433/154494152-2e550555-a42b-4dc4-a701-392ea14360c5.png">
