### ISSUE TITLE
Can't create automated build

### ISSUE THREAD

**Issue by mottosso** [docker/hub-feedback#1522]
Hi Docker Hub,

I've created several of these in the past, but now for some reason I can't seem to get a listing of available repositories for my GitHub projects. Bitbucket works however.

- https://hub.docker.com/add/automated-build/getavalon/github/orgs/

Here's what I'm seeing in the console.

```txt
main.min.js:3 [Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
window.XMLHttpRequest.open @ main.min.js:3
/api/nautilus/v1/repositories/summaries/getavalon/docker:1 Failed to load resource: the server responded with a status of 404 (Not Found)
hub.docker.com/:1 Failed to load resource: the server responded with a status of 502 (Bad Gateway)
githubUsersAndRepos.js:24 Uncaught TypeError: Cannot read property 'detail' of null
    at githubUsersAndRepos.js:24
    at d.callback (client.js:804)
    at d.<anonymous> (client.js:527)
    at d.i.emit (index.js:133)
    at XMLHttpRequest.t.onreadystatechange (client.js:886)
```

![image](https://user-images.githubusercontent.com/2152766/41027129-2336d5aa-696e-11e8-82ac-d72cfd3110d4.png)

Any ideas?

Thanks,
Marcus

**Comment by mottosso** [comment]
Adding to this, I've tried removing the GitHub authentication and re-adding it, no change.

**Comment by cicorias** [comment]
exact same issue here.  Question, how many repos might you have? I'm in many orgs, many repos.  

Direct call to the API via Postman with the `Authorization: JWT ...` header and token, same issue.

Something failing in Docker Hub world after the nginx front end: `502 Bad Gateway`

![image](https://user-images.githubusercontent.com/1080406/46035079-303f8580-c0d0-11e8-8df1-e1c6ddf6589f.png)

**Comment by mottosso** [comment]
I've indeed got quite a few (50+?), and are part of 10+ organisations.

**Comment by cicorias** [comment]
how the hell do you even get support on Docker Hub?  There's no paid options.  Kinda worthless when things go this south.  and no API to address the workaround to UI issues.

I guess I'll standup an Azure Container Registry and just use that.
