### ISSUE TITLE
Status page has "access denied"

### ISSUE THREAD

**Issue by patrick-webs** [docker/hub-feedback#1525]
https://www.docker.com/ at the bottom links to http://status.docker.com/ which I assume would be the status page for DockerHub.

However that page just shows an "Access denied" message:

    <html>
      <head>
        <title>Access Denied</title>
      </head>
      <body>
        <style>

          body {
            background-color: #272822;
            font-family: 'Helvetica Neue', Arial, Helvetica, Geneva, sans-serif;
            font-size: 55px;
            font-style: normal;
            font-variant: normal;
            color: rgb(255, 255, 255);
            text-align: center;
            opacity: 0.7;
          }

        </style>

        <p style='margin-top:200px; opacity: 0.7; font-size: 25px;'>Access Denied</p>
        <p style='margin-top:5px; font-size: 20px;'></p>

      </body>
    </html>

**Comment by rdeanar** [comment]
I can open status page as logged in user and in incognito tab. Looks like all works.

**Comment by patrick-webs** [comment]
I verified it works on a different network/ISP. Seems like it's some sort of network issue! I'll follow up with my net admins, sorry for the trouble.

**Comment by patrick-webs** [comment]
FWIW, this is still an issue :( accessing from 209.190.211.23 . am I in an IP blocked range or something?

![screen shot 2018-12-13 at 5 36 46 pm-fs8](https://user-images.githubusercontent.com/10403580/49971853-ec556300-fefd-11e8-8943-8cd7c22d6dea.png)

**Comment by patrick-webs** [comment]
no longer reproduce the issue
