### ISSUE TITLE
can not create a new account

### ISSUE THREAD

**Issue by jerry100chan** [docker/hub-feedback#1526]
i can't click the sign up button,because it is grey.i can't create account.

**Comment by theg1nger** [comment]
Same here. Console error
`8a042fc2e0d4.js:1 POST https://cloud.docker.com/v2/users/signup/ 400 (BAD REQUEST)`

**Comment by nandhini915** [comment]
Thanks for surfacing this issue. We've identified this issue and deployed a fix to production.
