### ISSUE TITLE
Namesquatting, release of username

### ISSUE THREAD

**Issue by mottosso** [docker/hub-feedback#1527]
Hi Docker,

I was wondering whether I'd be able to take over a possibly inactive account since three years?

- https://hub.docker.com/r/avalon/

I'm unsure of your policy against namesquatting, but thought I'd ask. Would be much appreciated!

Best,
Marcus

**Comment by thaJeztah** [comment]
In such cases it's best to contact support@docker.com, as more details may be needed

**Comment by mottosso** [comment]
Ok, thank you!
