### ISSUE TITLE
Renamed bitbucket repo commit enqueues two docker builds

### ISSUE THREAD

**Issue by dabrain34** [docker/hub-feedback#1529]
Hello,

First, i created automated builds linked with a bitbucket repositories and then I decided to rename the bitbucket repos, so I removed the automated builds by using the interace in **Settings->Delete Repository**
And then i created from scratch a new automated build with the new repository name.

But now each time i commit to this new repository, two builds are triggered on ducker hub side.
How can I avoid that because i renamed a few?

By example:
https://hub.docker.com/r/fluendo/docker-buildbot-cerbero-hardy-x86

**Comment by andrei-m-code** [comment]
I'm getting this issue now. Do you have any solution for it?
