### ISSUE TITLE
bitbucket avatars not showing up

### ISSUE THREAD

**Issue by kencochrane** [docker/hub-feedback#153]
Not sure if this is just me, or everyone.

My bitbucket avatars are not showing up.

<img width="772" alt="screenshot 2015-08-03 16 42 20" src="https://cloud.githubusercontent.com/assets/261601/9047277/befbe086-39fe-11e5-8a86-a6df5913cebd.png">
<img width="532" alt="screenshot 2015-08-03 16 43 06" src="https://cloud.githubusercontent.com/assets/261601/9047283/cdaeb6e4-39fe-11e5-863f-0dc61f5a41b0.png">

**Comment by ChristopherBiscardi** [comment]
ping @rrarunan

**Comment by rrarunan** [comment]
Looking into it.
