### ISSUE TITLE
Docker for Windows hangs during "Removing Files"

### ISSUE THREAD

**Issue by amitkhatumrc** [docker/hub-feedback#1532]
I am trying to install Docker for Windows 18.03.1 -ce-win65. Everytime it starts installing and then suddenly hangs or gets stuck in "Removing Files" step. My PC has Windows 10 Enterprise.

![docket install stuck](https://user-images.githubusercontent.com/30510542/41433569-fb6be93a-6fde-11e8-9750-5cad581dc91c.PNG)

**Comment by umitkose** [comment]
Hello @amitkhatumrc ,
I am having the same problem.Did you find a solution for the problem.

**Comment by Radhika108** [comment]
Any solution

**Comment by amitkhatumrc** [comment]
@Radhika108 - None so far.

**Comment by Radhika108** [comment]
Can i downgrade a version of docker, could it be just this build? Do you think it will work?

**Comment by amitkhatumrc** [comment]
@Radhika108 - i tried all old 17.x versions to no avail. Tried disabling AntiVirus, still no success.

**Comment by nandhini915** [comment]
Closing this ticket since it relates to running Docker in a user's local environment or on the users on-prem/cloud based cluster.

If you are a community user using our Docker Engine product, Please go to https://forums.docker.com/ and verify if other members in the community have run into this issue, or post an issue back to the community.
If you are a user with a subscription to Docker Enterprise, you can go to https://success.docker.com/ and obtain help.

**Comment by gvreddym** [comment]
I observed the same issue on my windows 10 laptop. please provide solution for this.

**Comment by DynaSpan** [comment]
For anyone observing this issue on Windows 10, 1809: Try to go to Settings -> Update & Security -> Windows Security -> Threat Protection -> Manage ransomware protection -> Disable the protection, or allow the installer. This fixed the issue for me.

**Comment by rbtcollins** [comment]
Ransomware protection off doesn't fix it for me.

**Comment by DynaSpan** [comment]
@rbtcollins did you restart the installer after you applied the settings? You can also try disabling the "real time protection" instead.

**Comment by adityasuman2025** [comment]
@DynaSpan you are god

**Comment by Shadownsf** [comment]
@DynaSpan You made my day !!

**Comment by PhoeniXAbhisheK** [comment]
@DynaSpan thanks a lot mate... 😸

**Comment by sanghunyoo** [comment]
@DynaSpan Thanks a lot! Disabling ransomware protection made it installed well.

**Comment by SimonGeering** [comment]
@DynaSpan thanks this fixed it for me.

**Comment by rbtcollins** [comment]
> 
> 
> @rbtcollins did you restart the installer after you applied the settings? You can also try disabling the "real time protection" instead.

I did, yes. And disabled real time protection yes.

**Comment by jessegoodier** [comment]
Disabling A/V/malware still fixes the issue on Desktop 2.0.0.3!
crazy

**Comment by unodgs** [comment]
Have the same problem.. unfortunately I can't modify maleware settings.

**Comment by SunneyTyagi** [comment]
Facing the same issue (gets stuck in "Removing Files" step), but can't modify the malware settings, is there any other way for troubleshooting this issue?
Many thanks in advance.

**Comment by seanvikoren** [comment]
I guess it would be cool if bugs fixed themselves, but come on here guys.

Windows Firewall Off.  No way to install the product.
![docker_fail](https://user-images.githubusercontent.com/786528/59644057-29561880-9120-11e9-8615-2778d541404d.jpg)

**Comment by RicardoVolkz** [comment]
@DynaSpan  thx bro.

**Comment by DynaSpan** [comment]
@jessegoodier @unodgs check out [this answer on another issue](https://github.com/docker/for-win/issues/1172#issuecomment-363509883). 

@seanvikoren you shouldn't disable the firewall but the ransomware protection, you can find it under Settings -> Update & Security -> Windows Security -> Threat Protection -> Manage ransomware protection

**Comment by seanvikoren** [comment]
Thank you @DynaSpan!
Turning the Ransomware Protection off worked.

Adding the installer to the exception list did not.

**Comment by fkostadinov** [comment]
Yeah, same problem here with Docker 2.0.0.3. Unfortunately, on my company laptop I'm not allowed (cannot) turn off Windows Defender.

**Comment by seanvikoren** [comment]
@fkostadinov As @DynaSpan mentioned, it's actually ransomware protection, and you only have to disable it for the install:

Settings -> Update & Security -> Windows Security -> Threat Protection -> Manage ransomware protection

**Comment by wjtscn** [comment]
The same problem, on my machine,  right - click on setup-program and select run as administrator，ok！

**Comment by lnguyenfx** [comment]
If the above solutions do not work, try this saving this PowerShell script and execute it as an Administrator:
https://success.docker.com/article/how-to-completely-remove-docker-in-windows-10

Then run the installer again in Administrative mode.

**Comment by regismesquita** [comment]
Same issue on Docker Desktop 2.1.0.0 , @DynaSpan solution solved the problem. thanks!
