### ISSUE TITLE
index of hub.docker.com with largest js

### ISSUE THREAD

**Issue by netoht** [docker/hub-feedback#1533]
When I'm trying access index page from hub.docker.com took a long time to complete because there exists this js: https://hub.docker.com/public/js/client.753038d3e40b8701c151.js

So, it's largest around 4.2mb this took about 1.6 minutes to load.

**Comment by kainzjoh** [comment]
Same for me - https://hub.docker.com/public/js/client.322616f22a9ea3a3adfc.js takes ages to load.
To be more specific, according to Chrome DevTools more than 13 seconds and this was a "quick" rendering.
