### ISSUE TITLE
How to run archlinux container image in coreos?

### ISSUE THREAD

**Issue by newuser135** [docker/hub-feedback#1534]
How do I run the base/archlinux container image in coreos? I have spent hours googling this, and there seems to be no documentation explaining how to actually run/start/execute an official container image after a pull request is made and the download completes in coreos.

**Comment by thaJeztah** [comment]
Note that the `base/archlinux` image is a community provided image, and not an official image; from the readme of that image; https://hub.docker.com/r/base/archlinux/


> If you've got issues, questions or improvements, please open an issue on the Github Issue tracker.

So I recommend opening an issue in the issue tracker for that image; https://github.com/archimg/archlinux/issues
