### ISSUE TITLE
bionic Release' does not have a Release file

### ISSUE THREAD

**Issue by rupyr19** [docker/hub-feedback#1539]
I'm working on Ubuntu 18.04. I'm trying to install Docker. But whenever i run this command "sudo add-apt-repository \
   "deb [arch=amd64] $DOCKER_EE_URL/ubuntu \
   $(lsb_release -cs) \
   stable-17.06" 
It show an error says 
" The repository 'https://storebits.docker.com/ee/ubuntu/sub-d360c329-980f-468d-bf62-4736d27919be/ubuntu bionic Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
".

 I'm attaching the screenshot 
![error_1](https://user-images.githubusercontent.com/40421630/41644004-8058b92a-748a-11e8-9bbd-347955dfb7c8.png)
Please help me with this issues as soon as possible.

**Comment by thaJeztah** [comment]
Docker EE is not yet supported on Ubuntu Bionic; see the "OS requirements" section in the installation section: https://docs.docker.com/install/linux/docker-ee/ubuntu/#os-requirements

and the compatibility matrix; https://success.docker.com/article/compatibility-matrix

**Comment by rupyr19** [comment]
Thank you so much Sir for your response. Sir but i've tried to install
Docker CE version too and I'm encountering same error.

**Comment by thaJeztah** [comment]
For Docker CE, it's currently in the "edge" channel, because Bionic was released after the last (18.03) stable version; Bionic will arrive in Docker 18.06 stable, but may be added to 18.03 (compatibility is being tested); https://docs.docker.com/install/linux/docker-ce/ubuntu/#os-requirements

> Bionic 18.04 (Docker CE 18.05 Edge and higher only)

**Comment by rupyr19** [comment]
Thank you very much for the help. 😃

**Comment by thaJeztah** [comment]
I got just informed that 18.03 stable is now also available for Ubuntu Bionic

**Comment by nandhini915** [comment]
Closing this issue since it is resolved.

**Comment by MurKit** [comment]
Looks like I'm still getting this error:

`Ign:10 https://download.docker.com/linux/ubuntu (lsb_release InRelease               
Err:11 https://download.docker.com/linux/ubuntu (lsb_release Release                 
  404  Not Found [IP: 54.192.230.81 443]
Reading package lists... Done                      
E: The repository 'https://download.docker.com/linux/ubuntu (lsb_release Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.`

**Comment by thaJeztah** [comment]
@MurKit looks like something went wrong when you added the repository; looks like there's a _literal_ `(lsb_release InRelease)` in your repository list, instead of the _output_ of that command

What does the content of your `/etc/apt/sources.list` look like? (look for the lined with `download.docker.com`)

**Comment by MurKit** [comment]
```
deb http://security.ubuntu.com/ubuntu bionic-security main restricted
# deb-src http://security.ubuntu.com/ubuntu xenial-security main restricted
deb http://security.ubuntu.com/ubuntu bionic-security universe
# deb-src http://security.ubuntu.com/ubuntu xenial-security universe
deb http://security.ubuntu.com/ubuntu bionic-security multiverse
# deb-src http://security.ubuntu.com/ubuntu xenial-security multiverse
deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
# deb-src [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
```

**Comment by slassh** [comment]
@MurKit  did you solve the issue ?

**Comment by MurKit** [comment]
@slassh yes, see my previous reply.

Issue was resolved either by itself or because I have added and then removed edge and test repos.
Then stable release was added without any issues.

**Comment by RanaBan** [comment]
https://linuxconfig.org/how-to-install-docker-on-ubuntu-18-04-bionic-beaver

**Comment by thaJeztah** [comment]
@ranaban those instructions looks to be quite old; also I would not recommend installing the `docker.io` package that's packaged by Ubuntu, as it's often out of date, and may have vulnerabilities.

The instructions for installing the official docker packages can be found here; https://docs.docker.com/install/linux/docker-ce/ubuntu/

**Comment by RanaBan** [comment]
yes its old, I found it somewhere. Thanks for your comment

**Comment by nmakro** [comment]
Hi in my environment this issue still exists.

sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable"
Get:1 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]
Hit:2 http://archive.canonical.com/ubuntu bionic InRelease                                                                                                      
Hit:3 http://ppa.launchpad.net/anonbeat/guayadeque/ubuntu bionic InRelease                                                                                      
Hit:4 http://packages.microsoft.com/repos/vscode stable InRelease                                                                                               
Hit:5 http://us.archive.ubuntu.com/ubuntu bionic InRelease                                                                                                      
Hit:6 http://ppa.launchpad.net/apandada1/brightness-controller/ubuntu bionic InRelease                               
Ign:7 https://download.docker.com/linux/debian bionic InRelease                                                      
Hit:8 http://ppa.launchpad.net/bookworm-team/bookworm/ubuntu bionic InRelease                                        
Hit:10 http://us.archive.ubuntu.com/ubuntu bionic-updates InRelease                                                  
Hit:11 http://ppa.launchpad.net/kelleyk/compton/ubuntu bionic InRelease                                                                                         
Err:12 https://download.docker.com/linux/debian bionic Release                                                                                                  
  404  Not Found [IP: 10.144.1.10 8080]
Hit:13 http://ppa.launchpad.net/libreoffice/ppa/ubuntu bionic InRelease                                                                                         
Hit:14 http://us.archive.ubuntu.com/ubuntu bionic-backports InRelease                                                                             
Hit:15 http://ppa.launchpad.net/linrunner/tlp/ubuntu bionic InRelease                                                                             
Hit:9 https://netcologne.dl.sourceforge.net/project/ubuntuzilla/mozilla/apt all InRelease               
Hit:16 http://ppa.launchpad.net/lxle/stable/ubuntu bionic InRelease      
Hit:17 http://ppa.launchpad.net/maarten-baert/simplescreenrecorder/ubuntu bionic InRelease
Hit:18 http://ppa.launchpad.net/philip.scott/spice-up-daily/ubuntu bionic InRelease
Hit:19 http://ppa.launchpad.net/utappia/stable/ubuntu bionic InRelease 
Hit:20 http://ppa.launchpad.net/webupd8team/y-ppa-manager/ubuntu bionic InRelease
Reading package lists... Done                                                                                                                                   
E: The repository 'https://download.docker.com/linux/debian bionic Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

lsb_release -cs
bionic

cat /etc/os-release 
NAME="Ubuntu"
VERSION="18.04.3 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="LXLE Linux"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

**Comment by thaJeztah** [comment]
@nmakro looks like you're adding the debian package repository on an Ubuntu machine?

**Comment by nmakro** [comment]
@thaJeztah Correct.

**Comment by RanaBan** [comment]
I can't find why it works some times and shows error some times.
I started the docker:
:~/Documents$ docker run -d -p 127.0.0.1:9200:9200 -v $(pwd)/geonames_index/:/usr/share/elasticsearch/data elasticsearch:5.5.2
b833fd5a97fbdc130d2346cc939ee7fcbeace43c7dd36886c8e66248982c7372

Error is like this:
GET http://localhost:9200/geonames/_count [status:404 request:0.011s]

---------------------------------------------------------------------------
NotFoundError                             Traceback (most recent call last)
~/.local/lib/python3.6/site-packages/mordecai/geoparse.py in __init__(self, es_hosts, es_port, es_ssl, es_auth, verbose, country_threshold, threads, progress, mod_date, **kwargs)
     63             # with nostderr():
---> 64             self.conn.count()
     65         except:

~/.local/lib/python3.6/site-packages/elasticsearch_dsl/search.py in count(self)
    586             body=d,
--> 587             **self._params
    588         )['count']

~/.local/lib/python3.6/site-packages/elasticsearch/client/utils.py in _wrapped(*args, **kwargs)
     72                     params[p] = kwargs.pop(p)
---> 73             return func(*args, params=params, **kwargs)
     74         return _wrapped

~/.local/lib/python3.6/site-packages/elasticsearch/client/__init__.py in count(self, index, doc_type, body, params)
   1122         return self.transport.perform_request('GET', _make_path(index,
-> 1123             doc_type, '_count'), params=params, body=body)
   1124 

~/.local/lib/python3.6/site-packages/elasticsearch/transport.py in perform_request(self, method, url, params, body)
    311             try:
--> 312                 status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
    313 

~/.local/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py in perform_request(self, method, url, params, body, timeout, ignore)
    127             self.log_request_fail(method, full_url, url, body, duration, response.status, raw_data)
--> 128             self._raise_error(response.status, raw_data)
    129 

~/.local/lib/python3.6/site-packages/elasticsearch/connection/base.py in _raise_error(self, status_code, raw_data)
    124 
--> 125         raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
    126 

NotFoundError: TransportError(404, 'index_not_found_exception', 'no such index')

During handling of the above exception, another exception occurred:

ConnectionError                           Traceback (most recent call last)
~/.local/lib/python3.6/site-packages/IPython/core/interactiveshell.py in run_code(self, code_obj, result, async_)
   3295                 else:
-> 3296                     exec(code_obj, self.user_global_ns, self.user_ns)
   3297             finally:

<ipython-input-27-9a38a641401f> in <module>
      1 from mordecai import Geoparser
----> 2 geo = Geoparser()

~/.local/lib/python3.6/site-packages/mordecai/geoparse.py in __init__(self, es_hosts, es_port, es_ssl, es_auth, verbose, country_threshold, threads, progress, mod_date, **kwargs)
     69 See https://github.com/openeventdata/mordecai#installation-and-requirements
---> 70 for instructions on setting up Geonames/Elasticsearch""".format(es_hosts, es_port))
     71         es_date = utilities.check_geonames_date(self.conn)

<class 'str'>: (<class 'IndexError'>, IndexError('tuple index out of range',))

During handling of the above exception, another exception occurred:

IndexError                                Traceback (most recent call last)
~/.local/lib/python3.6/site-packages/IPython/core/interactiveshell.py in run_code(self, code_obj, result, async_)
   3311             if result is not None:
   3312                 result.error_in_exec = sys.exc_info()[1]
-> 3313             self.showtraceback(running_compiled_code=True)
   3314         else:
   3315             outflag = False

~/.local/lib/python3.6/site-packages/IPython/core/interactiveshell.py in showtraceback(self, exc_tuple, filename, tb_offset, exception_only, running_compiled_code)
   2036                                             value, tb, tb_offset=tb_offset)
   2037 
-> 2038                     self._showtraceback(etype, value, stb)
   2039                     if self.call_pdb:
   2040                         # drop into debugger

~/.local/lib/python3.6/site-packages/ipykernel/zmqshell.py in _showtraceback(self, etype, evalue, stb)
    544             u'traceback' : stb,
    545             u'ename' : unicode_type(etype.__name__),
--> 546             u'evalue' : py3compat.safe_unicode(evalue),
    547         }
    548 

~/.local/lib/python3.6/site-packages/ipython_genutils/py3compat.py in safe_unicode(e)
     63     """
     64     try:
---> 65         return unicode_type(e)
     66     except UnicodeError:
     67         pass

~/.local/lib/python3.6/site-packages/elasticsearch/exceptions.py in __str__(self)
     67     def __str__(self):
     68         return 'ConnectionError(%s) caused by: %s(%s)' % (
---> 69             self.error, self.info.__class__.__name__, self.info)
     70 
     71 

~/.local/lib/python3.6/site-packages/elasticsearch/exceptions.py in error(self)
     42     def error(self):
     43         """ A string error message. """
---> 44         return self.args[1]
     45 
     46     @property

IndexError: tuple index out of range

**Comment by thaJeztah** [comment]
@RanaBan  your issue looks completely unrelated to the issue reported here

**Comment by Lilith1410** [comment]
I've encountered the same issue mentioned here. Followed the official docs meticulously on a freshly installed ubuntu 18.04 machine - no coming through. Opted to install via `sudo apt install docker.io` and worked like a charm. 

this: 

`sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu  $(lsb_release -cs)  stable" ` leads to 

`Err:9 https://download.docker.com/linux/ubuntu \ Release                                
  404  Not Found [IP: 2600:9000:2057:9400:3:db06:4200:93a1 443]
Hit:10 https://repos.influxdata.com/ubuntu bionic InRelease                             
Reading package lists... Done          
E: The repository 'https://download.docker.com/linux/ubuntu \ Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.`

**Comment by thaJeztah** [comment]
@Lilith1410 what does the output of `lsb_release -cs` looks like on your machine?

**Comment by Lilith1410** [comment]
@thaJeztah bionic

**Comment by ipergenitsa** [comment]
I have the same issue, I'm following https://docs.docker.com/install/linux/docker-ce/ubuntu/

**Comment by ipergenitsa** [comment]
I could install it from deb packages: https://docs.docker.com/install/linux/docker-ce/ubuntu/#install-from-a-package
you need to install
1. containerd.io deb
1. docker-ce-cli deb
1. docker-ce deb

**Comment by thaJeztah** [comment]
Did a quick test (running the install in a container using the install script, which does the same steps), but not able to reproduce the issue;

```bash
docker run -it --rm ubuntu:disco sh -c 'apt-get -qq update > /dev/null && apt-get install -qq -y curl > /dev/null && curl -fsSL https://get.docker.com | sh'

debconf: delaying package configuration, since apt-utils is not installed
# Executing docker install script, commit: 442e66405c304fa92af8aadaa1d9b31bf4b0ad94
+ sh -c apt-get update -qq >/dev/null
+ sh -c DEBIAN_FRONTEND=noninteractive apt-get install -y -qq apt-transport-https ca-certificates curl gnupg >/dev/null
debconf: delaying package configuration, since apt-utils is not installed
+ sh -c curl -fsSL "https://download.docker.com/linux/ubuntu/gpg" | apt-key add -qq - >/dev/null
Warning: apt-key output should not be parsed (stdout is not a terminal)
+ sh -c echo "deb [arch=amd64] https://download.docker.com/linux/ubuntu disco stable" > /etc/apt/sources.list.d/docker.list
+ sh -c apt-get update -qq >/dev/null
+ [ -n  ]
+ sh -c apt-get install -y -qq --no-install-recommends docker-ce >/dev/null
debconf: delaying package configuration, since apt-utils is not installed
If you would like to use Docker as a non-root user, you should now consider
adding your user to the "docker" group with something like:

  sudo usermod -aG docker your-user

Remember that you will have to log out and back in for this to take effect!

WARNING: Adding a user to the "docker" group will grant the ability to run
         containers which can be used to obtain root privileges on the
         docker host.
         Refer to https://docs.docker.com/engine/security/security/#docker-daemon-attack-surface
         for more information.
```

From the output in https://github.com/docker/hub-feedback/issues/1539#issuecomment-604364133, wondering if it's something related to IPv6?

```
404  Not Found [IP: 2600:9000:2057:9400:3:db06:4200:93a1 443]
```

**Comment by Lime91** [comment]
> Did a quick test (running the install in a container using the install script, which does the same steps), but not able to reproduce the issue;
>
>```docker run -it --rm ubuntu:disco sh -c 'apt-get -qq update > /dev/null && apt-get install -qq -y curl > /dev/null && curl -fsSL https://get.docker.com | sh'```

@thaJeztah I'm quite new to Docker, but it seems to me that you didn't use an ubuntu:bionic image in your test?
Most people reporting this issue here (including me) use Ubuntu 18.04 bionic.

**Comment by thaJeztah** [comment]
Ah, my bad; ran a script to check all the versions and copied the wrong one; here's bionic;

```bash
docker run -it --rm ubuntu:bionic sh -c 'apt-get -qq update > /dev/null && apt-get install -qq -y curl > /dev/null && curl -fsSL https://get.docker.com | sh'
debconf: delaying package configuration, since apt-utils is not installed
# Executing docker install script, commit: 442e66405c304fa92af8aadaa1d9b31bf4b0ad94
+ sh -c apt-get update -qq >/dev/null
+ sh -c DEBIAN_FRONTEND=noninteractive apt-get install -y -qq apt-transport-https ca-certificates curl gnupg >/dev/null
debconf: delaying package configuration, since apt-utils is not installed
+ sh -c curl -fsSL "https://download.docker.com/linux/ubuntu/gpg" | apt-key add -qq - >/dev/null
Warning: apt-key output should not be parsed (stdout is not a terminal)
+ sh -c echo "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable" > /etc/apt/sources.list.d/docker.list
+ sh -c apt-get update -qq >/dev/null
+ [ -n  ]
+ sh -c apt-get install -y -qq --no-install-recommends docker-ce >/dev/null
debconf: delaying package configuration, since apt-utils is not installed
If you would like to use Docker as a non-root user, you should now consider
adding your user to the "docker" group with something like:

  sudo usermod -aG docker your-user

Remember that you will have to log out and back in for this to take effect!

WARNING: Adding a user to the "docker" group will grant the ability to run
         containers which can be used to obtain root privileges on the
         docker host.
         Refer to https://docs.docker.com/engine/security/security/#docker-daemon-attack-surface
         for more information.
```

**Comment by EdwardBurgin** [comment]
I also had the same problem. I think its occuring because people follow the tutorial and accidentally run a debian line instead of ubuntu. 
I could proceed in the install removing the following line, editing install sources with:
`sudo nano /etc/apt/sources.list`
uncommenting the following line:
`deb-src [arch=amd64] https://download.docker.com/linux/debian bionic stable`
This was my error msg: 

> The repository 'https://download.docker.com/linux/debian bionic Release' does not have a Release file
I'm installing on bionic beaver.

**Comment by Neurone** [comment]
> I also had the same problem. I think its occuring because people follow the tutorial and **accidentally run a debian line instead of ubuntu**.

That was exactly what just happened to me. I solved using the correct repo:

`deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable`

**Comment by michaelBenin** [comment]
Reproduced this morning ollowing these steps: https://docs.docker.com/engine/install/debian/

@Neurone confirmed that worked on my end that worked. Thank you for posting.

**Comment by michaelBenin** [comment]
![image](https://user-images.githubusercontent.com/521971/82337586-7949f900-99db-11ea-91b6-d8fec787ce45.png)

Here's where we need to update the docs.

**Comment by Luctia** [comment]
> I also had the same problem. I think its occuring because people follow the tutorial and accidentally run a debian line instead of ubuntu.
> I could proceed in the install removing the following line, editing install sources with:
> `sudo nano /etc/apt/sources.list`
> uncommenting the following line:
> `deb-src [arch=amd64] https://download.docker.com/linux/debian bionic stable`
> I'm installing on bionic beaver. This was my error msg:
> 
> > The repository 'https://download.docker.com/linux/debian bionic Release' does not have a Release file

In addition to this, it might have happened that a previous attempt has put a line
```
deb-src [arch=amd64] https://download.docker.com/linux/debian (lsb_release -cs) stable
```
or similar in the file. This should be removed and is a product of a shell using `$(lsb_release -cs)` as a literal.

**Comment by Zerogirl25** [comment]
Hi,
I am also encountering the same issue while installing docker in bionic.
**I used sudo-add command and updated debian with bionic.**
Here is my sources.list content.

#------------------------------------------------------------------------------#
#                            OFFICIAL UBUNTU REPOS                             #
#------------------------------------------------------------------------------#


###### Ubuntu Main Repos
deb http://in.archive.ubuntu.com/ubuntu/ bionic main restricted universe multiverse

###### Ubuntu Update Repos
deb http://in.archive.ubuntu.com/ubuntu/ bionic-security main restricted universe multiverse
deb http://in.archive.ubuntu.com/ubuntu/ bionic-updates main restricted universe multiverse


I tried sudo apt-get update
and facing this issue ,
1 Metadata [2,468 B]
Reading package lists... Done                                        
E: The repository 'https://download.docker.com/linux/ubuntu $(lsb_release Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

Unable to proceed.

**Comment by thaJeztah** [comment]
Looks like you added `$(lsb_release` as a literal string in one of your repository configuration files (instead of the output);

```
E: The repository 'https://download.docker.com/linux/ubuntu $(lsb_release Release' does not have a Release file.
```

**Comment by danman01** [comment]
I was all like, "None of these misspellings are in my sources file", but then I read the error message for the 10th time, and realized `bioninc` != `bionic`

**Comment by abonne01** [comment]
hello,

sorry again to bother with this issue. I have the error above, but as far as I checked, I correctly configure the file source.list :
```
#  cat /etc/apt/sources.list.d/docker.list
deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu   bionic stable
#deb [signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu   bionic stable
```

This is the result of command
```

# echo   "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu bionic stable
```

But I still have the error message : 
```
# apt update
Ign:2 https://download.docker.com/linux/ubuntu bionic InRelease
Err:3 https://download.docker.com/linux/ubuntu bionic Release
  Certificate verification failed: The certificate is NOT trusted. The received OCSP status response is invalid.  Could not handshake: Error in the certificate verification. [IP: 52.222.158.94 443]
Hit:4 http://archive.ubuntu.com/ubuntu bionic InRelease
Hit:5 http://archive.ubuntu.com/ubuntu bionic-updates InRelease
Hit:6 http://archive.ubuntu.com/ubuntu bionic-backports InRelease
Hit:7 http://archive.ubuntu.com/ubuntu bionic-security InRelease
Reading package lists... Done
**E: The repository 'https://download.docker.com/linux/ubuntu bionic Release' does not have a Release file.**
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

```

thanks a lot in advance for help

**Comment by jacob-r-anderson** [comment]
Accidently installed a debian version on ubuntu 18.04. I invariably get this error when running sudo apt update. I removed the PPA in the Ubuntu Software update GUI, but I still get this problem. Is it possible to manually remove the file(s) causing this error?


```

E: The repository 'https://download.docker.com/linux/debian bionic Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```
