### ISSUE TITLE
"An internal error has occured" after password reset

### ISSUE THREAD

**Issue by jralmaraz** [docker/hub-feedback#1547]
Hi,

I have been trying to reset my password in docker hub and get the message "An internal error has occured" after doing so. I have tried 3 times so far, no luck on succeeding. While doing the password reset process, I successfully get the e-mail with the link, but, no status (fail or success) of the actual reset process, I submit the new password and get no feed-back from the UI.

PS: typo in the occurred word in the error message

Thanks.

Jose

![image](https://user-images.githubusercontent.com/13877691/41824357-ed33d8b4-7862-11e8-86dc-5dc9f6c033ec.png)

**Comment by jralmaraz** [comment]
![image](https://user-images.githubusercontent.com/13877691/41824401-7d8f0b72-7863-11e8-910c-b921d881e438.png)

Actual reset is also failing as per the 500 return code on browser.

**Comment by ehayon** [comment]
Looks like docker.io is having a more widespread issue. I am not even able to push images to the registry right now.

**Comment by tifayuki** [comment]
There is a server error on our side, we are looking into it: https://status.docker.com/

**Comment by tifayuki** [comment]
The issue has been resolved
