### ISSUE TITLE
Service unavailable -  503

### ISSUE THREAD

**Issue by renatojava** [docker/hub-feedback#1548]
When I try to pull the image from docker hub I catch the error:

~ $ docker run wurstmeister/zookeeper
Unable to find image 'wurstmeister/zookeeper:latest' locally
docker: Error response from daemon: Get https://registry-1.docker.io/v2/wurstmeister/zookeeper/manifests/latest: received unexpected HTTP status: 503 Service Unavailable.

**Comment by CATHGX** [comment]
Yeah it's solved my build passed !

**Comment by velo** [comment]
Same here for the past 24 hours.

Failing locally and on the cloud... macOS and linux.
<img width="815" alt="screen shot 2018-06-25 at 10 43 10 am" src="https://user-images.githubusercontent.com/136590/41824776-65916b4e-786a-11e8-83a4-45e8ea47c3fc.png">

**Comment by manishtomar** [comment]
We [had problems](https://status.docker.com/pages/history/533c6539221ae15e3f000031) in our caching system causing errors. It has since been fixed. Thanks for your patience.

**Comment by SupermanAdam007** [comment]
It is working now. I hope it will be.

https://status.docker.com/pages/533c6539221ae15e3f000031

Good job! :+1:
