### ISSUE TITLE
BAD REQUEST when trying to create automated build

### ISSUE THREAD

**Issue by das-g** [docker/hub-feedback#1550]
## To reproduce

1. Sign in to https://hub.docker.com and choose "Create" > "Create Automated Build"

   ![menu](https://user-images.githubusercontent.com/97746/41977360-67536b60-7a1f-11e8-9b70-df02021fba9d.png)
2. Choose "Github" (I already had my accounts linked)

   ![git repo host choices](https://user-images.githubusercontent.com/97746/41977466-b08e9142-7a1f-11e8-8121-7d823fb9db41.png)
3. Choose the organization or user that owns the Git repo with the Dockerfile and search for the Git repo name

   ![repo selection](https://user-images.githubusercontent.com/97746/41977555-eb2c48e4-7a1f-11e8-8c02-7361b84592f1.png)
4. Click that Git repo name and in the following form, choose the Docker repo namespace, adapt the Docker repo name if needed and provide some description

   ![form](https://user-images.githubusercontent.com/97746/41977686-3bea6478-7a20-11e8-8334-585badd12521.png)
5. Click "Create" button

### Expected
The system displays the home page for my newly created automated build. (See [documentation](https://docs.docker.com/docker-hub/builds/#create-an-automated-build).)

### Observed
Nothing seems to happen: Browser stays on that form.

In the browser console, it says:
```
POST https://hub.docker.com/v2/repositories/geometalab/asciidoctor-with-latest-mathematical/autobuild/ 400 (BAD REQUEST)
```
for `client.js` line 960

**Comment by das-g** [comment]
Already when loading the form, these errors where logged to the console:

```
/v2/services/check/bitbucket/:1 Failed to load resource: the server responded with a status of 404 (NOT FOUND)
/v2/repositories/geometalab/docker-asciidoctor-with-latest-mathematical/autobuild/:1 Failed to load resource: the server responded with a status of 400 (BAD REQUEST)
/v2/services/check/bitbucket/:1 Failed to load resource: the server responded with a status of 404 (NOT FOUND)
```

**Comment by fczuardi** [comment]
I fixed my problem by connecting to Github again, I think the organization for that project wasnt linked to github
