### ISSUE TITLE
DockerHUb - micro plan - payment

### ISSUE THREAD

**Issue by hbiscan** [docker/hub-feedback#1560]
I have issues with upgrading account to micro plan. When I enter all my payment details this pops out nevertheless I entered all the fields: "There was an error updating your account profile information. Please check your information and try again."  Did you encounter the same problem?

**Comment by tescherm** [comment]
@hbiscan thanks for the report, could you provide your docker username?

**Comment by hbiscan** [comment]
hello, it is hbiscan

**Comment by tescherm** [comment]
@hbiscan I had a look, it looks like you were able to update your account information successfully, but your card was not added. Could you check your card information and try again? We accept the following types of cards:

Visa
MasterCard
American Express
JCB, Discover
Diners Club

Also verify that you do not have an outstanding balance on the card, your bank might be declining it for that reason.
