### ISSUE TITLE
How to Enable any docker container for AD Authentication or Ldap authentication

### ISSUE THREAD

**Issue by sconrod-tester** [docker/hub-feedback#1568]
How can I go about configuring a docker image to use AD authentication. For example, I am running Grafana inside a docker container, and I would like the users to logon to the interface using their Active Directory account instead of local accounts. I was not able to find any documentation on how to do this.

**Comment by kungfu71186** [comment]
http://docs.grafana.org/installation/ldap/

Looks like you need to set it up in the config file. Docker images only run the application, it doesn't configure them. You would need to create the proper config file and then add it to the image.

**Comment by luogeshibu** [comment]
i use docker image ubuntu 20.04, and my docker host is already work with AD Authentication or Ldap authentication. i can login with domain user name to my docker host. is there any way that my container use AD Authentication or Ldap authentication.
