### ISSUE TITLE
Account not activated yet?

### ISSUE THREAD

**Issue by AlexSurya** [docker/hub-feedback#1573]
im signup on docker when im login im getting Account not active yet. Please check your email to activate your account but im not getting the main

**Comment by nandhini915** [comment]
https://github.com/docker/hub-feedback/issues/1572#issuecomment-404818570 -- we have an ongoing issue that is preventing user activation. We will provide an update as soon as we have one.

**Comment by nandhini915** [comment]
Hi, our signup/activation email issues should've resolved. If you haven't received an activation email yet, please respond to this ticket with your Docker user ID and we will manually activate (if you've signed up)

**Comment by nile** [comment]
can receive active mail with exmail.qq.com
