### ISSUE TITLE
Unable to create new automated build from GitHub repository

### ISSUE THREAD

**Issue by skymoo** [docker/hub-feedback#1574]
Trying to setup a new automated build with a repository on GitHub, so I log in to my Docker Hub and then try to seup a new automated build by doing the following:

1. select Create New Automated Build from the the Create Menu
1. select Create Auto-build Github button

Nothing happens but eventually an error is displayed stating:

An error occurred while trying to connect to github
Link your account [here](https://hub.docker.com/account/authorized-services/)

But my GitHub account is already linked. If I unlink, relink, and try to create the build again I receive the same error.

**Comment by vamega** [comment]
I'm running into this issue as well.
