### ISSUE TITLE
i register a count ,bug not receive the activation email

### ISSUE THREAD

**Issue by newbie-tan** [docker/hub-feedback#1576]
i register a count ,bug not receive the activation email,my email  address is "newbiwtan@163.com".

**Comment by newbie-tan** [comment]
i register a count ,bug not receive the activation email,my email address is "newbiwtan@163.com".

**Comment by nandhini915** [comment]
Hi,
Please go to https://success.docker.com/ and open a ticket so our support team can activate your account.
