### ISSUE TITLE
Build failed from Bitbucket repo

### ISSUE THREAD

**Issue by fbeghini** [docker/hub-feedback#1579]
Hi everyone, 
I linked a Bitbucket repo for an automated build. When the build is triggered, it stays queued for a few hours and after it tries to build but it fails.
I have only but a simple **Build failed: Build canceled.** error and nothing more than this error is logged.

The full log is [here](https://hub.docker.com/r/segatalab/metaphlan2/builds/boysa2ewvkxtkbvkih68tmh/)

Best,
Francesco

**Comment by izonder** [comment]
The same for github. Take a look onto 3 last attempts to build an image for tag 10 here: https://hub.docker.com/r/izonder/anny/builds/
Build log: https://hub.docker.com/r/izonder/anny/builds/bddvsjhmrz9hlpsqrbvpzno/

Nevertheless, the build on travis-ci was succeeded: https://travis-ci.org/izonder/anny/builds/407597004
