### ISSUE TITLE
No information about what names are valid for a team

### ISSUE THREAD

**Issue by marcusmartins** [docker/hub-feedback#158]
When attempting to create a new team for an organization, I don't get enough information about what names are valid.

![Image](https://www.dropbox.com/s/n6fn1s9hshdjh8x/Screenshot%202015-08-03%2016.27.17.png?dl=1)

**Comment by aventurella** [comment]
yup, I'm getting this exact same thing.

**Comment by scanf** [comment]
Please consider adding a section to the registration form. This is annoying and confusing.

**Comment by darshakthakore** [comment]
I have been having the same issue. I tried to create a team name with a hyphen and then an underscore and in both cases it rejected it. I tried just camelCasing the name and that got rejected too.
