### ISSUE TITLE
Docker images download are painfully slow today

### ISSUE THREAD

**Issue by sylvainOL** [docker/hub-feedback#1580]
## Problem description
Docker images download are painfully slow today

tried via ADSL( speedtest ~12Mb DL), 4G (speedtest ~30Mb DL) and even fiber (>500M DL) but I'm always stuck @3Mb/s...

These tries are coming from different machines (MacOs and Linux)

All these connections are from Orange network if it may help (IP address of "docker hub" is 104.18.125.25)

**Comment by manishtomar** [comment]
Have you got faster downloads earlier? Is it only recently slow? Can you tell me your IP address and also can you run this script and see what rate it is giving?
``bash
#!/bin/bash
# call it as <script> library/mysql blobs/sha256:2a72cbf407d67c7a7a76dd48e432091678e297140dce050ad5eccad918a9f8d6
repo=$1
url=$2
token=$(curl "https://auth.docker.io/token?service=registry.docker.io&scope=repository:$repo:pull" | jq -r .token)
curl -v https://registry-1.docker.io/v2/$repo/$url -H "Authorization: Bearer $token" -L > /dev/null
```

**Comment by sylvainOL** [comment]
Hello,
Thanks for the reply.
I’m now out of work for the week end plus holiday.
I’ll check when I go back, meanwhile I will close it.
