### ISSUE TITLE
How to report abuse?

### ISSUE THREAD

**Issue by thirsch** [docker/hub-feedback#1583]
The following namespace also contains abuse: https://hub.docker.com/u/kaitlynyij6qmitchell/

Maybe it's a good idea to introduce a link directly on a repo/image to be able to report an abuse site?

**Comment by nandhini915** [comment]
Thanks for your feedback. We have removed this user from Hub. We've implemented solutions to prevent bots from signing on and are actively investigating other means of moderating abusers.

Thank you for reporting this issue.
