### ISSUE TITLE
Access denied for Private Repos with FROM scratch

### ISSUE THREAD

**Issue by ecwillis** [docker/hub-feedback#1585]
## Problem description
Pushing certain images to private repos result in the repo on docker hub being locked with the inability to push or pull any new images or tags. Each push or pull request ends up in an error: ` requested access to the resource is denied`

All of the images for this particular issue are using `FROM scratch`.

Any thoughts?

**Comment by thaJeztah** [comment]
Could it be you reached your quota for private repositories? How many private repositories are allowed in your subscription? Perhaps you reached that limit

**Comment by ecwillis** [comment]
That was it. Wasn't my repository so I didn't know how many there we're. Would suggest possibly better error messaging but will close this.
