### ISSUE TITLE
Private repository cannot be deleted

### ISSUE THREAD

**Issue by snics** [docker/hub-feedback#1591]
## Problem description
If I want to delete the repository but always get a 404 error. I try to open the repository settings over the group's dashboard view but the 404 page always opens . So it is not possible for me to delete this repository :-{

Is there another way to delete repository?

**Comment by jmwong** [comment]
@snics sorry to hear that you're running into an issue deleting a repo. do you mind sending an email to support@docker.com with details so that we can better help you out? Thanks!
