### ISSUE TITLE
Automated regex tags not triggering, 500 on manual trigger

### ISSUE THREAD

**Issue by mplanchard** [docker/hub-feedback#1592]
## Problem description

I noticed today that the automated regex tags I have set up for `pypiserver` (https://hub.docker.com/r/pypiserver/pypiserver/) did not run when I pushed a new version. Automated builds for the `master` branch of this project have been working for some time. However, this is the first time I've pushed a tag since setting up the automated Docker Hub integration, so I thought I might be doing something wrong. I tried deleting the tag from the remote and re-creating it, to no avail.

Regardless of the automated builds working or not, I wanted to get images out for the pushed tag, so I created two tag triggers, each corresponding to the exact name of the tag (`v1.2.3`), pushing to `latest` and `v1.2.3` docker images respectively. 

When I tried to run these manually, I got a `Failed` message in the trigger button. Further investigation showed that the server was returning a 500 response:

```
HTTP/1.1 500 INTERNAL SERVER ERROR
Date: Sat, 04 Aug 2018 18:19:32 GMT
Content-Type: application/json
Transfer-Encoding: chunked
Connection: close
Vary: Cookie
X-Frame-Options: deny
Server: nginx
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
Strict-Transport-Security: max-age=31536000

{"detail": "We encountered a problem processing your request. This error has been logged and we will look into it.", "error": true}
```

This was in response to this request:

```
POST /v2/repositories/pypiserver/pypiserver/autobuild/trigger-build/ HTTP/1.1
Host: hub.docker.com
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:63.0) Gecko/20100101 Firefox/63.0
Accept: application/json
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
Referer: https://hub.docker.com/r/pypiserver/pypiserver/~/settings/automated-builds/
Content-Type: application/json
Authorization: JWT <RECACTED> 
Content-Length: 70
Cookie: ajs_user_id=null; ajs_group_id=null; ajs_anonymous_id=%22c106ddc4-4c42-47da-b587-0f93af940456%22; bf_lead=18tacos8jc0800; session_hint=1; token=<REDACTED> csrftoken=<REDACTED>
DNT: 1
Connection: keep-alive

{"source_name":"v1.2.3","source_type":"Tag","dockerfile_location":"/"}
```

I did manage to get the builds to trigger by changing them from `tag` builds to `branch` builds, with the same source ref (`v1.2.3`), and then triggering manually, but this is obviously non-intuitive and not ideal.

**Comment by froblesmartin** [comment]
I am facing the same issue. A regex source works with branches but no with tags.

**Comment by zanes2016** [comment]
We are also facing this issue. I see that only non-regex source works with tags in our Bitbucket Repository. 

Also, when we remove the beginning and end slashes `/`, we get the **Trigger** button to show up on the UI. However, the Build status immediately goes to **FAILED** without producing any recent build logs. 
Something is amiss.

**Comment by meticulous-dft** [comment]
Hi @zanes2016 Trigger dose not work with regex, because it is non deterministic.

**Comment by zanes2016** [comment]
Thank you @meticulous-dft , that reflects the behavior we're seeing.
