### ISSUE TITLE
New image is pushed but not shown on "tags" page

### ISSUE THREAD

**Issue by bin3377** [docker/hub-feedback#1594]
## Problem description
We pushed a new version of image to one private repository on dockerhub today with `docker push`. The image is available with `docker pull` from other machine but not shown on "tags" page and the latest push on UI is still 1 month ago

https://hub.docker.com/r/sumologic/collector-beta/tags/

**Comment by jmwong** [comment]
Hi @bin3377, sorry for the inconvenience caused. We had an incident yesterday that might have caused the delay in push events: https://status.docker.com/pages/incident/533c6539221ae15e3f000031/5b69e593da107a4e20898aae. I've updated your tag accordingly. Please reach out to support@docker.com if you run into any further issues. Thanks!
