### ISSUE TITLE
Remove Billing info

### ISSUE THREAD

**Issue by arteniioleg** [docker/hub-feedback#1596]
I accidentally bought a private repo plan for my account instead of organization.
I want to remove all my billing information, especially credit card details.

![staticshot_10-08-2018_09-31-51](https://user-images.githubusercontent.com/28860670/43942544-1efad07c-9c81-11e8-98fd-e908be7c3bfa.png)

**Comment by arteniioleg** [comment]
_Reopen of https://github.com/docker/hub-feedback/issues/861_

**Comment by nandhini915** [comment]
You can go to https://success.docker.com/article/how-do-i-cancel-or-downgrade-my-docker-subscription to view workarounds. We also have a link to our support portal listed, and Docker Support can help you remove your credit card info.
