### ISSUE TITLE
How to get a refund?

### ISSUE THREAD

**Issue by arteniioleg** [docker/hub-feedback#1597]
I accidentally bought a private repo plan for my account instead of organization.
I downgraded back to Free plan after a few minutes.

[The docs](https://success.docker.com/article/transfer-billing-from-user-account-to-organization) say that the system will do a refund automatically.

> If you cancel an existing subscription the billing system automatically prorates and refunds any charges.

But after one day I didn't receive the money back on my credit card.

1. Please add in docs info about how long it will take for the refund to happen.
2. Can you check my account (username `arteniioleg`) if the refund has started?

![staticshot_10-08-2018_09-31-51](https://user-images.githubusercontent.com/28860670/43942753-e02ca270-9c81-11e8-9032-327dbd3f6be2.png)

**Comment by nandhini915** [comment]
Hi @arteniioleg - if your refund has still not processed, you may open a ticket at https://success.docker.com/support (screenshot attached). ![Screenshot](https://user-images.githubusercontent.com/2453622/42834230-695d1064-89ab-11e8-9e27-6ead616cfe92.png)
