### ISSUE TITLE
how to add formatting to description (repo info)

### ISSUE THREAD

**Issue by condor-the-bird** [docker/hub-feedback#1598]
## Problem description
I see that some repos have well-formatted readme's (repo info, e.g. https://hub.docker.com/r/portainer/portainer/ ), some do not. Markdown is not supported, neither is plain html. Is it a paid feature? 
Browsed documentation, failed to find anyting.

**Comment by manishtomar** [comment]
The description is not taken from Readme file like in a Github repo. It is entered manually by clicking on edit button in the UI.

![44051017-931eeb0a-9eed-11e8-98d1-d85384d66d3f](https://user-images.githubusercontent.com/758529/44051086-bedd4cf0-9eed-11e8-85b5-1e555784a557.png)
