### ISSUE TITLE
Malicious crypto-mining images: https://hub.docker.com/r/dockerminer/

### ISSUE THREAD

**Issue by NivLipetz** [docker/hub-feedback#1600]
The following repository: https://hub.docker.com/r/dockerminer/ contains malicious crypto mining images. 

The image used to mine the XMR coin using a Minergate pool is **dockerminer/etcd** while the image **dockerminer/scan_marathon_forever** is used to scan Shodan's api to find victim hosts.

This is the following code taken from dockerminer/scan_marathon_forever script that it runs:
[scan_marathon_forever_script.txt](https://github.com/docker/hub-feedback/files/2280816/scan_marathon_forever_script.txt)

please remove these images

**Comment by manishtomar** [comment]
Thanks for the report. The account has been deactivated.
