### ISSUE TITLE
Run Nexus using Docker in AWS Linux Instance

### ISSUE THREAD

**Issue by kushaangdeswal** [docker/hub-feedback#1605]
## Problem description
Hi All,
I am trying to run nexus in AWS Linux instance using docker. My docker is installed and running but I don't know how to proceed further with nexus installation. 
Please help me out.

**Comment by nandhini915** [comment]
Hi @kushaangdeswal 
If you are a community user using our Docker Engine product, Please go to https://forums.docker.com/ and verify if other members in the community have run into this issue, or post an issue back to the community.
If you are a user with a subscription to Docker Enterprise, you can go to https://success.docker.com/ and obtain help.
