### ISSUE TITLE
Problem creating GitHub automated build

### ISSUE THREAD

**Issue by frankier** [docker/hub-feedback#1607]
## Problem description

When I try to create and automated build with this GitHub account, nothing happens. Occasionally after waiting a long time I get an error message telling me to link my account. I have linked the account and it was working previously.

**Comment by jcortejoso** [comment]
I'm having same issues. I think it is a temporal problem.

**Comment by JPZ13** [comment]
@frankier @jcortejoso Sorry that y'all are having this issue. To help us fix it, can y'all post some screenshots of the errors you're seeing?

**Comment by frankier** [comment]
![screenshot from 2018-08-23 07-57-14](https://user-images.githubusercontent.com/299380/44505579-c421ca00-a6aa-11e8-9e75-c9d3847efa87.png)

**Comment by jcortejoso** [comment]
I guess I have other problem. My problem is that the images take an eternity to start to build:
![image](https://user-images.githubusercontent.com/5635989/44512569-5336de00-a6bb-11e8-96f1-46c7c3a46fc2.png)
After almost 3 hours waiting it built without problem, but I have tried again now and it is waiting for 30m now...

**Comment by satra** [comment]
same issue for me. error connecting to github.

**Comment by JPZ13** [comment]
@frankier - Sorry for the delay. The issue that you're having requires us to do a bit of a deep dive. In the meantime, can you use Docker Cloud Autobuilds? It will unblock you immediately. [Here's a link to the documentation.](https://docs.docker.com/docker-cloud/builds/automated-build/#configure-automated-build-settings)

**Comment by tomkralidis** [comment]
Having the same issue here:

looking at Web Console in FF 62:
```
Use of XMLHttpRequest’s timeout attribute is not supported in the synchronous mode in window context. munchkin.js:11:377
TypeError: t.response.body is null[Learn More]
```
