### ISSUE TITLE
UDP Port Exposure (PXE server issues)

### ISSUE THREAD

**Issue by JohanBerg78** [docker/hub-feedback#1613]
Hi good day. I am having trouble getting my PXE server visible on my Ethernet LAN. Please see [https://github.com/jumanjihouse/docker-tftp-hpa/issues/16] as well (a report to the image contributor). The physical PXE clients on the LAN are not able to communicate to the docker containers I have tried (docker-tftp-hpa is not the only one, I even have my own PDHCP/TFTP solution which has the same problem).

**Comment by manishtomar** [comment]
Hi @JohanBerg78 We do not handle issues related to images. Please track it with image contributor.

**Comment by JohanBerg78** [comment]
Hi. What do you mean by track it with image contributor? As I said before I am one of the image contributors relating to this problem, and my UDP services are not reachable from the host network. Wireshark confirms this the packets do not reach the container at all.

**Comment by JohanBerg78** [comment]
# Use an official Python runtime as a parent image
FROM solita/ubuntu-systemd

ENV DEBIAN_FRONTEND noninteractive

# Set the working directory to /app
WORKDIR /app
#WORKDIR /

# Copy the current directory contents into the container at /app
COPY . /app

# Install any needed packages and copy+install our daemons into the image
RUN apt-get update \
&& apt-get install -y --no-install-recommends apt-utils zip unzip libboost-all-dev iputils-ping net-tools \
&& apt-get clean \
&& rm -rf /var/lib/apt/lists/* \
&& mkdir -pv /var/log/brainwaregroup \
&& mkdir -pv /usr/share/brainwaregroup/tftpdata \
&& mkdir -pv /etc/brainwaregroup \
&& cp /app/ColumbusPbs.out /usr/sbin \
&& cp /app/preboot.conf /etc/brainwaregroup \
&& cp /app/preboot.log /var/log/brainwaregroup \
&& cp /app/ColumbusPbs.service /lib/systemd/system/multi-user.target.wants \
&& chmod 766 /lib/systemd/system/multi-user.target.wants/ColumbusPbs.service \
&& unzip /app/pxedata.zip -d /usr/share/brainwaregroup/tftpdata

# Make PXE ports available to the world outside this container
EXPOSE 67/udp 4011/udp 69/udp

**Comment by manishtomar** [comment]
@JohanBerg78 If you are having trouble with using Docker (which based on your description seems to be the case) then please check forums.docker.com and success.docker.com for possible solutions. If you think you've found a problem with the Docker Engine then please feel free to open an issue or look for existing one in https://github.com/moby/moby/. This github repo is only used to track issues w.r.t functioning of Docker Hub.
