### ISSUE TITLE
Billing Issues with unsettled invoices

### ISSUE THREAD

**Issue by ebridge2** [docker/hub-feedback#1615]
## Problem description

When an invoice is left unpaid, there is no way to rectify it without manually contacting docker's billing team. This is the same issue as https://github.com/docker/hub-feedback/issues/1054.

Our case was switching credit cards and forgot to switch over the docker credit card, leaving our billing invoice unpaid. Seems like something that the front end should be able to handle (or could be able to handle pretty easily), so I've opened a new issue

**Comment by ebridge2** [comment]
Yes; i had 1 unpaid invoice on my account from a previous card bounce afte
changing cards and not updating docker billing. I have contacted docker.com
and been given a support ticket, but i have no idea how long that will take
to address, whereas it seems easy natural to support 1) above in a future
release so these issues could be resolved instantaneously.

**Comment by thomas-jakemeyn** [comment]
My company is facing the exact same problem. We first tried to contact the Docker support team but we did not get any answer. After wasting some precious time for our business, we decided to contact the billing team directly (billing@docker.com). We are now waiting for their help.

Having a way to re-trigger a failed payment ourselves (automated or not) would have been really welcome.

**Comment by ThomasStubbe** [comment]
Same problem here...

**Comment by am-mnandor** [comment]
Billing page isn't loading for any of the organizations I am using. Is this the same for everyone?
I tried to contact support also, but no response yet :disappointed:
