### ISSUE TITLE
No matching manifest for library/gradle

### ISSUE THREAD

**Issue by msrd0** [docker/hub-feedback#1618]
There seems to be an issue with `library/gradle`.

This is what I found today on Docker Hub for my automated build:

```
Building in Docker Cloud's infrastructure...
Cloning into '.'...

KernelVersion: 4.4.0-1060-aws
Components: [{u'Version': u'18.03.1-ee-1-tp5', u'Name': u'Engine', u'Details': {u'KernelVersion': u'4.4.0-1060-aws', u'Os': u'linux', u'BuildTime': u'2018-06-23T07:58:56.000000000+00:00', u'ApiVersion': u'1.37', u'MinAPIVersion': u'1.12', u'GitCommit': u'1b30665', u'Arch': u'amd64', u'Experimental': u'false', u'GoVersion': u'go1.10.2'}}]
Arch: amd64
BuildTime: 2018-06-23T07:58:56.000000000+00:00
ApiVersion: 1.37
Platform: {u'Name': u''}
Version: 18.03.1-ee-1-tp5
MinAPIVersion: 1.12
GitCommit: 1b30665
Os: linux
GoVersion: go1.10.2
Starting build of index.docker.io/msrd0/gradle:latest...
Step 1/4 : FROM gradle:alpine


no matching manifest for linux/amd64 in the manifest list entries
```

Trying to pull on ArchLinux:

```
$ docker pull gradle:alpine
alpine: Pulling from library/gradle
no matching manifest for unknown in the manifest list entries
```

**Comment by nikita-v** [comment]
Same issue with nginx:alpine.
Perhaps this is due to the fact that the build worker for the amd64 architecture is offline.
https://doi-janky.infosiftr.net/computer/multiarch-amd64/
https://doi-janky.infosiftr.net/job/multiarch/job/amd64/job/gradle/

**Comment by nbukhter** [comment]
I also have the same issue.
Is there any ETA to resolve it?

**Comment by cuotos** [comment]
same here, while some of the nginx images are still available, non of the gradle ones are. causes a bit of an issue to our automated build pipelines

**Comment by msrd0** [comment]
Both `gradle` and `nginx` seem to be downloadable again. Thanks for resolving the issue
