### ISSUE TITLE
Error: A firewall is blocking file sharing between Windows and the containers

### ISSUE THREAD

**Issue by kpratihast** [docker/hub-feedback#1619]
The issue of 'A firewall is blocking file sharing between Windows and the containers' still persists in Docker for Windows v18.06.1-ce. 

The below article mandates to have a previous version (17.06.0-ce-win18 12627) in order for the fix to work:
https://success.docker.com/article/error-a-firewall-is-blocking-file-sharing-between-windows-and-the-containers

Any workaround / plans to fix this issue in the latest version ?

**Comment by manishtomar** [comment]
Issue moved to [docker/for-win #2512](https://github.com/docker/for-win/issues/2512) via [**ZenHub**](https://www.zenhub.com/)
