### ISSUE TITLE
Unable to run mysql, it will stop automatically.

### ISSUE THREAD

**Issue by Hiolen** [docker/hub-feedback#1621]
## mysql will stop automatically
All my settings are working. 

Yesterday I encounter a problem that my mysql is not working anymore. If I up my  docker `docker-compose up -d` the mysql will run just a seconds and it will stop automatically.

See my logs
<img width="1280" alt="screen shot 2018-08-31 at 10 51 12" src="https://user-images.githubusercontent.com/40222158/44894940-b6141f00-ad24-11e8-9b6b-017172421ec8.png">

<img width="848" alt="screen shot 2018-08-31 at 11 22 18" src="https://user-images.githubusercontent.com/40222158/44894962-c88e5880-ad24-11e8-9e49-fae1fce8c8ac.png">

I already try this solution 
https://dba.stackexchange.com/questions/163445/innodb-ignoring-the-redo-log-due-to-missing-mlog-checkpoint at some point its still not working.

Is there anyone who encounter this problem and can you please guide how to fix this.

**Comment by manishtomar** [comment]
This tracker is for issues with Docker Hub only. This maybe be problem with mysql image for which you can file issue at https://github.com/docker-library/mysql/issues. The link is there in image description https://hub.docker.com/_/mysql.
