### ISSUE TITLE
COPY failed in a Docker Hub multi-stage build

### ISSUE THREAD

**Issue by arey** [docker/hub-feedback#1622]
Hi,

On my Macbook, this gradle Dockerfile is building with Docker 18.05.0-ce-rc1-mac63.
But on Docker Hub, it's failing on the following issue:

> Build failed: COPY failed: stat /var/lib/docker/overlay2/a76323b8722610e18ef8b037f7e706f0a945ea9a20fe59ee1d4b5642bb974688/merged/home/gradle/src/build/libs/spring-petclinic-kotlin.jar: no such file or directory

You may have the full log here: https://hub.docker.com/r/arey/spring-petclinic-kotlin/builds/bvrv6fqt6nbkvthcplbavg6/

It looks like the path from the 1st stage is invalid. I don’t know why the behavior is not the same between my laptop and  Docker Hub. Do you have any idea? Maybe a different Docker version? Do you know how I can debug?

Regards

**Comment by nandhini915** [comment]
Hi @arey -- we use `docker-ee 18.03` for our Docker Autobuilds. Hope this helps.
