### ISSUE TITLE
Unable to convert user to organization

### ISSUE THREAD

**Issue by kasunt84** [docker/hub-feedback#1623]
Im unable to convert a user (https://hub.docker.com/u/steadypay/) to an Organization. I tried to add a owner account (kasunt84) in https://hub.docker.com/account/convert-to-org however no errors were displayed.

I then looked at the dev tools to only notice a 503 error, `https://hub.docker.com/account/convert-to-org/`.

Can someone please take a look at this for me.

**Comment by ArtificialPB** [comment]
Can confirm that we're unable to convert user to an organization. I however do not get error 503 in the dev tools console.

**Comment by kasunt84** [comment]
Any reason for this ?

I still get the `503` when trying to convert. Shows the error `{"detail": "Unable to convert user to organization at this time. Please try again later."}`

**Comment by ArtificialPB** [comment]
@kasunt84 checked again, this time with a different browser, and it reported the 503 error.

**Comment by kasunt84** [comment]
@ArtificialPB does that mean i have to remove the user somehow and create it as an organization ?

**Comment by Morreski** [comment]
+1

**Comment by kiwileaks78** [comment]
Same there ...

**Comment by manishtomar** [comment]
We are actively looking into this issue and will post an update soon. Thanks for your patience.

**Comment by dahln** [comment]
I am also seeing this error.

**Comment by dahln** [comment]
I just attempted to convert an account to an organization and it worked. I'm not certain what/if anything changed.

**Comment by manishtomar** [comment]
I am sorry we deployed a fix for this few hours ago. I forgot to update this thread. Thanks for updating. I am going to close this now. Please let us know if this occurs again. Sorry for the inconvenience and thanks for your patience.

**Comment by peterrattew** [comment]
Im getting a similar error while trying to convert my company account into an organisation.

400 (Bad Request) - User must first leave all organizations and groups.

My personal account is not part of any organisations or groups and same for the company account so i am not sure why i am getting this response.

**Comment by vladimirtiukhtin** [comment]
Cannot conver my account to an organisation. Getting

"Something went wrong. We can not convert your account at this time."

**Comment by manishtomar** [comment]
@vladimirtiukhtin What is your hub user name that is failing?

**Comment by vladimirtiukhtin** [comment]
Hi @manishtomar. It is "**hippolab**"

**Comment by manishtomar** [comment]
@vladimirtiukhtin Can you try again and look for the API response in browser network inspector? Unfortunately error reporting is broken and we are working to fix it.

**Comment by vladimirtiukhtin** [comment]
@manishtomar thanks for the advice. So, I got HTTP 400
```
{"non_field_errors": ["User must first leave all organizations and groups."]} 
```
But, my "Organizations" page is empty

**Comment by manishtomar** [comment]
Hmm. Will investigate and get back.

**Comment by vladimirtiukhtin** [comment]
@manishtomar have you had a chance to look at the issue? Thanks

**Comment by manishtomar** [comment]
@vladimirtiukhtin Can you please create a support ticket by going to https://hub.docker.com/support/contact/ ? I am not sure I can share the reason here.
