### ISSUE TITLE
Cannot convert user into organization (no error displayed)

### ISSUE THREAD

**Issue by adinriv** [docker/hub-feedback#1624]
## Problem description
I'm trying to convert a user into an organization, and no error is displayed.  

As indicated in the knowledgebase the users are no part of another organization or teams.  The user I'm trying to convert not even has a repository.

Further testing shows that when adding white-spaces to the new owner's ID triggers a "user doesn't exist" error.  But the correct user name has no effect.

## Docker Hub Account Issues

User trying to be converted into organization: mipl
User that will be the owner: adnrv

**Comment by jmwong** [comment]
We’re sorry about the inconvenience caused. To help us diagnose better, can you provide an error trace from your browser’s dev tools?

**Comment by adinriv** [comment]
On firefox it produces no error (not even on the console).  On Chrome it outputs:

```
client.js:960 POST https://hub.docker.com/v2/users/mipl/convert_to_org/ 503 (Service Temporarily Unavailable)
d.end @ client.js:960
v @ Users.js:149
e.exports @ convertToOrganization.js:7
(anonymous) @ callAction.js:21
e.exports @ $.invoke.js:5
v.(anonymous function) @ $.task.js:31
y @ $.task.js:19
h @ $.task.js:23

```

**Comment by house-md** [comment]
@adinriv I can confirm this. Today I got exactly the same error. In firefox no error even in console but chrome shows POST https://hub.docker.com/v2/users/ableteam/convert_to_org/ 503 (Service Temporarily Unavailable)

**Comment by adinriv** [comment]
I guess this makes it the same issue as https://github.com/docker/hub-feedback/issues/1623

**Comment by manishtomar** [comment]
This is same as #1623 which has been fixed few hours ago. Please let us know if you find any other problems.
