### ISSUE TITLE
libcontainerd: failed to receive event from containerd

### ISSUE THREAD

**Issue by SocialCrypt-Verify** [docker/hub-feedback#1626]
My server started to hang for a bit then I went to check the logs and found this:

## Problem description
`Sep  6 13:36:30 *** dockerd-current: time="2018-09-06T13:36:30.947564848+02:00" level=error msg="libcontainerd: failed to receive event from containerd: rpc error: code = 13 desc = transport is closing"
Sep  6 13:36:31 *** d*ockerd-current: time="2018-09-06T13:36:31.143498042+02:00" level=info msg="libcontainerd: new containerd process, pid: 20518"
Sep  6 13:36:34 *** dockerd-current: time="2018-09-06T13:36:33.255841171+02:00" level=info msg="libcontainerd: new containerd process, pid: 20519"
Sep  6 13:36:35 *** dockerd-current: time="2018-09-06T13:36:35.905058818+02:00" level=info msg="libcontainerd: new containerd process, pid: 20525"
Sep  6 13:36:43 *** dockerd-current: time="2018-09-06T13:36:43.464359810+02:00" level=info msg="libcontainerd: new containerd process, pid: 20526"
Sep  6 13:36:47 *** dockerd-current: time="2018-09-06T13:36:47.552413823+02:00" level=info msg="libcontainerd: new containerd process, pid: 20532"
....................
`

Suddenly I found this error in my messages logs.

I run Cent OS 7 with MySQL-MariaDB 10.2 on docker. MariaDB logs and rest of the logs are clean, my server is running good now but this could happen again?
Have no idea where to look for issues.

**Comment by manishtomar** [comment]
This tracker is for problems with Docker Hub only. Kindly open an issue in https://github.com/moby/moby/issues/ for issues pertaining to Docker Engine.
