### ISSUE TITLE
Can't pull image from hub.docker.com

### ISSUE THREAD

**Issue by arch1tect0r** [docker/hub-feedback#1627]
## Problem description
```
docker run hello-world
Unable to find image 'hello-world:latest' locally
docker: Error response from daemon: Get https://registry-1.docker.io/v2/: net/http: TLS handshake timeout.
```
```
docker pull hello-world
Using default tag: latest
Error response from daemon: Get https://registry-1.docker.io/v2/: net/http: TLS handshake timeout
```

What's going on?

**Comment by mohibakhan** [comment]
I'm having a similar issue.  Did you find out what was causing it?

**Comment by arch1tect0r** [comment]
@mohibakhan No. I closed issue because I don't get any feedback here.

**Comment by mohibakhan** [comment]
I was able to pull the image now.  The problem for me was the proxy settings.
I put this under Docker Settings > Proxies : Select Manual proxy configuration.
http://user:user@proxyurl:portnumber/

**Comment by hussain1406** [comment]
i was facing this same issue and i solved it by logging into the docker hub. as now docker supports ipv6 it requires authentication.
here's the link: https://www.docker.com/blog/docker-hub-registry-ipv6-support-now-generally-available/
