### ISSUE TITLE
How to Remove ProgramData\docker\windowsfilter

### ISSUE THREAD

**Issue by JackyVeracitiz** [docker/hub-feedback#1628]
## Problem description

The programdata\docker\windowsfilter is having high volume data while pulling images.

Can any one guide if we uninstall will it hep or not? 

We are not able to delete them with powershell nor it is getting uninstall

**Comment by nandhini915** [comment]
Hi @JackyVeracitiz 
If you are a community user using our Docker Engine product, Please go to https://forums.docker.com/ and verify if other members in the community have run into this issue, or post an issue back to the community.
If you are a user with a subscription to Docker Enterprise, you can go to https://success.docker.com/ and obtain help.
