### ISSUE TITLE
Service unavailable (503) when trying to pull an image

### ISSUE THREAD

**Issue by RogerLapin** [docker/hub-feedback#1632]
Hi,
## Problem description
I can't pull images or login to docker registry.
I used to do it with no problem, but today ends up returning only such error :

```
# docker pull debian:stretch-slim
Error response from daemon: Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
```
```
# docker login
Login with your Docker ID to push and pull images from Docker Hub. If you don't have a Docker ID, head over to https://hub.docker.com to create one.
Username: ***
Password: ***
Error response from daemon: Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
```

## Additional details

When I perform a _ping_ onregistry-1.docker.io, it ends up with 100% packet loss.
When I perform a curl, I get a "moved permantly answer"
```
# curl https://registry-1.docker.io/v2
<a href="/v2/">Moved Permanently</a>.
```

I used to be behind a company proxy, but I bypassed it using a direct internet connection. 
I also unset all my http(s)_proxy/HTTP(S)_proxy variables, removed them also from /etc/default/docker and restarted my docker daemon.

I tried from both a VM-hosted ubuntu 16.04 and a Windows 7 EE.
My docker version is 18.03.0-ce, build 0520e24

**Comment by jmwong** [comment]
Sorry to hear that you’re having trouble pulling an image. Have you tried doing it on a different network?

**Comment by RogerLapin** [comment]
Yes, on two different network : company network, and external one.
I am not sure this is a Docker Hub issue, but since I never had any problem before, and since I don't remember doing anything specific that sounds related to my problem, I wondered if there was something wrong with the hub

**Comment by RogerLapin** [comment]
Eventually, it was on my side : my ip had changed (and I had no clue about it!), and the configuration set up in /etc/systemd/system/docker.service.d/http-proxy.conf was thus obsolete.

The solution was then to change this variable :

`[Service]
      Environment="HTTP_PROXY=http://1<newIp>:<proxyPort>/"`

**Comment by rsgilbert** [comment]
I had this problem because I had setup a proxy on my macbook weeks back and forgot to disable it. Disabling fixed the problem. You can check the status of docker hub using this link: https://status.docker.com/

**Comment by einsteinarbert** [comment]
> Eventually, it was on my side : my ip had changed (and I had no clue about it!), and the configuration set up in /etc/systemd/system/docker.service.d/http-proxy.conf was thus obsolete.
> 
> The solution was then to change this variable :
> 
> `[Service] Environment="HTTP_PROXY=http://1<newIp>:<proxyPort>/"`

Yeah, I must to remove this file which owner from old user, and login worked.

**Comment by jaroslawhartman** [comment]
For reference and those who came to this page from a web search:
```
# curl https://registry-1.docker.io/v2
<a href="/v2/">Moved Permanently</a>.
```

There should be a slash at the end, ie.e.

```
# curl https://registry-1.docker.io/v2/
*   Trying 127.0.0.1:32000...
* Connected to localhost (127.0.0.1) port 32000 (#0)
> GET /v2/ HTTP/1.1
> Host: localhost:32000
> User-Agent: curl/7.88.1
> Accept: */*
>
< HTTP/1.1 200 OK
< Content-Length: 2
< Content-Type: application/json; charset=utf-8
< Docker-Distribution-Api-Version: registry/2.0
< X-Content-Type-Options: nosniff
< Date: Thu, 25 Jan 2024 16:44:39 GMT
<
* Connection #0 to host localhost left intact
```

**Comment by lbolanos** [comment]
I have this now
curl https://registry-1.docker.io/v2/
{"errors":[{"code":"UNAUTHORIZED","message":"authentication required","detail":null}]}
