### ISSUE TITLE
WebSocket connection to 'ws://localhost:3000/' failed: Connection closed before receiving a handshake response

### ISSUE THREAD

**Issue by lingdongyuanjia** [docker/hub-feedback#1635]
I am learning nodeJS recently .when I learn websocket,I meet a error:

server:
var express = require('express'),
    wsio = require('websocket.io');

//create express app

var app = express();

//attach websocket server

var ws = wsio.attach(app);

//server your code

app.use(express.static('public'));

//listening on connections

ws.on('connection',function(socket){
    socket.on('message',function(msg){
        console.log('\033[96m got :\033[39m '+msg);
        socket.send('pong');
    })
})

//listen
app.listen(3000)

client
<!DOCTYPE html>
    <head>
        <title>Websocket echo test</title>
    </head>
    <body>
        <script>
            var lastMessage;
            window.onload = function(){
                var ws = new WebSocket('ws://localhost:3000');
                ws.onopen = function(){
                    //send first ping
                    ping();
                }
                ws.onmessage = function(ev){
                    console.log('got:'+ev.data);
                    //you got echo back.measure latency
                    document.getElementById('latency').innerHTML = new Date - lastMessage;
                    //ping again
                    ping()
                }
                function ping () {
                    //record the time
                    lastMessage = +new Date;
                    //send the message
                    ws.send('ping');
                }
            }
        </script>
        <h1>Websocket Echo</h1>
        <h2>Latency:<span id="latency"></span>ms</h2>    
    </body>
</html>

when I run,it can't run.I can't solve this problem,please help me,thanks!

WebSocket connection to 'ws://localhost:3000/' failed: Connection closed before receiving a handshake response

**Comment by jmwong** [comment]
This repo is for feedback on Docker Hub. Is there a chance you’re looking for the Nodejs GitHub repo? I’d suggest checking out stackoverflow.com too.
