### ISSUE TITLE
Admin unexpectedly removed from organization

### ISSUE THREAD

**Issue by ravenpride** [docker/hub-feedback#1637]
Dear support team,

Recently I contacted you to delete the user account "GriffinPlus" I added as I've not been able to convert it to an organization. The function in the "Settings" menu was simply not working. For about 3 weeks nothing happened. Meanwhile the conversion function was working and I converted the account "GriffinPlus" to an organization. My user account "ravenpride" became the administrator and everything was fine. At 19.08.2018 I got an e-mail notifying me that "ravenpride" was removed from the organization "GriffinPlus". At this time there were multiple repositories associated with the organization - all have been removed! When I tried to re-register the organization, I could not do that, as the name of the organization seems to be blocked now.

I already mailed the issue to support@docker.com, but there is no reaction, yet. Could you please have a look at the issue? There is something going really wrong...

Thank you very much!

**Comment by ai45242** [comment]
Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by ravenpride** [comment]
Issue has been solved. Thank you.
