### ISSUE TITLE
Opennms+Postgresql docker image

### ISSUE THREAD

**Issue by viki6** [docker/hub-feedback#1639]
Hi All,

I'm new to Docker world. I'm planning to combine both Opennms and Postgresql into a single image(since both are dependent to each other). We have gone through "https://hub.docker.com/r/opennms/horizon-core-web/~/dockerfile/" where we have option to install Opennms. But we need to append Postgresql entries as well to make our requirement done. 

We are using Centos 7.5 with 3.10.0-862.11.6.el7.x86_64.

**Comment by manishtomar** [comment]
This tracker is for issues with Docker Hub only. For general Docker questions, please try forums.docker.com or support.docker.com.
