### ISSUE TITLE
Unexpected error on every docker hub builds 

### ISSUE THREAD

**Issue by virgilekat** [docker/hub-feedback#1641]
Every build, on several repository, I'm running on docker hub are failing from few hours. 
There are no build log just a red header with "Unexpected error". 

I don't see any issue reported https://status.docker.com ? 

Is it something general ?

**Comment by NeilClayton** [comment]
Having same issue

**Comment by dis1** [comment]
Same here

**Comment by virgilekat** [comment]
there is an official ticket right now I guess it's related : https://status.docker.com/pages/incident/533c6539221ae15e3f000031/5bace09ada4e4f5cccc9dc19

**Comment by nandhini915** [comment]
Confirming an issue happening on Docker Builds, we're actively looking into it.
