### ISSUE TITLE
My automated builds appear to be stuck

### ISSUE THREAD

**Issue by terrywbrady** [docker/hub-feedback#1643]
## Problem description

My automated builds seem to be stuck. See https://hub.docker.com/r/terrywbrady/dspace/builds/

In an attempt to resolve this issue, I deleted my dockerhub repo terrywbrady/dspace and re-created the automated build.

![image](https://user-images.githubusercontent.com/1111057/46166028-065c9f00-c247-11e8-9231-05dad6af5be5.png)

**Comment by jmwong** [comment]
Hi @terrywbrady , we apologize for the inconvenience caused. There is an active incident with the autobuilds subsystem. Our engineers are working on resolving it. Please follow https://status.docker.com/ for updates.

**Comment by manishtomar** [comment]
That incident has since been resolved. The builds should be triggered now. Thanks for your patience.
