### ISSUE TITLE
Docker Hub builds broken

### ISSUE THREAD

**Issue by andyceo** [docker/hub-feedback#1644]
## Problem description
Our builds are stuck for 6 hours already. Cancelling not works. Before that, get quick builds failed with Unexpecred error message without any logs.

Can you help please?

**Comment by jmwong** [comment]
Hi @andyceo, we apologize for the inconvenience caused. There is an active incident with the autobuilds subsystem. Our engineers are working on resolving it. Please follow https://status.docker.com/ for updates.
