### ISSUE TITLE
Docker support page not working

### ISSUE THREAD

**Issue by jperry** [docker/hub-feedback#1647]
Anyone else seeing this by going to the docker support page?

![screen shot 2018-10-05 at 8 40 00 am](https://user-images.githubusercontent.com/410748/46535737-4e4c7900-c87a-11e8-81f9-359178883175.png)

I get there by going to this page:
![screen shot 2018-10-05 at 8 40 53 am](https://user-images.githubusercontent.com/410748/46535788-7045fb80-c87a-11e8-8c4f-d25612d85097.png)

**Comment by nandhini915** [comment]
Hi @jperry - via a quick check, we observed we were able to use the portal. We are investigating further and will get back to you soon.
