### ISSUE TITLE
Registration doesn't work

### ISSUE THREAD

**Issue by calebickler** [docker/hub-feedback#1648]
If I enter in my information, no errors in the inputs, then check all the boxes, the create account button is still gray, either there is feedback missing or the button is not becoming active.

**Comment by calebickler** [comment]
Looks like it was a problem with re-captcha service, I did it in incognito and it loaded. could be a cookie problem

**Comment by jmwong** [comment]
@calebickler sorry about the inconvenience. please let us know if you're still running into the issue.
