### ISSUE TITLE
Unauthorized login after trying to upgrade the account to organisation

### ISSUE THREAD

**Issue by ernesto-usal** [docker/hub-feedback#1649]
Days ago I tried to change my docker account to organization and, after that, I was logout from the application and lost the access to the main account.
I've already opened 2 tickets in https://success.docker.com/support (the first one in 26/09) and no answer, so I still can't access the account. The tickets references are 00059147 and 00059872
The username of the account is **aave**.
Thanks

**Comment by jmwong** [comment]
@ernesto-usal sorry for the inconvenience. an organization account cannot be logged into, and can only be managed by a user in the `owners` team. Can you see if https://success.docker.com/article/how-do-i-convert-my-docker-hub-cloud-user-account-into-an-organization-account helps?

**Comment by ernesto-usal** [comment]
The problem is that I have access to the organization created from the **aave** account from one of the owners account, but that organization is not the result of upgrade the **aave** account, so doesn't have the paid plan associated

**Comment by jmwong** [comment]
@ernesto-usal I see, sorry for the misunderstanding. Let me escalate the support ticket for you.
