### ISSUE TITLE
ENH: Auto-builds for all git tags

### ISSUE THREAD

**Issue by jakirkham** [docker/hub-feedback#165]
It's not obvious to me that this has been solved in the new version. However, the issue here is that in automated builds git tags are not automatically being converted to image tags. See this feature was brought up on the forum ( https://forums.docker.com/t/auto-builds-for-all-tags/682 ).

**Comment by dnephin** [comment]
+1 I would use this feature (for probably every image)

It looks like gliderlabs has found a way to handle it from a client https://hub.docker.com/r/gliderlabs/dockerhub-tag/

**Comment by Alonkad** [comment]
+1 asap

**Comment by drora** [comment]
+1 ASAP also here.. any ruff ETAs on this?

**Comment by avoinea** [comment]
+1

**Comment by vsimonian** [comment]
+1, but more like a +999

**Comment by amoussard** [comment]
+1 too !

**Comment by tyauvil** [comment]
+1

**Comment by mostlygeek** [comment]
+1

**Comment by jakirkham** [comment]
As this has been deployed and people are actively using this feature ( http://blog.docker.com/2015/11/upgraded-autobuild-docker-hub/ ), I am going to close this out. Thanks to Docker Hub for getting this in.

**Comment by ChristopherBiscardi** [comment]
thanks @jakirkham
