### ISSUE TITLE
Can not get JWT token

### ISSUE THREAD

**Issue by bingzhang** [docker/hub-feedback#1650]
## Problem description

our bash script used to successfully get JWT token from this endpoint , https://hub.docker.com/v2/users/login/ by using username and passwd.

but today, it seems it does not working. May someone help on it, please?

Regards.

**Comment by bingzhang** [comment]
working now. close.

**Comment by jmwong** [comment]
Hi @bingzhang, sorry for the inconvenience caused. Glad that it's resolved. However, please note that Docker Hub does not offer a supported public API as of now, and its implementation is subject to change without notice.
