### ISSUE TITLE
my docker container program no response

### ISSUE THREAD

**Issue by tokingHong** [docker/hub-feedback#1652]
## Problem description
my program bind 8080,but when I request or curl  ,there are no response
![1539592441 1](https://user-images.githubusercontent.com/39825820/46939192-3fdf3800-d098-11e8-908e-034d2adeab7c.jpg)

docker inspect ,it show running ,no exception.but it just no response ,

"State": {
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 76343,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2018-10-10T13:54:13.476361442Z",
            "FinishedAt": "2018-10-10T13:53:40.332023221Z"
        },

my dockerfile 
FROM scratch
xxxx

Can anyone solve this problem?

**Comment by nandhini915** [comment]
Hi @tokingHong 
If you are a community user using our Docker Engine product, Please go to https://forums.docker.com/ and verify if other members in the community have run into this issue, or post an issue back to the community.
If you are a user with a subscription to Docker Enterprise, you can go to https://success.docker.com/ and obtain help.
