### ISSUE TITLE
intermittent repo page failure

### ISSUE THREAD

**Issue by dkebler** [docker/hub-feedback#1653]
Strange.  Never had this issue before.  I search for some docker and then click on any of the results and all the repo pages give 404 errors.  Mon 10/15/18 10am pst.  Now a few minutes later it's fine.

**Comment by manishtomar** [comment]
https://status.docker.com/pages/incident/533c6539221ae15e3f000031/5bc4cb4711241e04b5a0c982

This has been fixed. Sorry for the inconvenience.
