### ISSUE TITLE
Tags on Docker Hub don't reflect results of docker pull

### ISSUE THREAD

**Issue by nampas** [docker/hub-feedback#1654]
## Problem description
I'm trying to pull in a php image - php:7.1.23-fpm. According to docker hub, that tag exists:
https://hub.docker.com/_/php/

However, I can't pull the image:
```
npastor $ docker pull library/php:7.1.23-fpm
Error response from daemon: manifest for php:7.1.23-fpm not found
```

Running the CLI tool on MacOS 10.13.6
Docker Version 18.06.1-ce-mac73

**Comment by manishtomar** [comment]
Strange. I am able to pull.
```
docker pull library/php:7.1.23-fpm
7.1.23-fpm: Pulling from library/php
f17d81b4b692: Downloading [===========>                                       ]  5.274MB/22.49MB
376d99d019dc: Download complete
80b3573727f0: Downloading [==>                                                ]  3.747MB/67.43MB
2c492579cd1f: Download complete
```
Can you try again?

**Comment by nampas** [comment]
Hey, yeah looks like things are good now.
It appears the job that actually pushes the tag didn't run until yesterday afternoon:
https://doi-janky.infosiftr.net/job/multiarch/job/amd64/job/php/111/

So I think this issue is really a dup of https://github.com/docker-library/php/issues/578

Thanks for taking a look @manishtomar !
