### ISSUE TITLE
 auto build docs errata: eliminate remaining references to github services

### ISSUE THREAD

**Issue by eedwards-sk** [docker/hub-feedback#1657]
## Problem description

as per the timeline posted in [github's announcement (back in april)](https://developer.github.com/changes/2018-04-25-github-services-deprecation/), as of october 1st, services can no longer be installed

therefore, it's now impossible to set up an automated build on docker hub using github

related: #1497

**Comment by jmwong** [comment]
@eedwards-sk sorry for the inconvenience caused. As a mitigation for the Github Services deprecation, we've moved to creating Github webhooks prior to 10/1. The docs were updated to reflect that: https://docs.docker.com/docker-hub/github/#auto-builds-and-limited-linked-github-accounts. If you're still seeing an issue it's might be a bug on our side. to help us diagnose, do you mind providing more detail on the error you're seeing and the exact steps you took?

**Comment by eedwards-sk** [comment]
@jmwong "configure automated builds" from https://docs.docker.com/docker-hub/builds/ still references services, the docs need an overhaul

**Comment by jmwong** [comment]
@eedwards-sk sorry for the oversight. we'll get the docs updated. thanks for letting us know!

**Comment by eedwards-sk** [comment]
I re-configured my repos to use the webhook instead of the service and it appears to be working.

As one additional data point, the docs currently still read as though "Public and Private" vs "Limited Access" is what determines whether or not you need to use webhooks.

From what I understand, we now need to use webhooks in all cases, but it's not clear if we still need to provide "Public and Private" access. It appears that even with "Public and Private" access, the webhooks don't get automatically created, so I'm not clear if there's any advantage to giving this access if you're only building from public repos.

If there's no advantage, I'd like to be able to change to just "limited" access, since I'm only building from public repos anyway.

Thanks :D
