### ISSUE TITLE
Unable to install mysql 5.7 and 5.6 in windows core 1709 image

### ISSUE THREAD

**Issue by avik-sengupta** [docker/hub-feedback#1658]
I have downloaded both official windows nano and core (version 17.09) images.

My docker file looks like:

FROM microsoft/windowsservercore:1709
ADD https://dev.mysql.com/get/Downloads/MySQL-5.7/mysql-5.7.22-winx64.zip mysql.zip

and similar for nano server.

Once the image build is successful, I am trying to run mysql on both the images using powershell.

I am able to install and run it successfully in nano server, however I am not getting any logs (on the console as well) for 1709 core server. Also, there are no error logs as well. 

After I execute "C:\MySQL\bin\mysqld.exe --initialize --console --explicit_defaults_for_timestamp ; " in powershell of 1709 core server, nothing happens and the pointer move to the next line.

The same happens for mysql 5.6 as well.

**Comment by nandhini915** [comment]
If you are a community user using our Docker Engine product, Please go to https://forums.docker.com/ and verify if other members in the community have run into this issue, or post an issue back to the community.
If you are a user with a subscription to Docker Enterprise, you can go to https://success.docker.com/ and obtain help.
