### ISSUE TITLE
Remove security scanning from our repository

### ISSUE THREAD

**Issue by lox** [docker/hub-feedback#1667]
We are still seeing security warnings on https://hub.docker.com/r/buildkite/agent/tags/ despite no scans being run for several months. 

These appear to be completely inaccurate and report versions that have changed substantially. How can we disable these?

See also https://github.com/buildkite/agent/issues/841

**Comment by manishtomar** [comment]
We are planning a UI upgrade in 1-2 months that will not have this problem. Thanks for your patience.

**Comment by lox** [comment]
So @manishtomar is the new UI that just landed that UI upgrade? The problem is still occurring.

**Comment by manishtomar** [comment]
@lox I don't see scans in new UI:
<img width="460" alt="image" src="https://user-images.githubusercontent.com/758529/50059772-08e0dd80-0140-11e9-884c-9dc3a2cd9610.png">

**Comment by lox** [comment]
Ah that's good, I am still seeing it in the admin though:

<img width="1182" alt="docker hub 2018-12-17 09-38-31" src="https://user-images.githubusercontent.com/15758/50059804-9fb0a700-01df-11e9-98ea-91a6ad6ad988.png">

We can live with that I guess, is there a plan to remove that too?

**Comment by manishtomar** [comment]
Hmm. That shouldn't happen. Let me get back to you on this.

**Comment by lox** [comment]
Still seeing this on the admin, but not on the client side.

**Comment by manishtomar** [comment]
@lox Sorry haven't gotten to it. I've created internal ticket and will get to it sometime after Jan 7th due to holidays.
