### ISSUE TITLE
Networking issue

### ISSUE THREAD

**Issue by kkalugerov** [docker/hub-feedback#1670]
Hello there, I have found a strange issue which is maybe tied to docker engine. My `docker.service` is running since two months and I found a strange behaviour which is expressed in losing a connection between docker containers which are running in the same bridge network. They just lost connection between each other and when I restarted my docker service everything start to work fine again.

For example I have one docker container which runs official `postgres` image and one more container which is connecting to this `postgres` container. For а time they worked perfectly fine but after a few days they just lost connection between each other. Then I tried to restart/run them again and again but without any effect to make proper connection between each other. To resolved the problem I had to restart my `docker.service`. 

My OS is Ubuntu 16.04 LTS x64 and I'm using Docker-CE.

**Comment by nandhini915** [comment]
If you are a community user using our Docker Engine product, Please go to https://forums.docker.com/ and verify if other members in the community have run into this issue, or post an issue back to the community.
If you are a user with a subscription to Docker Enterprise, you can go to https://success.docker.com/ and obtain help.
