### ISSUE TITLE
Cannot pull image from docker hub - http 503 status

### ISSUE THREAD

**Issue by kbuchsicf** [docker/hub-feedback#1673]
## Problem description

I noticed that for a period of 10-15 minutes, ending Oct 30 10:50 am CDT, I was unable to pull an image from docker hub. Mostly I tried to pull _vault:latest_, but alpine also failed. This happened on two different hosts: my laptop and an AWS server. I'm just reporting this in the event that you did not know about this or additional information here might help. I don't need a response and when you have what might be useful in this issue, you can close it. 

Here is the transcript of my attempts:

-------------
$ docker pull vault
Using default tag: latest
Warning: failed to get default registry endpoint from daemon (Error response from daemon: Bad response from Docker engine). Using system default: https://index.docker.io/v1/
Error response from daemon: Bad response from Docker engine

$ curl -iL https://index.docker.io/v1
HTTP/1.1 301 MOVED PERMANENTLY
Server: nginx/1.6.2
Date: Tue, 30 Oct 2018 15:38:52 GMT
Content-Type: text/html; charset=utf-8
Transfer-Encoding: chunked
X-Frame-Options: SAMEORIGIN
Location: https://index.docker.io/v1/
Strict-Transport-Security: max-age=31536000

HTTP/1.1 200 OK
Server: nginx/1.6.2
Date: Tue, 30 Oct 2018 15:38:53 GMT
Content-Type: text/html; charset=utf-8
Transfer-Encoding: chunked
X-Frame-Options: SAMEORIGIN
Strict-Transport-Security: max-age=31536000

Docker Registry API

... later ...

$ docker pull vault
Using default tag: latest
Error response from daemon: Get https://registry-1.docker.io/v2/library/vault/manifests/latest: received unexpected HTTP status: 503 Service Unavailable

$ curl -iL https://registry-1.docker.io/v2/library/vault/manifests/latest
HTTP/1.1 401 Unauthorized
Content-Type: application/json; charset=utf-8
Docker-Distribution-Api-Version: registry/2.0
Www-Authenticate: Bearer realm="https://auth.docker.io/token",service="registry.docker.io",scope="repository:library/vault:pull"
Date: Tue, 30 Oct 2018 15:41:31 GMT
Content-Length: 156
Strict-Transport-Security: max-age=31536000

{"errors":[{"code":"UNAUTHORIZED","message":"authentication required","detail":[{"Type":"repository","Class":"","Name":"library/vault","Action":"pull"}]}]}

$ docker search vault
NAME                                       DESCRIPTION                                     STARS               OFFICIAL            AUTOMATED
vault                                      Vault is a tool for securely accessing secre…   366                 [OK]
...

$ docker pull vault
Using default tag: latest
Error response from daemon: Get https://registry-1.docker.io/v2/library/vault/manifests/latest: received unexpected HTTP status: 503 Service Unavailable

$ docker pull alpine
Using default tag: latest
Error response from daemon: Get https://registry-1.docker.io/v2/library/alpine/manifests/latest: received unexpected HTTP status: 503 Service Unavailable

... and next it started working again ...
$ docker pull busybox
Using default tag: latest
latest: Pulling from library/busybox
90e01955edcd: Pull complete
Digest: sha256:2a03a6059f21e150ae84b0973863609494aad70f0a80eaeb64bddd8d92465812
Status: Downloaded newer image for busybox:latest

$ docker pull alpine
Using default tag: latest
latest: Pulling from library/alpine
Digest: sha256:621c2f39f8133acb8e64023a94dbdf0d5ca81896102b9e57c0dc184cadaf5528
Status: Image is up to date for alpine:latest

$ docker pull vault
Using default tag: latest
latest: Pulling from library/vault
...

**Comment by manishtomar** [comment]
We had an [incident](https://status.docker.com/pages/history/533c6539221ae15e3f000031) during that time and has since been resolved. We apologize for the inconvenience and are taking steps to avoid it.
