### ISSUE TITLE
Intermittent problem with slow Docker Hub downloads

### ISSUE THREAD

**Issue by BertCC** [docker/hub-feedback#1674]
## Problem description
Intermittent problem with slow Docker Hub downloads for the past few days.
User-Agent": "Docker-Client/18.06.0-ce (linux)

Pulling images from probably https://index.docker.io/v1/ based on the authentication.

Example of the download
ec37562cf8fa: Pull complete
c4ea5f051b6f: Pull complete
2bae1ad5d892: Downloading [============>                                      ]  2.637MB/10.7MB
eb35a070c734: Download complete
c2f7b3a40d11: Download complete
18572853bf32: Download complete
7e015c44723d: Download complete
c8c367712557: Download complete
85048b9a5b9c: Download complete
6cdf739c1817: Download complete
632b3a034732: Download complete
0dd4c1e6a8e3: Download complete
ec1eb1401d3a: Download complete
bdca2c95594c: Verifying Checksum

Not sure what other details will be useful for reporting this issue.

**Comment by BertCC** [comment]
After several minutes , 

ec37562cf8fa: Pull complete
c4ea5f051b6f: Pull complete
2bae1ad5d892: Downloading [================================>                  ]   6.86MB/10.7MB
eb35a070c734: Download complete
c2f7b3a40d11: Download complete
18572853bf32: Download complete
7e015c44723d: Download complete
c8c367712557: Download complete
85048b9a5b9c: Download complete
6cdf739c1817: Download complete
632b3a034732: Download complete
0dd4c1e6a8e3: Download complete
ec1eb1401d3a: Download complete
bdca2c95594c: Verifying Checksum

**Comment by manishtomar** [comment]
I suspect there is problem with you network. We've had cases like this in the past where problem turned out to be in user's networking environment. Could you try to download the blob using following script and let us know how it performs?
```
#!/bin/bash
# call it as <script> library/mysql blobs/sha256:2a72cbf407d67c7a7a76dd48e432091678e297140dce050ad5eccad918a9f8d6
repo=$1
url=$2
token=$(curl "https://auth.docker.io/token?service=registry.docker.io&scope=repository:$repo:pull" | jq -r .token)
curl -v https://registry-1.docker.io/v2/$repo/$url -H "Authorization: Bearer $token" -L > /dev/null
```

**Comment by BertCC** [comment]
Thanks @manishtomar for your script!  I seem to get an authentication issue right now and looking into that problem.  I am able to workaround right now by having a longer timeout for now.

**Comment by mkj28** [comment]
seeing same issues as @BertCC or in https://github.com/docker/hub-feedback/issues/1675

for @manishtomar 's script - it took ~1 second to pull the image: 
`100 21.4M  100 21.4M    0     0  12.4M      0  0:00:01  0:00:01 --:--:-- 20.1M`

The problem with slow pulls is intermittent and given I have seen it in different networks - seems to be on on the dockerhub side.

**Comment by manishtomar** [comment]
@mkj28 Could you paste the output of the script? Please redact auth token and blob sha if it is private blob. Moreover 20MB in 1 second is pretty good right?

**Comment by mkj28** [comment]
@manishtomar  I did whatever you pasted in https://github.com/docker/hub-feedback/issues/1674#issuecomment-435418940
as for 1 second - yes, it is fast, but intermittently it can take multiple seconds (see https://github.com/docker/hub-feedback/issues/1675#issuecomment-436324946)

**Comment by manishtomar** [comment]
Lets continue the conversation in #1674. Closing.

**Comment by BertCC** [comment]
OK @manishtomar : I can reproduce last night where time was anywhere from almost instantaneous on 1 machine.  But on another machine it was varying usually 11 to 14 seconds to do a docker pull, but went up to 60 seconds for 1 test run.

My logs are gone right now, but I can add to the other ticket once I reproduce again including the time.

**Comment by manishtomar** [comment]
@BertCC Please add it to #1675 itself. Thanks.
