### ISSUE TITLE
Forgot Password isn't working on Dockerhub site

### ISSUE THREAD

**Issue by kflavin** [docker/hub-feedback#1677]
Forgot password emails are not coming through.  Two people on our team have reported this.  We were able to get back in, but you might want to look at it.

Link is here:
https://id.docker.com/reset-password/?service=43f17c5f-9ba4-4f13-853d-9d0074e349a7

Doesn't appear to be going to spam, either.

**Comment by andyl** [comment]
I also have this problem.

**Comment by napsta32** [comment]
emails are working fine for me. however email link is broken. it redirects me to a blank page
