### ISSUE TITLE
private repo progress bar

### ISSUE THREAD

**Issue by kencochrane** [docker/hub-feedback#168]
I have a normal account with no subscriptions, so I should only have 1 free private repo. The progress bar doesn't show me much, it looks like this.

<img width="427" alt="screenshot 2015-08-04 10 56 34" src="https://cloud.githubusercontent.com/assets/261601/9063845/97c05e04-3a97-11e5-973c-96b71527921a.png">

It would be helpful if it told me how many private repos I had used, and how many I had free. Right now it looks like I have a bunch, but once I create on private repo, it fills right up. If we can't make it proportional, I think adding the numbers to the progress bar somewhere is a good start.

<img width="435" alt="screenshot 2015-08-04 10 59 57" src="https://cloud.githubusercontent.com/assets/261601/9063940/10adf0c4-3a98-11e5-8252-375aad81e796.png">

Considering I can't find out how many private repos I have used, and how many are free any where else, it would be good to add it there.

**Comment by rrarunan** [comment]
@jsouth ping.

**Comment by jsouth** [comment]
@kencochrane : Totally agree. Working an updated version of this progress bar that is actually useful (currently it does not provide the proper actions for users to easily view usage and/or upgrade). Will have a sample ready in the next day or so for us to review.

**Comment by kizbitz** [comment]
Duplicate: https://github.com/docker/hub-beta-feedback/issues/10

**Comment by kristiehoward** [comment]
Closed as this has been fixed in production.
