### ISSUE TITLE
Docker hosted redis losing data

### ISSUE THREAD

**Issue by tushar69** [docker/hub-feedback#1683]
I am running standalone redis using docker-hub image with volume for persistent storage(--appendonly yes),however after a while all the keys from the redis are disappearing.

starting the docker by following command :

`docker run  -p 6379:6379 -v redis-vol:/data -d redis redis-server --appendonly yes`

I haven't set the EXPIRE time for any of the keys. Can anyone please let me know what might be going wrong?

Thank you.

**Comment by pdkproitf** [comment]
I got the same problem. it seems the volume be clear and recreate every day. 
I saw the volume->createAt day has changed. 
Any though?

**Comment by thaJeztah** [comment]
Perhaps related; https://github.com/docker-library/redis/blob/7be79f51e29a009fefdc218c8479d340b8c4a5e1/5.0/Dockerfile#L65-L67

(https://github.com/docker-library/redis/issues/4#issuecomment-50780840)

Note,  however that this issue tracker is for feedback on Docker Hub itself, not the images that are hosted there. For feedback on / issues with the official images, refer to their readme on Docker Hub; 

https://hub.docker.com/_/redis

> **Where to file issues:**
> https://github.com/docker-library/redis/issues
