### ISSUE TITLE
Unable to login on docker hub - account deactivated?

### ISSUE THREAD

**Issue by hildeweerts** [docker/hub-feedback#1687]
Up until a month ago I have used my account on Docker Hub without a problem. But now I cannot login anymore on docker hub, my repositories seem to have been removed, and it looks like my account is deactivated. 

When I try to login on docker hub, it states "Incorrect authentication credentials", even though the exact same credentials do work on the CLI. Moreover, I cannot pull my docker images (which were public and worked fine up until a month ago) because according to the CLI they do not exist.

I would like to know why/how my account was deactivated to make sure that it does not happen again. In the best case scenario, I would also like to get access to my account again. I have already filed a support ticket almost a month ago but haven't gotten a response, despite asking for updates. Hopefully through this channel somebody can point me to a solution!

**Comment by negim** [comment]
I am also having the same issue. Don't know how my account has been deactivated without my persmissions.
