### ISSUE TITLE
Comments in repo details are in reverse chronological order

### ISSUE THREAD

**Issue by rrarunan** [docker/hub-feedback#169]
Would be better to have latest on top

**Comment by ChristopherBiscardi** [comment]
@rrarunan Does the API currently support this `ordering`?

**Comment by tedyoung** [comment]
This is a pretty big bug, it means that people won't see the latest comments unless they **know** that the ordering is oldest first, which is different from most other systems.

**Comment by tianon** [comment]
The "Comments" functionality appears to now be completely gone from Docker Hub, which renders this issue obsolete! :tada: :heart:
