### ISSUE TITLE
Intermittent: login attempt to https://registry.hub.docker.com/v2/ failed with status: 401 Unauthorized

### ISSUE THREAD

**Issue by mkj28** [docker/hub-feedback#1694]
## Problem description
Getting this intermittently today (Saturday November 24th):
`login attempt to https://registry.hub.docker.com/v2/ failed with status: 401 Unauthorized`

for example:
around 16:15:47 PST (4:15PM PST)
around 23:05:45 PST (11:05PM PST)

before/between/after these times - same login works perfectly fine

**Comment by manishtomar** [comment]
Duplicate of #1693.
