### ISSUE TITLE
cannot create automated build

### ISSUE THREAD

**Issue by xposix** [docker/hub-feedback#1699]
## Problem description
I cannot create a new automated build. I go through the process, fill the repository namespace and name, and visibility, add a short description, press 'Create' and it does nothing, the textfield in the button changes to 'creating...' briefly' but goes back to 'create' without giving any other feedback.

If I go to Chrome developers tool, I can see that the service returned the error below, which is obviously wrong. I also tried to give a two-letters name to the repository but the error is the same.

**detail: {vcs_repo_name: ["VCS repository name cannot exceed 50 chars"]}**

![image](https://user-images.githubusercontent.com/17210993/49031064-de36e100-f1a0-11e8-9d83-a36a6421673f.png)

Please see attached a screenshot of the issue.

Thanks for your help,
Ruben

**Comment by jmwong** [comment]
@xposix sorry for the inconvenience caused. thank you for the feedback. we will work on better surfacing the error message. In this case, the `VCS repository name` refers to the Github/Bitbucket repository that you're trying to recreate the automated build out of, not the name of the Docker Hub repo itself.

**Comment by xposix** [comment]
Oh yes, the error message actually said that but I didn’t read it right. But yes, an actual error message shown in the web Ui would be great.

Thanks,
Rubén Sancho

________________________________
