### ISSUE TITLE
Can't access support

### ISSUE THREAD

**Issue by xcq1** [docker/hub-feedback#1700]
I cannot access the suggested support page at https://support.docker.com from an account with an organization with a paid plan. I'm only getting the following error message:

>  Problem Logging In
> We can’t log you in because of the following error.
> 
> REGISTRATION_HANDLER_ERROR: Could not find a valid Contact based on Docker_Hub_User_Name or Docker_Id.

Searching for that I've only found an (unresolved?) reddit post from 6 months ago that faced the same problem: https://www.reddit.com/r/docker/comments/8juej7/totally_stuck_cannot_contact_docker_for_support/

Now there's apparently no other way to contact support which is why I'm posting this here. Or is there no support for paying customers?

**Comment by tnolet** [comment]
Same here. This company is just so broken.

**Comment by jmwong** [comment]
Hi @xcq1 @tnolet, I apologize for the inconvenience caused. Our team is looking into the issue. In order to help diagnose the issue, can you provide your Docker Hub usernames?

**Comment by xcq1** [comment]
Hi @jmwong 
My affected login username is "meisterplaninc"
Thanks for your help

**Comment by mmuth** [comment]
Also the same here... I used the form on the start page of support.docker.com/support to report the problem...but I never received a response.

**Comment by tnolet** [comment]
@jmwong My username for accessing the support page is "checkly"

**Comment by jmwong** [comment]
We're looking into the issue and will post an update shortly

**Comment by arrtchiu** [comment]
Also got the same issue. I created a new account just to try accessing support. Same problem. I can't wait until you fix (it's been 3 days since you said "looking into the issue"). How else can I get in contact with a human who might be able to actually fix something?

**Comment by Lvguangyuan** [comment]
@jmwong I also got the same issue, my username is "1302080104".

**Comment by gintautassulskus** [comment]
Hi guys, any progress on this? I have just subscribed to paid Docker and stuck with the very same issue.

**Comment by nandhini915** [comment]
We apologize for the delay in responding to this issue. As mentioned in the `hub-feedback` readme when creating a new issue, we recommend users submitting a ticket via https://success.docker.com/support (screenshot attached).  ![Screenshot](https://user-images.githubusercontent.com/2453622/42834230-695d1064-89ab-11e8-9e27-6ead616cfe92.png)

Apologies again for the delay, and hope this helps.

**Comment by giodegiorgi** [comment]
Is there any valid answer to that shitty support? we cannot push our images anymore even with a valid credit card.
