### ISSUE TITLE
Private Docker Hub Registry pulls super slow right now

### ISSUE THREAD

**Issue by tnolet** [docker/hub-feedback#1701]
Docker pull commands from my private repo have almost grind to a halt. Happened around 17:00 CET time. Up to that moment everything was fine. Pulls that normally takes 3 minutes are now at 31 minutes and not halfway done. To make things worse:
- https://status.docker.com/ status page says everything is A-OK
- https://support.docker.com/ throws an error...

This is just so sad.

**Comment by jmwong** [comment]
Hi @tnolet, sorry for the inconvenience caused. There is no active incident going on right now. However, we are actively investigating reports of pulls being slow. Would you mind adding some information in this ticket to help us diagnose: https://github.com/docker/hub-feedback/issues/1675#issuecomment-438036421? Thanks.

**Comment by manishtomar** [comment]
@tnolet Cloudflare has made some fixes. See https://github.com/docker/hub-feedback/issues/1675#issuecomment-442537485. Can you please let us know if is still slow? Also closing this in favor of #1675.

**Comment by tnolet** [comment]
@manishtomar this is still a huge issue. Pulls are quick for some hashes and then super slow for others.
