### ISSUE TITLE
Very slow pulls on production.cloudflare.docker.com

### ISSUE THREAD

**Issue by kursattuncel** [docker/hub-feedback#1702]
Hello,

We are experiencing very slow pulls on production.cloudflare.docker.com.

First download seems to be stalled when it hists any of the ip addresses resolved by production.cloudflare.docker.com.

 104.18.124.25, A 104.18.122.25, A 104.18.123.25, A 104.18.125.25, A 104.18.121.25 

Afterwards, it speeds up but first connection that hits the cloudflare servers seems to be stalled forever, very slow pull, causing the complete pull to fail.

How can I prevent dockerd hitting these servers?

I configured registry mirrors to use gcr.io servers but it still hits cloudflare machine.

Is this related with private repos?

**Comment by jmwong** [comment]
@kursattuncel sorry for the inconvenience caused. do you mind including more details in this ticket: https://github.com/docker/hub-feedback/issues/1675#issuecomment-438036421 to help us diagnose?

**Comment by kursattuncel** [comment]
here is my daemon.json

{
  "registry-mirrors": ["https://mirror.gcr.io"]
}


It starts with 100mbit/s connection, quickly starts to pull all the images:

723254a2c089: Pull complete 
39ec0e6c372c: Pull complete 
ba1542fb91f3: Pull complete 
c7195e642388: Pull complete 
95424deca6a2: Pull complete 
2d7d4b3a4ce2: Pull complete 
fbde41d4a8cc: Pull complete 
880120b92add: Downloading [=====>                                             ]  5.905MB/57.1MB
9a217c784089: Download complete 
d581543fe8e7: Verifying Checksum 
e5eff8940bb0: Download complete 
462d60a56b09: Download complete 
135fa6b9c139: Download complete 

And one of the downlads (randomly, not for a specific image), it starts to slow down, and the speed slows down to 3kb/s but it does get disconnect and the slow download stall for some time, it retries but again, it starts to download fast, gets to be stalled once again at some random part of the image. It waits for ever on this state.

By examining the tcpdump logs, we understand that, all cloudflare servers behave like this.
AmazonWS hosted servers are not affected by this problem.

It's very hard to give a proof or log on this issue, because we can not pin point the exact cloudflare server. We tried to pin point all cloudflare servers by defining them in /etc/hosts one by one, but at the end of the day, each server starts fast, then slows down.

**Comment by kursattuncel** [comment]
New update: I was able to complete the pull by switching all CloudFlare routes to another ISP (Vodafone Turkey.) Previous ISP was TURKCELL-SUPERONLINE.

Not only docker hub but all infrastructure using CloudFlare is problematic with TURKCELL SUPERONLINE.

**Comment by kursattuncel** [comment]
> @kursattuncel sorry for the inconvenience caused. do you mind including more details in this ticket: [#1675 (comment)](https://github.com/docker/hub-feedback/issues/1675#issuecomment-438036421) to help us diagnose?

I added comments to the issue you pointed out.

Thanks you.

**Comment by manishtomar** [comment]
Closing in favor of #1675
