### ISSUE TITLE
Login Bug: User name capitalization problem.

### ISSUE THREAD

**Issue by DavidSagan** [docker/hub-feedback#1704]
When creating a user account, the user name is stored as lower case. When logging in to Docker, the inputted user name is **not** converted to lower case and, if the user name is not inputted in lower case, this prevents the user from logging in with the error message "Incorrect authentication credentials." This is very aggravating if one does not realize what is happening.

**Comment by DavidSagan** [comment]
As far as I know this is still a problem but I have not tested.

**Comment by DavidSagan** [comment]
As far as I know this is still an open issue.

**Comment by ingshtrom** [comment]
@DavidSagan Have you tested this? I just tried to log in to hub.docker.com from the Web UI and it automatically converted all uppercase characters to lowercase.
