### ISSUE TITLE
Build details for automated builds are not directly available in Docker Hub's new web interface

### ISSUE THREAD

**Issue by erikmd** [docker/hub-feedback#1718]
Dear Docker Hub maintainers,

The new web interface of Docker Hub is very nice!
However it seems that for automated build repos, the detail (`Dockerfile` and logs) of a given build is not directly available anymore: only the `Dockerfile` of the *latest* build can be seen globally in the Dockerfile tab (`https://hub.docker.com/r/:user/:repo/dockerfile`), while the rows of the table in the Builds tab (`https://hub.docker.com/r/:user/:repo/builds`) are not "clickable" IINM.

Actually it seems this info is available (once signed-in) at URL
`https://cloud.docker.com/repository/docker/:user/:repo/timeline`.

Would it make sense and would it be feasible to add some hyperlink(s) to that URL from the Builds tab `https://hub.docker.com/r/:user/:repo/builds`, in order to browse more easily the corresponding `Dockerfile` and/or logs of such automated builds?

Thanks!

**Comment by raesene** [comment]
I'd +1 this . Also to add, I got some messages for failed builds today, and the links provided in the e-mails to look at the build logs no longer work, however the workaround described by @erikmd above works for me.

**Comment by skullydazed** [comment]
I'd also like to +1 this and add that for our open source project we want this information to be available publically. Transparency is very important to us and this change makes our project less transparent to our users.

**Comment by meticulous-dft** [comment]
Should be fixed.

**Comment by erikmd** [comment]
@meticulous-dft sorry I had not realized you had replied to this thread.

Actually the feature at stake still seems missing: as shown by the attached screenshot below, the `Builds` table in Docker Hub provides no *hyperlink to the Dockerfile+log detail of individual builds on Docker Cloud* (whether I am connected with my Docker ID or not). Could you thus reopen this issue?

Thanks for your time!

![docker_hub-feedback_issue-1718](https://user-images.githubusercontent.com/10367254/54306229-34515800-45c9-11e9-8049-111d9d2c7fcf.png)

**Comment by erikmd** [comment]
@meticulous-dft any update about this?
(namely, I think one should reopen this issue, but it seems I can't do it myself, there is no button "reopen")

**Comment by erikmd** [comment]
@meticulous-dft friendly ping

**Comment by meticulous-dft** [comment]
I see, this is my fault, should not close the ticket.

**Comment by erikmd** [comment]
@meticulous-dft Thanks!

To sum up, it would be great if one of the columns (say e.g., `Status`, cf. my [previous comment](https://github.com/docker/hub-feedback/issues/1718#issuecomment-472558893) screenshot) could be clicked to trigger an hyperlink to one of the following URLs (I don't know which one would be preferable):

- `https://cloud.docker.com/repository/registry-1.docker.io/:user/:repo/builds/:uuid`
- `https://cloud.docker.com/repository/docker/:user/:repo/builds/:uuid`

For example, this URL (that was referenced from [Docker Cloud's page for this repo](https://cloud.docker.com/repository/docker/coqorg/coq/) that I maintain) works:
- https://cloud.docker.com/repository/registry-1.docker.io/coqorg/coq/builds/8925ca90-92e7-43ca-bb02-5737a1550d25

Even if this feature request is just a matter of adding hyperlinks in Docker Hub's `Builds` pages such as https://hub.docker.com/r/coqorg/coq/builds, IMHO this would be a very important and nice feature to have!

**Comment by meticulous-dft** [comment]
You can link to the cloud build details if is the owner of the repository from hub side. This is the first step. We are doing a lot more to make the overall experience much better. So will close this for now.

**Comment by skullydazed** [comment]
It seems you can't link to the cloud build details as the repository owner because no one else can see it. For example I tried to share this URL: https://cloud.docker.com/u/skullydazed/repository/docker/skullydazed/qmk_compiler/builds/fc2e9d0e-e56f-4054-8af0-bd1c01496c08

What issue is the other work being track under?

**Comment by erikmd** [comment]
Good news, thanks a lot @meticulous-dft ! :+1:

(FYI I've just took the opportunity to open #1787 so the discussion could be continued there if need be)
