### ISSUE TITLE
Azure webhook links are rejected from docker hub

### ISSUE THREAD

**Issue by forki** [docker/hub-feedback#1719]
Azure webhook links are rejected from docker hub

![docker1](https://user-images.githubusercontent.com/57396/50090497-fda5b480-0208-11e9-855b-0f767cf10e1a.jpg)

![docker2](https://user-images.githubusercontent.com/57396/50090504-01d1d200-0209-11e9-9724-bb106e205edc.jpg)

**Comment by forki** [comment]
corresponding forum issue: https://forums.docker.com/t/azure-webhook-links-are-rejected-from-docker-hub/65217

**Comment by noirbizarre** [comment]
Exactly the same issue for MicroBadger webhooks URLs. I believe the URL validation is broken on this field

**Comment by meticulous-dft** [comment]
@noirbizarre Can you post the url format here, removing all sensitive info?

**Comment by Erikostberg** [comment]
I have the exact same problem. Any progress?

**Comment by meticulous-dft** [comment]
Yes, we should have a update end of this week or early next week to fix this.

**Comment by forki** [comment]
@meticulous-dft  do you really need to verify the url - maybe just accept everything!?

**Comment by meticulous-dft** [comment]
This should be fixed. Reopen the ticket if still not working.

**Comment by forki** [comment]
works for me. thank you!

Am Fr., 11. Jan. 2019 um 05:15 Uhr schrieb Ming He <notifications@github.com
