### ISSUE TITLE
When you finished creating an automated build, you get 404 instead of the build list

### ISSUE THREAD

**Issue by lorantonodi** [docker/hub-feedback#172]

**Comment by kencochrane** [comment]
@lorantonodi I just did it and it worked for me, can you give some more information so I can try and reproduce.

1. Which type of automated build: github or bitbucket?
2. Was it a public or private repository?
3. Did you have just one build config (branch, tag, etc), or were there more then one? if so, what was it.

**Comment by simonluijk** [comment]
I also saw this. It happens when you create an automated build under an organization that is not your main account. So you end up at /r/mainaccount/new-repo/ instead of /r/organization/new-repo/

**Comment by rrarunan** [comment]
@lorantonodi @simonluijk A fix is on the way.
