### ISSUE TITLE
double triggered buils after docker hub upgrade

### ISSUE THREAD

**Issue by davidkarlsen** [docker/hub-feedback#1720]
## Problem description
I have automated builds setup against github - after the recent docker hub upgrade these are triggered twice w/o me changing anything. What changed is the docker hub upgrade.

Example: The two triggers of the elastalert branch here just now: https://hub.docker.com/r/evryfs/kibana-docker/builds

**Comment by binhex** [comment]
see this issue #1499

**Comment by romainr** [comment]
We are seeing the same issue consistently https://hub.docker.com/repository/docker/gethue/hue/builds

**Comment by erikmd** [comment]
@romainr maybe this is related to this other (closed) issue? https://github.com/docker/hub-feedback/issues/1949

**Comment by romainr** [comment]
Thanks, but I only have circleci hook:

![image](https://user-images.githubusercontent.com/17945/96576469-15c44000-1287-11eb-9bfe-34148eacc455.png)

**Comment by erikmd** [comment]
@romainr OK :) but if you have *no* webhook in the upstream GitHub repo, how the Docker Hub automated build can be triggered?
