### ISSUE TITLE
Can't click on my repo name to see my repo

### ISSUE THREAD

**Issue by kaspergrubbe** [docker/hub-feedback#1721]
## Problem description

https://v.usetapes.com/CY33Toyem8

**Comment by kaspergrubbe** [comment]
Hi Ming,

No matter what I click I get sent back to https://hub.docker.com/ with a 302, this happens on any repo, create repo, repositories, and when I try to logout:

<img width="712" alt="screenie_1545244914_850647" src="https://user-images.githubusercontent.com/334273/50240843-2de68200-03c6-11e9-85a1-276b683b5eba.png">

<img width="560" alt="screenie_1545244958_382936" src="https://user-images.githubusercontent.com/334273/50240883-49518d00-03c6-11e9-80ce-c088979fb012.png">

I have disabled all my browser plugins and the behaviour is the same.

**Comment by kaspergrubbe** [comment]
I just tried clearing my cookies, and that helped, really strange...

**Comment by meticulous-dft** [comment]
Yeah, sorry, we been using cookie heavily and unfortunately looks like there is a conflict in this case. Thanks for this info, i will look into it.
