### ISSUE TITLE
Automated build post_push hook not working

### ISSUE THREAD

**Issue by nbrownuk** [docker/hub-feedback#1723]
## Problem description
When attempting to execute a `post_push` script for an automated build, I get the following error:

```
errors:
denied: requested access to the resource is denied
unauthorized: authentication required
post_push hook failed! (1)
```

I've seen similar issues here, but no advice is published about the fix. Can someone help? Thanks.

**Comment by jmwong** [comment]
@nbrownuk sorry for the inconvenience. can you provide more details about the error? which repo is the automated build on, and what does the `post_push` hook attempt to do? it looks like it's trying to push to a repo - is that a repo under the same namespace?

**Comment by nbrownuk** [comment]
@jmwong the repo is `nbrown/curl`, and the the script tags the built image and pushes to the same repo under the same namespace. Here's the script:

```
#!/bin/bash

set -e

# Parse image name for repo name and major tag version
tagStart=$(expr index "$IMAGE_NAME" :)
repoName=${IMAGE_NAME:0:tagStart-1}
ver=${IMAGE_NAME:tagStart}
majorVer=${ver%%.*}
minorVer=${ver%.*}

# Tag and push image with <major>
echo "Tagging and pushing" ${repoName}:${majorVer}
docker tag $IMAGE_NAME ${repoName}:${majorVer}
docker push ${repoName}:${majorVer}

# Tag and push image with <minor>
echo "Tagging and pushing" ${repoName}:${minorVer}
docker tag $IMAGE_NAME ${repoName}:${minorVer}
docker push ${repoName}:${minorVer}

# Tag and push image with latest
echo "Tagging and pushing" ${repoName}:latest
docker tag $IMAGE_NAME ${repoName}:latest
docker push ${repoName}:latest
```

**Comment by nbrownuk** [comment]
This now appears to be working.
