### ISSUE TITLE
Docker pulls failing due to randon x.509 failures

### ISSUE THREAD

**Issue by mallyvai** [docker/hub-feedback#1724]
## Problem description

Seeing random failures happen when we try and pull an image. Usually a couple of layers fail and this kills the image's pull. Example failure:

`
filesystem layer verification failed for digest sha256:aa18ad1a0d334d80981104c599fa8cef9264552a265b1197af11274beba767cf
[...]
error pulling image configuration: Get https://production.cloudflare.docker.com/registry-v2/docker/registry/v2/blobs/sha256/4d/4d9cdd30c445bf1d576d531d9154c8fd7510c13323349ffa475ee444957ba627/data?verify=1545337072-F%2B7LbB3qcWsZ%2B8PELFso9uoJKzk%3D: x509: certificate signed by unknown authority (possibly because of "x509: ECDSA verification failure" while trying to verify candidate authority certificate "COMODO ECC Domain Validation Secure Server CA 2")
`
Another one:
`
Get https://registry-1.docker.io/v2/library/ruby/manifests/2.3.4: Get https://auth.docker.io/token?account=gustosolano&scope=repository%3Alibrary%2Fruby%3Apull&service=registry.docker.io: x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "Amazon")
`

We had this happen a few weeks ago on a sustained, random basis as well. We don't have any evidence that it's because of something on our side. It would be great if DockerHub could investigate. Happy to provide more info if requested.

**Comment by jmwong** [comment]
@mallyvai sorry to hear that. our team is looking into this

**Comment by jmwong** [comment]
@mallyvai unfortunately we haven't been able to pinpoint an issue on our side or received similar reports of widespread issues from other users. do you mind double checking if your machine has the latest certs in its cert store? for auth.docker.io, you can verify it through these steps: https://aws.amazon.com/blogs/security/how-to-prepare-for-aws-move-to-its-own-certificate-authority/

**Comment by mallyvai** [comment]
@jmwong Thanks for taking a look. We'll try and investigate on our side again when this pops up.

One question - 

We have an internal Docker Registry (the free dockerized app - https://docs.docker.com/registry/ ) setup as a write-around cache My belief was that the internal docker registry should handle everything on the read path, and main Dockerhub should only handle stuff on the write path.

However, this seems to be failing on the read path, which is surprising. Any chance you can provide more color reading on how the `docker pull` is done with a registry in play? Happy to read any docs or source if pointed to it.

**Comment by jmwong** [comment]
HI @mallyvai, I believe validation of root CA is delegated to the root cert store on the host machine. The registry does not embed certificates.

These articles might help:
https://security.stackexchange.com/questions/105241/how-can-i-verify-that-a-root-certificate-is-authentic
https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2008-R2-and-2008/cc734054(v=ws.10)
http://manpages.ubuntu.com/manpages/trusty/man8/update-ca-certificates.8.html
