### ISSUE TITLE
Allow Docker tag-specific builds in new build process

### ISSUE THREAD

**Issue by Gordonei** [docker/hub-feedback#1725]
## Problem description
In the old Docker hub interface, it was possible to trigger Docker tag-specific builds by including a JSON blob with `{"docker_tag": "<tag name>"}` in the body of the `POST` to the build trigger.

It would be nice to have the same functionality in the new build interface.

## Use Case
Our use case is that we have cascading images in one Github repo, e.g. images A, B, C, where B has `FROM A` and C has `FROM B` in their Dockerfiles, and would like to have one corresponding Docker repo, where A, B, C are Docker tags on the same image.

We will use the Docker tag trigger along with `hooks/post_push` to trigger the build of the next image in the cascade, with a push on Github repo just triggering the base image.
    
Happy to resolve this, if you think that #1709 is similar enough.

**Comment by Gordonei** [comment]
I suppose an alternative that would support our use case is a way to control the build order of the build rules in a Docker repo, but that is maybe overly specific to our use case.

**Comment by meticulous-dft** [comment]
Hey @Gordonei 

  I think the functionality is still there. Can you check the `examples` in the build trigger section? We didn't remove any build trigger related functionalities.

![screen shot 2018-12-28 at 1 52 54 pm](https://user-images.githubusercontent.com/8132231/50529180-e936a700-0aa7-11e9-8586-f3dc6aee6997.png)

**Comment by Gordonei** [comment]
Thanks for the reply - I think the structure (and API) of the build triggers has changed in the new version of Docker hub.

I can see the triggers (with `registry.hub.docker.com` subdomain) on an old docker image, e.g.

![old_dockerhub_triggers](https://user-images.githubusercontent.com/1272984/50542302-1035cb80-0bc3-11e9-9c1d-78c172d3a667.png)

But not on a newer one (notice the new subdomain, `cloud.docker.com`):

![new_dockerhub_triggers](https://user-images.githubusercontent.com/1272984/50542304-17f57000-0bc3-11e9-9c25-470b4d2ea14a.png)

If I try send the `'{"docker_tag": "<tag name goes here>"}'` JSON body to the new style trigger, I get an 4XX HTTP error, and the desired build does not trigger, although any builds set to autobuild do.

**Comment by Gordonei** [comment]
A very minor gripe is that the new style URLs also don't incorporate the username and image into the path, instead opting for a UUID. I'm sure it makes some state retrieval easier, but it makes the URLs less readable.

**Comment by meticulous-dft** [comment]
Thanks for the clarification. I will take a look at 4xx Error.

**Comment by Gordonei** [comment]
Hey @meticulous-dft , I gave it a try again, as I'm back at work today, and it seems to be working (I'm now getting a `202` status code back):

```
$ curl -v -H "Content-Type: application/json" --data '{"docker_tag": "python"}' -X POST https://cloud.docker.com/api/build/v1/source/68095815-b057-4bb2-ac26-e2509ba1b9f7/trigger/<API SECRET>/call/

*   Trying 34.232.230.241...
* TCP_NODELAY set
* Connected to cloud.docker.com (34.232.230.241) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: CN=*.docker.com
*  start date: Jul 30 00:00:00 2018 GMT
*  expire date: Aug 30 12:00:00 2019 GMT
*  subjectAltName: host "cloud.docker.com" matched cert's "*.docker.com"
*  issuer: C=US; O=Amazon; OU=Server CA 1B; CN=Amazon
*  SSL certificate verify ok.
> POST /api/build/v1/source/68095815-b057-4bb2-ac26-e2509ba1b9f7/trigger/9758151c-06fb-4373-a5be-e5e2f7631552/call/ HTTP/1.1
> Host: cloud.docker.com
> User-Agent: curl/7.58.0
> Accept: */*
> Content-Type: application/json
> Content-Length: 25
> 
* upload completely sent off: 25 out of 25 bytes
< HTTP/1.1 202 ACCEPTED
< Date: Fri, 04 Jan 2019 10:17:48 GMT
< Content-Type: application/json
< Content-Length: 838
< X-RateLimit-Remaining: 59
< X-XSS-Protection: 1; mode=block
< X-Content-Type-Options: nosniff
< X-DockerCloud-Action-URI: /api/audit/v1/action/bff957b8-6f57-47dc-92a9-69cd05395874/
< Vary: Accept
< X-RateLimit-Limit: 60
< X-Frame-Options: deny
< X-RateLimit-Reset: 60
< Server: nginx
< Strict-Transport-Security: max-age=31536000
< 
* Connection #0 to host cloud.docker.com left intact
{"autotests": "OFF", "build_in_farm": true, "build_settings": ["/api/build/v1/setting/3f0f3ce8-29b3-4f47-8fd7-733cafd5674c/", "/api/build/v1/setting/e28289e5-e08b-4494-8d53-d7cf77f6e108/", "/api/build/v1/setting/2736ec11-622a-4a0f-b7ef-ac0ded9a2358/", "/api/build/v1/setting/d7ba9708-ecd1-4e08-9759-95fe5e5f0165/", "/api/build/v1/setting/d281ca6c-0f45-4bce-81c5-18342c8e1f54/", "/api/build/v1/setting/469c5284-d293-427a-a373-e36ff271c0a5/"], "channel": "Stable", "envvars": [{"key": "BUILD_SECRET", "value": "<API SECRET>"}], "image": "cityofcapetown/datascience", "owner": "cityofcapetown", "provider": "Github", "repo_links": true, "repository": "docker_datascience", "resource_uri": "/api/build/v1/source/68095815-b057-4bb2-ac26-e2509ba1b9f7/", "state": "Failed", "uuid": "68095815-b057-4bb2-ac26-e2509ba1b9f7"}
```

There is a `state` field in the response, that has the value `Failed`, but the build seems to be triggering on docker cloud fine.

So happy to close this, as we can now pursue our intended build flow.
