### ISSUE TITLE
What is the problem with mercurial?

### ISSUE THREAD

**Issue by zdm** [docker/hub-feedback#1726]
## Problem description
After migration to the docker cloud autobuild functionality for my mercurial is not working anymore.
In logs I see, that builder trying to clone mercurial repo using git.
What is the problem?
If you were removed mercurial support - you should inform your customers instead of keep silence.

**Comment by sarkis** [comment]
@zdm this has been resolved a month or so ago. Please reopen the ticket if you continue to experience issues.
