### ISSUE TITLE
ability to repository-link / trigger build from upstream images is lost

### ISSUE THREAD

**Issue by davidkarlsen** [docker/hub-feedback#1729]
## Problem description
Before the new hub there was a possibility to trigger builds based on upstream image change:
https://docs.docker.com/v17.12/docker-hub/builds/#repository-links - this is no longer possible:
https://docs.docker.com/docker-hub/builds/

**Comment by stayallive** [comment]
Dupe of #1717

**Comment by lshep** [comment]
Still an issue!
