### ISSUE TITLE
Sign In link on hub.docker.com is invisible at my resolution

### ISSUE THREAD

**Issue by lyoshenka** [docker/hub-feedback#1730]
## Problem description

Sign In link on hub.docker.com is invisible at my resolution. The link is white and the background behind the link is also white.

I have a 27" monitor with a 2560x1440 resolution. Here's what the top of hub.docker.com looks like for me:

![](https://i.imgur.com/HKXHzJO.png)

**Comment by meticulous-dft** [comment]
Thanks for the report. We will take a look.

**Comment by BasPH** [comment]
Same issue with LG 5K ultrawide monitor with 5120x2160 resolution.
