### ISSUE TITLE
Deployments Stuck In Pending

### ISSUE THREAD

**Issue by NeilClayton** [docker/hub-feedback#1734]
We are unable to deploy at all today. The builds are stuck in pending, we have checked our end and we have no issues, can you please check your side?

First thing this morning the builds where failing.

**Comment by manishtomar** [comment]
Sorry for the inconvenience. There was an [incident](https://status.docker.com/pages/incident/533c6539221ae15e3f000031/5c35cc493221a704b1d17943) which was fixed half an hour ago. Could you try triggering the builds again?

**Comment by NeilClayton** [comment]
Thanks for the reply. We have re-triggered a build 5 mins ago but it is still stuck in a pending state so the issue may not be fully cleared as of yet.

**Comment by tgmagalhaes** [comment]
Same here. I'm trying to build since 1:00 pm UTC, but none of them are starting.

**Comment by NeilClayton** [comment]
I have just had 2 successful deploys so the issue seems to have cleared now
