### ISSUE TITLE
Outdated Python SSL/TLS and/or Mercurial on the machines 

### ISSUE THREAD

**Issue by saaj** [docker/hub-feedback#1736]
## Problem description

As of 2018-12-01 Bitbucket [has disabled][1] support for TLSv1 and TLSv1.1 (obviously for strengthening security). 

> The Mercurial command line on UNIX-based systems may be affected; please check your version of Python (with “python -V”). Versions 2.7.9 and later are unaffected, and most versions earlier than 2.7.9 are affected. 

After then Docker Hub can no longer clone a mercurial repo from Bitbucket. The error in the build log looks like:

> Building in Docker Cloud's infrastructure...
abort: error: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:590)
please ensure the correct public key is added to the list of trusted keys for this repository and the remote branch exists. (255)

Mercurial has to be updated to at least 3.9 which [supports TLS v1.1+][2] (but it's better to use the latest version 4.8 as 3.9 was released in 2016).

[1]: https://bitbucket.org/blog/deprecating-tlsv1-tlsv1-1-2018-12-01
[2]: https://www.mercurial-scm.org/wiki/SecureConnections

**Comment by cowsrule** [comment]
Hi @saaj, we have released an update that should address this issue. Please let me know if you continue to see this error.
