### ISSUE TITLE
Build tags - invalid 'name' field

### ISSUE THREAD

**Issue by sjwarner-bp** [docker/hub-feedback#1739]
## Problem description
Trying to add multiple tags to a single build fails.

I add the tags `2,craft2` as described [here](https://docs.docker.com/docker-hub/builds/#create-multiple-docker-tags-from-a-single-build), but when I try to 'save' I get the following error:

```
Invalid 'name' field: Illegal Docker tag character ',' at position 2. Valid values are ^[A-Za-z0-9_][A-Za-z0-9_.-]{0,127}$
```

Seems to be incorrect tag validation.

From my UI, I see:

![screenshot from 2019-01-16 16-40-53](https://user-images.githubusercontent.com/30871823/51264204-e09e0600-19ad-11e9-8278-321dc8c09a24.png)

Any advice here?

**Comment by meticulous-dft** [comment]
We don't support this. I will update docs to make it clear. Please create 2 rules for this user case.
