### ISSUE TITLE
My image with 10M+ pulls has just gone (completely removed)

### ISSUE THREAD

**Issue by frol** [docker/hub-feedback#1741]
I have maintained `frolvlad/alpine-oraclejdk8` image ([the link](https://hub.docker.com/r/frolvlad/alpine-oraclejdk8/) now returns HTTP 404), which had 10M+ pulls. However, yesterday I started receiving messages (https://github.com/frol/docker-alpine-oraclejdk8/issues/37) that the image is no longer available on Docker Hub.

~~I believe, I can just recreate the image, though the stats will be zeroed, but I would like to know why this even happened.~~

I have also sent an e-mail to the support (the bot responded, that there is no chance to receive a response out of business hours).

~~P.S. Given the number of people depending on the image, I promised that I will re-create the image if there is no response within Monday.~~

EDIT: I cannot re-create the image as Docker Hub reports "Repository with this Name and Namespace already exists".

**Comment by frol** [comment]
I cannot re-create the image either:

![image](https://user-images.githubusercontent.com/304265/51524899-cb0a5f80-1e37-11e9-95ed-7e871277d8d5.png)

Bummer!

**Comment by NathanBland** [comment]
They probably got a take down request from Oracle.

**Comment by kylegordon** [comment]
@golubbe any comment?

**Comment by steve-todorov** [comment]
This broke our CI builds as well. @thaJeztah sorry to directly ping you, but I'm not sure who else to ping to get some sort of answers/help.

**Comment by steve-todorov** [comment]
@thaJeztah many thanks for your quick and extensive reply! Yeah, we were planning to base our images on `openjdk` at some point in February (due to Oracle's license changes). We just didn't expect this sudden change without any notice.

**Comment by andrewnicols** [comment]
Unfortunately that isn't a solution for us as we're trying to add functionality to Oracle database. We were extending the https://hub.docker.com/r/wnameless/oracle-xe-11g image (which is still present).
The official images are not available publicly (but are free) but we use these for our CI service (using disposable hosts).

**Comment by frol** [comment]
Just for the reference, I re-created [`frolvlad/alpine-java:jdk8-*`](https://github.com/Docker-Hub-frolvlad/docker-alpine-java/issues/37#issuecomment-460003346) image back then, but later Oracle changed the way how their binaries are distributed, so it was impossible to do it in Dockerfile and thus the image got stale in the whatever last state it was, so now it is deprecated.
