### ISSUE TITLE
Cannot create organization with error {"profile_url": ["Invalid value."]}

### ISSUE THREAD

**Issue by ovegug** [docker/hub-feedback#1744]
## Problem description
I'm trying to create an organization here https://cloud.docker.com/orgs, but facing `400 Bad request` with this body:

```json
{
    "profile_url":[
        "Invalid value."
    ]
}
```
I tried to fill profile URL with "qweqweqweqweqew", but it still answer same error.

**Comment by ovegug** [comment]
If I'm trying to use already existent account name then I'm facing this error:

```
{
    "orgname":[
        "An organization with the same name already exists."
    ],
    "profile_url":[
        "Invalid value."
    ]
}
```

**Comment by meticulous-dft** [comment]
Hey @ovegug Just leave the profile url empty. We will add better indication on the UI for required / optional fields.
