### ISSUE TITLE
internet explorer support

### ISSUE THREAD

**Issue by BillMills** [docker/hub-feedback#1745]
## Problem description

*x-posted from @franklouwers at https://github.com/docker-training/exercises/issues/597*

Hi,

Sorry to open this here, but I don't know what the best place would be to report this: It seems students using Internet Explorer have issues seeing part of the Docker Hub.

For instance in Fundamentals, when they have to push an image to the hub, we tell them to browse to the hub, make sure they are logged in, then navigate to Repositories in the blue top menu bar.

When doing to in IE, it seems to throw a blank page. Can't verify, as I am using a Mac myself.

Could you pass it on to the Docker Hub web-team? Thanks!

**Comment by meticulous-dft** [comment]
Hi, we don't support IE since it is really old. Please use Edge or Chrome. We will add a banner to the website to let user know if detect IE.
