### ISSUE TITLE
Markdown is not rendering correctly on repository pages (hub.docker.com)

### ISSUE THREAD

**Issue by zfields** [docker/hub-feedback#1747]
## Problem description

Specifically, angle bracketed ("<") code inside a "code block" ("```bash") is not rendering properly.

For example, the following will not render on hub.docker.com...

```bash
script.sh --parameter1 <your parameter>
```
This used to work recently (maybe a month ago).

**Comment by zimme** [comment]
Having the same problem here, https://hub.docker.com/r/zimme/rar2fs
```sh
docker run \
  -d \
  --init \
  --name rar2fs \
  --cap-add SYS_ADMIN \
  --device /dev/fuse \
  -v <path/to/rar/files>:/source \
  -v <path/to/empty/folder>:/destination \
  zimme/rar2fs
```
is rendered as
```sh
docker run \
  -d \
  --init \
  --name rar2fs \
  --cap-add SYS_ADMIN \
  --device /dev/fuse \
  -v :/source \
  -v :/destination \
  zimme/rar2fs
```

Maybe it's related to this issue? #1737

**Comment by meticulous-dft** [comment]
Just fixed this.

**Comment by pedroferreira84** [comment]
Same problem here! Still facing problems in the following images:

https://hub.docker.com/r/pegi3s/bedtools/
https://hub.docker.com/r/pegi3s/sapp/
https://hub.docker.com/r/pegi3s/soapdenovo2/
https://hub.docker.com/r/pegi3s/utilities/

Pedro.

**Comment by pedroferreira84** [comment]
Any developments on this problem?
