### ISSUE TITLE
Build page showing builds on other containers

### ISSUE THREAD

**Issue by TJNII** [docker/hub-feedback#1749]
## Problem description
The builds page at https://cloud.docker.com/repository/docker/[user]/[repo]/builds is showing builds from other projects.

The following screenshot shows the builds page with builds going back two years.  This repo is just under a month old.

![builds page example](http://tjnii.com/~tom/BugReports/DockerHub.20190203/Builds_page.png)

Here is an example of a build that shows me as the owner, but the output of a completely unrelated build:

![unrelated build example: page top](http://tjnii.com/~tom/BugReports/DockerHub.20190203/Build_top.png)
![unrelated build example: page bottom](http://tjnii.com/~tom/BugReports/DockerHub.20190203/Build_bottom.png)

This is exposing build output to unrelated users.  The image here is also public, I didn't go through each build to see if it was exposing private builds.

[EDIT: Fix image markdown]

**Comment by TJNII** [comment]
Timeline is also showing unrelated builds that predate the repo:

![Timeline Page](http://tjnii.com/~tom/BugReports/DockerHub.20190203/Timeline.png)

**Comment by nandhini915** [comment]
Thanks for letting us know @TJNII -- we will look into this and work on fixing the visibility asap.

**Comment by JPZ13** [comment]
Hi @TJNII. I'm working on fixing this issue. Was `thelab/s2i-python` an image that you were looking at on Docker Hub previously, or is it an entirely unrelated image?

**Comment by TJNII** [comment]
@JPZ13 Entirely unrelated

**Comment by JPZ13** [comment]
@TJNII We made some changes to our backend that look like they fixed the issue. Can you confirm?

**Comment by TJNII** [comment]
:+1: Looks good after a refresh.
