### ISSUE TITLE
Unable to `docker login` when password created in hub.docker.com contains underscore

### ISSUE THREAD

**Issue by julien-lecomte** [docker/hub-feedback#1751]
## Problem description
Website allows creation of a password using an underscore. When a password contains an underscore, we can login on the website, but `docker login` will always fail.

Previous password that would never allow me to login via CLI: docker_2JCMNAj3s3MdDqeP4cLABdsdEDCEi2EmnmBWQAHp

~~~
$ docker login -u julienlecomte
Password: 
Error response from daemon: Get https://registry-1.docker.io/v2/: unauthorized: incorrect username or password
~~~

After password change to docker2JCMNAj3s3MdDqeP4cLABdsdEDCEi2EmnmBWQAHp (removal of underscore), the following worked:
~~~
$ docker login -u julienlecomte
Password: 
WARNING! Your password will be stored unencrypted in /home/julien/.docker/config.json.
Configure a credential helper to remove this warning. See
https://docs.docker.com/engine/reference/commandline/login/#credentials-store

Login Succeeded
~~~

_nb: passwords pasted above have been changed and are not used anywhere else_

**Comment by meticulous-dft** [comment]
Thanks for reporting. Will look into it.

**Comment by antusus** [comment]
It is not only the underscores that makes logging in fails. My password:
`Q{UQE*$f6@}+6c.P%HJu}83V7KWB38evs4n^9hw7`
I've changed it already and I'm not using characters and it works.

**Comment by julien-lecomte** [comment]
Nope.
