### ISSUE TITLE
Docker Hub not using manifest file to list supported architectures

### ISSUE THREAD

**Issue by rodriguezst** [docker/hub-feedback#1754]
When **compiling ARM containers on x86_64 machines** (Docker Hub automated builds), the resulting images are marked as x86_64 architecture. This is expected because the images are being compiled on that architecture.

The problem is that when I create a "latest" tag as a **docker manifest linking to ARM and x86_64** builds with architecture and os information, **Docker Hub does not list my repository if I filter by ARM architecture**. However, the manifest is working properly when pulling images from an ARM system giving the right QEMU built image.

![image](https://user-images.githubusercontent.com/2828844/52628352-c9244100-2eb7-11e9-87c3-f0eed432fae3.png) Docker Hub detects the image as x86_64 only.

How can I tell Docker Hub to read my 'latest' tag manifest to look for the supported architectures?
I would expect Docker Hub to give higher priority to the architectures declared in the manifest than the architectures that the images were built on.

```json
$ docker manifest inspect rodriguezst/telethon_downloader:latest
{
   "schemaVersion": 2,
   "mediaType": "application/vnd.docker.distribution.manifest.list.v2+json",
   "manifests": [
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 3037,
         "digest": "sha256:cff3564e9d68785bdada78eb0cbf9687b85d54e862a187fda2fcc169f14d94a8",
         "platform": {
            "architecture": "arm",
            "os": "linux"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 1778,
         "digest": "sha256:800c9039693d0714d00e22b7995e7604ba98dde00efa28c6deaff951d5961fa2",
         "platform": {
            "architecture": "amd64",
            "os": "linux"
         }
      }
   ]
}
```

**Comment by manishtomar** [comment]
Ack. We've created internal ticket to handle this. It looks like this is happening with your repo only. Need to dig more.

**Comment by moikot** [comment]
The same for me 😿 
Output from `docker run --rm weshigbee/manifest-tool inspect moikot/beacon`
```shell
Name:   moikot/beacon (Type: application/vnd.docker.distribution.manifest.list.v2+json)
Digest: sha256:1b20df7fe74aa0878229ed6a5645cdc71a00d205c3368ec2fdcf4f362210c659
 * Contains 3 manifest references:
1    Mfst Type: application/vnd.docker.distribution.manifest.v2+json
1       Digest: sha256:2686301d6d1ceaa631e8b646dc38c01eb09e3acce5a384a46385ec04e922e465
1  Mfst Length: 738
1     Platform:
1           -      OS: linux
1           -    Arch: amd64
1           - Variant: 
1           - Feature: 
1     # Layers: 2
         layer 1: digest = sha256:4a5569fcf8963b839382ba9c0eb38157172b1956b7fd1bb6a1f30b4badf0cc29
         layer 2: digest = sha256:57284436dbd3b4bc863efccb7b7f85ad6c49923d84f84b8b34f806484ae47f7a

2    Mfst Type: application/vnd.docker.distribution.manifest.v2+json
2       Digest: sha256:474f94ec7204077a46ca21e6f24edeaff993c9b8cd279a9d46665afd7781bbdf
2  Mfst Length: 738
2     Platform:
2           -      OS: linux
2           -    Arch: arm
2           - Variant: v7
2           - Feature: 
2     # Layers: 2
         layer 1: digest = sha256:4a5569fcf8963b839382ba9c0eb38157172b1956b7fd1bb6a1f30b4badf0cc29
         layer 2: digest = sha256:6e77b322bc4839a6e9d6a928bcda67d4b7d9c9ac536766e4535e680ce0f8a15c

3    Mfst Type: application/vnd.docker.distribution.manifest.v2+json
3       Digest: sha256:2ae29690e7d87862f7ffaf6977c68d499002ab580e9a2915b67035d03d9257b8
3  Mfst Length: 738
3     Platform:
3           -      OS: linux
3           -    Arch: arm64
3           - Variant: v8
3           - Feature: 
3     # Layers: 2
         layer 1: digest = sha256:4a5569fcf8963b839382ba9c0eb38157172b1956b7fd1bb6a1f30b4badf0cc29
         layer 2: digest = sha256:148ea9073676a26c6139491f65537073f6ea05d82abab9203a24c9567985e139
```
From Docker Hub search results
![image](https://user-images.githubusercontent.com/38087929/54878283-cdcf0400-4e2a-11e9-803b-6b80b4e930dc.png)

The same in tooltips on Tags page for that image:
![image](https://user-images.githubusercontent.com/38087929/54878315-2e5e4100-4e2b-11e9-98ce-36ea47e72c0e.png)

It is super confusing, could you please prioritize?
