### ISSUE TITLE
Suggestion to improve search to detect tags

### ISSUE THREAD

**Issue by franklouwers** [docker/hub-feedback#1755]
## Problem description
I was helping somebody out in the community Slack, and noticed that the search on the Hub's wegpages, don't seem to detect image:tag formats. If the search could be improved to detect that syntax and directly point to the correct page, that would be great.

eg: search for `php:7.2.1-apache`,

The First link is the httpd image (because of the 'apache' in the name), but I feel the search engine should have detected the syntax and pointed to the php page first.

**Comment by ikunat33** [comment]
Hi and thanks for this suggestion Frank. I would suggest that further organization would be helpful. PHP has thousands of tags and finding them could be much easier than a manual search say, for example, when searching for apache:

On the Docker PHP web page I click "view available tags".
I see Tags (2493) which seem be ordered by latest update
on page 5 I run into my first few instances of apache.
on page 6 I run into a few more.
on page 11 another one.

How many more are there I do not know but this is taking time and my eyesight is not great, or I am in a hurry and I may overlook one that would interest me.

It would be nice to have a search box at the top of the page where a person might type in apache, Ubuntu, Alpine, ZTS, or Cli. Then all the relevant tags could be displayed.

all tags with apache would be displayed most recently updated first

Perhaps a list of the most commonly appearing sub strings within those tags available somewhere nearby for those people unsure what they might be looking for would help further; such as Ubuntu, Alpine, etc...

The last may even be considered enticing for newcomers.

**Comment by franklouwers** [comment]
Still an issue imho
