### ISSUE TITLE
pushes to dockerhub.com account (paid/private) failing

### ISSUE THREAD

**Issue by apoland** [docker/hub-feedback#1757]
## Problem description
About 45 minutes ago we seem to have lost the ability to push to dockerhub.  All pushes from CircleCI are failing with one of two errors:

unknown blob

OR

error parsing HTTP 404 response body: invalid character 'p' after top-level value: "404 page not found\n"

The symptoms looks identical to this service issue that happened in November:
https://github.com/docker/hub-feedback/issues/1693

**Comment by cowsrule** [comment]
We are looking into it, thank you for the report.

**Comment by h314to** [comment]
We are also having the same issue pushing from CircleCI:

```
error parsing HTTP 404 response body: invalid character 'p' after top-level value: "404 page not found\n"
```

**Comment by thelamer** [comment]
Pulling and pushing on our end at Linuxserver.io: 

```
error pulling image configuration: unknown blob
unknown blob
invalid character 'p' after top-level value: "404 page not found
```
This issue is identical to an outage a few months ago. 

Also would it be possible to get updates here: 
https://status.docker.com/
Status.io is nice and all, but it seems like more basic health checks that full loop would be more useful than api response rate pings.

**Comment by cowsrule** [comment]
This issue has been resolved.

**Comment by thelamer** [comment]
@cowsrule all better here builds are flowing again. 
If you want to collab on some full loop monitoring logic let me know, can be something community supported as long as we have something to ping into outside of Github Issues.

**Comment by cowsrule** [comment]
Feel free to send me an email - grant.watters@.
