### ISSUE TITLE
Random 500 errors

### ISSUE THREAD

**Issue by thelamer** [docker/hub-feedback#1761]
We cannot get builds through currently at LSIO. 

everything is failing with 500, I can confirm this locally with only a couple pushes : 

```
478d5c9246ad: Layer already exists
d46f9f76f72f: Retrying in 5 seconds
d46f9f76f72f: Retrying in 4 seconds
d46f9f76f72f: Retrying in 3 seconds
0ef7813a3715: Pushed
d46f9f76f72f: Retrying in 2 seconds
d46f9f76f72f: Retrying in 1 second
d46f9f76f72f: Pushed
received unexpected HTTP status: 500 Internal Server Error
```

**Comment by dcorto-eu** [comment]
I confirm we are facing same issues pushing images from AWS at Oregon region

**Comment by mustafaakin** [comment]
Can confirm, 12 out of 100 pushes failed to Hub.

**Comment by bolencki13** [comment]
Facing same issues pushing images from Gitlab CI/CD online version.

**Comment by cowsrule** [comment]
We are aware of the issue and are rolling out a fix currently.

https://status.docker.com/

**Comment by thelamer** [comment]
@cowsrule we are starting to get successful pushes on our end . 
Thank you for looking into this .

**Comment by thelamer** [comment]
As this incident is fully resolved I am closing this case.
