### ISSUE TITLE
Docker ID can't log in at docker hub website.

### ISSUE THREAD

**Issue by unihon** [docker/hub-feedback#1762]
## Problem description

Feedback the following when I log in.

_Account has multiple email addresses. Please contact customer support to fix it._

![image](https://user-images.githubusercontent.com/42078581/54071564-4077a580-42a9-11e9-94fd-b2d591a9e475.png)

**Comment by nandhini915** [comment]
Please go to https://success.docker.com/support and open a ticket so our support team can take a look. If there is a case number, let us know and we can help.

**Comment by unihon** [comment]
> Please go to https://success.docker.com/support and open a ticket so our support team can take a look. If there is a case number, let us know and we can help.

Thanks 😁

**Comment by Snazzie** [comment]
I opened a ticket 2 months ago and have yet to receive any help. ive also tweeted at you guys and no response..
