### ISSUE TITLE
Stuck build for https://cloud.docker.com/u/xwiki/repository/registry-1.docker.io/xwiki/xwiki-jenkins-slave

### ISSUE THREAD

**Issue by vmassol** [docker/hub-feedback#1769]
Hi there.

Our build at https://cloud.docker.com/u/xwiki/repository/registry-1.docker.io/xwiki/xwiki-jenkins-slave is stuck. It finished building but the status was not updated and the image not deployed. After waiting a long time (a lot more than usual), I tried to cancel it and now it's stuck while cancelling https://cloud.docker.com/u/xwiki/repository/registry-1.docker.io/xwiki/xwiki-jenkins-slave/builds/73af16ad-982e-4bf1-b79e-e2bf9d83e30f

What can I do?

Thanks a lot

**Comment by cowsrule** [comment]
We are actively investigating a slowdown in our Automated Builds and will update https://status.docker.com/ once it is resolved.

**Comment by vmassol** [comment]
Thanks for the quick answer! I should have checked https://status.docker.com/ before creating the issue, sorry.
