### ISSUE TITLE
Mercurial automated builds failing with git error message

### ISSUE THREAD

**Issue by javh** [docker/hub-feedback#1770]
Automated builds from our mercurial repository are failing with the following error:

```
Building in Docker Cloud's infrastructure...
abort: repository git@bitbucket.org:kleinstein/immcantation.git not found!
please ensure the correct public key is added to the list of trusted keys for this repository and the remote branch exists. (255)
```

It appears to be expecting a git repository? We have made no changes to the docker hub project or repository (aside from commits) between now and the last successful build (2/1/2019).  However, the build timeline seems to have been deleted.  Also, docker hub is seeing the correct (most recent) changeset when attempting to build. (This was `287fb82d` when I triggered the build, which it shows correctly.)

The hub project is here:
https://cloud.docker.com/u/kleinstein/repository/docker/kleinstein/immcantation

The target repository for automated builds is here:
https://bitbucket.org/kleinstein/immcantation

(The Dockerfiles are within subdirectories of `docker`.)

I made a new automatic build project off the same repository and got the same error ([here](https://cloud.docker.com/repository/docker/javh/test)). (When bitbucket changed their security settings at the end of last year we had to do this to get the hub repo to build. But, it didn't help in this case.)

**Comment by olivergrahl** [comment]
Same here. Cannot build anything any more. :-(

**Comment by sarkis** [comment]
This has been resolved, please re-open if you continue to eperience issues.
