### ISSUE TITLE
Cannot delete auto-build rule: "Build setting with this Build source, Name and Source name already exists"

### ISSUE THREAD

**Issue by edsiper** [docker/hub-feedback#1776]
## Problem description

I am trying to edit the new auto-build rules that we are going to use, but after clicking on 'Save' some rules disappear or are not listed, this is the interface where I am facing the problem:

    https://cloud.docker.com/u/fluent/repository/docker/fluent/fluent-bit/builds/edit

Our image is fluent/fluent-bit which have as source repository https://github.com/fluent/fluent-bit-docker-image . Trying to add a specific rule it fails behind the scenes, inspecting the network traffic upon 'Save' I see the following error:

```
{"error": "[u'Build setting with this Build source, Name and Source name already exists.']"}
```
If you see the following screenshot you can see that rule is not listed to be deleted/replaced:

![sc](https://user-images.githubusercontent.com/369718/54857376-a827ea80-4cc4-11e9-91b2-1faf2b642a90.png)

this is happening for one of the rules (Branch: 1.0, Tag: latest). This is a blocker since we cannot configure that rule for new releases.

## Docker Hub Account Issues

docker hub repo: fluent/fluent-bit

**Comment by meticulous-dft** [comment]
Hi, what is the rule you are trying to add, can you share with me a screenshot of the build rules which have error?

Also dose delete these rules work?

**Comment by edsiper** [comment]
@meticulous-dft 

this is the rule I am trying to add (last row):

![1](https://user-images.githubusercontent.com/369718/54858474-8893c080-4cca-11e9-804a-e24828feeb9f.png)

after clicking Save:

![2](https://user-images.githubusercontent.com/369718/54858488-95181900-4cca-11e9-9a52-be2ea8c73452.png)

the rule is not generated, the error is only visible running Inspec in Google Chrome:

![3](https://user-images.githubusercontent.com/369718/54858515-cb559880-4cca-11e9-9f1e-133f37d58176.png)

**Comment by edsiper** [comment]
note: the problematic original rule cannot be deleted since is not displayed in the UI

**Comment by meticulous-dft** [comment]
Thanks for the details. I identified a possible cause and deployed a fix. Please try again and let me know if the issue is still there.

**Comment by edsiper** [comment]
@meticulous-dft thanks! that fixed the problem, I was able now to trigger the build.
