### ISSUE TITLE
Autobuild is not running. Webhook API returns HTTP 500 error code

### ISSUE THREAD

**Issue by Erikvl87** [docker/hub-feedback#1778]
## Problem description
Autobuilds in Docker Hub are not triggered. I have configuration for a Github repository that worked yesterday but broke down today. I have changed some of the build rules, to be specific the regular expressions, but this seem to be unrelated as the API returns the following:

**Headers:**
```
Content-Length: 72
Content-Type: application/json
Date: Fri, 29 Mar 2019 14:33:18 GMT
Server: nginx
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-RateLimit-Limit: 60
X-RateLimit-Remaining: 58
X-RateLimit-Reset: 2
X-XSS-Protection: 1; mode=block
```
**Body:**
`{"error": "Our service is temporarily unavailable. We'll be back soon!"}`

I've already tried to re-add the Webhook but that didn't solve the issue. I can't find anything about any degraded service or known issue related to this. Is this a known issue? I have this problem for some hours now.

**Comment by meticulous-dft** [comment]
Hey @Erikvl87 Can you provide more details on the failed build? e.g. Screenshot, rules, settings etc. If they are not public, can you send the info to ming.he@docker.com, this would help a lot to pinpoint the problem. Thanks.

**Comment by Erikvl87** [comment]
Hi @meticulous-dft! Thank you for your time!

The build is not even started since the Webhook from Github is not reaching Docker properly. So there is no detailed log of a build I can give to you.

![image](https://user-images.githubusercontent.com/1898162/55245546-a5d50b80-5243-11e9-855a-f5bfbf666614.png)

Public Docker repository: https://hub.docker.com/r/erikvl87/languagetool
Github repository: https://github.com/Erikvl87/docker-languagetool/

Build rules:
```
Tag	/^v[0-9]+\.[0-9]+\.[0-9]+(?<!-)$/	latest	Dockerfile	/
Tag	/^v([0-9]+\.[0-9]+\.[0-9]+(?:-.*)?)$/	{\1}	Dockerfile	/
```

Is there any more information I could share with you that could help?

**Comment by Erikvl87** [comment]
Alright, I've found out that the regular expression for `latest` (`/^v[0-9]+\.[0-9]+\.[0-9]+(?<!-)$/`) was the cause of my issues. The expression was matching a version and excluding any `-` character, but since I've also matched the ending (using the `$` sign) that is unnecessary and I could rewrite this to a simpler expression: `/^v[0-9]+\.[0-9]+\.[0-9]+$/`.

I do feel that the error that the API returns is incorrect. The [expression is valid](https://regex101.com/r/FeHHAz/2) and the API seem to suggest that the service is down. It should have pointed me to the direction of the regular expression.

**Comment by meticulous-dft** [comment]
Thanks for the info. I will take a look to have useful response message.

**Comment by ulope** [comment]
We just ran into the same problem. Please document which regex syntax features are supported.
Our regex was: `/^v\d+\.\d+\.\d+((:?\-|\.)?(rc|dev)\d*)?$/`

Apparently backslash character classes are not supported. Replacing `\d` with the equivalent-ish `[0-9]` makes the build work.

The misleading error message in the webhook certainly doesn't help though.

**Comment by fischerscode** [comment]
I run into the same problem. It seems like the regex must not contain a capture group, that may be unmatched. For example, when using this `/^v((?:0|[1-9][0-9]*)\.(?:0|[1-9][0-9*)\.(?:0|[1-9][0-9]*)(?:-[a-zA-Z0-9_\.-]+)?)(\+.*)?$/` regex to catch semantic versioning, then the Webhock returns 500 for the tag `v1.2.3`, since the last capture group `(\+.*)?` may not contain anything.
Workaround: Replace unused and maybe empty capture groups with a non capturing group (`(?:)`).
Semver regex would then be `/^v((?:0|[1-9][0-9]*)\.(?:0|[1-9][0-9*)\.(?:0|[1-9][0-9]*)(?:-[a-zA-Z0-9_\.-]+)?)(?:\+.*)?$/`
