### ISSUE TITLE
I accidentally closed/deactivate a docker account and now I can't seem to reactivate it

### ISSUE THREAD

**Issue by modernNeo** [docker/hub-feedback#1788]
I already made a submission with the form [on this page](https://success.docker.com/support) 4 days ago and still haven't heard back.

**Comment by meticulous-dft** [comment]
Hi, what is your docker id need to reactivate?

**Comment by modernNeo** [comment]
@meticulous-dft sfucsss

**Comment by meticulous-dft** [comment]
sorry i forgot earlier, can you send an email to ming.he@docker.com from the email address you want to associate with the docker id?

**Comment by modernNeo** [comment]
email sent and issue resolved
