### ISSUE TITLE
Cannot add auto-build rules in an organization repo (blocking issue)

### ISSUE THREAD

**Issue by erikmd** [docker/hub-feedback#1789]
## Summary

In the repo `mathcomp/mathcomp` (which had been created as a classic automated build, before the automatic migration) I've just noticed it is now impossible to add auto-build rules.

## Context

The repo belongs to the `mathcomp` Docker Hub organization and I am one of the owners with username `erikmd`.

Since the automatic migration, with the default authentication (with `/u/mathcomp/` in the URL) I see a build trigger "hub-migrated-trigger" but no build details, cf. screenshot 1 of
https://cloud.docker.com/u/mathcomp/repository/docker/mathcomp/mathcomp/builds/edit :

![GH_2019-04-09_16-19-27_Screenshot_u-mathcomp-edit](https://user-images.githubusercontent.com/10367254/55808710-eacf2c80-5ae4-11e9-850d-d302075604af.png)

(the two greyed UIDs being different) while after changing the URL to be identified as `erikmd` (with `/u/erikmd/` in the URL) I see no build trigger, but the current build details, cf. screenshot 2 of
https://cloud.docker.com/u/erikmd/repository/docker/mathcomp/mathcomp/builds/edit :

![GH_2019-04-09_16-20-18_Screenshot_u-erikmd-edit-1](https://user-images.githubusercontent.com/10367254/55808805-19e59e00-5ae5-11e9-9e6e-9c57d9f77280.png)

So far so good, as I expect the discrepancy between the last two screenshots is maybe OK…

## Problem description

In the https://cloud.docker.com/u/erikmd/repository/docker/mathcomp/mathcomp/builds/edit page, I **cannot create auto-build rules anymore**, which is needed to be able to package the recently-released mathcomp library.

To reproduce the bug, I added a line in the end and clicked on Save, cf. screenshot 3 of
https://cloud.docker.com/u/erikmd/repository/docker/mathcomp/mathcomp/builds/edit :

![GH_2019-04-09_16-20-52_Screenshot_u-erikmd-edit-2](https://user-images.githubusercontent.com/10367254/55809088-9a0c0380-5ae5-11e9-9741-b006804057f2.png)

But when I come back to this URL, the build rule at stake is not saved… FYI it seems there is a problem with one of the API calls that return a 404 error, as shown by this screenshot 4 of https://cloud.docker.com/u/erikmd/repository/docker/mathcomp/mathcomp/builds/edit :

![GH_2019-04-09_16-22-36_Screenshot_u-erikmd-edit-3](https://user-images.githubusercontent.com/10367254/55809504-55349c80-5ae6-11e9-8b61-46b200d18b6d.png)

and the response associated with the 404 line is:

```
{"error": "Selected Source does not exist"}
```

This issue is blocking for us, so hopefully you'll be able to investigate this… thank you in advance!

**Comment by erikmd** [comment]
To follow-up my previous post:

1. when I add a new build-rule and click on Save, according to the Firefox inspector, the
    ```
    PATCH https://cloud.docker.com/api/build/v1/source/:token/
    ```
    HTTP request yields a 404 error, with payload:
    ```
    {"error": "Source Provider account is not linked"}
    ```

2. these two repositories (in organization `coqorg`) are also impacted:
- https://cloud.docker.com/repository/docker/coqorg/base/builds/edit
- https://cloud.docker.com/repository/docker/coqorg/coq/builds/edit

So it seems this issue with auto-build rules is a result of the recent migration of classic automated builds…

What should be done to solve this?
Cc @meticulous-dft

**Comment by meticulous-dft** [comment]
Hi @erikmd Thanks for the details. The first screenshot https://user-images.githubusercontent.com/10367254/55808710-eacf2c80-5ae4-11e9-850d-d302075604af.png is the problem. You can only edit the build rules within that context.

You will need to relink github using the `mathcomp` context. You should be able to do it in https://cloud.docker.com/u/mathcomp/settings. Same for the `coqorg` namespace too.

The recent update in auto build may require to relink the source provider for organization accounts.

**Comment by erikmd** [comment]
Thanks @meticulous-dft for your quick and precise response! the configuration of autobuild rules is working again with your suggestion so I'm closing this issue now.

**Comment by cohm** [comment]
FWIW, the same issue had me scratching my head for a good 20 minutes until I found this discussion. If there's an easy way to give a clear error message saying a repo needs to be relinked when this happens, that might save others the same confusion!
