### ISSUE TITLE
Cannot edit url listed in profile

### ISSUE THREAD

**Issue by markmsmith** [docker/hub-feedback#1790]
## Problem description
When I visit my profile on Docker Hub at https://hub.docker.com/u/markmsmith there is a link in the top right beside a house icon linking to https://developer.help.rallydev.com/.

As I am no longer affiliated with this company I would like to remove it from my profile, but when I go to the edit screen at https://cloud.docker.com/u/markmsmith/settings I can't find any mention of this link or any place to remove it.  I've also tried checking my linked gravatar profile, but I don't see any sign of it there.

Hopefully I'm just missing something simple, but I'd appreciate help with this.
Thanks!

**Comment by meticulous-dft** [comment]
Hi, can you try again now from https://cloud.docker.com/u/markmsmith/settings? This is a bug on our side.

**Comment by markmsmith** [comment]
Yup, that fixed it, I was able to update the url.
Thanks!
