### ISSUE TITLE
Nonsense Autobuild interface

### ISSUE THREAD

**Issue by chbrandt** [docker/hub-feedback#1791]
## Problem description
> Briefly describe the problem that you found.

I am creating a new repository which I want to set autobuild on, source code/dockerfile is in a public github repository. My github account is connected; it is not the first autobuild I setup.

Here is a screenshop of my current view (after selecting the option for building from github):
<img src="https://user-images.githubusercontent.com/482051/55955170-fe9f9d80-5c60-11e9-84da-1fe16895c709.png" width="50%" height="50%" />

And...hopefully we all noticed one very important information missing here: the source repository.
**_There is no place to define where the data (i.e., dockerfile) is coming from._**
That is very, very strange.

Please, notice also that the "create" buttons are disabled by now -- which is reasonable, since the data set in inconsistent.

**Comment by meticulous-dft** [comment]
![Screen Shot 2019-04-12 at 4 36 02 PM](https://user-images.githubusercontent.com/8132231/56071124-15b5bc80-5d41-11e9-837f-7ed536406b87.png)

When you click the Github icon, it should show the selectors to choose source repository. Not sure why it did not show up in the screenshot you have.

Another way to setup automated build is to follow the steps here https://docs.docker.com/docker-hub/builds/ after creating the repository.

**Comment by chbrandt** [comment]
Thanks for the attempt @meticulous-dft , I had already followed the steps in https://docs.docker.com/docker-hub/builds/ (although this is far from being my first autobuild) without success. By all means, I just tried _again_ in respect to your attention; again, no success. Here are the screenshots I took now:
![dockerhub_build_1](https://user-images.githubusercontent.com/482051/56117006-77577000-5f67-11e9-908e-e6a04fa0ebd0.png)
![dockerhub_build_2](https://user-images.githubusercontent.com/482051/56117011-7b838d80-5f67-11e9-8138-83e93a9b5644.png)

I don't know...maybe my user/db has something stuck?
Thanks anyway ;)

**Comment by meticulous-dft** [comment]
Thanks for the info. The connection to github is not working, so can not fetch git repositories to populate the selector. Can you try disconnect and reconnect to source provider in settings https://cloud.docker.com/settings?

**Comment by chbrandt** [comment]
Yes. That's it: disconnecting and reconnecting to github did the trick (I also logged out/in just in case some refresh is done in the process). Thanks a lot @meticulous-dft
