### ISSUE TITLE
Delete the dockerfile tab when not using autobuilds or update on every image push

### ISSUE THREAD

**Issue by krasi-georgiev** [docker/hub-feedback#1792]
I believe the dockerfile tab in docker hub is updated at every autobuild. Prometheus is not using autobuilds anymore so this tab is quite outdated.
Could you please delete the details or advise how we can get this updated at every image push.

https://hub.docker.com/r/prom/prometheus/dockerfile

**Comment by meticulous-dft** [comment]
Hi, to remove the `Dockerfile` and `build` tabs, you need to remove the auto build settings.

**Comment by krasi-georgiev** [comment]
As I already mentioned in the issues description the repo doesn't have any auto build settings.

**Comment by meticulous-dft** [comment]
I disabled the auto build settings for this repo. Now the `Dockerfile` and `Build` tabs are gone.
