### ISSUE TITLE
Automated builds not producing tags

### ISSUE THREAD

**Issue by StewMcc** [docker/hub-feedback#1793]
## Problem description
Automated builds complete successfully, but their tags (latest/v0.54) don't show up properly.

`broken:` https://hub.docker.com/r/erothejoker/docker-hugo 
`working:` https://hub.docker.com/r/erothejoker/docker-docfx 

## Recent Builds
![recent-builds](https://user-images.githubusercontent.com/8014812/56042334-b94ba080-5d32-11e9-86d7-4257d395906d.png)

## Current Tags
![tags](https://user-images.githubusercontent.com/8014812/56042345-bea8eb00-5d32-11e9-9565-e6f4f35580eb.png)

Annoyingly it also shows the dockerfile for latest in public view but doesn't allow you to pull the latest tag.

The same process used on separate repo's works without issue.

At a loss as of how to access these builds?

**Comment by meticulous-dft** [comment]
Hi, somehow the build is not finished in the broken repo, that is why there is no new tag created. You can see the build logs dose not have the `Build finished` line as the successful one. Let me check why it did not success.

**Comment by StewMcc** [comment]
Yeah seems weird that everything at first glance seems successful, but is actually failing for an unknown reason. 😞

**Comment by StewMcc** [comment]
Note: deleting repo etc, as no longer using, but still had an odd result, with uninformative builds failing, but appearing successful in the UI
