### ISSUE TITLE
Non-automated build repository get updated automatically

### ISSUE THREAD

**Issue by dclong** [docker/hub-feedback#1794]
## Problem description
I really have to say that DockerHub has messed up. I used to have automated build for my repositories but it was too slow and the same commit got trigger many times. Now I have disabled automated build for most of my repositories but I still see automatical updates to some of my repositories (e.g., https://cloud.docker.com/repository/docker/dclong/jupyterhub-rp). Why?

**Comment by meticulous-dft** [comment]
Hi, can you share more info on where you see the updates? I see last build for the repo is March 11, no more builds have been triggered after that.

**Comment by dclong** [comment]
@meticulous-dft 

![image](https://user-images.githubusercontent.com/824507/56072074-32092780-5d48-11e9-976f-b9eea23c8663.png)

**Comment by meticulous-dft** [comment]
Thanks for the info. I located the problem. Will have a fix next week.

**Comment by dclong** [comment]
Great to hear that. Looking forward to it!

**Comment by dclong** [comment]
@meticulous-dft Has a fix been released? I still see the same problem.

**Comment by meticulous-dft** [comment]
This happens because the classic auto build repolink somehow was still valid. So it builds with upstream changes. Now we have disabled all classic auto build, so should not occur any more.

**Comment by dclong** [comment]
Unfortunately, I still see the same issue.
