### ISSUE TITLE
PS H:\> docker run hello-world Unable to find image 'hello-world:latest' locally C:\Program Files\Docker\Docker\Resources\bin\docker.exe: Error response from daemon: Get https://registry-1.docker.io/v2 /: Forbidden.

### ISSUE THREAD

**Issue by nibus1034** [docker/hub-feedback#1797]
After installing Docker for windows, when i use docker run command i'm getting  Error response from daemon: Get https://registry-1.docker.io/v2 /: Forbidden.

Please find the below log from powershell : 

PS H:\> docker version
Client: Docker Engine - Community
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        6247962
 Built:             Sun Feb 10 04:12:31 2019
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.24)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 04:28:48 2019
  OS/Arch:          windows/amd64
  Experimental:     false
PS H:\> docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 18.09.2
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: ics l2bridge l2tunnel nat null overlay transparent
 Log: awslogs etwlogs fluentd gelf json-file local logentries splunk syslog
Swarm: inactive
Default Isolation: process
Kernel Version: 10.0 14393 (14393.0.amd64fre.rs1_release.160715-1616)
Operating System: Windows Server 2016 Standard Version 1607 (OS Build 14393.0)
OSType: windows
Architecture: x86_64
CPUs: 1
Total Memory: 16GiB
Name: CPWIDWEB0065
ID: 2KEG:NLUA:ASS5:GMGK:6DHG:7OV3:WUZL:5GWL:3DRH:PZMA:R42G:PUAP
Docker Root Dir: C:\ProgramData\docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: -1
 Goroutines: 31
 System Time: 2019-04-15T03:42:26.3000187-05:00
 EventsListeners: 2
HTTP Proxy: http://xxxxx:xxxxx@proxy****.******.com:3128/
HTTPS Proxy: http://xxxxx:xxxxx@proxy****.******.com:3128/
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine

PS H:\> docker run hello-world
Unable to find image 'hello-world:latest' locally
C:\Program Files\Docker\Docker\Resources\bin\docker.exe: Error response from daemon: Get https://registry-1.docker.io/v2/: Forbidden.

Please let me know how it can be resolved & why its happening

**Comment by manishtomar** [comment]
Looks like there is something wrong with your proxy setup. Maybe it is blocking https://registry-1.docker.io/v2/ ? Can you try without proxy and see?

**Comment by nibus1034** [comment]
I removed the proxy details mentioned in the docker desktop settings as well from the system variables & again tried the docker run.
Please find the log below :

PS H:\> docker run hello-world
Unable to find image 'hello-world:latest' locally
C:\Program Files\Docker\Docker\Resources\bin\docker.exe: Error response from daemon: Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (
Client.Timeout exceeded while awaiting headers).

**Comment by nibus1034** [comment]
Any updates on this?

**Comment by thaJeztah** [comment]
if you're running on Windows Server 2016, this is probably the same issue as https://github.com/docker/for-win/issues/3775#issuecomment-484997758

> Microsoft has deprecated and removed nanoserver for Windows Server 2016, which is likely why this no longer works 😔, and windowsservercore is probably a bit too big as a hello-world image.
>
> You can run `docker run -it docker/surprise` (which is quite small)

**Comment by thaJeztah** [comment]
Also see https://github.com/docker-library/hello-world/issues/56 and https://github.com/docker/for-win/issues/2695#issuecomment-483992855

**Comment by nibus1034** [comment]
PS H:\> docker run -it docker/surprise
Unable to find image 'docker/surprise:latest' locally
C:\Program Files\Docker\Docker\Resources\bin\docker.exe: Error response from daemon: Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (
Client.Timeout exceeded while awaiting headers).

**Comment by thaJeztah** [comment]
That looks like a network connection issue; might be something in your network

**Comment by TahseenAlaa** [comment]
I solved this issue by doing bellow steps:
goto terminal and wright `docker login` then `docker run hello-world`

@nibus1034

**Comment by Saswat956** [comment]
$ docker run hello.world
Unable to find image 'hello.world:latest' locally
C:\Program Files\Docker Toolbox\docker.exe: Error response from daemon: pull access denied for hello.world, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'C:\Program Files\Docker Toolbox\docker.exe run --help'.

how to resolve this .i tried login also.still error persists

**Comment by thaJeztah** [comment]
Looks like a typo; the image is named `hello-world`, not `hello.world`
