### ISSUE TITLE
Can't link bitbucket account at settings.

### ISSUE THREAD

**Issue by Vista1nik** [docker/hub-feedback#1802]
Hello. I had problems with builds, docker hub won't to fetch repo.
i unlinked bitbucket account. but now i can't connect it back. "CONNECT" button only refreshing page.

**Comment by meticulous-dft** [comment]
http://docker.status.io/

We are working with BitBucket to resolve this issue.

**Comment by meticulous-dft** [comment]
Bitbucket has restored our client. Should be able to link now.
