### ISSUE TITLE
Problem of #1747 occurs again

### ISSUE THREAD

**Issue by uweplonus** [docker/hub-feedback#1805]
## Problem description
Specifically, angle bracketed ("<") code inside a "code block" is not rendering properly.

For example, the following will not render on hub.docker.com...

script.sh --parameter1 &lt;your parameter&gt;

This seems to be a regression of #1747

**Comment by meticulous-dft** [comment]
Yes, this is a regression. We will fix this early next week.

**Comment by wader** [comment]
Seems to work now 👍

**Comment by demizer** [comment]
It's still broken for https://hub.docker.com/r/nvidia/cuda, I am going to remove the angle brackets for now so the description renders properly.

**Comment by pedroferreira84** [comment]
Same problem here! Still facing problems in the following images:

https://hub.docker.com/r/pegi3s/bedtools/
https://hub.docker.com/r/pegi3s/sapp/
https://hub.docker.com/r/pegi3s/soapdenovo2/
https://hub.docker.com/r/pegi3s/utilities/

Pedro.

**Comment by pedroferreira84** [comment]
Any developments about this problem?

**Comment by meticulous-dft** [comment]
Hey @pedroferreira84 Can you point to me specifically which part of text in each of these repos do not render correctly? This would help me a lot to track down the problem. Thanks.

**Comment by pedroferreira84** [comment]
Sure @meticulous-dft !! 

https://hub.docker.com/r/pegi3s/bedtools/
Error: docker run --rm -v /your/data/dir:/data pegi3s/bedtools <bedtools-application-name> -fi -bed <bed> -fo /data/stdout)
It should be:
docker run --rm -v /your/data/dir:/data pegi3s/bedtools <bedtools-application-name> -fi <input FASTA> -bed <BED/GFF/VCF> -fo /data/stdout

**Comment by pedroferreira84** [comment]
BedTools: https://hub.docker.com/r/pegi3s/bedtools/

Error:
[https://drive.google.com/file/d/1_HrpC3VC-QW_IWEfN9kFdpu3Bb5UKkr-/view](url)

Correct:
[https://drive.google.com/file/d/1iCd5HvKE3LEdQiodxkVvF_cj-sLitAL-/view](url)

**Comment by pedroferreira84** [comment]
SAPP: https://hub.docker.com/r/pegi3s/sapp/

Error:
https://drive.google.com/open?id=1uWZfocK9C6yol7f3zjqGiO4GLlQCC4P5

Correct:
https://drive.google.com/open?id=1m04Q3ETZu-I6ne1abIRt1VpqPZ71JEr1

**Comment by pedroferreira84** [comment]
SOAPdenovo2: https://hub.docker.com/r/pegi3s/soapdenovo2/

**Error:**
https://drive.google.com/open?id=1vmuHxRpgKCUiFX1ftdcxrInPrqB3AJT5

**Correct:**
https://drive.google.com/open?id=1ohNI-PhlUKgF1EkJUKkqDSXDNAWh30fE

**Comment by pedroferreira84** [comment]
**Utilities:**https://hub.docker.com/r/pegi3s/utilities/

**Error:**
https://drive.google.com/open?id=1Ch3CvvUTTV9ABBmL8exaVizuSnZtKL8d

**Correct:**
https://drive.google.com/open?id=1D01uv-FVLqvqd62NB8BFNmM9JTgyQjKp

**Comment by pedroferreira84** [comment]
Problem persists....

**Comment by meticulous-dft** [comment]
Hi @pedroferreira84 the problem is `<>` is considered by our parser as html tag, and might add close tag `</...>` or strip it `<input  >`. 

I am working on fix the parsing issue. In the mean time, is it possible for you to use some other symbols instead of `<>` for placeholder?

**Comment by pedroferreira84** [comment]
Dear @meticulous-dft I prefer to wait for you to fix this, as we have other README.md from other Docker images that have those characters "<>" and the problem don't happen.

**Comment by pedroferreira84** [comment]
On this Docker image for example: https://hub.docker.com/r/pegi3s/utilities/ is impossible to use other symbols instead of "<,>" because it's an example of a test case file...

**Comment by pedroferreira84** [comment]
@meticulous-dft any developments on the parser issue? Still facing the problem here...

**Comment by TimWolla** [comment]
The second code block of the “Loading Plugins” section of Admin is affected as well. For that one the opening `<?php` tag is treated as an HTML tag: https://hub.docker.com/_/adminer/#loading-plugins

**Comment by pedroferreira84** [comment]
> Dear @meticulous-dft I prefer to wait for you to fix this, as we have other README.md from other Docker images that have those characters "<>" and the problem don't happen.

Dear @meticulous-dft any developments on this matter? It's been a while since this problem persists...

Thank you.

**Comment by meticulous-dft** [comment]
@pedroferreira84  Sorry, it takes us a while to figure out how to correct this. I believe it is rendering correct now. Please take a look.

**Comment by pedroferreira84** [comment]
> @pedroferreira84 Sorry, it takes us a while to figure out how to correct this. I believe it is rendering correct now. Please take a look.

Thank you very much!! :) It's everything OK now!
Best regards,
Pedro.
