### ISSUE TITLE
No activation email. No support reply

### ISSUE THREAD

**Issue by tomcorby** [docker/hub-feedback#1808]
It's been two months since I tried creating an account, and two months since I submitted a support ticket (ref 00070862)

Resending verification email button does nothing. Password reset link does nothing. Apparantly the only way to get a reply is via creating duplicate issues on github, where people are told to contact support either by email or using the support link, which I have already done.

**Comment by meticulous-dft** [comment]
Hey, sorry to hear this. Can you post your `DockerID` here, i can take a look.

**Comment by tomcorby** [comment]
tcfod is my id

**Comment by meticulous-dft** [comment]
Thanks. I activated your account.

**Comment by brian-kane521** [comment]
I'm having the same issue, no replies to support emails. Signup email is dockerhub@dorae.com

**Comment by ldibello** [comment]
I have the same issue to ageak8s user, can't see resend email validation
