### ISSUE TITLE
[zoolu2/*] Mining malware from "marumira" under different account

### ISSUE THREAD

**Issue by btx3** [docker/hub-feedback#1809]
All images on the zoolu2 Docker Hub account are either the exact same or extremely similar to the one pointed out in issue #1807 (XMR miner, automatic spreading through Shodan, etc.), except some now use multiple Shodan accounts instead of just one.

**Comment by btx3** [comment]
Hi,

Bumping this to let you know this is still an ongoing attack:
![img](https://i.imgur.com/MBHKDKf.png)
(image from my Docker honeypot)

**Comment by Caprico1** [comment]
https://www.shodan.io/search?query=docker+%22zoolu2%22+port%3A2375

Ran across this yesterday. Seems like zoolu2 account could be still active. Saw a result come in on a machine in Poland today that wasn't there last night.

Are these images still from zoolu2 still propagating in your honeypot? 

I'm not seeing anything on shodan for that other image.

**Comment by btx3** [comment]
Yup, I've been seeing multiple different images from the same account:

![Imgur](https://i.imgur.com/Nj7obB0.jpg)

**Comment by Caprico1** [comment]
Thanks,
I'm going to be looking at them closer in a VM here in a bit. I'll let you know if I find anything.

**Comment by Caprico1** [comment]
looks like the mini1 image is making a callout to some server. 
![image](https://user-images.githubusercontent.com/24262012/57897609-421a9800-781b-11e9-943d-0e2b275f94e8.png)

I'm going to keep digging but I'll check back.

Can you see any outbound traffic from your honey pot?

**Comment by Caprico1** [comment]
Okay looks like a couple of them are going out and querying shodan looking for port 2375. It's almost exactly asking the link that I sent earlier.

**Comment by Caprico1** [comment]
So....here are the shodan accounts...

![image](https://user-images.githubusercontent.com/24262012/57903370-55d1f880-7833-11e9-951c-a2fa93c8f7bc.png)

**Comment by btx3** [comment]
Sorry, didn't see the emails. About the outbound traffic, there is some through tor, so I don't exactly know where it's going. It also seems to use multiple Shodan accounts instead of just one like in the previous image.

Also, the mining endpoint is to Nicehash (same account name), so a report should stop the mining.

**Comment by Caprico1** [comment]
yeah I found the onion link at least for the Auto image. Dm me on twitter and I'll share what I've got.

**Comment by Caprico1** [comment]
https://twitter.com/Suprn8/status/1129877707897081856

Got confirmation from shodan that those accounts are deactivated they won't propogate anymore

**Comment by manishtomar** [comment]
I've disabled `zoolu2` account. Thanks for the report.

**Comment by Caprico1** [comment]
He's back.

The user is Pavlov32. The image is pavlov32/auto
https://hub.docker.com/r/pavlov32/auto

it has the exact same code minus a 0 byte file named pavlov (i assume to get passed some file hash tests)

I am contacting John Matherly again to get the accounts disabled.

**Comment by manishtomar** [comment]
I've disabled this account also `pavlov32`. Thanks for the report.

**Comment by Caprico1** [comment]
and again,

user is zoolu2 image is zoolu2/jauto. 
https://hub.docker.com/r/zoolu2/jauto

exactly the same code. and it even links to pavlov32.
