### ISSUE TITLE
Please remove IPs from the blacklist

### ISSUE THREAD

**Issue by korsikm** [docker/hub-feedback#1810]
85.159.148.19
80.79.203.12
109.109.136.10

Please unblock and provide us with the reason for the blocking of mentioned IPs. We suppose It could be caused by some of our monitoring automation that performs docker hub availability checks from all the servers. Also is there any policy to be used in terms of building our workflows to stay in a safe area? 

Thanks,

**Comment by tescherm** [comment]
Hi @korsikm, the ip addresses have been unblocked. While checking for abuse, we incorrectly determined that these were abusive ips.
