### ISSUE TITLE
Automated build error github

### ISSUE THREAD

**Issue by job3-14** [docker/hub-feedback#1812]
Hello
I want to do an automatic build on github using Automated build.
However, the build does not start forever. The yellow clock mark indicates that it was created with “master: / Docker / *****” (**********). More than six hours have passed since the repository was created, but there has been no change.
Also, this sentence may be strange because it was translated by google translation.
Thank you very much.

**Comment by job3-14** [comment]
![キャプチャ](https://user-images.githubusercontent.com/38198567/57266553-53df9b00-70b7-11e9-8789-c26ef0f5b456.PNG)

**Comment by azuken** [comment]
Same issue here, since one week, automatic or manual builds stays in pending.

**Comment by koenhendriks** [comment]
Same issue here, when googling found an older issue where people report the same problem:

https://github.com/docker/hub-feedback/issues/1370

**Comment by Tiboris** [comment]
Same issue here followed by this: https://github.com/docker/hub-feedback/issues/1813#issuecomment-495624879
