### ISSUE TITLE
Automatic build stuck from before re-linking github

### ISSUE THREAD

**Issue by cpoppema** [docker/hub-feedback#1815]
## Problem description
Not too long ago we had to switch the way dockerhub integrates with github. I believe we've all had to redo repo setup/relink accounts. i believed I had done that already, but today I got this error message during an automatic build:

https://cloud.docker.com/repository/registry-1.docker.io/cpoppema/docker-flexget/builds/47b50d35-57e2-42b8-8312-76f288284b8d
```
Building in Docker Cloud's infrastructure...
Cloning into '.'...
Warning: Permanently added the RSA host key for IP address '192.30.253.113' to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.
please ensure the correct public key is added to the list of trusted keys for this repository (128)
```

So I relinked again, did a "save and build" and it add another build to the queue.

The problem is that it seems my build queue is now stuck. I tried to manually cancel the broken auto build using all the different cancel buttons I could find: after inspecting xhr I see "operation cannot be canceled".
Now, after 3 hours it says "canceling", but who knows how long that is going to take. This doesn't seem right.

Edit: so it was completely canceled after 251 minutes and the next build completed fine. I still hope something can be done to prevent this in the future for everyone.

**Comment by meticulous-dft** [comment]
Thanks for the info. We will look into this issue.
