### ISSUE TITLE
Certificate issue for auth.docker.io

### ISSUE THREAD

**Issue by tumpech** [docker/hub-feedback#1817]
## Problem description
auth.docker.io's certificate is valid for *.hms.awsdev.infor.com, not auth.docker.io. This makes login to dockerhub impossible. For now, this affects only one computer, other computers in the same network do not produce this kind of behavior. However, this affects every program on that computer.

```
C:\Users\LaszloTumpech> docker login
Login with your Docker ID to push and pull images from Docker Hub. If you don't have a Docker ID, head over to https://hub.docker.com to create one.
Username: laszlotumpech
Password:
Error response from daemon: Get https://registry-1.docker.io/v2/: Get https://auth.docker.io/token?account=laszlotumpech&client_id=docker&offline_token=true&service=registry.docker.io: x509: certificate is valid for *.hms.awsdev.infor.com, not auth.docker.io
```

**Comment by tumpech** [comment]
Found the issue, for some reason, docker addresses were hardcoded in the system.

```
# Docker hosts
52.202.29.4		index.docker.io
52.70.175.131 	registry.docker.io
52.22.201.61 	registry-1.docker.io
34.205.207.96 	auth.docker.io
13.35.242.68	dseasb33srnrn.cloudfront.net
104.18.123.25	production.cloudflare.docker.com
# End Docker hosts
```

**Comment by polar9527** [comment]
> Found the issue, for some reason, docker addresses were hardcoded in the system.
> 
> ```
> # Docker hosts
> 52.202.29.4		index.docker.io
> 52.70.175.131 	registry.docker.io
> 52.22.201.61 	registry-1.docker.io
> 34.205.207.96 	auth.docker.io
> 13.35.242.68	dseasb33srnrn.cloudfront.net
> 104.18.123.25	production.cloudflare.docker.com
> # End Docker hosts
> ```

Thanks, it works for me!
