### ISSUE TITLE
Documentation: "Supports Regex" is insufficient specification

### ISSUE THREAD

**Issue by atz** [docker/hub-feedback#1821]
# Problem description

For triggering builds, docker hub supports triggers based on pattern-matching branches/tags, as documented in the section ["Regexes and automated builds"](https://docs.docker.com/docker-hub/builds/#regexes-and-automated-builds).  This feature _sorta_ works, but very much leads users astray by not specifying _which_ specific regex syntax is supported.  

From experimentation, I conclude that the following are NOT supported:
- PCRE - Perl (5) compatiable RegExp
- POSIX Extended RE - e.g. BSD `egrep` matching

Is the intent to support POSIX Basic RE?  If so, the lack of escaping requirements (e.g. parens) would be important to call out.

Correct me if I'm mistaken, but feature-wise, critical restrictions currently include:
- Character classes, like `\s`, \d`, etc.: NOT supported
- POSIX character classes like `[:digit:]`: NOT supported
- Switches (e.g. case-insensitivity, greedy vs. non-greedy matching): NOT supported
- Look-ahead: NOT supported
- quantifiers: ???
- alternation, e.g. `/(rc|beta)$/`: ???

Ideally the UI/docs would reference some combination of:
- the implementation library version (so users can go read its docs as authoritative)
- the abstract syntax specification, if available
- a live web UI like [regex101.com](https://regex101.com/) that would allow dynamic construction and validation of whatever syntax IS supported.

Note: lack of clarity also potentially affects utilization of RE features that ARE supported by obscuring which syntax/escaping allows access to them.

Thanks!

**Comment by privatehosting** [comment]
Automated Builds with regex is crap ... and doenst work ... 

it just stays at "Build Status: Empty" ... Already checked many regex combination ... 
{\1} ... {\9} will be replace everytime to {sourceref} --- without information why this happen ... 
examples doesnt work neither ...

**Comment by alexkuc** [comment]
It appears that `?!` does not work as well. The only thing that worked for me was `A-z`, `0-9` and `-`. For example, this regex worked for me: `/[A-z0-9-]+/`. 

Additionally, I have observed the following behaviour: Docker Hub will push any regex images to the top of the build matching rules. 

Also matching is greedy meaning Docker Hub will try to find as many matches as possible (it won't stop on the first successful match!). 

Finally, use of non-supported flags/characters/expressions appears to break the automatic building (manual trigger works fine though) until non-supported expression is removed.
