### ISSUE TITLE
Greater-than symbol ">" is escaped to "&gt" When Inside backticks or triple backticks

### ISSUE THREAD

**Issue by leonowski** [docker/hub-feedback#1824]
Similar to the issue here:

https://github.com/docker/hub-feedback/issues/1746

However, this problem appears when the ">" symbol is inside a text block surrounded by triple backticks or backticks.

For example, this:
```
$ curl -d "@request.json" -H "Content-Type: application/json" -X POST http://localhost:4200/sync > response.json
```
Shows up incorrectly rendered as:

$ curl -d "@demand-request.json" -H "Content-Type: application/json" -X POST http://localhost:4200/sync `&gt;` demand-prediction.json

**Comment by meticulous-dft** [comment]
This should be fixed now.
