### ISSUE TITLE
Certain build rules do not trigger manually or automatically

### ISSUE THREAD

**Issue by Time6628** [docker/hub-feedback#1827]
## Problem description
We were originally getting the issue resolved in #1825, which we are no longer seeing.
We now get this error when triggering certain build rules:
```
{"error": "Branch 'dev/master' not found"}
```
It seems to be only for branches that start with `dev/` as I've tried all our dev branches and they all produce the same thing. We have a build rule for a `live` branch that triggers with repo pushes and manually, while the dev build rules do not for either.
Our repo is hosted in a private BitBucket cloud repo.

Screenshots:
Build Rules:
![image](https://user-images.githubusercontent.com/9041033/58817176-283dcb00-85f9-11e9-80f1-f3dc803a526a.png)

**Comment by Time6628** [comment]
Unsure what changed, but now pushes to the repo are fine. Manually attempting to build it still throws the same error.

**Comment by sarkis** [comment]
@Time6628 thanks again for reporting the issue. This should now be fixed, please let us know if you continue to experience issues.
