### ISSUE TITLE
Link to Bitbucket broken

### ISSUE THREAD

**Issue by martnst** [docker/hub-feedback#1829]
Link to Bitbucket from https://cloud.docker.com/u/$username/settings it not working. 

Bitbucket is giving this error blaming the vender, which is Docker Hub in this case. 

![image](https://user-images.githubusercontent.com/3084607/58946187-a62edd00-8785-11e9-8a3c-33179da5c312.png)

The `redirect_uri` is: 

https://bitbucket.org/site/oauth2/authorize? [...] 
&redirect_uri=`https%3A%2F%2Fcloud.docker.com%2Fapi%2Ftutum%2Fv1%2Fcredentials%2Foauth%2Fbitbucket%2Fcomplete%2F` 
[...]

**Comment by sarkis** [comment]
@martnst thank you for reporting this. It looks like this may be an issue on Atlassian side, I've reached out and have an update from their support team:

```
Cassiano Alves05/Jun/19 4:03 PMLATEST
Hello Sarkis,

Our team is currently investigating an issue with OAuth that affects connections to Bitbucket Cloud. Our apologies for the inconvenience caused by this.

We will give you an update as soon as we have more info on the issue.

In the meantime, feel free to let us know if you have any questions.

Thank you,
Bitbucket Cloud Support Team```

Will keep posted on this issue as I get updates.

**Comment by sarkis** [comment]
Looks like the bitbucket status page is updated now:

```
OAuth “Invalid redirect_uri” error Subscribe
Identified - Users who try to connect their Bitbucket account via OAuth see an “Invalid redirect_uri” error. The Bitbucket team is working on resolving this issue
```

https://bitbucket.status.atlassian.com/

**Comment by sarkis** [comment]
@martnst this issue has now been resolved by Atlassian

**Comment by martnst** [comment]
Thanks @sarkis for going after this. I can confirm that Bitbucket Connect is now working fine for me.

**Comment by ab-dev-github** [comment]
I still get this.
