### ISSUE TITLE
Automated Build Regex Doesn't Work

### ISSUE THREAD

**Issue by ryan-clancy** [docker/hub-feedback#1831]
## Problem description

I have a [repo](https://github.com/osirrc/anserini-docker/releases) with tag `v0.1.1` and the Automated Build for tags with regex `/^v([0-9.]+)$/` (exactly the "View example build rules" example), doesn't work and shows a Build Status of EMPTY. Can this be fixed?

![image](https://user-images.githubusercontent.com/1282383/59553346-c3bc2d80-8f61-11e9-86ad-88d72b94f393.png)

**Comment by sarkis** [comment]
@r-clancy are you still seeing this issue? I was unable to successfully reproduce this issue. Can you provide any details to help reproduce the issue?

**Comment by sarkis** [comment]
I think you'd like to trigger a build from the docker hub UI on an existing tag, unfortunately I do not think this is possible by design. If we allowed for the trigger to happen from here we'd need to trigger for all tags that match the regex, which in most cases would be unexpected. Have you tried pushing to the tag to trigger this from the git repo?

**Comment by sarkis** [comment]
@r-clancy Thanks for the report, however based on the above comments, I am closing the issue. Please re-open if the above has not unblocked you.

**Comment by psi-4ward** [comment]
Similar problem here. I've tags with `4.1.10` but `/^[0-9.]+$/` never triggers if I push a new tag or if I renew a tags commit.

**Comment by sarkis** [comment]
@psi-4ward can you provide more information, what is the exact tag (i.e. does it start with a `v`?) What provider are you using github or bitbucket? If you are using bitbucket is this for git or mercurial?

**Comment by psi-4ward** [comment]
It's all public. See https://github.com/psi-4ward/docker-powerdns/releases

Type: `Tag`
Source: `/^[0-9.]+$/`
Ref: `{sourceref}`

I force-pushed Tags `4` and `4.1` and created `4.1.10` but it did only built the `master`

**Comment by sarkis** [comment]
@psi-4ward I see that you have specific build rules set for 4, 4.1, 4.1.10. What I believe is happening here is that the specific build rules are matching before the `/^[0-9.]+$/` one. Did you create these after the above issues?

**Comment by psi-4ward** [comment]
I had the issue for some time now and created these some weeks ago but at least the new tag 4.1.10 should match the regex

**Comment by r-clancy** [comment]
Apologies for the late response, @sarkis, I've been traveling.

When creating a new tag the build is performed properly, I guess I was looking for a retroactive build of tags. However, it seems that @psi-4ward is having a different (but related?) issue...

**Comment by shazow** [comment]
Same problem here, particularly for existing tags.

If the behaviour does not intend to apply to exist tags, it would be useful to have some kind of UI indicator of that, maybe the option to force a build on some existing tags. Bonus points if it could show what tags it would have matched the expression.

**Comment by shazow** [comment]
Also maybe unrelated issue, but editing doesn't work for me anymore:

## Dashboard

![image](https://user-images.githubusercontent.com/6292/60207203-4fb43c00-9823-11e9-9bda-5bff8ec02ee3.png)

## Configure automated builds

Changed `release-{sourceref}` to `{sourceref}`

![image](https://user-images.githubusercontent.com/6292/60207244-65c1fc80-9823-11e9-9ea2-19ea944af459.png)

## After save

![image](https://user-images.githubusercontent.com/6292/60207256-6d81a100-9823-11e9-89d0-54fe85f12e0f.png)

I have to delete the row and remake it to actually get it to change.

**Comment by r-clancy** [comment]
> Also maybe unrelated issue, but editing doesn't work for me anymore:
> 
> I have to delete the row and remake it to actually get it to change.

I can confirm I've seen this issue too.

**Comment by sarkis** [comment]
> > Also maybe unrelated issue, but editing doesn't work for me anymore:
> > I have to delete the row and remake it to actually get it to change.
> 
> I can confirm I've seen this issue too.

Thanks for reporting this - we're working on a fix for this, in the meantime, you will need to delete and recreate Build Rules, these should be immutable but the ui currently shows it as an editable field which should not be the case.

**Comment by wuhkuh** [comment]
Any updates on retroactive builds using regex matches? I am having the same problem (autobuild not triggering for existing tags).

**Comment by ruffsl** [comment]
> Thanks for reporting this - we're working on a fix for this, in the meantime, you will need to delete and recreate Build Rules, these should be immutable but the ui currently shows it as an editable field which should not be the case.

Deleting the rule is kind of a pain in that for `REPOSITORY LINKS` set to `Enable for Base Image`, these automated triggers do not seem to come into effect until the build rule has been manually triggered at least once. Thus, if users need to correct/update the tag in a build rule, they have to recreate it and wait for a successful build before being sure the triggering from `REPOSITORY LINKS` is live for that rule. 

I'm guessing this is due to the lazy evaluation of the `FROM` directive in the Dockerfile targeted by the rule, so that the underlying `REPOSITORY LINK` is only added after the first trigger following the hour or so average queing time, and not instantaneously when the user adds the build rule in the web UI. 

Shouldn't the Dockerfile for the build rule be examined when the build rule is added, or for all rules when the `REPOSITORY LINKS` radio button is toggled? Having to wait to verify links are working is tedious.

**Comment by tzinm** [comment]
I have the same problems as @r-clancy and @shazow. The tag Source Type doesn´t work, and to change the Docker Tag I have to remove the row and recreate it.

**Comment by javierluraschi** [comment]
Same here, tried a bunch of different combinations but can't seem to get regex to work, while non-regex tags work fine:

<img width="1092" alt="Screen Shot 2019-09-15 at 8 03 48 AM" src="https://user-images.githubusercontent.com/3478847/64923533-7d0fe680-d78f-11e9-9af2-a3b4756d5e1d.png">

Image: https://cloud.docker.com/repository/docker/jluraschi/multiverse-k8s/builds

**Comment by yilunzhang** [comment]
We also experienced this issue, and strangely it's repo-dependent:
* In the original repo non-regex rule works, but regex rule matching tag does NOT work.
* If I fork the repo to another account, both non-regex and regex rule works.

**Comment by tsarna** [comment]
Still not working over a year later.

**Comment by Guang1234567** [comment]
Still not work in 2020-08-12 -_-||,  i think create a `demo-hello-world-docker` project can reproduce the problem.

My cfg:

![image](https://user-images.githubusercontent.com/8240718/90491452-85785a80-e172-11ea-9c23-940f2b77d700.png)

I already test in [regex101.com](https://regex101.com/r/hYMvKp/1/), it ( `\^v([0-9.]+$)\` ) works,  but in docker-hub donot trigger auto-build

![image](https://user-images.githubusercontent.com/8240718/90492573-eb191680-e173-11ea-85d1-01bc0d90f15d.png)


thanks.

**Comment by a-st** [comment]
Looks like this issue only occurs if the selected repository is a fork

**Comment by yilunzhang** [comment]
> Looks like this issue only occurs if the selected repository is a fork

In our case it's not true. Our original repo is the one that suffers from this problem.

**Comment by mderouet** [comment]
Same issue here, I tried all the examples provided. None of them are working for some reasons.
Using a private repository on my side...
It seems like no one is interested in providing a fix or at least an explanation.

**Comment by kaipyroami** [comment]
I am currently having this same issue with all but the "example" regex rules. For some reason if I copy the suggested examples from the drop down I can get the regex to work but only with that specific instance. (Example: v1.2.3 to version-1.2.3)

**Comment by mderouet** [comment]
@kaipyroami 
Did you succeed to make it work with the regex, or only specific version, otherwise can you put here an example of your configuration ?

**Comment by davidmurdoch** [comment]
Does seem to work for this config either:

![image](https://user-images.githubusercontent.com/187813/94939976-de8d1b00-04a0-11eb-8d24-40fff68ea7a1.png)

**Comment by ThomasJejkal** [comment]
Not surprisingly, I have the same issue. I have two build triggers, one for master mapping to latest and one for tags mapping to the according version. The builds are expected to be triggered by a Webhook configured to fire on all events. 

I've tried several configuration options and expressions, including /^([0-9.]+)$/ mapping to {\1} as well as /^[0-9.]+$/ mapping to {sourceref}

However, the build is not triggered on tag creation/modification nor can I trigger the build manually as the "Trigger" button is not shown. 

The only scenario in which I've managed to get the workflow running is by mapping /^v([0-9.]+)$/ to {\1}, turning off the build caching leaving Autobuild enabled. Also in that case, the "Trigger" button is not visible but the automatic trigger is working. I hope this helps solving the issue as we do not plan to change our version naming scheme just to get the builds running on DockerHub. ;-)

**Comment by BKhenloo** [comment]
Same problem here. Old tags are not detected.

But with this setting:, all new tags are created.
![image](https://user-images.githubusercontent.com/74878006/102773844-304f8e00-438a-11eb-87c8-980057aa2d55.png)

**Comment by ZacharyACoon** [comment]
Same problem.  Regex matching simply does not work.

**Comment by liyishuai** [comment]
The only setting that worked for me:

| Source | Docker Tag
|---|---
| `master` | `latest`
| `/.*/` | `{sourceref}`

Somehow usable, assuming:
1. You want to build all branches.
2. Unless specified by string literals (like `master`), the entire branch name becomes a substring of the docker tag.

**Comment by pschiffe** [comment]
I'm also not able to make regex rules work in any way.

**Comment by mschirrmeister** [comment]
Not sure if something was fixed within the Docker automated build system, but automatic builds for Github tags works for me. It does **not** work for existing tags after adding a new rule, but it **does** work, when a new tag is created. 

Here is what I use.

Source | Docker Tag
-- | --
/^v([0-9.]+)$/ | {\1}

After creating a new tag, it triggered a build and it was successful.

<img width="659" alt="docker_auto_build" src="https://user-images.githubusercontent.com/1037177/116828099-e0d16800-ab9c-11eb-8314-ec61fce6f282.png">

**Comment by mderouet** [comment]
Tested again today, still now chances with this feature, my rules:
![image](https://user-images.githubusercontent.com/9265133/116828657-568b0300-aba0-11eb-911b-f8c2a2a25dc5.png)
When hardcoding a tag, it works like charm when I create a new release (first create the tag on docker hub eg: 1.0.9 and then create a release on github.

But still not works with the last rule, nothing is getting trigger:
My new release was 2.0.0 for testing purpose.
@mschirrmeister do you know whether I should do something different or is it just randomly working?

**Comment by AstroGD** [comment]
Same issue here - On another repo my regex works. On the next it doesn't. It's the same regex string, Every tool that I tried recognizes the tags but automatic builds are just not being triggered...

**Comment by ZacharyACoon** [comment]
Is this still not fixed?

I'm having to setup github actions instead.

**Comment by patrick7kelly** [comment]
[This comment](https://github.com/docker/hub-feedback/issues/1831#issuecomment-504766137) was pretty helpful.

It seems like you want the regex rule to be the first one under "Automated Builds".  This started working for me once I moved the regex rule to the top and added a new rule for master/latest below it.

I guess it stops evaluating additional rules after it hits the first match.

**Comment by AstroGD** [comment]
I can confirm this to be correct @patrick7kelly !
It seems like Docker only builds the first successful rule.

However Docker builds are sorted by Docker Tag name so there is no tag prioritization possible. You need to rename your docker Tags to get to the desired order.

But a few days ago my branch rule didn't exist and it still did no build although the tag should have matched so this seems to be a more complicated issue. I don't understand why it's working now...

**Comment by mschirrmeister** [comment]
For me, I did not need to have the regex rule first. I have only 2 rules. First one is to build `master/main`, if there is a commit and then there is 1 regex rule for whenever a tag is created in Github.

@mderouet For me it was consistently working. For what you can do differently, maybe try it more simple without creating the tags in Docker Hub.
Only thing I created was this regex rule. Then I tagged a commit in Github with for example `v1.0` and that triggered the build in Docker Hub and created a new tag `1.0`.

**Comment by thaivanhoa** [comment]
still not work on 20222222222222222222222222

**Comment by thaivanhoa** [comment]
![image](https://user-images.githubusercontent.com/7814259/165251162-01b3155f-2f00-4d0d-86e6-e5ddb67be55f.png)
actually it's not stable
actually it's not stable

**Comment by psi-4ward** [comment]
We switched to github actions..

**Comment by burnsjeremy** [comment]
It took me forever to figure this one out, there probably needs to be some more documentation around it and it would be much easier. The docs only has a small paragraph about it and then the examples don't help either. So of course starting out you get your static tags setup usually (in my case I wanted develop branch to build to develop tag, and test also). This is a private bitbucket repo and those were working great. Then I wanted to add in the tag part for releases, so I create a git tag and then get a docker tag created automatically. I tried all sorts of different combinations but then went to just a simple number tag to number tag to see what was going on. Nothing would build. I read through this thread and decided to remove all auto builds and start with the tag only, get it working how I wanted and then add back in develop (other static tags). This was the only way that I could get it to work. I used

`/^([a-zA-Z]+)\/(\d(\.\d){2})$/` to `{\1}-{\2}` and my git tags are `release/1.1.1` then my docker tags are `release-1.1.1` 

Again, this would not work until I removed all other build rules. When you add the others back in they will show above the tag rule again but the builds will work then at least. If you ever want to change it or add another I am assuming that you would have to remove all of them also. Then add back with least specific at the top (I have not tested that but that is what it sounds like). Old tags do not build again either, or multiple. You have to create a tag and then push that tag for it to build. 

It was hard to get it going but well worth it now that it is, so maybe we can help make it easier or the dev team could help.

**Comment by u-yas** [comment]
Hi, I was suffering from the same problem, but I experimented with one thing and found an oddity, so I share it with you. I hope others can try this and get it working.

When pushing a git tag with `git push --tags`, dockerhub's autobuild did not detect it. Instead, pushing one specific tag made dockerhub autobuild work!


❌
````
git tag -a v1.0.0 -m ""
git push --tags
```

🟢
```
git tag -a v1.0.0 -m ""
git push origin v1.0.0
```

Hope this helps!
