### ISSUE TITLE
Unable to create new Docker ID after deactivating old one

### ISSUE THREAD

**Issue by ashauer** [docker/hub-feedback#1834]
## Problem description
I followed the instructions on [How do I change my Docker username?](https://success.docker.com/article/how-do-i-change-my-docker-username) and deactivated my old account (_lashauer_).

I got a mail telling me ...

> Your Docker User ID 'lashauer' has been deactivated and all personal information associated with the account has been deleted.

When I try to create my new account using the same email address as in my old one I get the following error message:

> This email address is already associated with an account.

The old one is not accessible anymore. When I try to login into the old one I get the following error message:

> Account has multiple email addresses. Please contact customer support to fix it.

Can you please completely deactivate/remove my old account so I can create the new one? Thx a lot!

(BTW, this was the only plausible channel I found to get in contact with you regarding this issue...)

**Comment by AmauryOrtega** [comment]
Same situation, old account was _xxdrackleroxx_. Now I want to create a new account with the same email address and I can't create a new account because of the error message:

> This email address is already associated with an account

**Comment by rhenriquez28** [comment]
Same here. And I've already received the email confirmation that all my old info has been deleted:
>Your Docker User ID 'roy068' has been deactivated and all personal information associated with the account has been deleted.

Yet I still get the same error:
>This email address is already associated with an account

**Comment by AmauryOrtega** [comment]
@rhenriquez28 Update (10 days later), I was able to create a new account with my old email address. Try again in a few days and it will probably work.

Still, the issue is that the process takes time and I don't know if there's a sign that this will happen which makes the UX not so great

**Comment by ashauer** [comment]
Doesn't apply for me. 14 days now, still not able to create the a account with the old email address, and - wha's point on here? - still no action about this issue...

**Anybody out there being able to solve this???**

**Comment by AmauryOrtega** [comment]
@ashauer Maybe try creating the account using a VPN or proxy in another part of the world, it could work if there is some region dependent database or similar that is being checked at account creation

**Comment by xiaklizrum** [comment]
same case, after week my account keep on associated to deactivated account. my ticket (number 00096348) has no reaction

**Comment by ashauer** [comment]
my ticket number is 00091263. There was no response at all. Even a request weeks (!) later about the ticket's status did not make them react in any way...

**Isn't there anybody from Docker listening and able to at least respond??? Sorry, but: What kind of a behavior is this?**

**Comment by jam** [comment]
Same problem here... opened a support ticket over a week ago (00098802) and haven’t had a response yet.

**Comment by DarylAranha** [comment]
If you want to get access to your old account then click on reset your password. You will get a mail to reset it, once done try login in. I worked for me.

**Comment by alexkuc** [comment]
> If you want to get access to your old account then click on reset your password. You will get a mail to reset it, once done try login in. I worked for me.

I have tried deactivating the account and encountered the same pesky message. Here's what I did

- re-activate the account by doing a password reset (as mentioned by @DarylAranha )
- change email to something else
- change new email to primary and remove the old email from the old account
- register new Docker Hub account with old email

**Comment by mydevfingers** [comment]
Thats great. It worked for me too. However, i had created an organization name and deleted it, but that organization name is not available now for recreating. Does it take more time or a day to clear the deleted organization name from backend?

![dockerhub_org_issue](https://user-images.githubusercontent.com/29328825/77613285-4f3d0300-6f65-11ea-8a96-8448a438e25f.PNG)

**Comment by nigelmpofu** [comment]
> If you want to get access to your old account then click on reset your password. You will get a mail to reset it, once done try login in. I worked for me.

I am only able to reset my password but I am still not able to login. I get the following error message:
> Account has multiple email addresses. Please contact customer support to fix it.

I've created multiple support tickets over the last few months without any success. Is there another way to get around this?

**Comment by ashauer** [comment]
Same for me, @nigelmpofu: I also get the "Account has multiple email addresses" message, and I also did not get any response for my support ticket. This is really embarrassing for a company like Docker! No response on the official ticket channel, no reaction here in _their_ GitHub account. Really disappointing! Still nobody reading here who's part of Docker, working there??

**Comment by tananga** [comment]
Thank you @alexkuc

**Comment by iraklisg** [comment]
@mydevfingers I have the same problem after deleting my organization
Have you found any solution for this?

**Comment by zxcvbnmone** [comment]
Cant create new DockerID with an email address that was associated with a deactivated DockerID. (old DockerID zaedooda777)

**Comment by codermrrob** [comment]
This is so frustrating. Followed Dockers own guidance to change username.
Now impossible to create a new account without a new email address.

The work around above does not work for me.

I get "Error from accounts" message when I click the "Resend Activation Email"

**Comment by croraf** [comment]
Followed the instructions to change the DockerID. After one week, still no confirmation that my old account has been deactivated.

Trash company. Will never purchase anything from them. This kind of behavior towards the users and ignoring of support requests for more than a year is completely unacceptable.

**Comment by ashauer** [comment]
Quite exactly 18 months now, actually. I have no words for it. **No matter how you contact them: no reaction at all. Absolutely embarrassing...**

**Comment by croraf** [comment]
I did manage to solve my issue. 

1. I went to "I forgot my password". After the mail came I set the new password and my account got active again.
2. I added a second mail, and set it as primary mail
3. I deleted the old mail
4. Now I was able to create a new account with the new Docker ID and my primary mail

Didn't have to wait a bit. Each step was applied immediately.

**Comment by sramanujan** [comment]
> Thats great. It worked for me too. However, I had created an organization name and deleted it, but that organization name is not available now for recreating. Does it take more time or a day to clear the deleted organization name from backend?
> 
> ![dockerhub_org_issue](https://user-images.githubusercontent.com/29328825/77613285-4f3d0300-6f65-11ea-8a96-8448a438e25f.PNG)

@mydevfingers were you able to find a solution? I'm stuck with a related problem, i.e needing a deactivated docker-id for use as an organization name.

**Comment by TrikkStar** [comment]
3 months with an open support ticket regarding renaming my account; radio silence.

**Comment by mbound** [comment]
How is not being able to delete or modify your own account acceptable?  It probably even violates GDPR!

**Comment by SaiPrabhathK** [comment]
I have encountered the same problem many of you have been discussing about. I was doing all this in the new MS Edge inPrivate  window i.e. deactivating and again signing up. After failing multiple times, I opened a normal (the same browser) window and tried it. Don't know the exact reason, but it worked and I was able to create a new account using the same email address. Hope this is helpful.

**Comment by technicallyjosh** [comment]
Hey all!

Hopefully this news will help some of you experiencing issues! We know that account deactivation has been a pain point for some time now and have greatly improved the account deactivation process here recently. Here are some recent changes.

- We updated deactivation to properly clear emails for accounts. ~ 1 month ago 
- We cleared any emails for previously deactivated users - I just applied this personally 15 min ago 😄 . If you couldn't sign up because of that... go for it!
- Repos are now removed from viewing, downloading, etc when deactivating. If yours is shown and should be hidden, please contact [support](https://hub.docker.com/support/).

As far as "GDPR" @mbound. We have a process within support to scrub data for a user or org. It requires the submission of a ticket at the moment. We do have plans to incorporate all of this during deactivation but are working on it.

Unfortunately right now, renaming orgs and users is on our long-term feature list but not happening in the immediate future as there are a decent amount of repercussions with repos and lots of other data. Trust me when I say, this is something we want to do, but aren't quite there yet.

I hope this information gives some unknown transparency on the subject. 😀

**Comment by nats12** [comment]
@technicallyjosh does Docker plan to clear out deactivated account emails frequently? I deactivated mine a couple days ago and I'm still unable to register for a new one. I can't even reactivate the account by requesting a password reset as the reset email won't arrive into my inbox. Any suggestions? Thanks!

**Comment by technicallyjosh** [comment]
> Does Docker plan to clear out deactivated account emails on a regular basis?

@nats12 Sorry to hear you ran into that issue again. If you deactivated your account and cannot sign up again with the same email, you'd have to contact support to clear that out as it shouldn't have happened. We'll have to look into what happened during your deactivation 🤷🏼 .

**Comment by nats12** [comment]
Thanks @technicallyjosh, I contacted support yesterday, hoping to hear back soon.

**Comment by ALENTL** [comment]
I have contacted the support. They said they would just like end up the issue by the end of August and now I have to wait to Aug to have a new docker account.

> Thanks @technicallyjosh, I contacted support yesterday, hoping to hear back soon.

Dude thanks for the comments and replies.

**Comment by theMyth721** [comment]
Just created a new account, decided to change the username, if only I had known better.
Most awful experience. Im not even getting a reset email anymore, I can't even create a brand new account with a new email

**Comment by ALENTL** [comment]
> Just created a new account, decided to change the username, if only I had known better.
> Most awful experience. Im not even getting a reset email anymore, I can't even create a brand new account with a new email

I am also having the same issue. They told that they would be fixing and be back available in the end of August. Like it's Spetember 14 today I haven't recieved any mails from them.

**Comment by nats12** [comment]
@ALENTL @theMyth721 try triggering the reset email/creating a new account from an incognito browser window. For some reason that worked for me

**Comment by lin-mt** [comment]
> Unfortunately right now, renaming orgs and users is on our long-term feature list but not happening in the immediate future as there are a decent amount of repercussions with repos and lots of other data. Trust me when I say, this is something we want to do, but aren't quite there yet.

Is there any update information on this?
