### ISSUE TITLE
Docker doesn't seem to recognize proxy settings.

### ISSUE THREAD

**Issue by miknoll** [docker/hub-feedback#1837]
## Problem description
Docker doesn't seem to recognize proxy settings.

I'm setting up a Swarm cluster in the lab for the developers and can't seem to get docker to recognize the proxy settings configured as described here: https://docs.docker.com/config/daemon/systemd/#httphttps-proxy

[root@XXXXXXXXX ~]# cd /etc/systemd/system/docker.service.d         
[root@XXXXXXXXX docker.service.d]# ls
http-proxy.conf  https-proxy.conf
[root@XXXXXXXXXX docker.service.d]# cat http-proxy.conf
[Service]
Environment=“HTTPS_PROXY=http://XXX.XXX.XXX.XXX:8080”

[root@XXXXXXXXXX docker.service.d]# cat https-proxy.conf
[Service]
Environment=“HTTPS_PROXY=https://XXX.XXX.XXX.XXX:8080”

[root@XXXXXXXXXX docker.service.d]# systemctl show --property=Environment docker
Environment=
[root@XXXXXXXXXX docker.service.d]# systemctl daemon-reload
[root@XXXXXXXXXX docker.service.d]# systemctl restart docker
[root@XXXXXXXXXX docker.service.d]# systemctl show --property=Environment docker
Environment=

I *ought* to see the environment variable for my proxy there so I can check why my pulls aren't working.  And despite following the linked doc it seems docker doesn't recognize that a proxy has been configured.

My VM specs are:
[root@XXXXXXXXXX docker.service.d]# cat /etc/redhat-release
CentOS Linux release 7.3.1611 (Core)
[root@XXXXXXXXXX docker.service.d]# docker version
Client:
 Version:           18.09.6
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        481bc77156
 Built:             Sat May  4 02:34:58 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.6
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       481bc77
  Built:            Sat May  4 02:02:43 2019
  OS/Arch:          linux/amd64
  Experimental:     false

**Comment by cowsrule** [comment]
This repository is for Docker Hub specific issues. Please visit https://forums.docker.com/ to discuss your issue.

**Comment by miknoll** [comment]
I believe this is a docker specific issue as the same proxy settings for the same proxy works just fine with other docker versions.

[https://www.cisco.com/c/dam/m/en_us/signaturetool/images/logo/Cisco_Logo_no_TM_Cisco_Blue-RGB_43px.png]
Michael Knoll
Engineer - Network
miknoll@cisco.com<mailto:miknoll@cisco.com>
Tel: +1 512 340 3576




Cisco Systems, Inc.
12515 Research Blvd., Building 4
AUSTIN
78759
United States
cisco.com
[http://www.cisco.com/assets/swa/img/thinkbeforeyouprint.gif]
Think before you print.
This email may contain confidential and privileged material for the sole use of the intended recipient. Any review, use, distribution or disclosure by others is strictly prohibited. If you are not the intended recipient (or authorized to receive for the recipient), please contact the sender by reply email and delete all copies of this message.
Please click here<http://www.cisco.com/c/en/us/about/legal/terms-sale-software-license-agreement/company-registration-information.html> for Company Registration Information.
