### ISSUE TITLE
Docker new account sing up/register "reCAPTCHA is required" problem.

### ISSUE THREAD

**Issue by Peipol** [docker/hub-feedback#1840]
I'm new to Docker and I want an account, but I can't sign up/register a new account.

There is a **reCAPTCHA is required** warning but I can't do anything with that.

![image](https://user-images.githubusercontent.com/39447385/60724539-b9f46d00-9f04-11e9-9d08-dfebc0456379.png)

**Comment by Peipol** [comment]
I have these errors in the console
![image](https://user-images.githubusercontent.com/39447385/60724761-430ba400-9f05-11e9-848c-44b91d855d5a.png)

**Comment by Peipol** [comment]
Apparently, in my country (Venezuela), the government blocked this "https://recaptcha.net/recaptcha/api.js?onload=onloadcallback&render=explicit"
![image](https://user-images.githubusercontent.com/39447385/60725358-e315fd00-9f06-11e9-8891-202f7724ec70.png)
So I tried with a free VPN to see if the page will load and it works 
![image](https://user-images.githubusercontent.com/39447385/60725558-66cfe980-9f07-11e9-8dd4-4c949cd6ef11.png)
And now I can see the reCAPTCHA with no problem. Yet I will not register an account using a free VPN
if anyone knows a secure free VPN please let me know, most of then are IP blocked.
![image](https://user-images.githubusercontent.com/39447385/60725424-fc1eae00-9f06-11e9-8aa4-ecff1aa0e50f.png)

**Comment by Peipol** [comment]
I found a VPN and now I have an account.

**Comment by jstifano** [comment]
Which was the VPN you used @Peipol ? Because I'm having the same trouble.

**Comment by Peipol** [comment]
@jstifano I don't remember the exact name of the VPN but it was one from google chrome web store

**Comment by fr3nch13** [comment]
Apparently this is still an issue. 
No vpn is blocking my access. 
I live in the USA. 
I’ve tried from my home Wi-Fi via cox. 
I’ve also tried on my phone via AT&T 5ge. 

All are failing.

**Comment by fr3nch13** [comment]
Nevermind.
The frontend is saying it's a captcha issue, but my issue was that the username was taken.
I'll post something over at #1889

**Comment by adamzovits** [comment]
This issue has just been observed, it looks like a misconfiguration, as the hub.docker.com site works as intended.
![20211105_130501](https://user-images.githubusercontent.com/22171237/140507744-b6733997-acbf-4a61-8a3d-d77ba3f6a94a.jpg)

**Comment by ingshtrom** [comment]
The misconfiguration is that we actually allow access to `index.docker.io` as a UI for Docker Hub. `hub.docker.com` is the canonical URL and should be used whenever interacting with Docker Hub through the website interface.
