### ISSUE TITLE
Organization repositories list returns 404 publicly

### ISSUE THREAD

**Issue by jlegido** [docker/hub-feedback#1841]
## Problem description
URL of organization repositories list returns 404 publicly:

https://hub.docker.com/u/kedu

However for logged in organization members returns the expected output, the repository list.

## Security Issues
N/A

## Issues related to running a container in a user's local environment or user's on-prem/cloud based cluster.
N/A

## Docker Hub Account Issues
URL of organization repositories list returns 404 publicly:

https://hub.docker.com/u/kedu

However for logged in organization members returns the expected output, the repository list.

### Account Activation Issues
N/A

### Password Reset Issues
N/A

### Deleting User Accounts and Organization Accounts
N/A

**Comment by j1elo** [comment]
The exact same issue is happening to Kurento and Elastest user pages:

* https://hub.docker.com/u/kurento
* https://hub.docker.com/u/elastest
* https://hub.docker.com/u/elastestbrowsers

I have also observed that this same problem is happening to some other random (but well known) users I've checked:

* https://hub.docker.com/u/pandoc
* https://hub.docker.com/u/libreoffice
* https://hub.docker.com/u/firefoxtesteng
* https://hub.docker.com/u/selenium

So I'm inclined to assume this is a global issue happening across lots of user profiles right now in Docker Hub.

**Comment by manishtomar** [comment]
Thanks for the report. We are looking into it.

**Comment by filipre** [comment]
Some additional errors I get which might help you to fix it (see issue https://github.com/docker-library/official-images/issues/6234)

<img width="836" alt="Screenshot 2019-07-05 at 18 38 55" src="https://user-images.githubusercontent.com/8502198/60838585-564f9580-a1cb-11e9-8bf5-e1784c9403c3.png">

<img width="1430" alt="Screenshot 2019-07-05 at 18 40 04" src="https://user-images.githubusercontent.com/8502198/60838586-564f9580-a1cb-11e9-894f-ab78e3a9e452.png">

**Comment by cowsrule** [comment]
This issue should be fixed. Please re-open if you continue to see this happen.
