### ISSUE TITLE
sudo apt update

### ISSUE THREAD

**Issue by nabeelhassan98** [docker/hub-feedback#1842]
![Screenshot from 2019-07-09 23-12-16](https://user-images.githubusercontent.com/49884022/60913568-21157700-a2a1-11e9-92af-c5b4bd5621c6.png)
Facing following issue while trying sudo apt update

Hit:1 http://security.ubuntu.com/ubuntu bionic-security InRelease
Ign:2 http://dl.google.com/linux/chrome/deb stable InRelease                                                                                         
Hit:3 https://dl.winehq.org/wine-builds/ubuntu cosmic InRelease                                                                                      
Hit:4 http://dl.google.com/linux/chrome/deb stable Release                                                                                           
Ign:5 https://download.docker.com/linux/debian bionic InRelease                                                               
Hit:6 https://download.docker.com/linux/ubuntu bionic InRelease                                         
Hit:7 http://pk.archive.ubuntu.com/ubuntu bionic InRelease             
Hit:8 https://download.docker.com/linux/ubuntu xenial InRelease        
Hit:10 http://pk.archive.ubuntu.com/ubuntu bionic-updates InRelease      
Err:11 https://download.docker.com/linux/debian bionic Release           
  404  Not Found [IP: 54.192.151.75 443]
Hit:12 http://pk.archive.ubuntu.com/ubuntu bionic-backports InRelease   
Reading package lists... Done                     
E: The repository 'https://download.docker.com/linux/debian bionic Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by cowsrule** [comment]
This repository is for Docker Hub specific feedback. Please visit https://forums.docker.com/ to discuss your issue.
