### ISSUE TITLE
Binary file execution on entrypoint in dockerfile is bugged

### ISSUE THREAD

**Issue by Sterilise** [docker/hub-feedback#1845]
### Here is a terminal log of my docker session, gateway is just a binary file. the docker file is very simple and can be reconstructed from looking at the console log
`
root@ip-172-**:/opt/temp# dir
Dockerfile  gateway
root@ip-172-**:/opt/temp# ls -lah gateway
-rwxr-xr-x 1 root root 51M Jul 15 23:27 gateway
root@ip-172-**:/opt/temp# docker build -t automaticgateway .
Sending build context to Docker daemon  70.38MB
Step 1/3 : FROM frolvlad/alpine-glibc
 ---> e8076a77c225
Step 2/3 : COPY ./gateway .
 ---> Using cache
 ---> bac21bfc575e
Step 3/3 : ENTRYPOINT ['./gateway']
 ---> Running in d977a9acee8f
Removing intermediate container d977a9acee8f
 ---> 9c2f823a9101
Successfully built 9c2f823a9101
Successfully tagged automaticgateway:latest
root@ip-172-**:/opt/temp# docker run -it --name automaticgatewaycontainer automaticgateway
/bin/sh: [./gateway]: not found`

i changed the line of code in the dockerfile from 
ENTRYPOINT['./gateway']
to
ENTRYPOINT["./gateway"] 
and it runs without the `/bin/sh: [./gateway]: not found` error

### Summary
using single quotes does not work when executing a binary file on the entrypoint of a dockerfile, but double quotes does?

**Comment by thaJeztah** [comment]
Correct; single quotes are invalid JSON, in which case it falls back to treating it as a shell command (`[` is a built-in in shell)
