### ISSUE TITLE
Build args are not passed when using Docker Hooks with multiple docker files

### ISSUE THREAD

**Issue by deepio** [docker/hub-feedback#1846]
## Problem description
Build args are not passed to a build that is not in the root directory of a repository, or from multiple builds. When pointing to multiple different docker files, they are not consumed. 

### Possibly related issue
* https://github.com/docker/hub-feedback/issues/891
* https://github.com/docker/hub-feedback/issues/1510

### Issue
```
#!/bin/bash
# hooks/build
# https://docs.docker.com/docker-cloud/builds/advanced/

echo "[***] Build hook running"
echo "[***] Building Test Image"

docker build \
  --build-arg VERSION=$(git describe --tags --always) \
  --build-arg COMMIT=$(git rev-parse HEAD) \
  --build-arg URL=$(git config --get remote.origin.url) \
  --build-arg BRANCH=$(git rev-parse --abbrev-ref HEAD) \
  --build-arg DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ") \
  --tag $IMAGE_NAME .

echo "[***] Building App2"

docker build \
  --build-arg BRANCHES="develop" \
  --tag d33pi0/docker-hooks:testing \
  --file ./App2/Dockerfile .
```
Builds the first app with the build args, but the args (BRANCHES) are not passed to the second build. It raises a warning instead, which I do not believe is intended behavior. 

```bash
Step 1/2 : FROM debian:latest
latest: Pulling from library/debian
5ae19949497e: Pulling fs layer
5ae19949497e: Verifying Checksum
5ae19949497e: Download complete
5ae19949497e: Pull complete
Digest: sha256:903779f30a7ee46937bfb21406f125d5fdace4178074e1cc71c49039ebf7f48f
Status: Downloaded newer image for debian:latest
---> 00bf7fdd8baf
Step 2/2 : RUN printenv
---> Running in b24535729eb9
HOSTNAME=b24535729eb9
HOME=/root
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PWD=/
Removing intermediate container b24535729eb9
---> 8c75074324e3
[Warning] One or more build-args [BRANCHES] were not consumed
Successfully built 8c75074324e3
Successfully tagged d33pi0/test-docker:testing
Pushing index.docker.io/d33pi0/test-docker:latest...
Done!
```

**Comment by hholst80** [comment]
Please post `App2/Dockerfile` as well

**Comment by deepio** [comment]
@hholst80 Ahh, as you can see in the build steps I had forgotten to include `ARG BRANCHES` in App2/Dockerfile.

**Comment by deepio** [comment]
@hholst80 
Actually the problem persist. In my larger project there is no dockerfile in the root directory. Because of this, all hooks get ignored when pointing the dockerfile location to a folder where one (any) exists. In my example, it only worked because there was a very little dockerfile in the root directory.
