### ISSUE TITLE
can't see dockerfile online

### ISSUE THREAD

**Issue by dataf3l** [docker/hub-feedback#1848]
When I go to this page, I can see the dockerfile:

https://hub.docker.com/r/nathannathannathan/omada-controller/dockerfile

However, when I go to this file I can't see the dockerfile:
https://hub.docker.com/_/rust

Why are you guys trying to hide the Dockerfiles?

Where is the Dockerfile Tab?
Why is it so hard to find?

**Comment by cowsrule** [comment]
We currently only display the Dockerfile tab for repositories that are setup to use the Docker Hub Autobuilds. Any repository that is not built in this way will not have the tab. We are looking at ways to expose this same information for other repositories.. stay tuned for updates.
