### ISSUE TITLE
Tag list should be sorted

### ISSUE THREAD

**Issue by jamesnetherton** [docker/hub-feedback#185]
Hope this isn't a duplicate (didn't find anything similar)....

The list of image tags should be sorted into some logical order. E.g if I view the list of Debian image tags I get:

```
experimental    51 MB
rc-buggy    51 MB
wheezy-backports    35 MB
wheezy  35 MB
7   35 MB
7.8 35 MB
unstable    51 MB
testing 51 MB
stretch 51 MB
stable-backports
```

It'd be nicer if they were sorted to help find things quickly. Especially for images that have a lot of tags.

OS: Fedora 22
Browser: Chrome 44.0.2403.125

**Comment by ChristopherBiscardi** [comment]
@jamesnetherton What sorting would be most useful to you? (alphabetical, recently pushed, size, etc).

**Comment by jamesnetherton** [comment]
@ChristopherBiscardi For me personally, default sorting alphabetically. With the added option of sorting on any of the other tag attributes in ascending / descending order. Anything that makes it easy to find stuff is good.

**Comment by warden** [comment]
+1 for alphabetic sorting.

**Comment by posita** [comment]
> What sorting would be most useful to you? (alphabetical, recently pushed, size, etc).

How about all of the above? The concept of multiple, sort-able columns has been around for quite a while, no?

**Comment by posita** [comment]
See also #415.

**Comment by jgkamat** [comment]
I would prefer sorted by most recently pushed (if you can't give us a sorting option :smile:), it makes more sense from a debug point of view (What if I want to delete that tag I just pushed (assuming we can delete tags eventually)).

**Comment by kristiehoward** [comment]
FYI @jgkamat https://github.com/docker/hub-feedback/issues/68 (ability to delete tags) was just deployed

**Comment by jgkamat** [comment]
Oh nice, thanks!

**Comment by sshipway** [comment]
+1 
I would prefer to be able to change the sort order between 'most recently pushed' and 'asciinumerically by tag'

Sorting ascibetically by tag is not good enough because 21.0 would cone before 3.1.  The tag sort function needs to be able to sort intelligently so that latest comes first, and tags are split on '.' and '-' as separators, and parts matching /(v(er)?)[0-9]+/ are compared numerically.  Might get a bit messy.

**Comment by warden** [comment]
Maybe [this](https://maven.apache.org/ref/3.0.3/maven-artifact/apidocs/org/apache/maven/artifact/versioning/ComparableVersion.html) will be a good reference impl.

**Comment by chromerobv** [comment]
would love to be able to sort by recently pushed. any headway on this?

**Comment by ducttapecoder-vt** [comment]
/bump

The the lack of a 'sort by' or 'limit # on page' drop down makes viewing tags exceedingly difficult. Manually browsing through 28 pages of [Confluence tags](https://hub.docker.com/r/atlassian/confluence-server/tags?page=28) with 6.15.3 (the second most recent version) being on the _last_ page is awful.

Sort options should be something like: alphabetical, age, 'asciinumerically' (as sshipway calls it), # of downloads, and some other attributes that don't seem to exist yet like FROM source or sub-tag (being able to filter for alpine seems _so freaking logical_ it's sad it doesn't exist yet).

A simple search would also be amazing. Why after _**THREE YEARS**_ are these features still not available?

**Comment by furiousassault** [comment]
Any update on this issue? Sorting by created timestamp might be very useful in self-maintained docker registry cleaning solutions.

**Comment by sshipway** [comment]
Well, declaring the ticket stale is not quite as good as actually providing the feature, though both seem to result in the ticket being closed
