### ISSUE TITLE
Too Many Requests (HAP429)

### ISSUE THREAD

**Issue by chewrocca** [docker/hub-feedback#1850]
Is it possible one of our IPs is blocked or rate-limted?  We're getting 429s.  I believe our public IP is 165.130.255.119.

**Comment by cowsrule** [comment]
Is it possible you are being blocked on a different IP? I do not see any requests from 165.130.255.119 receiving a 429.

**Comment by chewrocca** [comment]
Could you check 207.11.113.30 to see if this is the culprit?

**Comment by emakarov** [comment]
same problem from Bitbucket CI

**Comment by sha-liquidapps** [comment]
same issue with Bitbucket CI. Any workaround?

**Comment by haggaret** [comment]
Us as well - using Bitbucket pipelines and getting this quite freqently

**Comment by neill-ebx** [comment]
Still an issue for us - any update?

**Comment by mpepping** [comment]
Also an issue for us. When pulling a couple of images concurrently-ishh across ~30 nodes the better part ends in HTTP-429's.

**Comment by markgoddard** [comment]
We are having the same problem in the OpenStack Kolla project. I tried reaching the email address provided by @cowsrule, but got bounced. Presumably they moved on. Is there someone else who could help?

**Comment by manishtomar** [comment]
@markgoddard I believe number of concurrent requests must be pretty high for you to get 429. Please send an email to hub-support@docker.com referring this thread.
