### ISSUE TITLE
docker pull hangs for a long time

### ISSUE THREAD

**Issue by unclejack** [docker/hub-feedback#1851]
The Hub seems to have some kind of problem. `docker pull alpine` takes approximately 3 minutes to complete. It appeared to be a problem related to the CDN at first. An analysis of the TCP traffic revealed the following pattern:
some requests are made to ec2-34-232-31-24.compute-1.amazonaws.com
long delay
some more requests are made to ec2-34-199-40-84.compute-1.amazonaws.com
long delay
the layers are being pulled from 104.18.123.25

**Comment by unclejack** [comment]
The download of the manifest takes 1m35 seconds. The server does something for about 1m35s after the initial connection was established. Something is certainly wrong on the server side.

**Comment by unclejack** [comment]
This is still not fixed. Is there something else I can do to help sort this out sooner?

**Comment by manishtomar** [comment]
@unclejack Can you run this script and post the logs?
```
#!/bin/bash
# call it as <script> library/alpine blobs/sha256:0503825856099e6adb39c8297af09547f69684b7016b7f3680ed801aa310baaa
repo=$1
url=$2
token=$(curl "https://auth.docker.io/token?service=registry.docker.io&scope=repository:$repo:pull" | jq -r .token)
curl -v https://registry-1.docker.io/v2/$repo/$url -H "Authorization: Bearer $token" -L > /dev/null
```

**Comment by unclejack** [comment]
@manishtomar: Please take a look at the attached log.

I've noticed that it always takes exactly 1m35 seconds. This delay appears to be fixed.

[debug.log](https://github.com/docker/hub-feedback/files/3421822/debug.log)

**Comment by manishtomar** [comment]
> This delay appears to be fixed.

@unclejack Does this mean it is not taking 1m35s anymore? Is it faster?

**Comment by unclejack** [comment]
@manishtomar: No, it's just that the delay is always the same - 1m35 seconds.

**Comment by manishtomar** [comment]
@unclejack From the logs it looks like the CDN is immediately completing the request. Can you try a few things?
1) Try downloading other blobs using the script
2) Check your Internet settings to make sure other sites/services are downloading with decent speed

**Comment by unclejack** [comment]
@manishtomar: The problem isn't the CDN. It's the Docker registry which needs 1m35 to make the redirect.

**Comment by unclejack** [comment]
The Internet connection is fine.

**Comment by manishtomar** [comment]
> @manishtomar: The problem isn't the CDN. It's the Docker registry which needs 1m35 to make the redirect.

Oh. Interesting. Apologies I didn't realize this is what you meant earlier. That seems really strange. Can you try running the script one more time except without `-L` flag to avoid the redirect to make sure the time taken? Also, the IP seems to be 188.26.58.211. Is this correct?

**Comment by unclejack** [comment]
@manishtomar: Please remove the IP address and don't post any again. I've reported this issue because these services are used by many. It wasn't consent to have IP addresses posted on a public website.

I've attached the log of the run without the redirect.
[debug-no-redirect.log](https://github.com/docker/hub-feedback/files/3423792/debug-no-redirect.log)

**Comment by manishtomar** [comment]
@unclejack It is difficult to track down individual requests due to the sheer volume. To discuss this further with possibly sensitive info, could you please send an email to support@docker.com and link this ticket? I checked our system and the redirect happens within few ms. So I am not sure why it is taking >1m to get the redirect back. Please do try on different machines with different network settings to help root cause this.

**Comment by unclejack** [comment]
@manishtomar: I'll close the issue because you've confirmed it's not caused by the Hub. It's something to investigate and reach out when I have more bits of information about this problem. Thanks for looking into this.
