### ISSUE TITLE
Malware report

### ISSUE THREAD

**Issue by kapitanov** [docker/hub-feedback#1853]
I would like to report a couple of malware images on Docker Hub:

* [hzulu/hauto](https://hub.docker.com/r/hzulu/hauto)
  Contains a malware cryptocurrency miner, IP scanner (scans IP range for unsecured docker API), SSH and TOR
* [jzulu/xauto](https://hub.docker.com/r/jzulu/xauto)
  Contains a malware cryptocurrency miner with some kind of remote control and SSH server.

There are similar reports: #1807 #1809.

**Comment by manishtomar** [comment]
Thanks for the reports. These accounts have been deactivated.

**Comment by idanr1986** [comment]
also from the same campaign zoolu2/jauto is still active

**Comment by manishtomar** [comment]
Thanks. That account has been deactivated.

**Comment by idanr1986** [comment]
hzulu/hauto 
hzuzu/hauto
still active

**Comment by manishtomar** [comment]
Thanks. They've been deactivated.
