### ISSUE TITLE
User must be admin in github repo to link to docker

### ISSUE THREAD

**Issue by jrjohnson** [docker/hub-feedback#1854]
Followed the directions at https://success.docker.com/article/why-cant-i-see-my-github-repositories-when-creating-a-new-automated-build several times, but there is a hidden step that the user must be an 'admin' user in the github repo. 

If this is a requirement I can't find that anywhere in the docs. 

It would be better if the user could have only 'read' permission on the github end that way a service account compromise would by much easier to contain. Requiring admin makes the service account user too powerful.

**Comment by nicolagi** [comment]
Got here with the same issue. Why are admin rights required?
