### ISSUE TITLE
Can not activate account or reset password

### ISSUE THREAD

**Issue by brian-kane521** [docker/hub-feedback#1856]
I never received an email for activating my account, and retried several times. After contacting support and waiting a few days, I hadn't heard back so I tried the reset password link with the email registered. This isn't sending emails either, and another week has gone by with no response from support.

**Comment by cowsrule** [comment]
What is your Docker ID?

**Comment by brian-kane521** [comment]
I believe it is doraebuilder or doraedockerhub, sorry I can't remember exactly. The email is dockerhub@dorae.com

**Comment by cowsrule** [comment]
Please re-try requesting a password reset (or validation) email. Your email server originally bounced the email that we sent as the address appeared to be invalid.

**Comment by brian-kane521** [comment]
Thank you!
