### ISSUE TITLE
Please whitelist company IP from blacklist 

### ISSUE THREAD

**Issue by eagly13** [docker/hub-feedback#1858]
Hello all,

We use Docker Images in our CI in order to build our product. Yesterday, we got the you are blocked message,
![image](https://user-images.githubusercontent.com/10497389/62363396-ec0ae600-b527-11e9-92a6-10d0cffb73b8.png)
and from then on we cannot pull any images from docker hub.

We replaced the images with ones in our private registry in order to continue builds but we need to get some new ones and have a really hard time doing this.

Our outgoing IP is 217.114.160.36

Could you please whitelist it?

**Comment by manishtomar** [comment]
As the error clearly states the IP is blocked since it is originating from Iran and Docker being a US company has to comply to export control regulation. We cannot unblock it. Sorry about it.

**Comment by eagly13** [comment]
> As the error clearly states the IP is blocked since it is originating from Iran and Docker being a US company has to comply to export control regulation. We cannot unblock it. Sorry about it.

Hello, how is this IP detected as originating from IRAN when it clearly comes from Ireland?

https://www.ip-tracker.org/locator/ip-lookup.php?ip=217.114.160.36

![image](https://user-images.githubusercontent.com/10497389/63504499-60f38f00-c4da-11e9-9083-10b8824cb1f9.png)

**Comment by eagly13** [comment]
@manishtomar Any update?

**Comment by eagly13** [comment]
@binman-docker  thanks for the info. I just made a correction request to Maxmind.

**Comment by eagly13** [comment]
Hello, 
Maxmind has corrected its GeoIP information but we still cannot pull from docker hub

![image](https://user-images.githubusercontent.com/10497389/66560722-9b83ba80-eb60-11e9-98f1-9e0bc12e2644.png)

**Comment by binman-docker** [comment]
According to the database we use (not the "Precision" product demo'd on their website), it's still registered to Iran. I've filed a ticket with Maxmind asking what's going on and whether they can update the database we use based on your correction request.

**Comment by binman-docker** [comment]
Maxmind advised the following:

> I am unfortunately unable to locate a correction request for 217.114.160.36. It is therefore recommended that a new correction request be submitted. Corrections for our GeoIP data should be submitted directly to our corrections team using the form at https://support.maxmind.com/geoip-data-correction-request/

>It may help our corrections team identify the issue if the "Other" text box on the form reads something along the lines of: The 'registered_country' appears to be wrong in that it locates to Iran

**Comment by eagly13** [comment]
Hello, 

Maxmind answered us:

> Hi Ioannis,
> We updated the records for this IP. The registered country should be updated in next Tuesday's build of the database. Please let Docker know that the registered country should be Ireland. The change should have happened sooner, but there was an issue on MaxMind side.
> Best Regards,
> MaxMind, Inc.

**Comment by binman-docker** [comment]
By next Tuesday do they mean the 22nd? We pick up changes daily so you should see yourself unblocked soon after they fix their database.

**Comment by eagly13** [comment]
@binman-docker  that's probably what they meant. I guess we will know by tomorrow.

**Comment by eagly13** [comment]
@binman-docker  the issue is resolved! At last

**Comment by binman-docker** [comment]
Good to hear! Sorry it dragged on so long.
