### ISSUE TITLE
Builds hung / won't cancel

### ISSUE THREAD

**Issue by johnvcoleman-w24** [docker/hub-feedback#1859]
Started yesterday 8/5

Automatic builds triggered by Github push not recognizing the build has finished. Build finishes in a few minutes, but build status shows "building" for hours.

Attempts to cancel the hung builds finally register with the system after 4-5 requests, but once the system acknowledges the cancel request nothing happens, for hours.

The hung builds are blocking the next build from starting.

**Comment by ryan-morris** [comment]
having this exact issue, _again_, today.

**Comment by jpfeuffer** [comment]
Same here. Dockerhub became unusable. It takes ages until the logs show (usually first after the build already finished) and then it takes ages until the system recognizes the finished build. It took 4 hours!! for a 30 mins build.

**Comment by johnvcoleman-w24** [comment]
Yep, started happening again yesterday.

**Comment by fippli** [comment]
Same for me. My image built in 1min but has been stuck for 3h...
