### ISSUE TITLE
Failed automated build will not cancel

### ISSUE THREAD

**Issue by bradbeck** [docker/hub-feedback#1860]
## Problem description
The following failed image build will not cancel.
https://cloud.docker.com/repository/registry-1.docker.io/bradbeck/nexus-https/builds/dab882e1-b919-4b4a-95d0-c00836e07ebf

**Comment by andrewchernow** [comment]
Having same problem. Canceling forever. Not sure why this issue #1352 was ever closed.

**Comment by ryan-morris** [comment]
same here

**Comment by andrewchernow** [comment]
![Screen Shot 2019-08-06 at 3 06 10 PM](https://user-images.githubusercontent.com/1630312/62568770-d9601c00-b85b-11e9-9e53-0bacddc2972b.png)

logs already show me it failed and I know why. Sooooo, what gives?

**Comment by bradbeck** [comment]
Seems to have finally cancelled after 6 hours.

**Comment by pytely** [comment]
Same issue
