### ISSUE TITLE
Getting Service Unavailable

### ISSUE THREAD

**Issue by vjcubas** [docker/hub-feedback#1863]
docker: Error response from daemon: Get https://registry-1.docker.io/v2/: Service Unavailable

I was able to SingIn using the browser - is there an outage or perhaps maintenance beeing done?

**Comment by manishtomar** [comment]
Our metrics didn't notice any disruption. We also didn't notice errors reported from anywhere else. I am going to close this for now. Feel free to let us know if this problem continues.
