### ISSUE TITLE
hello-world documentation is empty

### ISSUE THREAD

**Issue by wglambert** [docker/hub-feedback#1867]
The docs tab for the [hello-world](https://hub.docker.com/_/hello-world?tab=description) official-image is empty

https://github.com/docker-library/hello-world/issues/59#issuecomment-512975815
>If you go to https://hub.docker.com/v2/repositories/library/hello-world/, you can see that `full_description` includes the appropriate markdown from https://github.com/docker-library/docs/blob/master/hello-world/README.md, so this looks like a Docker Hub JavaScript/rendering issue.

Also the downloads counter is at 2.6K, whereas on the [search-preview](https://hub.docker.com/search?q=hello-world&type=image) it's shown as 10M+

**Comment by cowsrule** [comment]
Thanks for your report - we will look into this next week.

**Comment by meticulous-dft** [comment]
This is fixed now.
