### ISSUE TITLE
Unable to convert user account to organization.

### ISSUE THREAD

**Issue by ginko** [docker/hub-feedback#1870]
## Problem description

When trying to convert a user account to an organization account and providing the correct docker ID/username I'm getting the following error **Please enter a valid Docker ID** The user account in question is not part of any organizations.  

Any help is greatly appreciated.

<img width="1242" alt="Screen Shot 2019-08-28 at 3 14 02 PM" src="https://user-images.githubusercontent.com/183611/63885898-512aed80-c9a7-11e9-8b8a-e8f6abdce082.png">

**Comment by cowsrule** [comment]
Hi @ginko - we are unable to reproduce this behavior on our end. We have an update to this part of the UI coming out in a week or so which may help fix your issue. You may also consider creating (and email verifying) new Docker IDs for the org and owner and trying with fresh accounts. There may also be additional error information in the browser developer console in the network request. If so, please share as it may help us understand what is happening here. I will try to ping this thread once the UI update is released.

**Comment by ginko** [comment]
I did create a brand new account and verified the email. The developer console in Chrome is showing the following error when I try to use the new Docker ID. 
<img width="1427" alt="Screen Shot 2019-08-29 at 8 49 22 PM" src="https://user-images.githubusercontent.com/183611/63986117-9717ac80-caa0-11e9-82dc-7ca5ade4c8f6.png">

**Comment by VeNoMouS** [comment]
ive got the same issue, ive opened a support ticket... man the amount of people complaining about the same things on the docker forums is insane.... have yet seen an actual posted resolve for this...

**Comment by siarheikarneichyk** [comment]
@VeNoMouS what error are you getting? I just checked and everything works well for me =/ Could you please provide some screenshots, it could help us to reproduce the issue.

**Comment by VeNoMouS** [comment]
Help desk resolved it for me.... even though a sub org had been deleted , it hadn’t really been deleted , I emailed docker support who fixed it , I can supply you with ticket number if you want?
