### ISSUE TITLE
Make manage repository links redirect to public view

### ISSUE THREAD

**Issue by Enteee** [docker/hub-feedback#1872]
## Feature description
Currently links to the manage repository page redirect to the index page when not logged in. Make `manage repository` links automatically redirect to public view for not auhorized users.

So if i am not logged in, this: 
`https://cloud.docker.com/u/enteee/repository/docker/enteee/pyinstaller-windows`
should automatically redirect to:
`https://hub.docker.com/r/enteee/pyinstaller-windows` 

It has happened in the past that I accidentally posted the private link. The two pages look very similar, and this fallback mechanism would then at least make those private links somewhat usable.

**Comment by manishtomar** [comment]
Thanks for the report. We are working on a change where this will not be a problem. Stay tuned for UI updates in next 1-2 months.

**Comment by Enteee** [comment]
bad bot!
