### ISSUE TITLE
Not receiving activate email for new account

### ISSUE THREAD

**Issue by OlegoO** [docker/hub-feedback#1877]
Hi all,

Hope this is the correct place for this.

I have registered today (I think) but didn't get the email to activate my account so I can't login. I have tried the feature for lost password that resends this email but no luck so far.

My account ID is ozhvirtowaycom

Thanks in advance!

**Comment by bytegyver** [comment]
We've got that same issue.

We signed up 2 weeks ago, but received no activation Mail. The workaround with resetting the password and activating the account through that, did not work for us either. We requested support through dockers ticket-system, but aside from the confirmation, that the ticket was opened, we received no further assistance.

Account ID: bytegyver

If anyone could help, we'd highly appreciate it.
