### ISSUE TITLE
Some suggested improvements for the new tag UI

### ISSUE THREAD

**Issue by joshsleeper** [docker/hub-feedback#1878]
## Problem description
Although the ([recently announced](https://blog.docker.com/2019/09/introducing-docker-hub-improved-tag-ux/)) fancy new image tag viewer is a substantial improvement already, it still has a few papercuts. The two that bother me the most at the moment are:

1. the list of architectures isn't consistently sorted between images, making it extremely hard to look at the same arch across different tags and quickly parse the differences (or similarities!) between them
    - example: I wasn't sure if the current `rust:slim` image is equivalent to `rust:slim-stretch` or `rust:slim-buster`, so I tried looking at the top hash of each list. drat, all different arches at the top for some reason!
![image](https://user-images.githubusercontent.com/849941/64573445-525e0200-d339-11e9-816b-19faad46a7f7.png)

1. relating to my example for the first issue, it'd be nice if each tag displayed (or could present in some way) a list of all other tags it's equivalent to! That way instead of me comparing hashes, the system could just inform me that `rust:slim` and `rust:slim-buster` are the same.
    - ... as well as `rust:1.37.0-slim`, `rust:1.37.0-slim-buster`, `rust:1-slim`, etc.

**Comment by meticulous-dft** [comment]
Hi, thanks for the suggestions. We are sort tags based on architecture, which should make it easier to check and compare tags.

We will be looking into how to present the equivalent tag in an intuitive way.
