### ISSUE TITLE
Begging for a two-factor authentication update...

### ISSUE THREAD

**Issue by jakejarvis** [docker/hub-feedback#1879]
I know this is a duplicate of #358 from _four years ago_, but an update would be much appreciated, especially after the breach — speaking for over 100 commenters. :)

Moving to GitHub Packages or GitLab in the meantime, which is unfortunate.

![giphy](https://user-images.githubusercontent.com/1703673/64887975-d49b3e80-d637-11e9-92b9-cac9aa5b22aa.gif)

**Comment by comunitius** [comment]
Hello Docker folks. It's me again. I wrote in https://github.com/docker/hub-feedback/issues/358 and also tried on twitter as well (https://twitter.com/comunitius/status/1170450304849965056). No answer. We are talking about issue 358... 1521 issues ago!

What really bothers me is the lack of communication and responses in https://github.com/docker/hub-feedback/issues/358, (but hopefully not this issue).

All we are asking is for a response. . @meticulous-dft said that 2fa would be available in June. We all understand that projects are always underestimated (there's science and data one this). It's fine if it isn't ready!, **but the lack of communication is truly the problem! not the fact that 2fa is not ready**. A simple response would suffice to show the community and your customers that you actually care.

Here are some examples of a simple response that I think would make us happy or at least less frustrated:
  - "hey folks, sorry, we underestimated and this is not ready, it's going to take us X more months to complete"
  - "Sorry folks, we know we mentioned June, but in fact there are some other priorities and this is going to take a while"
  - "We are a little behind on some other projects, but this is a priority in our roadmap!"

Not sure about other issues, but I'm guessing there is not that much responses. **I'm also begging... for more communication...**

**Comment by comunitius** [comment]
@jakejarvis here is a good article about alternatives due to the fact that docker has no 2fa. https://news.ycombinator.com/item?id=19763795

**Comment by meticulous-dft** [comment]
Hello, it is me again. Very sorry for all the confusion from my premature comment. I underestimated and take full responsibility.

2FA is always high priority. That being said, we will have a release soon to pave the road for it,  then will try our best to deliver as fast as we can. I understand the lack of communication is problematic, but really want to have concrete progress before sharing, so i don't make the same mistake again.

I use docker hub every day, and also feel the pain of lacking 2fa. Please give us some more time to correct this. Thanks very much for your patience.

**Comment by comunitius** [comment]
Thank you for answering @meticulous-dft ! much appreciated.

Would be awesome if you keep the communication flowing and let us know once you have something to share 😄

**Comment by dylmye** [comment]
@meticulous-dft we would appreciate some transparency into what's going on here, what's causing this hold-up, the lack of response after the breach, is that possible? Thank you.

**Comment by cowsrule** [comment]
Appreciate the interest and patience! Please see our latest blog post for some great news: https://www.docker.com/blog/designing-docker-hub-2fa/

We are all very excited to have this feature available, please keep making noise about issues that matter.
