### ISSUE TITLE
Improve Docker Hub tag view for multiple Windows OS versions

### ISSUE THREAD

**Issue by StefanScherer** [docker/hub-feedback#1882]
## Problem description
The new Docker Hub view is very good to see which platforms are supported by a multi-arch image.

<img width="973" alt="docker hub stefanscherer/whoami:1.9.4" src="https://user-images.githubusercontent.com/207759/64921484-05a87a00-d7c4-11e9-9d2e-cfecffad767d.png">

But, for Windows it's still not showing which Windows OS version a manifest list supports.

This would be a great enhancement for Windows users that struggle with finding matching host OS version with the container image version.

Phil Estes' tool already lists this information:

```
$ docker run --rm mplatform/mquery stefanscherer/whoami:1.9.4
Image: stefanscherer/whoami:1.9.4
 * Manifest List: Yes
 * Supported platforms:
   - linux/amd64
   - linux/arm/v6
   - linux/arm64
   - windows/amd64:10.0.17763.737
   - windows/amd64:10.0.14393.2551
   - windows/amd64:10.0.16299.1087
   - windows/amd64:10.0.17134.1006
   - windows/amd64:10.0.18362.356
```

I suggest an additional column that can display the OsVersion if available.

**Comment by siarheikarneichyk** [comment]
Thanks for you comment Stefan. We added OS version for windows.

![image](https://user-images.githubusercontent.com/50419668/65348278-9650d280-db95-11e9-8133-9f613a1a78b4.png)

**Comment by StefanScherer** [comment]
Awesome! Thanks @siarheikarneichyk that makes a whole difference. A great improvement for Windows users.
