### ISSUE TITLE
Can’t recover my username after failed attempt to convert to organization 

### ISSUE THREAD

**Issue by frenchzed** [docker/hub-feedback#1883]
Hi,

For some reason I just cannot get support attention on my issue (web form and ticket opened more than a week ago with absolutely no response so far) so I’m trying here...

I tried to convert my username into an organization and it failed for some reason. There was no error but the page where you do so was just seamingly unresponsive when submitting the form. I had other things to do and decided to retry later. 

When I came back to retry, docker hub would refuse my username and password. I tried to reset my password but would never receive the reset password email. I finally tried to recreate my account but it obviously says that the username is taken...

So currently, my username is in sone sort of limbo and I just don’t have any obvious way to recover it. 

How can I recover my username back or get any form of helpful support for that issue ?

Thanks,

**Comment by meticulous-dft** [comment]
Hi, what is your docker username?

**Comment by frenchzed** [comment]
@meticulous-dft, my username is unryo (the one I lost access to)

**Comment by meticulous-dft** [comment]
Looks like `unryo` is now an organization. Can you create a new docker id for yourself, i can add it to the owners team in the `unryo` org.

**Comment by frenchzed** [comment]
Created unryoadmin already, can you add this one ? Thanks.

**Comment by frenchzed** [comment]
Just got the email and I can now access it ! Thanks a lot @meticulous-dft !
