### ISSUE TITLE
Cannot add automated builds (both Chrome and Firefox won't work, haven't tried others)

### ISSUE THREAD

**Issue by bs-thomas** [docker/hub-feedback#1884]
## Problem description

I am on a free account, have around 2x automated builds currently.  Clicked on automated builds to add one more.  After adding it, no error messages of any sorts, but the new automated build was not added for some odd reason.

The video should explain it all.  
http://cdn.beamstyle.com.hk/docker-hub-bug.webm

The branch and folder I'm targeting the build at does indeed exist, and verified on the repository end already.

Was wondering if it's my config problems, or if this is a bug?

Any help is greatly appreciated!

**Comment by bs-thomas** [comment]
#1789 Not sure if this is related, but the behavior looks similar.  A regression perhaps?

**Comment by bs-thomas** [comment]
Hello guys, hope you don't mind my friendly nudge here.

I was wondering if anyone is also experiencing this issue?  As I'm pending on a few tasks, I'm keen to know if this was a problem on my end, or if many others are also experiencing this issue?

Would anyone be able to help and shed me some light here?

Thanks and much appreciated on any assistance!!

**Comment by bs-thomas** [comment]
Sorry for my directness here, but nobody could comment on this?
Nobody ever experiencing this problem?

I felt left out here, hope someone could leave a comment or something.

Thank you again!

**Comment by bs-thomas** [comment]
@manishtomar Hello there, sorry to tag you in here.  I just wanted to grab some attention, and see that you're active on other issues.  I need some assistance on here.  Is the support supposed to be a paid service?  If so, please let me know so I can arrange and get support on this sooner.  Thank you very much!

**Comment by manishtomar** [comment]
@bs-thomas It could be a problem in frontend. Can you check the network inspector and see if API response to add a new build rule was 200 OK? I suspect it is failing but frontend is not giving feedback.

**Comment by bs-thomas** [comment]
@manishtomar First off, thank you very much your kind assistance in responding to my tag.  Really happy and really appreciate it!

Please see my further investigation below:

=====

It seems to give 202 and 200 for two requests.  Don't see any obvious failures.
http://cdn.beamstyle.com.hk/docker-hub-bug-2.webm

=====

To investigate further, I did another request and inspected the responses (so the uuid's below may not correspond to the video above).

From my understanding, I think:
1. 202 request contains my changes
URL: https://cloud.docker.com/api/build/v1/beamstyle/source/7277ad90-8454-4995-8e39-8f7866200c7d/)

2. 200 request is the AJAX to get the builds for my repository 
URL:https://cloud.docker.com/api/build/v1/beamstyle/setting/?buildsource=%2Fapi%2Fbuild%2Fv1%2Fsource%2F7277ad90-8454-4995-8e39-8f7866200c7d%2F

=====

**202 Request**

In the 202 request, I spot my changes are in fact embedded inside the payload.
![image](https://user-images.githubusercontent.com/2464920/65557699-d5e93700-df66-11e9-9f92-0c0bf5e1949a.png)

Here is the 202 response (i suppose item 25 is the new item):
![image](https://user-images.githubusercontent.com/2464920/65557861-560f9c80-df67-11e9-9085-090ca8803d5d.png)

It does seem like the response reflected my changes.

=====

**200 Request**

What is problematic to me, seems like is this request that follows.

While retrieval is 200 OK.
![image](https://user-images.githubusercontent.com/2464920/65558253-94f22200-df68-11e9-8a12-176adde77fa6.png)

The response seems to hint that the LIMIT is 25, and OFFSET is 0!  (The new item I added is item 26, which in order to display it, will request OFFSET 1)

![image](https://user-images.githubusercontent.com/2464920/65558300-b8b56800-df68-11e9-97de-bbd257d63365.png)

But the odd thing is, in the 200 request URL, there isn't any parameter to specify the "OFFSET".  This is the URL format:

https://cloud.docker.com/api/build/v1/beamstyle/setting/?buildsource=%2Fapi%2Fbuild%2Fv1%2Fsource%2F7277ad90-8454-4995-8e39-8f7866200c7d%2F

=====

@manishtomar Could the above be the ultimate reason to why this is not showing up?  Because there is no pagination in the automated builds interface?

**Comment by manishtomar** [comment]
@bs-thomas Thank you for your help in debugging. I suspect that either backend has a limit of 25 build rules but does not error. Or backend stores it but the API and frontend have limitation of returning/showing only 25 items. We're working on rewriting builds UI and in the process have fixed issues. Please wait for a few weeks for updated UI to rollout.
