### ISSUE TITLE
DockerHub proceeds to push a new image even though the build failed with Error 3

### ISSUE THREAD

**Issue by aivanova5** [docker/hub-feedback#1885]
## Problem description
After running validation, the system produces an error 3, however dockerhub built and pushed the images despite the error. 

Image for reference: 
~~~
Successfully built 1850b5f377fe
Successfully tagged gridlabd/slac-master:latest
Pushing index.docker.io/gridlabd/slac-master:latest...
~~~
Source code: https://github.com/dchassin/gridlabd

**Comment by manishtomar** [comment]
Can you link the build logs?

**Comment by aivanova5** [comment]
https://cloud.docker.com/u/gridlabd/repository/registry-1.docker.io/gridlabd/slac-master/builds/7bcbf058-4264-4cea-b1ea-48df8493b079
