### ISSUE TITLE
Docker new account sing up/register "reCAPTCHA is required" problem.

### ISSUE THREAD

**Issue by slyubski** [docker/hub-feedback#1889]
Same as #1840
09/30/2019  tried to register for docker ID. 
I am  at MAC. Tried bot CHROME an SAFARI.

By default on CHROME  when clicking  I AM NOT ROBOT is says RE CAPTCHA is required and nothing happens.

An SAFARI  when clicking I AM NOT A ROBOT the pictures pop up.
I found all LIGHTS  and  STAIRS , repeated  5 times but it still does not work and keep saying 
RECAPTCHA is required.  
I do not understand the speculations about VPN t the original #1840 case.

**Comment by samuelmullin** [comment]
I have this same issue connecting from Canada.  No errors in the console, but can't get past the recaptcha.  Same issue with both Firefox (71.0b1 (64-bit)) and Chome (77.0.3865.120).   Ad blockers disabled in both cases.  Using Windows 10.

**Comment by fr3nch13** [comment]
My issue was that the username was taken. I was able to see the error message in the web console in Chrome, but it wasn't showing up in the DOM/user view.

**Comment by samuelgjfarquhar** [comment]
i live in UK and still cant even sign up, getting caught at "reCAPTCHA is required" problem.

**Comment by MarkNelson86** [comment]
Canada, same problem.
