### ISSUE TITLE
Image Rendering Issue: Not possible to pass style="max-width:100%;"  in an img src tag

### ISSUE THREAD

**Issue by scyto** [docker/hub-feedback#1890]
## Problem description

When using standard image markdown syntax large images are not scaled within border of frame.  for example this should not render outside border of document frame
![Image of HDSentinel](https://github.com/scyto/hdsentinel/blob/master/images/hdsentinel.png)

When using img src tag same issue occurs, adding style="max-width:100%;"  in an img src tag should fix, however the hub readme.md rendering engine is ignoring this and discarding it.

This should fix issue *if* all tags were being passed:

\<img src="https://github.com/scyto/hdsentinel/raw/master/images/hdsentinel.png" style="max-width:100%;">

however the style tag is being removed, if i use F12 to hard force the code change on docker hub description page - image renders correctly.

Either apply max-width automatically in the same manner git hub does.
Or
Allow full passthrough of <img src= > tags like style

**Comment by scyto** [comment]
compare
https://github.com/scyto/hdsentinel/blob/master/README.md
and
https://cloud.docker.com/u/scyto/repository/docker/scyto/sentinel

**Comment by caronc** [comment]
Found [this article on Stackoverflow](https://stackoverflow.com/questions/14675913/changing-image-size-in-markdown) suggesting another way of sizing the image using the markdown syntax and this also doesn't work. Quoted:

> With certain Markdown implementations (including Mou and Marked 2 (only macOS)) you can append =WIDTHxHEIGHT after the URL of the graphic file to resize the image. Do not forget the space before the =.
> 
> `![](./pic/pic1_50.png =100x20)`
> 
> You can skip the HEIGHT
> 
> `![](./pic/pic1s.png =250x)`

It would be cool to even consider this option if you can't do the in-line html choice @scyto suggested.  Ideally auto-resizing it like GitHub does sounds like the best solution all around.

**Comment by seriousm4x** [comment]
this is still an issue
