### ISSUE TITLE
Remove IP blacklist entry

### ISSUE THREAD

**Issue by limenet** [docker/hub-feedback#1895]
Hello,

Could you please remove `62.12.149.190` from the blacklist for hub.docker.com and registry-1.docker.io? The IP in question was in use until early 2019 by a standard LAMP server which was not accessing Docker infrastructure and now the IP belongs to a development/staging server for a Docker environment and we'd appreciate if you could remove it from the blacklist.

Please let me know if there's anything else we can do to help.

Thank you!

**Comment by cowsrule** [comment]
We have no record of this IP address.
