### ISSUE TITLE
Docker hub isn't working

### ISSUE THREAD

**Issue by freester1** [docker/hub-feedback#1897]
Steps to reproduce:
```
$ docker pull ubuntu:latest
Error response from daemon: received unexpected HTTP status: 503 Service Unavailable
```

**Comment by tomfi** [comment]
Same here, can't push any image. getting `503 Service Unavailable`

**Comment by hbolzan** [comment]
Same here when trying to push an image. `received unexpected HTTP status: 503 Service Unavailable`

**Comment by efranelas** [comment]
Same here
![Captura de tela de 2019-10-15 14-03-24](https://user-images.githubusercontent.com/3271182/66852957-9190fb80-ef54-11e9-9461-3ce3c7591f34.png)

**Comment by spinpay-git** [comment]
Same here

**Comment by Ben-Epstein** [comment]
+1

**Comment by saiyam1814** [comment]
+1

**Comment by Emily-Thomas** [comment]
Same here as well. 
<img width="687" alt="Screen Shot 2019-10-15 at 1 04 22 PM" src="https://user-images.githubusercontent.com/25155957/66853189-ab2e4500-ef4c-11e9-87e5-631f9166c794.png">

**Comment by michaeljoy** [comment]
```Error: Got error when attempting to fetch image version from registry: Got bad response from registry: 503 Service Unavailable```

**Comment by hugorut** [comment]
+1

**Comment by JeremyPlease** [comment]
The status page shows this incident: 
https://status.docker.com/pages/incident/533c6539221ae15e3f000031/5da5fc78c7b1c11cd8603721

Godspeed to the engineers fixing the problem!

**Comment by wayne-t** [comment]
+ 1

**Comment by MihanixA** [comment]
```
(venv) Mikhails-Mac-Pro:trading msitnikov$ docker pull postgres:11
Error response from daemon: received unexpected HTTP status: 503 Service Unavailable

```
+1

**Comment by Razikus** [comment]
+1

**Comment by sicKitchen** [comment]
+1

**Comment by M-Fararjeh** [comment]
+1

**Comment by manassesferreira** [comment]
+1

**Comment by erikdj** [comment]
+1

**Comment by rvillalba-novetta** [comment]
+1

**Comment by spencerQS** [comment]
+1

**Comment by PradheepKumarA** [comment]
+1

**Comment by Erick-Zanetti** [comment]
+1

**Comment by mayurkale22** [comment]
+1

**Comment by prathappuppala1** [comment]
+1

**Comment by lonix1** [comment]
it's completely dockered

**Comment by zjb421** [comment]
+1

**Comment by kevinsallee** [comment]
this is what the apocalypse feels like then

**Comment by MitulGedeeya** [comment]
+1

**Comment by davidhesson** [comment]
Time to set up that mirror

**Comment by poebeta** [comment]
The same (Poland).

**Comment by nasirkhanbeis** [comment]
same here (UK)

**Comment by vitualizz** [comment]
The same (Peru) :trollface:

**Comment by youhide** [comment]
Sasame (BR)
![image](https://user-images.githubusercontent.com/4053124/66856290-4af2cf80-ef5b-11e9-812b-ec534ae79590.png)

**Comment by olliecee** [comment]
The same (Canada)

**Comment by NeronJoseph** [comment]
Same here (India)

**Comment by allanpedroni** [comment]
same here (BR)

**Comment by kavichu** [comment]
The same (BR)

**Comment by UrielHaile** [comment]
same here MX

**Comment by kbucksch** [comment]
same same

**Comment by code1x1** [comment]
+1

**Comment by seriallink** [comment]
Same here. 

Failed to pull Docker image golang:1.13.1: Error response from daemon: received unexpected HTTP status: 503 Service Unavailable.

**Comment by joev0000** [comment]
Me too!
> DON'T REPLY ALL
>> Please take off this mailing list.

**Comment by koderoff** [comment]
+1

**Comment by saifahmed218** [comment]
same here

```docker pull creack/firefox-vnc
Using default tag: latest
Error response from daemon: received unexpected HTTP status: 503 Service Unavailable```

**Comment by nasirkhanbeis** [comment]
working okay now(UK)

**Comment by manassesferreira** [comment]
working okay now(BR)

**Comment by spencerQS** [comment]
yayy work time

**Comment by iabruskov** [comment]
and same

**Comment by MitulGedeeya** [comment]
working now.

**Comment by M-Fararjeh** [comment]
It's working now

**Comment by shubhamgupta731** [comment]
Working okay now (India).

**Comment by davidhesson** [comment]
Let me guess - it's working nao?

**Comment by kavichu** [comment]
Working okay nao.

**Comment by MihanixA** [comment]
Working OK, Russia

**Comment by fuatkestane** [comment]
Working OK(Turkey)

**Comment by TwinProduction** [comment]
Working (Canada)

**Comment by cowsrule** [comment]
This issue has been resolved. Thank you for the reports!
