### ISSUE TITLE
Build Settings messy & need source repo type display

### ISSUE THREAD

**Issue by cpuguy83** [docker/hub-feedback#190]
The build settings page for an automated build is super messy, likely due to the right justification of the 2nd column.

![screen shot 2015-08-07 at 9 19 28 am](https://cloud.githubusercontent.com/assets/799078/9136556/9a509378-3ce5-11e5-840d-d1a602b819b4.png)

**Comment by nhsiehgit** [comment]
hey @cpuguy83 

you're just referring to the 'activate auto-build' row right? agreed can be better

**Comment by cpuguy83** [comment]
That's part of it.
It's also som buttons underneath, some buttons inside, some buttons with no box at all. Button on the left, button on the right, and buttons on both sides.

**Comment by commanderfun** [comment]
Also, the linked GitHub repo name should appear somewhere on this page.

**Comment by nhsiehgit** [comment]
Column width has been fixed. updating ticket to reflect other changes that can be improved

**Comment by nhsiehgit** [comment]
this should be resolved now. closing
