### ISSUE TITLE
Intermittent 504's from API 

### ISSUE THREAD

**Issue by lholland421** [docker/hub-feedback#1903]
## Problem description
When calling “https://hub.docker.com/v2/repositories/{{ORG}}/{{REPO}}/tags?page_size=100&page=1” we are seeing intermittent 504 gateway errors. 

We are seeing the call return a 200 http status code but the below HTML. 

![image](https://user-images.githubusercontent.com/25055726/67076593-59243400-f185-11e9-9a80-32fa1a598b3c.png)

**Comment by manishtomar** [comment]
While our APIs are easy to decipher from the browser we don't officially support (yet) it being called from third parties. That being said, could you give example of repos that failed and what times?
