### ISSUE TITLE
Cannot delete tags

### ISSUE THREAD

**Issue by ginkel** [docker/hub-feedback#1904]
## Problem description

When attempting to delete a tag, such as tgbyte/cron:armhf, through the Docker Hub web frontend, nothing happens and the tag remains in place.

The Javascript console logs the following error that may or may not be related:

```
tags:61 GET https://cloud.docker.com/api/nautilus/v1/repositories/summaries/tgbyte/cron/ 404 (Not Found)
```

**Comment by buanet** [comment]
Same here.

**Comment by meticulous-dft** [comment]
thanks for reporting, will take a look

**Comment by meticulous-dft** [comment]
should be working now.

**Comment by buanet** [comment]
Confirm. For me it is working again. Thanks.
