### ISSUE TITLE
Multi Stage Build Caching not working

### ISSUE THREAD

**Issue by SatoshiDark** [docker/hub-feedback#1905]
I have a multi stage build (React and Nginx), but the build cache doesn't work at all, it takes up to 25 minutes to build, and it never uses the cache.

Is this feature supported or build cache only works on one-stage builds only?

**Comment by jmdodge** [comment]
I seem to be having the same issue with a multi-stage build for Angular and Nginx. None of the layers in the first stage are pulling from cache in Docker Hub, but I do see some "Using cache" logs once it gets to the second layer.

**Comment by IanSmith123** [comment]
I have the same question here, it take up to 50 minutes to build when I use multi-stage. I use multi-stage to decrease the size of image, docker cache worked in my own computer, but the cache doesn't work at dockerhub. However, traditional Dockerfile without multi-stage, the cache works well in Dockcer Hub.
