### ISSUE TITLE
Unable to list tags

### ISSUE THREAD

**Issue by denzp** [docker/hub-feedback#1906]
I'm having troubles loading tags of my public repositories. At first, I was able to see tags in the Management view but not in the Public view. Then after several days, the Management view got broken too.

Seems like pushing and pulling works as expected.

Affected repositories:
- https://hub.docker.com/r/denzp/cargo-wharf-frontend/tags
- https://hub.docker.com/r/denzp/cargo-container-tools/tags

![img-2019-10-23-164446](https://user-images.githubusercontent.com/747869/67405020-78bbc200-f5b4-11e9-8b45-21dd72823897.png)

![img-2019-10-23-164652](https://user-images.githubusercontent.com/747869/67405208-bf112100-f5b4-11e9-9ef1-db8467ea1607.png)

The following requests failed with status 500 and same error:
https://hub.docker.com/v2/repositories/denzp/cargo-container-tools/tags/?page_size=25&page=1
https://cloud.docker.com/v2/repositories/denzp/cargo-container-tools/tags/?page_size=25

``` json
{
    "txnid": "REPOSREQ-fac63740-106a-4647-a201-a593cd486dcd",
    "message": "ListRepositoryTags failed",
    "errinfo": {
        "api_call_docker_id": "6f04012fabc94fc485ce8efc26f4e0a9",
        "api_call_name": "ListRepositoryTags",
        "api_call_start": "2019-10-23T14:38:48.373453025Z",
        "api_call_txnid": "REPOSREQ-fac63740-106a-4647-a201-a593cd486dcd",
        "error": "failed to update 1 tag(s)"
    }
}
```

**Comment by denzp** [comment]
Another observation: **Pulls** counter is getting increased every time I refresh the Public tags view.

**Comment by manishtomar** [comment]
Thanks for the report. We will investigate this. It looks like only your repository is having trouble. Was the images pushed using docker engine (`docke push`) or some other tool by any chance? Regarding the pull count it is unfortunately occurring due to the above problem. That should not happen once this is fixed.

**Comment by denzp** [comment]
Thanks for the fast response!

I think the problem started when I pushed a BuildKit cache. I used `docker buildx` with [`--cache-to=type=registry` flag](https://github.com/docker/buildx#--cache-tonametypetypekeyvalue).

**Comment by manishtomar** [comment]
Aah. That explains then. While build cache is pushed as an image with correct media type it looks like Hub is not processing it due to annotations. We will fix it on our end. Thanks.

**Comment by manishtomar** [comment]
Scratch that. The manifest representing the build cache does seem incorrect as per the spec. I'll have to open an issue in buildx repo.

**Comment by manishtomar** [comment]
Buildx issue: https://github.com/docker/buildx/issues/173

**Comment by manishtomar** [comment]
Hub tags view should not break if manifest is incorrect. We will fix on our end to list other tags at least.

**Comment by denzp** [comment]
Thank you! That sounds like a good plan! 

Also, it might be helpful to show a warning near the tag that has a wrong manifest.

**Comment by dargmuesli** [comment]
Is there an ETA or roadmap on this?

Background:
The inability to fetch this tag information makes [renovate](https://renovatebot.com/) open PRs for updates that are configured to be automerged, which results in a lot of work when maintaining a few repos.

**Comment by manishtomar** [comment]
We are working on this. Hoping to get this done in next few weeks.

**Comment by dargmuesli** [comment]
Looks like my project's tags ([example](https://hub.docker.com/r/dargmuesli/jonas-thelemann/tags)) are now visible again, including the cache tag with `Unknown` digest :) thanks!

**Comment by manishtomar** [comment]
Yeah. We fixed it but forgot to update the issue. Closing.
