### ISSUE TITLE
Multiple 2FA Devices

### ISSUE THREAD

**Issue by ankane** [docker/hub-feedback#1909]
Hi, good to see 2FA support is in beta. It'd be great if multiple 2FA devices were supported at once (for instance, an app and YubiKey). This would make it less likely for users to get locked out of their account.

**Comment by manishtomar** [comment]
Thanks for the feedback. While I don't think we can support multiple 2FA devices "at once" we will work towards supporting webauthn along with TOTP based authentication.

**Comment by ankane** [comment]
Hey @manishtomar, thanks for the response. Can you elaborate on why you don't think it's possible? Many services do this, like GitHub. https://github.com/settings/security

**Comment by manishtomar** [comment]
Sorry I didn't intend to to say we won't (or can't) be supporting other authentication mechanisms. We definitely do want to support other devices but cannot commit on the timelines as of now. We've webauthn in our near term roadmap and hence mentioned that. We will let you know once there is clarity on when we can add support for other devices.

**Comment by ankane** [comment]
Thanks for clearing that up
