### ISSUE TITLE
Feature request: Add guide to the non-QR 2FA setup to distinguish between easily confused characters (e.g. oh and zero)

### ISSUE THREAD

**Issue by salticus** [docker/hub-feedback#1913]
## The display of the 2FA secret makes it hard to distinguish between similar characters

For a device that cannot read the QR code, one must enter the text of the secret.

When entering the secret it was not clear whether certain characters where a zero or an oh. It may be that the font makes a clear distinction, but the secret given only uses one of those characters. The workaround of course is to copy the secret to a word processor and type O and 0 and compare the shapes, or change the font.

## Suggested feature
Add a guide under the secret displaying characters that might be confused, for example:
L vs 1 vs I, O vs 0, etc.

**Comment by thaJeztah** [comment]
Thanks for the feedback! I'll forward this internally
