### ISSUE TITLE
Can not add credit card

### ISSUE THREAD

**Issue by PatrikTes** [docker/hub-feedback#1915]
## Problem description
I can not add a payment with the card.

## Docker Hub Account Issues

Getting error:
bizible.js:128 POST https://api.billforward.net/v1/tokenization/auth-capture 400

Add payment method failed. Please check the card information is correct or try another one.

Looks like a problem in billforward api... Can not create private repo, it's at the moment blocker for me

**Comment by JPZ13** [comment]
I'm getting this same error too - it looks like organizations are not getting created in BillForward, causing a 404:
```
{"txnid":"BLSREQ-394c2e4f-d770-4ded-ac84-e24f5aa32476","message":"account not found","errinfo":{"api_call_docker_id":"2d7998505e2548a8b16f80f46c6ce4a6","api_call_name":"GetV3Account","api_call_start":"2020-03-10T19:46:44.243601907Z","api_call_txnid":"BLSREQ-394c2e4f-d770-4ded-ac84-e24f5aa32476","docker_id":"xxxxxxxxx"}}

@manishtomar @engclarissa @spencerhcheng Could y'all look into it? I'm trying to give y'all money 😂 
```

**Comment by manishtomar** [comment]
@JPZ13 HOWDY!? Thanks for the info. Can you describe when you got this info? Was it while creating the org or was it while purchasing subscription for the org?

**Comment by JPZ13** [comment]
WHAT'S UP, @manishtomar ?!?!! I get it on the following screen after putting in my credit card info and hitting submit. The org has already been created, but I can't purchase the subscription. I have no information entered in the screenshot so that I don't get robbed:

![Screen Shot 2020-03-11 at 5 33 49 PM](https://user-images.githubusercontent.com/6625432/76466808-b59b2080-63be-11ea-83c4-dd796e3aba21.png)

**Comment by manishtomar** [comment]
Thanks @JPZ13. We are investigating and will get back.

**Comment by JPZ13** [comment]
My man!

**Comment by manishtomar** [comment]
@JPZ13 Have you tried again? Same error? I think the page should try to create account if it is not found. Can you try capturing the network traffic when you are adding the credit card info, save it as HAR file and send it across to hub-support@docker.com?

**Comment by JPZ13** [comment]
@manishtomar It started working today. Thanks, man!

**Comment by manishtomar** [comment]
Good to know. Thanks for the info. Please feel free to reach out if you have any trouble. The HAR files will be super helpful though :). I am closing this ticket. @PatrikTes I assume your problem is also not occurring now.
