### ISSUE TITLE
HTTP Code 404 (page not found) for Pricing page at Docker Cloud

### ISSUE THREAD

**Issue by christian-weiss** [docker/hub-feedback#1917]
When your are not logged in then you can see at:
https://cloud.docker.com/
as menu item "Pricing". When you click on that then your are asked to login. After successful login you see a 404 error page.

Happens on Ubuntu 19.10 with Firefox 70.0.1 (even i a private tab) and in chrome 78.0.3904.87 - also with another account.

**Comment by meticulous-dft** [comment]
hi there. i believe this problem is fixed now. Please reopen if you still see 404 and attach a screenshot. Thnaks a lot.
