### ISSUE TITLE
Automated builds with moby/buildkit not working overall

### ISSUE THREAD

**Issue by qdm12** [docker/hub-feedback#1918]
## Problem description

Running builds with moby/buildkit in Docker Hub Automated builds is not working overall.

- Exporting `DOCKER_BUILDKIT=1` does not do anything as Docker Hub is not set to use experimental settings
- Using the hooks/build:

    ```sh
    #!/bin/bash

    docker run --rm --privileged -v `pwd`:/tmp/app \
        --entrypoint buildctl-daemonless.sh \
        moby/buildkit \
        build \
        --frontend=dockerfile.v0 --local context=/tmp/app --local dockerfile=/tmp/app \
        --output type=image,name=$DOCKER_REPO:$DOCKER_TAG
    ```

    Will not write the Docker image to the host and so it cannot push the image.

- Using the hooks/build:

    ```sh
    #!/bin/bash

    docker run --name buildkit -d --privileged moby/buildkit
    export BUILDKIT_HOST=docker-container://buildkitd
    docker cp buildkit:/usr/bin/buildctl /usr/local/bin/
    buildctl build \
        --frontend=dockerfile.v0 --local context=. --local dockerfile=. \
        --output type=image,name=$DOCKER_REPO:$DOCKER_TAG
    ```

    Fails with error `error: failed to get status: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection closed`. Using a TCP port gives a similar error `error: failed to get status: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: error while dialing: dial tcp 127.0.0.1:1234: connect: connection refused"`

Any help would be appreciated!

**Comment by davidwindell** [comment]
It looks like this issue can be closed now, see https://docs.docker.com/docker-hub/builds/#build-images-with-buildkit

**Comment by arikw** [comment]
I can confirm it works.

At first, I got the following error message although I've added the `DOCKER_BUILDKIT=1` env variable:
`failed to solve with frontend dockerfile.v0: failed to create LLB definition: Dockerfile parse error line 16: Unknown flag: mount`

The problem occurred due to an empty line before the `# syntax = docker/dockerfile:1.2` line in the `Dockerfile`.
Removed the empty line and everything worked.

**Comment by rdmolony** [comment]
Hey there,

As of 2022-05-11 the [automated test step on Docker Hub](https://docs.docker.com/docker-hub/builds/automated-testing/) don't automatically support BUILDKIT like the `build` step does.

After a bit of trial & error I overrode this step via `hooks/test` ...

```sh
#! /bin/bash

DOCKER_BUILDKIT=1 \
    docker build \
    -f $DOCKERFILE_PATH \
    -t $IMAGE_NAME \
    .
```

... but it would be nice to  have it enabled by default to enable things like 

```Dockerfile
RUN --mount=type=cache,target=/var/cache/apt \
    --mount=type=cache,target=/var/lib/apt \
    apt-get update && apt-get install -y ...
```
