### ISSUE TITLE
API to ListRepositoryTags is failing 19/20 times as of today.

### ISSUE THREAD

**Issue by grayaii** [docker/hub-feedback#1919]
## Problem description
As of this morning, we have started getting this error:

```
{
  "txnid": "REPOSREQ-8a33f2e3-6b18-4870-b2de-0a0bfba3c176",
  "message": "object not found",
  "errinfo": {
    "api_call_docker_id": "",
    "api_call_name": "ListRepositoryTags",
    "api_call_start": "2019-11-22T18:23:37.422778838Z",
    "api_call_txnid": "REPOSREQ-8a33f2e3-6b18-4870-b2de-0a0bfba3c176"
  }
}
```

The python code is pretty simple:
1) Get an auth token:
```
url = 'https://hub.docker.com/v2/users/login/'
headers = {'Content-Type': 'application/json'}
data = {'username': docker_hub_username, 'password': docker_hub_password}
r = requests.post(url, json=data, headers=headers)
token = json.loads(r.content.decode('UTF-8'))['token']
```

2) Get the tags:
```
url = 'https://hub.docker.com/v2/repositories/clearcare/web/tags/?page_size=100'
headers = {'Authorization': 'JWT {}'.format(token)}
r = requests.get(url, headers=headers)
```
Bam. We get that error.

This code has been running flawlessly for years, but as of this morning, it's been failing 95% of the time.
It seems to work 1/20 times though, which is super weird.

I don't see any issues on the status page of docker hub, nor do we see any outages reported.

I'm not sure how to even debug this.

**Comment by cowsrule** [comment]
Hi @grayaii ,

Can you share the username you are making this request with? Please feel free to send it to the email in my profile if it is sensitive. Thanks.

**Comment by grayaii** [comment]
No problem, @cowsrule !  The username is ccojenkins.

**Comment by cowsrule** [comment]
Can take a look at your logs and clarify on when you started to see this happen? Specifically, can you pinpoint this to November 7th timeframe?

**Comment by cowsrule** [comment]
Also can you verify the host that you are hitting? It looks like you may not have copy/paste the code being run exactly. Is it in fact `registry.hub.docker.com` instead?

**Comment by roeP** [comment]
I'm also facing this issue starting from today, most of the calls failed with:
{"txnid":"REPOSREQ-bddbb4bc-2463-4356-b21b-b333cf3283de","message":"object not found","errinfo":{"api_call_docker_id":"","api_call_name":"ListRepositoryTags","api_call_start":"2019-11-24T16:11:00.419313515Z","api_call_txnid":"REPOSREQ-bddbb4bc-2463-4356-b21b-b333cf3283de"}}

Run this to reproduce:

#!/bin/bash


TOKEN=`curl -s -H "Content-Type: application/json" -X POST -d '{"username": "****", "password": "***"}' https://hub.docker.com/v2/users/login/ | jq -r .token`

curl -s -H Authorization: JWT $TOKEN "https://hub.docker.com/v2/repositories/${ORG}/${REPO}/tags/?page_size=100"

**Comment by cowsrule** [comment]
One last question: Did you recently enabled 2FA on the accounts that are being used here?

**Comment by roeP** [comment]
> Did you recently enabled 2FA on the accounts that are being used here and are you using a Personal Access Token instead of a password?

For me no 2FA and I'm using the password instead of the token.
I just try with a tocken instead of the password and gets the same result

**Comment by cvrod** [comment]
Hello,
I'm facing the same issue since Friday 11/25 morning.
I receive this error most of the time : 
`{"txnid":"REPOSREQ-2f4bd163-4071-44d6-81cb-f00558902a33","message":"object not found","errinfo":{"api_call_docker_id":"","api_call_name":"ListRepositoryTags","api_call_start":"2019-11-25T13:21:16.889345436Z","api_call_txnid":"REPOSREQ-2f4bd163-4071-44d6-81cb-f00558902a33"}}`

And sometime it's work as expected....

**Comment by jclegras** [comment]
I was struggling with this issue.
Thank you very much @cvrod.

**Comment by grayaii** [comment]
My workaround (in python) is the same. Basically sleep until it works:


    # First get the token:
    url = 'https://hub.docker.com/v2/users/login/'
    headers = {'Content-Type': 'application/json'}
    data = {'username': docker_hub_username, 'password': docker_hub_password}
    r = requests.post(url, json=data, headers=headers)
    if r.status_code != 200:
        say('***ERROR: Did not get a 200 from hub.docker.com to get a token...', color='red')
        say(r.content)
        sys.exit(1)
    token = json.loads(r.content.decode('UTF-8'))['token']
    say('Successfully got auth token for docker hub...', do_print=args.debug)
    # Now get the tags for the repo:
    url = 'https://hub.docker.com/v2/repositories/clearcare/web/tags/?page_size=100'
    headers = {'Authorization': 'JWT {}'.format(token)}
    for i in range(10):
        r = requests.get(url, headers=headers)
        if r.status_code == 200:
            break
        else:
            time.sleep(1.5)
    if r.status_code != 200:
        say('***ERROR: Did not get a 200 from hub.docker.com...', color='red')
        say(r.content)
        sys.exit(1)

**Comment by jurglic** [comment]
We are having the same issue since 22nd of November. The request to list tags for a private repo fails with 404 about 50% of the time... as if the token wasn't valid and we don't get authorised to access the resource.

Same solution as already described: wait and retry for the token to "become valid".

**Comment by cowsrule** [comment]
Appreciate your patience and reports. We have identified the issue on our end thanks to the information everyone provided and will be rolling out a fix in the next few days.

As stated above, adding a couple seconds of sleep after receiving your token before making the API call will mitigate the auth problem.

**Comment by cowsrule** [comment]
A fix was rolled out yesterday, this should no longer be occurring. Please re-open if you continue to see this issue.
