### ISSUE TITLE
Create Repository Button is sometimes not there.

### ISSUE THREAD

**Issue by lbergelson** [docker/hub-feedback#1920]
## Problem description
The button to create a repository is sometimes missing on https://hub.docker.com/.  Navigating to a different organization and back will reveal it.  It sometimes shows up / disappears on refresh.

1. What I see on page load, no button.
<img width="964" alt="Screen Shot 2019-12-05 at 2 39 31 PM" src="https://user-images.githubusercontent.com/4700332/70267779-1fc37a00-176d-11ea-8a72-6b4ff08a39ba.png">

2. Then navigate to a different one of my organizations:
<img width="957" alt="Screen Shot 2019-12-05 at 2 39 40 PM" src="https://user-images.githubusercontent.com/4700332/70267784-218d3d80-176d-11ea-915f-f65db5e02f3f.png">

3. Then navigate back to the original one and the button is back!
<img width="946" alt="Screen Shot 2019-12-05 at 2 39 46 PM" src="https://user-images.githubusercontent.com/4700332/70267790-2520c480-176d-11ea-9abe-a4e78a4a24bc.png">

See  https://thumbs.gfycat.com/ThankfulJauntyHeron-mobile.mp4 for a more moving demonstration.

**Comment by meticulous-dft** [comment]
Thanks for the report. We will investigate it.

**Comment by siarheikarneichyk** [comment]
Hi lbergelson, could you please check if you are an owner of the `broadinstitute` organization. Only owners of the organization allowed to create a repository inside that organization.

**Comment by lbergelson** [comment]
@siarheikarneichyk I'm not an owner of the broadinstitute organization.  The weird thing is that I can't create repositories under MY name unless I toggle between organizations.

**Comment by mulodo-ngo-anh** [comment]
Same issue, the create repository button has been gone. where is it now

**Comment by siarheikarneichyk** [comment]
Hi @mulodo-ngo-anh We are currently working on this issue. For now try to reload the page, it doesn't happen all the time. I will update you as soon as it's fixed.

**Comment by mtnmts** [comment]
Having the same issue, tried to re-login 5 times, switch browsers (Chrome & Firefox).

any advice?

**Comment by mtnmts** [comment]
Actually - Just solved it, this may help others, I had Bitbucket integration set up, the moment i disconnected it the button appeared.

**Comment by mulodo-ngo-anh** [comment]
> Hi @mulodo-ngo-anh We are currently working on this issue. For now try to reload the page, it doesn't happen all the time. I will update you as soon as it's fixed.

 Thank you!





> Actually - Just solved it, this may help others, I had Bitbucket integration set up, the moment i disconnected it the button appeared.

I haven't even any integration :)

**Comment by d-goro** [comment]
Same issue. Refreshes didn't help and I have no integration with the git hub.

**Comment by aukedejong** [comment]
Same here. No integrations. New account, created few weeks ago and wanted to push my first image.

**Comment by dantuluri** [comment]
Having the same issue.

Thought it was some of my ad blocking extensions or my VPN. Even when shut off for the docker hub subdomain, I'm not seeing the create repo button all the time.

**Comment by siarheikarneichyk** [comment]
@lbergelson @mulodo-ngo-anh Fixed. Thanks for creating an issue.

**Comment by sallysharon** [comment]
I am unable to create a reposirory too. The create button isn't there
