### ISSUE TITLE
Docker login broken

### ISSUE THREAD

**Issue by sarusso** [docker/hub-feedback#1921]
```
$ docker login
Login with your Docker ID to push and pull images from Docker Hub. If you don't have a Docker ID, head over to https://hub.docker.com to create one.
Username: xxxx
Password: 
Login Succeeded

$ docker push xxxx/something
The push refers to repository [docker.io/xxxx/something]
[cut]
denied: requested access to the resource is denied

$ docker logout
Not logged in to https://index.docker.io/v1/

```

Docker version 18.06.1-ce-mac73 (26764).

Any hints?

Thank you.

**Comment by manishtomar** [comment]
It is working for us. Are you sure you have the permission to push?

**Comment by sarusso** [comment]
Hi @manishtomar, yes I confirm that I have permission to push and I am indeed working around the problem using Docker-in-Docker to push. This works:
```
$ docker version
Client:
 Version:           18.09.7
 API version:       1.38 (downgraded from 1.39)
 Go version:        go1.10.1
 Git commit:        2d0083d
 Built:             Fri Aug 16 14:20:06 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:29:02 2018
  OS/Arch:          linux/amd64
  Experimental:     true
```
..while this doesn't:
```
$ docker version
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:21:31 2018
 OS/Arch:           darwin/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:29:02 2018
  OS/Arch:          linux/amd64
  Experimental:     true
```

**Comment by manishtomar** [comment]
Ok thanks. I am not sure what is the problem with your environment. Since this is not a problem with hub, I am closing this ticket. I am not sure why it is not working for you. Maybe check the engine's `~/.docker/config.json`?

**Comment by sarusso** [comment]
Hi @manishtomar, I hardly think it is a problem with my environment as it stopped working from one day to the another, but it of course might be the case. I anyway deleted even the `~/.docker/config.json` file and started fresh, still permission denied.

Sounds like a not back-compatible api change on docker hub to me.

Have you tried with the same version of Docker for Mac, or have you regression tests in place to cover my version as well?

The version I am using it is the latest one supported on OS X El Capitan (which I have to stick to for other reasons).

Thank you,
Stefano.

**Comment by manishtomar** [comment]
Try running below script. If it works then something is wrong with your engine:
```bash
#!/bin/sh
# Run this as ./script library/golang manifests/latest
repo=$1
url=$2
token=$(curl -v -u username:password "https://auth.docker.io/token?service=registry-1.docker.io&scope=repository:$repo:pull" | jq -r .token)
curl https://registry-1.docker.io/v2/$repo/$url -H "Authorization: Bearer $token" -L -H "Accept: application/vnd.docker.distribution.manifest.v2+json" "$@"
```

**Comment by sarusso** [comment]
`{"errors":[{"code":"UNAUTHORIZED","message":"authentication required","detail":[{"Type":"repository","Class":"","Name":"sarusso/astrocook","Action":"pull"}]}]}`.

..but I can successfully get the token.

**Comment by manishtomar** [comment]
> ..but I can successfully get the token.

You will always get a token. The permissions in that may not be what you want. Try pasting the token in jwt.io to see what access you got. Based on the above error message it looks like the password is incorrect. I haven't worked with dind envs but the password should be from the system where `docker` command is run. If it is run inside the container then container's `~/.docker/config.json` has the right password and your laptop/dev machine's config.json does not have the password.
