### ISSUE TITLE
All our Docker Hub build triggers disappeared recently, and we cannot create them anew

### ISSUE THREAD

**Issue by erikmd** [docker/hub-feedback#1922]
## Problem description

In these two automated build repos:

- https://hub.docker.com/repository/docker/coqorg/coq/builds/edit
- https://hub.docker.com/repository/docker/mathcomp/mathcomp/builds/edit

the build triggers that were configured up to now, have been unexpectedly removed
(it seems this occurred at some point between 2019-12-04 03:05 UTC+1 and 2019-12-05 00:05 UTC+1)
and in addition, we are unable to add them anew: **any click on the button `+` is a no-op**.

Would this be a known bug?
Hopefully you'll be able to look at this soon, as build triggers are an important Docker Hub feature for maintaining these images :)

Thank you for your time

**Comment by cowsrule** [comment]
Appreciate the report - I am looking into this.

**Comment by cowsrule** [comment]
Unfortunately we won't have a fix rolled out today, but this is being actively addressed.

**Comment by erikmd** [comment]
Hi @cowsrule, would you have some news - or a time estimate for the fix?

**Comment by erikmd** [comment]
The triggers are visible again in our repos so the issue seems resolved, thanks for the fix :+1:
