### ISSUE TITLE
create repository

### ISSUE THREAD

**Issue by SuperElectron** [docker/hub-feedback#1923]
## Problem description
As a user
I want to create a repository when I am logged into my account
So that I can start a new project!

## Issue
- I need to click on my user (SuperElectron for my dockerhub) before I can see the "+Create Repository" button visible.

## Context
- This means that if I follow your instructions here: https://docs.docker.com/docker-hub/repos/
- First I log in, go to repository, and I should see a button to click.

The problem is that if I follow your instructions I DO NOT see a button to create a new repository (the button is hidden until I select my user from the drop down menu).  This took me quite a while to figure out, and it should auto-select the first user in the drop down menu SO THAT I do not need to select one.

## Example of Problem
(the hidden step is clicking my username)
I click my username and now I can see "+Create Repo"
![dockerhub-issue](https://user-images.githubusercontent.com/11896926/70471307-bc458f00-1a81-11ea-976e-e3fc1c990b83.gif)

**Comment by manishtomar** [comment]
Being tracked in #1920. Closing this.
