### ISSUE TITLE
Tag Pagination

### ISSUE THREAD

**Issue by Quetzacoalt91** [docker/hub-feedback#194]
With the new Docker Hub, the number of displayed tags seems to be limited.

On the repository _prestashop/prestashop_, we are supposed to have every version of our software available.
All existing tag has been assigned to a folder of our [GitHub repository](https://github.com/PrestaShop/docker/tree/master/images).

However, even after an automated build, only 10 of them are displayed in the new Docker Hub.
![capture du 2015-08-07 17 31 31](https://cloud.githubusercontent.com/assets/6768917/9139421/81ce18a8-3d2a-11e5-8e93-d8c3397e31e6.png).

Maybe all tags are actually available, but softwares like Kitematic show the same list as Docker Hub. This lack of information is in my opinion an issue.

Kind regards

**Comment by ChristopherBiscardi** [comment]
Thank you for reporting this. It would seem something changed in the Tags API we are using to fetch the data which is now defaulting to a page_size of 10.

**Comment by kunickiaj** [comment]
+1

**Comment by VelizarVESSELINOV** [comment]
:+1:

**Comment by Quetzacoalt91** [comment]
Thanks @ChristopherBiscardi for your answer. Should I notify the Kitematic team about this issue or a fix on the Docker Tags API would be enough ?

**Comment by ChristopherBiscardi** [comment]
@Quetzacoalt91 We brute forced a fix for this on Hub by bumping our page_size to 100. It's unlikely the page_size default will change in the backend, which means Kitematic will need to bump the page_size. 

ping @jeffdm ^

**Comment by ChristopherBiscardi** [comment]
Closing since we bumped the limi to 100

![screenshot 2015-08-25 21 53 53](https://cloud.githubusercontent.com/assets/551247/9485814/ced036f2-4b73-11e5-8117-460d24d4921e.png)

**Comment by Quetzacoalt91** [comment]
Thanks for your help @ChristopherBiscardi :+1:

**Comment by posita** [comment]
How does this fix the issue? Bumping them to 100 merely makes the issue appear later? If one cannot page through to the second, third, etc. block of 100 and/or delete tags (see #68) so that you can keep the number under 100, the issue still exists. Please consider reopening as not yet fixed.

**Comment by ChristopherBiscardi** [comment]
@posita we're listening. Can you provide a use case for >100 tags besides just knowing that they haven't been deleted (which was brought up in a different issue). I have at least two ideas for the implementation of the interface but would appreciate a concrete use case so I can prioritize the implementation that enables the right access patterns.

**Comment by kunickiaj** [comment]
@ChristopherBiscardi I don't think we really need >100 tags except that we want to publish nightly builds in some cases. The fact that you cannot delete older tags today is how we ended up with > 100 tags.

**Comment by posita** [comment]
> @posita we're listening. Can you provide a use case for >100 tags besides just knowing that they haven't been deleted [...?]

I don't have one personally. I'm sure I could invent or speculate on some, but that would be a poor source for influencing priorities. :grin: I just wanted to make the point that this issue seems to be about user data that exists, but which can become invisible to the user. And it's *possible* that problem isn't necessarily solved by forcing users to delete some of their more recent data.

Actually, that's an (accidental) use case: even *with* the ability to delete tags, consider the following:

* User creates 200 tags
* Assuming #68 gets fixed and user has ability to delete tags, user wants to delete *oldest* 100 tags

In order to do that, the user would have delete some block of the *newest* 100 tags before any of the *older* 100 tags would even become visible in order to delete them.

**Comment by ChristopherBiscardi** [comment]
Marking this for pagination implementation. (FYI @rrarunan)

**Comment by vicamo** [comment]
https://hub.docker.com/r/vicamo/debian/tags/ here is an use case if you really want to know. But I don't really think that's the point though. Just don't assume there is an upper limit for the service.

**Comment by arjenvanderende** [comment]
And here's another: https://hub.docker.com/r/nodesource/trusty/tags/
For some reason the `Last Updated` field is the same for all tags in this repo. This causes several of the newest tags to be hidden. E.g. tags `4.4.6` and `5.1.0` are shown, but `4.4.7` is hidden, even though it exists. This is very confusing.

**Comment by dimaspivak** [comment]
We *desperately* need this. We develop a product with dozens of stage libraries for each release and, for upgrade testing, we push each one as a separate tag. As of now, we can only see/delete about 2 days worth of tags.

**Comment by derFunk** [comment]
Same here, pagination is really needed! https://hub.docker.com/r/derfunk/awscli-versionized/tags/

**Comment by derFunk** [comment]
Hey, the Docker Hub Tag page is doing a XHR request already, which is already prepared for pagination.

**Why not reflect this on the website and adding pagination links?**

E.g.: 
https://hub.docker.com/v2/repositories/derfunk/awscli-versionized/tags/?page=25

Manipulating the `page` parameter shows all tags.

There's another parameter `page_size`, which upper limit seems to be hard-coded unfortunately:
https://hub.docker.com/v2/repositories/derfunk/awscli-versionized/tags/?page=1&page_size=2

**Comment by sdouglasnelson** [comment]
We also need this feature. Are any plans to implement tag pagination in the near future?

**Comment by dimaspivak** [comment]
Docker Cloud has this, which is why I'm guessing it hasn't been implemented on Docker Hub.
