### ISSUE TITLE
Not able to signup - invalid recaptcha response

### ISSUE THREAD

**Issue by rafaelgilardino** [docker/hub-feedback#1941]
## Problem description
During the signup process I'm unable to create my account.

While digging into the events I realize that signup request is failing with error: '{"recaptcha_response": ["invalid recaptcha response"]}' despite it was successfully performed

![image](https://user-images.githubusercontent.com/28607816/72913112-679d6100-3d1b-11ea-8ab9-7e0fd95fe7c7.png)

It does look similar to the issue https://github.com/docker/hub-feedback/issues/1572 however it shows as closed therefore the issue came up once again

**Comment by manishtomar** [comment]
Thanks for the report. Unfortunately, this was due to bad deploy which was quickly reverted. We had a bad deploy which was quickly reverted. Apologies.

**Comment by JakubGIT** [comment]
I've been experiencing this problem yesterday and today!
