### ISSUE TITLE
Cannot pull image with ipv6

### ISSUE THREAD

**Issue by NoxInmortus** [docker/hub-feedback#1945]
Hello,

I'm trying to setup an ipv6-only server with docker containers.

Sadly, is seems that registry-1.docker.io and docker.io does not have any AAA dns entry.

As the public IPv4 addresses pool has finally reached it's limit, I really think this could be the good time to add an AAA entry.

Thanks.

**Comment by thaJeztah** [comment]
I opened a ticket in the public roadmap; https://github.com/docker/roadmap/issues/89

If you're interested in this enhancement, upvote that ticket (which can help getting it prioritised)

**Comment by manishtomar** [comment]
Closing it in favor of https://github.com/docker/roadmap/issues/89
