### ISSUE TITLE
Unable to list repository tags when using personal access token

### ISSUE THREAD

**Issue by philliphoff** [docker/hub-feedback#1947]
## Problem description

When a user has enabled 2-factor authentication (2FA), the Docker Hub web API can be used to list namespaces and repositories associated with the user.  However, the web API for listing tags of a given repository returns the error `"access to the resource is forbidden with personal access token"`.

Specifically, the following web APIs succeed:

 - `[GET] v2/repositories/namespaces`
 - `[GET] v2/repositories/<namespace>`

The following web API fails:

 - `[GET] v2/repositories/<namespace>/<repository>/tags`

Which returns a 403 Forbidden:

```json
{
    "message": "access to the resource is forbidden with personal access token"
}
```

**Comment by cowsrule** [comment]
Hey @philliphoff,

PATs on Hub should only support Registry APIs through https://registry-1.docker.io/v2/, they do not provide full access to Hub specific APIs through https://hub.docker.com/v2/.  You should be able to use https://docs.docker.com/registry/spec/api/#tags to list tags associated with a particular namespace/repo.

**Comment by meticulous-dft** [comment]
The problem should be fixed.

**Comment by philliphoff** [comment]
@meticulous-dft Confirmed fixed; thanks for the quick turnaround!
