### ISSUE TITLE
one git push to linked GitHub repo triggers two builds in automated build repo

### ISSUE THREAD

**Issue by erikmd** [docker/hub-feedback#1949]
### Problem description

Currently (tested after adding a new build rule), in a Docker Hub automated repo such as `mathcomp/mathcomp`, a **git push** on the GitHub **branch** associated to a build rule triggers **twice the same build** (so we need to manually cancel one of them)

### URL for the page in question.
https://hub.docker.com/repository/docker/mathcomp/mathcomp/timeline

Cc @ybertot @CohenCyril FYI

### Screenshots of the issue

<details>

![2020-02-01_18-43-32_Screenshot_automated_build_twice_bug](https://user-images.githubusercontent.com/10367254/73596658-68f13980-4524-11ea-81b2-44d75c8563b1.png)

&

![2020-02-01_18-44-29_Screenshot_automated_build_twice_bug](https://user-images.githubusercontent.com/10367254/73596663-6f7fb100-4524-11ea-929a-b6ad0ee71767.png)

</details>

### The rough date and time the error occurred

2020-02-01 @ 18:43 UTC+1

### Your Docker Hub username

erikmd

**Comment by meticulous-dft** [comment]
Hi, this is probably because there are two webhooks got triggered from us. please check the `webhook settings` in the gihub repo, it should be https://github.com/math-comp/docker-mathcomp/settings/hooks, if you see both `cloud.docker.com/api/...` and `hub.docker.com/api/...`, please delete the `cloud.docker.com/api/...` one.

**Comment by erikmd** [comment]
Hi @meticulous-dft , thanks for your reply, and good catch!

there were indeed several webhooks (see screenshot below). So I removed the `cloud.docker.com/api`. Should I also remove the `registry.hub.docker.com/hooks/github` ? (which triggers a **301 Moved Permanently**)

![2020-02-04_20-58-35_Screenshot_docker-mathcomp](https://user-images.githubusercontent.com/10367254/73782129-cfc75a80-4791-11ea-82ba-4f04124086e8.png)

Cc @Zimmi48 @ejgallego FYI

**Comment by meticulous-dft** [comment]
yes, `registry.hub.docker.com/hooks/github` can also be removed. thanks.

**Comment by erikmd** [comment]
OK! so I can close the issue, thanks!
