### ISSUE TITLE
Markdown: Link Rendering

### ISSUE THREAD

**Issue by chali** [docker/hub-feedback#195]
I have links defined in my repository full description but they are not shown on rendered page under "Repo Info" tab.

I use this markdown ` [Installing CDH 5 with YARN on a Single Linux Node in Pseudo-distributed mode](http://www.cloudera.com/content/cloudera-content/cloudera-docs/CDH5/latest/CDH5-Quick-Start/cdh5qs_yarn_pseudo.html)` and I have just blank space rendered. It worked in previous version.

**Comment by ChristopherBiscardi** [comment]
This is an issue with the markdown renderer we are using. Specifically, the rendering of anchor tags.

**Comment by kazssym** [comment]
I see http links are not rendered and https are. It also unexpectedly breaks a line with a single EOL.

**Comment by mkjsix** [comment]
I can confirm the same behavior: only https links in markdown are rendered.

**Comment by Ducatel** [comment]
Same bug with link added like:
```
* `dev` contains the developpement version of dashboard. Should be an image of [`master branch`][masterBranch]

[masterBranch]: http://XXXX/dev/commondashboard/tree/master
```

`https` links are added without trouble

**Comment by mkjsix** [comment]
This bug is still present and **very annoying**, as my project's description is full of holes. I can edit the description by hand but when an automated build is triggered my description gets overwritten.

Half of the links are not rendered at all, so people is not able to read the documentation properly unless they move to the original Github's README file. Honestly, this is unaceptable:

![schermata 2015-09-12 alle 13 11 15](https://cloud.githubusercontent.com/assets/365382/9831265/ccf8dcaa-594f-11e5-9dc0-028b1a51be98.png)

**Comment by suchja** [comment]
I can confirm that it is still an issue. This http-link `[EA](http://www.sparxsystems.com/products/ea/index.html)` is **not** working while `[suchja/wine](https://hub.docker.com/r/suchja/wine/)` works without problems.

**Comment by stain** [comment]
Any progress on this? It's quite common for good documentation to have hyperlinks, and this bug makes those descriptions unreadable.  I'll add some of mine as another examples:

https://hub.docker.com/r/stain/jena-fuseki/
https://hub.docker.com/r/openphacts/identitymappingservice/
https://hub.docker.com/r/stain/virtuoso/

Some of these only suffer spurious newlines.

**Comment by spikecurtis** [comment]
+1

**Comment by janeczku** [comment]
+1

**Comment by xorbit** [comment]
Seriously, there are many good, working Markdown parsers.  Why does this problem even exist?  It should be possible to fix this within an hour.

**Comment by adamnovak** [comment]
I can confirm that this is still broken.

**Comment by dhermanns** [comment]
Same problem for me. +1 for being able to use links in documentation ;) Maybe this is of some help for someone: HTTPS-Links are working fine...

**Comment by sb-minimal** [comment]
+1

**Comment by scottdraves** [comment]
:broken_heart:

**Comment by janeczku** [comment]
> chali opened this issue on 7 Aug

:grimacing:

**Comment by ChristopherBiscardi** [comment]
Thanks everyone for hanging in there. This is pending a deploy.

**Comment by ChristopherBiscardi** [comment]
This is deployed. Please let us know if you are still experiencing issues.

**Comment by chali** [comment]
It works. Thank you. Documentation looks much better now.

**Comment by scottdraves** [comment]
:dolphin:
