### ISSUE TITLE
Please remove IP from blacklist

### ISSUE THREAD

**Issue by iExalt** [docker/hub-feedback#1950]
#298

Having issues pulling from 172.106.164.82. Accidentally set too aggressive of a polling setting for Docker Hub.

What is the maximum rate I should pull at to be respectful and to avoid being blacklisted?

**Comment by cowsrule** [comment]
Your IP will be automatically unblocked. Please re-open this if you continue to see issues.

Can you share your use case?

**Comment by iExalt** [comment]
[FluxCD](https://fluxcd.io/) periodically polls an image repository in order to determine whether a new image has been pushed. I'm looking for a balance between extra latency during the build pipeline and not polling Docker Hub too often.
