### ISSUE TITLE
Unable to delete a "Build Trigger"

### ISSUE THREAD

**Issue by dduportal** [docker/hub-feedback#1952]
## Problem description

Hi dear Hub team 👋 

We have a build "Build Trigger" URL called by our CI system to trigger a DockerHub build on the https://github.com/asciidoctor/docker-asciidoctor which was not working (ref. https://github.com/asciidoctor/docker-asciidoctor/issues/125).

After generating a new trigger for the build, we wanted to delete the "old not working" one.

Clicking the "trash" icon next to the hooks does not trigger any event, and generate an XHR error which get an `HTTP/404` answers, see the screenshots below.

<img width="1314" alt="Screenshot 2020-02-09 at 09 21 16" src="https://user-images.githubusercontent.com/1522731/74098995-e1588b80-4b1e-11ea-95af-ecfa73124120.png">

<img width="1792" alt="Screenshot 2020-02-09 at 09 22 38" src="https://user-images.githubusercontent.com/1522731/74098996-e289b880-4b1e-11ea-88c1-18121868b1bf.png">

Creating a new build hook results on the same state: unable to delete a new one as well.

**Comment by leonjza** [comment]
I am not sure if I should open a new issue or just +1 this one, but I am experiencing a similar 404 for the trigger endpoint to add a new trigger.
![image](https://user-images.githubusercontent.com/1148127/79078418-84d54080-7d08-11ea-816d-cb93c01a227b.png)

**Comment by dduportal** [comment]
I confirm that the problem is now solved. Thanks!
