### ISSUE TITLE
Forgot Password Link is not working in macOS

### ISSUE THREAD

**Issue by napsta32** [docker/hub-feedback#1954]
I tried to change password but I can't. When I click the link in the "[Docker Hub] Docker ID Retrieval/Password Reset Request" email, a blank page opens.

![image](https://user-images.githubusercontent.com/26403251/74384028-690ff580-4dbe-11ea-99be-c4b7ddc67a15.png)

**Comment by manishtomar** [comment]
Hi @napsta32 Thanks for the report. Unfortunately, it was due to bad deploy which we immediately reverted. It should be working fine now.
