### ISSUE TITLE
Private Repository Marked as Public 

### ISSUE THREAD

**Issue by Warfront1** [docker/hub-feedback#1955]
## Problem description
Browse to a PRIVATE repository (tested under an organization/ORG in this case), using a non owner account
IE. `https://hub.docker.com/repository/docker/{ORG}/{REPO}/settings`

Notice how the following text suggested that the Repository is actually PUBLIC!
![image](https://user-images.githubusercontent.com/1920038/74875487-59e5f600-5330-11ea-81eb-91d68e1728f8.png)

You would expect it to remark the repository as PRIVATE, not PUBLIC! This would leave the end user to believe there is a huge security risk with the repository being public, when in reality it is not.

It is marked correctly nearly everywhere else, for example:
`https://hub.docker.com/orgs/{ORG}/repositories`
![image](https://user-images.githubusercontent.com/1920038/74877039-c3670400-5332-11ea-8a16-466797d222c6.png)

*Note* That when logged into a different account with `owner` permissions it appears correctly (as seen below). I had a few different co-workers try, and results were mixed.
![image](https://user-images.githubusercontent.com/1920038/74875870-fb6d4780-5330-11ea-8a12-14e48e4e6d4d.png)

**Comment by manishtomar** [comment]
I am not able to reproduce it. Can you please email hub-support@docker.com with specific repository in question?
