### ISSUE TITLE
Problems setting up two-factor authentication

### ISSUE THREAD

**Issue by rpkilby** [docker/hub-feedback#1958]
## Problem description

Hi, I ran into a few issues setting up two-factor authentication on my account. Here's what I did:
- Scanned QR code with Google Authenticator
- Entered multiple 6 digit codes, all failures
- Tried manually entering the text code in Google Authenticator
- Entered multiple 6 digit codes, all failures
- Cancelled the process
- After cancelling, tried to setup 2FA a second time, however the recovery code would not generate.
- I logged out/logged back in and finally on the third attempt, I was able to setup 2FA.

I'm not sure if the recovery code generated on the third attempt due to time, or if it was because I had logged out/logged in.

That all said, I was able to successfully setup 2FA, it just took 3 attempts.

**Comment by EagleOne42** [comment]
Same issue, code was rejected.  Logged out and back in then it worked.

My order of trying to set it up:
Reset my password
Logged in and tried to set up 2FA but it failed.
Found this issue
Logged out
Logged in again
Set up 2FA, it worked this time.
