### ISSUE TITLE
GitHub Auth re-link

### ISSUE THREAD

**Issue by ChristopherBiscardi** [docker/hub-feedback#196]
as per [this comment](https://github.com/docker/hub-beta-feedback/issues/186#issuecomment-128678397) and my reproduction, it would seem that something isn't fully completing when we unlink GitHub access. We still have to remove access from GitHub's side to unlink and re-link an account.

**Comment by rrarunan** [comment]
This is part of the workflow, as per discussion with @kencochrane. I vote for closing this one. @ChristopherBiscardi ?

**Comment by ChristopherBiscardi** [comment]
@rrarunan We should make this ticket improving the message that is presented when unlinking your account. WDYT?

**Comment by rrarunan** [comment]
I agree. :+1:.. Let's do it.
