### ISSUE TITLE
Unexpected EOF reading trailer when listing tags with v2 API

### ISSUE THREAD

**Issue by beornf** [docker/hub-feedback#1960]
I am getting intermittent registry v2 API slow (> 30 seconds) and partial responses when listing public tags for the official Golang repository.

First retrieving an access token with:
`https://auth.docker.io/token?service=registry.docker.io&scope=repository:library/golang:pull`

Then using the access token to query for all tags on:
`https://registry-1.docker.io/v2/library/golang/tags/list`

Is this due to many tags (1401) being present in this repository? I attempted to use pagination with `https://registry-1.docker.io/v2/library/golang/tags/list?n=100` but all tags are being returned.

Is this due to rate limiting of the same IP? I can cache "200 - ok" registry responses on the client side. However this wouldn't appear to be the case as I have only received "200 - ok" responses and not "429 - too many requests".

Appreciate your advice on how to reliably query for the latest tags. Otherwise I can create a cache to manually check for tags hourly (although why not push tags and metadata to some CDN on updates).

**Comment by manishtomar** [comment]
Hmm, this is not good. Will investigate and get back. Meanwhile, you can get all the tags from hub.docker.com/v2/repositories/library/golang/tags/. However, please be mindful of the API and do not run it in a loop/script on a continuous basis :)
