### ISSUE TITLE
Allow organizations to require two factor auth for all members

### ISSUE THREAD

**Issue by mlissner** [docker/hub-feedback#1961]
## Problem description

When I add people to my organization on Docker Hub, I don't have a way of forcing them to enable 2FA, nor of checking that they have it set up. This means that sooner or later one of our members of our org won't have 2FA set up, leading to a potential issue. 

## Solution

Github has a feature that allows an organization to require 2FA on all member accounts:

https://help.github.com/en/github/setting-up-and-managing-organizations-and-teams/requiring-two-factor-authentication-in-your-organization

It'd be great if Docker Hub had something similar.

**Comment by manishtomar** [comment]
Thanks. This is good feedback. We would like to implement it but cannot tell when this will come.

**Comment by thaJeztah** [comment]
@mlissner perhaps you can open a ticket for this in our new public roadmap; https://github.com/docker/roadmap/issues

**Comment by mlissner** [comment]
@thaJeztah Can somebody just transfer it? Github issues can be moved across repos these days. Or does it need to be in both places?

**Comment by thaJeztah** [comment]
It could be moved, but the other repository uses an issue template, so would be great if you could use the template for that

**Comment by mlissner** [comment]
Very well, will do, thanks.

**Comment by thaJeztah** [comment]
Thanks!!
