### ISSUE TITLE
Organisation - linked account - unable to deactivate

### ISSUE THREAD

**Issue by mattseymour** [docker/hub-feedback#1969]
## Problem description
Unable to disconnect provider link between github account and a dockerhub organisation account.

The following URL is being POST-ed too `https://hub.docker.com/api/tutum/v1/mattseymour/credentials/unlink/github/` with empty payload`--data '{}'`.

Any ideas on how to unlink the accounts?

**Comment by mattseymour** [comment]
**Update:**

So the issue looks like its to do with the URL which is being called to perform the POST. Changing the url to include the Org name instead of my user account name resulted in the organisation account deactivating its link with github.
```
await fetch("https://hub.docker.com/api/tutum/v1/<**orgname**>/credentials/unlink/github/", {
    "credentials": "include",
    "headers": {
        ...
    },
    "referrer": "https://hub.docker.com/orgs/<**orgname**>/settings/linked-accounts",
    "body": "{}",
    "method": "POST",
});```

**Comment by stronk7** [comment]
Yeah, can confirm this is borked in the organizations UI, and it's impossible to disconnect from there (in the other side, user disconnect work ok).

Thanks for the trick about replacing the request to orgname, that did the trick here and I've been able to disconnect as org.

Ciao :-)
