### ISSUE TITLE
Push error: denied: requested access to the resource is denied

### ISSUE THREAD

**Issue by Robert-Forrest** [docker/hub-feedback#1975]
Hi,

All of my builds on dockerhub are failing to push with the following error, after successfully building the image:

```
....
Successfully built 41371458293e
Successfully tagged {organization}/{image}:latest
Pushing index.docker.io/{organization}/{image}:latest...
Push failed. Attempt 2 in 60 seconds.
Push failed. Attempt 3 in 60 seconds.
Push failed. Attempt 4 in 60 seconds.
Push failed. Attempt 5 in 60 seconds.
{u'message': u'denied: requested access to the resource is denied'}
```

This is happening for multiple images, with some retries of the same image, over the course of several hours now.

I have tried locally building the image and pushing, but I get a similar error when trying to push after having successfully built and properly tagged the image:
```
The push refers to repository [docker.io/{organization}/{image}]
3f7574718a03: Preparing
408e1ad6916f: Preparing
02ec60ffb439: Preparing
06bb37f8840f: Preparing
28bf756b6f8e: Preparing
4c299e1e70d5: Waiting
f1b5933fe4b5: Waiting
denied: requested access to the resource is denied
```

My account has admin privileges in the organization, as does the account used for the autobuilds on dockerhub which are failing.

**Comment by manishtomar** [comment]
Has this started occurring recently? Are you using password or token? Are you able to push to your personal namespace? Is it succeeding at least once when you try multiple times? Please provide your username.

**Comment by Robert-Forrest** [comment]
The first failed build with this issue I can identify was April 7, 2020 06:53 PM (BST)

I am using a username and password to login when attempting to push via the Linux cli, however this issue is also present with the automated builds using dockerhub's infrastructure.

I did not have any repositories in my personal namespace, and so have created one which I can indeed push to.

The pushes to the organization repositories never succeed.
My username is: robertforrest

**Comment by manishtomar** [comment]
Thanks for the info. Can you provide your organization name that is having trouble? Also, just to rule out options can you create a personal access token and try to push using that?

**Comment by Robert-Forrest** [comment]
The organization name is: materialsdiscoveryhub
I'll try a personal access token and report back, thanks for the speedy response!

**Comment by Robert-Forrest** [comment]
I have created and logged in with a new personal access token, and still cannot push to the organization repositories.

**Comment by Robert-Forrest** [comment]
In case it is helpful, a similar issue has been reported in the same timeframe on the docker forum: https://forums.docker.com/t/push-fails-denied-requested-access-to-the-resource-is-denied/91957

**Comment by manishtomar** [comment]
Can you print out the output of following command? Please replace the repo with your org repo and `username:password` with your credentials.
```
jwt decode $(curl -u "username:password" "https://auth.docker.io/token?service=registry.docker.io&scope=repository:library/alpine:push" | jq -r .token)
```
The jwt cli is from https://github.com/mike-engel/jwt-cli

**Comment by Robert-Forrest** [comment]
Output when scope is an organization repository which I cannot push to:

```
Token header
------------
{
  "typ": "JWT",
  "alg": "RS256"
}

Token claims
------------
{
  "access": [],
  "aud": "registry.docker.io",
  "exp": 1586329327,
  "iat": 1586329027,
  "iss": "auth.docker.io",
  "jti": "r0I9p_pG_Kp_dV41P-Sc",
  "nbf": 1586328727,
  "sub": "59fc5932-fe5f-4540-a20f-fcfedac77e34"
}
```

Output when the scope is a repository in my personal namespace which I can successfully push to:
```
{
  "access": [
    {
      "actions": [
        "push"
      ],
      "name": "robertforrest/test",
      "type": "repository"
    }
  ],
  "aud": "registry.docker.io",
  "exp": 1586329314,
  "iat": 1586329014,
  "iss": "auth.docker.io",
  "jti": "MaFqThHN3kKB1qpEi6Kr",
  "nbf": 1586328714,
  "sub": "59fc5932-fe5f-4540-a20f-fcfedac77e34"
}
```

**Comment by Robert-Forrest** [comment]
A further potentially related issue is that dockerhub occasionally thinks the organization has 0 allowance for private repositories. We are currently using 14, and pay for an allowance of 20. However, when I go to make a new repository, I see the following message:
![privaterepos](https://user-images.githubusercontent.com/42879091/78767319-5b23be80-7982-11ea-987d-0580fff0bab2.PNG)

We recently downgraded our plan due to a consolidation of images meaning we required fewer private repositories.
![allowance](https://user-images.githubusercontent.com/42879091/78767552-a8079500-7982-11ea-979e-056777238e25.PNG)

**Comment by manishtomar** [comment]
Thanks for the info. This does look like a problem. We will investigate and get back.

**Comment by Robert-Forrest** [comment]
We've unfortunately had to seek an alternative solution so that we can resume working (Jenkins+local registry). Thanks anyway for looking into the issue, and I hope it is fixed for future users.

**Comment by manishtomar** [comment]
@Robert-Forrest We have root caused the private repos issue and hope to deploy a fix today. However, I am not sure how why you are not able to push to a existing repo. I impersonated you using internal technique and able to simulate a push. Could you please try this command again and paste the command along with the output? Please redact your password before pasting here.
```
jwt decode $(curl -u "username:password" "https://auth.docker.io/token?service=registry.docker.io&scope=repository:library/alpine:push" | jq -r .token)
```

**Comment by manishtomar** [comment]
Also if possible could you create a public repo and try that command again? Thanks!
