### ISSUE TITLE
Unable to push private repository to Docker Hub

### ISSUE THREAD

**Issue by harshit-mishra** [docker/hub-feedback#1976]
Problem: **denied: requested access to the resource is denied.**

Expected behaviour: Docker should push the private repository.

Steps:
1) Created a build from Jenkins.
2) logged into docker via docker login
3) docker push username/repository:tag-name
 *Already checked image exists using command **docker images**
Result:

The push refers to repository [docker.io/{..}/{..}]

8f641b012f1d: Preparing

faab1b638469: Preparing

71dbf3e3316d: Preparing

12c374f8270a: Preparing

0c3170905795: Preparing

df64d3292fd6: Waiting

Note: We already have paid account with plan for private repositories. The plan is for 10 repositories. I tried checking on the account it shows different repos used everytime we login.
currently, it shows **-6 private repositories available**, yet push always keeps failing.

We have tried multiple solutions provided on Github but none of them work for us. 
Also reported the same issue on docker hub forum. for your reference
https://forums.docker.com/t/push-fails-denied-requested-access-to-the-resource-is-denied/91957

**Comment by manishtomar** [comment]
Thanks for the report. We will investigate and get back.

**Comment by manishtomar** [comment]
@harshit-mishra Can you print out the output of following command? Please replace the repo with repo you are trying to push and `username:password` with your credentials. Please be careful and do not post your credentials here.
```
jwt decode $(curl -u "username:password" "https://auth.docker.io/token?service=registry.docker.io&scope=repository:library/alpine:push" | jq -r .token)
```
The jwt cli is from https://github.com/mike-engel/jwt-cli.

**Comment by harshit-mishra** [comment]
@manishtomar  printing the output for the above-mentioned command.

Token header
------------
{
  "typ": "JWT",
  "alg": "RS256"
}
Token claims
------------
{
  "access": [],
  "aud": "registry.docker.io",
  "exp": 1586509174,
  "iat": 1586508874,
  "iss": "auth.docker.io",
  "jti": "8bKWIHT6pSRy4B7h-YUh",
  "nbf": 1586508574,
  "sub": "d1d6a222-e909-4ca0-a8dc-43937846044f"
}

**Comment by manishtomar** [comment]
Thanks. We've identified the cause for billing discrepancy and are planning to deploy a fix today. However the push should not fail. To debug this further can you temporarily create a public repo and try pushing? Please try the above command with that public repo and paste the command and its output here. Please redact the password before pasting.

**Comment by manishtomar** [comment]
@harshit-mishra We have deployed a fix for the billing discrepancy. Can you please check if it shows correct number of private repos?

**Comment by manishtomar** [comment]
@harshit-mishra Please post the org name that is having issue. There is a misconfiguration in your account that I need to fix.

**Comment by harshit-mishra** [comment]
@manishtomar  Organization name - **healthi**
Also, Billing info is coming correctly now and we will shortly give the output of pushing to docker public repo.

**Comment by manishtomar** [comment]
@harshit-mishra I've fixed your account. Please check.

**Comment by harshit-mishra** [comment]
@manishtomar Thanks checked I'm able to push now.

**Comment by manishtomar** [comment]
Good to know. Apologies for the inconvenience.
