### ISSUE TITLE
[URGENT] Unable to push and pull private repository to/from Docker Hub

### ISSUE THREAD

**Issue by dhyaniarun1993** [docker/hub-feedback#1977]
Hello team,

While pushing the image to the private repository in docker hub, I am getting the following error:
**denied: requested access to the resource is denied**

While pulling the image from the private repository in docker hub, I am getting the following error:
**Error response from daemon: pull access denied for my-private-repo, repository does not exist or may require 'docker login': denied: requested access to the resource is denied**

Everything was working fine 10 hrs ago. I have tried this from different platforms, after logout and logging in, But still facing the same issue. 

Organization: clinikkhealthcare
User: dhyaniarun

Please help us out on priority. We are blocked on this.

**Comment by manishtomar** [comment]
@dhyaniarun1993 Can you print out the output of following command? Please replace the repo with repo you are trying to push and `username:password` with your credentials. Please be careful and do not post your credentials here.
```
jwt decode $(curl -u "username:password" "https://auth.docker.io/token?service=registry.docker.io&scope=repository:library/alpine:push" | jq -r .token)
```
The jwt cli is from https://github.com/mike-engel/jwt-cli. Please run the same with `pull` and paste the output here.

**Comment by manishtomar** [comment]
If you don't want to paste your private repo name can you try with a new test private repo?

**Comment by dhyaniarun1993** [comment]
@manishtomar : 

{
  "typ": "JWT",
  "alg": "RS256"
}

Token claims
------------
{
  "access": [],
  "aud": "registry.docker.io",
  "exp": 1586629556,
  "iat": 1586629256,
  "iss": "auth.docker.io",
  "jti": "-KFT_WNTzl3BkwU69uGY",
  "nbf": 1586628956,
  "sub": "64879166-781a-44ec-8093-0b2d76a21df5"
}

**Comment by manishtomar** [comment]
Can you paste the command also?

**Comment by dhyaniarun1993** [comment]
jwt decode $(curl -u "dhyaniarun:password" "https://auth.docker.io/token?service=registry.docker.io&scope=repository:clinikkhealthcare/oauth-service:push" | jq -r .token)

**Comment by manishtomar** [comment]
Thanks. I've added myself https://hub.docker.com/u/manisht as owner in your org to debug this. Please don't be alarmed.

**Comment by dhyaniarun1993** [comment]
Sure.

**Comment by manishtomar** [comment]
OK. It should be working now. Can you please try again?

**Comment by dhyaniarun1993** [comment]
Checked. Seems to working fine now.

**Comment by manishtomar** [comment]
Good to know. I removed myself from the org. However I cannot delete https://hub.docker.com/repository/docker/clinikkhealthcare/testpublic repo that I created for debugging. Kindly remove it. I'll close this issue. Sorry for the inconvenience.
