### ISSUE TITLE
2 Factor Authentication

### ISSUE THREAD

**Issue by vinodj** [docker/hub-feedback#1978]
There is no problem - just wondering how to setup a current Yubikey with Docker instead of using the authenticator app

**Comment by ChristophShyper** [comment]
See the bottom of: https://www.docker.com/blog/designing-docker-hub-2fa/
They only plan to introduce WebAuthn. So we still need to wait.

**Comment by thaJeztah** [comment]
Perhaps you can open a ticket on our public roadmap; that roadmap is also used to prioritise features that are much requested; https://github.com/docker/roadmap/issues

Related: There's one roadmap ticket already for enforcing 2FA for an organisation (https://github.com/docker/roadmap/issues/40)
