### ISSUE TITLE
Quick Filter for Repos

### ISSUE THREAD

**Issue by ChristopherBiscardi** [docker/hub-feedback#198]
It would be useful to be able to "quick filter" the lists of repos that are displayed on the site.

**Comment by rrarunan** [comment]
+1

**Comment by ofir-petrushka** [comment]
Currently there is no way to search for private repos.
This service becomes unusable without it.
I would migrate our accounts if this isn't resolved soon one way or another.

**Comment by ymote** [comment]
+1, the new UI is a disaster. I don't know the rational behind the changes. It is ugly and not usable. Please let me roll back to the old version.

**Comment by oryband** [comment]
related to #32

**Comment by oryband** [comment]
what is going with this feature? private repo search doesn't work for so long! the website is horrible.

**Comment by rrarunan** [comment]
There is a way to filter your private repositories, which was deployed as mentioned in #199. 
<img width="953" alt="screen shot 2015-12-20 at 4 33 34 pm" src="https://cloud.githubusercontent.com/assets/201193/11921148/875e2bec-a737-11e5-8bdc-bd2f7e785ac9.png">

The above screen is available in the user/organization dashboard.

**Comment by oryband** [comment]
finally! private search appeared to have been fixed!

**Comment by rrarunan** [comment]
Closing as per update in #199
