### ISSUE TITLE
Accidentally deleted account, need it reactivated

### ISSUE THREAD

**Issue by ddutt** [docker/hub-feedback#1982]
## Problem description
I created a docker hub account today, that I deleted because I wanted an organization, not a user. I didn't realize I could transfer a user account to an organization. Now I cannot get the username  due to "account needs to be activated". 

Could you please activate the dockerid associated with dinesh@stardustsystems.net. 
Thanks,
Dinesh

**Comment by ddutt** [comment]
I did send mail to support asking for reactivation this morning, and haven't heard back yet.

**Comment by ddutt** [comment]
Its been 3 days since I contacted support to reactivate my dockerid, but have received no response. Could you please help? Thank you.

**Comment by kbariotis** [comment]
@ddutt did you have any luck with that? I've been waiting too and I see requests like these in other places as well.

**Comment by ddutt** [comment]
Nope, no news. Its just terrible this support

**Comment by nebuk89** [comment]
@ddutt hey did you get this sorted? If not can you drop a new email to support and then ping me an email with your case number to bengotch@docker.com -> thanks!

**Comment by kbariotis** [comment]
thank you @nebuk89, I got it sorted.
