### ISSUE TITLE
Add support for automated multi-arch builds

### ISSUE THREAD

**Issue by maxromanovsky** [docker/hub-feedback#1983]
## Problem description

Currently only amd64 linux automated builds are supported.
Please add support for multi-arch automated builds.

Maybe a duplicate of #1779. But that issue was just closed, so I wonder how to track progress of the request.

**Comment by tyranron** [comment]
Another one: https://github.com/docker/hub-feedback/issues/1874

**Comment by rednoah** [comment]
+1

**Comment by maxromanovsky** [comment]
Duplicate of #1874
