### ISSUE TITLE
Build from github stuck after "done", stuck trying to cancel

### ISSUE THREAD

**Issue by jberryman** [docker/hub-feedback#1984]
After reporting "done", no build was available after over an hour. I'm now canceling, but that seems stuck too.

There are at least half dozen similar issues reported over the last few months

![dockerhub](https://user-images.githubusercontent.com/210815/80518133-12916c80-8954-11ea-9bfa-4bff07397f92.png)

**Comment by semionk-jomedia** [comment]
experiencing the same issue here. any one knows whats up?

**Comment by salokas** [comment]
Same here..

**Comment by Bernd-L** [comment]
When will this be fixed?

**Comment by mcarans** [comment]
I have a hanging build again and have had this several times previously. In the absence of a fix for the hanging, I think there needs to be a way to force kill a build as cancelling doesn't seem to help.

**Comment by Darkatek7** [comment]
Still an issue
