### ISSUE TITLE
'Details' on PR Status Check Redirects to 404 Not Found on hub.docker.com

### ISSUE THREAD

**Issue by nevrending** [docker/hub-feedback#1985]
## Problem description
This has been happening for a few months now.
Clicking on `Details` on a status check item in a PR (to check it's details or error messages), will ALWAYS redirects to a 404 Not Found page on hub.docker.com

This is very inconvenient as if something fails, we need to go to hub.docker.com and search manually for that failed build to see the logs.

The URL on `Details` is something like `https://hub.docker.com/redirect/?resource_uri=/api/audit/v1/action/<UUID>/`
After clicking it, will be redirected to `https://hub.docker.com/login/?next=/redirect/%3Fresource_uri%3D/api/audit/v1/action/<UUID>/` and met with 404 Not Found page

![image](https://user-images.githubusercontent.com/4745298/80562000-a8e39200-8a29-11ea-8c53-5c74749fbf67.png)

cc @dendisuhubdy @ujang360

**Comment by thaJeztah** [comment]
Looks like this has the same underlying problem as https://github.com/docker/hub-feedback/issues/1957. Let me close this one to prevent the discussion from diverging

**Comment by nevrending** [comment]
> Looks like this has the same underlying problem as #1957. Let me close this one to prevent the discussion from diverging

No problem, thanks for responding.

**Comment by ibrahima** [comment]
Hmm, I'm still seeing this issue with the status details even though #1957 was closed, is anyone else seeing that too?

**Comment by Habbie** [comment]
Still seeing this.
