### ISSUE TITLE
I deleted my account and now I cant create new one

### ISSUE THREAD

**Issue by tananga** [docker/hub-feedback#1986]
Hi. Deactivated my account on docker hub because I took wrong username. I wanna chenge that but It's not possible. So I deleted my account and now when I want to create new account Im getting "This email is already in use." during a registragion. Please can someone tell me what to do ?

**Comment by Ntimesp** [comment]
Same here, I followed the method mentioned by @alexkuc [](https://github.com/docker/hub-feedback/issues/1834#issuecomment-555780489) and it works for me.

**Comment by thaJeztah** [comment]
Let me close this as it looks like there's a workaround in https://github.com/docker/hub-feedback/issues/1834#issuecomment-555780489
