### ISSUE TITLE
Missing Dockerfile and no Builds triggered when linked to Github

### ISSUE THREAD

**Issue by vace117** [docker/hub-feedback#1988]
## Problem description
I have created a new repository and linked it to my public Github repo. I expected that this would make the Dockerfile visible, and that it would trigger builds every time I push to my Git repo.

Neither one of the above is happening, even though my Github repo is correctly listed under "Source Repository"

Dockerhub Repo: https://hub.docker.com/r/vace117/calibre-dedrm/dockerfile
Github repo: https://www.github.com/vace117/calibre-dedrm-docker-image

**Comment by badouralix** [comment]
Hi @vace117 ! As far as I can see, no autobuild happened on your repo yet, and this is likely the reason why the dockerfile is not visible 

<img width="1552" alt="image" src="https://user-images.githubusercontent.com/19719047/82739811-28bbfe00-9d43-11ea-9636-cee7866d7a5e.png">

Just make sure automated builds are enabled and you should be good to go : https://docs.docker.com/docker-hub/builds/

Here is an example of a working repo https://hub.docker.com/r/badouralix/toolbox/dockerfile

<img width="1552" alt="image" src="https://user-images.githubusercontent.com/19719047/82739838-7df80f80-9d43-11ea-9b49-de91a46e9277.png">

**Comment by fightforlife** [comment]
I currently have the same problem. 
Builds are not started, manually or autmatic. Configuration is exactly as above.
