### ISSUE TITLE
Lost ability to search own's private repositories

### ISSUE THREAD

**Issue by f-wong** [docker/hub-feedback#199]
When trying to use the search box in the top right corner, it only returns public repos not even associated to our organization account. This used to work before.

**Comment by andymotta** [comment]
+1

**Comment by kencochrane** [comment]
@f-wong we have always only showed public repos in the search, we do not index private repos for risk of leaking those repos accidentally. we hope to add that in the future, but it isn't supported today.

**Comment by kencochrane** [comment]
@f-wong let me start over, are you talking about filtering your repos in your repo page, or searching across the site?

**Comment by ymote** [comment]
I have 100+ private repo. How can I search through those repos and filtering the result?

**Comment by yagilm** [comment]
+1 filtering or searching through the private repositories is a must have. (I have to go through all the pages to find the correct repo)

**Comment by kencochrane** [comment]
@rrarunan do you have an ETA on when filtering will get to production?

**Comment by rrarunan** [comment]
@f-wong @ymote @yagilm @kencochrane @andymotta There is a way now to filter your private repositories on demand in the dashboard. You will see all your repos and can filter by name when you decide to use the filter. Let me know if you have any questions.
