### ISSUE TITLE
Mining Malware Image

### ISSUE THREAD

**Issue by subodhp** [docker/hub-feedback#1990]
## Problem description
Malicious Mining Image at DockerHub - "trezrez1187sourtour/ubuntu14.01"

## Security Issues
Please remove the image repo ASAP if it hasn't been yet.

**Comment by meridsa** [comment]
## Security Issues
If you are reporting about security vulnerability in the site or about some malicious image that
should be taken down ASAP then please report it via email to security@docker.com.

**Comment by meridsa** [comment]
I have emailed them. I'll see if they respond.

**Comment by manishtomar** [comment]
I believe this user has been deactivated. Closing.
