### ISSUE TITLE
Unbinding Email Address from Deactivated Account

### ISSUE THREAD

**Issue by zzc-tongji** [docker/hub-feedback#1991]
I would like to change my docker hub username, so I have to deactivate the account and register a new one.

It seems that it does not allow me to use the email address of the deactivated account to register a new one.

Could you help to unbind the email address from the account `sulfonamide`?

(PS: I have filled the [form](https://hub.docker.com/support/contact/) several times but there is no response.)

**Comment by nebuk89** [comment]
Hey, we had an issue with this the email address should now be unbound. Please submit a new support ticket if this is not the case. Thanks
