### ISSUE TITLE
Team Repository Permissions not visable and incorrect error messages on permission updates

### ISSUE THREAD

**Issue by meridsa** [docker/hub-feedback#1992]
## Problem description

I am an admin for an organization and manage permissions for teams. Team's repository permissions are not visible to me and when I try to give a team new permissions I am greeted with an error message stating "Unable to update repository permissions. Try again later.". However, team-members report being granted permissions in question, despite the error message. Note I am using the web-client.

#### TL;DR
- Using web client
- Cannot see a team's permission as an organization's admin.
- Erroneous error message when chaning team's permissions, stating "Unable to update repository permissions. Try again later." although permissions are in fact granted.

## Details
- OS: macos 10.14.6
- Browser: Firefox 76.0.1 (64-bit)
- URL: https://hub.docker.com/orgs/**ORG**/teams/**TEAM**
- Date: 12-13.05.2020
- Hub username: will send on request
### Screenshots
![bilde](https://user-images.githubusercontent.com/35993351/81803185-9d0eca00-9517-11ea-83cf-760d4266a391.png)
Team "developers" seem to not have any permissions though they in matter of fact do

![bilde](https://user-images.githubusercontent.com/35993351/81803371-e232fc00-9517-11ea-8621-8d7aa84360ef.png)
Trying to grant permission gives this error message, however the team members report being granted permission despite this.

### Additional comments
Seems odd to have to file bug-reports in a publically viewable place.

**Comment by manishtomar** [comment]
This is bad. Thank you for reporting it. We are investigating it.

**Comment by manishtomar** [comment]
This has been fixed. Can you please check?

**Comment by meridsa** [comment]
Perfect! Works beautifully, thanks!
