### ISSUE TITLE
Option to convert account to organization doesn't exist even though mentioned in documentation still.

### ISSUE THREAD

**Issue by GrahamDumpleton** [docker/hub-feedback#2001]
## Problem description

Documentation at:

* https://success.docker.com/article/how-do-i-convert-my-docker-hub-user-account-into-an-organization-account

explains process for converting account to an organization but no such option exists on the account settings page.

Conversion of accounts to organization also mentioned on page:

* https://docs.docker.com/docker-hub/orgs/#access-an-organization

but process not explained. The google search link which directed to that page seems to have actually been going to:

* https://docs.docker.com/docker-hub/convert-account/

but that page no longer exists so was redirected. The cached version of the page in Google is:

https://webcache.googleusercontent.com/search?q=cache:4nE20IxlKPMJ:https://docs.docker.com/docker-hub/convert-account/+&cd=7&hl=en&ct=clnk&gl=au&client=firefox-b-d

That page shows different UI than first link, where conversion was a separate tab:

![image](https://user-images.githubusercontent.com/507637/83366784-8a8c0000-a3f4-11ea-8145-6699f697bdcf.png)

but that is now gone.

Has the feature to convert accounts to organizations been removed and this process is no longer possible?

**Comment by manishtomar** [comment]
We disabled this temporarily due to internal complications. We will be enabling it back again next week

**Comment by ianbranda** [comment]
> We disabled this temporarily due to internal complications. We will be enabling it back again next week

I'm still having this issue two years later. Any updates?
