### ISSUE TITLE
Periodic connection failure

### ISSUE THREAD

**Issue by ThatNerdyPikachu** [docker/hub-feedback#2002]
When pulling images from Docker Hub, I periodically get ``docker: Error response from daemon: Get "https://registry-1.docker.io/v2/": dial tcp: lookup registry-1.docker.io on [::1]:53: read udp [::1]:60040->[::1]:53: read: connection refused.``. It's usually resolved if I run the command I was trying to run multiple times, but this has been happening for over a year. I've searched for solutions with no luck.

**Comment by binman-docker** [comment]
Your connection to your DNS server is periodically failing when doing a lookup. This is happening before your machine attempts to connect to Hub so there's nothing we can do on our side to fix it. 

One easy thing to test would be to change your DNS server to one of the many free providers out there (OpenDNS on 208.67.222.222, Cloudflare on 1.1.1.1, Google on 8.8.8.8, etc). If you still have failures, then it's an issue with your local network or machine.
