### ISSUE TITLE
Docker Hub Max 32-bit Integer Reached

### ISSUE THREAD

**Issue by Keimeno** [docker/hub-feedback#2003]
## Problem description
Docker Hub is using a 32-bit integer to count the number of times an image has been pulled. However, the pull count of some images is higher than 2.147.483.647, e.g. https://hub.docker.com/_/redis, and you can find the exact amount of pulls here https://hub.docker.com/v2/repositories/library/redis/

**Comment by manishtomar** [comment]
We are aware about this issue. However we cannot commit when it will be fixed.

**Comment by aeneasr** [comment]
Dupe #1946

**Comment by emilevauge** [comment]
Hello there!
Any news on this?
[Traefik](https://hub.docker.com/_/traefik) just reached this limit too, this is pretty annoying 😢
Thanks!

**Comment by SantoDE** [comment]
Hey @manishtomar,

any updates on this? :) Is there something we can do? :)

**Comment by manishtomar** [comment]
Apologies I don't work for Docker anymore. Maybe @ddebroy can help answering this.

**Comment by thaJeztah** [comment]
This issue should now be fixed on Docker Hub, so let me go ahead and close 👍
