### ISSUE TITLE
Unexpected EOF when pulling older images

### ISSUE THREAD

**Issue by leedm777** [docker/hub-feedback#2004]
## Problem description

We have some legacy images that are based on some pretty old Docker Hub images. Recently we've seen intermittent "unexpected EOF" errors when trying to pull these images. At first we thought this was network glitches, but we've discovered that we can successfully pull other images while these older images fail to pull.

Two images we've specifically had problems with lately have been `php:5.4-cli` and `mariadb:5.5.42`.

```sh
$ docker pull php:5.4-cli
Error response from daemon: unexpected EOF

# try a few more times; eventually it works

$ docker pull php:5.4-cli
5.4-cli: Pulling from library/php
Image docker.io/library/php:5.4-cli uses outdated schema1 manifest format. Please upgrade to a schema2 image for better future compatibility. More information at https://docs.docker.com/registry/spec/deprecated-schema-v1/
<snip/>
```

**Comment by manishtomar** [comment]
Can you please try now? I think it should be fixed.

**Comment by leedm777** [comment]
Yeah, things are working now. Feel free to close this ticket.

But, as I said, it's been an intermittent issue. If it happens again, should I post to this ticket or create a new one?

**Comment by manishtomar** [comment]
Please feel free to reopen it. We are working on mitigating it. I'll close it when that is done.

**Comment by manishtomar** [comment]
This has been fixed.
