### ISSUE TITLE
API permission issues with personal access tokens

### ISSUE THREAD

**Issue by jjlin** [docker/hub-feedback#2006]
I'm trying to delete some image tags via the Docker Hub REST API, since AFAIK, the Docker CLI doesn't support this operation. I get a JWT using the method described at https://success.docker.com/article/how-do-i-authenticate-with-the-v2-api. However, if I use a personal access token as the password for getting the JWT, then calling
```
curl -sS -X DELETE \
         -H "Authorization: Bearer ${jwt}" \
         "https://hub.docker.com/v2/repositories/${repo}/tags/${tag}/"
```
returns a 403 error with message
```
{"detail": "access to the resource is forbidden with personal access token"}
```
It works fine if I get the JWT using the actual account password.

Is there a particular reason for this restriction against personal access tokens? It seems like it would also break users who have 2FA enabled on Docker Hub.

**Comment by manishtomar** [comment]
Personal access token is restricted to registry APIs only (docker login). It does not allow accessing all APIs because doing that will bypass 2nd factor when an account is 2FA enabled. We want to eventually add fine-grained permission associated with each token similar to Github.

**Comment by manishtomar** [comment]
I've created roadmap item that addresses this. https://github.com/docker/roadmap/issues/115. I am closing this for now. Please consider upvoting that.

**Comment by christian-kreuzberger-dtx** [comment]
I'm trying to automate deleting old unused tags (created by the CI) and ran into the same issue.

So the only workaround for now is to use my username and actual password and disable 2FA?

**Comment by zhangguanzhang** [comment]
same issue in github action, but works on my pc 😢
