### ISSUE TITLE
Cannot delete old tags

### ISSUE THREAD

**Issue by thokari** [docker/hub-feedback#2008]
## Problem description
Cannot delete old tags from DockerHub.

## Docker Hub Account Issues
I am writing a script to clean up old tags from DockerHub. I searched on stackoverflow, and there were many examples to be found, but none of them worked.
Most notably this one didn't:
https://stackoverflow.com/a/59334315/1293709
When I tried to do it via the DockerHub frontend, it also would not work, and I am seeing a similar `403 Forbidden` error in the network tab of my browser, as I am receiving when running the script that I assembled. The fact that it fails when doing it manually from the frontend suggests that there is a more general problem here, that is not related to my script...

**Comment by rsaffi** [comment]
I myself am getting a `405 Method Not Allowed` when doing something similar.

I'm basically trying to setup on my CI a cron job to regularly clean-up old build from Pull Requests and would rely on this for deletion of the tags, but can't make this work. :-(

**Comment by thokari** [comment]
I could solve this, it turned out that `403 Forbidden` was actually the result of not having administration permissions on the account that I was using.

**Comment by rsaffi** [comment]
But wait: you're using Docker Hub and you're able to delete tags via the API? Can you elaborate on how you're doing it, please? I am using an account with `owner` role and I'm still getting the `405`.

**Comment by thokari** [comment]
You should be able to see he requests in the browser.
Open the network tab, then:
1. Log in
2. Navigate to the "Tags" page
3. Delete a tag
If you have the proper permissions in the browser, you will see the requests that are being made, and then you can turn them into a script.
