### ISSUE TITLE
Cannot reuse email for new dockerhub account

### ISSUE THREAD

**Issue by SiegfredRodriguez** [docker/hub-feedback#2014]
I was trying to deactivated my account for docker id changing purposes,
however i still get the "email already used error" when i try to re register.

I have deactivated my account two weeks ago and
waited for email deletion email, however i didn't get any.

I already emailed support, but still no response.

**Comment by heyrudy** [comment]
I have the same issue. And yet they never response back. I do feel we need coorporate tool more than open source tool without any kind of support. I don't understand why they need to keep our email or dockerID in their product database.
Ifile in issue and I hope we reach out to someone quickly.
#2022

**Comment by migrant** [comment]
I have the same problem. Now neither can I register a new account with my email nor login in my old account.

**Comment by FranchommeE** [comment]
duplicates #1834

**Comment by technicallyjosh** [comment]
Hey @SiegfredRodriguez I've updated a similar ticket with information about fixes for this 😄
