### ISSUE TITLE
Deleting repository doesn't delete manifest

### ISSUE THREAD

**Issue by KerberosMorphy** [docker/hub-feedback#2017]
**Description**

I don't know if it's more a docker cli or docker hub issues.

I'm trying to make a GitHub Action to check if a specifique docker image exist or not using `docker manifest inspect ...`.
I was using Docker Hub as registry and was doing some test by deleting the repository and try to inspect the manifest again.
I was expecting a `no such manifest` error but I get a manifest instead. 
Is it normal that manifest wasn't delete with repository?

**Steps to reproduce the issue:**
1. Push image on Docker Hub registry
2. Delete everything related to this in Docker Hub
3. docker login && activate experimental feature
4. Inspect the deleted image `docker manifest inspect ...`

**Describe the results you received:**

The manifest still exist even if I delete the repository.

**Describe the results you expected:**

The manifest shouldn't exist since the repository as been deleted.

**Additional information:**

You must be log with the account that own the repository even if it was public.

**Comment by manishtomar** [comment]
Hmm, this shouldn't be possible. Can you also pull from the delete repository?

**Comment by manishtomar** [comment]
I think there might be some delay. Can you please try after a minute or so before fetching the manifest again?

**Comment by KerberosMorphy** [comment]
I cannot pull from the deleted repository.
I retry today and no manifest was found 5s after I delete the repository... the other day I has found the manifest even after 5 minutes. 
I guess it was a due to some delay, I cannot explain it more why the big difference.
I'll close my issue since I cannot reproduce it anymore and the all seems now normal.
