### ISSUE TITLE
Does deleting a repository also delete it on Github

### ISSUE THREAD

**Issue by cereallarceny** [docker/hub-feedback#2020]
## Problem description
The title of the question is pretty self-explanatory: **if I delete a repository, does it also delete the code repository on Github?**

I'm afraid to delete an old Dockerhub repo for fear it will also delete the source codebase. Perhaps this could be made more clear in the delete repository section on Dockerhub. 😄

**Comment by manishtomar** [comment]
No. We do not delete the github repo. I am not sure we even have permission to do so.
