### ISSUE TITLE
Unable to delete my two Docker ID

### ISSUE THREAD

**Issue by heyrudy** [docker/hub-feedback#2022]
## Problem description
Hi,
I would like to delete my docker accounts associated to these 2 dockerIDs : turing00 and heyrudy101, because I already have another docker account. Can you please delete these 2 docker account with dockerIDs : turing00 and heyrudy101 ?
I am available to provide additional information as I already logged these issue to docker support team.

How long would it take to review and delete my account ?

Thanks upfront.

**Comment by nebuk89** [comment]
Hey this should now be complete.
Please open a new support ticket if needed for account support
