### ISSUE TITLE
docker: no matching manifest for unknown ... when pulling from my multi-platform buildx repo

### ISSUE THREAD

**Issue by ballerburg9005** [docker/hub-feedback#2024]
## this works

On my PC:
```
docker buildx build --platform linux/arm64 --push -t ballerburg9005/xonotic-server-arm64:arm64 .
```
My ARM Box:
```
docker run ballerburg9005/xonotic-server-arm64:arm64
```

## this doesn't work

On my PC:
```
docker buildx build --platform linux/arm64,linux/arm64 --push -t ballerburg9005/xonotic-server-arm64 .
```
My ARM Box:
```
docker run ballerburg9005/xonotic-server-arm64
Unable to find image 'ballerburg9005/xonotic-server-arm64:latest' locally
latest: Pulling from ballerburg9005/xonotic-server-arm64
docker: no matching manifest for unknown in the manifest list entries.
See 'docker run --help'.
```

I can run from other multi-architecture tags on my box , like so:
```
docker run debian:latest 
```

But when I try my repository it doesn't work.

[manifest-inspect.txt](https://github.com/docker/hub-feedback/files/5111961/manifest-inspect.txt)

**Comment by pashak09** [comment]
I have the same error

**Comment by pavel-nano** [comment]
I have some error

**Comment by ballerburg9005** [comment]
I think the issue is that Docker tries to pull 32bit ARM, if it detects the system as either 32bit ARM or 64bit ARM, whenever multiple architectures are available. 

The workaround is to also build an armhf package, whenever building an arm64 package.

Note that my system is not detected as armhf, its correctly identified arm64. 

Docker version 18.09.1
