### ISSUE TITLE
Hub rate limit handling for anonymous and authenticated requests from same IP

### ISSUE THREAD

**Issue by lenaing** [docker/hub-feedback#2025]
Hello,

We provide to our users a build factory.

As such, we use a pull-through cache instance to cache Docker images.
Requests are made authenticated to the registry from this instance.

However, we have a single public IP so we are not the only ones to query
the hub from this IP on our premises. Non authenticated requests may
therefore trigger the rate limit on this IP.

[Documentation](https://docs.docker.com/docker-hub/download-rate-limit/) isn't clear on this point:

Can the authenticated requests can get through or are they also rate limited
because of the IP rate limiting triggered by non authenticated requests ?

Kind regards,

**Comment by binman-docker** [comment]
Any requests that are authenticated are not affected by the anonymous / per-IP rate limits. More details here: https://www.docker.com/pricing/resource-consumption-updates

**Comment by lenaing** [comment]
Thanks,
That was not clearly identified at the moment I wrote the issue.
Closing it now :)
