### ISSUE TITLE
get Too Many Requests (HAP429) from behind a firewall

### ISSUE THREAD

**Issue by lintmars** [docker/hub-feedback#2027]
I am in a big company which I think uses a pool of public IPs to access docker hub. recently we have encountered the error "Too Many Requests (HAP429)" from time to time. I think because the public IP of our http proxy is assigned dynamically each time when accessing the internet, and some IPs are black listed and some are not yet. But we don't know which. any suggestion on this?

**Comment by mikeparker** [comment]
Have you authenticated? https://github.com/docker/hub-feedback/issues/2025#issuecomment-685940301
