### ISSUE TITLE
IP appears to have been blacklisted

### ISSUE THREAD

**Issue by Oats87** [docker/hub-feedback#2029]
## Problem description

One of the IP's in our lab environment (`184.105.224.70`) seems to have been blacklisted from Docker Hub, as we're getting consistent 500 server errors when hitting docker hub (or any docker related URL). Is there a reason as to why the IP was put onto the blacklist? We can and will correct any issues that the machine behind this IP is causing, if there are any.

**Comment by manishtomar** [comment]
cc @binman-docker

**Comment by binman-docker** [comment]
Hi @Oats87 - it looks like that IP was added to our block list back in January. It was scraping Hub's repos API to the point it was causing stability issues with our services, and the service owners added it to the list to mitigate that.

If you can confirm that's no longer happening, I can ask them to try unblocking it.

**Comment by Oats87** [comment]
Hi @binman-docker - thanks for the information. I'll go ahead and relay that over to the developer that runs the machine, and we'll get things sorted out on our side. I'll update this issue when any changes that need to be implemented on our side are done.

**Comment by Oats87** [comment]
Hi @binman-docker the developer has come back to me saying they are no longer performing API calls at the original frequency. Would it be possible to have the IP un-blacklisted?

**Comment by binman-docker** [comment]
I'll pass it through to the Hub team and update this thread.

**Comment by binman-docker** [comment]
Hi @Oats87, the IP has been removed from the list. We'll let you know if we see further issues.
