### ISSUE TITLE
Licenses are under 'Settings'

### ISSUE THREAD

**Issue by mbentley** [docker/hub-feedback#203]
Finding licenses is difficult and doesn't make sense to have it under 'Settings'.  It really ought to be somewhere more obvious, such as next to 'Repositories' and 'Stars' when viewing your account page:
![screenshot 2015-08-07 at 3 07 46 pm](https://cloud.githubusercontent.com/assets/414445/9143739/17a80c86-3d16-11e5-99e7-a94bd942ebfa.png)

**Comment by ChristopherBiscardi** [comment]
agreed. This is the plan of record.

**Comment by mbentley** [comment]
Awesome, thanks for the quick feedback. :+1:

**Comment by huslage** [comment]
Is the plan of record somehow unchangeable?

**Comment by ChristopherBiscardi** [comment]
@huslage "plan of record" just means it's the plan we have for this at this moment in time.
