### ISSUE TITLE
IP Blacklisted (94.130.225.35)

### ISSUE THREAD

**Issue by jipjan** [docker/hub-feedback#2030]
The IP of one of our cloud servers appears to be blacklisted. This server was compromised because of an incorrect firewall configuration and this has been resolved.

Can the blacklist be lifted for IP 94.130.225.35?

**Comment by manishtomar** [comment]
cc @binman-docker

**Comment by binman-docker** [comment]
Hi @jipjan, can you be more specific? What action are you performing and what error message are you seeing?

If you've encountered our rate limiting, you should find it expires within several hours.

**Comment by jipjan** [comment]
Thanks for looking in, it appears to been have that, it resolved itself.
