### ISSUE TITLE
Account deactivated by accident

### ISSUE THREAD

**Issue by Riku32** [docker/hub-feedback#2032]
Accidently closed my docker account (Account id: deltaquake1). Can I reactivate it with my disassociated email address rudnik7000@gmail.com.

**Comment by erikmd** [comment]
Hi, it seems a workaround was mentioned in this other issue: https://github.com/docker/hub-feedback/issues/1834#issuecomment-544047975

**Comment by DonaldKellett** [comment]
Unfortunately, the workaround does not seem to work anymore as of 13/09/2020.
