### ISSUE TITLE
Filtering tags does not wait for user to finish typing

### ISSUE THREAD

**Issue by chakrakan** [docker/hub-feedback#2034]
## Problem description

Filtering for tags on Docker Hub fires a search request as user is still typing instead of waiting after they are done. 

Reproduced Issue:

![docker-hub-glitch](https://user-images.githubusercontent.com/57884127/93008923-9dac8100-f548-11ea-8521-b7a95e191ba5.gif)

**Comment by SanduRajapakse** [comment]
Can confirm also experiencing the issue. It also appears to lose focus on the field forcing the user to keep selecting the field. Maybe increase the debounce as well?

**Comment by thaJeztah** [comment]
Thanks for reporting; that looks like a bug indeed. I think it's ok to start searching, but the search field itself should not disappear when it does so, and should not loose focus.

Let me reach out to the docker hub team to bring it to their attention 👍

**Comment by shawnaxsom** [comment]
Hey all, sorry for the delay on this one. I noticed in our surveys we give to users (yes we do read those and they're very helpful 🙂) that this is still an issue. I'll get this one prioritized, it is certainly annoying.

**Comment by spencerhcheng** [comment]
Thank you for surfacing this issue. We've just a deployed a fix for this bug.
