### ISSUE TITLE
Change / detect default GitHub branch

### ISSUE THREAD

**Issue by hrueger** [docker/hub-feedback#2038]
## Problem description
Recently, GitHub changed the default branch name from `master` to `main`. When creating a new repository on Docker Hub, connecting it to GitHub and enabling auto builds, `master` is assumed for the branch name. This causes the `Create & Build` Button to do nothing (it's loading and then nothing happens).

Furthermore, I couldn't change the branch name under `Build configurations`. I had to add a new build rule and then delete the old one. This is a little bit confusing.

**Comment by colin-pm** [comment]
Is there any update to address this problem?

**Comment by hrueger** [comment]
Apparently this has now been fixed.
