### ISSUE TITLE
"test webhook" with new UI and other webhook things

### ISSUE THREAD

**Issue by zezuladp** [docker/hub-feedback#204]
On the old UI there was a way to "test webhook" which essentially just triggered the webhook callback chain to be called. Would be very useful to be able to do this through UI. 

Also being able to cancel "pending" webhooks was very useful. Can't seem to find that on new UI.

+1'd a guy who mentioned he can't delete a webhook.

Why do webhook timestamps start with the year? Least useful thing ever.

**Comment by posita** [comment]
Not relevant to the core of this issue, but:

> Why do webhook timestamps start with the year? Least useful thing ever.

https://en.wikipedia.org/wiki/ISO_8601
http://www.obj-sys.com/asn1tutorial/node14.html
