### ISSUE TITLE
I accidentally closed/deactivate a docker account and now I can't seem to reactivate it [service request #18196]

### ISSUE THREAD

**Issue by UmeshCGC** [docker/hub-feedback#2045]
I am currently blocked from retrieving my account **[Docker ID: 18170935]**.
To reactivate my account, I tried to get a verification email using the Resend Activation Email button.
But I am getting an `Error from accounts` error message and the verification email is not sent to my primary email address
Please remove the secondary email and reactivate my account.
For issue details please refer to the  **service request #18196** logged.

Similar issue as #1788 and #2012

**Comment by UmeshCGC** [comment]
This is annoying! I logged the service request two days ago, no response to that.
So opened an issue here and no response here as well.

**Comment by dbytecoderc** [comment]
Hi, @UmeshCGC  have you been able to resolve this? I have a similar issue

**Comment by UmeshCGC** [comment]
Hi @dbytecoderc, no my issue is still unresolved. ah! yeah... I don't know, what another way we can reach out to customer support.

**Comment by UmeshCGC** [comment]
Hi, @dbytecoderc, my account issue is resolved by customer support after I followed up on the service request logged. I would recommend the same. Good luck!
