### ISSUE TITLE
Can't make Automated Builds linking to github repositories

### ISSUE THREAD

**Issue by machalen** [docker/hub-feedback#2050]
Dear Docker hub Team

Maybe this is a very basic question... I created a repository in GitHub with a Dockerfile and after linking this repository to Dockerhub, I am trying to make an Automated Build with "Trigger" as I did many times before. However, this time, even changing the Build configurations to "Internal and External Pull Requests", it is not working.

Can somebody help me with this? 

Thanks!

**Comment by Dirnei** [comment]
Maybe have a look at the [docker forum](https://forums.docker.com/t/automated-build-never-builds/18713/15). I was having also issues and the last comment solved it

**Comment by machalen** [comment]
> Maybe have a look at the [docker forum](https://forums.docker.com/t/automated-build-never-builds/18713/15). I was having also issues and the last comment solved it

Thanks @Dirnei ! This was very helpful
