### ISSUE TITLE
Aggregate and make it possible to handle vulnerabilities

### ISSUE THREAD

**Issue by jryberg** [docker/hub-feedback#2067]
## Problem description - It's not possible to even start handle vulnerabilities with provided feature in a sane way
Docker sell teams subscriptions and makes vulnerabilities scanning a selling point. I admit that vulnerability scanning is delivered and that do "work" but the feature is almost useless.

I got containers with "thousands" of vulnerabilities, it's 10x duplicates since each path is reported for each vuln and that makes it tons of dupes. 

Most of the vulns are known and will not be fixed. 

It's almost impossible to find vulns that are really important to handle since it's just a list with tons of entries. 

May I suggest the following: 
  -  Aggregate same vuln into 1 entry, feel free to add all paths in that entry
  - Make it possible to mark vulns as  "okey", "ignore" or something so we can detect new vulns that we need to fix or maybe approve as a calculated risk. That should apply for the entire repository and not just the tag itself. 

There are probably many more things to add to this feature but this is a start.

**Comment by mikeparker** [comment]
@jryberg great feedback, thanks! The first suggestion is on our roadmap already, so the same vuln caused by different paths will be grouped in future. The 2nd is an interesting idea. 

Any other thoughts on the feature or ideas are welcomed.

I'd also be interested if you looked at a full Snyk solution (are you aware a paid Snyk account brings more functionality using their site? We tried to keep the advertising to a minimum, but maybe we went too far hiding it) or whether you'd prefer us to include more of that functionality into Docker Hub directly.

**Comment by jryberg** [comment]
> 
> 
> @jryberg great feedback, thanks! The first suggestion is on our roadmap already, so the same vuln caused by different paths will be grouped in future. The 2nd is an interesting idea.
> 
> Any other thoughts on the feature or ideas are welcomed.
> 
> I'd also be interested if you looked at a full Snyk solution (are you aware a paid Snyk account brings more functionality using their site? We tried to keep the advertising to a minimum, but maybe we went too far hiding it) or whether you'd prefer us to include more of that functionality into Docker Hub directly.

Thank you for your feedback. Yes, I'm aware about Snyk but I'm not looking for full functionality, just little more than Docker Hub provides right now. 

Some functionality would hover be great such as marking a specific vulnerability on the repo level so only new or changed vulnerabilities are listen as unhandled so we can make a decision if we need to take any action or not. 

As it is today it's overwhelming with information and it's not really possible to make any use of the list unless maybe if you work hard with one container as a one shot but once you push a new container you need to start all over again. 

Best regards Johan Ryberg

**Comment by mikeparker** [comment]
@jryberg we just shipped an iteration on the scanning UI which will now group issues by CVE. Note this will only occur for new scans, previous scan reports will remain intact. Please let us know if this helps.

We haven't implemented the ability to ignore vulnerabilities yet.
