### ISSUE TITLE
Unable to authenticate against dockerhub/api

### ISSUE THREAD

**Issue by ValeriiVozniuk** [docker/hub-feedback#2071]
Hi,

Our team has faced an issue with dockerhub/api authentication starting from the last hour. api auth requests are failing with "{"detail": "Failed to validate JWT token against trusted cert"}" response. When trying to authenticate in browser on https://id.docker.com/login/ we get "An internal error has occurred. Please try again later." message. Could you please check what is causing these errors, and fix the issue?

**Comment by mikeparker** [comment]
We're already on it, thanks for the report.

**Comment by mikeparker** [comment]
Can you try now please?

**Comment by ValeriiVozniuk** [comment]
Thank you, I am now able to authenticate both via api and on website :)
