### ISSUE TITLE
Docker image tags are unexpectedly gone from DockerHub

### ISSUE THREAD

**Issue by Snipx** [docker/hub-feedback#2077]
The problem we and our clients have encountered is that some tags are gone for this repository and this is causing production issues for our clients.
For example, we are absolutely sure we pushed tag 1.2.1 on 2019-12-16 into our repository https://hub.docker.com/repository/docker/itext/dito-sdk.

We have some logs in CI systems that prove it:

```
[16:57:11][Step 8/10] Starting: /bin/sh -c "docker push  itext/dito-sdk:1.2.1"
[16:57:11][Step 8/10] in directory: /home/duser/teamcity/work/6be7b0050a9778fe
[16:57:11][Step 8/10] The push refers to repository [docker.io/itext/dito-sdk]
[16:57:11][Step 8/10] efdfe75c906b: Preparing
[16:57:11][Step 8/10] c2a7ce353aa7: Preparing
[16:57:11][Step 8/10] 852001431fd6: Preparing
[16:57:11][Step 8/10] 2ee490fbc316: Preparing
[16:57:11][Step 8/10] b18043518924: Preparing
[16:57:11][Step 8/10] 9a11244a7e74: Preparing
[16:57:11][Step 8/10] 5f3a5adb8e97: Preparing
[16:57:11][Step 8/10] 73bfa217d66f: Preparing
[16:57:11][Step 8/10] 91ecdd7165d3: Preparing
[16:57:11][Step 8/10] e4b20fcc48f4: Preparing
[16:57:11][Step 8/10] 9a11244a7e74: Waiting
[16:57:11][Step 8/10] 91ecdd7165d3: Waiting
[16:57:11][Step 8/10] e4b20fcc48f4: Waiting
[16:57:11][Step 8/10] 5f3a5adb8e97: Waiting
[16:57:11][Step 8/10] 73bfa217d66f: Waiting
[16:57:13][Step 8/10] 2ee490fbc316: Layer already exists
[16:57:13][Step 8/10] b18043518924: Layer already exists
[16:57:13][Step 8/10] 9a11244a7e74: Layer already exists
[16:57:13][Step 8/10] 5f3a5adb8e97: Layer already exists
[16:57:14][Step 8/10] 73bfa217d66f: Layer already exists
[16:57:14][Step 8/10] 91ecdd7165d3: Layer already exists
[16:57:15][Step 8/10] e4b20fcc48f4: Layer already exists
[16:57:16][Step 8/10] efdfe75c906b: Pushed
[16:57:16][Step 8/10] c2a7ce353aa7: Pushed
[16:57:27][Step 8/10] 852001431fd6: Pushed
[16:57:32][Step 8/10] 1.2.1: digest: sha256:2e790952b366a233ab555f88cd6d04b4da02318cc51c2cd67e90bbbab54af2a6 size: 2421
[16:57:32][Step 8/10] Process exited with code 0
```

But we cannot see that tag on DockerHub anymore and it's impossible to pull it either:

```
 docker pull itext/dito-sdk:1.2.1
Error response from daemon: manifest for itext/dito-sdk:1.2.1 not found: manifest unknown: manifest unknown
```

We saw that DockerHub announced image retention policy but as far as I understand it was postponed till mid 2021 and we also have a paid subscription plan now, so I believe the image retention policy could not have applied to us.
I could not see any history or anything that would indicate the fact of tag removal or reason of it.

Could you please restore the removed tags (e.g. 1.1.9 is certainly removed as well) as soon as possible, and let us know the reasons on why the tags have been removed and how we can prevent that?

Thank you,
Alexey Subach

Director of Development
iText Group NV

**Comment by mikeparker** [comment]
Thanks for the report, we're on it.

**Comment by mikeparker** [comment]
We can see the tag `1.2.1` was deleted by actor `itextditodockerpublisher` at the time `2020-11-17 01:01:06.592`

Tag 1.1.9 is still pullable.

**Comment by Snipx** [comment]
Hi @mikeparker and thanks for your quick reply!
`1.1.9` is pullable because we had to re-upload it, so this is expected.

Just to clarify, the timestamp you attached is in UTC, right?

In fact this sounds very strange - we don't have any intention to remove the tags, and I am pretty sure we did not remove anything. Could that removal be an unfortunate side effect of another command execution?
We did remove 1.1.8 because we also found out it was missing at some point and then we re-uploaded it, but decided to remove it afterwards because it clobbered the top of the tag list. I don't think we removed other ones.

Of course we may have done something wrong on our side but it's a giant mystery what it could be.

Could you please check logs for the following tags that we are now missing:

- 1.1.10
- 1.1.12
- 1.1.13
- 1.2.0
- 1.2.1 (you already provided info for this one)
- 1.2.2
- 1.2.3
- 1.2.4
- 1.2.5
- 1.2.6
- 1.3.0

The general pattern I see is that the tags older than ~1 year are removed, with some exceptions of course.

**Comment by mikeparker** [comment]
We can see deliberate deletions for some of these:

```
| itext       | repo          | delete_tag | itext/dito-sdk | itextditodockerpublisher | {"tag": "1.2.0"} | 2020-11-17 01:01:06.592 | False            |
| itext       | repo          | delete_tag | itext/dito-sdk | itextditodockerpublisher | {"tag": "1.2.1"} | 2020-12-02 01:03:10.1   | False            |
| itext       | repo          | tag.delete | itext/dito-sdk | itextditodockerpublisher | {"tag": "1.2.5"} | 2021-01-13 01:00:37.459 | False            |
| itext       | repo          | tag.delete | itext/dito-sdk | itextditodockerpublisher | {"tag": "1.2.6"} | 2021-01-27 01:00:32.644 | False            |
| itext       | repo          | tag.delete | itext/dito-sdk | itextditodockerpublisher | {"tag": "1.3.0"} | 2021-02-10 01:01:50.298 | False            |
```

But our audit logs don't go back very far, the feature was only released a few months ago, so if there were deletions before this point we won't have logs for them.

If you look carefully at the timestamps you can see they are all triggered at 1am UTC, usually on a wednesday, could even be every 2 weeks from the looks of this data: 

Weds 10th Feb 1am -> deleted 1.3.0
Weds 27th Jan 1am -> deleted 1.2.6
Weds 13th Jan 1am -> deleted 1.2.5

So my guess would be either you or us have some kind of cron job deleting things at 1am on a fortnightly basis on wednesdays. It's possible this is our end but my instinct would be to check your end first. Please let us know if you find what it is, it'll help us help others who have the same issue in future.

**Comment by Snipx** [comment]
Thanks @mikeparker, we will be investigating further. Meanwhile, is there any other information you could provide me with? E.g. IP addresses and so on. I can share my email to you so that you have a proof it's me who has permissions for that account, or prove it otherwise.
Also, is there any chance to restore those tags somehow?

**Comment by mikeparker** [comment]
> Meanwhile, is there any other information you could provide me with? E.g. IP addresses and so on.

Sorry, no we don't track this kind of data. 

Adding a new feature to track login events with IP addresses in the Audit Logs feature might be something useful to you? Although we'd need to be careful for GDPR and privacy concerns of course.

> is there any chance to restore those tags somehow?

Sorry, no. Us storing all the data for old deleted images in case someone makes a mistake would cost us quite a lot in storage.

Sorry I can't be more help :(.

**Comment by Snipx** [comment]
> Adding a new feature to track login events with IP addresses in the Audit Logs feature might be something useful to you?

In this case it would indeed be quite useful I believe

**Comment by Snipx** [comment]
Hi Mike, 
I see that 1.3.1, 1.3.2 and 1.3.3 tags are also gone now.
Meanwhile I think we now have a clue of what might have been going on. So probably it's on our side indeed.
Let us try to apply the fix and wait for a couple of weeks to see if it helps.

I appreciate your help on this one very much!

**Comment by mikeparker** [comment]
@Snipx sorry to hear you're still having problems! Good news you might have found it, though :) 

No problem and please let us know if you find the problem so we can help other users that may have the same thing.

**Comment by Snipx** [comment]
We now have more evidence to support my guess about the root cause, so I will close this ticket now.

The reason was the configuration of our CI tool that we are using - TeamCity. The "Docker support" build feature has "On server clean-up, delete pushed Docker images from registry" flag, and it was set to true for us. This means that after a while when the build information was cleaned up, the tag was removed from the registry. Our service user also had powerful permissions to update the documentation automatically, that's why it was able to also remove the tags unfortunately.

Thanks lot for your help once again!

**Comment by mikeparker** [comment]
@Snipx awesome, thanks for taking the time to get back to us on this. Glad we didn't miss anything!
