### ISSUE TITLE
Spam user pullirounti

### ISSUE THREAD

**Issue by borissmidt** [docker/hub-feedback#2078]
## Problem description
I found another spam user:
https://hub.docker.com/u/pullirounti

**Comment by Jehoel** [comment]
Here's another one I found: https://hub.docker.com/u/terspurjoydei

**Comment by MikeRich88** [comment]
Another spam user: https://hub.docker.com/u/hiestanespor

**Comment by scheffold** [comment]
Same with https://hub.docker.com/u/thralilovwer
