### ISSUE TITLE
Replacement character � (%EF%BF%BD) in URL goes to empty repo

### ISSUE THREAD

**Issue by ptaranat** [docker/hub-feedback#2084]
This is a minor bug. A user could browse to an empty private repo using the � character as the repo name in url.
The expected behavior is a 404 page. There's no way to actually create this repo or make changes to it.

**Operating system** Windows 10, 19042.867
**Browser and Browser version** Google Chrome 89.0.4389.114
**URL for the page in question.** https://hub.docker.com/repository/docker/ptaranat/%EF%BF%BD or https://hub.docker.com/repository/docker/ptaranat/�
**Screenshots of the issue**
![](https://i.imgur.com/e371q4l.png)
**The rough date and time the error**
April 6, 2021, 12pm ET
**Your hub username**
ptaranat

**Comment by mikeparker** [comment]
Yes, I can reproduce this. Thanks for the report!
