### ISSUE TITLE
Partially downgrade performance in dockerhub

### ISSUE THREAD

**Issue by jindov** [docker/hub-feedback#2087]
We got partially downgrade performance in SEA
Pulling speed in some layer of an image is very slow (KB/s), I test in my local laptop in Vietnam, and even in our server in AWS and GCP in singapore region

this take over 20min to reach this
```
...
11a8dedc2366: Pull complete
633c3fd5157a: Pull complete
49fe9c5e53ec: Downloading [============================================>      ]  308.9MB/350.7MB
e33ae4e6e7a1: Download complete
```

Note: when you stop this pull and rerun, this will fast until 308.9MB then slow drastically

**Comment by shawnaxsom** [comment]
Thanks for reporting. We've had a few other reports of slow pulls, all in Asia-Pacific regions. We've updated the status page and are investigating: https://status.docker.com/

**Comment by shawnaxsom** [comment]
If you'd like, you can contact [support](https://hub.docker.com/support/contact/) and provide one or more IP addresses. We're investigating with one of our providers and having IPs can help identify any issue on their end.

Otherwise, please keep an eye on our status page and we'll update as we know more.

**Comment by binman-docker** [comment]
If anyone is encountering this issue, it would help narrow down the issue if you can run these commands on the same machine and copy the "cf-ray" header into a comment here. This will tell us which edge sites may be affected.

Also if pulling a public image is very slow, please let us know which one so we can have a reliable reproduction. Thanks!

```
token=$(curl "https://auth.docker.io/token?service=registry.docker.io&scope=repository:library/busybox:pull" | jq -r .token)

curl -v -L https://registry-1.docker.io/v2/library/busybox/blobs/sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4 -H "Authorization: Bearer $token" > /tmp/layer

**Comment by binman-docker** [comment]
I've tested with large public and private images on VMs in several APAC regions, including GCP Singapore, and haven't been able to reproduce a slow download. We're leaving the incident open until we get more feedback from those affected.

**Comment by binman-docker** [comment]
We haven't received any further reports and haven't been able to reproduce the issue, so I've closed the incident on status.docker.com. 

I will leave this ticket open to collect further information, and users experiencing extremely slow pulls in the APAC region can add details here or file a support ticket. Thanks!

**Comment by jindov** [comment]
Hi dockerhub team,

After hours faced the issue, everything is back to normal, we can pull completely as expectation. We do not collect too much information, apologize for this unconvenient

**Comment by nebuk89** [comment]
Thanks @jindov . We will close this for now, feel free to open a new ticket in the future.
