### ISSUE TITLE
Build performance regression the last 2 days

### ISSUE THREAD

**Issue by wader** [docker/hub-feedback#2088]
Hi! I have build that has starting failing the last days. It usually take 60-70min but now it get cancelled after 240min.

The image is mwader/static-ffmpeg

Here is the graph of the last 100 builds:

![Screenshot 2021-04-21 at 11 09 47](https://user-images.githubusercontent.com/185566/115528282-30a55a80-a292-11eb-8e32-d60c38a68790.png)

The build is very CPU intensive, builds lots of C, C++ and Rust code so it would be sensitive to changes of CPU performance or parallellism.

**Comment by wader** [comment]
The commit since last time it succeeds is https://github.com/wader/static-ffmpeg/commit/19dacf787d6a0d0006caf56f138fa18955ffcb02 (update alpine version). The github action ci build had no problem building with that change.

**Comment by jcarter3** [comment]
This should be fixed now, please try again and let us know if the issue persists. We adjusted the resources allocated to builds and it had larger ramifications than intended.

**Comment by wader** [comment]
Aha that make sense. Thanks! I've re-triggered last build and will close issue once it succeeds

**Comment by wader** [comment]
Success, back to previous build time 👍
