### ISSUE TITLE
Linked GitHub repo doesn't display on the Build Settings or Repo Info tab

### ISSUE THREAD

**Issue by commanderfun** [docker/hub-feedback#209]
For automated builds there is no way to see what GitHub repo is being used.  It should display on the "Build Settings" tab and on the "Repo Info" tab.

**Comment by rrarunan** [comment]
@commanderfun if it is a public repo, could you share the URL.. also, check the `source repository` button to the right side and see if that takes you to the github repo. We are looking at feedback on improving that.

**Comment by commanderfun** [comment]
@rrarunan Thanks.  Sorry, for some reason I was blind to the big blue "Source Project " button.   Maybe a GitHub logo would help.  However, I still think you should has another link or some indication of the GitHub repo on the "Build Settings" tab.

![docker-hub](https://cloud.githubusercontent.com/assets/2975811/9147324/404e6456-3d1a-11e5-869a-50343d495474.png)

**Comment by ChristopherBiscardi** [comment]
The "Linked Repos" field which the screenshot is pointing to here is related to the "Automated Build Links" functionality (which trigger a build of this Hub repo when another Hub repo builds). It is not related to the linked github repo.

I've opened #230 to deal with the wording of "Linked Repos" in that place.

Also leaving this ticket open to deal with the visibility of the GitHub linked repo.

**Comment by nhsiehgit** [comment]
This should be resolved now. closing
