### ISSUE TITLE
Docker Hub Build Trigger does not work via Cloudflare Worker

### ISSUE THREAD

**Issue by thasmo** [docker/hub-feedback#2090]
```javascript
fetch('https://hub.docker.com/api/build/v1/source/.../trigger/.../call/', {
    method: 'POST',
});
```
returns `ERROR 400` when running via cloudflare worker.

Running this in a browser console works as expected.

Where can I find official documentation about docker hub build triggers? Thanks!

**Comment by nebuk89** [comment]
Hey!
We don't have a public API/docs for this yet, we are building out our API docs here at the moment actively: https://docs.docker.com/docker-hub/api/latest/ 

Keep an eye for changes to come in over the next couple of months as we work through the backlog of documenting everything

**Comment by thasmo** [comment]
When calling the cloudflare worker URL in the browser, the Docker API returns error 400. When calling the cloudflare worker URL via the cloudflare worker web dashboard, the Docker API returns success 202.

So, why is that? Where can I find the documentation for the `api/build/v1` endpoint?
