### ISSUE TITLE
UI "tags" not shown in Hub page for multi-arch image

### ISSUE THREAD

**Issue by anentropic** [docker/hub-feedback#2092]
## Problem description
I've published a multi-arch image for `linux/arm64` and `linux/amd64`

I was expecting to see the UI tags for `Linux` `arm64` and `amd64` (or maybe `x86-64`) on the image homepage in Docker Hub as per:
https://www.docker.com/blog/introducing-docker-hub-improved-tag-ux/

However I only get the basic `Container` tag 😞 

My image with its published (docker) tags is here:
https://hub.docker.com/r/anentropic/chuckd/tags?page=1&ordering=last_updated

Am I doing it right?

AFAICT there is no way for me to manually specify the UI tags ?

**Comment by anentropic** [comment]
in case relevant, the image is built and pushed via the `docker/build-push-action@v2` GitHub Action

**Comment by mikeparker** [comment]
Those are labels, not tags. If you want your image to have an `arm64` label you need to specify it manually as a label. Not all image authors that publish multi-arch images add those labels so they can't be relied upon to filter or find multi-arch images.

I realise this isn't obvious from the blog post as it doesn't focus on the difference between labels and tags.

> AFAICT there is no way for me to manually specify the UI tags ?

Yes, you can, check out https://github.com/docker/build-push-action#inputs and scroll to `labels`.

**Comment by anentropic** [comment]
The default labels from build-push-action are key value pairs like `org.opencontainers.image.title=chuckd` and they don't show up in the UI.

Do I need a particular key string to add the value `arm64` and have it displayed?  Or I can just specify bare `arm64` as a label?
