### ISSUE TITLE
Not able to build on docker hub with Ubuntu hirsute as the base image

### ISSUE THREAD

**Issue by aragula12** [docker/hub-feedback#2095]
## Problem description
I am not able to build images with Ubuntu 21.04  as the base image

Repo Dockerfile:
FROM ubuntu:rolling
apt-get update -y

I get the following error:
gpgv, gpgv2 or gpgv1 required for verification, but neither seems installed

According to Stackoverflow, this is because docker hub build server has a older version of runc (1.0.0-rc10)
https://stackoverflow.com/questions/66319610/gpg-error-in-ubuntu-21-04-after-second-apt-get-update-during-docker-build

I am able to build on my local system which has runc version 1.0.0-rc93

**Comment by willat8** [comment]
You can workaround this by adding a `hooks/build` to your repo that builds with an updated version of docker in docker. Doesn't respect the build cache though.

https://gist.github.com/willat8/2130449fad36cf3176e5c858661788f9

**Comment by aragula12** [comment]
@willat8 Thank you!!! 
My deepest gratitude.
Thats just brilliant. It worked perfectly for me!
