### ISSUE TITLE
Accidentally deactivated two accounts without knowing that the IDs are kept. Need help reactivating.

### ISSUE THREAD

**Issue by kiwi-bui** [docker/hub-feedback#2098]
I deactivated two accounts with the intent of transferring them to different emails, but I didn't know that the IDs stay reserved:
kmbui1995
kiwibui

Would someone be able to help reactivate them for me?

**Comment by nebuk89** [comment]
Hey @kiwi-bui can you open a support ticket please https://hub.docker.com/support/ 

Thanks!
