### ISSUE TITLE
Our IP range seems to have been blocked

### ISSUE THREAD

**Issue by betterphp** [docker/hub-feedback#2104]
## Problem description
Connections to anything related to docker hub hang, our router sees packets being sent and no reply coming back.
![image](https://user-images.githubusercontent.com/788007/118781169-a9dda080-b884-11eb-9080-6978b2adc285.png)

Our range is 185.150.147.0/25.

**Comment by nebuk89** [comment]
Hey @betterphp have you had a response on your support ticket now?

**Comment by betterphp** [comment]
Yes thanks, turns out there was a missing route rule one one of our internet routers. All our fault :P

**Comment by nebuk89** [comment]
No worries! :D
