### ISSUE TITLE
Problem building with alpine 3.14.0

### ISSUE THREAD

**Issue by wader** [docker/hub-feedback#2114]
## Problem description

Problem building with lastest alpine stable 3.14.0.

I have an image that work fine with `alpine:3.13.4` but with `alpine:3.14.0` they started failing. After digging i think the issue might be related to https://wiki.alpinelinux.org/wiki/Release_Notes_for_Alpine_3.14.0#faccessat2

Symptom for me is error similar to this:
```
/bin/sh: Operation not permitted 
```

Image is https://hub.docker.com/r/mwader/static-ffmpeg

It builds fine with docker desktop 3.4.0 (engine 20.10.7) on macOS.

**Comment by majamee** [comment]
This issue is not only happening on alpine, but in fact on a lot of up2date distributions. The reason seems, that docker hub seems to use an out-dated build chain. Would be great to have this fixed though. Should be an update of the build environment for/ by docker hub.
Additional information: 
https://forums.docker.com/t/multiple-projects-stopped-building-on-docker-hub-operation-not-permitted/92570/6

**Comment by wader** [comment]
golang alpine 3.14 had similar issue and is now buliding (accoding to comments) https://github.com/docker-library/official-images/pull/10379#issuecomment-863396878 . But my build is still failing

**Comment by majamee** [comment]
Fyi: Here another image which builds perfectly fine locally, but the make script fails hard on docket hub:
https://hub.docker.com/r/majamee/alpine-dash-hls

**Comment by wader** [comment]
@majamee yes i guess this will get worse and worse when more things uses new syscalls and get EPERM. But i dont get how the golang alpine image seems to build fine now, used newer builder version somehow?

**Comment by majamee** [comment]
Any updates would be highly welcome as my auto-builds are now stuck for about a month, without me being able to do anything about it. :(

**Comment by wader** [comment]
@majamee I've started migrate my auto builds to github actions instead. Here is an example that maps git tags to image tags and master branch to latest tag https://github.com/wader/static-ffmpeg/blob/master/.github/workflows/ci.yml

**Comment by majamee** [comment]
My builds are working again :) Just re-tried and it seems that the build chain of docker hub was updated successfully.

**Comment by wader** [comment]
Aha good to know! Strange that they don't announce updates on https://docs.docker.com/docker-hub/release-notes/ etc?

I got an email some time ago that  auto-builds are pro-only now, maybe good to know https://www.docker.com/blog/changes-to-docker-hub-autobuilds/
