### ISSUE TITLE
Querying for namespaces does not return organizational namespaces (REST API)

### ISSUE THREAD

**Issue by karolz-ms** [docker/hub-feedback#2117]
When querying Docker Hub via its REST API, the `v2/repositories/namespaces` query only returns namespaces associated with the Docker Hub login. The same query used by the Docker Hub site UI returns both namespaces associated with the login, as well as namespaces owned by all organizations that the user belongs to.

Full repro steps (using VS Code) are available from [related VS Code Docker extension issue](https://github.com/microsoft/vscode-docker/issues/2954)

**Comment by silvin-lubecki** [comment]
Hello @karolz-ms ! Thanks for filling this issue 👍 
I checked it on my side, but I got the same results between the Hub-UI and a cURL request...
Hub-UI:
<img width="1078" alt="Screen Shot 2021-07-05 at 10 59 28" src="https://user-images.githubusercontent.com/31478878/124451057-4f8d9600-dd85-11eb-8fcf-8c0aa4df5553.png">
cURL:
```
$ curl --request GET \
  --url https://hub.docker.com/v2/repositories/namespaces/ \
  --header 'Authorization: Bearer XXXXX.XXXXX.XXXXX' \
{"namespaces": ["composeonkubernetes", "dockerinternal", "kamoulox", "silvinorgtest", "slubecki"]}
```
But maybe I'm misunderstanding your point ?
Can you add more context about what you get from hub-ui, and what you got by calling the API directly, and what you expect ? Thanks !

**Comment by karolz-ms** [comment]
Silvin, good question, and sorry for stating the problem poorly. 

I have the following setup:
- An organization `zpkarolfriends` that has a repository `hwflask` with one image: `zpkarolfriends/hwflask:0.3`
- A user `karolzms` that is part of `zpkarolfriends` organization

When I log to Docker Hub website using `karolzms` credentials, I can see the `zpkarolfriends/hwflask` repository with no difficulty.

When I log in to Docker Hub from VS Code though, VS code issues a GET HTTP request with the path `v2/repositories/namespaces?page_size=100` against GitHub API, no namespaces are returned. I tried the same query using `curl`, with the same effect.

Hope this makes it clearer?

**Comment by nebuk89** [comment]
Yep that does thanks @karolz-ms we are able to reproduce and are looking into this further

**Comment by ruggi** [comment]
Hey @karolz-ms 👋 we deployed a fix to this issue. Any chance you can give it another go and see if it is indeed as expected on your end too? Thanks!

**Comment by karolz-ms** [comment]
Hey @ruggi thanks for checking, but no, unfortunately I do not see the `zpkarolfriends` organization returned from the namespaces query when I log as `karolzms` user. Only `karolzms` namespace is returned... 😞 

Please let me know if I can try something else?

**Comment by silvin-lubecki** [comment]
Hello @karolz-ms, can I ask how you call the Docker Hub API? What is the authentication process you use (ie: Bearer token)?

**Comment by silvin-lubecki** [comment]
Hello @karolz-ms, I have a question after parsing your code. What is your intent when you query namespaces? If I understand it correctly, you want to display a tree view with all the organizations the user is part of, then all the repositories inside?
After re-checking our `/namespaces` code, in the end it behaves as expected, ie: it returns all the organizations where you are an `owner`. Can I suggest you to use the `/v2/user/orgs/` endpoint instead, so you can list all the organizations ?
Happy to help you to migrate to the new endpoint if needed 👍

**Comment by bwateratmsft** [comment]
So `v2/repositories/namespaces` is specifically for owners? If so we'll have to query `/v2/user/orgs` as you suggest and merge it.

@karolz-ms can you add me to the `zpkarolfriends` org and I can try these scenarios out?

**Comment by karolz-ms** [comment]
@bwateratmsft done

**Comment by silvin-lubecki** [comment]
Hello @karolz-ms , I can see you patched the code to use `/v2/user/orgs` https://github.com/microsoft/vscode-docker/commit/f4ac5cd1e664244a89c1f4a5edb22463abc36c8e. Does that fix the issue? Can I close the ticket?

**Comment by bwateratmsft** [comment]
I think that would be fine, any objections @karolz-ms?

**Comment by karolz-ms** [comment]
Yep, looks good, thanks @silvin-lubecki !
