### ISSUE TITLE
newly pushed tag not showing

### ISSUE THREAD

**Issue by rustyx** [docker/hub-feedback#2118]
Just pushed a new release

```
$ docker build . -t rustyx/etcdv3-browser:v0.6.1
. . .
$ docker push rustyx/etcdv3-browser:v0.6.1
The push refers to repository [docker.io/rustyx/etcdv3-browser]
08a02e664873: Layer already exists
3ef4aaefebeb: Layer already exists
1799628130b2: Layer already exists
03901b4a2ea8: Layer already exists
v0.6.1: digest: sha256:136a6ea81d2a79834fc96dd7865bdbfbf210fb0150bb74c97d62458a14277dda size: 1156
$
```

The `latest` tag has been updated, but where's the `v0.6.1` tag?

https://hub.docker.com/repository/docker/rustyx/etcdv3-browser

`docker pull rustyx/etcdv3-browser:v0.6.1` works.

**So why is `v0.6.1` not showing as a tag?**  

<img src="https://user-images.githubusercontent.com/1296899/124275012-3e087c00-db42-11eb-956e-9a353be0c033.png" width="500">

**Comment by silvin-lubecki** [comment]
Hello @rustyx , thank you for filling this issue 👍 
I looks like the `v0.6.1` has been created https://hub.docker.com/layers/rustyx/etcdv3-browser/v0.6.1/images/sha256-136a6ea81d2a79834fc96dd7865bdbfbf210fb0150bb74c97d62458a14277dda?context=explore
Did you re-push it afterwards?

**Comment by danger89** [comment]
I have the same issue. I think Docker really takes time to push new tags??

**Comment by rustyx** [comment]
@silvin-lubecki yes I re-pushed multiple times to no avail. Then approximately a week later the tag finally appeared on the site.
