### ISSUE TITLE
Cannot delete empty repository

### ISSUE THREAD

**Issue by PascalRauprecht** [docker/hub-feedback#2119]
## Problem description
I created an empty docker repository and tried to delete it afterwards, I do not get an error message or anything. Instead, I get redirected to the repository overview in which the repository I just deleted via the delete button is still showing up (also after refreshing etc.) 

As the repository is now in a strange state, I also cannot push images to it anymore. Are you aware of that problem? Is there a workaround?

**Comment by shashankkatte** [comment]
I am experiencing the same issue as well.

**Comment by PascalRauprecht** [comment]
Seems like it is gone today, was able to delete repos again
