### ISSUE TITLE
Multiple private repos in account with free plan

### ISSUE THREAD

**Issue by jarekrzdbk** [docker/hub-feedback#2122]
## I can create multiple private repos, event though I am on a free plan.

I built image locally, logged in using access token, and then pushed image to the hub. 
On the hub this image is marked as private, but I am on a free plan, and already have private repo, and after changing repo type to public I see that I can't change it again to private.

**Comment by technicallyjosh** [comment]
Hey there, I'm not aware of any way to create a private repo when pushing from the CLI. It should default to public. Can you provide any more context as to how you got it create a private repo from the CLI using a login via PAT?

**Comment by technicallyjosh** [comment]
So it looks like it creates the repo with the status of "Locked" which means you cannot push again or pull. We will have to look into options on how to display or limit this functionality 😄 Thanks for reporting!
