### ISSUE TITLE
two-factor mac docker desktop failing

### ISSUE THREAD

**Issue by gettes** [docker/hub-feedback#2125]
I enabled two-factor.  This has been working for a several weeks.  Today I got a new laptop and installed docker desktop fresh (no upgrades).  I am able to login to docker.com with my account and two-factor works.  However, using docker desktop I try to sign-in to my account and my password is accepted but the two-factor NEVER works.  I have tried 3.5.2 Mac desktop and even tried going back to 3.5.1 (after using appcleaner to destroy docker).

**Comment by ccatlett1984** [comment]
Same here, disabling 2FA for now.... :( 👎

**Comment by gettes** [comment]
Upgraded to MacOS 11.5.2 and Docker Desktop 3.6... problem persists.
