### ISSUE TITLE
Deployment key not added to new automated builds on BitBucket

### ISSUE THREAD

**Issue by markosamuli** [docker/hub-feedback#213]
I've added a new automated build where the source is a private BitBucket repository.

I can select the git repository and create a new automated build, but when I try to trigger a new build manually, I get an error that the authentication has failed.

A previous repository has a Deployment key set up correctly on Bitbucket, but for the new repository this didn't seem to work and copying the existing key from the previous project does not seem to help either.

Is there a way to set up this manually?

**Comment by benfuller** [comment]
I'm having a similar issue with my bitbucket repo:
Failed to clone repository: Cloning into '/tmp/build_bbnq9pvhah5gy8nhh5n67nq'... Warning: Permanently added the RSA host key for IP address '131.103.20.168' to the list of known hosts. Permission denied (publickey). fatal: Could not read from remote repository. Please make sure you have the correct access rights and the repository exists.

**Comment by stupied4ever** [comment]
I'm facing the exact same problem.

**Comment by kencochrane** [comment]
@markosamuli I just tried this out and it is working for me. I created a new automated build from a private bitbucket git repo, and the deploy key was in bitbucket. If it isn't you can get your deploykey from the build-settings page and then copy and paste it into bitbucket. Each automated build has a different deploy key.

Goto Repo settings -> build settings -> scroll to bottom until you see deploy key, it is all in one line so make sure you scroll to the right and copy the whole key, and the put it in bitbuckets deploy keys settings. There is a link on the page to the bitbucket help doc for deploy keys if you need it.

URL to page would look like this, replace your username and repo name.
https://hub.docker.com/r/[username]/[reponame]/~/settings/automated-builds/

**Comment by febbraro** [comment]
I had this problem and here is a workaround... 

If the repo in BitBucket is private, you must create the Automated Build as private, then everything gets created correctly (deploy keys, etc). I then manually trigger the first build and the repo is cloned etc. I then change the Automated Build repo to public and the build will continue successfully.

Hope that helps.

**Comment by markosamuli** [comment]
Thanks all, I eventually moved my repos to GitHub that solved the issue.

@kencochrane I tried to use the key from another repo with a working automated build, but after it failed I guessed it had to be unique per build. 

Didn't know where to look for this before and struggled to find it. Looking again I can see the deploy key on the automated build I created before this issue, but I still can't see it on the newer automated builds. These do use GitHub instead of BitBucket if that makes a difference.

@febbraro I did try to create a public automated build from a private BitBucket repo so that might have been the issue. As mentioned, moving the repo to GitHub (and making it public) worked for me

I haven't tried again with BitBucket yet.

**Comment by markosamuli** [comment]
Oh well, the deploy key should not exist obviously as the new repos are public. I'll give BitBucket a go and see if it works now.

**Comment by ceecko** [comment]
+1
Works with private repos on dockerhub but not public

**Comment by nhsiehgit** [comment]
Thanks for filing & helping out all - has this been resolved?

I'm going to mark this as triaged for now. If there's still an issue please let us know.

**Comment by referup-amontero** [comment]
The problem still exists if you are trying to create a new automated build on behalf of an organization, since you cannot create new private repos (I supose that this is because organizations do not have free private repo).
Unless there is a way to transfer ownership of an automated build from a user to an organization, any workaround above would work for these cases.

**Comment by kencochrane** [comment]
Confirmed this is an API issue, I have assigned to myself to fix.

**Comment by kencochrane** [comment]
This should be fixed in production, if anyone still sees and issue, please let me know.

**Comment by granvilleschmidt** [comment]
Hi @kencochrane we're still experiencing this issue. Going to try some of the recommendations mentioned above, and will relay our findings.

**Comment by aulizko** [comment]
Hi @kencochrane problem still exist. Build fails with error: 
```
Failed to clone repository: Cloning into '/tmp/build_b8kwrsybbgtxblxphkcjqsb'... Warning: Permanently added the RSA host key for IP address '131.103.20.168' to the list of known hosts. Permission denied (publickey). fatal: Could not read from remote repository. Please make sure you have the correct access rights and the repository exists. 
```
I have private bitbucket repo and I tried to create both private and public automated builds - no one has set deployment keys for bitbucket repo.

**Comment by kencochrane** [comment]
@aulizko Can you give me the docker repo name that isn't working so I can take a look at what might be causing the problem.

**Comment by aulizko** [comment]
@kencochrane I've deleted it yesterday, so right now I created a new one and it seems that the problem remains. Repository: `aulizko/front-vezdehod`.

**Comment by kencochrane** [comment]
@aulizko Thanks for that, I can see the issue, and I'll let you know when it is fixed, so you can test again.

**Comment by aulizko** [comment]
@kencochrane Thanks! I hope it would be simple fix :)

**Comment by kencochrane** [comment]
@aulizko The fix went into prod last night, please try creating an automated build on bitbucket now, and see if it fixes your issue. 

Just to let you know what the issue was, for some reason we were not allowed to add the deploy-key to the bitbucket repo via the API. Either an API or permissions issue. This happens some times, but it shouldn't prevent the deploy key from getting created on our side, which would allow you to manually install the deploy key on the repo from an account that has access. 

This fix was to better handle the error case around not adding the deploy key automatically to your repo.

So, it is possible you still might not see the deploy key on bitbucket, if the permissions are still not working correctly. If so, you will need to manually add the deploy key. The deploy key can be found in the build settings page near the bottom.

If you have any other questions or issues, please let me know.

**Comment by aulizko** [comment]
@kencochrane Hooray!


I was able to create automated build that works and here are the details about how it went:

1. When I clicked to create automated build and chose appropriate repo on the next step, new automated build has been created successfully. It gave back green message (before there was a red one).
2. I clicked "trigger build" and it's status became `pending`. It laster at least 10 min so then I check if deployment keys has been set up properly at bitbucket.
3. So I went at bitbucket repo settings and deployment key wasn't in there.
4. So I went at `build settings` tab and saw deployment key panel at the bottom (there was no such a thing before you have shipped your fix).
5. I set up this key for bitbucket repo. Build status still was `pending`.
6. I was absent for an hour or so, but when I came back, I saw that build status became `done` and it built the image.

So, that's it. I'm happy.
Thank you much and have a nice weekend!

**Comment by kencochrane** [comment]
@aulizko thanks for the update, I'm glad it worked. I'm not sure why we were not able to create the deployment key via the API, but I'm glad you were able to add it manually. Let us know if you need anything else.

**Comment by vannakpanha** [comment]
Make sure your ssh is working 

$ ssh -T git@bitbucket.org

**Comment by JnMik** [comment]
Dockerhub manage to pull my private repository on bitbucket, start building the thing, but then hit a RUN command line that is supposed to run composer install. All the public dependencies install successfully but the when it hit a private repository in the same bitbucket account, it fails.

RUN bash -c "wget http://getcomposer.org/composer.phar && php composer.phar install"

I've checked the ssh keys and the deploy key has deploy itself successfully.
Not sure what I should do to make sure Dockerhub can pull the private dependencies and run the build completely? 

thx

**Comment by vehsakul** [comment]
What if I'm not the owner of organization (so I cannot add deploy keys), it just granted me access on dockerhub?

**Comment by bcwalrus** [comment]
@vehsakul If your GH/BB account is not authorized to add deploy keys, then Hub will still create the automated build, without the deploy key though. Builds will fail to clone your repo. The bottom of the build settings page has the key that somebody in your org can copy-n-paste into GH/BB.

**Comment by vehsakul** [comment]
@bcwalrus I know but this is not very convenient. AFAIK there is no such thing as "add deploy key permission" on GH. Correct me if I'm mistaking.

**Comment by bcwalrus** [comment]
@vehsakul A GH user with the admin role for a repo can add deploy key. https://help.github.com/articles/repository-permission-levels-for-an-organization/#changing-repository-settings

**Comment by svallis** [comment]
I'm having issues with the BitBucket webhook not getting created automatically; doesn't seem to work for personal or organisation repos, whether public or private. The accounts and repos are correctly listed in the drop downs for selection, but when saving the settings it just loses the data.

> So, it is possible you still might not see the deploy key on bitbucket, if the permissions are still not working correctly. If so, you will need to manually add the deploy key. The deploy key can be found in the build settings page near the bottom.

It would be nice if the above worked out of the box, but in the meantime I also can't find the deploy key (or even the build settings page) referred to above. Has this changed, or could somebody point me specifically to where the deploy keys can be found? Thanks in advance.

**Comment by juanjoDiaz** [comment]
I'm having a similar issue in Docker Cloud. A repository that used to work is not working any more, I've tried reconnecting to bitbucket and recreating the automated build (you can remove builds in docker cloud which is another issue.) but I can't get it to create the SSH key in my repo :/

Any suggestion?

**Comment by FedericoBiccheddu** [comment]
It seems only work once per repo and it's impossibile to do deploy in an automated way.

Is there any chance to have a feedback from the staff?

**Comment by tobiassjosten** [comment]
I'm having the same problem. A new Bitbucket repo didn't get a deploy key added to it when I added it to Docker Hub and I can't find any way to have DH re-try that or even give me its public key so I can add it manually. I've tried removing and re-adding the repository and removing and re-connecting the organization in DH from BB. No dice.

With two previous repositories, also on BB, this worked just fine. They were created ~2 months before this one, though, which was created a few weeks ago.

**Comment by ValheKouneli** [comment]
What started a similar problem for me: updating ssh-keys on Bitbucket and DockerHub. First, it was not agle to clone into the git submodules I used. Then, it was not able to pull the main repo. My repo used SSH_PRIVATE environment variable – a private ssh key generated by me. The public pair was added to both my main repo and my submodules in Bitbucket. ALSO the public key provided by DockerHub was added to both. Did not help. Also, my Bitbucket account was connected to my DockerHub account.

What solved this for me: I got rid of the SSH_PRIVATE environment variable and re-built without cache.

**Comment by OMotornyi** [comment]
Hey there. Is there any reliable solution for this issue? We have similar problem in our project where out of tens bitbucker repos (all private) only for one of them deploy keys are created on the docker hub side. For other repositories the keys are simply not created hence we cannot do anything to set up the automated build process. Tried everything mentoined here to no avail. 
Unfortunately filing a support ticket did not help either as for 2 weeks no one is replying to it, so we really don't know what to do (and this is a shame, considering that we are on a paid plan and yet we cannot use features we are payng fror)

**Comment by OMotornyi** [comment]
Stale? Issue not going anywhere
