### ISSUE TITLE
New Products are stuck in "Pending Approval" in the "Docker Hub Publisher Center" for more than 10 days.

### ISSUE THREAD

**Issue by ashvayka** [docker/hub-feedback#2137]
## Problem description
We are trying to publish new product images via Publisher Center. We already have published and verified images. However, adding two new components "[ThingsBoard Professional Edition LwM2M Transport Microservice](https://hub.docker.com/publisher/products/45f09295-10f9-4f5d-a9a0-d1d060366ef4)" and "[ThingsBoard Professional Edition SNMP Transport Microservice](https://hub.docker.com/publisher/products/d18cc316-e11f-48ab-bdd4-dc18808a60ab)" seems to be stuck with no moderator feedback/response, etc. What is the right contact person or email and how to accelerate this process? Many of our users are affected and can't update to the latest version.

**Comment by eunomie** [comment]
Hello @ashvayka 

The two new products have been approved. Sorry for the delay.

**Comment by ashvayka** [comment]
Thank you!
