### ISSUE TITLE
public repositories not found in search

### ISSUE THREAD

**Issue by mikebrow** [docker/hub-feedback#2140]
## Problem description
None of the docker.io/ibmcom account repositories are found in docker hub search.

**Comment by eunomie** [comment]
Hi @mikebrow
The search has been fixed, `ibmcom` repositories are back into the search results.
<img width="925" alt="image" src="https://user-images.githubusercontent.com/1542321/131802496-ee3ea9c0-1d67-4052-aa9f-65aa41434cf9.png">

**Comment by mikebrow** [comment]
Verified working.  Thank you!
