### ISSUE TITLE
Deleted repository (and tags) still show up in the web ui

### ISSUE THREAD

**Issue by wlad** [docker/hub-feedback#2144]
## Problem description
I'm trying to delete an experimental repo on docker hub, but it's still displayed there. Trying to pull an image from the deleted repo indicates that is does not exist any more, though. So I guess Docker Hub UI is not displaying proper information(?)

https://user-images.githubusercontent.com/64201310/131412557-097f8a30-f395-488d-8a61-116382662694.mp4

**Comment by mikeparker** [comment]
Deleting a repository and all images takes a while, it goes on a queue of work and so is not immediate. Can you check back in an hour or so?

**Comment by wlad** [comment]
the repo that I show in example above is still there, but I guess it's because after deleting it I pushed more images to the same namespace.

I think besides the delay of deleted repos/tags to disappear from web ui there were some other outage yesterday, where pushed images were not displayed online :roll_eyes:
