### ISSUE TITLE
How to explore large number of images from Docker Hub?

### ISSUE THREAD

**Issue by martinstraesser** [docker/hub-feedback#2147]
For a data analytics study, I would like to analyze as much images from Docker Hub as possible.

I'm currently investing some effort in a web crawler, however, I am facing the problem that the results from an explicit search or from the explore page are limited to 20 pages, but it says that ` 8.249.493 available images` are stored on Docker Hub. 

Is there any way to get the image names for all public available images from Docker Hub? Or to enlarge to number of pages for the search results? 

Thanks for any feedback.

**Comment by nebuk89** [comment]
Hey Martin, would love to chat about what you are doing at University of Würzburg. can you drop me an email on bengotch@docker.com Thanks!
