### ISSUE TITLE
Pro user extremly slow image downloads

### ISSUE THREAD

**Issue by webmutation** [docker/hub-feedback#2150]
I had to upgrade to Pro account to make use of the automated builds. It has been nothing but problems, builds are triggered twice and download of the images takes almost 10 minutes. This is slowing down our CI considerably, before the image is cached.

Account webmutation.

**Comment by ingshtrom** [comment]
This repository is monitored and responded to on a best-effort basis. Since you have a Pro account, you can use [our support form](https://hub.docker.com/support/contact/) to submit a ticket and receive more timely and personal support.
