### ISSUE TITLE
Setup an Automated Build | Input forms UX issue

### ISSUE THREAD

**Issue by VelizarVESSELINOV** [docker/hub-feedback#216]
Click on "Create", no error message but it is not working.

My Dockerfile is not in the GitHub / root folder but in a subfolder.

Please work on UX of your website for now is far behind github...

**Comment by VelizarVESSELINOV** [comment]
I managed to make it work, but the website is very badly designed (if you have issue no error, debug information). Editing edit box is moving the cursor to the end, etc.

**Comment by rrarunan** [comment]
@VelizarVESSELINOV Thanks for the report and feedback.

 Could you share what browser and OS you are using? esp. RE: the edit box moving the cursor to the end issue.

**Comment by VelizarVESSELINOV** [comment]
Safari 8.0.7 on Mac 10.10.4

**Comment by ChristopherBiscardi** [comment]
@rrarunan The form inputs are something I'm working on. Will close a few issues we're having around them.
