### ISSUE TITLE
Abuse report

### ISSUE THREAD

**Issue by WolfspiritM** [docker/hub-feedback#2167]
## Problem description
Hi. I think there really should be some way to report docker hub abuse.
I've stumbled upon this user https://hub.docker.com/u/afcrypello which either is distributing illegal or malicious stuff.

# Task List
- [x] This is **NOT** a security issue
- [x] I do **NOT** have a Docker subscription
- [x] I have looked through other issues and they do **NOT** apply to me

**Comment by actualben** [comment]
I sent an email to the docker security@ address referencing this issue (and the problem of allowing wide open linking and image embedding in general). Got back a zendesk support issue number `69137`

**Comment by technicallyjosh** [comment]
After confirming on the email thread and the data, we've disabled this account. Thanks for reporting. Closing.
