### ISSUE TITLE
{u'message': u'unauthorized: please use personal access token to login when SSO is enforced'}

### ISSUE THREAD

**Issue by thepixelmonk** [docker/hub-feedback#2181]
```
#21 DONE 0.0s
------
> importing cache manifest from index.docker.io/gsillc/spdhi:latest:
------
Pushing index.docker.io/gsillc/spdhi:latest...
Push failed. Attempt 2 in 60 seconds.
Push failed. Attempt 3 in 60 seconds.
Push failed. Attempt 4 in 60 seconds.
Push failed. Attempt 5 in 60 seconds.
{u'message': u'unauthorized: please use personal access token to login when SSO is enforced'}
```

what is this unauthorized sso stuff we're seeing all of the sudden?

**Comment by pdelaby** [comment]
Same probleme here. 
For info, there is [a thread in the docker forum about the same subject](https://forums.docker.com/t/failed-to-authorize-rpc-error-code-unknown-desc-failed-to-fetch-oauth-token-unexpected-status-401-unauthorized/118562).

**Comment by technicallyjosh** [comment]
👋🏼  So we've been making some changes behind the scenes to upgrade our auth goodies. We are investigating this currently.

**Comment by technicallyjosh** [comment]
This should be resolved now. Feel free to close the issue once confirmed.
