### ISSUE TITLE
Unable to link new dockerhub repositories to bitbucket

### ISSUE THREAD

**Issue by MaximilianB134** [docker/hub-feedback#2184]
## Problem description
We have linked our company bitbucket workspace to dockerhub a long time ago to use automated builds. While trying to connect a new repository on dockerhub to bitbucket since today we get the following error message:

```
Automated build from Bitbucket
Fetch source repositories failed.

Error: Error trying to fetch teams.Connect a Bitbucket account to publicplan to enable automated builds. If it is already connected, please re-link the source provider.
```

To resolve the issue by ourselves we re-linked the bitbucket account at https://hub.docker.com/orgs/*redacted*/settings/linked-accounts with both the bitbucket account used before and another account which was not linked to dockerhub before. Both accounts are administrators of the workspace so they have access to all private repositories. 

So far we had no success to re-enable the repository list. Existing autobuilds nevertheless do work but here we cannot select another bitbucket repository also.

## Debug Information
**Browser name and version**:
 - Firefox 95.0.2 (64-Bit) on macOS 12.1 (M1 Pro)
 - Safari Version 15.2 (17612.3.6.1.6) on the same machine
 - Chrome 96.0.4664.110 (official build, arm64) also on the same machine

**URL**: https://hub.docker.com/repository/docker/*org redacted*/*repo redacted*/builds/edit

**Timestamp or time range**: (YYYY-MM-DD) 2021-12-20; 1 PM CET (UTC+1)

**Hub Username**: maximilianb

**Org Name**: publicplan

## Error messages (on screen or in browser console)
```
Automated build from Bitbucket
Fetch source repositories failed.

Error: Error trying to fetch teams.Connect a Bitbucket account to publicplan to enable automated builds. If it is already connected, please re-link the source provider.
```

# Task List
- [x] This is **NOT** a security issue
- [ ] I do **NOT** have a Docker subscription
- [x] I have looked through other issues and they do **NOT** apply to me

**Comment by ingshtrom** [comment]
Please see [our status page](https://status.docker.com/). We have re-opened our incident to reflect this issue.

**Comment by ingshtrom** [comment]
@MaximilianB134 we have confirmed this is now working for our repositories. Could you please confirm this is working for you, now?

Thank you for your patience!

**Comment by ingshtrom** [comment]
I am going to close this issues as we believe it to be fixed. Please re-open if something still isn't working for you.

**Comment by MaximilianB134** [comment]
@ingshtrom Thank you for your support, the issue was resolved for us.
