### ISSUE TITLE
Missing tag list

### ISSUE THREAD

**Issue by sudo-bmitch** [docker/hub-feedback#2190]
## Problem description

I'm seeing a repo with no tags or readme listed. Not sure if the readme should be there, but the tags are definitely missing from the web page. However, checking from the registry API, there are definitely tags:

```shell
$ regctl tag ls anchore/syft
0
0.14
0.14.0
latest
v0
v0-amd64
v0-arm64v8
v0.15
v0.15.1
v0.15.2
...
```

## Debug Information

**Browser name and version**: Testing on Firefox 91.4.1esr (64-bit) running on Linux

**URL**: <https://hub.docker.com/r/anchore/syft/tags>

**Timetamp or time range**:  EST

**Public IP**: `2600:8806:2400:xx::xx`

**Hub Username**: sudobmitch, but accessing web page without logging in

## Error messages (on screen or in browser console)

Web page:
```
Tags not retrieved
An error occurred while loading the tags. Try reloading the page.
```

Console:
```
Promise rejected after context unloaded: Actor 'Conduits' destroyed before query 'RuntimeMessage' was resolved
index.js:4847
XHRGEThttps://hub.docker.com/v2/user/
[HTTP/1.1 401 UNAUTHORIZED 71ms]

XHRGEThttps://hub.docker.com/v2/user/
[HTTP/1.1 401 UNAUTHORIZED 29ms]

XHRGEThttps://hub.docker.com/v2/user/
[HTTP/1.1 401 UNAUTHORIZED 29ms]

XHRGEThttps://hub.docker.com/v2/repositories/anchore/syft/tags/?page_size=25&page=1
[HTTP/1.1 500 Internal Server Error 447ms]

XHRGEThttps://hub.docker.com/v2/repositories/anchore/syft/tags/?page_size=25&page=1
[HTTP/1.1 500 Internal Server Error 803ms]
```

## Screenshots of the issue (if applicable)

![Screenshot from 2022-01-11 12-31-59](https://user-images.githubusercontent.com/1979858/148993248-3d4f596f-a142-4f48-892c-9d18155179e5.png)

# Task List
- [X] This is **NOT** a security issue
- [X] I do **NOT** have a Docker subscription
- [X] I have looked through other issues and they do **NOT** apply to me

**Comment by silvin-lubecki** [comment]
A fix has been deployed, it should fix the issue. Thanks for reporting it @sudo-bmitch 👍 
<img width="1313" alt="Screenshot 2022-01-18 at 15 34 56" src="https://user-images.githubusercontent.com/31478878/149957618-09dccefd-b5a7-47ba-88c1-edb01d374067.png">

**Comment by silvin-lubecki** [comment]
Let me know if I can close this issue

**Comment by sudo-bmitch** [comment]
LGTM, thanks!
