### ISSUE TITLE
Unable to find Dockerfile on Docker Hub

### ISSUE THREAD

**Issue by pluveto** [docker/hub-feedback#2192]
I'm in China and our government blocked dockerhub. I wanna download some dockerfiles in order to do some custom things. But I cannot find a way to do that.

![image](https://user-images.githubusercontent.com/50045289/150673949-419f1829-f7f0-48f0-a6a2-0eeca3bbd12d.png)
![image](https://user-images.githubusercontent.com/50045289/150673963-7c39df5d-ff88-40fb-a762-2ed8a168eb08.png)
![image](https://user-images.githubusercontent.com/50045289/150673983-2cc80a92-6ead-483e-91b6-97a9f07b05cc.png)

I noticed commands of every layer are given. But I have to copy and paste, which is upsetting.

**Comment by ingshtrom** [comment]
Just to confirm--is this a new issue that has come up?

Is it just pulling images that is the problem? It seems you can access the UI, right?

**Comment by pluveto** [comment]
I'm just wondering whether there is a way to get the original dockerfile of an image from the dockerhub, because in many of my cases, I need to modify some of these instructions in the dockerfile to use mirrors

**Comment by ingshtrom** [comment]
O.o, I misunderstood your question. Unfortunately, there is no great solution for finding the exact Dockerfile contents. You would need to find the source repository on an SCM like GitHub/GitLab/BitBucket/etc, copy the contents, and then make your modifications.
