### ISSUE TITLE
Unable to add or remove additional email addresses

### ISSUE THREAD

**Issue by ct-scheong** [docker/hub-feedback#2193]
Hello,

It appears that the account settings page on Docker Hub no longer allows you to add or remove "additional" email addresses. I have a non-primary email I added to my account a few months ago but I can no longer remove that email from my account. I can only edit the primary email address. Is this a new change to the site, and if so, how do I edit additional email addresses?

According to step 4 in this document page, it should be available: https://hub.docker.com/support/doc/how-do-i-change-my-email-address

**Comment by ob1dev** [comment]
Hi @ct-scheong, I can remove it for you. What's your Docker ID / username?

**Comment by ct-scheong** [comment]
@ob1dev Hello, yes that is correct. I would like to keep the gmail.
