### ISSUE TITLE
All r/ links in hub get 404 error in Opera GX

### ISSUE THREAD

**Issue by Xyndra** [docker/hub-feedback#2196]
Description
![Unbenannt](https://user-images.githubusercontent.com/71836523/151600935-8011a09b-dc98-46fa-96bd-5a126c05a807.PNG)
I am trying to access the link https://hub.docker.com/r/randomdude/gcc-cross-x86_64-elf and somehow all r/ links (I tested others too) are somehow blocked.
Also it takes incredibly long to load the website.
Edit:
It is fast now
Edit 2:
Chrome browser seems to work fine, Opera GX doesn't

**Comment by ingshtrom** [comment]
Please follow https://status.docker.com/. We had some issues over the last several days intermittently. That is likely the cause of the problem you are seeing. 

Thank you.
