### ISSUE TITLE
Pull limit don't get reset

### ISSUE THREAD

**Issue by lettore** [docker/hub-feedback#2197]
## Problem description
I well know that Docker Hub have a pull/push limit of 200 pull/push in 6 hours, I have setup a proxy repository for managing this and until now I didn't had problems.
Recently I had a software problem and one Swarm service that it was pulling directly from the Hub restarted many times hitting the limit.
The problem is, it's more than 24 hours that I'm blocked, and it's possible that other services and the proxy repository itself are trying over and over to pull an image, and it seems this is counting over the limit also if Docker Hub denies the request.
This is really weird and stupid, because in this way I can't go out of the limit if I can't properly pull the image.
I tried to block registry-1.docker.io in DNS resolving for a night but did not resolve.
Just for info I'm migrating all my images to quay.io so I will never be stuck like this.
My account is lettore.
Thanks Docker team for this nice situation.

**Comment by ingshtrom** [comment]
We are sorry this has caused so much trouble! That sounds like a headache.

We have found the problem and are investigating a solution.

**Comment by ingshtrom** [comment]
We deployed a fix for this last week. Sorry for the delay in response!
