### ISSUE TITLE
Expansion of DockerHub's audit log function

### ISSUE THREAD

**Issue by takahashi-jiec** [docker/hub-feedback#2202]
Hi there

I would like to propose a feature to be added to the Audit log in DokerHub.

Currently, the event definitions in the Audit log are as follows
 Organization Event
 Repository events

I think we need a login event to record who logged in and when.
 It would also be better if the IP address from which the access was made is output to the log.

I also think it would be good if the logs are stored on DockerHub for about a year for auditing purposes. Currently, the logs are only saved for 3 months.

https://docs.docker.com/docker-hub/audit-log/

**Comment by technicallyjosh** [comment]
Great suggestion! We've added it as a discussion item. No telling when/if it gets implemented, but thank you for the feedback.

**Comment by technicallyjosh** [comment]
Given that we have this item to discuss, I'm closing this ticket.
