### ISSUE TITLE
Website is broken when cookies are disabled

### ISSUE THREAD

**Issue by OiYouYeahYou** [docker/hub-feedback#2203]
## Problem description

Site does not render anything when cookies are disabled.

## Debug Information
**Browser name and version**:
Confirmed on Chrome and Firefox

## Error messages (on screen or in browser console)

![image](https://user-images.githubusercontent.com/20130059/152441514-24adea0b-72c7-44d4-8a2a-7d2d004c7a3a.png)

# Task List
- [x] This is **NOT** a security issue
- [x] I do **NOT** have a Docker subscription
- [x] I have looked through other issues and they do **NOT** apply to me

**Comment by mark-dr** [comment]
This should be resolved now. @OiYouYeahYou, can you confirm?

**Comment by OiYouYeahYou** [comment]
@mark-dr Seems to be running okay now, there is a slight page load delay due to slow requests. But it has improved over the past few days, thank you.
