### ISSUE TITLE
Careers link is possibly broken

### ISSUE THREAD

**Issue by kevinadhiguna** [docker/hub-feedback#2205]
## Problem description

Hi, this is not a vital issue. I visited Dockerhub in which I clicked a link above navbar. The careers link is possibly broken.

## Debug Information

**URL**: dockerhub.com

## Error messages (on screen or in browser console)

It said : Page not found.

## Screenshots of the issue (if applicable)

Link above navbar component :

![image](https://user-images.githubusercontent.com/43397636/152715249-331f4304-27e3-4a6a-933d-23e27fc91556.png)

will redirect to https://hub.docker.com/careers (Page not found) : 

![image](https://user-images.githubusercontent.com/43397636/152715359-65638ea6-08ba-4cdd-ac7f-0a33976e5cff.png)

----- 

Did Dockerhub mean https://www.docker.com/careers ? 

![image](https://user-images.githubusercontent.com/43397636/152715668-aa7ca67b-6415-41bd-97f5-69672520189f.png)

# Task List
- [x] This is **NOT** a security issue
- [x] I do **NOT** have a Docker subscription
- [x] I have looked through other issues and they do **NOT** apply to me

Thank you.

**Comment by shawnaxsom** [comment]
Thanks! Yes, the banner was intended for www.docker.com at first, it's probably redirecting to /careers without considering the subdomain. We'll get it fixed.

**Comment by shawnaxsom** [comment]
Okay I think I fixed it 🙂 Try again?

**Comment by kevinadhiguna** [comment]
Cool, it works now. Thanks @shawnaxsom !
