### ISSUE TITLE
401 / 404 Authorisation issues - Cannot CREATE Repository

### ISSUE THREAD

**Issue by mistergjones** [docker/hub-feedback#2210]
## Problem description

When attempting to CREATE a repository by clicking the button, a spinning circle appears and nothing else happens.

When viewing the PAGE SOURCE, it seems that there are 401 / 404 / API issues that prevents this capability.

Please refer to screenshot for detailed information.

More information is also found in this forum showing **many people** are now experiencing the same issue: https://forums.docker.com/t/cannot-create-a-repository/121339 

This happens in both CHROME and SAFARI

## Debug Information
**Browser name and version**: Version 98.0.4758.102 (Official Build) (x86_64)

**URL**: https://hub.docker.com/repository/create?namespace=mrgjones

**Public IP**: ? [110.144.58.153](https://whatismyipaddress.com/ip/110.144.58.153)

**Hub Username**: mrgjones

## Error messages (on screen or in browser console)

Failed to load resource: the server responded with a status of 401 (UNAUTHORIZED): https://hub.docker.com/v2/repositories/namespaces/

Failed to load resource: the server responded with a status of 401 (UNAUTHORIZED): https://hub.docker.com/v2/repositories/mrgjones/?page_size=25&page=1&ordering=last_updated

Failed to load resource: the server responded with a status of 401 (UNAUTHORIZED):
https://hub.docker.com/v2/users/mrgjones/registry-settings/

Failed to load resource: the server responded with a status of 404 ():
https://secure.gravatar.com/avatar/c94b96ccb7e4f466d1368e00d1082178.jpg?s=80&r=g&d=404

## Screenshots of the issue (if applicable)

# Task List
- [X] This is **NOT** a security issue
- [X] I do **NOT** have a Docker subscription
- [X] I have looked through other issues and they do **NOT** apply to me

**Comment by mistergjones** [comment]
![DockerCreateRepository](https://user-images.githubusercontent.com/37855622/154823860-0343fa5d-70a7-4507-a49e-df471a34e130.png)

**Comment by ingshtrom** [comment]
Yup, we ave an active incident going on right now. You can follow along at [status.docker.com](https://status.docker.com/).

We did roll out part of the fix already. We are actively working on the full fix.

Thank you for your patience.

**Comment by shawnaxsom** [comment]
The issue should be resolved. We fixed the root cause and backfilled user configuration that was missing.

Feel free to reopen if you're still having issues.
