### ISSUE TITLE
Can't delete repository

### ISSUE THREAD

**Issue by ratanservegar** [docker/hub-feedback#2211]
Hi,
When I delete a repo by providing the name it doesn't delete it

"There was an error. The repository was not deleted."

![1](https://user-images.githubusercontent.com/31865710/155003743-d321a9df-7cc4-4f66-b44a-42716696ef30.png)
![2](https://user-images.githubusercontent.com/31865710/155003753-91fdfec7-9301-4142-b05e-488c6633bd54.png)
![3](https://user-images.githubusercontent.com/31865710/155003780-eebc6c14-dfdd-4e06-a4c0-c0492b21a5c6.png)

Not sure, if the below is the reason for the error but the main reason I am deleting this repo is because when i push a image to this repo it says access denied all the time, I've logged out and re logged in many times, however it still says access denied, however I can push images to other repo in my account.

I also noticed the following in the request logs
![4](https://user-images.githubusercontent.com/31865710/155003814-a188b511-5523-4c60-b637-d86301169272.png)
![5](https://user-images.githubusercontent.com/31865710/155003819-37b916a8-40d5-48bf-a410-263276e1f531.png)

**Comment by milosgajdos** [comment]
Hi @ratanservegar, since you are on a Personal Plan (i.e. free plan which explains the `404` in the billing API endpoint you are seeing), you are only allowed a single private repository and we've noticed you have created 2 more which immediately got locked. If you would like to unlock them you'd have to switch to a paid plan.

**Comment by ratanservegar** [comment]
Hi [milosgajdos](https://github.com/milosgajdos),

I am aware of the limit on the free plan, and i've deleted the 3rd repo, however I am unable to delete a image called commadservice in my repo. I've tried several times to delete it and it doesnt work.

ratanservegar /commandservice

![image](https://user-images.githubusercontent.com/31865710/155025662-e906c172-1ba2-4d4d-958d-a3d3a6d0b925.png)

**Comment by milosgajdos** [comment]
@ratanservegar can you please try again?

**Comment by milosgajdos** [comment]
I've noticed you've now deleted the repo, so I'm closing this ticket.

**Comment by ratanservegar** [comment]
Hi [milosgajdos](https://github.com/milosgajdos), 

Strange, when i logged in today the repo was gone, I did not manually delete the repo today!
