### ISSUE TITLE
Remove IP from blacklist

### ISSUE THREAD

**Issue by danxvv** [docker/hub-feedback#2217]
Hi,
I try to use registry.hub.docker.com in a caprover instance and I can't, on others server with the same caprover version I can use it perfectly, i got this message: toomanyrequests: too many failed login attempts for username or IP address.
the ip is:
45.79.7.34

can you check if this ip is blocked and remove it from the blacklist please.

**Comment by ingshtrom** [comment]
This is a temporary block caused by an incorrect username and password.  Please try again after 15 minutes. 

It isn't tied to the IP. We will look at making that error message clear
