### ISSUE TITLE
Is Docker Hub abandoned?

### ISSUE THREAD

**Issue by koyadume** [docker/hub-feedback#2219]
I have a personal account on dockerhub with **koyadume** username. Last year I was subscribed to monthly payment plan till mid of March and tried to convert it to Annual plan but it deducted money for both the plans without refunding amount paid towards the monthly plan. Sent an email to support team using https://hub.docker.com/support/contact/ link but have not got any reply till date. Tried to contact docker using different means (e.g. Twitter) but never got any response. My annual subscription was due for renewal on 14th of March this month but it has failed multiple times in spite of adding details of multiple credit cards. This is happening due to a mandate by RBI (India's central bank and regulatory body) around standing instructions if these are not compliant to some rules which seems to be the case with Dockerhub and so credit card payment is not going through. Wrote an email to support again on 16th of March using same link (https://hub.docker.com/support/contact/) but have not got any response till date again. Without renewal it will downgrade my plan to free plan which will expose my private repositories and so far I have not been able to figure out how to make the payment go through without some support from docker side. Can someone please help?

**Comment by shawnaxsom** [comment]
Hey @koyadume, sorry about that! I've raised this with support.

Do you have a ticket ID that I could share with them?

**Comment by koyadume** [comment]
Hi @shawnaxsom, I believe ticket ID is 79791 because that is the only number I see in the subject of the email I got after opening a ticket with dockerhub support team -

**Docker Support [Request received] - Payment failed in spite of updating credit card details (#79791)**

**Comment by koyadume** [comment]
It seems other users from India have already reported this issue in #2160.

**Comment by koyadume** [comment]
Thanks @shawnaxsom for your help. Docker hub support team responded to my ticket and the issue is now resolved.
