### ISSUE TITLE
description table support, markdown rules / parser

### ISSUE THREAD

**Issue by svenevs** [docker/hub-feedback#2229]
Hey Team :slightly_smiling_face:

I've seen a couple of markdown related issues, #124 and possibly related #179.  I've searched around a lot but "docker hub description markdown syntax" etc are all rather overloaded search terms :scream:

I was looking into how to fix the `<table>` rendering at https://hub.docker.com/r/pandoc/latex

![texlive-table-version](https://user-images.githubusercontent.com/5871461/165014717-306289ad-c56e-4af5-af32-f12db163a5e2.png)

I tried a couple of different versions in a test repository, but don't seem to have success in creating a `<table>` either with html directly or via markdown.

1. Are tables supported?
2. Would you be willing to share what parser is being used for the markdown?  I couldn't find any specific documentation on what is or is not allowed anywhere, but that could very well be for lack of looking in the right place (if so, sorry in advance!).  I think users would benefit from knowing what is or is not supported in general.

Thanks for any suggestions!

# Task List
- [X] This is **NOT** a security issue
- [X] I do **NOT** have a Docker subscription
- [X] I have looked through other issues and they do **NOT** apply to me

**Comment by rossipedia** [comment]
Thanks for reporting this. A fix has been identified and will be rolling out shortly :)
