### ISSUE TITLE
SVG images not rendering correctly in Docker Hub

### ISSUE THREAD

**Issue by jawnsy** [docker/hub-feedback#2230]
## Problem description

SVG images render correctly in GitHub markdown, but do not render in Docker Hub.

## `docker info` output

Docker Info:
```yaml

```

## Debug Information
**Browser name and version**:

Chrome Beta
Version 101.0.4951.41 (Official Build) beta (arm64)

Running on macOS with Apple Silicon

**URL**: https://hub.docker.com/r/prefecthq/prefect

**Timetamp or time range**: 

**Public IP**: 

**Hub Username**:

## Screenshots of the issue (if applicable)

For example, the `prefecthq/prefect` image has the following [README.md on GitHub](https://github.com/PrefectHQ/prefect/blob/master/README.md):

![image](https://user-images.githubusercontent.com/52710/165130003-a6735364-bbc3-4093-a186-03bce90e44de.png)

The [Docker Hub page for `prefecthq/prefect`](https://hub.docker.com/r/prefecthq/prefect) looks like this:

![image](https://user-images.githubusercontent.com/52710/165129895-6b970cd3-f900-44f7-bcbf-53476d43032f.png)

# Task List
- [x] This is **NOT** a security issue
- [x] I do **NOT** have a Docker subscription
- [x] I have looked through other issues and they do **NOT** apply to me

**Comment by rossipedia** [comment]
Thanks for catching this. A fix has been identified and will be rolling out shortly.
