### ISSUE TITLE
Remove IP from blacklist

### ISSUE THREAD

**Issue by cornfeedhobo** [docker/hub-feedback#2231]
## Problem description

I iterated on a new k8s cluster a few times and now cloudflare is timing out. I've got enough points of presence to verify that this is due to some blocking somewhere.

## Debug Information

**Public IP**: `162.254.118.15` (It appears to be all of `162.254.118.0/24`)

**Hub Username**: cornfeedhobo

## Error messages (on screen or in browser console)

```
error pulling image configuration: Get "https://production.cloudflare.docker.com/registry-v2/docker/registry/v2/blobs/sha256/3d/3db6b894c1ca2a107f1d9f7335e63397a98ad81b69b87d02fb6570fb9c43a4c8/data?verify=1651627607-QpI4j0%2B32M7yu9AtOhODrjmgG%2BA%3D": dial tcp 104.18.125.25:443: i/o timeout
```

# Task List
- [x] This is **NOT** a security issue
- [x] I do **NOT** have a Docker subscription
- [x] I have looked through other issues and they do **NOT** apply to me

**Comment by cornfeedhobo** [comment]
cc @ingshtrom @milosgajdos 

Is IP allow listing exposed through the hub UI? If so, I'll pay for an account... All I want to do is iterate on some dev cluster setups :sweat_smile:

**Comment by RomainBelorgey** [comment]
Hi,

We are not blocking this IP or the block ip.
If your IP is blocked, you should receive a http error 429.

Looking at the error you got, it looks to failed to contact the ip behind the url.

This url is hosted on our CDN (cloudflare), or you sure that you don't have anything blocking the requests with them ?

**Comment by RomainBelorgey** [comment]
I can see 2 access logs around 00:00 UTC 2022/05/04:
```
"162.254.118.15:40934 [03/May/2022:23:59:10.976]  200 3523 - - ---- 1631/1614/30/4/0 0/0 {hub.docker.com\|Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36} -- \"GET /v2/repositories/cornfeedhobo/monero/tags/?page_size=25&registry&ordering=last_updated HTTP/1.1\""
"162.254.118.15:56912 [03/May/2022:23:59:07.911]  200 3523 - - ---- 1637/1624/27/3/0 0/0 {hub.docker.com\|Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36} -- \"GET /v2/repositories/cornfeedhobo/monero/tags/?page_size=25&registry&ordering=last_updated HTTP/1.1\""
```

So it confirms that we are not blocking this IP and looks like issue to contact cloudflare.

**Comment by cornfeedhobo** [comment]
@RomainBelorgey Thank you. I'll take this up on my end.
