### ISSUE TITLE
Continue unsuccessful email verification

### ISSUE THREAD

**Issue by renyu2016** [docker/hub-feedback#2233]
## Problem description
I m trying to activate my docker hub account. I can receive verification emails, but when I click the verification link,  the webpage shows: Unsuccessful Email Verification Please sign in and from there, request a new verification email. Contact customer support if this issue occurs repeatedly.
I have tried many times, but it still tells me verification is unsuccessful. What should I do?

## `docker info` output

Docker Info:
```yaml
Unsuccessful Email Verification
Please sign in and from there, request a new verification email.
Contact customer support if this issue occurs repeatedly.

```

## Debug Information
**Browser name and version**:

**URL**:

**Timetamp or time range**: 

**Public IP**: 

**Hub Username**:

## Screenshots of the issue (if applicable)

# Task List
- [ ] This is **NOT** a security issue
- [ ] I do **NOT** have a Docker subscription
- [ ] I have looked through other issues and they do **NOT** apply to me

**Comment by msteffeck** [comment]
I am also experiencing this issue

**Comment by jayanandagit** [comment]
have same issue.

**Comment by renyu2016** [comment]
I leave messages to the hub support on the webpage and they manually verified the email address. It seems all normal now.
