### ISSUE TITLE
Collaborative Private Repo Not Visible [again]

### ISSUE THREAD

**Issue by Nightlord851108** [docker/hub-feedback#2244]
Hello, 

I cannot see the collaborative private repositories on my dashboard in Docker hub. 
I can pull these private docker images. 

it seems there's a similar bug fixed long ago, but it seems that it happens again.

**Comment by milosgajdos** [comment]
What's the namespace and the name of the repository?

**Comment by Nightlord851108** [comment]
> What's the namespace and the name of the repository?

The namespace is "ezkanban", and all the repositories are not shown in my dashboard. One of the repositories is "
ezkanban-frontend-dev"

**Comment by milosgajdos** [comment]
What's the username you are accessing it with?

**Comment by Nightlord851108** [comment]
> What's the username you are accessing it with?

Hello, the username I'm using is "nightlord851108"

**Comment by milosgajdos** [comment]
Hey @Nightlord851108, apologies for the late reply -- I was swamped with some work.

My understanding of this is, that you don't see the `ezkanban` namespace in the dropdown button when trying to list the repos you have been added as a collaborator on? Is that right?

In that case, that's actually expected. `ezkanban` is a _USER_ `namespace`, so you won't be able to see the `repos` in the repository list, but the pulls will continue to work as expected given you are a collaborator. I'd be surprised if this ever worked.

If `ezkanban` gets converted to an _ORGANISATION_  (follow this [ur](https://hub-stage.docker.com/settings/convert)) things should work as per your current expectation -- mind you if you convert from User namespace to Organisation your paid plan will change, too.

There is no plan to make the repo list uniform across different types of accounts at the moment.

**Comment by Nightlord851108** [comment]
Hi, @milosgajdos 
Thank you so much for such a detailed reply.
You've answered all my questions.
