### ISSUE TITLE
Image management endpoints not returning 404s and 500s

### ISSUE THREAD

**Issue by mbentley** [docker/hub-feedback#2249]
## Problem description

Today, one of the advanced image management APIs started returning 404s:

For example, opening up the image management page for a repo:
`https://hub.docker.com/usage/docker/mbentley?repo=acme.sh&returnTo=%2Frepository%2Fdocker%2Fmbentley%2Facme.sh`

I can see that the following returns a 404 from my Chrome dev tools:
```
https://hub.docker.com/v2/namespaces/mbentley/repositories/acme.sh/images-summary?can_edit=true
```

In addition, the delete endpoint is failing with a `500 Internal Server Error`:

`https://hub.docker.com/v2/namespaces/mbentley/delete-images`

![delete](https://user-images.githubusercontent.com/414445/175771696-6498a188-44ad-4831-a996-ce79af009df8.gif)

## `docker info` output
n/a

## Debug Information
Google Chrome and also happens with curl

**URL**:

June 27, 7:30am Eastern

**Public IP**:  `104.254.222.95`

**Hub Username**: mbentley

## Error messages (on screen or in browser console)
404 and 500; see screen shot for Hub UI

## Screenshots of the issue (if applicable)
See above

# Task List
- [ X ] This is **NOT** a security issue
- [ X ] I do **NOT** have a Docker subscription
- [ X ] I have looked through other issues and they do **NOT** apply to me

**Comment by thaJeztah** [comment]
Hi! 👋  Hmm, let me ask internally if there's a known issue

**Comment by thaJeztah** [comment]
Oh! Got a reply, and they seem to found an issue; they're looking into it 🎉

**Comment by milosgajdos** [comment]
Hi @mbentley, can you please check if you are still seeing these issues. I believe they should now be fixed.

**Comment by mbentley** [comment]
Thanks!  Looks like it's working again.

**Comment by milosgajdos** [comment]
Awesome! I'm closing this issue, but feel free to reopen it if you need to.
