### ISSUE TITLE
Font size rendering for markdown syntax "-" and "=" in README.md

### ISSUE THREAD

**Issue by nmarus** [docker/hub-feedback#225]
I have noticed a font size rendering issue for MD syntax. Mainly "=" should render a larger font than "-", but the reverse is true. Notably, this is correct here...  but will render the opposite on the hub page. 

Test
----

Test
====

**Comment by ChristopherBiscardi** [comment]
This has been deployed.

**Comment by jakirkham** [comment]
So, glad to have this fix. :+1:
