### ISSUE TITLE
Get Image Tags returns 403 using personal access token

### ISSUE THREAD

**Issue by aldobongio** [docker/hub-feedback#2253]
Hello, today we are experiencing exactly the same issue as #2171 and #2247. The only difference is in the errinfo detail.

Starting from today listing image tags using a token obtained via personal access token returns a 403.

To replicate:

1. Login on hub.docker.com using a regular user and its main password
2. Profile > Account Settings > Security > New Access Token > Copy the access token

Now open a Linux environment with `curl` available:
```
TOKEN=$(curl -s -H "Content-Type: application/json" -X POST -d '{"username": "<USERNAME>", "password": "<MAIN_PASSWORD>"}' https://hub.docker.com/v2/users/login/ | jq -r .token )
curl -s -H "Content-Type: application/json" -H "Authorization: JWT ${TOKEN}" -X GET "https://hub.docker.com/v2/repositories/<ORGANIZATION>/<IMAGE_NAME>/tags/?page=1&page_size=10000"
{"count":... }

TOKEN=$(curl -s -H "Content-Type: application/json" -X POST -d '{"username": "<USERNAME>", "password": "<PERSONAL_ACCESS_TOKEN>"}' https://hub.docker.com/v2/users/login/ | jq -r .token )
curl -s -H "Content-Type: application/json" -H "Authorization: JWT ${TOKEN}" -X GET "https://hub.docker.com/v2/repositories/<ORGANIZATION>/<IMAGE_NAME>/tags/?page=1&page_size=10000"
{"message":"request to https://accounts-api.s.us-east-1.aws.dckr.io/api/internal/user/ failed with status 403: {\"message\":\"access is forbidden with a JWT issued from a personal access token\",\"errinfo\":{}}\n"}
```

Until yesterday the API invocation using the token obtained from a login with a personal access token worked perfectly. Today is not working. And is forcing us to store in our CI/CD environment the master password of the user responsible of reading/writing the Docker Hub registry, like in the pre-access-token era.

**Comment by milosgajdos** [comment]
Hi @aldobongio, this is slightly embarrassing for us, and I've no excuse for this, I'm afraid. We appreciate your prompt reporting of this issue and all your patience. We have identified an issue and deployed the fix to production now. Thanks for reporting again.

**Comment by aldobongio** [comment]
@milosgajdos No problem: it's not such a big issue and the workaround (use the master password) is very easy to apply ... so don't worry :)

**Comment by milosgajdos** [comment]
I am closing this issue. Feel free to reopen. Thanks again!
