### ISSUE TITLE
/go/src/github.com/docker/saas-mega/lib/go-pg/error.go.Github.com/docker/saas-mega/lib/go-pg.error.Createrepository query error.

### ISSUE THREAD

**Issue by imoisharma18** [docker/hub-feedback#2255]
## `docker info` output

Docker Info: /go/src/github.com/docker/saas-mega/lib/go-pg/error.go.Github.com/docker/saas-mega/lib/go-pg.error.Createrepository query error.

```yaml

```

## Debug Information
**Browser name and version**:

**URL**:

**Timetamp or time range**: 

**Public IP**: 

**Hub Username**:

## Screenshots of the issue (if applicable)

# Task List
- [ ] This is **NOT** a security issue
- [ ] I do **NOT** have a Docker subscription
- [ ] I have looked through other issues and they do **NOT** apply to me

**Comment by ingshtrom** [comment]
Closing due to lack of information.
