### ISSUE TITLE
504s when accessing Docker Hub API

### ISSUE THREAD

**Issue by elishagreenwald** [docker/hub-feedback#2258]
Getting 504s when calling GET https://hub.docker.com/v2/repositories/{org}/{repo}/tags/{tag}

**Comment by elishagreenwald** [comment]
Now working but seems lots of latency

**Comment by binman-docker** [comment]
Just following up - this was related to the incident earlier today, documented on the status page here: https://status.docker.com/pages/history/533c6539221ae15e3f000031

Functionality was restored a few hours ago and we cleared out the incident after making some additional changes to mitigate future scenarios like this.
