### ISSUE TITLE
My public Docker Hub repo can be pulled but cannot be searched, any help?

### ISSUE THREAD

**Issue by hellodk34** [docker/hub-feedback#2260]
My image in docker hub why does not appear in the search result? neither with the `docker search` CLI command.

More information would be useful:

- the public image I uploaded 2 days ago.
- the image is `dko0/squoosh`, it has two tags named `latest` and `1.12.0`, it's public address in docker hub is https://hub.docker.com/r/dko0/squoosh , you can do a pull.

Why it not appeared in the search result? the index system broken?

Looking forward to your reply, thanks!

**Comment by hellodk34** [comment]
Any help would be appreciated.

**Comment by milosgajdos** [comment]
Hi, thanks for the report. We've identified the issue and are working on getting it fixed. We dont have any ETA on the fix at the moment.

**Comment by hellodk34** [comment]
@milosgajdos Thank you so much for tracking down this issue. Looking forward to your good news.

**Comment by hellodk34** [comment]
@milosgajdos It displayed in the search result!

Really thanks, you did good job. ❤
