### ISSUE TITLE
Consider disabling autocomplete in the TFA input

### ISSUE THREAD

**Issue by dimaqq** [docker/hub-feedback#2267]
How it looks now:

![Screenshot from 2022-09-07 09-24-24](https://user-images.githubusercontent.com/662249/188762735-0980bb3e-889b-48db-81d5-33ac7486eaab.png)

How to fix it: `spellcheck="false" autocorrect="off" autocapitalize="off" autocomplete="off"`

**Comment by nico1510** [comment]
thanks a lot for your suggestion 👍  This should be fixed by now.
