### ISSUE TITLE
Please remove IP from blacklist

### ISSUE THREAD

**Issue by FrancescoMez79** [docker/hub-feedback#2268]
Hello,
from some days hub.docker.com is issuing error:
"message": "You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit"

Investigating we have understand that our public IP : 84.253.147.38 has been blacklisted.
This because we have inadvertently made an error using the tool watchtower with an interval of 5seconds.
We have already fixed this, setting the default value of 24hours.

May you please remove our IP from docker blacklist?

Thanks and best regards,
Francesco

**Comment by binman-docker** [comment]
Hi Francesco, that rate limit is evaluated over a period of six hours: https://docs.docker.com/docker-hub/download-rate-limit/#what-is-the-download-rate-limit-on-docker-hub

Now that you've fixed the issue with Watchtower, you should be ok in a few hours.

**Comment by FrancescoMez79** [comment]
Hello,
thanks for your reply.
It worked until a few days ago. We tried today and we have the problem again.
We are re-checking the watchtower configuration. We have removed the "interval" field which by default should be 24 hours.

May you please remove our IP from docker blacklist?

Thanks,
Francesco
