### ISSUE TITLE
Windows installer doesnt work

### ISSUE THREAD

**Issue by vicglarson** [docker/hub-feedback#2269]
Component CommunityInstaller.EnableFeaturesAction failed: 
   at CommunityInstaller.InstallWorkflow.<DoHandleD4WPackageAsync>d__30.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CommunityInstaller.InstallWorkflow.<DoProcessAsync>d__2
3.MoveNext()

![image](https://user-images.githubusercontent.com/222960/189487851-2762d11d-dfae-4fb3-b348-2fc11636edbe.png)

**Comment by vicglarson** [comment]
https://stackoverflow.com/questions/71095210/installing-docker-desktop-4-5-0-failed-componet-communityinstaller-enablefeatur 
https://programmersought.com/article/29075200559/
etc doent help
hope it possible to fix installer

**Comment by binman-docker** [comment]
Hi @vicglarson - this repository is for feedback on Docker Hub. You can submit issues with Docker Desktop for Windows here: https://github.com/docker/for-win/issues
