### ISSUE TITLE
How to use new Build triggers ?

### ISSUE THREAD

**Issue by bersace** [docker/hub-feedback#2270]
## Problem description

Hi,

I don't find any mention of Build triggers in https://docs.docker.com/docker-hub/builds/ . Can you point how to use new `https://hub.docker.com/api/build/v1/source/XXX/trigger/XXX/call/` endpoint ?

Regards,
Étienne BERSAC,
DALIBO

# Task List
- [x] This is **NOT** a security issue
- [x] I do **NOT** have a Docker subscription
- [x] I have looked through other issues and they do **NOT** apply to me

**Comment by mcapell** [comment]
Hi @bersace! You can create a new build trigger in the Autobuild configuration in Hub (from your repository, go to builds / Configure automated builds / Build triggers). In order to use it, just create a POST request to the trigger's URL.

**Comment by bersace** [comment]
Hi @mcapell, thanks for the reply.

Can you confirm an empty payload is accepted ?

Regards,

**Comment by bersace** [comment]
Is it possible to trigger a specific tag ou build rule ?

**Comment by bersace** [comment]
Got it, thanks @mcapell  !
