### ISSUE TITLE
Public image not showing up in search for 3 days

### ISSUE THREAD

**Issue by shiomax** [docker/hub-feedback#2276]
https://hub.docker.com/r/shiomax/jrivermc30

Pushed this image 3 days ago. It still does not show up in search as of right now. From what I could find images are supposed to show up within 24 hours. Or does it just take longer now?

There have been other issues about this fairly recently too: https://github.com/docker/hub-feedback/issues/2260

**Comment by silvin-lubecki** [comment]
Hello @shiomax, the root cause of this issue has been found, I'll let you know as soon as the fix is deployed 👍

**Comment by silvin-lubecki** [comment]
Hello @shiomax, the search has been fixed, your repository is now available in search results https://hub.docker.com/search?q=shiomax%2Fjrivermc30 . Thank you for opening this issue 👍

**Comment by shiomax** [comment]
Great, thanks! :)
