### ISSUE TITLE
Venue for Discussion of Registry API?

### ISSUE THREAD

**Issue by dweekly** [docker/hub-feedback#2278]
I wasn't able to find any place in the Docker Registry API documentation as of v2.0l at https://docs.docker.com/registry/spec/api/ that mentioned venues for discussion about potential enhancements (e.g. around a v3.0 API).

Is there a mailing list or other forum for those interested in the evolution of the Registry API?

**Comment by binman-docker** [comment]
Hi @dweekly - the Distribution project (on which Registry is based) was donated to the CNCF. You can find the repository here: https://github.com/distribution/distribution. It looks like they have a channel in the CNCF Slack.

**Comment by dweekly** [comment]
Ah, that's exactly the right place, thank you. I'll close this.

**Comment by milosgajdos** [comment]
`distribution` is a great place to start the conversation but if you really want to start the conversation with people that can change things I'd recommend asking in https://github.com/opencontainers/distribution-spec

No spec change = no party.
