### ISSUE TITLE
Could not list Tags in my repository

### ISSUE THREAD

**Issue by mehmetdogan74** [docker/hub-feedback#2279]
My builds are working fine but I could not list Tags.

My repo: https://hub.docker.com/repository/docker/geosolutionsit/geoserver/tags?page=1&ordering=last_updated

![image](https://user-images.githubusercontent.com/78139964/198120364-17511379-d416-4bb5-a3b0-aa96231ce7f6.png)

![image](https://user-images.githubusercontent.com/78139964/198120765-ef34f1d9-d4ea-4d16-b7cc-5081688bbce7.png)

**Comment by eunomie** [comment]
Hi,
It looks like an error occurred but everything looks like to work as expected now.
I can see your different tags on https://hub.docker.com/r/geosolutionsit/geoserver/tags

**Comment by mehmetdogan74** [comment]
thanks a lot I can see them too

**Comment by milosgajdos** [comment]
I'm going to close this ticket @mehmetdogan74. Feel free to reopen if the issue occurs again.
