### ISSUE TITLE
unable to sinup in docker 

### ISSUE THREAD

**Issue by TarakaSatyaRaju** [docker/hub-feedback#2284]
I am trying to signup for a Docker ID, the site allows me to type username/email/password combination.
It doesn't give any feedback of success on screen
It doesn't email me(I don't know if it should)
I cannot then sign in with the username and password just registered.
Tried in Chrome and IE, (interestingly chrome does not warn that username can only contain letters, IE does)

## Security Issues
If you are reporting about security vulnerability in the site or about some malicious image that
should be taken down ASAP then please report it via email to security@docker.com. 

## Issues related to running a container in a user's local environment or user's on-prem/cloud based cluster.
- If you are a community user using our Docker Engine product, Please go to https://forums.docker.com/ and verify if other members in the community have run into this issue, or post an issue back to the community.
- If you are a user with a subscription to Docker, you can go to https://hub.docker.com/support/contact/ and create a support ticket.

Please, verify if similar issue is already open by someone else before creating new one. You can
thumbs up an existing issue to express your concern. 

-->

## `docker info` output

Docker Info:
```yaml

```

## Debug Information
**Browser name and version**:

**URL**:

**Timetamp or time range**: 

**Public IP**: 

**Hub Username**:

## Screenshots of the issue (if applicable)

# Task List
- [ ] This is **NOT** a security issue
- [ ] I do **NOT** have a Docker subscription
- [ ] I have looked through other issues and they do **NOT** apply to me

**Comment by rossipedia** [comment]
Can you give me some more information? What OS/Browser (including versions) are you seeing this on? Also, what specific URL are you using to signup (we have a few)?

**Comment by TarakaSatyaRaju** [comment]
Hi
I am. Using both chrome and IE

I am. Using the URL job. Docker. Com

I try to click the sign up button but it is not going to work

**Comment by TarakaSatyaRaju** [comment]
URL hub.docker.com

**Comment by mbaddi** [comment]
The response of singup request is

**Comment by ArpadGBondor** [comment]
Same problem here. Server keeps responding to Sign up requests with Error 500, unable to validate recaptcha.

**Comment by TarakaSatyaRaju** [comment]
Hi,
 I am not get anything when I try to click sign up button it still stay in
the same position and same page

**Comment by moonlightlane** [comment]
same problem. please help. thanks!

**Comment by shawnaxsom** [comment]
Thanks for the feedback all, we're investigating.

We may have identified the change that caused the issue.

We'll update here when resolved.

**Comment by rossipedia** [comment]
We believe we've found the issue and have deployed a fix. Please try again and let us know if you are still experiencing difficulty signing up, in which case we will re-open this issue. Thanks!
