### ISSUE TITLE
`rockylinux` container lacks a `latest` tag

### ISSUE THREAD

**Issue by mernst** [docker/hub-feedback#2286]
## Problem description

https://hub.docker.com/_/rockylinux
contains the command `docker pull rockylinux` near the upper right corner.

This command does not work.  The output is

```
% docker pull rockylinux
Using default tag: latest
Error response from daemon: manifest for rockylinux:latest not found: manifest unknown: manifest unknown
```

However, running `docker pull rockylinux:9` does work.

## Debug Information
**Browser name and version**:
Chrome Version 107.0.5304.110 (Official Build) (64-bit)

**URL**:
https://hub.docker.com/_/rockylinux

**Timetamp or time range**: 
Sun Nov 13 05:18:47 PM PST 2022

**Hub Username**:
mdernst

# Task List
- [X] This is **NOT** a security issue
- [X] I do **NOT** have a Docker subscription
- [X] I have looked through other issues and they do **NOT** apply to me

**Comment by binman-docker** [comment]
This appears to be intentional per the maintainers: https://github.com/docker-library/official-images/issues/12797

**Comment by mernst** [comment]
Thanks for that information.  I'll close the issue.
