### ISSUE TITLE
Problem accessing public repository page (404)

### ISSUE THREAD

**Issue by IvoMajic** [docker/hub-feedback#2288]
Our **public** repository is about a week old now ( https://hub.docker.com/r/arcionlabs/replicant-on-premises ) but non-registered users can not access it via a web browser (they get a 404 page). 

To make it weirder it does show up in the search for non-registered users - https://hub.docker.com/search?q=arcionlabs , but accessing it gives a 404 page again.

**Comment by milosgajdos** [comment]
Hi, @IvoMajic. We identified the issue was caused by a bad deployment that shipped code that skipped past our CI checks. We rolled it back and addressed the issue -- everything should be back to normal. Apologies for the inconvenience.

**Comment by IvoMajic** [comment]
Thank you @milosgajdos, it works now.
