### ISSUE TITLE
Docker is not compatible with Almalinux 8 and 9 Firewall

### ISSUE THREAD

**Issue by dainora** [docker/hub-feedback#2289]
![image](https://user-images.githubusercontent.com/3883196/202156672-259077d4-2673-4cdc-9a49-5d3232b4cba4.png)
Tried with ALmalinux 8 and 9 same issue.

Docker is not compatible with Firewall, it should be compatible during installation, after OS or firewall reboot.

Client: Docker Engine - Community
 Version:           20.10.21
 API version:       1.41
 Go version:        go1.18.7
 Git commit:        baeda1f
 Built:             Tue Oct 25 18:02:19 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.21
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.7
  Git commit:       3056208
  Built:            Tue Oct 25 18:00:24 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.9
  GitCommit:        1c90a442489720eec95342e1789ee8a5e1b9536f
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

**Comment by binman-docker** [comment]
Hi @dainora - this would be related to the Engine rather than Hub. You can post this issue here: https://github.com/moby/moby/issues
