### ISSUE TITLE
Please remove IPs from blacklist

### ISSUE THREAD

**Issue by amajauskas** [docker/hub-feedback#2293]
Hello,

Recently we have been trying to access download.docker.com from this IP address (144.121.20.86) and were not able to connect, all of the traffic on our side is allowed and we have no reason to believe that its being blocked internally.
Have not tried from secondary IP, but would be great to make sure that its unblocked too.

**Public IPs**:
144.121.20.86 
50.79.175.162

## Error messages (on screen or in browser console)
![image](https://user-images.githubusercontent.com/82594881/205169966-2037c0c6-271d-4b90-aa18-3a85d7452029.png)

# Task List
- [x] This is **NOT** a security issue
- [x] I do **NOT** have a Docker subscription
- [x] I have looked through other issues and they do **NOT** apply to me

**Comment by binman-docker** [comment]
The only filtering we do on download.docker.com is for countries that we are legally required to block per US sanctions / export controls. However, even if that was the case in your situation, the TCP connection would still succeed and you would receive an http error response (probably 403). 

The fact that you can't connect at all, including ping, indicates there is a networking problem somewhere between your machine and Cloudfront.

**Comment by amajauskas** [comment]
Hello, please see below:

-----------------------------------------------------------

user@blocked-host-1:\~$ telnet download.docker.com 443
Trying 13.249.190.100...
^C
user@blocked-host-1:\~$ telnet download.docker.com 80
Trying 13.249.190.100...
^C
user@blocked-host-1:~$


-----------------------------------------------------------


user@allowed-host-1:\~$ telnet download.docker.com 443
Trying 13.225.63.62...
Connected to d2h67oheeuigaw.cloudfront.net.
Escape character is '^]'.
^C^CConnection closed by foreign host.
user@allowed-host-1:\~$ telnet download.docker.com 80
Trying 13.225.63.62...
Connected to d2h67oheeuigaw.cloudfront.net.
Escape character is '^]'.
^CConnection closed by foreign host.
user@allowed-host-1:~$


-----------------------------------------------------------

Are you able to see any inbound traffic for the 144.121.20.86 IP? We see traffic going out, but nothing coming back.

**Comment by ingshtrom** [comment]
Hi @amajauskas 👋 

ICMP packets sent to `hub.docker.com` will not respond. It has always behaved in this fashion.

Have you attempted a traceroute to `download.docker.com` to see where the packet loss is happening?

`download.docker.com` is served by Cloudfront. Are you able to access other Cloudfront-served endpoints from this location?

**Comment by amajauskas** [comment]
Hi team,

We have put a configuration in place that only changes one thing, which allows our host that cannot reach this website, go through our secondary ISP.

And it worked as expected. This basically proves that 144.121.20.86 is being blocked by Cloudfront/download.docker.com.

![image](https://user-images.githubusercontent.com/82594881/206562337-9cb13af1-15cb-41d9-a0cd-4213f9dd5f26.png)
Top attempt is while the connection goes through primary ISP, bottom attempt is while the connection goes through our secondary ISP.

Can you please look into it more, or add a explicit whitelist?

**Comment by ingshtrom** [comment]
I appreciate the test, but your conclusion that we are blocking this IP is inaccurate. Please [refer back to Brett's original comment on this](https://github.com/docker/hub-feedback/issues/2293#issuecomment-1334573592).

I advise you to use a tool like traceroute to see where the TCP packets are being dropped. We cannot control the paths that network traffic takes on the public Internet.

Unfortunately, we also cannot add explicitly allowlist entries for customers.
