### ISSUE TITLE
I need to create bot in gupshup

### ISSUE THREAD

**Issue by Rajasathyavan** [docker/hub-feedback#2295]
In the Gupshup application, this is the page for creating the bot to get the callback URL to get what's app message conversation. In the bellow screenshot, I have entered the correct URL and password but it shows me wrong please guide me.
![Snip - Gupshup My Bots - Google Chrome (3)](https://user-images.githubusercontent.com/119675716/205639663-b9731987-d770-4e4c-979d-cb194fb94c92.png)

**Comment by ingshtrom** [comment]
Primarily, please do not put your passwords in third-party systems like this. We always [recommend 2FA](https://docs.docker.com/docker-hub/2fa/) for Docker Hub accounts. When accessing an account in an automated way, please use a [Personal Access Token (PAT)](https://docs.docker.com/docker-hub/access-tokens/).

I would contact the Gupshup team as we do not have any official integrations with them. Without knowing what API call is being made, it is hard to know what is being done incorrectly.

**Comment by Rajasathyavan** [comment]
ok sir
