### ISSUE TITLE
Explain me this please! Document in Gupshup!

### ISSUE THREAD

**Issue by Rajasathyavan** [docker/hub-feedback#2297]
I Just mailed Gupshup dev support for how to get third-party API to get whats app conversation. they emailed me this 
![Snip - successfully set the callback URL - sathya@erssmail com - ELROI Software Solution Mail - Google Chrome](https://user-images.githubusercontent.com/119675716/205847440-75e6ec56-64f0-4534-877f-c9dd27ed1ee4.png)
Then I select the link that they send to me but in this paragraph, I  can't understand any, please convey to me clearly.
![Snip - What is a Webhook - Google Chrome](https://user-images.githubusercontent.com/119675716/205847822-7943ab48-cf01-4e1e-8fa1-1a83500284a2.png)

**Comment by ingshtrom** [comment]
@Rajasathyavan Please keep the issues reported in the hub-feedback repository about Docker or any of its products. 

As for the immediate question you posed; I think continuing the conversation with their support would be more beneficial as they have more context into the problem and how to use the Gupshup APIs. 

I am going to close out this issue again as it is unrelated to Docker or any of the services we provide.
