### ISSUE TITLE
Automated builds not working

### ISSUE THREAD

**Issue by aaronnuu** [docker/hub-feedback#2301]
## Problem description

My dockerhub automated builds are currently not working. For all of my repositories the "Recent builds" section has an infinite loading spinner and when going to the "Builds" tab none of my builds are showing.

## Debug Information
**Browser name and version**: Chrome 108

**URL**: https://hub.docker.com/repository/docker/aaronnuu/[repository]

**Hub Username**: aaronnuu

## Screenshots of the issue (if applicable)

![image](https://user-images.githubusercontent.com/8295812/211142222-48f1e315-125c-4cba-8050-b286f0c8a782.png)

# Task List
- [x] This is **NOT** a security issue
- [ ] I do **NOT** have a Docker subscription
- [x] I have looked through other issues and they do **NOT** apply to me

**Comment by rimelek** [comment]
I can confirm it. I checked the developer console's network tab in Google Chrome and I can see HTTP 503 error codes.

I have also lost all my build settings in my repository (rimelek/php) although I am not sure if it happened now or it is an independent issue.

People are also reporting issues on the Docker Forum related to the automated build. This is how I found this issue.

https://forums.docker.com/t/unable-to-trigger-docker-build-via-rest-api-or-web-ui/133927

Again, I am not sure if it is related, but it could be.

**Comment by aaronnuu** [comment]
I just checked and I am also getting 503's on the `/builds` endpoint.

**Comment by EdgarJan** [comment]
Same issue, first noticed it 10 hours ago

**Comment by thaJeztah** [comment]
Thanks for reporting; I'm not on the Docker Hub team, but I pinged the team on our Slack; they're looking into it.

**Comment by speaklanguages** [comment]
I am also having problems with automated builds. All the automated builds I had configured have disappeared (although it still shows that Github is "Connected") and I can no longer see the build history for each repository. The "Recent builds" section on the repository homepage just shows an endless spinner. The relevant section of the "service status" page should be updated to show that there are issues as it currently says Automated builds are "Operational".

**Comment by carltonsmith** [comment]
Looks like everyone is having this problem, but I haven't seen any official word from GitHub or Docker. Would be great to get some kind of idea if we should be finding another build solution.

**Comment by aaronnuu** [comment]
Builds are back working for me - happy to close this issue if it's fixed for everyone

**Comment by rimelek** [comment]
@aaronnuu Yes, it is fixed for me too. I also have my build settings again.

**Comment by thaJeztah** [comment]
Just checked internally, and saw that the team deployed a fix. I think they're still validating the fix, but should probably be fixed now

**Comment by speaklanguages** [comment]
It's working again for me.
