### ISSUE TITLE
Cannot create docker hub repository

### ISSUE THREAD

**Issue by hxu10** [docker/hub-feedback#2303]
I am a newly registered account, have not created any docker hub repository yet.
But I am not able to create any docker hub repository, even if I have one private repository remaining. 
Here is the screen shot.

<img width="782" alt="Screen Shot 2023-01-19 at 7 25 43 PM" src="https://user-images.githubusercontent.com/26615314/213591619-2dfef42b-8d75-4c5e-80b5-1d132e3f8eaa.png">

**Comment by shawnaxsom** [comment]
Hey there 👋🏼 

It looks like you just need to type in a name in the "Name" field.
The "Create" button will be greyed out until you give the repository a name.

I'll close the issue – feel free to reopen this if that doesn't resolve the problem.
