### ISSUE TITLE
Public image not showing up in search for 3 days

### ISSUE THREAD

**Issue by sungamma** [docker/hub-feedback#2309]
https://hub.docker.com/r/sungamma/nas-tools

I made it private 3 days ago， and 1 hour later made it public again。 Since then，it cannot be searched again

**Comment by milosgajdos** [comment]
We do not reindex repositories when their visibility (privacy) changes in real-time. This is only done as part of the full reindex once a week. The repo will become searchable, if it stays public, next week. If you would like this to be done differently please raise this in https://github.com/docker/roadmap

**Comment by sungamma** [comment]
Thank you!
