### ISSUE TITLE
rate limit headers not visible with paid accounts

### ISSUE THREAD

**Issue by xonvanetta** [docker/hub-feedback#2311]
## Problem description

Rate limit is not returned when querying docker.io registry using the documented steps on https://docs.docker.com/docker-hub/download-rate-limit/.  It works with an anon creds which returns the correct rate limit headers but using a paid account returns no header at all even using different repos. I did read the part about `I don’t see any RateLimit headers` in that page but no rate limit headers at all in every repo i tried?

I get a header but i don't know how to use it or even if i should be able to use it `docker-ratelimit-source`. Rate limit header works with free users and anon usage but not with paid accounts. Example a curl response

```
$ curl --head -H "Authorization: Bearer $TOKEN" https://registry-1.docker.io/v2/ratelimitpreview/test/manifests/latest  
HTTP/1.1 200 OK
content-length: 2782
content-type: application/vnd.docker.distribution.manifest.v1+prettyjws
docker-content-digest: sha256:767a3815c34823b355bed31760d5fa3daca0aec2ce15b217c9cd83229e0e2020
docker-distribution-api-version: registry/2.0
etag: "sha256:767a3815c34823b355bed31760d5fa3daca0aec2ce15b217c9cd83229e0e2020"
date: Thu, 09 Mar 2023 14:20:31 GMT
strict-transport-security: max-age=31536000
docker-ratelimit-source: <uuid>
```

## Debug Information
**Browser name and version**:
`User-Agent: curl/7.88.1` 

**URL**:
`curl --head -H "Authorization: Bearer $TOKEN" https://registry-1.docker.io/v2/ratelimitpreview/test/manifests/latest`

# Task List
- [X] This is **NOT** a security issue
- [ ] I do **NOT** have a Docker subscription
- [X] I have looked through other issues and they do **NOT** apply to me

**Comment by ingshtrom** [comment]
Right, there are no headers if you have a paid plan with Docker because you are no longer rate limited for pull requests. If you are not being rate-limited, what would you expect to see?

**Comment by jonaz** [comment]
@ingshtrom so this from the pricing page is wrong? 
![2023-03-10-080202_1388x219_scrot](https://user-images.githubusercontent.com/1146389/224246447-0d8643d3-74a3-4aea-b8d6-2fe76245093e.png)

**Comment by ingshtrom** [comment]
Ah, right. I apologize, I forgot about the 5000 pull limit. It is not something that will affect most customers, but if it does apply, an account representative will reach out to you with specific data. You will not be automatically blocked for hitting that number.

**Comment by xonvanetta** [comment]
So i guess then we don't see the rate limit as it don't really apply on paid accounts until we get contacted by an account representative with some internal data about pulls. Then I find the docs a bit misleading and it should contain something about this case with paid accounts not being able to see the rate limit.

**Comment by ingshtrom** [comment]
Docs https://github.com/docker/docs/pull/16887 help clear it up at all?
