### ISSUE TITLE
hub.docker.com signup page reCAPTCHA not working

### ISSUE THREAD

**Issue by bpva** [docker/hub-feedback#2312]
## Problem description
When I`m trying to sign-up I see error message on reCAPTCHA, which makes registration impossible:
> ERROR for site owner: Invalid site key

## Debug Information
**Browser name and version**: Firefox 110 on Ubuntu Linux

**URL**: https://hub.docker.com/signup

**Timetamp or time range**:  1678502373

**Public IP**: 165.22.68.39

## Error messages (on screen or in browser console)
on reCAPTCHA iframe
>ERROR for site owner: Invalid site key

# Task List
- [x] This is **NOT** a security issue
- [x] I do **NOT** have a Docker subscription
- [x] I have looked through other issues and they do **NOT** apply to me

**Comment by binman-docker** [comment]
Apologies for that - there was a brief issue that has since been resolved. For reference: https://status.docker.com/pages/history/533c6539221ae15e3f000031

**Comment by Vick-Chow** [comment]
I can't open the https://hub.docker.com
IP: 112.47.172.200
