### ISSUE TITLE
Leaving old images up and unmaintained after sunset of Free Teams will lead to security mess

### ISSUE THREAD

**Issue by boutell** [docker/hub-feedback#2315]
Having read the new update here:

https://www.docker.com/blog/we-apologize-we-did-a-terrible-job-announcing-the-end-of-docker-free-teams/

I appreciate the commitment to not allowing squatting on old names.

However my concern is that this post promises images will be left in place, without addressing that this will quickly become a security hole as abandoned images from frozen accounts become unmaintained. Even if they lack security bugs of their own, bugs in their dependencies will be found, and things will go downhill from there.

How will this risk be communicated to those installing such packages?

**Comment by yavorg** [comment]
As [announced](https://www.docker.com/blog/no-longer-sunsetting-the-free-team-plan/), Docker is no longer sunsetting the Free Team plan, so maintainers will be able to continue updating their images. I'm closing the issue, but please reopen if you have further concerns.
