### ISSUE TITLE
400 Bad Request when using buildkit export-cache

### ISSUE THREAD

**Issue by com6056** [docker/hub-feedback#2322]
We're getting a `unexpected status: 400 Bad Request` back from Docker Hub when trying to use https://github.com/moby/buildkit and `--export-cache`.

```
buildctl build \
    --frontend dockerfile.v0 \
    --local context="." \
    --local dockerfile="." \
    --output "type=image,name=foo/bar:baz,push=true" \
    --export-cache type=registry,ref=foo/bar:buildkit-cache \
    --import-cache "type=registry,ref=foo/bar:buildkit-cache" \
    --opt label:"buildkite=true" \
    --opt label:"git-branch=foo" \
    --progress=plain \
    --opt filename=foo/bar/Dockerfile
```

Results eventually in:
```
#21 ERROR: error writing manifest blob: failed commit on ref "sha256:4ffd161309ae280fd4b5b33fb7d73f84be821886b370dae3d3fb1031012fef31": unexpected status: 400 Bad Request
```

Saw this in logs as well if it helps:
```
time="2023-04-17T17:52:47Z" level=warning msg="reference for unknown type: application/vnd.buildkit.cacheconfig.v0"
time="2023-04-17T17:52:48Z" level=error msg="/moby.buildkit.v1.Control/Solve returned error: rpc error: code = Unknown desc = error writing manifest blob: failed commit on ref \"sha256:46b779af3684778e9e686c8ce658cb374b4b25934c7f7655a29696aa5a4efa0f\": unexpected status: 400 Bad Request\n"
time="2023-04-17T17:52:48Z" level=info msg="stopping server"
buildkitd: context canceled
```

**Comment by milosgajdos** [comment]
@com6056 thanks for reporting. We are currently looking into this.

**Comment by milosgajdos** [comment]
@com6056 we've just rolled out a fix. Would you be able to verify if things work on your end?

**Comment by com6056** [comment]
Looks like we're back in business, thanks for the quick fix! 🎉

**Comment by vinnysenthil** [comment]
@milosgajdos - thanks for the quick response and @com6056 for the report. We were experiencing the same issue earlier and can also confirm things are working again on our end.

**Comment by milosgajdos** [comment]
Hi @staffanf, apologies for the inconvenience we've caused you and other people. We take this seriously but bugs inevitably crawl in 😞 

As for the status we maintain https://status.docker.com/. As soon as we verified the problem was on our side we updated the incident. You can see the record of it at https://status.docker.com/pages/history/533c6539221ae15e3f000031.

**Comment by milosgajdos** [comment]
Thanks for the feedback @staffanf. I'll take it to the team and we'll see how we can improve this for the users going forward.

**Comment by milosgajdos** [comment]
Yes, I agree with you. We will work on making this better.

**Comment by milosgajdos** [comment]
@com6056 would you mind closing this issue now?
