### ISSUE TITLE
remove card

### ISSUE THREAD

**Issue by juansbeck** [docker/hub-feedback#2323]
I have been trying to delete my credit card for several days now, the problem is that I have a personal account that owns an organization account. By mistake I put the card in the personal account. When I should have left it alone in the organization. I've been like this for months. I sent a ticket but they don't respond in help.. please help

**Comment by ob1dev** [comment]
Hi @juansbeck, I can help you with that. 

- What's your personal account name? 
- Do you have a support ticket number?
