### ISSUE TITLE
new docker image tags not appearing 

### ISSUE THREAD

**Issue by philippem** [docker/hub-feedback#2327]
After pushing a new tag to docker hub, we are able to pull the image by its tag, but the tag is not appearing in the manifest at  https://hub.docker.com/v2/repositories/blockstream/esplora/tags/ nor in the public web at 
https://hub.docker.com/r/blockstream/esplora/tags

pulling latest:

```
% docker pull blockstream/esplora:latest                                                  
latest: Pulling from blockstream/esplora
Digest: sha256:9f8d7fbacd12086a0550d3e9b26e96196e871e64a89bf89bdcd77382de126f54
Status: Image is up to date for blockstream/esplora:latest
docker.io/blockstream/esplora:latest
```

pulling tag:
```
% docker pull blockstream/esplora:814bc41fa0c5c421a061fd89d406fc0a3fb9f7cf
814bc41fa0c5c421a061fd89d406fc0a3fb9f7cf: Pulling from blockstream/esplora
Digest: sha256:9f8d7fbacd12086a0550d3e9b26e96196e871e64a89bf89bdcd77382de126f54
Status: Image is up to date for blockstream/esplora:814bc41fa0c5c421a061fd89d406fc0a3fb9f7cf
docker.io/blockstream/esplora:814bc41fa0c5c421a061fd89d406fc0a3fb9f7cf
```

absent from manifest:

```
% curl -s https://hub.docker.com/v2/repositories/blockstream/esplora/tags/ | jq | grep 814

```

## `docker info` output

Docker Info:
```yaml

```

## Debug Information
**Browser name and version**:

**URL**:

**Timetamp or time range**: 

**Public IP**: 

**Hub Username**:

## Screenshots of the issue (if applicable)

# Task List
- [ ] This is **NOT** a security issue
- [ ] I do **NOT** have a Docker subscription
- [ ] I have looked through other issues and they do **NOT** apply to me

**Comment by jcarter3** [comment]
Thanks for reporting this! This is resolved now (we'll get the status page updated accordingly)

No images or tags were lost and they were always accessible from the CLI. We experienced a delay in replication getting the data to where it's served by the UI.

**Comment by philippem** [comment]
Thank you!
visible now

```
% curl -s https://hub.docker.com/v2/repositories/blockstream/esplora/tags/ | jq | grep 814
      "name": "814bc41fa0c5c421a061fd89d406fc0a3fb9f7cf",
```
