### ISSUE TITLE
New docker images are not showing in repository

### ISSUE THREAD

**Issue by Arghajit47** [docker/hub-feedback#2328]
![Screenshot from 2023-06-03 02-41-56](https://github.com/docker/hub-feedback/assets/101691771/b719f0ab-0af2-4f33-ab94-5ffcec668af3)
![Screenshot from 2023-06-03 02-42-32](https://github.com/docker/hub-feedback/assets/101691771/a448d979-605f-4ebd-bfae-c52c8e48db18)

## `docker info` output

Docker Info:
```yaml

```

## Debug Information
**Browser name and version**:

**URL**:

**Timetamp or time range**: 

**Public IP**: 

**Hub Username**:

## Screenshots of the issue (if applicable)

# Task List
- [ ] This is **NOT** a security issue
- [ ] I do **NOT** have a Docker subscription
- [ ] I have looked through other issues and they do **NOT** apply to me

**Comment by jcarter3** [comment]
This should now be resolved.

No data was lost - all images & tags were stored correctly & accessible via the CLI, but we experienced a replication delay in getting this data to where it's queried for the UI
