### ISSUE TITLE
"Layer details are not available for this image"

### ISSUE THREAD

**Issue by sudo-bmitch** [docker/hub-feedback#2329]
## Problem description

Image cannot be viewed on Hub.

## `docker info` output

Docker Info: n/a

## Debug Information
**Browser name and version**: Firefox

**URL**: https://hub.docker.com/layers/curlimages/curl/latest/images/sha256-9d679ae7718688259258a3ea3862963023f32eae630052fde63aae5e9919a90d?context=explore

**Timetamp or time range**:  2023-06-07

**Public IP**: multiple users encountered this

**Hub Username**: not logged in

## Error messages (on screen or in browser console)

n/a

## Screenshots of the issue (if applicable)

![Screenshot from 2023-06-07 16-21-16](https://github.com/docker/hub-feedback/assets/1979858/272815ff-5508-436d-a712-896f2de14412)

The manifest for this image contains the following:

```
{
  "schemaVersion": 2,
  "manifests": [
    {
      "mediaType": "application/vnd.oci.image.manifest.v1+json",
      "digest": "sha256:d50e9aca7725d72e48abdbbe09d022e63b26b8af7853c91d05bddabd569aa37f",
      "size": 660,
      "platform": {
        "architecture": "amd64",
        "os": "linux"
      }
    },
    {
      "mediaType": "application/vnd.oci.image.manifest.v1+json",
      "digest": "sha256:e9873010d7b30eb89236956c335bd1911c4d04106a02bb058da77018b4e7c32c",
      "size": 656,
      "platform": {
        "architecture": "arm64",
        "os": "linux"
      }
    },
    {
      "mediaType": "application/vnd.oci.image.manifest.v1+json",
      "digest": "sha256:a8194c74dc55d781e23a4949b0b6fb2d61b46ec10706c1a0b64ac0718a5619ee",
      "size": 656,
      "platform": {
        "architecture": "ppc64le",
        "os": "linux"
      }
    },
    {
      "mediaType": "application/vnd.oci.image.manifest.v1+json",
      "digest": "sha256:13e39ef4e072c0f399633e628a92edf166d73f6b1d2100f4cef1d44de046d8c1",
      "size": 656,
      "platform": {
        "architecture": "s390x",
        "os": "linux"
      }
    },
    {
      "mediaType": "application/vnd.oci.image.manifest.v1+json",
      "digest": "sha256:862e2c621cdc27bc7f2ea79d1663a9bdaf221cccff06bc86328ee6d85dff1687",
      "size": 660,
      "platform": {
        "architecture": "386",
        "os": "linux"
      }
    }
  ]
}
```

It appears that the `mediaType` value is not defined, which may be a factor. I believe the maintainer is in the process of switching their builds to buildah.

# Task List
- [X] This is **NOT** a security issue
- [ ] I do **NOT** have a Docker subscription
- [X] I have looked through other issues and they do **NOT** apply to me

**Comment by milosgajdos** [comment]
Yes, the reason for this is the manifest does not have `mediaType` in the manifest. We have this in our backlog but no timeline for addressing this or similar OCI idiosyncracies at the moment, I'm afraid.

**Comment by milosgajdos** [comment]
This should now work fine _for the new PUSHes_ i.e. we should now be handling empty media types in OCI manifest properly. Let us know if you believe the issue is still present.
