### ISSUE TITLE
"Updated 2022 years ago" 

### ISSUE THREAD

**Issue by VaradBelwalkar** [docker/hub-feedback#2331]
Some docker images on Docker hub are having an update status of "Updated 2022 years ago" on the search results page

**Comment by milosgajdos** [comment]
Would you be able to provide us with a specific example?

**Comment by VaradBelwalkar** [comment]
Like loot at my particular images, for the last one in the results page, it shows the buggy update format

![Screenshot_2023-06-12_17_32_16](https://github.com/docker/hub-feedback/assets/86964576/f629c193-c31b-4b6e-96ff-9745ce63131a)

while it does show properly when seen specifically as here:

![Screenshot_2023-06-12_17_35_47](https://github.com/docker/hub-feedback/assets/86964576/1b8109f8-bb9a-43e9-8446-3baac27e22b2)

while not at all problem with this, but seems annoying as when i tried to search some images on docker hub, i found quite a few images that have such buggy update status

**Comment by rossipedia** [comment]
@VaradBelwalkar 👋 We've identified the issue and have a fix. It might not roll out today as it's a company holiday, but it should get deployed tomorrow at the latest. Will update this issue once the fix is out. Thanks!

**Comment by VaradBelwalkar** [comment]
that's awesome!
