### ISSUE TITLE
Hub.docker.com is blocking my IP address

### ISSUE THREAD

**Issue by hluaces** [docker/hub-feedback#2335]
## Problem description

:wave: hello team

I'm experiencing what I believe is a block from `hub.docker.com` which prevents me from pulling images or reaching `https://hub.docker.com`. AFAIK, this is something has started happening in the last 2h hours. My IP is 213.60.86.192 (Spain).
## Debug Information

**Browser name and version**: any browser

**URL**: hub.docker.com

**Timestamp or time range**: 2023-08-08, all day, CEST (UTC+2), see below for finer details

**Public IP**: 213.60.86.192

**Hub Username**: N/A

## Error messages (on screen or in browser console)

Some examples of the problem:

```shell
$ date +%FT%TZ%z && docker run -it --rm centos:7 
2023-08-08T12:38:29Z+0200
Unable to find image 'centos:7' locally
docker: Error response from daemon: Get "https://registry-1.docker.io/v2/": net/http: TLS handshake timeout.
See 'docker run --help'.

$ date +%FT%TZ%z && docker-compose up
2023-08-08T12:39:06Z+0200
Pulling postgres (postgres:15)...
ERROR: Get "https://registry-1.docker.io/v2/": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

# HTTP requests freeze here. I've tried all LBs I've found (see below)
$ date +%FT%TZ%z && curl -v https://hub.docker.com
2023-08-08T12:39:56Z+0200
*   Trying 18.206.20.10:443...
* TCP_NODELAY set

$ date +%FT%TZ%z && dig +short hub.docker.com
2023-08-08T12:40:42Z+0200
elb-default.us-east-1.aws.dckr.io.
prodextdefblue-1cc5ls33lft-b42d79a68e9f190c.elb.us-east-1.amazonaws.com.
18.206.20.10
3.228.146.75
18.210.197.188

# Tracepath fails at an amazon-owned IP
$ date +%FT%TZ%z && tracepath 18.210.197.188
2023-08-08T12:38:50Z+0200
 1?: [LOCALHOST]                      pmtu 1500
 1:  _gateway                                              4.451ms 
 1:  _gateway                                              1.176ms 
 2:  10.5.0.1                                              9.555ms 
 3:  no reply
 4:  no reply
 5:  no reply
 6:  ix-be-7-700.ecore1.dvs-bilbao.as6453.net             22.083ms asymm  5 
 7:  if-ae-20-2.tcore2.sv8-highbridge.as6453.net         126.149ms asymm 11 
 8:  no reply
 9:  if-ae-15-2.tcore3.njy-newark.as6453.net             110.268ms asymm 11 
10:  if-ae-1-3.tcore4.njy-newark.as6453.net              160.443ms 
11:  if-ae-34-14.tcore3.nto-newyork.as6453.net           183.638ms asymm  9 
12:  if-be-2-2.ecore1.n75-newyork.as6453.net             169.080ms asymm  7 
13:  15.230.148.40                                       108.698ms asymm 11 
14:  no reply
15:  52.93.4.54                                          166.041ms asymm 11 
16:  no reply
17:  no reply
18:  no reply
19:  no reply
20:  no reply
21:  no reply
22:  no reply
23:  no reply
24:  no reply
25:  no reply
26:  no reply
27:  no reply
28:  no reply
29:  no reply
30:  no reply
     Too many hops: pmtu 1500
     Resume: pmtu 1500 

```

## Screenshots of the issue (if applicable)

Github is not uploading images now for some reason.

All browsers return `ERR_TIMED_OUT` when trying to reach `hub.docker.com`.

# Task List

- [x] This is **NOT** a security issue
- [x] I do **NOT** have a Docker subscription
- [x] I have looked through other issues and they do **NOT** apply to me

**Comment by hluaces** [comment]
This was solved at 2023-08-08T13:12:48Z+0200

If any of you had anything to do with this <3 <3

**Comment by binman-docker** [comment]
Hi @hluaces - when we do rate limit or block, we return responses (like 429s). If you're not getting a response, like handshake timeouts, it's a problem with your system or the internet between you and us. (or it could be a problem with us, but you wouldn't be the only one experiencing it).

Glad it's working now though :)
