### ISSUE TITLE
Error with docker builds

### ISSUE THREAD

**Issue by klkvr** [docker/hub-feedback#2340]
It seems that Ipv6 upgrade caused some issues with docker builds. Following errors are started dropping on pipelines that earlier were executing successfully

```
#3 [internal] load metadata for docker.io/library/python:3.10-buster
#3 ERROR: failed to authorize: failed to fetch anonymous token: Get "https://auth.ipv6.docker.com/token?scope=repository%3Alibrary%2Fpython%3Apull&service=registry.docker.io": dial tcp [2600:1f18:2148:bc00:e947:5a7f:a49f:9126]:443: connect: cannot assign requested address
```

**Comment by ingshtrom** [comment]
Thank you for your comment. We are aware of the issue and are investigating. Can you confirm you are using Docker in Docker? We are under the impression this only happens for Docker in Docker setups on dual-stack networks where IPv6 is not enabled in the daemon configuration settings.

You can get further updates on our [status page](https://www.dockerstatus.com/pages/incident/533c6539221ae15e3f000031/64e75cde1670c8052e6ffd6d).

**Comment by klkvr** [comment]
Yes, I am using Docker in Docker

**Comment by ingshtrom** [comment]
Thank you for your patience while we worked on this fix. We've just finished rolling out the solution to use a dual-stack authentication endpoint, as the ipv6 only auth endpoint was setup for the beta release.

Did this solve the issue for you?

**Comment by klkvr** [comment]
Yes, the issue is not solved for me, thanks!
