### ISSUE TITLE
API calls to repo /tags endpoint not recognizing page_size parameter

### ISSUE THREAD

**Issue by tcs-cclaflin** [docker/hub-feedback#2343]
Curl requests to our private repo tags endpoint isn't recognizing the page_size=1 parameter we use to determine the last pushed image, instead the json is returning 25 image tags. Appears to have started in the past day or so.  

```
curl -sL -X GET -H "Authorization: JWT ${DOCKERHUB_TOKEN}" "https://hub.docker.com/v2/namespaces/<SANITIZED>/repositories/${REPO_NAME}/tags?page_size=1"
```

# Task List
- [x] This is **NOT** a security issue
- [ ] I do **NOT** have a Docker subscription
- [x] I have looked through other issues and they do **NOT** apply to me

**Comment by milosgajdos** [comment]
Hi @tcs-cclaflin, thanks for reporting. We've now identified the issue and will work on the fix next week.

**Comment by milosgajdos** [comment]
@tcs-cclaflin this should now be fixed. Can you please verify this on your end and close the issue. Thanks

**Comment by tcs-cclaflin** [comment]
confirmed back to working normally, thank you.
