### ISSUE TITLE
Help,register docker hub with wrong email

### ISSUE THREAD

**Issue by guhill1** [docker/hub-feedback#2345]
Dear docker project team members:

I’m a newbie here, I just registered docker hub with the wrong email guhill1@msn.com [1],
and then I realized it was wrong, I changed its email to the right email guhill1@outlook.com [2], but it is needed to verify the wrong email [1], and I can’t verify it.

Then I logged in with the account [2], and I found it could be logged in, but the email is still the wrong email [1], and I can not use it.

The problem is, no matter whether I log in to account [1] or account [2], the email is the wrong email [1], and it is not the right email [2].
would you please modify my account on docker hub to the right email [2] so that I can use it?
Thanks!

**Comment by gurleensethi-docker** [comment]
@guhill1 Thank you for reporting the issue, we have put in a fix, can you please try changing the email again.

**Comment by guhill1** [comment]
> @guhill1 Thank you for reporting the issue, we have put in a fix, can you please try changing the email again.

Thank you for your reply and the team's fix for the issue, now the verify email is sent to the new email address so I can log in, thanks a lot for the help!

**Comment by milosgajdos** [comment]
Closing, feel free to reopen @guhill1
