### ISSUE TITLE
Searching for `docker` by best match does not sort the best match first

### ISSUE THREAD

**Issue by corhere** [docker/hub-feedback#2352]
## Problem description

Docker Hub search thinks that the best matches for `docker` are:
1. alpine
2. nginx
3. busybox
4. ubuntu
5. python

The search result I wanted, [the `docker` official image, a.k.a. DinD](https://hub.docker.com/_/docker), was the fifteenth search result. I would have expected it to be the first, the least of which because the search query is an exact match for the repo name.

## Screenshots of the issue (if applicable)

<details><summary>Screenshot</summary>
<p>

![Docker is fifteenth in the list](https://github.com/docker/hub-feedback/assets/274527/b855cb0c-99a4-4162-9ff1-25ad3552ec3e)

</p>
</details> 

# Task List
- [X] This is **NOT** a security issue
- [X] I do **NOT** have a Docker subscription
- [X] I have looked through other issues and they do **NOT** apply to me

**Comment by thaJeztah** [comment]
Looks like it's gotten worse; auto-complete results doesn't include the image at all;

<img width="587" alt="Screenshot 2024-04-17 at 10 04 37" src="https://github.com/docker/hub-feedback/assets/1804568/9d0b6279-910f-4ba5-b0a6-81a6a6a8cbc9">


And search results now moved docker to the second page; as 27th result;

<img width="996" alt="Screenshot 2024-04-17 at 10 07 16" src="https://github.com/docker/hub-feedback/assets/1804568/fca6568c-2a0c-49b3-8fd4-ab620f1dd7c3">

I wondered if it was ranking by number of recent pulls, but hello-world, which is ranked 4th has 2.3 million pulls in the last week, which is a lot less;

<img width="976" alt="Screenshot 2024-04-17 at 10 10 56" src="https://github.com/docker/hub-feedback/assets/1804568/51025d1a-acfc-4ae4-a041-69115000e0bc">

**Comment by thaJeztah** [comment]
Oh, wait; results are randomised?? I spotted `debian` to be on page 4, but recalled it was initially shown on page 1, but it looks like reloading the page is randomising the order of results

<img width="1018" alt="Screenshot 2024-04-17 at 10 19 30" src="https://github.com/docker/hub-feedback/assets/1804568/984eaa43-46e7-47c5-a221-30c5eca0cd20">
<img width="969" alt="Screenshot 2024-04-17 at 10 19 48" src="https://github.com/docker/hub-feedback/assets/1804568/62839744-870b-40f2-b209-5059d5bb7fa9">


[search-51-75.pdf](https://github.com/docker/hub-feedback/files/15008139/search-51-75.pdf)
[search-1-25.pdf](https://github.com/docker/hub-feedback/files/15008140/search-1-25.pdf)
[search-1-25-reload.pdf](https://github.com/docker/hub-feedback/files/15008141/search-1-25-reload.pdf)

**Comment by benja-M-1** [comment]
We released a fix last week for this. It should be fixed now si I'll go ahead and close the issue. Feel free to reopen if it still does not work for you. 🙏
