### ISSUE TITLE
Please Remove IP from Blacklist

### ISSUE THREAD

**Issue by aco-jbruhns** [docker/hub-feedback#2356]
Hi,

I think my our 95.130.252.204 is blacklisted.

i'm not sure, if it was blacklisted for exessive pulls, but our dev cluster is currently unable to build images.
if that is the problem, we've already added proxy to reduce traffic.

Can you please remove the ip from the blacklist?

Kind regards,

**Comment by ryanhristovski** [comment]
Hi @aco-jbruhns 

Thanks for the report, we see that your traffic has been significantly reduced since block listing and we've removed you from said list. 

Thank you for your patience!

**Comment by ryanhristovski** [comment]
IP removed from block list

**Comment by aco-jbruhns** [comment]
thank you for the quick reponse and the unblock!
