### ISSUE TITLE
GetNamespacesRepositoriesImages endpoint suddenly throws a 404

### ISSUE THREAD

**Issue by Fkscorpion** [docker/hub-feedback#2362]
## Problem description

Hey there all you fine Docker people,

we have an automated script that sends a GET with a Bearer Token as Authoriziation to this url:

`https://hub.docker.com/v2/namespaces/{namespace}/repositories/{repositoryName}/images?ordering=-last_activity&currently_tagged=true`

On monday (december 11th) this still worked fine but since yesterday (december 12th) we are getting: “message”: “404: Page Not Found” as response.

However, if we do the same GET to:

`https://hub.docker.com/v2/namespaces/{namespace}/repositories/{repositoryName}/`

All still works fine, so we don't think it's any authorization issue.

After [posting this into the docker forums](https://forums.docker.com/t/suddenly-getting-a-404-from-dockerhub-api-when-trying-to-access-repository-images/138899), user "rimelek" found out, that the endpoint is mentioned here:

https://docs.docker.com/docker-hub/api/deprecated/

But when clicking on the v2 version, there is no link anchor and no API doc anymore, the endpoint "vanished".

## Debug Information
**URL**: /v2/namespaces/{namespace}/repositories/{repository}/images

**Hub Username**: fkscorpion

## Error messages (on screen or in browser console)
“404: Page Not Found”

# Task List
- [x] This is **NOT** a security issue
- [ ] I do **NOT** have a Docker subscription
- [x] I have looked through other issues and they do **NOT** apply to me

**Comment by stepheUp** [comment]
Hello, the Advanced Image Management and related APIs have been retired on 2023/12/11. 
See : https://docs.docker.com/docker-hub/release-notes/#2023-12-11
