### ISSUE TITLE
hub.docker.com no indexed on google?

### ISSUE THREAD

**Issue by SiestaCat** [docker/hub-feedback#2363]
When I search for example "mysql server docker" in Google, results from hub.docker.com disappeared

![image](https://github.com/docker/hub-feedback/assets/53893905/a4830dcc-4720-4a83-8064-d06d13affde5)

**Comment by rossipedia** [comment]
Thanks for the report! Yeah, we've noticed some issues with our Google indexing, and we're taking steps to address them. Unfortunately due to how Google crawls things, it takes a while for any fixes we make to propagate out.

**Comment by wmluke** [comment]
@SiestaCat Thanks again for the report. Google is now indexing https://hub.docker.com/_/mysql, so it should be the top result for your search for `mysql server docker`.  Note: it may take longer for Google to reindex our other pages.

<img width="1340" alt="image" src="https://github.com/docker/hub-feedback/assets/1744642/28313ca2-4158-4b4e-a5e4-7d48c765f2c1">

**Comment by wmluke** [comment]
I'm closing this as resolved, but feel free to open up again if other symptoms surface.
