### ISSUE TITLE
What is the search index refresh interval?

### ISSUE THREAD

**Issue by jammsen** [docker/hub-feedback#2368]
## Problem description
Im working daily on my pub-repo and the image on Github, im commiting multiple times and uploading mutliple times a day images, but the search says this:
![image](https://github.com/docker/hub-feedback/assets/2270806/d9d2f04e-5512-4641-9410-d7f97a49fa6b)

While i actually have about 40k pulls and 27 stars and "latest" mostly hours apart.

Sources:
- https://github.com/jammsen/docker-palworld-dedicated-server/commits/master/
- https://hub.docker.com/r/jammsen/palworld-dedicated-server

2 Questions arise from this for me:

- What is the search index refresh interval?
- Will 33k or 42k listed as the next rounded down 10k amount or is it 10k and the 100k? Which would be vastly different from a jump from 10k to 20k and so on.

## Debug Information
**Browser name and version**:
Any browser search in the docker-hub search for "palworld"

**URL**:
Not sure if this classifies as the definition of an error but here your go:
https://hub.docker.com/search?q=palworld

**Timetamp or time range**: 
Since 20-21 January 2024

# Task List
- [x] This is **NOT** a security issue
- [x] I do **NOT** have a Docker subscription
- [x] I have looked through other issues and they do **NOT** apply to me

**Comment by jammsen** [comment]
Hello?

**Comment by stepheUp** [comment]
Hello jammsen, today indexing is triggered by some specific events like repository creation, repository deletion, tag deletion, privacy change, ...
So that probably explains the behavior you faced in your case.

**Comment by jammsen** [comment]
Hey @stepheUp
> * What is the search index refresh interval?
> * Will 33k or 42k listed as the next rounded down 10k amount or is it 10k and the 100k? Which would be vastly different from a jump from 10k to 20k and so on.

I asked 2 questions and im not sure if i understand your explanation of number 1. 
Regarding your answer to number 1, so what you are saying is that the index is generated when i add or delete tags? I never did that, never changed the repo to private, the repo exists and isnt deleted, so all of thoose events dont trigger this, so what would be the other criteria that could happend, for this "long-update-time"?

**Comment by jammsen** [comment]
Hello?
