### ISSUE TITLE
Public static IP blocked

### ISSUE THREAD

**Issue by pears0** [docker/hub-feedback#2370]
My static Public IP address appears to be blocked / rate limited on auth.docker.io. This means I am unable to register my docker instances for work so as to avoid any issues with download limits from the docker hub.

Public IP: 45.13.7.122

Could it be unblocked so I can at least log into docker desktop etc please?

**Comment by ingshtrom** [comment]
Thank you for reaching out. I would like to get more detail from you so I can better help you.

Can you be specific with what command you are running or how you are trying to log in?

Can you please provide the error message you are receiving or the difference between your expected and actual behavior?

Thank you!

**Comment by pears0** [comment]
I'm attempting to login to docker hub from my docker deamon:
`root@nas:~# cat dock_pass.txt | docker login --username gonzohome --password-stdin
Error response from daemon: Get "https://registry-1.docker.io/v2/": read tcp 10.42.2.200:50034->54.198.86.24:443: read: connection reset by peer`

I'd expect to be able to login or get an authentication failed error message. I also attempted to login on docker desktop on a different machine behind the same public IP. The web login works, but the desktop app instantly logs back out and asks for me to login. It appears that I'm unable to access the api / api auth from behind my public IP address

**Comment by pears0** [comment]
I've also just tested on a 3rd machine on my home network that's connected via a dial-in VPN, so appears from a seperate static public IP address, and that's connected successfully without issue on the same account details.

**Comment by pears0** [comment]
Any updates? @ingshtrom

**Comment by pears0** [comment]
I do see the issue on hub.docker.com and as mentioned, behind a VPN from the same network I connect fine. I see the issue on hub.docker.com, I have a right game logging in via a browser, and as such, the login from docker desktop appears to initally connect then signs out again immediatly.

My IP from my ISP is static and hasn't been rotated in at least 18 month, possibly the last 2 years, wondering if the whole block (it's assigned from a /24 block) has been blacklisted somewhere? Are you using Amazon for your hosting, wonder if Amazon is doing something funky, as I see a lot of packet fragmentation issues from Amazon IPs on my firewall.

**Comment by ingshtrom** [comment]
Yes, we use Amazon.

**Comment by pears0** [comment]
This is what I see on my network tab when I attempt to log in to docker-desktop via the web page:
![image](https://github.com/docker/hub-feedback/assets/1243954/0538d277-5671-42c0-8de3-cab5e1f12703)

It seems really odd that it's taking so long. This is in firefox, but I don't see this issue as much when on the VPN but still on firefox.

**Comment by pears0** [comment]
Ok, I'm pleased to report I have finally identified the issue and resolved it.

For future refrence, the issue was being caused by packet duplication by one of my switches erronously mirrior packets across VLAN's!!!!
