### ISSUE TITLE
5000 character limit on descriptions

### ISSUE THREAD

**Issue by yosifkit** [docker/hub-feedback#238]
There was not a limit on the previous hub and [some](https://github.com/docker-library/docs/blob/046ddc6f448df2168f6aefda2de9c93662e46e1e/ubuntu/README.md) of [the](https://github.com/docker-library/docs/blob/046ddc6f448df2168f6aefda2de9c93662e46e1e/redmine/README.md) Official [Images](https://github.com/docker-library/docs/blob/046ddc6f448df2168f6aefda2de9c93662e46e1e/ros/README.md) are beyond that.

Can we remove or greatly increase the limit?

As a workaround we'll probably just cut all the official image descriptions on the hub to a minimal set and link back to github.

**Comment by ChristopherBiscardi** [comment]
For easy reference, the Official Images listed come in at approx 5300, 8500 and 5300 chars respectively.

Ping @rrarunan @kencochrane I think it makes sense to bump this limit considerably

**Comment by tianon** [comment]
Some more interesting byte counts:
```console
$ wc -c */README.md | sort -n
   631 scratch/README.md
  2157 cirros/README.md
  2231 ubuntu-upstart/README.md
  2650 hipache/README.md
  2727 celery/README.md
  2774 julia/README.md
  2841 opensuse/README.md
  2958 thrift/README.md
  2979 glassfish/README.md
  3055 ubuntu-debootstrap/README.md
  3095 docker-dev/README.md
  3148 ghost/README.md
  3275 registry/README.md
  3333 hylang/README.md
  3373 rakudo-star/README.md
  3386 hello-world/README.md
  3422 logstash/README.md
  3496 mageia/README.md
  3509 memcached/README.md
  3555 perl/README.md
  3561 sonarqube/README.md
  3637 owncloud/README.md
  3663 irssi/README.md
  3695 kibana/README.md
  3720 oraclelinux/README.md
  3760 haproxy/README.md
  3823 crux/README.md
  3896 jenkins/README.md
  3910 fedora/README.md
  3947 alpine/README.md
  4187 kaazing-gateway/README.md
  4254 elasticsearch/README.md
  4307 gcc/README.md
  4382 nginx/README.md
  4493 clojure/README.md
  4511 sentry/README.md
  4535 busybox/README.md
  4719 httpd/README.md
  4862 swarm/README.md
  4865 neurodebian/README.md
  4923 r-base/README.md
  4970 jruby/README.md
  4975 tomcat/README.md
  5087 crate/README.md
  5276 percona/README.md
  5343 ros/README.md
  5357 ubuntu/README.md
  5404 mono/README.md
  5493 redis/README.md
  5543 jetty/README.md
  5579 rethinkdb/README.md
  5678 debian/README.md
  5684 odoo/README.md
  5697 maven/README.md
  5734 mariadb/README.md
  5916 rails/README.md
  5917 drupal/README.md
  5999 php-zendserver/README.md
  6057 joomla/README.md
  6092 haskell/README.md
  6283 wordpress/README.md
  6410 django/README.md
  6421 java/README.md
  6540 rabbitmq/README.md
  6619 aerospike/README.md
  7114 iojs/README.md
  7271 pypy/README.md
  7322 php/README.md
  7339 mongo/README.md
  7429 websphere-liberty/README.md
  7570 buildpack-deps/README.md
  7616 ruby/README.md
  7652 centos/README.md
  7966 postgres/README.md
  8224 arangodb/README.md
  8380 node/README.md
  8416 golang/README.md
  8602 redmine/README.md
  9631 python/README.md
 10887 mysql/README.md
 11584 gazebo/README.md
 12062 cassandra/README.md
 20088 couchbase/README.md
```

**Comment by ChristopherBiscardi** [comment]
thanks @tianon That's really helpful :smile:

**Comment by kencochrane** [comment]
So what do we want for a limit? 20k seems really high does it need to be that high? Higher, lower? Honestly I don't care what it is I just don't want to make the change 5 times.

/cc @fxdgear

**Comment by yosifkit** [comment]
My opinion would be to put it at least at 100k characters.  That is only 100-400 kB of storage and can easily be gzipped.

**Comment by tianon** [comment]
I'm definitely curious why this particular limit was chosen during the switch -- knowing why the limit was set to 5000 would be helpful for picking a new limit, I'd imagine.

**Comment by kencochrane** [comment]
@tianon I can't remember why, but I'm pretty sure everyone was involved, because this has a major case of de ja vu if not. :) 

IIRC we didn't want it too big since everything is coming across in the API responses and it would make them much bigger, and realistically how many repos need more then 5000 characters?

I personally think 100k is way too big. having to pass that around in the API would really suck. maybe 25k?

**Comment by rrarunan** [comment]
@tianon @kencochrane I agree with the 25K cap. Especially, after looking at the data showing only one official repo with around 20K characters. (couchbase)

**Comment by nhsiehgit** [comment]
@kencochrane @ChristopherBiscardi has this fix been deployed?

**Comment by fxdgear** [comment]
@nhsiehgit Not yet. There's a PR under review for it.

**Comment by psftw** [comment]
Confirmed the fix is deployed and allows 25,000 characters or less.  :cat2:

cc @tianon @yosifkit

**Comment by yosifkit** [comment]
Will there be an update to the page to let users know the new limit?  It still says "Limit 5000 Characters", even though the limit is 25k.

**Comment by kristiehoward** [comment]
Yes, @yosifkit we will be updating the repo description page with the new limit shortly

**Comment by tianon** [comment]
Just for posterity / future reference, updated numbers for today's official images are as follows:
```console
$ wc -c */README.md | sort -n
   1386 scratch/README.md
   2628 cirros/README.md
   3242 julia/README.md
   3428 thrift/README.md
   3515 clearlinux/README.md
   3621 registry/README.md
   3679 swipl/README.md
   3753 rakudo-star/README.md
   3910 rocket.chat/README.md
   3943 opensuse/README.md
   3971 fedora/README.md
   4020 fsharp/README.md
   4037 mageia/README.md
   4052 photon/README.md
   4068 hylang/README.md
   4133 eclipse-mosquitto/README.md
   4139 rethinkdb/README.md
   4221 piwik/README.md
   4328 znc/README.md
   4561 sourcemage/README.md
   4576 rust/README.md
   4606 known/README.md
   4649 crate/README.md
   4741 crux/README.md
   4749 hola-mundo/README.md
   4798 gcc/README.md
   4822 hello-seattle/README.md
   4954 hello-world/README.md
   4974 alpine/README.md
   5071 swarm/README.md
   5192 traefik/README.md
   5380 swift/README.md
   5416 r-base/README.md
   5614 mono/README.md
   5720 kaazing-gateway/README.md
   5726 busybox/README.md
   5752 kibana/README.md
   5842 amazonlinux/README.md
   6015 sonarqube/README.md
   6066 mongo-express/README.md
   6075 perl/README.md
   6101 plone/README.md
   6189 memcached/README.md
   6207 composer/README.md
   6211 irssi/README.md
   6282 bash/README.md
   6406 orientdb/README.md
   6529 backdrop/README.md
   6641 chronograf/README.md
   6783 haskell/README.md
   6950 adminer/README.md
   7071 spiped/README.md
   7087 eggdrop/README.md
   7110 oraclelinux/README.md
   7189 owncloud/README.md
   7192 gradle/README.md
   7462 neurodebian/README.md
   7490 storm/README.md
   7493 ubuntu/README.md
   7534 joomla/README.md
   7540 httpd/README.md
   7545 rapidoid/README.md
   7608 elixir/README.md
   7686 vault/README.md
   7796 pypy/README.md
   7814 logstash/README.md
   7996 redis/README.md
   8002 mediawiki/README.md
   8152 aerospike/README.md
   8168 notary/README.md
   8244 couchdb/README.md
   8298 lightstreamer/README.md
   8352 ghost/README.md
   8427 maven/README.md
   8610 erlang/README.md
   8620 sentry/README.md
   8725 kong/README.md
   8730 haproxy/README.md
   8735 convertigo/README.md
   8807 tomcat/README.md
   8849 buildpack-deps/README.md
   8989 centos/README.md
   9098 kapacitor/README.md
   9179 odoo/README.md
   9240 nats/README.md
   9254 clojure/README.md
   9295 jruby/README.md
   9355 telegraf/README.md
   9372 php-zendserver/README.md
   9777 zookeeper/README.md
   9863 elasticsearch/README.md
  10296 arangodb/README.md
  10547 jetty/README.md
  10726 nginx/README.md
  10816 nuxeo/README.md
  10825 geonetwork/README.md
  11090 groovy/README.md
  11135 tomee/README.md
  11432 jenkins/README.md
  11672 debian/README.md
  12062 node/README.md
  12108 haxe/README.md
  12314 golang/README.md
  12523 ruby/README.md
  12771 websphere-liberty/README.md
  12907 ibmjava/README.md
  12997 rabbitmq/README.md
  13118 drupal/README.md
  13119 wordpress/README.md
  13244 mongo/README.md
  13263 openjdk/README.md
  13312 influxdb/README.md
  13340 docker/README.md
  13414 gazebo/README.md
  13627 redmine/README.md
  14327 cassandra/README.md
  14827 flink/README.md
  15248 nats-streaming/README.md
  15842 solr/README.md
  15851 percona/README.md
  15865 mysql/README.md
  15876 xwiki/README.md
  16290 mariadb/README.md
  16832 couchbase/README.md
  17151 postgres/README.md
  17157 neo4j/README.md
  17526 silverpeas/README.md
  17947 python/README.md
  18463 php/README.md
  18872 nextcloud/README.md
  19504 bonita/README.md
  20353 ros/README.md
  21594 consul/README.md
```

(significantly more repos up near that 20k mark now)

**Comment by tianon** [comment]
Here's an updated list (with PHP now over that 25k mark):

```console
$ wc -c */README.md | sort -n | tail -n20
  15934 wordpress/README.md
  16445 percona/README.md
  16885 mariadb/README.md
  16927 mongo/README.md
  17005 mysql/README.md
  17674 couchbase/README.md
  18160 silverpeas/README.md
  18802 openjdk/README.md
  19765 nats-streaming/README.md
  19823 influxdb/README.md
  20239 ros/README.md
  20443 python/README.md
  21553 postgres/README.md
  21599 xwiki/README.md
  21842 nextcloud/README.md
  22025 bonita/README.md
  22385 consul/README.md
  24075 neo4j/README.md
  25868 php/README.md
```

**Comment by vijayant123** [comment]
PHP still shows an warning message at the top of its description field. I agree with @yosifkit that the limit should be over and above 100k characters.

**Comment by MichaelSimons** [comment]
We have started hitting this limit with the [microsoft/dotnet](https://hub.docker.com/r/microsoft/dotnet/) repo.  We are getting ready to release a preview version of the next release which puts us over the 25k limit.  With the broad number of platforms/distros/multi-arch tags etc, the 25k limit seems pretty small.

**Comment by Djelibeybi** [comment]
We seem to have hit the limit on the [official-library/openjdk](https://github.com/docker-library/openjdk/) image now as well.

**Comment by tianon** [comment]
Yep, we've got ~13 official images over the limit now:

```console
$ wc -c */README.md | sort -n | tail -n20
  17064 couchbase/README.md
  17240 percona/README.md
  17392 solr/README.md
  17523 rabbitmq/README.md
  18221 silverpeas/README.md
  18256 neo4j/README.md
  20792 nats-streaming/README.md
  20807 open-liberty/README.md
  21165 ros/README.md
  21793 influxdb/README.md
  21998 bonita/README.md
  22671 nextcloud/README.md
  22989 consul/README.md
  24085 python/README.md
  24602 mongo/README.md
  24610 openjdk/README.md
  24948 websphere-liberty/README.md
  25030 php/README.md
  25170 postgres/README.md
```

**Comment by thaJeztah** [comment]
@cowsrule ^^

**Comment by aguibert** [comment]
@tianon can we revisit this please? I think the official images could display tags in a more concise way. The many combinations of tags is the main reason why the OpenLiberty description got so long, but the scheme is just:
```
[VERSION-]PROFILE[-JAVA_DIST]

    VERSION       the version of OpenLiberty (e.g. 19.0.0.4)
    PROFILE       the profile of OpenLiberty. Possible values: 
        - kernel
        - webProfile7
        - webProfile8
        - etc...
    JAVA_DIST    the distribution of Java used with OpenLiberty. Possible values: 
        - java8-openj9
        - java8-ibmsfj
        - java11-openj9
        - etc....
```

Perhaps we could allow a little bit of customization for how/which image labels are shown in the image description?

**Comment by tianon** [comment]
The other issue is a more appropriate place to discuss the specific formatting we use; this issue is about the Hub's character limit which is only tangentially related.

**Comment by gdams** [comment]
hmm https://hub.docker.com/_/adoptopenjdk seems way over the limit. Not sure what the best approach is here?

**Comment by thaJeztah** [comment]
@cowsrule ^^

**Comment by CurosMJ** [comment]
> @tianon I can't remember why, but I'm pretty sure everyone was involved, because this has a major case of de ja vu if not. :)
> 
> IIRC we didn't want it too big since everything is coming across in the API responses and it would make them much bigger, and realistically how many repos need more then 5000 characters?
> 
> I personally think 100k is way too big. having to pass that around in the API would really suck. maybe 25k?

As for the comment that descriptions are included in API responses and having higher limits would cause bigger API responses, one solution I can think of, is to truncate the description fields by default and expose new endpoints for full descriptions.

**Comment by LukeCarrier** [comment]
Is it worth opening a new ticket for this issue? I'm not sure how likely Docker folks are to see comments in a closed ticket.

**Comment by mk-pmb** [comment]
I usually skim manuals for the relevant parts, so at first I missed the cut-off note on top. Can we please repeat that note directly below the actual cut-off? And can we give that note a box layout, at least a border?
