### ISSUE TITLE
Synching of PHP images/tags to AWS ECR appears broken again. 

### ISSUE THREAD

**Issue by ldebrouwer** [docker/hub-feedback#2382]
There seem to be renewed issues with syncing the PHP image/tag information from Docker Hub to AWS ECR Public Gallery. All the images/tags for PHP 8.3.5 and 8.3.6 seem to be missing here; https://gallery.ecr.aws/docker/library/php. Could someone please look into this?

I believe this to be related to; [Issue with PHP DOI to ECR](https://github.com/docker/hub-feedback/issues/2341)

**Comment by jcarter3** [comment]
Hey! Thanks for raising an issue - it is indeed related to the previous issue. We have hit our limit again with tags (60k) on an ECR repo and are working with the ECR team to get it raised. After that we will re-sync the data over and work on a more sustainable solution going forward.

**Comment by ldebrouwer** [comment]
Thanking you!

**Comment by jcarter3** [comment]
We got the limit raised and re-synced the images over. Let us know if there are any issues!

**Comment by ldebrouwer** [comment]
Thank you, just wanted to let you know it works a treat now.
