### ISSUE TITLE
Collective responsibility of ordinary citizens

### ISSUE THREAD

**Issue by Maligosus** [docker/hub-feedback#2387]
Is it really a person’s fault that he lives in Russia and cannot leave?

I understand if paid subscriptions were banned, there is really no way to make payments due to sanctions, but why did you decide to prohibit using the free features of the hub.

We are a private company, we do not work for the Russian government, I do not support the war in Ukraine.

**Comment by cuyk** [comment]
Your private company and you personally still pay taxes, aren't you? ¯\_(ツ)_/¯
There are ways of lifting such thing of yourself it will bring you discomfort. So you do not support the war, but not against it and willing to do nothing, I guess.

**Comment by cuyk** [comment]
Your private company and you personally still pay taxes, aren't you? ¯\_(ツ)_/¯
There are ways of lifting such thing of yourself it will bring you discomfort, so you're against, but willing to do nothing, I guess.

**Comment by cuyk** [comment]
Your private company and you personally still pay taxes, aren't you? ¯\_(ツ)_/¯
There are ways of lifting such thing of yourself. It will bring you even more discomfort for a time being, but it's possible. So you're not supporting the war, but not against it and but willing to do nothing, I guess.

**Comment by andrew-qa** [comment]
Well, collective responsibility applies if you've been held accountable for war crimes committed by your military in Ukraine. However, that's not even remotely similar to being unable to pull Docker images. So, please stop acting like a victim here.

**Comment by l13t** [comment]
> There is no need to say anything about taxes if you don’t know how it works, in your country there are a lot of foreign companies that work with us, so let’s not say anything about it, so there is no point in continuing the dialogue with you.

The usual soviet takes "What about....". Time flies, but nothing changes.

**Comment by vvershilovich** [comment]
I wonder, will the countries in Europe that pay the Russian government way more for oil and gas than all private companies combined also be blocked? Or is it 'a different story'?

**Comment by neshkeev** [comment]
This is just a sucker punch.

A reasonable company would've warned people about blocking Russian IPs beforehand.

Good luck blocking Open Source, adding mirrors to our configs took like a minute, so the impact on business is minimal, but the reputation damage is huge. The whole world saw what you did today and you're at risk of losing business in China, India and many other sovereign countries

**Comment by simonsk1990** [comment]
As always, playing the victim. Actions have consequences, you break international law, you get punished by sanctions, including technological sanctions.

**Comment by l13t** [comment]
> Good luck blocking Open Source, adding mirrors to our configs took like a minute, so the impact on business is minimal, but the reputation damage is huge. The whole world saw what you did today and you're at risk of losing business in China, India and many other sovereign countries

Nice try, but no. Today was blocked country that doesn't care about licenses and laws (starting from 2022 your country steals software, films, cartoons, etc.). And docker hub has nothing to do with open source. It's a commercial platform that provides hosting of the data, so that is their business who can have access to their platform and who doesn't.

**Comment by nothugofsea** [comment]
OMG! Politics has reached open source projects... It's so stupid move to restrict Russian developers to use docker hub... These are no longer sanctions but some kind of racism

**Comment by l13t** [comment]
> Racism is discrimination and prejudice against people based on their race or ethnicity.

Where do you see racism?

**Comment by KweezyCode** [comment]
@cuyk 
> Your private company and you personally still pay taxes, aren't you? ¯_(ツ)_/¯ There are ways of lifting such thing of yourself. It will bring you even more discomfort for a time being, but it's possible. So you're not supporting the war, but not against it and but willing to do nothing, I guess.

You are very brave being abroad, but if you were in Russia, at best you would be sitting silently with your tongue up your a*s, and at worst you would be in jail for discrediting the army (this is a real law, you can get up to 15 years in jail for violating this article in the law). Not everyone has the financial ability to leave here, just look at the number of people who have loans, it's about 40% of the population of the country, who can give up to 80% of their salary to pay off loans, it's a very sad statistic.

**Comment by vstets23** [comment]
This can quite easily be fixed; just ask your government to stop the invasion. Or you can't ?

**Comment by baznikin** [comment]
> This can quite easily be fixed; just ask your government to stop the invasion. Or you can't ?

You are silly. Russia in enormous, civil society trampled into the mud with spec-op police decades ago. All you can do there - leave country if you can (I leave, thank all the gods), wear T-shirt with letter 'Z' or shout your mouth. If you put :+1: on post on social networks against war you *can* be arrested, it is modern Russian reality. 
https://zapad24.ru/uploads/posts/2021-02/1612145185_avatarka.jpg - real photo from my home city, year before invasion. Thing becafe waaaaay harder since that old good times.

**Comment by chtuqu** [comment]
@simonsk1990
>you break international law
I believe as an Israeli you should probably refrain from this discussion.
