### ISSUE TITLE
can't docker pull images from China

### ISSUE THREAD

**Issue by Y-pandaman** [docker/hub-feedback#2388]
### Description

can't docker pull images in China, who know what happened ?

### Reproduce

failed to copy: httpReadSeeker: failed open: failed to do request: Get "https://production.cloudflare.docker.com/registry-v2/docker/registry/v2/blobs/sha256/25/25d4f4c53ee345457f55dc77f65dd6e6737f936a178709b2547e51186290202c/data?verify=1718079893-D1%2FpJc%2FKKgeeGYg42JoGk7Utj0U%3D": dial tcp 199.59.149.236:443: i/o timeout

### docker version

```bash
Client: Docker Engine - Community
 Version:           26.1.3
 API version:       1.45
 Go version:        go1.21.10
 Git commit:        b72abbb
 Built:             Thu May 16 08:33:49 2024
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          26.1.3
  API version:      1.45 (minimum version 1.24)
  Go version:       go1.21.10
  Git commit:       8e96db1
  Built:            Thu May 16 08:33:49 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.9
  GitCommit:        1c90a442489720eec95342e1789ee8a5e1b9536f
 nvidia:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client: Docker Engine - Community
 Version:    26.1.3
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.14.0
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.27.1
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 3
  Running: 2
  Paused: 0
  Stopped: 1
 Images: 6
 Server Version: 26.1.3
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: nvidia runc io.containerd.runc.v2
 Default Runtime: nvidia
 Init Binary: docker-init
 containerd version: 1c90a442489720eec95342e1789ee8a5e1b9536f
 runc version: v1.1.4-0-g5fd4c4d
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
 Kernel Version: 5.15.0-107-generic
 Operating System: Ubuntu 20.04.6 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 15.44GiB
 Name: bdca-shenzhou
 ID: efcb31ba-c29d-4ce5-8dfd-6760f6b0d06c
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http://127.0.0.1:7890
 HTTPS Proxy: http://127.0.0.1:7890
 Username: pandaman666
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Comment by binman-docker** [comment]
We've had a few reports of Hub being inaccessible in China. There appears to be something wrong with your DNS - 199.59.149.236 is not an IP owned by our CDN, but by [Twitter apparently](https://ipinfo.io/199.59.149.236). 

Every other location seems to [report IPs](https://dnschecker.org/#A/production.cloudflare.docker.com) that are currently correct for our CDN (note that these may change over time though).

I would recommend contacting your internet or DNS provider to resolve the issue.

**Comment by AvatarrX** [comment]
I am facing the same issue. Do you have any updates regarding this?

Failed to pull image "busybox": rpc error: code = Unknown desc = failed to pull and unpack image "docker.io/library/busybox:latest": failed to copy: httpReadSeeker: failed open: failed to do request: Get "https://production.cloudflare.docker.com/registry-v2/docker/registry/v2/blobs/sha256/65/65ad0d468eb1c558bf7f4e64e790f586e9eda649ee9f130cd0e835b292bbc5ac/data?verify=1718191161-HlH1AW7DOXJbfV5PhI1Puryk0L0%3D": dial tcp 93.179.102.140:443: connect: connection refused

**Comment by binman-docker** [comment]
Unfortunately there is nothing Docker can do for you if your DNS provider is not providing correct DNS records. 93.179.102.140 is not a valid IP for our CDN. 

Please consult with your DNS provider to resolve the issue, or switch your DNS nameservers to another service. Cloudflare (1.1.1.1) in particular should work nicely.

> ➜  ~ host production.cloudflare.docker.com 1.1.1.1
Using domain server:
Name: 1.1.1.1
Address: 1.1.1.1#53
Aliases:
production.cloudflare.docker.com has address 104.16.97.215
production.cloudflare.docker.com has address 104.16.98.215
production.cloudflare.docker.com has address 104.16.99.215
production.cloudflare.docker.com has address 104.16.101.215
production.cloudflare.docker.com has address 104.16.100.215
production.cloudflare.docker.com has IPv6 address 2606:4700::6810:65d7
production.cloudflare.docker.com has IPv6 address 2606:4700::6810:63d7
production.cloudflare.docker.com has IPv6 address 2606:4700::6810:62d7
production.cloudflare.docker.com has IPv6 address 2606:4700::6810:64d7
production.cloudflare.docker.com has IPv6 address 2606:4700::6810:61d7
