### ISSUE TITLE
Feedback on save actions.

### ISSUE THREAD

**Issue by appcontainers** [docker/hub-feedback#239]
1. Earlier experienced an issue where if going over the new inconvenient 5000 description limit on repo descriptions, save refuses to work and gives no feedback as to why it fails to save. 
2. On build when changing build settings save seems to hover and again gives no feedback as to if it failed or succeeded. It appears to have saved, but I will have to pull the new build back down to verify, which again is very inconvenient. 
3. On the dashboard page, the first line for each of the users listed repositories shows public | Automated build instead of the repo name. Maybe it's just me, but my eye always gravitates to the first line, and so at glance when your looking for one of your repositories all you initially notice is a list view of public | automated build.
4. Filter on your repo list isn't present, I need to go to search to search site wide to find the one container that I am looking for in my repo list. 
5. Page pagination on the bottom of the page doesn't indicate that there are multiple pages of repositories available again on the dashboard. It simply has <<X>> on each page even if no more pages exist. There should be an indicator as to if there are more pages or not. 

I am curious as to why this been switched to production when it doesn't really seem to be the production ready version of the hub. I am kind of thinking this shouldn't have been switched to production until more of these minor obvious issues were QA approved.

**Comment by nhsiehgit** [comment]
So to break it down.
- [x] 5000 limit (being addressed)
- [x] validations on forms - description & autobuild triggers (being addressed)
- [ ] repo item content
- [x] user filtering personal repo's (being addressed)
- [x] pagination (being addressed)

Thanks for the feedback, definitely very helpful. Most of these items seem to be duplicated in other tickets as well and are being addressed.
