### ISSUE TITLE
build arm image, error

### ISSUE THREAD

**Issue by Baron20200407** [docker/hub-feedback#2394]
ERROR: failed to solve: DeadlineExceeded: DeadlineExceeded: DeadlineExceeded: arm64v8/ubuntu:18.04: failed to copy: httpReadSeeker: failed open: failed to do request: Get "https://production.cloudflare.docker.com/registry-v2/docker/registry/v2/blobs/sha256/d1/d1a528908992e9b5bcff8329a22de1749007d0eeeccb93ab85dd5a822b8d46a0/data?verify=1718961463-Xg8gtYolxz8xuOFfQVwEx1fwDr8%3D": dial tcp 199.59.148.15:443: i/o timeout

How to solve?

**Comment by binman-docker** [comment]
199.59.148.15 is not an IP address owned by Docker or our CDN partners. (It [looks](https://ipinfo.io/199.59.148.15) to be owned by Twitter).

Is your system located in China? We've seen similar reports from there: https://github.com/docker/hub-feedback/issues/2388

I would suggest working with your DNS provider to resolve the issue, or switch providers.
