### ISSUE TITLE
Cannot pull arm32v7 images

### ISSUE THREAD

**Issue by setycz** [docker/hub-feedback#2395]
## Problem description
Cannot pull arm32v7 images, running `docker pull arm32v7/mono:6.12.0.182` results in:

> docker pull arm32v7/mono:6.12.0.182
> 6.12.0.182: Pulling from arm32v7/mono
> no matching manifest for linux/amd64 in the manifest list entries

## Error messages (on screen or in browser console)

> no matching manifest for linux/amd64 in the manifest list entries

# Task List
- [x] This is **NOT** a security issue
- [x] I do **NOT** have a Docker subscription
- [x] I have looked through other issues and they do **NOT** apply to me

**Comment by binman-docker** [comment]
`arm32v7/mono:6.12.0.182` is only built for the `linux/arm/v7` architecture: https://hub.docker.com/layers/arm32v7/mono/6.12.0.182/images/sha256-bb330a955d4e30fc342e6a770e76253662e2ab4eaf51dbb51f988815f6b28f29?context=explore

The error message `no matching manifest for linux/amd64` implies your system is trying to pull the image for the amd64 architecture, which is not available for that image.

**Comment by setycz** [comment]
We were using the same command for multiple years without any issue, so it looks like the platform has been removed from DockerHub. Anyway, if there is anyone else struggling, adding the platform to your Dockerfile fixes the issue:

> FROM --platform=linux/arm/v7 arm32v7/mono:6.12.0.182
