### ISSUE TITLE
Error in https://hub.docker.com/r/amd64/ros

### ISSUE THREAD

**Issue by FHefterSRH** [docker/hub-feedback#2396]
In several places on the page there is an error in
```
CMD ["ros2", "launch", "demo_nodes_cpp", "talker_listener.launch.py"]
```

Solution:

```talker_listener.launch.py```

should be

```talker_listener_launch.py```

Then the examples work.

**Comment by binman-docker** [comment]
It appears that content comes from https://github.com/docker-library/docs/blob/master/ros/README.md - please open an issue here: https://github.com/docker-library/docs/issues

(I would transfer this issue but they are in different Github organizations and that's not supported)

**Comment by FHefterSRH** [comment]
I created https://github.com/docker-library/docs/issues/2456
