### ISSUE TITLE
Something went wrong! in billing page

### ISSUE THREAD

**Issue by backtony** [docker/hub-feedback#2397]
<img width="828" alt="스크린샷 2024-07-01 오후 2 55 02" src="https://github.com/docker/hub-feedback/assets/68492475/c6d943a8-a0da-41e9-aed5-18bd14c1b63c">

I cannot access repository and billing page.

<img width="827" alt="스크린샷 2024-07-01 오후 2 56 29" src="https://github.com/docker/hub-feedback/assets/68492475/ea051b4b-880b-40ea-87d1-cf848b60cdbf">

and this is my profile page

**Comment by binman-docker** [comment]
Hi @backtony - since this seems to be related to your specific account, can you please open a support ticket? Our support team will be able to work with you to figure out what's going on. Thanks!

https://hub.docker.com/support/contact

**Comment by backtony** [comment]
The problem has been solved, so I will close the issue.
Thank you!
