### ISSUE TITLE
Unable to Delete Tags from Docker Hub Repository

### ISSUE THREAD

**Issue by ErcinDedeoglu** [docker/hub-feedback#2398]
I am experiencing an issue with deleting tags from my Docker Hub repository. When attempting to delete tags, I receive a 500 status code, and the response indicates an unauthorized deletion attempt, even though I have authenticated successfully and obtained a valid token. I have encountered the same issue both through the Docker Hub API and the Docker Hub UI. This problem is not specific to a single repository, as it occurs across multiple repositories.

**Hub Username:** dublok
**Repository Name:** base-linux
**Error Messages:** The deletion attempts fail with the following error messages:
**Failed to delete tag:** alpine-v1.0. Status code: 500
**Response content:** b'{"message":"Delete \"https://registry.s.us-east-1.aws.dckr.io/api/internal/repos/dublok/base-linux/tags/alpine-v1.0\\": http: non-successful response (status=401 body=\"{\\\"errors\\\":[{\\\"code\\\":\\\"UNAUTHORIZED\\\",\\\"message\\\":\\\"authentication required\\\",\\\"detail\\\":[{\\\"Type\\\":\\\"repository\\\",\\\"Class\\\":\\\"\\\",\\\"Name\\\":\\\"dublok/base-linux\\\",\\\"Action\\\":\\\"delete\\\"}]}]}\\n\")","errinfo":{}}\n'

**This error is consistent across multiple tags in the repository.**

### Steps to Reproduce

1. Authenticate to Docker Hub and obtain a token using the /v2/users/login/ endpoint.
2. Attempt to delete tags from the repository using the /v2/repositories/{username}/{repo}/tags/{tag_name}/ endpoint.
3. Observe the 500 status code and the response content indicating an unauthorized error.
4. **Attempt to delete tags via the Docker Hub UI and encounter the same unauthorized error.**

```
curl -s -H "Content-Type: application/json" -X POST -d '{"username": "dublok", "password": "dckr_pat_XXX"}' https://hub.docker.com/v2/users/login/
curl -s -H "Authorization: JWT token" -X DELETE https://hub.docker.com/v2/repositories/dublok/base-linux/tags/alpine-v1.0/
```

**Comment by ErcinDedeoglu** [comment]
Looks like similar issue years ago: https://github.com/docker/hub-feedback/issues/2251

**Comment by ErcinDedeoglu** [comment]
Just tested again, it looks like fixed.

**Comment by jcarter3** [comment]
This has been resolved, thanks for reporting!

**Comment by chadlwilson** [comment]
Is this or a similar problem back again? Oddly the first delete in a loop from code seems to work, but the second one immediately after fails with 500 Internal Server Error. Not quite sure why :-/

From the browser I see similar errors, but it then sends a second request which gets a `204` so seems to kind of work.

```json
{"message":"Delete \"https://registry.s.us-east-1.aws.dckr.io/api/internal/repos/gocdexperimental/gocd-server/tags/v24.5.0-19801\": http: non-successful response (status=500 body=\"{\\\"errors\\\":[{\\\"code\\\":\\\"UNKNOWN\\\",\\\"message\\\":\\\"unknown error\\\",\\\"detail\\\":\\\"cannot find tag v24.5.0-19801 in repository gocdexperimental/gocd-server\\\"}]}\\n\")","errinfo":{}}

```

**Comment by sheltongraves** [comment]
@chadlwilson is this issue still occuring?

**Comment by chadlwilson** [comment]
I have seen it in recent months from our automation that I can recall, so possibly it has been fixed.
