### ISSUE TITLE
https://hub.docker.com Can't open, can't pull, are you preparing not to let us use it?

### ISSUE THREAD

**Issue by 120011676** [docker/hub-feedback#2402]
https://hub.docker.com Can't open, can't pull, are you preparing not to let us use it?
China region.

https://hub.docker.com 不能打开，不能拉动，你准备不让我们使用它吗？
中国区域。

**Comment by binman-docker** [comment]
Docker has no intention of blocking access to Docker Hub from China. We have found that many users in China have incorrect DNS records for our servers, or that they are encountering some other sort of network issue between their systems and our servers.

More info: https://github.com/docker/hub-feedback/issues/2388

**Comment by jc0803kevin** [comment]
> https://hub.docker.com Can't open, can't pull, are you preparing not to let us use it? China region.
> 
> https://hub.docker.com 不能打开，不能拉动，你准备不让我们使用它吗？ 中国区域。

大佬，现在这个解决了么？
