### ISSUE TITLE
Support for prefers-color-scheme in images

### ISSUE THREAD

**Issue by nandyalu** [docker/hub-feedback#2405]
## Problem description
Docker Hub does not respect prefers-color-scheme for images. My [image page](https://hub.docker.com/r/nandyalu/trailarr) has an image at the top that uses media query of `prefers-color-scheme` to set image based on light/dark modes like:
```
  <picture>
    <source media="(prefers-color-scheme: dark)" srcset="https://raw.githubusercontent.com/nandyalu/trailarr/main/assets/images/trailarr-full-512-lg.png">
    <source media="(prefers-color-scheme: light)" srcset="https://raw.githubusercontent.com/nandyalu/trailarr/main/assets/images/trailarr-light-full-512.png">
    <img alt="Trailarr logo with name" src="https://raw.githubusercontent.com/nandyalu/trailarr/main/assets/images/trailarr-full-512.png" width=50%>
  </picture>
```

This works well on github but not on docker-hub. Is there any alternative or plans for adding support for this?

## Debug Information
Google Chrome - Version 127.0.6533.89 (Official Build) (64-bit)

[Docker Hub project link](https://hub.docker.com/r/nandyalu/trailarr)

## Error messages (on screen or in browser console)
None related to issue

## Screenshots of the issue (if applicable)
Dark Mode:
![image](https://github.com/user-attachments/assets/83950a4f-b3f0-4bcc-8796-3c8d5d78d739)

Light Mode:
![image](https://github.com/user-attachments/assets/7eb56923-a54c-46ba-af0b-4af83ab6031b)

Adding Github images to show how image looks on dark vs light modes.
On Github - Dark Mode:
![image](https://github.com/user-attachments/assets/c8358218-728d-40fa-a782-c25062f49690)

On Github - Light Mode:
![image](https://github.com/user-attachments/assets/0cbebe86-45b0-44c7-95df-0814cb3ed154)

## Temporary Solution
I have changed the `<img>` source to use an image with a color that works in both light and dark modes, but a solution would be much appreciated!

# Task List
- [x] This is **NOT** a security issue
- [x] I do **NOT** have a Docker subscription
- [x] I have looked through other issues and they do **NOT** apply to me

**Comment by wmluke** [comment]
Hi @nandyalu, Thanks for bringing this issue to our attention.  We're rolling out some changes to address it.

**Comment by nandyalu** [comment]
Perfect! I can confirm that this works! Thank you 😊
