### ISSUE TITLE
Building docker images on Github actions raises a 401 on auth.docker.io

### ISSUE THREAD

**Issue by p-j** [docker/hub-feedback#2413]
Hi, running a docker [build using alpine](https://github.com/p-j/fly-pr-review-apps/blob/main/Dockerfile) as a base image from a github action yields a 401:

```
  #0 building with "default" instance using docker driver
  
  #1 [internal] load build definition from Dockerfile
  #1 transferring dockerfile: 223B done
  #1 DONE 0.0s
  
  #2 [auth] library/alpine:pull token for registry-1.docker.io
  #2 DONE 0.0s
  
  #3 [internal] load metadata for docker.io/library/alpine:latest
  #3 ERROR: failed to authorize: failed to fetch oauth token: unexpected status from GET request to https://auth.docker.io/token?scope=repository%3Alibrary%2Falpine%3Apull&service=registry.docker.io: 401 Unauthorized
  ------
   > [internal] load metadata for docker.io/library/alpine:latest:
  ------
  Dockerfile:1
  --------------------
     1 | >>> FROM alpine
     2 |     
     3 |     RUN apk add --no-cache curl jq sed
  --------------------
  ERROR: failed to solve: alpine: failed to resolve source metadata for docker.io/library/alpine:latest: failed to authorize: failed to fetch oauth token: unexpected status from GET request to https://auth.docker.io/token?scope=repository%3Alibrary%2Falpine%3Apull&service=registry.docker.io: 401 Unauthorized
Error: Docker build failed with exit code 1
```

Accessing https://auth.docker.io/token?scope=repository%3Alibrary%2Falpine%3Apull&service=registry.docker.io from my own IP does return a JSON payload containing a token, so this seems to be an issue between github actions and the registry.

# Task List
- [x] This is **NOT** a security issue
- [x] I do **NOT** have a Docker subscription
- [x] I have looked through other issues and they do **NOT** apply to me

**Comment by p-j** [comment]
The issue seems to have been solved, or to not affect all github runners as I just retryied (for the 5th time) and it went through.
First occurence for me was at 20:29 UTC.

**Comment by thaJeztah** [comment]
Yes, there was an issue with authentic on Docker Hub; https://www.dockerstatus.com/

**Comment by thaJeztah** [comment]
Docker Hub team confirmed that this should now be resolved;

> September 27, 2024 14:20 PDT
September 27, 2024 21:20 UTC[Monitoring] Access Tokens are working again, and error rates have returned to normal. Will continue to monitor.
