### ISSUE TITLE
Official image pulls are being rate-limited (nginx, busybox, traefik)

### ISSUE THREAD

**Issue by rfay** [docker/hub-feedback#2414]
Our DDEV builds on github are showing rate-limiting failures on official images like `nginx`, `traefik`, and `busybox`. It seems like something has gone wrong with the dockerhub rate-limiting today?

> #3 ERROR: failed to copy: httpReadSeeker: failed open: unexpected status code https://registry-1.docker.io/v2/library/nginx/manifests/sha256:a98c2360dcfe44e9987ed09d59421bb654cb6c4abe50a92ec9c912f252461483: 429 Too Many Requests - Server message: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit

> Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
> failed to pull image busybox:stable: exit status 1

> ERROR: failed to solve: traefik:3.0: failed to resolve source metadata for docker.io/library/traefik:3.0: failed to copy: httpReadSeeker: failed open: unexpected status code https://registry-1.docker.io/v2/library/traefik/manifests/sha256:a208c74fd80a566d4ea376053bff73d31616d7af3f1465a7747b8b89ee34d97e: 429 Too Many Requests - Server message: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit

I hope you can fix that. I think "official images" and "DSOS images" should not be having this problem, right? And of course, rate-limiting from Github Actions runners is a serious problem for the world, because all those IP addresses are used by so many of us.

**Comment by benja-M-1** [comment]
Hi @rfay indeed something was wrong and we are sorry for the inconvenience 🙁 
We rolled back a change so the issue should be solved by now. Let us know if you still experience any problem.

**Comment by rfay** [comment]
Thank you very much!

**Comment by zachkirsch** [comment]
@benja-M-1 I am stil seeing `429 Too Many Requests - Server message: toomanyrequests` when pulling `node:22-alpine`, not sure if that applies to this issue or that is supposed to be rate-limited.

For context, this is within github actions where (I believe) I don't have the ability to log in and reduce the rate limiting

**Comment by benja-M-1** [comment]
@zachkirsch it is most likely not related to the issue we had. 

Regarding authenticating within a GitHub Action you can use that action https://github.com/docker/login-action?tab=readme-ov-file#docker-hub.

**Comment by zachkirsch** [comment]
ah cool thanks @benja-M-1 !

**Comment by rfay** [comment]
But... you shouldn't need to authenticate on an official image either.

**Comment by brianmlink** [comment]
This is still happening.

**Comment by jcarter3** [comment]
Which part is still happening? Official images are subject to rate limiting, but the specific issue happening from GHA was resolved. Can you be more specific where you are seeing an issue?

**Comment by sudo-bmitch** [comment]
I can confirm that I saw the issue several days ago and it was quickly resolved in my own GHA job.

**Comment by chenele** [comment]
It started to happen to us also.,

```
#3 [internal] load metadata for docker.io/library/node:18
#3 ERROR: failed to copy: httpReadSeeker: failed open: unexpected status code https://registry-1.docker.io/v2/library/node/manifests/sha256:ddd173cd94537e155b378342056e0968e8299eb3da9dd5d412d3b7f796ac38c0: 429 Too Many Requests - Server message: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
------
 > [internal] load metadata for docker.io/library/node:18:
------
```

we use Github Actions for our CI-CD and always used anonymous docker login to pull the official images.

is there a concrete issue now that causing this? 
is it just coincidence as Github Runners IP are shared by everyone?

trying to understand if we should switch to authenticated user everywhere.

**Comment by jcarter3** [comment]
Do you explicitly pull `docker.io/library/node:18`? Or just `node:18`? I wonder if this is a mismatch in how the credential resolver loads credentials. 

By default, credentials are saved & used by domain name -> if you do a `docker login registry.foobar.io`, credentials are saved under `registry.foobar.io` and pulls that start with `registry.foobar.io` will use those creds. Docker Hub credentials are usually saved under `index.docker.io` or `registry-1.docker.io` - pulls that use `docker.io/...` will fail to leverage them and pull anonymously (and get rate limited).

Github Actions workers are usually exempt from rate limits, but things like 👆 can cause the mechanism to fail.

**Comment by lukehsiao** [comment]
@jcarter3 

> Github Actions workers are usually exempt from rate limits, but things like 👆 can cause the mechanism to fail.

Just to check, are you suggesting we should pull `node:18`, and not `docker.io/library/node:18` to ensure we are except from rate limits?

**Comment by cabello** [comment]
Just got hit by this with postgres while on self hosted runners.

![Image](https://github.com/user-attachments/assets/67bb590a-e1b7-4104-9524-b647580657a7)

We are using the official docs https://docs.github.com/en/actions/use-cases-and-examples/using-containerized-services/creating-postgresql-service-containers

```
jobs:
  services:
        postgres:
          image: postgres:14
          env:
            POSTGRES_PASSWORD: postgres
          options: >-
            --health-cmd "pg_isready -d postgres -U postgres"
            --health-interval 5s
            --health-timeout 5s
            --health-retries 5
          ports:
            - 5432:5432
```

The mentioned docs do not cover how to point to a non Docker hub image.

This one does: https://docs.github.com/en/actions/use-cases-and-examples/using-containerized-services/about-service-containers#authenticating-with-image-registries

Trying this now.

**Comment by jcarter3** [comment]
> Just to check, are you suggesting we should pull `node:18`, and not `docker.io/library/node:18` to ensure we are except from rate limits?

Yes, the thinking is that this should help it. `docker.io` is not a registry (it's either `index.docker.io` or `registry-1.docker.io`) and so credentials will not be sent.

Also for clarity - Docker Official Images are not exempt from rate limits.

**Comment by mezotaken** [comment]
Yeah, still happening with just a single image pulled

**Comment by cabello** [comment]
Follow up, in our case we use Ubicloud and they were on top of the problem: https://github.com/ubicloud/ubicloud/discussions/2244#discussioncomment-11231599

Turns out it was this:
![Image](https://github.com/user-attachments/assets/919f67e4-8686-43e4-b97e-2b5da1c5337f)

**Comment by PhrozenByte** [comment]
> Github Actions workers are usually exempt from rate limits, but things like 👆 can cause the mechanism to fail.

Is this still true? Because we're seeing erratic rate limiting of anonymous pulls on GitHub's hosted action runners since 2025-01-29. Any changes on Docker's side? Or did GitHub change the IP subnets they use so that the rate limit exempts don't work anymore?

```
Trying to pull docker.io/library/ubuntu:focal...
time="2025-01-31T21:28:04Z" level=warning msg="Failed, retrying in 1s ... (1/3). Error: initializing source docker://ubuntu:focal: reading manifest focal in docker.io/library/ubuntu: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit"
time="2025-01-31T21:28:36Z" level=warning msg="Failed, retrying in 1s ... (2/3). Error: initializing source docker://ubuntu:focal: reading manifest focal in docker.io/library/ubuntu: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit"
time="2025-01-31T21:29:08Z" level=warning msg="Failed, retrying in 1s ... (3/3). Error: initializing source docker://ubuntu:focal: reading manifest focal in docker.io/library/ubuntu: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit"
Error: initializing source docker://ubuntu:focal: reading manifest focal in docker.io/library/ubuntu: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
```

**Comment by graft** [comment]
We're seeing this on our GHA CI since Friday (appeared out of the blue):

ERROR: failed to solve: busybox: failed to resolve source metadata for docker.io/library/busybox:latest: failed to copy: httpReadSeeker: failed open: unexpected status code https://registry-1.docker.io/v2/library/busybox/manifests/sha256:498a000f370d8c37927118ed80afe8adc38d1edcbfc071627d17b25c88efcab0: 429 Too Many Requests - Server message: toomanyrequests: You have reached your pull rate limit as '...': dckr_jti_skD35SybpJNiXmeX7cDEAJN9GGU=. You may increase the limit by upgrading. https://www.docker.com/increase-rate-limit

**Comment by SARAN-thala** [comment]
Are official images still excluded from the rate limit after April 1, 2025?
https://docs.docker.com/docker-hub/usage/

**Comment by jcarter3** [comment]
Official images were never excluded from the rate limits. That said, we will not be changing the rate limit rules on April 1. We are stepping back and re-evaluating the changes. Anything that _is_ done will be gradually phased in to ensure minimal impact.

**Comment by mikeD42** [comment]
> Official images were never excluded from the rate limits. That said, we will not be changing the rate limit rules on April 1. We are stepping back and re-evaluating the changes. Anything that _is_ done will be gradually phased in to ensure minimal impact.

Is there any public facing info available to confirm this?

**Comment by cdupuis** [comment]
> Is there any public facing info available to confirm this?

https://www.docker.com/blog/revisiting-docker-hub-policies-prioritizing-developer-experience/

**Comment by rfay** [comment]
But if I understand right that's out of date, https://github.com/docker/hub-feedback/issues/2414#issuecomment-2737323470

And I know you're aware that CI builds and such often use official images in situations where it's complex to add authentication, and where the IP addresses are shared by thousands, so are a poor limiting technique.

**Comment by jcarter3** [comment]
There is an agreement in place to support developers accessing Docker Hub from GitHub Actions. Rate limits are removed, though there are cases (running docker in docker) where anonymous limits still get applied. That is the behavior today and will remain the behavior after April 1

**Comment by PhrozenByte** [comment]
That's great news, thank you @jcarter3! :heart:

One last question: Should we report every rate limiting issue (like the ones reported here; unless, of course, it's one of those special cases, like running Docker in Docker), or are *some* errors to be expected (e.g. due to GitHub changing IP addresses) and we should only report more recurring issues (e.g. because you're always aware of IP address changes anyway)?

**Comment by jcarter3** [comment]
@PhrozenByte If you have an issue and know it's not related to DinD, please continue to report (maybe in a new issue though). IP changing _shouldn't_ be an issue, but if you see something recurring, you can let us know. We do have [OIDC](https://github.com/docker/roadmap/issues/314#issuecomment-2605945137) with GHA coming Soon™ which should also help on the authorization angle and reduce reliance on special integrations.

**Comment by edmorley** [comment]
> There is an agreement in place to support developers accessing Docker Hub from GitHub Actions. Rate limits are removed, though there are cases (running docker in docker) where anonymous limits still get applied.

@jcarter3 Hi! Does this agreement also apply to GitHub owned/hosted "custom runner groups" which have the static outbound IP option enabled?
https://docs.github.com/en/actions/using-github-hosted-runners/using-larger-runners/about-larger-runners#assigning-static-ip-addresses-to-larger-runners

**Comment by glimchb** [comment]
from today
```
Starting job container
  /usr/bin/docker pull docker.io/library/ubuntu:22.04
  Error response from daemon: unauthorized: authentication required
  Warning: Docker pull failed with exit code 1, back off 7.047 seconds before retry.
```

**Comment by rfay** [comment]
@glimchb usually `docker logout` will often solve this. Somehow the tokens seem to get out of line sometimes.  Also, dockerhub had a very bad day yesterday and a number of things were messed up. 

I'm not seeing any problems right now:
```
$ docker logout
Removing login credentials for https://index.docker.io/v1/
$ docker pull ubuntu
Using default tag: latest
latest: Pulling from library/ubuntu
Digest: sha256:353675e2a41babd526e2b837d7ec780c2a05bca0164f7ea5dbbd433d21d166fc
Status: Downloaded newer image for ubuntu:latest
docker.io/library/ubuntu:latest
$ docker pull ubuntu:22.04
22.04: Pulling from library/ubuntu
fdf67ba0bcdc: Pull complete
Digest: sha256:4e0171b9275e12d375863f2b3ae9ce00a4c53ddda176bd55868df97ac6f21a6e
Status: Downloaded newer image for ubuntu:22.04
docker.io/library/ubuntu:22.04

```
