### ISSUE TITLE
tag sizes are inaccurate

### ISSUE THREAD

**Issue by daniel-garcia** [docker/hub-feedback#242]
The size reported by the tag is not correct. 

``` bash
$ docker pull ubuntu:14.04
14.04: Pulling from ubuntu
6071b4945dcf: Pull complete 
5bff21ba5409: Pull complete 
e5855facec0b: Pull complete 
8251da35e7a7: Pull complete 
Digest: sha256:fb00a642c029fdd339cd7ed5d46ec4ace045c595123a56fc9ba331675ec9da08
Status: Downloaded newer image for ubuntu:14.04
$ docker images | grep ubuntu
ubuntu                   14.04               8251da35e7a7        3 days ago          188.4 MB
```

This shows that ubuntu:14.04 is 188MB but docker hub shows 63 MB.

![image](https://cloud.githubusercontent.com/assets/366029/9200199/4d3d6fe6-400c-11e5-924d-e85955c07942.png)

**Comment by nhsiehgit** [comment]
Hi @daniel-garcia 
I know there was an issue with docker 1.8 causing the tag sizes to be incorrect. Can you verify what version of docker you were using? 
If on 1.8, would you be able to upgrade to 1.8.1 and see if this is still an issue?

Thanks

**Comment by daniel-garcia** [comment]
@nhsiehgit 
```
Client version: 1.7.1
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 786b29d
OS/Arch (client): linux/amd64
Server version: 1.7.1
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 786b29d
OS/Arch (server): linux/amd64
```
Should I try with 1.8.1?

**Comment by nhsiehgit** [comment]
Actually this may be a different issue.

Thanks for filing, we'll try to figure out where the discrepancy is

**Comment by twang2218** [comment]
I got the same issue. Tag sizes in the Docker Hub are incorrect.

Use official Python image as a example,
<https://hub.docker.com/r/library/python/tags/>

<img width="721" alt="2016-08-05 10 50 25" src="https://cloud.githubusercontent.com/assets/6299096/17423068/036c3ffe-5afb-11e6-8609-fdb8e3725b45.png">

The size of `latest` tag shown on the Docker Hub page are `267MB`, however, when it's been pulled to the local, the size is `687.1MB`, they are very different:

```bash
$ docker images
REPOSITORY                  TAG                 IMAGE ID            CREATED             SIZE
python                      latest              8bdda5ddd39e        3 days ago          687.1 MB
```

And I don't think the `docker` command are wrong, if we look further, check the security scan report page on Docker Hub, <https://hub.docker.com/r/library/python/tags/latest/>, the size of `python:latest` is definitely not `267MB`:

<img width="1252" alt="2016-08-05 10 50 44" src="https://cloud.githubusercontent.com/assets/6299096/17423162/0a9d6cac-5afc-11e6-8963-358e214fd861.png">

As you seen the highlighted part in the screenshot, add them up, they are far beyond the `267MB` size. Actually, the security scanned sizes are similar to the `docker images` command.

It's a bug in Docker Hub code. I added the layers with several combinations, still cannot figure out where the number `267MB` came from.

My docker version is the latest one, `1.12`:

```bash
$ docker version
Client:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 21:04:48 2016
 OS/Arch:      darwin/amd64
 Experimental: true

Server:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 21:04:48 2016
 OS/Arch:      linux/amd64
 Experimental: true

$ docker info
Containers: 3
 Running: 0
 Paused: 0
 Stopped: 3
Images: 97
Server Version: 1.12.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 223
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null host overlay bridge
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.15-moby
Operating System: Alpine Linux v3.4
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.954 GiB
Name: moby
ID: GYJ7:MTJ2:B4PV:T7FB:PPUE:FNPU:5WN2:T7ED:WLXS:2WWO:UMJO:VF3M
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 21
 Goroutines: 32
 System Time: 2016-08-05T01:07:03.014628696Z
 EventsListeners: 1
No Proxy: *.local, 169.254/16
Username: twang2218
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
```

**Comment by bcwalrus** [comment]
`docker images` shows the uncompressed size. During a `docker push`, the engine compresses (gzip) the image before sending to the registry. The size shown in the Hub UI is the compressed size, and roughly represents how much work a fresh `docker pull` would need to do. The network transfer size is probably the more important number when deploying containers.

Point taken on the UI being unclear. It should really say "Compressed size".

**Comment by afeld** [comment]
cc #331
