### ISSUE TITLE
Broken Redirect Link After Email Update in Docker Hub

### ISSUE THREAD

**Issue by Ksj14-kumar** [docker/hub-feedback#2420]
**Description**:
After changing my email address on Docker Hub, I received a confirmation email with a link to visit my account settings. However, when I clicked the link, I was redirected to a new tab showing the following URL:

`http://%22%22/`

**Actual Behavior**:
The link leads to an invalid URL, and the page shows only `http://%22%22/.`

**Reproduce**
**Steps to Reproduce:**
- Log in to Docker Hub.
- Change your email address in the account settings.
- Receive the confirmation email with the link.
- Click the link in the email.

**Expected Behavior:**
The link should redirect me to the Docker Hub account settings page.

**Comment by pla-sam** [comment]
Hello, thank you for reporting this issue to us. The issue has been fixed. Future emails will send you to the correct page
