### ISSUE TITLE
DockerFlex Frontend Image Pull Count Discrepancy

### ISSUE THREAD

**Issue by mbakgun** [docker/hub-feedback#2422]
Hello,

I am the maintainer of DockerFlex (https://github.com/mbakgun/DockerFlex): The missing file manager for Docker containers 🐳 Browse, edit, and manage container files with ease through a modern web interface) and I’ve noticed a significant discrepancy between our frontend and backend image pull counts:

Frontend Image (mbakgun/dockerflex-frontend): 0 pulls
Backend Image (mbakgun/dockerflex-backend): 98 pulls

Both images are:

Published through the same GitHub Actions workflow
Using identical tag strategies
Pushed at the same time
Both set as public repositories

I’ve verified that:

The frontend image is successfully being pushed
The repository is public
The image is accessible and can be pulled
Both images are referenced in our docker-compose.yml

Could you please investigate why the frontend pull count might not be tracking correctly or if there are any visibility issues with the frontend repository?

Thank you for your assistance.

**Comment by jcarter3** [comment]
I can verify that we do receive a lot of pulls on `dockerflex-backend` repo, but we have not gotten pulls on the `dockerflex-frontend`. I do not know why that would be, but the counts do look correct.

**Comment by mbakgun** [comment]
> I can verify that we do receive a lot of pulls on `dockerflex-backend` repo, but we have not gotten pulls on the `dockerflex-frontend`. I do not know why that would be, but the counts do look correct.

I don't think so. I only installed it on 3 different servers. 0 sems really not possible. I also received updates with the latest tag as updates were released (wathctower). I had also written on the forum, and others had downloaded both repo too. https://forums.docker.com/t/dockerflex-frontend-image-pull-count-discrepancy/145134

**Comment by rimelek** [comment]
@jcarter3 Yes, I'm one of the "others" who pulled the image and checked the counter one day later when the backend counter changed, but the frontend didn't. I checked the counter using the API and the GUI. The first day the backend had 101 on the GUI and 110 from the API. The second day it had 110 on the GUI and I think 121 from the API, but there was no change for the frontend

**Comment by mbakgun** [comment]
Thank you all. It seems like we have now made progress; it shows 3 for the **frontend** repo

**Comment by jcarter3** [comment]
It looks like this is resolved at the moment - we had an event pipeline get backed up. We've added further monitoring for the future to prevent this from happening again!
