### ISSUE TITLE
Pulling published tags (eg.: latest) is denied until vulnerability scans are finished

### ISSUE THREAD

**Issue by martonivan** [docker/hub-feedback#2426]
I'm attempted to use a recent tag of an official docker image: docker:dind, but failed to fetch the image. The error message was "manifest for docker:latest not found: manifest unknown: manifest unknown".

My educated guess about the root cause is that this was caused by the circumstance that there was no vulnerability scans finished on this tagged image.

I wish it wouldn't be better not to overwrite an existing tag with a new image content until that scan is finished to ensure that the image is downloadable while the scan of the image is being performed?

This widely used and official image is unavailable for hours at this moment. Thread was started about this at first on Docker community forum:
https://forums.docker.com/t/images-are-not-available-while-still-no-vulnerability-analysis-are-available/145482

**Comment by cdupuis** [comment]
Thanks for raising this. 

We are aware of issues with some recently pushed Docker Official Images. We'll report back with an update soon.

**Comment by thaJeztah** [comment]
For more details; here's two tickets reported for the `docker` (docker in docker) images; I posted some further details on those tickets;

- https://github.com/docker-library/docker/issues/519
- https://github.com/docker-library/docker/issues/520

**Comment by thaJeztah** [comment]
Update on this issue; a colleague confirmed that the list of official images should be all processed. The verification script will still be running for some hours, but we're updating the statuspage to "monitoring"

There may be some images in the platform-specific orgs that are used as intermediate image that may not yet be addressed, and (given much lower / corner-case use), e.g. images in the platrform-specific namespace (e.g. https://hub.docker.com/u/arm64v8/, and other similar namespaces listed in; https://github.com/docker-library/official-images#architectures-other-than-amd64. Those namespaces are effectively intermediate stages for the multi-platform images. These images will likely be processed later, which may be done after the weekend.


I'll close this ticket
