### ISSUE TITLE
Build Settings is very broken

### ISSUE THREAD

**Issue by wblankenship** [docker/hub-feedback#245]
When adding new rows, they get added randomly throughout the existing list.

When typing data into rows, it mucks up data in other rows.

This makes the page unusable. I currently can not add new tags to my existing images.

Screenshot:

[Imgur](http://i.imgur.com/z8rWlGN.gifv)

`lsb_release -a`

```text
Distributor ID:  Debian
Description:     Debian GNU/Linux 8.1 (jessie)
Release:         8.1
Codename:        jessie
```

`google-chrome --version`

```text
Google Chrome 43.0.2357.65 
```

**Comment by rrarunan** [comment]
looking into it.

**Comment by nhsiehgit** [comment]
Wow...
was able to reproduce. seems like the issue comes when you are adding more than 10 rows. Definitely an issue.

+1 on it

**Comment by nhsiehgit** [comment]
Hi @wblankenship 

can you check and confirm whether this is still an issue or not?

**Comment by nhsiehgit** [comment]
closing this issue now. If there's still a problem please reopen with any relevant information
