### ISSUE TITLE
Need the ability to delete tagged images in automated builds

### ISSUE THREAD

**Issue by timlinux** [docker/hub-feedback#250]
I have the situation in https://hub.docker.com/r/kartoza/postgis/ where I have a tag I cannot delete:

<img width="272" alt="screen shot 2015-08-12 at 08 15 18" src="https://cloud.githubusercontent.com/assets/178003/9217634/624018bc-40ca-11e5-8feb-e7ad5f2163cc.png">

But in my settings I have:

<img width="955" alt="screen shot 2015-08-12 at 08 15 06" src="https://cloud.githubusercontent.com/assets/178003/9217639/6a03578a-40ca-11e5-9be3-cdafd346d2e0.png">

I tried adding a tag by the same name in settings and then removing it again, hoping to 'trick' it into deleting the unwanted tag without success. 

# Expected outcome

Deleting a tagged build in settings should remove the corresponding tag in the tags tab (perhaps with an appropriate warning if there is already an existing image for that tag.

**Comment by timlinux** [comment]
For clarity, the unwanted tag above is ```9.3```.

**Comment by sbrrodm** [comment]
+1 on this one, I also need to delete some tags for ordering and restructuring of tag practices.

**Comment by kizbitz** [comment]
Linking to: https://github.com/docker/hub-beta-feedback/issues/68

**Comment by aayore** [comment]
+1

**Comment by jawaid** [comment]
+1

**Comment by FunThomas424242** [comment]
+1

**Comment by ChristopherBiscardi** [comment]
Deleting Tags is live in prod. Thank you everyone; Please let us know if you have any issues.

![screen shot 2015-12-04 at 12 06 28 pm](https://cloud.githubusercontent.com/assets/551247/11600127/81b60b66-9a7f-11e5-92d4-a88078aeec68.png)

**Comment by timlinux** [comment]
@ChristopherBiscardi thanks so much!
