### ISSUE TITLE
Cursor jumps to end in text boxes on create new automated build

### ISSUE THREAD

**Issue by ejether** [docker/hub-feedback#258]
Create a new automated build
Enter text in ether the registry name or the description
Use keyboard or mouse to put cursor in the entered text
Press key

Cursor jumps to end of field

Using Chrome Version 44.0.2403.125 (64-bit) on Mac OSX Yosemite 10.10.4 (14E46)

**Comment by ChristopherBiscardi** [comment]
Thanks for reporting; I'm working on redoing all of our text fields for various reasons.

**Comment by mcandre** [comment]
Same error on create new repo. The new Docker Hub is incredibly buggy.
