### ISSUE TITLE
Inconsistent units used when reporting image size

### ISSUE THREAD

**Issue by bdehamer** [docker/hub-feedback#259]
When looking at the output from the `docker images` command, the image size is reported in megabytes (MB).

<img width="858" alt="screen shot 2015-08-12 at 10 59 08 am" src="https://cloud.githubusercontent.com/assets/398027/9232196/390987fa-40e1-11e5-988f-19ff70f9e896.png">

However, the image size reported on the hub is shown in mebibytes (MiB)

<img width="511" alt="screen shot 2015-08-12 at 11 00 23 am" src="https://cloud.githubusercontent.com/assets/398027/9232217/5cc2ce9a-40e1-11e5-839f-4d6dae9ba29f.png">

Even though the hub uses the "MB" suffix, it technically isn't megabytes. 

Would probably be better to use a consistent measurement unit across all of the Docker tools.

**Comment by ChristopherBiscardi** [comment]
Agreed. We should move to parity with the CLI.

**Comment by twang2218** [comment]
As one year later, Aug 2016, they are still different.

And not only the size on the tag page, as the size in security scan report page as well.

**Comment by bcwalrus** [comment]
CLI is reporting the uncompressed size, while Hub reports the compressed size. It's a column labelling issue. Let's track it in https://github.com/docker/hub-feedback/issues/242#issuecomment-237928742.
