### ISSUE TITLE
Unable to create automated builds from organizations when linked to Github with 'Limited' access.

### ISSUE THREAD

**Issue by kizbitz** [docker/hub-feedback#260]
When linked to Github with 'Limited' access - No repositories from any Github organizations are displayed when creating a new automated build. Just personal Github repositories.

**Comment by ChristopherBiscardi** [comment]
Looks like we should be using the `public_repo` [scope](https://developer.github.com/v3/oauth/#scopes). Instead we are currently using `(no scope)`

**Comment by akerl** [comment]
no_scope should be sufficient for listing the repositories that a user has access to. Without any auth at all, you can get a list of a user's public orgs: https://api.github.com/users/akerl/orgs and then a list of those org's repos: https://api.github.com/orgs/dock0/repos
