### ISSUE TITLE
The automated-build button is hidden / hard to find

### ISSUE THREAD

**Issue by rogaha** [docker/hub-feedback#261]
It's hard to easily find the button to create automated-builds, should we have only one button with an option to create either a normal or an automated repo?

**Comment by ChristopherBiscardi** [comment]
There are a few threads surrounding the creation of objects in the system. One of which is related to this button (which is what I think you're referring to).

![screenshot 2015-08-12 11 45 03](https://cloud.githubusercontent.com/assets/551247/9233401/9cd0cd60-40e7-11e5-9d62-17530e029596.png)

In the future, it is likely that this button will send you to a page which allows you to choose between Automated and Normal repo types (with explanations as to what each are).
