### ISSUE TITLE
Error pushing to registry: Server error: 400 trying to push ...

### ISSUE THREAD

**Issue by jakirkham** [docker/hub-feedback#265]
Seems I am getting this error frequently.

**Comment by jason-tian** [comment]
I'm getting this error frequently too. Who can help resolve it on dockerhub side?

**Comment by lawitschka** [comment]
Same here, sometimes it just works, but in 90% of the time pushing fails

**Comment by ChristopherBiscardi** [comment]
Can anyone confirm this is still occurring for them?

**Comment by jakirkham** [comment]
It's an intermittent error. However, I haven't seen it recently.

**Comment by jakirkham** [comment]
Sometime I have seen an `exception` where it states "Log unrecoverable.". I wonder if they share a common cause.

**Comment by twinge** [comment]
I'm still having this issue fairly frequently (maybe 1 in 5 or so pushes)

**Comment by ChristopherBiscardi** [comment]
@twinge Can you provide docker version and any other information about your current setup that may be relevant?

@jakirkham Are you saying that this issue only shows up in Automated Builds? or was this originally a push from your local computer/server.

**Comment by jakirkham** [comment]
@ChristopherBiscardi, I almost only use automated builds. So, I can't say that it wouldn't have shown up otherwise. All I can say, is this was the context, in which this error arose for me.

**Comment by twinge** [comment]
Docker version 1.6.2, build 7c8fca2

$ docker push cruglobal/missionhub

time="2015-08-26T16:01:50Z" level=fatal msg="Error pushing to registry: Server error: 400 trying to push cruglobal/missionhub:a0faca59614daeb0c016686424b6ce47d3f6733b-466 manifest"

**Comment by jakirkham** [comment]
So, this happened to me again. A couple hours before the disruption occurred.

**Comment by nhsiehgit** [comment]
Has this been resolved? If not it seems like this would be a priority ticket.

@ChristopherBiscardi ?

**Comment by jakirkham** [comment]
I haven't seen this particular error recently. However, I have seen the "Log unrecoverable" exception a few hours ago.

**Comment by cswarth** [comment]
"Log unrecoverable" is still happening,
https://hub.docker.com/r/cswarth/docker-beast/builds/baxmsqhfggamamfgjtdg8xm/

Also the message doesn't seem to show up unless I am logged in to dockerhub. If not logged in the exception report is completely blank, and this is a public repo of an automated build.
