### ISSUE TITLE
Automated build dockerfile view is empty

### ISSUE THREAD

**Issue by eviltnan** [docker/hub-feedback#268]
Dockerfile is empty in the automated build page.

I'm not sure if this can be influenced by the fact, that initially I've specified wrong path for the dockerfile. Nevertheless after fixing the dockerfile path, I trigger the build and it finishes successfully, but in Dockerfile tab and in build details view Dockerfile content remains empty.

Repo: tbeu/avousbackend

**Comment by justfortherec** [comment]
I have [the same issue](https://hub.docker.com/r/jftr/fairphone2-build-env/~/dockerfile/). Is there a way to resolve this from my side?

**Comment by OskarKlintrot** [comment]
2 years later, is there still no fix for this?
