### ISSUE TITLE
Automated builds have "dirty" submodule repos

### ISSUE THREAD

**Issue by jakirkham** [docker/hub-feedback#270]
If I insert a git repo into a container, as is done in some automated builds. I find that the repo appears to be dirty. In particular, I can reliably repeat the following.

```
$ git status
# On branch <branch>
nothing to commit (working directory clean)

$ git describe --tags --dirty --always
<TAG>-<NUM COMMITS>-<SHA>-dirty

$ git diff

$ git describe --tags --dirty --always
<TAG>-<NUM COMMITS>-<SHA>
```

Additionally, I tried to follow this ( https://tech.bellycard.com/blog/taming-git-for-docker ). However, it won't eliminate the dirty issue itself. When inspecting `.git`, it appears the git repo's index file is changed in some fashion after running `git diff`.

**Comment by jakirkham** [comment]
Also, if I try running this in a container and commit it and run the committed image as a new container, the repo will appear dirty again afterwards.

**Comment by jakirkham** [comment]
This appears to be caused by an issue with git ( http://stackoverflow.com/questions/16035240/why-is-git-describe-dirty-adding-a-dirty-suffix-when-describing-a-clean-ch ). It can also be addressed by running `git update-index -q --refresh`. However, it is surprising that that updating the index in this way does not persist in a committed image.

**Comment by jakirkham** [comment]
It turns out simply running `touch .git/index` after will alleviate the commit issue. However, this seems to be a strange workaround as `git update-index -q --refresh` will already update the timestamp on that file.

**Comment by jakirkham** [comment]
Surprisingly, this workaround ( https://github.com/docker/hub-beta-feedback/issues/270#issuecomment-130780354 ) does not help in an active build. It only works when committing a previously run container that already has the repo within.

**Comment by nhsiehgit** [comment]
Seems like you may have found your solution, but as this doesn't look like it pertains to docker hub i'm closing this ticket.

Thanks

**Comment by jakirkham** [comment]
Actually, not totally true. The error is caused by git. However, the fix that works outside of a container does not seem to work in the automated build. It also doesn't seem to remain between commits. I think this is still worth investigating. That being said, I have done a fair bit of work to understand the issue.

**Comment by ChristopherBiscardi** [comment]
Re-opening to triage.

@jakirkham Do you have a reproduction case for this issue? In the original filing I only see git commands.

**Comment by jakirkham** [comment]
I have a private repo that suffers from this. I can try to come up with a simple public repo that reproduces this problem.
