### ISSUE TITLE
"Source Project" button opens the same page on a different tab

### ISSUE THREAD

**Issue by ahmetalpbalkan** [docker/hub-feedback#288]
https://hub.docker.com/r/mesoscloud/zookeeper/~/dockerfile/

> ![image](https://cloud.githubusercontent.com/assets/159209/9291458/0d35e708-4376-11e5-9a8e-f08e2b95d635.png)

This button just opens the same url. The issue #160 was reported before but it is not fixed. The repo is an automated repo in this case and the Hub should have access to its dockerfile and repo link.

**Comment by ChristopherBiscardi** [comment]
@ahmetalpbalkan Thanks for re-opening this.

**Comment by md5** [comment]
I believe this only happens when the user is not logged in.

**Comment by pedroxs** [comment]
I can confirm this happened to me. While not logged the "Source Project" just opens the same page on new tab, but after logging in it started working fine.

**Comment by rrarunan** [comment]
Ok, I have reproduced this in only one scenario (when a page is loaded from a link, when not being logged in).. if you search for `zookeeper` for example and click on it.. it will work fine. Looking into a fix.

**Comment by md5** [comment]
I just ran across this problem when I was logged in. Going directly to https://hub.docker.com/r/mdillon/postgis/builds/ in a new tab makes the "Source Project" button not work. If I then click on "Repo Info", the "Source Project" button starts working again.

**Comment by ahmetalpbalkan** [comment]
yup still happens.

**Comment by ahmetalpbalkan** [comment]
I genuinely wonder how hard is it to fix this.

**Comment by kristiehoward** [comment]
Closing as this is fixed in production
