### ISSUE TITLE
Status of automated build is not obvious

### ISSUE THREAD

**Issue by huslage** [docker/hub-feedback#3]
I didn't realize, and had to look quite hard to find the status of my newly created automated build.

https://www.dropbox.com/s/vi8z3hhakmtj4pm/Screenshot%202015-06-03%2019.08.35.png?dl=0

**Comment by ChristopherBiscardi** [comment]
Copying image to be inline rather than a link.

![image](https://cloud.githubusercontent.com/assets/551247/7973912/26e96246-0a10-11e5-8bef-6a0b1cbf6224.png)

**Comment by ChristopherBiscardi** [comment]
hrm. This does seem problematic. There also seems to be a discrepancy between the `PENDING` status and the actual list of builds. Thanks for reporting.
