### ISSUE TITLE
Last pushed: never

### ISSUE THREAD

**Issue by archit** [docker/hub-feedback#301]
I just created a public repository in my docker account `archit/pox`. I pushed some images from the CLI. The output showed like it succeeded. I'm able to `docker pull archit/pox:v1` from another machine.

However when I refresh the docker hub page, it says `last pushed: never`.

**Comment by anarcher** [comment]
Me too.  `docker push`  with tag was successful. But In hub.docker.com, I can't see this push's tags and last pushed isn't updated.

**Comment by mnylen** [comment]
Me too. I first pushed a new image from command line to my organization's account and that succeeded but nothing showed up on the Docker Hub page.

I tried waiting for a while and then created a new repository with the same name using the web interface (and set it to private) and pushed again, and now it shows `Last pushed: never`.

Using Docker 1.7.1.

**Comment by nhsiehgit** [comment]
Thanks for your comments everyone.

Looks like there may be an issue with what version docker you're using and whether you created the repo via hub or cli. Needs more digging

related: https://github.com/docker/hub-beta-feedback/issues/180

**Comment by archit** [comment]
@nhsiehgit I'm using Docker CLI `1.7.1` `786b29d`

**Comment by fauzanariffin** [comment]
@nhsiehgit I was able to replicate it.

**Docker Version:**
```
Client:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:35:49 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:35:49 UTC 2015
 OS/Arch:      linux/amd64
```

**Docker Push:**
```
The push refers to a repository [docker.io/fauzanariffin/docker-whale] (len: 1)
6aa0a2b2cc3e: Image successfully pushed 
1f3e54ba6882: Image successfully pushed 
1506dc8e2d91: Image successfully pushed 
fb434121fc77: Image successfully pushed 
5d5bd9951e26: Image successfully pushed 
99da72cfe067: Image successfully pushed 
1722f41ddcb5: Image successfully pushed 
5b74edbcaa5b: Image successfully pushed 
676c4a1897e6: Image successfully pushed 
07f8e8c5e660: Image successfully pushed 
37bea4ee0c81: Image successfully pushed 
a82efea989f9: Image successfully pushed 
e9e06b06e14c: Image successfully pushed 
latest: digest: sha256:ae40ff041871f31b3adecd3dcbbfece8aa7d222c23c2d7b37dd6adb782290ee0 size: 23737
```

My repo link:
https://hub.docker.com/r/fauzanariffin/docker-whale/

**Comment by jawaid** [comment]
I have same issue +1

**Comment by adamryman** [comment]
Same issue +1

**Comment by hharnisc** [comment]
I've got docker CLI Docker version `1.8.1, build d12ea79`

I have a new image that looks like it pushed successfully but I don't see it in hub.docker.com

```bash
bash-3.2$ docker push hharnisc/elasticsearch
The push refers to a repository [docker.io/hharnisc/elasticsearch] (len: 1)
f192ce485994: Image successfully pushed 
44d3379bfaa3: Image successfully pushed 
4cda1e1edc6d: Image already exists 
b07020d42866: Image already exists 
0f777b4f3a06: Image successfully pushed 
5f3d14a2a0b5: Image already exists 
f3dc09d18cd2: Image successfully pushed 
7d3be1fa5f3c: Image already exists 
bd14899ab130: Image successfully pushed 
5e7e747cf575: Image successfully pushed 
0b171acd54e1: Image already exists 
885e40150295: Image already exists 
a283ae560725: Image successfully pushed 
ad4cbf83fa18: Image successfully pushed 
f5e686234c7c: Image successfully pushed 
f57924d8adc8: Image successfully pushed 
b5efeb69cd3e: Image successfully pushed 
6ebd2800202a: Image already exists 
b7f545455a46: Image already exists 
9ddadf076b79: Image already exists 
1a9b1e5c4dd5: Image already exists 
4b61c52d7fe4: Image successfully pushed 
6f6bffbbf095: Image successfully pushed 
1ff9f26f09fb: Image successfully pushed 
9a61b6b1315e: Image already exists 
902b87aaaec9: Image successfully pushed 
latest: digest: sha256:f34b8560845429daf992881a1ebf01d11bd8daf5dcc83fb7d6a391f6829c33c5 size: 54182
```

I was expecting it to show up at https://hub.docker.com/r/hharnisc/elasticsearch/ but does not exist.

**Comment by hharnisc** [comment]
This morning when I checked the images seem to be there.

**Comment by mc388** [comment]
Same issue +1

**Comment by anyei** [comment]
It looks like it takes a while to reflect the last pushed wording, i was about to +1 but then i saw the little verbiage refreshed that says "Last pushed: 3 minutes ago".

**Comment by Stephenitis** [comment]
+1 not seeing that immediate feedback in the dockerhub interface had me running in circles for awhile.
`Docker version 1.8.1, build d12ea79`

**Comment by bitliner** [comment]
+1 docker `1.11.1`

**Comment by ankitarya10** [comment]
Seeing the same issue on Docker version 1.12.5, build 7392c3b

**Comment by bluesockets** [comment]
same on Docker version 1.12.3, build 6b644ec

**Comment by mrajashree** [comment]
Facing same issue today for Docker version 1.12.3

**Comment by student-t** [comment]
Same here.
