### ISSUE TITLE
Cannot edit tags of a repo

### ISSUE THREAD

**Issue by ahmetalpbalkan** [docker/hub-feedback#308]
Right now I'm editing tags of a repo (`microsoft/azure-cli`) of an organization I administer.

Hitting **SAVE** button below absolutely does not do anything.

> ![image](https://cloud.githubusercontent.com/assets/159209/9422071/1d73ad7c-4839-11e5-88b4-6a8115bf8f9d.png)

### Repro steps:

0. I went to https://hub.docker.com/r/microsoft/azure-cli/~/settings/automated-builds/
0. Changed latest to 0.9.6 --> 0.9.8
0. Added last two rows (0.9.7, 0.9.8)
0. Click "Save"
0. Nothing is happening, I'm still on the same page, form does not submit. There are no logs in the console...

> :warning:  **EDIT:** After a couple of refreshes, I realized the data is actually updated... However there's no visual feedback that the Save actually worked. (1) Page doesn't change (2) No color or text changes anywhere as far as I can tell...

**Comment by nhsiehgit** [comment]
Sorry, agreed this can be more clear.

If you notice, we _do_ add the subtle green outline to the table showing that a successful save has occured, but it can definitely be more obvious.

**Comment by ahmetalpbalkan** [comment]
haha totally not noticed that. I would've if `border-size: 20px`.
