### ISSUE TITLE
Automated build with private bitbucket repo not working

### ISSUE THREAD

**Issue by mc388** [docker/hub-feedback#310]
Hi,

I connected my bitbucket account with docker hub. Then I created a new automated build repo and select a private repo from bitbucket.

If I trigger the build process I always get an error

```
Failed to clone repository: Cloning into '/tmp/build_bf3cnrq5mbtf9zwgnhebtam'... Warning: Permanently 
added the RSA host key for IP address '131.103.20.167' to the list of known hosts. Permission denied 
(publickey). fatal: Could not read from remote repository. Please make sure you have the correct access 
rights and the repository exists.
```

If I switch the bitbucket repro from private to public, it works fine.

**Comment by NOX73** [comment]
Same problem

**Comment by sansusan** [comment]
fucked docker hub

**Comment by ChristopherBiscardi** [comment]
ping @rrarunan

**Comment by spiddy** [comment]
same problem for me too.

**Comment by rrarunan** [comment]
Could be related to https://github.com/docker/hub-feedback/issues/213 .. @kencochrane Can you please see if this is related? Doesn't seem like an issue with linking the repo.

**Comment by kencochrane** [comment]
@mc388 @NOX73 @spiddy are you still seeing this issue if you create a new automated build today using a private repo from bitbucket?

**Comment by mc388** [comment]
For me it works now. Thanks

**Comment by adegoodyer** [comment]
Make sure you've added your SSH keys in Bitbucket (and they match!)

**Comment by arslan88** [comment]
Could any one share a related document how to add a docker file in private repo to run automated builds ?

**Comment by kencochrane** [comment]
@arslan88 it is the same way as a public repo, no difference. Are you getting an error, or having an issue getting started?

**Comment by arslan88** [comment]
Hi again , i am trying to start and having issues . I want to crate automate build and automate test for bitbucket pipeline but i am unable to find a useful bitbucket-pipeline.yml. If you could share a document with step by step instructions it will be appreciated . Thanks in advance

**Comment by kencochrane** [comment]
Here are the docs for creating an automated build on the hub. https://docs.docker.com/docker-hub/builds/

I don't know anything about bitbucket pipelines you will have to check with bitbucket for that.

**Comment by arslan88** [comment]
The repo i am trying to automate build for is a git repo ..

**Comment by kencochrane** [comment]
It shouldn't matter, it will work for both git and mercurial
