### ISSUE TITLE
Bad spacing around code blocks in image README

### ISSUE THREAD

**Issue by ahmetb** [docker/hub-feedback#312]
Notice how space after the code block is less than before the code block. Hurts my eyes, sort of. :)

https://hub.docker.com/r/ahmetalpbalkan/registry-benchmark/

![image](https://cloud.githubusercontent.com/assets/159209/9480108/f621498c-4b35-11e5-9cb0-2ce2be28a37f.png)

**Comment by janeczku** [comment]
+1 My eyes are hurting too! :sob:

**Comment by binhex** [comment]
yep ugly as sin isn't it, +1

**Comment by janeczku** [comment]
What's the ETA for fixing this? This really upsets the layout and inhibits readability.
Here is another example of a code block followed by a heading:

![bildschirmfoto 2016-02-17 um 08 32 30](https://cloud.githubusercontent.com/assets/3813921/13102866/e907720c-d551-11e5-93c9-3aab2825ea94.png)

**Comment by ahmetalpbalkan** [comment]
still bad
