### ISSUE TITLE
No way to change source project for automated build

### ISSUE THREAD

**Issue by freeformz** [docker/hub-feedback#313]
For whatever reason (there are several) [heroku/cedar](https://hub.docker.com/r/heroku/cedar/) is setup to build from [tt/stack-images](https://github.com/tt/stack-images). We'd like to be able to change the source project to [heroku/stack-images](https://github.com/heroku/stack-images) instead w/o having to nuke the automated build / project and break everyone's links.

**Comment by danlamanna** [comment]
+1

**Comment by tt** [comment]
:+1:

**Comment by hg-jt** [comment]
+1

**Comment by markoshust** [comment]
:+1:

**Comment by jlsalvador** [comment]
:+1: Do you need some help to make that this happens?

**Comment by nhumrich** [comment]
:+1:

**Comment by kenny1986** [comment]
+1

**Comment by kytwb** [comment]
:+1:

**Comment by skohar** [comment]
:+1:

**Comment by zmarty** [comment]
:+1:

**Comment by jarfil** [comment]
:+1:

**Comment by samos123** [comment]
+1

**Comment by davidcarboni** [comment]
+1

**Comment by raphi** [comment]
+1

**Comment by nuxlli** [comment]
:+1:

**Comment by sjackman** [comment]
:+1:

**Comment by jangorecki** [comment]
:+1:

**Comment by btiernay** [comment]
:+1:

**Comment by andrew804** [comment]
:+1:

**Comment by Mahmoudz** [comment]
:+1:

**Comment by greyltc** [comment]
:+1: This feature is pretty important to me.

**Comment by bharath-cchmc** [comment]
+1

**Comment by Dids** [comment]
+1 especially now that Github's gone all unlimited on us, so we can finally move from Bitbucket to Github, which would break automated Docker Hub builds.

**Comment by pchico83** [comment]
This is supported in Docker Cloud Build service, we are prioritizing build development in Docker Cloud over Docker Hub.

**Comment by hurricanehrndz** [comment]
+1

**Comment by cyrille-leclerc** [comment]
+1

**Comment by hrchu** [comment]
+1

**Comment by jljorgenson18** [comment]
+1

**Comment by svlentink** [comment]
+1

**Comment by christianbundy** [comment]
Are there steps that we can take to get this fixed, or are we stuck waiting? This looks to be the second-most 👍'd issue on here and we haven't seen a response in over a year (except for @nhsiehgit tagging it as a feature request). I don't think the "+1" train above is very helpful, but I can empathize with those who don't see any other options to get the Docker Hub team's attention.

I guess having it tagged `feature-request` in October technically counts acknowledging the issue, but some feedback (or a timeline) would be *very* appreciated. Thanks for your work on this project!

**Comment by mghazizadeh** [comment]
@christianbundy this capability (and a lot more) is available in Docker Cloud. Docker Cloud provides you the same repo access with your existing content and repp subscriptions.

https://docs.docker.com/docker-cloud/builds/automated-build/

If you rely on the collaboration of teams and orgs functionality, the same integration and structure you have on Docker Hub will soon be available on Docker Cloud as well with that structure preserved. 

As @pchico83 had mentioned here before, we don't have immediate plans to update Docker Hub auto-builds with this capability.

**Comment by christianbundy** [comment]
Thanks, I must have misunderstood @pchico83's comment. Is the Docker Hub interface being fazed out? I'm only seeing this from a distance, but it seems like the Docker Hub interface is being replaced by Docker Cloud's cross-registry interface. Am I imagining things, or should I jump ship and learn Docker Cloud before the Hub interface becomes obsolete?

**Comment by Webysther** [comment]
:+1:

**Comment by mauricioklein** [comment]
:+1:

**Comment by mauricioklein** [comment]
Just a question, please:

As far I've understood, Docker team is focusing efforts to evolve Docker Cloud instead Docker Hub.

However:
1. Docker Cloud is in beta mode;
2. I've many repos bought in Docker Hub;

My question is:
1. Is Docker Cloud fine to be used in production already, even in beta mode?
2. It says in Cloud that it's free while in beta mode. After that, what's going to happen? My paid repos on Hub will be migrated to Cloud? The automated build will still be working?

**Comment by bcwalrus** [comment]
There's been some misunderstanding here. Docker Cloud has GA'ed, and is being used for production. Some of our customers are running 100+ services in their clusters, doing auto redeploy with blue-green deployment. Would love to have you try it out and get your feedback. https://blog.docker.com/2016/03/announcing-docker-cloud/
https://docs.docker.com/docker-cloud/getting-started/

Cloud and Hub shares the same Registry Service. If you go to Cloud today, you'll see the same repos that you see in Hub. No need to migrate any bits.

Automated builds is an area we're working on. Cloud and Hub store autobuild configuration separately today. We'd like to avoid asking users to do manual migration, and so are working on merging that. Meanwhile, you can repeat your autobuild setup in Cloud, and just disable builds on Hub.

**Comment by jangorecki** [comment]
Going back to the current issue, is there any ETA for it, or we just shouldn't wait for that feature?

**Comment by christianbundy** [comment]
I'm frustrated by the lack of communication regarding the future of Docker Hub, but it's becoming clear in this issue (and many others) that Docker Hub is being deprecated in favor of Docker Cloud. The responsible thing to do would be to close this issue as "wontfix" and telling people to migrate, but it sounds like the Docker team is using the phrase "this is available in Docker Cloud" and leaving all of these issues open.

@jangorecki I don't work for Docker, but I would recommend against waiting for *anything* in Docker Hub. I don't mind the fact that Docker Hub is on its way out, but the lack of transparency is disheartening.

**Comment by micahwedemeyer** [comment]
👍

**Comment by elcodedocle** [comment]
+1

**Comment by RichardSGN** [comment]
+1

**Comment by toschneck** [comment]
unfortunately the docker-cloud builds are pretty unstable, so also a :+1:  from me! 
Especially if you get forced by the Docker brand guidelines https://www.docker.com/brand-guidelines to rename your github repository, you currently have no option to do this without loss of all your docker-hub repository stars and comments :disappointed:

**Comment by rafaelstz** [comment]
+1

**Comment by t3chn0m4g3** [comment]
+1

**Comment by Arno0x** [comment]
+1

**Comment by rgerkin** [comment]
+1

**Comment by pkennedyr** [comment]
Support for change source project of an automated build is currently available in Docker Cloud. We encourage you to try out [Docker Cloud](https://cloud.docker.com) as this is where you will find support for this and [many](https://forums.docker.com/t/docker-cloud-release-notes-11-8-2016/24537) [other](https://forums.docker.com/t/docker-cloud-release-notes-11-16-2016/24922) autobuild features.

Also, marking this thread as `won't fix` since product development is currently focused on Docker Cloud: https://forums.docker.com/t/future-updates-on-docker-hub-docker-cloud/20498

**Comment by michaelmior** [comment]
To clarify how this works (since I just did it for one of my own projects), here are the steps:

1. Log on to Docker Hub and under the Build Settings for the appropriate repository, uncheck " When active, builds will happen automatically on pushes."
2. Log on to Docker Cloud.
3. Under "Cloud Settings" (left menu) click the plug next to GitHub to authenticate.
4. Back on Docker Cloud, go to the Repositories section (left menu).
5. Select the same Docker repository you want to build (which should already exist).
6. Under the Builds tab, select "Configure Automated Builds"
7. Select the new repository and branch from GitHub using the dropdown menus.
8. Select "Build on Docker Cloud's infrastructure" and pick any node type.
9. Click "Save and Build"

Now you're done and the image should be built from the new GitHub repository.

**Comment by crayfishx** [comment]
I followed the above steps outlined by @michaelmior (thanks for that!).   Although the image is now building from the correct source repo there is still an issue with some metadata on the Docker hub site.  https://hub.docker.com/r/crayfishx/jerakia/ was moved from the GitHub repo crayfishx/jerakia-docker to crayfishx/jerakia - the build is working but there are two issues....

* The "source repository" link on the main page still points to the old GitHub repo
* Clicking "build details" and the latest build shows the old Dockerfile and build details despite the actual image being correct

Anyone know what I need to do to get Docker Hub to "forget" the old builds and repo?

Thanks

**Comment by gdvalderrama** [comment]
@mghazizadeh Yes, you can change the repository in docker cloud, but I can't change the service (eg: I can't change the source from bitbucket to github).

**Comment by vveider** [comment]
Problem still exists.

**Comment by petk** [comment]
I understand that there are a lot of old services needed to be maintained but coming from the docs where it says that the hub.docker.php is the main Docker public registry and not having any advanced features there anymore is inconsistency and strange approach. Images are still pulled from hub.docker.com...

Plus not to mention, stars are gone when recreating the repository on hub.docker.com :)

**Comment by kjeldflarup** [comment]
@petk There is a possibility to create a new image, and then change Dockerfile for the current to
```
from newimage:tag
```

**Comment by vveider** [comment]
@kjeldflarup - that's not it, unfortunately.

**Comment by olivierdalang** [comment]
@crayfishx Did you find a way to change the link to the source repo and the dockerfiles details ?

**Comment by philippgille** [comment]
A few weeks ago there has been the announcement that Docker Cloud and Docker Store would now be part of Docker Hub: https://blog.docker.com/2018/12/the-new-docker-hub/

But it seems that it's *still* not possible to change the underlying GitHub repo of a Docker repo. I'm currently looking on `https://cloud.docker.com/repository/docker/<user>/<repo>/hubbuilds`.

@pkennedyr: You closed this issue [two years ago](https://github.com/docker/hub-feedback/issues/313#issuecomment-265835328). Maybe you can reopen it because according to the blog post Docker Hub is now the focus of development and the feature is *really* useful?
