### ISSUE TITLE
tag list not well sorted or easy to find in large list

### ISSUE THREAD

**Issue by cpuguy83** [docker/hub-feedback#316]
The tag list, especially with many tags, is not sorted very well (especially with version strings such as 1.2.0, 2.0.1, etc).
The list is also very hard to read in general with a long list.

Here's a screenshot from the official registry image tag list:

![screen shot 2015-08-27 at 9 31 39 am](https://cloud.githubusercontent.com/assets/799078/9521762/b3e27914-4c9e-11e5-9809-622e24768149.png)

**Comment by posita** [comment]
Dup. of #185?

**Comment by cpuguy83** [comment]
Seems so, thanks!
