### ISSUE TITLE
No way to change company name in the billing info

### ISSUE THREAD

**Issue by trombka** [docker/hub-feedback#317]
I made a typo in the company name when entering the billing info. It seems there is no way to change it.

**Comment by ChristopherBiscardi** [comment]
@trombka Please contact support@docker.com for account renaming.

**Comment by ChristopherBiscardi** [comment]
ah, I think I misread this. ping @nhsiehgit re: billing info Company Name.

**Comment by nhsiehgit** [comment]
related to #311

**Comment by nhsiehgit** [comment]
Sorry for the late response, but this should now be resolved. 
@trombka would you be able to confirm?

**Comment by nhsiehgit** [comment]
Closing this issue now
