### ISSUE TITLE
upgrade plan confirmation

### ISSUE THREAD

**Issue by trombka** [docker/hub-feedback#318]
It would be nice to be asked for a confirmation when clicking the upgrade plan link. I have just paid $7 just for checking if I would be able to alter the company name when making new payment.

**Comment by nhsiehgit** [comment]
Agreed, upgrading/downgrading/changing subscriptions should not be an immediate response and should require confirmation.

bumping priority on this one.

**Comment by nhsiehgit** [comment]
@trombka btw sorry, you should now have an extra $7 credit on your account. Currently we are working on a way for users to update their billing email/company etc. If you want to update your billing account information for now you can contact our support team.

Sorry there isn't any easier way at the moment but we will hopefully have that ability available soon!

**Comment by nhsiehgit** [comment]
this should be resolved now, closing.
