### ISSUE TITLE
Markdown

### ISSUE THREAD

**Issue by ChristopherBiscardi** [docker/hub-feedback#320]
- [x] code blocks
  - #312 
  - https://github.com/docker/hub-beta-feedback/issues/124#issuecomment-127434597
- [ ] tables
  - #88 
- [x] font sizes for headings doesn't match up with h1-h6
  - #225 
- [x] http links are not rendered
  - #195

**Comment by ypid** [comment]
Also, Docker Hub should ignore HTML comments in Markdown: https://hub.docker.com/r/jchaney/owncloud/

**Comment by ChristopherBiscardi** [comment]
@ypid Can you be more specific about the behavior you're suggesting?

**Comment by ypid** [comment]
Sure.

```HTML
<!-- Comment -->
```

is a valid HTML comment. Most Markdown programs ignore this so the browser also ignores it later. But the Docker Markdown translate somehow escapes it to HTML entities so that it is not a HTML comment anymore and is displayed to the user. (I updated the Docker image README so there is no comment anymore).

**Comment by mitar** [comment]
And please, remove line breaks. Compare rendering between GitHub and Docker here:


* https://hub.docker.com/r/tozd/postfix/
* https://github.com/tozd/docker-postfix

See how Docker keeps newlines from the source code.

Why Docker does not simply use the same rendered as GitHub does? See [example implementation here](https://github.com/joeyespo/grip).

**Comment by marcelstoer** [comment]
#515 is another annoying Markdown bug.

**Comment by ibnesayeed** [comment]
Please do not force line break in paragraph-like text. I personally write one sentence per line for better diffs in documentation and some people follow a fixed character boundary of 80 characters (or something similar). In either case the renderings looks ugly.

**Comment by tedder** [comment]
I have problems, but not really worth enumerating- mostly, what Markdown engine are you using? I don't mind going to the source to figure some things out, trying to figure out why Dockerhub and Github renders of the same text don't match.

The one issue I will mention is I'm unable to escape a pipe symbol in a table. There are several ways to do it, none seem to work. #585 might be related.
