### ISSUE TITLE
Build Details page lacking information

### ISSUE THREAD

**Issue by adrianhowchin** [docker/hub-feedback#329]
Currently when viewing the "Build Details" page, you have no idea which build corresponds to which Dockerfile you are building. Therefore, you have no way to know whether your build has succeeded or failed without going in to every single automated build page - painful even with a handful of builds.

To fix this, please add a new column called "Docker_Tag" which is based on the Docker tag (docker_tag) given to the automated build. It can be assumed that this will be something human-understandable, and thus make it easier to know which build refers to which Dockerfile.

**Comment by nhsiehgit** [comment]
@rrarunan @jsouth potential improvements to keep in mind for autobuilds redesign

**Comment by edmorley** [comment]
The build details page does now display this information, so I believe this can be closed :-)

**Comment by jsouth** [comment]
@edmorley 👍
