### ISSUE TITLE
No stars/downloads count on the repos?

### ISSUE THREAD

**Issue by ahmetalpbalkan** [docker/hub-feedback#332]
I can't see them on the repos?!

![image](https://cloud.githubusercontent.com/assets/159209/9667082/a68ab69c-522e-11e5-851e-c20d4b185258.png)

**Comment by ahmetalpbalkan** [comment]
Seriously this is annoying. Came here to report this again... As a user I care about how popular an image is before pulling it.


![image](https://cloud.githubusercontent.com/assets/159209/9802693/2a24731a-57d1-11e5-8e08-21a957782c8e.png)

**Comment by nhsiehgit** [comment]
agreed, triaging and adding todo

**Comment by thomasleveil** [comment]
![2016-05-15_13h18_27](https://cloud.githubusercontent.com/assets/42300/15273625/5ae74788-1aa0-11e6-901a-10661b5edaad.png)

**Comment by ahmetalpbalkan** [comment]
apparently never gonna happen
