### ISSUE TITLE
Specify multiple tags per build

### ISSUE THREAD

**Issue by Kaixhin** [docker/hub-feedback#341]
As per comments in https://github.com/docker/docker/issues/4768, it would be handy to specify multiple tags for a specific build. For example, the most common case would be assigning both a version number (e.g. "7.5") and the "latest" tag. Another use case, as seen with [Ubuntu images](https://hub.docker.com/_/ubuntu/), is to have version numbers and names.

**Comment by nathan-osman** [comment]
:+1: I'd love to see this as well

**Comment by soberstadt** [comment]
:+1: please. This would greatly increase the speed of fetching our master and staging branches instead of having to look it up all the time.

**Comment by jeroenpeeters** [comment]
+1 I also want this feature for semantic versioning.

**Comment by mikehaertl** [comment]
@ChristopherBiscardi Now over a year later, is there any news on this? It's basically the only reason that prevents me from using automated builds. In most official repos it's standard to have aliases for `latest` like `5.6.1`, `5.6` and `5` - but User repos can't do this.

**Comment by ChristopherBiscardi** [comment]
Sorry @mikehaertl I don't work at Docker anymore and thus have no insight into their priorities. As for the official repos, they are pushed manually (thus you could achieve a similar effect through any CI provider, which is what I do now).

**Comment by mikehaertl** [comment]
@ChristopherBiscardi Oh, ok. Thanks for the update. But with a CI provider I still can't use the "automated build" repo on docker hub, right? Thing is, that they privilege those in their search results. So if you don't have an automated build repo, your public repo is listed quite at the end somewhere.

**Comment by ChristopherBiscardi** [comment]
@mikehaertl I'm not sure what qualifies as "Automated Build" anymore. I just tested pushing to an [automated build repo I own](https://hub.docker.com/r/biscarch/docker-hub-webhook/tags/) under the `test` tag. It worked, so apparently you can do that (I also noticed my repo had been pushed to 2 days ago, which I definitely didn't do, so maybe base image updates are part of auto-builds now?).

Presumably you could fire a webhook when an Automated Build happens which triggers your CI platform of choice to pull the image, retag and push.

**Comment by mikehaertl** [comment]
From [here](https://docs.docker.com/docker-hub/builds/#/create-an-automated-build)

> Automated build repositories rely entirely on the integration with your code repository. You cannot push to these image repositories using the docker push command. 

In my understanding that's because an automated build should ensure, that you can always check the sources of the build. Whereas if you push a build, the user will not know if there isn't malware included etc. That's why automated build are favoured when searching on docker hub.

I don't know, why you where able to push to that repo, but given the above you shouldn't - maybe some permissive remains from your days at docker ;) ?

**Comment by pkennedyr** [comment]
Thanks for the feedback. We are in the process of adding support for specifying multiple tags from a single build, which will be available on Docker Cloud later this year.

In the meantime, a workaround for pushing multiple tags from a single build on Docker Cloud is to use a `post_push` hook with the following commands:

```
docker tag $IMAGE_NAME $DOCKER_REPO:your_extra_tag
docker push $DOCKER_REPO:your_extra_tag
```

For more information on using hooks and running custom commands between phases of the build process, please see: [https://docs.docker.com/docker-cloud/builds/advanced/](https://docs.docker.com/docker-cloud/builds/advanced/)

**Comment by mikehaertl** [comment]
@pkennedyr But will this work with automated builds? As quoted above the docs say, you can not push to an "automated build" repo.

**Comment by pkennedyr** [comment]
@mikehaertl: Yes, the above workaround will work for automated builds - the doc is being updated to reflect that pushes are allowed on automated repositories. Apologies for the confusion.

**Comment by Hronom** [comment]
Can't wait for this feature!

**Comment by pchico83** [comment]
Multi tags are already supported in both, Hub and Docker Cloud. You can specify tags separated by commas like:

          `latest,5.6`

**Comment by Hronom** [comment]
@pchico83 you mean I can do something like this:
```
{sourceref},latest
```
?

**Comment by pchico83** [comment]
@Hronom Yes, you can use any supported regexp for every tag separated by commas. 
I have tested it in Docker Cloud, but it should also work in Hub.

**Comment by Hronom** [comment]
@pchico83 awesome, thanks, I'm also look now at docker cloud...
I think some example in the `View example build rules` will be helpful for newcomers like me.

**Comment by pchico83** [comment]
@Hronom Thanks. Yes, I opened a doc issue last week to document all this.

**Comment by Kaixhin** [comment]
Any known issues with the Hub? I just tried `8.0,latest`, and got the following:  
`8.0,latest: Invalid 'name' field: Illegal Docker tag character ',' at position 4. Valid values are ^[A-Za-z0-9_][A-Za-z0-9_.-]{0,127}$`

**Comment by pchico83** [comment]
@Kaixhin Looks like it is not supported in Hub. I would recommend to switch to Docker Cloud.
https://forums.docker.com/t/future-updates-on-docker-hub-docker-cloud/20498

**Comment by Kaixhin** [comment]
@pchico83 If this is not going to be added to the Hub would you be able to add the `wontfix` label to this issue?

**Comment by pkennedyr** [comment]
Support for specifying multiple tags from a single build is now available in Docker Cloud. We encourage you to try out [Docker Cloud](cloud.docker.com) as this is where you will find support for specifying multiple tags per build and [many](https://forums.docker.com/t/docker-cloud-release-notes-11-8-2016/24537) [other](https://forums.docker.com/t/docker-cloud-release-notes-11-16-2016/24922) auto-build features.

Also, marking this thread as won't fix since product development is currently focused on Docker Cloud: https://forums.docker.com/t/future-updates-on-docker-hub-docker-cloud/20498

**Comment by MichaelSimons** [comment]
@pkennedyr, Please accept my apologies in advance if I missed something in the `Docker Cloud` documentation or something obvious.  How do you configure a single `build rule` for building multiple tags?

**Comment by pkennedyr** [comment]
@MichaelSimons To specify multiple Docker Tags from a single build rule on Docker Cloud:

1. Navigate to a automated build repository (i.e. configured with a source provider)
2. Click the `Builds` tab
3. Click `Configure automated builds`
4. In the `Build Rules` section, enter the desired tag name(s) in the `Docker Tag` field (separated by a comma without spaces)

e.g. `latest,1.1` or `{sourceref},latest`

Note: We will be updating the [Docker Cloud documentation](https://docs.docker.com/docker-cloud/builds/automated-build/) shortly to provide further context and examples of how to use this feature.

**Comment by MichaelSimons** [comment]
@pkennedyr, I was close with the syntax I was trying - I mistakenly had a space after the comma.  Little surprised the space isn't ignored.  Thanks for clarification!

**Comment by svengo** [comment]
I tried @pkennedyr `Docker Tag` field `{sourceref},latest` with my repository [svengo/tor](https://hub.docker.com/r/svengo/tor/):

![screenshot-2017-12-2 docker cloud](https://user-images.githubusercontent.com/2502366/33516501-17e980c6-d774-11e7-98a9-8f927d7d0f8d.png)

...but the build failed:

    Successfully built 7cffb47442d4
    Successfully tagged svengo/tor:0.3.1.9
    Pushing index.docker.io/svengo/tor:0.3.1.9...
    Push failed. Attempt 2 in 60 seconds.
    Push failed. Attempt 3 in 60 seconds.
    Push failed. Attempt 4 in 60 seconds.
    Push failed. Attempt 5 in 60 seconds.
    {u'message': u'tag does not exist: svengo/tor:latest'}
    ERROR: Build failed: {u'message': u'tag does not exist: svengo/tor:latest'}
    ERROR: Build failed with exit code 2
    ERROR: Build in '0.3.1.9' (645a86de) failed in 0:13:55

**Comment by klakegg** [comment]
I tried using this feature:

Docker Tag Name: 
`{sourceref},{sourceref}-busybox-latest` 

Error:
`{sourceref},{sourceref}-busybox-latest: Invalid 'name' field: Illegal Docker tag character ',' at position 12. Valid values are ^[A-Za-z0-9_][A-Za-z0-9_.-]{0,127}$`

The documentation is quite clear regarding use of comma to support multiple tags per build.

Please advice.

**Comment by WoZ** [comment]
See the same issue

**Comment by bananajamma** [comment]
Still doesn't work with a comma; the documentation states it should.

**Comment by nSimonFR** [comment]
As I was have having the same problem, I have switched to [Docker Cloud](https://cloud.docker.com/); no issue since.

**Comment by kelson42** [comment]
@pkennedyr Why this ticket is still closed if if it obvious it does not work on cloud.docker.com? I have "latest,1.6" and I get the infamous `Invalid 'name' field: Illegal Docker tag character ',' at position 7. Valid values are ^[A-Za-z0-9_][A-Za-z0-9_.-]{0,127}$`

**Comment by mark-r-m** [comment]
Docker Hub and Docker Cloud should both seamlessly support multiple tags, like "latest,{\1}.{\2}.{\3},{\1}.{\2},{\1}" - that's the most common use case for both! I understand the Cloud is where Docker want us to go, but for those of us staying on Hub, you should support this too.

**Comment by mserajnik** [comment]
This does not to seem to work on Docker Cloud as advertised either.

Trying to save an automated build with the Docker tag set to something like `{sourceref},latest` just keeps `{sourceref}` for me without showing any error.

**Comment by samhwang** [comment]
Just tested this again today and this feature is not on Docker Cloud, as advertised. I set up an automated build rule, with source branch `master`, with result tags `7.3` and `latest`. When I click save, it just saves to `7.3`, without popping up any error messages at all.

Settings:
![image](https://user-images.githubusercontent.com/4188758/66966858-6af4d100-f0ca-11e9-9a7b-e67ded8cb74e.png)

Saved:
![image](https://user-images.githubusercontent.com/4188758/66967228-f28f0f80-f0cb-11e9-95ee-41b74c523e67.png)

**Comment by samhwang** [comment]
Just tested this again today and this feature is not on Docker Cloud, as advertised. I set up an automated build rule, with source branch `master`, with result tags `7.3` and `latest`. When I click save, it just saves to `7.3`, without popping up any error messages at all.

Settings:
![image](https://user-images.githubusercontent.com/4188758/66967339-6af5d080-f0cc-11e9-8f0f-d54268695f1e.png)

Saved:
![image](https://user-images.githubusercontent.com/4188758/66967346-6f21ee00-f0cc-11e9-9540-9052f3109706.png)

**Comment by baztian** [comment]
For me specifying `latest,{sourceref}` works.

**Comment by mserajnik** [comment]
@baztian 

Interesting, thank you. Maybe it's the order (`latest` first)? I will give this a try myself later.

**Comment by anton-yurchenko** [comment]
For those who are still Googling, this works for me on https://hub.docker.com

<img width="1256" alt="image" src="https://user-images.githubusercontent.com/33016810/71569774-262de300-2ada-11ea-8ecc-5f3605b8bb06.png">

**Comment by ulope** [comment]
Can someone using this 'hack' confirm it still works?
Using this configuration:
![](https://ds.ulo.pe/fZF2IL2Abe.jpg)

Always fails when pushing with 
```
Successfully built a46fcc079028
Successfully tagged raidennetwork/raiden:latest
Pushing index.docker.io/raidennetwork/raiden:latest...
Push failed. Attempt 2 in 60 seconds.
Push failed. Attempt 3 in 60 seconds.
Push failed. Attempt 4 in 60 seconds.
Push failed. Attempt 5 in 60 seconds.
{u'message': u'tag does not exist: raidennetwork/raiden:v1.1.0'}
```

The missing tag is always the second one. If I switch the order of `latest` and `{sourceref}` the message complains about `latest` being the missing tag.

**Comment by HendrikRoehm** [comment]
Hi @ulope 

the problem might be with the sourceref variable. It worked for me on docker hub with
![image](https://user-images.githubusercontent.com/26203080/85380552-590edc00-b53d-11ea-9ab9-480c6ceb2b68.png)

**Comment by ulope** [comment]
@HendrikRoehm Ok thanks for the feedback. Will try that syntax.
