### ISSUE TITLE
Email URL doesn't show up properly in Hub 2.0

### ISSUE THREAD

**Issue by wzymaster** [docker/hub-feedback#342]
After Docker hub upgraded, my description format looks messed up and email url doesn't work, but it works fine before.

My source markdown description text is like below :

" 
....please send us an email (imcloud@ca.ibm.com) to be .... 
"

However, it doesn't work any more and no email url clickable link display. Please check my repo at https://hub.docker.com/r/ibmcom/db2express-c/

**Comment by nhsiehgit** [comment]
Looks like this is an issue with the Markdown generator. 
@ChristopherBiscardi will assign to you
