### ISSUE TITLE
provide per-label (tag) JSON for "docker inspect"

### ISSUE THREAD

**Issue by n0mer** [docker/hub-feedback#344]
Hi,

i use several labels in my repository (not "automated build", i build images on my own).

But, the only thing i can see for now is just image tag and image size:

![image](https://cloud.githubusercontent.com/assets/1862997/9863190/228e3b84-5b3e-11e5-9ef6-6f7e61fd8f9c.png)

Please allow somehow to see more image details. Ideally - everything that is visible from 

```bash
docker inspect image-id
``` 

command.

At minimum - please add "image id" and "last published date/time" to this table, otherwise it is barely usable.

**Comment by ChristopherBiscardi** [comment]
Consolidating to #139
