### ISSUE TITLE
Is it possible to delete an organization?

### ISSUE THREAD

**Issue by Kolyunya** [docker/hub-feedback#345]
I would not able to find an option of deleting the organization.
Is it implemented yet?

**Comment by kizbitz** [comment]
Hi Kolyunya,

This is on our roadmap but hasn't been implemented yet. 

You can track status at: https://github.com/docker/hub-feedback/issues/12

**Comment by ikourfaln** [comment]
+1

**Comment by edwardluzi** [comment]
any progress on the implementation?

**Comment by zatamine** [comment]
Not done yet ?

**Comment by cblackburn-ajla** [comment]
Seriously?!?  With all of the dozens if not hundreds of requests to delete an organization, there still is no functionality to do this on a self-service basis?  This undermines my confidence in Docker as a whole.

**Comment by febririzki461** [comment]
any update ?

**Comment by ahsansher** [comment]
any update ? :(
