### ISSUE TITLE
Fail when repo doesn't exist on push

### ISSUE THREAD

**Issue by cpuguy83** [docker/hub-feedback#346]
See docker/docker#5237

Basically, push always creates a new, public repo if one does not exist.
This can be dangerous.
It would be good to have a way to make sure either a repo isn't automatically created or is created as a private repo.
Maybe gated by a setting on the hub account/org?
New accounts can have this on by default for greater protection w/o breaking existing workflows for older users.

**Comment by ahmetalpbalkan** [comment]
+1, I realized this during #307 as well.
