### ISSUE TITLE
Bad markdown rendering in repo descriptions

### ISSUE THREAD

**Issue by ahmetalpbalkan** [docker/hub-feedback#349]
This one is from https://hub.docker.com/r/microsoft/aspnet/:
> 
![image](https://cloud.githubusercontent.com/assets/159209/9917674/d6effd80-5c77-11e5-8cc9-a18cc8c49346.png)

and this one is from GitHub:

> ![image](https://cloud.githubusercontent.com/assets/159209/9917664/bf66155a-5c77-11e5-9a8b-c54b446e5753.png)

The badge images are listed on separate lines. So that's not exactly GFM.

**Comment by fostertheweb** [comment]
+1 and for fenced code blocks it doesn't add space below the code block like GitHub does.

Docker Hub:
<img width="170" alt="screen shot 2015-09-23 at 4 04 18 pm" src="https://cloud.githubusercontent.com/assets/969506/10057174/ce643362-620c-11e5-8962-c7e6e4a390ae.png">

and on GitHub, much cleaner
<img width="157" alt="screen shot 2015-09-23 at 4 04 58 pm" src="https://cloud.githubusercontent.com/assets/969506/10057182/ddcfd496-620c-11e5-8324-e92a095121c4.png">
