### ISSUE TITLE
My comments do not use my gravatar

### ISSUE THREAD

**Issue by ahmetalpbalkan** [docker/hub-feedback#350]
I have a comment here: https://hub.docker.com/r/microsoft/aspnet/

> ![image](https://cloud.githubusercontent.com/assets/159209/9917762/3fd499b4-5c78-11e5-9459-c4fb9756aec8.png)

Although my profile has an avatar, it's not used:

> ![image](https://cloud.githubusercontent.com/assets/159209/9917766/4a5fd25e-5c78-11e5-9bce-6259fdc6a886.png)

Bug?

**Comment by ChristopherBiscardi** [comment]
This was merged earlier today and is pending deploy

**Comment by kristiehoward** [comment]
Closing as this has been fixed in production. Thanks for catching this @ahmetalpbalkan

**Comment by ahmetalpbalkan** [comment]
@kristiehoward avatars are not loaded under iOS Ad Blocker Peace.. I suggest taking a look. 
![image](https://cloud.githubusercontent.com/assets/159209/9968274/6203258e-5dfc-11e5-8fe6-d11be1241fc9.png)

**Comment by kristiehoward** [comment]
@ahmetalpbalkan are you able to see your avatar in the repo description page, or is that blocked too?

![image](https://cloud.githubusercontent.com/assets/7132362/9969271/59e644c0-5e02-11e5-8248-2d27127d1944.png)

**Comment by ahmetalpbalkan** [comment]
@kristiehoward I can't tell. That username is not clickable and your UI navigation just doesnt exist on mobile. I can't even go to my profile without knowing the URL. I reported related issues to this, nav on mobile isn't bad, it just doesn't exist.
