### ISSUE TITLE
relation between "Contributed" tab and Repo Collaborators tab unclear

### ISSUE THREAD

**Issue by ahmetalpbalkan** [docker/hub-feedback#351]
If I go to https://hub.docker.com/contributed/

> 
![image](https://cloud.githubusercontent.com/assets/159209/9917792/6dcaa6f6-5c78-11e5-9900-dfbd32a172dc.png)

I am contributor on at least 2 repositories when I go to my org dashboard (https://hub.docker.com/u/microsoft/dashboard/)

> ![image](https://cloud.githubusercontent.com/assets/159209/9917812/832304c6-5c78-11e5-89dc-d62bb32eb3ef.png)

but they're not listed here. Why?

**Comment by nhsiehgit** [comment]
hey @ahmetalpbalkan 

So the contributors tab is populated when you've been added as a collaborator to a repository (via collaborators tab). So it's independent of whether you've built/pushed a repo or not.

I'm going to update this ticket to reflect that this flow is currently unclear.

**Comment by ahmetalpbalkan** [comment]
@nhsiehgit I'm added as a collaborator, but if I go to the Contributors tab, I don't see these repos. That's still not clear to me.
