### ISSUE TITLE
500 internal server error updating billing details

### ISSUE THREAD

**Issue by orlade** [docker/hub-feedback#353]
I'm trying to change the card details associated with my account, and when I submit the form I receive the error:

```
PUT https://hub.docker.com/v2/billing/account/urbanetic/ 500 (INTERNAL SERVER ERROR)
p.end @ client.js:976
d @ Billing.js:69
u.default.series.i.Billing.updateBillingInfo.recurly_token @ updateBillingInformation.js:39
(anonymous function) @ async.js:689
r @ async.js:265
W.forEachOfSeries.W.eachOfSeries @ async.js:284
x @ async.js:688W.series @ async.js:710
(anonymous function) @ updateBillingInformation.js:37
(anonymous function) @ recurly.js:2
(anonymous function) @ recurly.js:1
window.(anonymous function) @ recurly.js:1
(anonymous function) @ token?first_name=…:1
```

**Comment by ChristopherBiscardi** [comment]
Thanks for reporting!

ping @nhsiehgit

**Comment by nhsiehgit** [comment]
Thanks, was able to repro and are working on a fix!

**Comment by nhsiehgit** [comment]
hey @orlade would you be able to confirm whether this is still an issue for you?

**Comment by orlade** [comment]
Yep. It doesn't highlight any errors in the form, the whole thing just goes red. The error message is "There was an error updating your contact information. Please check your information and try again." All my details are fine. I am in Australia, if that affects anything.

**Comment by orlade** [comment]
FYI this appears to be fixed now. Resubscribed!
