### ISSUE TITLE
Manually kill an automated build

### ISSUE THREAD

**Issue by Kaixhin** [docker/hub-feedback#355]
There is currently no way to stop an ongoing build, which may have been triggered by accident, or deemed unnecessary for some other reason. The functionality for manually killing a build exists already, but is only for internal use at the moment.

**Comment by eastlondoner** [comment]
+1

**Comment by sagivo** [comment]
+1

**Comment by jakirkham** [comment]
+1

**Comment by hugobessa** [comment]
+1

**Comment by callbacknull** [comment]
+1 This would be a very nice to have

**Comment by skemb321** [comment]
+1

**Comment by avoinea** [comment]
+1

**Comment by jonasrauber** [comment]
+1

**Comment by completerevolution** [comment]
+1   (Thought this would have been built-in from the start?)

**Comment by rrarunan** [comment]
We are working on this one. Stay tuned for an update soon.

**Comment by pkennedyr** [comment]
We are happy to announce that build cancelation is now available on Docker Hub.

To cancel a build, navigate to the Build Details tab of a repository and click the Cancel button for a given queued or in progress build.
