### ISSUE TITLE
Trigger a Build for a specific tag

### ISSUE THREAD

**Issue by Kaixhin** [docker/hub-feedback#356]
The web interface's "Trigger a Build" button triggers builds for all tags - in the Build Settings tab it would be useful to be able to build a specific Docker tag rather than all of them. This would fit into the existing UI and be more convenient than sending a POST when debugging a specific build.

**Comment by yurtaev** [comment]
:+1:

**Comment by jakirkham** [comment]
:+1:

**Comment by Kaixhin** [comment]
Looks like this has been added recently - fantastic! Closing.

**Comment by dciccale** [comment]
Now let's bring this to webhooks 😀  #372

**Comment by JonasGroeger** [comment]
@Kaixhin Really? `ubuntu:latest` still does not work.

**Comment by Kaixhin** [comment]
@JonasGroeger This is for a part of the web interface in the Build Settings tab - only available for images that you own. See below for a screenshot for one of my images with 4 tags, with 4 corresponding build buttons.

<img width="1267" alt="screen shot 2016-12-15 at 14 45 32" src="https://cloud.githubusercontent.com/assets/991891/21228309/3316946a-c2d5-11e6-889b-6c6c3e864dd4.png">

**Comment by JonasGroeger** [comment]
Ah. I meant to have "Linked Repositories" with tags.
