### ISSUE TITLE
Sometimes the Create button on hub.docker.com fails to work. 

### ISSUE THREAD

**Issue by Leopere** [docker/hub-feedback#360]
In certain browsers namely Safari Version 8.0.8 (10600.8.9) and google chrome Version 45.0.2454.93 (64 bit) the Create button fails to be clickable. 

![http://i.imgur.com/ayiJMih.png](http://i.imgur.com/ayiJMih.png)

**Comment by sjoeboo** [comment]
+1, having this issue currently, i've tried chrome, safari and firefox. all end up returning a 403 when i look with dev-tools upon clicking.

**Comment by chamunks** [comment]
Mine is just not letting me click it at all.  I basically have to kind of play with spamming TAB and then ENTER until it works.  Launch it inside of "Private Browsing Mode" and try there etc.

**Comment by nhsiehgit** [comment]
Intersting. Thanks for reporting this. we will take a look and see what could be causing this.
