### ISSUE TITLE
Missing Tags

### ISSUE THREAD

**Issue by kizbitz** [docker/hub-feedback#361]
The 'Tags' tab is not displaying all existing tags. (Can pull all tags with CLI)
Live example: https://hub.docker.com/r/fiware/orion/

Build settings:
<img width="1003" alt="screen shot 2015-09-23 at 8 14 08 am" src="https://cloud.githubusercontent.com/assets/201920/10044741/47d85314-61cb-11e5-8a4f-e38c5f1b10ff.png">

Tags Tab:
<img width="355" alt="screen shot 2015-09-23 at 8 14 31 am" src="https://cloud.githubusercontent.com/assets/201920/10044748/503a48be-61cb-11e5-9739-81f24a180954.png">

Multiple users have reported this issue.

**Comment by fgalan** [comment]
It happened again, in the same cited https://hub.docker.com/r/fiware/orion/, for tag 0.25

**Comment by fgalan** [comment]
It happened again, in the same cited https://hub.docker.com/r/fiware/orion/, for tag 0.26

**Comment by fgalan** [comment]
It happened again, in the same cited https://hub.docker.com/r/fiware/orion/, for tag 0.26.1.
