### ISSUE TITLE
Unable to link Docker Hub and GitHub accounts via oAuth "authorize"

### ISSUE THREAD

**Issue by Pysis868** [docker/hub-feedback#362]
I wanted to set-up account access for the Ducker Hub to automatically interact with my repositories requesting automated builds, and ran into a problem where I was unable to proceed with linking my accounts.

Here are the pages I went through:
 - https://docs.docker.com/docker-hub/builds/
 - https://docs.docker.com/docker-hub/github/
 - https://hub.docker.com/account/authorized-services/github-permissions/#

I went to link my Docker Hub account with my GitHub account via the "Public and Private" method.
It takes me to this page where I receive a 404, and I have tried multiples times today:
https://github.com/login/oauth/authorize?client_id=&scope=repo&state=r0e8kt9

I sent a support request to GitHub first, since that publicly document API URL for oAuth was consistent with what Docker Hub was using, along with a couple of parameters.
I received a response that the "client_id" parameter is missing a value, which should be causing the error.
I don't think a 404 Not Found HTTP Response Code may not be the best for the GitHub API to return, a 400 Bad Request may be better, but this does seem to be an issue with the Docker Hub code initiating the request.

For reference, I found issue #289 as well, but that appears to be a different problem, either before or after my current failure step.

**Comment by rrarunan** [comment]
@Pysis868 Try this: https://hub.docker.com/account/authorized-services/

Use that page and then click on `Link Github` button and see if that works for you.

**Comment by Pysis868** [comment]
I have now successfully linked GitHub with my account now. Thanks!

**Comment by GowrishankarGeek** [comment]
Hello,
what is procedure for SSO(single sing-on) with docker? please help me
