### ISSUE TITLE
Docker Hub comment pagination with many comments broken?

### ISSUE THREAD

**Issue by M4urice** [docker/hub-feedback#364]
1. The Docker Hub comment pagination only allows to jump to the next page of comments and starts at the oldest comment. For a popular image it means I would have to click **very** often to reach the newest comments.
2. The pagination never stops (see the screenshot, 66 comments but comment page 100).

Example:
https://hub.docker.com/r/library/postgres/
![screenshot 2015-09-24 17 32 31](https://cloud.githubusercontent.com/assets/1615089/10077849/75d9c988-62e2-11e5-86bf-6eddc9db725a.png)

**Comment by rrarunan** [comment]
Related to https://github.com/docker/hub-feedback/issues/169.

**Comment by tianon** [comment]
The "Comments" functionality appears to now be completely gone from Docker Hub, which renders this issue obsolete! :tada: :heart:
