### ISSUE TITLE
'Link Bitbucket' link broken

### ISSUE THREAD

**Issue by Hildebrand** [docker/hub-feedback#365]
When trying to setup an automated build from Bitbucket, and consequently clicking on 'Link Bitbucket' on the 'Linked Accounts & Services' page, a new tab opens with a blank page (about:blank) instead of the expected link setup page.

![image](https://cloud.githubusercontent.com/assets/302236/10097411/2b2ad2d2-6379-11e5-94c7-d92cf42387d8.png)

Operating system: Windows 8.1
Browser and Browser version: Google Chrome 45.0.2454.93 m en Mozilla Firefox 42.0a2
URL for the page in question.: https://hub.docker.com/account/authorized-services/
The rough date and time the error occurred: 25-09-2015 11:30 UTC+1
Your hub username: ritense, company account name: ritensebv

**Comment by ThomasRedstone** [comment]
Is it possible to get the URL that this link leads to?
The GitHub goes to:
https://hub.docker.com/account/authorized-services/github-permissions/
But changing github to bitbucket in the URL doesn't work.

**Comment by ThomasRedstone** [comment]
It seems the path you follow to link Docker Hub and Bitbucket is important.
If you go to Settings, Linked Accounts and Settings, then click Link Bitbucket, it works fine.
But if you go via Create, Create Automatic Build, and then attempt to link Bitbucket, it links to about:blank.

**Comment by Jerredr** [comment]
I'm having the same issue. However, after adding the repo (following the path described by @ThomasRedstone) I can add it, but as soon as I click on 'Create automated build', the Bitbucket account is removed again from DockerHub. I can still see the OAuth token in my Bitbucket account.

**Comment by bobo** [comment]
6 months for an issue with a broken link and it is still broken?

**Comment by rrarunan** [comment]
@bobo let us know what issue you are experiencing, this issue should be closed as fixed (i just tested myself) unless we believe you are having the _exact_ same one.

**Comment by rrarunan** [comment]
Closing this until I hear otherwise.

**Comment by Jerredr** [comment]
This is still an issue for me. Clicking the Bitbucket logo just reloads the page for me.

**Comment by xuey90** [comment]
Hi @rrarunan this still happens for me. Here's a quick screen recording https://www.dropbox.com/s/37ljtqvevphb9ag/dockerhub_bb.mov?dl=0

**Comment by pkennedyr** [comment]
Hi @xuey90: Can you confirm that your Bitbucket account is not already linked to a different Docker account? Currently, the same GitHub/Bitbucket account can only be linked to a single Docker account, which we have an internal task to improve the UX for.

**Comment by styfle** [comment]
@pkennedyr I can confirm.

I just created a new Docker Hub account and a new BitBucket account and I have the same issue today. Clicking the link BitBucket image just opens a new Docker Hub tab, the same as @xuey90 shows in the video.

I tried to sign into bitbucket first, then sign into docker hub, then link.
I also tried to sign out of bitbucket, then sign into docker hub, then link.

Both fail in the same way with no error message.

Do you keep any error logs? This is clearly still an issue.

**Comment by styfle** [comment]
My workaround was visiting `https://hub.docker.com/add/automated-build/<MY_USERNAME_HERE>/bitbucket/orgs/` and then clicking the button again a few times while I was already logged into BitBucket.

**Comment by jayenashar** [comment]
@styfle's last comment worked for me.  otherwise it was opening a new tab but showing the same page (https://hub.docker.com/account/authorized-services/ ).  After giving docker authorization, I got this error:

`Error linking your account to bitbucket. Please ensure, you do not have the same bitbucket account linked to another dockerhub account.`

I've never used docker hub before so I'm sure it's not linked to another account.  I checked https://bitbucket.org/account/user/<bitbucket username>/api and docker hub does have access.
