### ISSUE TITLE
Automated build option: Detect and build all branches of a git repo [feature-request]

### ISSUE THREAD

**Issue by johnw** [docker/hub-feedback#366]
# Story

I have a git repo with branches master and develop.  I create a new automated build and link it to this git repo, indicating that I'd like to use the build-all-branches feature.  At automated build creation, two images would be created for each branch and tagged with the branch name.   Later on if I add a WIP_FEATURE1 branch and commit to it, the commit would be picked up by hub, and a new image would be built and added with tag WIP_FEATURE1.    

When enabling this option, it might even be possible to configure a few things like:
- How to derive tag name from branch name
- Branch name excludes / includes ("exclude WIP_*")
- Delete image with tag x if branch x is deleted
- Dockerfile name for all branches will be...
# Justification

One use case:  CI for ad hoc WIP_ branches with several developers working on them.  (Where images are used to run test suite, start up the application and take screenshots in multiple devices and browsers and things like that.)

**Comment by sairghan** [comment]
Hey John! Did you find a solution to this problem? I am facing the same issue. It would be of great help.

**Comment by dendisuhubdy** [comment]
Yes I wish this exists too
