### ISSUE TITLE
No UI to remove tags excluded by automated build repos

### ISSUE THREAD

**Issue by ahmetalpbalkan** [docker/hub-feedback#368]
Repo: https://hub.docker.com/r/microsoft/aspnet/tags/
Aforementioned tag: `nightly`

I removed this tag on Apr 30, 2015 (149 days ago): https://github.com/aspnet/aspnet-docker/pull/52

As you can see below it's not even in our build list (and we had builds ever since): 
> ![image](https://cloud.githubusercontent.com/assets/159209/10121463/73d80c6a-64a1-11e5-8e03-968ad9243cd6.png)

Fast-forward 5 months, this tag is still listed in the new Docker Hub (I think it wasn't there in the old one). **This is confusing users** and I'm getting questions about this and I have no way of removing this. This bug is pretty pad, can someone help me getting rid of that tag?

> ![image](https://cloud.githubusercontent.com/assets/159209/10121469/b22d55e2-64a1-11e5-8602-77742edf6913.png)

not to mention, ofc image sizes are wrong, too. That's confusing users even more...

**Comment by kencochrane** [comment]
@ahmetalpbalkan when you said you removed it, did you remove just from the build settings, or did you delete the tag from the hub UI?

**Comment by ahmetalpbalkan** [comment]
@kencochrane I am not sure what deleting tag from the Hub UI means. Can you delete tags without removing them from build settings? The screenshots above should be explaining the issue, something that's not in the build settings list is still listed among the tags.

**Comment by kencochrane** [comment]
@ahmetalpbalkan on the old hub there was a way to delete the docker tag, not sure if we have it on the new hub ( @ChristopherBiscardi ?). If you remove them from the build settings, it doesn't delete the docker tags, it just stops new builds from happening and pushing to those tags.

**Comment by ahmetalpbalkan** [comment]
I see no such option to delete the tag in the web interface (I've never seen it in the old Hub either). :|

**Comment by kencochrane** [comment]
@ahmetalpbalkan I know it was there in the old hub (I worked on it :) ) but it was pretty hidden, so not surprised you didn't see it. I'll ping @ChristopherBiscardi to find out where it is in the new hub, if it is there, if not, when it will be added. 

Looks like there is another issue for deleting tags here: https://github.com/docker/hub-feedback/issues/68

**Comment by sbasyal** [comment]
@ahmetalpbalkan @kencochrane There was this option to delete the tags in Non-Automated Repositories but not in Repositories with Automated Builds in Old Hub. In the new Hub, currently we don't have an option to delete the tags at all.

**Comment by kencochrane** [comment]
@sbasyal thank you for the clarification.

**Comment by ahmetalpbalkan** [comment]
I should note that this repo has always been an automated repo.

**Comment by ahmetalpbalkan** [comment]
@sbaysal my emails to support@ are getting lost. Sending again:

Can you please delete the following tags

- nightly
- vs-1.0.0-beta4
- coreclr-1.0.0-beta5-11624

**Comment by ahmetalpbalkan** [comment]
Can somebody please help out here? We're stuck with the ancient tags and this is limiting us from deprecating certain tags from the existing repo as well... Are we ever going to have this Delete Tags feature back on Docker Hub? Any updates are appreciated.

**Comment by sbasyal** [comment]
@ahmetalpbalkan Sorry your message got lost. Following tags are deleted:
microsoft/aspnet:nightly
microsoft/aspnet:vs-1.0.0-beta4
microsoft/aspnet:coreclr-1.0.0-beta5-11624

If you want to delete more tags, send an email to support@docker.com.

**Comment by ahmetalpbalkan** [comment]
thanks @sbasyal.

**Comment by ahmetalpbalkan** [comment]
@sbasyal we just got more tags deleted. I appreciate if you can help out deleting these as well.

* microsoft/aspnet:1.0.0-beta1
* microsoft/aspnet:1.0.0-beta2
* microsoft/aspnet:1.0.0-beta3
* microsoft/aspnet:1.0.0-beta4

also changing issue title to reflect the root cause.

**Comment by sbasyal** [comment]
Hi @ahmetalpbalkan,
Sorry I missed your request. The tags you mentioned are deleted now.
When you have any request/issue, please send it to support@docker.com, so that it will be tracked through our ticketing system.

**Comment by nhsiehgit** [comment]
ability to delete tags has now been added to the hub

**Comment by ahmetalpbalkan** [comment]
Awesome! Thanks.
On Fri, Dec 4, 2015 at 12:11 PM Nathan <notifications@github.com> wrote:

> ability to delete tags has now been added to the hub
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/docker/hub-feedback/issues/368#issuecomment-162069854>
> .
>
-- 
—Ahmet Alp Balkan
