### ISSUE TITLE
webhook per branch

### ISSUE THREAD

**Issue by dciccale** [docker/hub-feedback#372]
dockerhub is able to build images from multiple branches, however i would like to be able to run a webhook when a specific branch is built.

case:

branch: master
branch: dev

1) push to github/dev branch, trigger docker build from github with
 `'{"source_type": "Branch", "source_name": "dev"}'`
2) **only after dev branch** image build is done, trigger webhook `dev-webhook`

i am not aware if this is possible right now

thx in advance

**Comment by n8io** [comment]
+1

**Comment by jakirkham** [comment]
:+1: Would be nice to see this for tags too. Also, related ( https://github.com/docker/hub-feedback/issues/356 ).

**Comment by dciccale** [comment]
any news? I really need this. how can I help?

**Comment by Patricol** [comment]
Unsure if this was the case before, but a [webhook's payload](https://docs.docker.com/docker-hub/webhooks/#example-webhook-payload) can be used to determine what branch was built; which reduces the need for this.
