### ISSUE TITLE
My URL has disappeared

### ISSUE THREAD

**Issue by bboreham** [docker/hub-feedback#376]
In https://hub.docker.com/r/weaveworks/weave/, the URL "http://weave.works" is there in the Full Description source, but not in the rendered output.

Is there some prohibition on http URLs?  I couldn't find any docs stating what is acceptable in that field.

**Comment by kristiehoward** [comment]
This has to do with our markdown rendering, and the fix is pending deploy.

**Comment by ChristopherBiscardi** [comment]
Deployed.

<img width="846" alt="screenshot 2015-10-05 23 22 04" src="https://cloud.githubusercontent.com/assets/551247/10301505/ef525a40-6bb7-11e5-89e8-ab80bd4bc968.png">
