### ISSUE TITLE
Create Repository: Editing text field moves cursor to end of text

### ISSUE THREAD

**Issue by donpark** [docker/hub-feedback#377]
Steps to reproduce:

1. Open "Create Repository+" dialog.
2. Enter some text into any text field.
3. Select anywhere in the middle of any text field and start typing some characters.
4. Notice that only first character got inserted in the middle and that the rest ended up at the end of the text field.

**Comment by pointbit** [comment]
Happens on Ubuntu and Windows using Firefox 41.0.1

**Comment by kenny1986** [comment]
verified on Chrome, Firefox and Safari

**Comment by kristiehoward** [comment]
Closing as this is fixed in production
