### ISSUE TITLE
login password autofill does not work with chrome

### ISSUE THREAD

**Issue by phemmer** [docker/hub-feedback#386]
Since we seem to be tracking the login autofill issues separately for each browser/password manager, I'm creating one for chrome. The others are #93 (lastpass), #182 (1password), #189 (safari).

In the current state, Chrome does not even offer to save the username/password on login.
Tested with Chrome versions 42.0.2311.90 and 45.0.2454.85

**Comment by mzedeler** [comment]
:+1: I'm surprised how this can be out of beta when it isn't working. Sorry if I sound blunt, but not letting users log in with site specific passwords is pretty basic.

**Comment by bamarni** [comment]
Is it still an issue? It's working fine for me (chrome 48.0.2564.116), however it doesn't with safeincloud plugin, just opened #593.

**Comment by bf** [comment]
Login on docker hub does not prompt for password storage, which is very inconvenient.

**Comment by bamarni** [comment]
what do you mean exactly? Are you on chrome? I see it after login

<img width="610" alt="screen shot 2016-03-02 at 10 35 44" src="https://cloud.githubusercontent.com/assets/1205386/13456370/22ad93b2-e063-11e5-96dc-027abd2b983d.png">

**Comment by mzedeler** [comment]
Well that's not working here.

I'm using 48.0.2564.82 (Official Build) (64-bit) on Ubuntu Mint.

Here is a [video](https://github.com/docker/hub-feedback/files/156198/doesntwork.ogv.gz) that demonstrates the problem. Whats odd is that my browser remembers some password, but not the correct one.

**Comment by bf** [comment]
Thanks for posting the video @mzedeler
