### ISSUE TITLE
Are build details and tags suffering a limit on data fetch?

### ISSUE THREAD

**Issue by cusspvz** [docker/hub-feedback#388]
I've set lot of tags (approx. 315) for my [node](https://hub.docker.com/r/cusspvz/node) repo.
Problem is that I'm not seeing most recent build details, and tags aren't displayed correctly, since I can fetch some tags that aren't present.

This is a high priority issue since most users do a Tag checking instead of reading the hole repo description.

Although I've added them to repo description.

**Comment by nebuk89** [comment]
stale - closing
