### ISSUE TITLE
Automated docker build fails with exception, docker client/server API version mismatch

### ISSUE THREAD

**Issue by danderson** [docker/hub-feedback#392]
The automated builds for Pixiecore (https://hub.docker.com/r/danderson/pixiecore/) have been failing for 3 days now, throwing an exception that seems to be about client/server API version mismatch. The only log text I get is:

```
Client:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:49:29 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.3-rc4
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   9f1606a
 Built:        Fri Oct  2 23:36:50 UTC 2015
 OS/Arch:      linux/amd64
```

AFAICT, there's nothing I can do about this, it looks like an incomplete rollout to the hub infrastructure.

**Comment by dustinlacewell** [comment]
We identified the issue as being caused by a decoding error when processing your README file which contains a non-utf character. We'll be rolling out a change to better handle that in the future but for now you can mitigate by removing that character from your README.

**Comment by RongxinZhang** [comment]
+1 I'm having the same issue

**Comment by danderson** [comment]
lol
