### ISSUE TITLE
Building Pull Requests (automated builds)

### ISSUE THREAD

**Issue by jakirkham** [docker/hub-feedback#394]
It would be really great if pull requests to an automated build repo were built. This would be useful in testing and further manual validation and/or collaboration on an image. Primarily, I am thinking of GitHub here, but I suppose it would be nice to extend to other services.

**Comment by anorsich** [comment]
Is there any plans on implementing that feature? It is essential for the teams, which work based on pull requests model and would love to test docker build, before merging PR to the upstream. 
Thanks for the great service!

**Comment by pchico83** [comment]
This feature is already available in Docker Cloud, which has also support for other cool features like:
- Slack notifications.
- Streaming build logs.
- Ability to cancel and retry a build action.
- Integration with Github and Bitbucket git statuses.
Docker Cloud is integrated with your Docker Hub repositories, you will automatically see all of them when login in Docker Cloud. For more information:
https://docs.docker.com/docker-cloud/builds/automated-build/
https://docs.docker.com/docker-cloud/builds/automated-testing/
