### ISSUE TITLE
Title tags on hub.docker.com need to be more descriptive

### ISSUE THREAD

**Issue by edcottrell** [docker/hub-feedback#396]
When viewing a repo on Docker Hub, the `<title>` tag is always just "Docker Hub." This is not very helpful, especially if a user has more than one browser tab open to Docker Hub at a time. It would be much more useful to have the name of the repo in the `<title>` tag, as in "Docker Hub - somebody/somerepo."

**Comment by etelej** [comment]
+1 

I'm currently getting a blank `<title>` tag, and no `doctype` declaration

```
chief@Work:~$ curl -s https://hub.docker.com/r/jwilder/nginx-proxy/ | head -1
<html><head><meta charset="utf-8"/><title></title><meta name="viewport" content="width=device-width, initial-scale=1"/><link rel="stylesheet" href="/public/styles/main.css"/><link rel="stylesheet" href="/public/styles/font-awesome.min.css"/><link rel="stylesheet" href="/public/styles/main-0-f506d27d0bbb3327f465.css"/></head>
```

**Comment by williamboman** [comment]
+1, same as @etelej.

**Comment by ksatirli** [comment]
+1 from me, too; first thought titles were dynamically generated and my ad blocker was eating them up but that doesn't seem to be the case.

makes for a tad more work when bookmarking, too!

**Comment by xrstf** [comment]
+1, this is bad for Auto-typing my login credentials via KeePass.

**Comment by SysAlex** [comment]
+1, please add title

**Comment by leifg** [comment]
+1

This is one of the first things I noticed about. It's been reported a year ago already.

**Comment by alexQueue** [comment]
+1. I doubt it would be difficult. I'll even add it if you point me to the source code.

Look at how user unfriendly this is: 

<img width="503" alt="screen shot 2016-06-30 at 11 35 07 am" src="https://cloud.githubusercontent.com/assets/1666114/16494312/dce0739c-3eb6-11e6-8381-45ec47663f80.png">

**Comment by wuliupo** [comment]
+1

**Comment by tugberkugurlu** [comment]
yeah, this looks really bad on Google search: https://twitter.com/tourismgeek/status/773105931815153664

I was hopping that hub site was open source and I can send a PR but apparently not 😞

**Comment by pkennedyr** [comment]
Hi All, Page titles are now available on Docker Hub.
