### ISSUE TITLE
Could not reach any registry endpoint

### ISSUE THREAD

**Issue by jason-tian** [docker/hub-feedback#398]
I always get the error "Could not reach any registry endpoint" when I'm trying to pull images from my private registry. But pull public images is normal. Could anyone from dockerhub team help it?

**Comment by jeham** [comment]
+1

**Comment by mariusgrigaitis** [comment]
+1

**Comment by petrpokorny-home24** [comment]
+1

**Comment by cagataygurturk** [comment]
+1

**Comment by leonfs** [comment]
+1

**Comment by mariusgrigaitis** [comment]
This is probably closed now. Sad for no reaction from dockerhub here ;/

**Comment by leonfs** [comment]
That's why I switched to quay.io. In general is much more polished service. Better hooks, better UX, better support. I would say pretty much better everything.

**Comment by san81** [comment]
+1

**Comment by NoobTW** [comment]
+1

**Comment by williampsena** [comment]
+1

**Comment by fragro** [comment]
+1

**Comment by andrewhsu** [comment]
I had a related issue when pulling docker images from the public registry:
```
bash$ sudo docker pull busybox
Pulling repository busybox
FATA[0001] Could not reach any registry endpoint
```

Turns out I'm using an old docker-1.4.1 client:
```
bash$ docker version
Client version: 1.4.1
Client API version: 1.16
Go version (client): go1.3.3
Git commit (client): 5bc2ff8/1.4.1
OS/Arch (client): linux/amd64
Server version: 1.4.1
Server API version: 1.16
Go version (server): go1.3.3
Git commit (server): 5bc2ff8/1.4.1
```

And the public docker registry killed support for docker clients v1.5 and older as of 2015-12-15:
https://forums.docker.com/t/docker-pull-deprecation-for-for-v1-5-clients/5071

I suspect if I built an image earlier in 2015 with a `Dockerfile` like so:
```
FROM busybox
MAINTAINER nobody@example.com
```

And pushed that image to my private registry.

And then tried to pull that image from my private registry using my docker-1.4.1 client today that I would get the same error because the docker client would first try to fetch the `busybox` image.

If this is at all the same cause as you, then the solution is to upgrade to the latest docker client and the docker pull should work.

**Comment by lynic** [comment]
+1 and my local docker is 1.4.1, any workaround for this?

**Comment by san81** [comment]
@lynic docker registry killed support for docker clients v1.5   Make sure that your docker client version is  atleast above 1.5

**Comment by Vish0007** [comment]
I have seen this error "Could not reach any registry endpoint"; when I am trying to pull an Image from a repo where the requested image tag does not exist. For example 
docker pull registry-endpoint/test/testrepo:1.0
if repo "testrepo" exist but the version 1.0 does not exist I see this error.
and I get different error message if repo "testrepo" itself does not exist.

**Comment by solutionguy** [comment]
I had this problem with the package lxc-docker on Ubuntu 14.04 LTS. The version of docker that this package provides is 1.0.1 which is too old for what is needed. Hence I decided to install the package docker.io, this removed the old lxc-docker package and replaced the client version with 1.6.2. The docker pull worked fine after that. Please find below the transcript.

`aahmed@freeswitch:~$ docker pull oraclelinux
2016/06/27 12:06:18 Post http:///var/run/docker.sock/images/create?fromImage=oraclelinux&tag=: dial unix /var/run/docker.sock: permission denied
aahmed@freeswitch:~$ sudo docker pull oraclelinux
[sudo] password for aahmed:
Pulling repository oraclelinux
2016/06/27 12:06:26 Could not reach any registry endpoint
aahmed@freeswitch:~$ docker version
Client version: 1.0.1
Client API version: 1.12
Go version (client): go1.2.1
Git commit (client): 990021a
2016/06/27 12:07:08 Get http:///var/run/docker.sock/v1.12/version: dial unix /var/run/docker.sock: permission denied
aahmed@freeswitch:~$ sudo su -
root@freeswitch:~# apt-cache search docker
pidgin - graphical multi-protocol instant messaging client for X
docker - System tray for KDE3/GNOME2 docklet applications
karbon - vector graphics application for the Calligra Suite
kdocker - lets you dock any application into the system tray
docker.io - Linux container runtime
golang-docker-dev - Externally reusable Go packages included with Docker
vim-syntax-docker - Docker container engine - Vim highlighting syntax files
lxc-docker-1.0.1 - Linux container runtime
lxc-docker - Linux container runtime
root@freeswitch:~# apt-get install docker.io
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following packages were automatically installed and are no longer required:
  linux-image-3.13.0-85-generic linux-image-3.13.0-86-generic
  linux-image-extra-3.13.0-85-generic linux-image-extra-3.13.0-86-generic
Use 'apt-get autoremove' to remove them.
Suggested packages:
  debootstrap lxc rinse
The following packages will be REMOVED:
  lxc-docker lxc-docker-1.0.1
The following NEW packages will be installed:
  docker.io
0 upgraded, 1 newly installed, 2 to remove and 23 not upgraded.
Need to get 4,749 kB of archives.
After this operation, 11.5 MB of additional disk space will be used.
Do you want to continue? [Y/n]
Get:1 http://us.archive.ubuntu.com/ubuntu/ trusty-updates/universe docker.io amd64 1.6.2~dfsg1-1ubuntu4~14.04.1 [4,749 kB]
Fetched 4,749 kB in 15s (299 kB/s)
(Reading database ... 822372 files and directories currently installed.)
Removing lxc-docker (1.0.1) ...
Removing lxc-docker-1.0.1 (1.0.1) ...
docker stop/waiting
Processing triggers for man-db (2.6.7.1-1ubuntu1) ...
Selecting previously unselected package docker.io.
(Reading database ... 822333 files and directories currently installed.)
Preparing to unpack .../docker.io_1.6.2~dfsg1-1ubuntu4~14.04.1_amd64.deb ...
Unpacking docker.io (1.6.2~dfsg1-1ubuntu4~14.04.1) ...
Processing triggers for man-db (2.6.7.1-1ubuntu1) ...
Processing triggers for ureadahead (0.100.0-16) ...
ureadahead will be reprofiled on next reboot
Setting up docker.io (1.6.2~dfsg1-1ubuntu4~14.04.1) ...
Installing new version of config file /etc/init.d/docker ...
Installing new version of config file /etc/init/docker.conf ...
addgroup: The group `docker' already exists as a system group. Exiting.
docker start/running, process 6306
Processing triggers for ureadahead (0.100.0-16) ...
root@freeswitch:~# docker pull oraclelinux
latest: Pulling from oraclelinux
3690474eb5b4: Pull complete
dcf772154efb: Pull complete
befcc0fb99d3: Pull complete
Digest: sha256:a0b5fa87695152890c0b01704db1cfb124c6f8c79bc248531c94cdb8b846fbd3
Status: Downloaded newer image for oraclelinux:latest
`

**Comment by BrandonClapp** [comment]
I installed docker.io, like @solutionguy recommended and it also worked for me. I am running Ubuntu 15.04

**Comment by sadaf2605** [comment]
Had similar issues with `docker -v 1.5.x` on top of ubuntu 14.04 with vagrant and installed docker.io as @solutionguy mentioned, solved the problem.

**Comment by itskshitizsh** [comment]
This is because "Docker will gradually impose download rate limits with an eventual limit of 100 pulls per six hours for anonymous users."
Reference:
https://docs.docker.com/docker-hub/download-rate-limit/

**Comment by sjlongland** [comment]
> This is because "Docker will gradually impose download rate limits with an eventual limit of 100 pulls per six hours for anonymous users."
> Reference:
> https://docs.docker.com/docker-hub/download-rate-limit/

"for anonymous users"

```
root@host:~/docker# docker login
Login with your Docker ID to push and pull images from Docker Hub. If you don't have a Docker ID, head over to https://hub.docker.com to create one.
Username (user): user
Password: 
Login Succeeded
root@host:~/docker# docker-compose up -d
Pulling service (repo/image:tag)...
Pulling repository docker.io/repo/image:tag
ERROR: Could not reach any registry endpoint
```

So, not an anonymous user.  This is actually blocking me from testing some code in a staging environment.

**Comment by sjlongland** [comment]
> ```
> ERROR: Could not reach any registry endpoint
> ```
> 
> So, not an anonymous user. This is actually blocking me from testing some code in a staging environment.

Right, this was a PEBKAC issue _in my case_.  I had forgotten to actually push `repo/image:tag` from my workstation.  PEBKAC caused by a misleading error message: nothing in that error equated to "not found".
