### ISSUE TITLE
Change/update automated source/build repo

### ISSUE THREAD

**Issue by markoshust** [docker/hub-feedback#399]
I currently have my Docker Hub automated build source repositories on BitBucket. I'd like to change the source repositories to GitHub for better user involvement. How can one go about doing this?

**Comment by jakirkham** [comment]
At present, I think the answer is no. See this related issue ( https://github.com/docker/hub-feedback/issues/313 ). However, you could delete and then recreate the build if you aren't too attached to it in its current form.

**Comment by markoshust** [comment]
Thanks, I'll close this as a dupe of https://github.com/docker/hub-feedback/issues/313
