### ISSUE TITLE
Show build duration on build details page

### ISSUE THREAD

**Issue by ebonharme** [docker/hub-feedback#404]
We are trying to speed up our builds and I'm finding it near enough impossible to get a good idea of how long a build takes.

For a specific build, it would be really useful to get the length of time a build took, from the point where it was triggered to the point where the image was available. 

We already have the Created and Last Updated but that shows as an 'ago' time which loses its granularity very quickly.  We also have the "created_at" time stamp but not anything showing when the image was pushed fully so we can't calculate the duration reliably.  

Thanks

**Comment by hvpareja** [comment]
+1

**Comment by ricoli** [comment]
yes please, I'd like this one to exist too

**Comment by d7h** [comment]
+1

**Comment by lamlephamngoc** [comment]
+1

**Comment by pkennedyr** [comment]
Thanks for the feedback. We welcome you to try out Docker Cloud (cloud.docker.com), which includes granular build duration information on the build details page (e.g. timestamps for the specific build start time and build finish time):

![screen shot 2017-04-26 at 9 23 28 am](https://cloud.githubusercontent.com/assets/16218086/25445264/ce0a5ff2-2a62-11e7-957e-1e0f3a7217d4.png)

It also includes queue time and on the "Builds" tab, you'll find a nice visual display of build history for a given repo:

![screen shot 2017-04-26 at 9 27 46 am](https://cloud.githubusercontent.com/assets/16218086/25445283/d4604e2a-2a62-11e7-8752-d661b3deba7e.png)
