### ISSUE TITLE
Min. char 4 usernames on Docker Hub incompatible with Github names

### ISSUE THREAD

**Issue by pik** [docker/hub-feedback#405]
Hello - not sure if this is the right place for this feedback (redirected from site-link) -- but I find that the account creation insists on minimum 4 character length user-names quite problematic, since it means I cannot easily maintain the same identity from github to dockerhub (which really should be easily associated with each other). Thanks.

**Comment by oncletom** [comment]
Yeah, plus there is zero information aside of a one pixel red border to tell *what* is wrong about the username:

![screen shot 2016-11-29 at 11 46 55](https://cloud.githubusercontent.com/assets/138627/20708837/bf078eba-b629-11e6-8a26-7b392d502484.png)
