### ISSUE TITLE
After deleting an image from private repository it still remains

### ISSUE THREAD

**Issue by hbenbenishti** [docker/hub-feedback#407]
Hi,

I have for example an image: coalmineadmin/docker_server_agent with only 1 tag.
I have deleted this repository.
Then i have created a new image with a different tag successfully.
When i am using the REST API as follows:

curl -s -H "Authorization: Token $token" https://$endpoint/v1/repositories/coalmineadmin/docker_server_agent/tags

it responds with a list of old tags, that i have deleted before....
Is it a bug?
Is it a normal behaviour?

Thanks,
Haim.

**Comment by fike** [comment]
I have the same problem but a little different. My case happen a public repository that I deleted but it still visible. 


![selection_012](https://cloud.githubusercontent.com/assets/33602/10693526/8e08573a-7977-11e5-92d3-51bc8d9018ea.png)

**Comment by maricaantonacci** [comment]
I'm experiencing the same problem with repositories: they remain in deleting state...
Is there a fix for that?

Thanks
Marica

**Comment by fike** [comment]
@maricaantonacci I think not. I have two repositories the same problem. 
In my case, these happened with my repositories had been a problem to complete the Automated Build.

![selection_006](https://cloud.githubusercontent.com/assets/33602/11100957/5e94db76-889b-11e5-9a5d-dd10d6bb1430.png)

**Comment by draffensperger** [comment]
I'm experiencing the same problem. I have a script that gets the list of tags for some automation, and the tag retrieval call was taking a long time so I deleted the repository and re-added it with a single tag, but the tags API call still returns the full list of tags.

**Comment by velvetcat** [comment]
Same issue. Deleted repository doesn't appear in the list at https://hub.docker.com/ but still accessible with `docker pull`.
