### ISSUE TITLE
Enterprise sign-up country selector is limited to Canada and U.S. only

### ISSUE THREAD

**Issue by mattpatey** [docker/hub-feedback#408]
When [signing up for a server license](https://hub.docker.com/enterprise/server-starter/) I am unable to select a country other than Canada or the U.S.:

![screen shot 2015-10-19 at 14 16 03](https://cloud.githubusercontent.com/assets/554109/10577518/30aa8bd4-766c-11e5-80ea-2a1c13316c90.png)

**Comment by thaJeztah** [comment]
@mattpatey thanks for reporting this, I raised this question internally earlier this week and they informed me that they were working on this.
