### ISSUE TITLE
Email notifications not being sent for repo comments

### ISSUE THREAD

**Issue by kennylim86** [docker/hub-feedback#410]
In my notification page, https://hub.docker.com/account/notifications/ , I've picked all 3 notify options.
But when I get a comment on one of my repo, there are no email notifications.
As for the "star" and "failed AB", I do get email notification.

**Comment by outcoldman** [comment]
The same for me

**Comment by frol** [comment]
It hasn't ever worked for me, so I thought it is a "feature", but now as I see the checkbox I think it is a bug.

**Comment by Kaixhin** [comment]
Looks like this issue still exists, which is disappointing as I don't manually check tens of images every week. Would very much like to see this addressed.

**Comment by daniel-smith-kaazing** [comment]
We at Kaazing would like this, too. Any ETA?

**Comment by viossat** [comment]
Same here, I receive emails for stars but not for comments.

**Comment by Kaixhin** [comment]
Over a year on from this being logged - any response from someone at Docker? Apparently Docker Support is now only for paying customers, so I can't contact them more directly.

**Comment by tianon** [comment]
The "Comments" functionality appears to now be completely gone from Docker Hub, which renders this issue obsolete! :tada: :heart:
