### ISSUE TITLE
Can't create an Automated Build

### ISSUE THREAD

**Issue by kadishmal** [docker/hub-feedback#411]
- My Github username is: `kadishmal`
- My Hub username is: `lighthopper`
1. I go to https://hub.docker.com/add/automated-build/github/form/kadishmal/cubrid-docker/ to create an automated build for my public repo called `cubrid-docker`.
2. Fill the necessary fields:
   <img width="731" alt="screen shot 2015-10-21 at 5 09 08 pm" src="https://cloud.githubusercontent.com/assets/978004/10631087/7c8a75d6-7816-11e5-972a-ba483baa8e83.png">
3. Press `Create` button. Nothing happens.
4. Check the Dev Tools:
   ![screen shot 2015-10-21 at 5 10 24 pm](https://cloud.githubusercontent.com/assets/978004/10631120/ad85f80e-7816-11e5-9f34-46e2c0745668.png)
5. The status code is `403` and the response is:
   
   ```
   {"detail": "You do not have permission to perform this action."}
   ```

Same in Chrome and Safari.

Why can't I create an automated build for my own public repo?

**Comment by rrarunan** [comment]
@kadishmal Can you trace the steps on how you ended up on this url? Also, can you try `https://hub.docker.com/add/automated-build/github/form/kadishmal/cubrid-docker/?namespace=lighthopper` for now. I will investigate further. Thanks for reporting.

**Comment by kadishmal** [comment]
1. Searched for `docker hub automated build`.
2. Found this article https://docs.docker.com/docker-hub/builds/ explains how to create an automated build which tells to link a Github account which is explained in...
3. ... this article https://docs.docker.com/docker-hub/github/ which has a link to **create an Automated Build** https://hub.docker.com/add/automated-build/github/orgs/.
4. From there I've selected my Github account and repo.

After following your URL and filling out the form, the response is `400 Bad Request` with the error saying `{"vcs_repo_name": ["This field is required."]}`.

The POST payload is the following:

```
active: true
build_tags: [{name: "latest", source_type: "Branch", source_name: "master", dockerfile_location: "/"},…]
description: "A Dockerfile to build CUBRID Docker image."
dockerhub_repo_name: "lighthopper/cubrid-docker"
is_private: false
name: "cubrid-docker"
namespace: "lighthopper"
provider: "github"
vcs_repo_name: ""
```

Notice the `vcs_repo_name` is an empty string.

**Comment by xfallenduskx** [comment]
I ran into this issue today, what was happening for me was that I was trying to create a private automated build when I was already at my maximum private repos. Maybe a better error message to explain that you're at your maximum private repositories?
