### ISSUE TITLE
Completed builds won't push due to error: `Too Many Requests`

### ISSUE THREAD

**Issue by jakirkham** [docker/hub-feedback#413]
Seeing this on all of builds after they have completed.

**Comment by agend07** [comment]
hi - have same problem - https://hub.docker.com/r/agend07/rsync/builds/

request failed with status: 429 Too Many Requests

**Comment by AlexDultsev** [comment]
:+1: We are not able to build anything via the automated builds

**Comment by jakirkham** [comment]
It would be really nice if someone from Docker would at least look at this or at a minimum acknowledge there is a problem. "All Systems Operational" is inaccurate ( http://status.docker.com/ ).

**Comment by kencochrane** [comment]
We are aware of the problem, and are currently trying to resolve it, we will update this ticket when we know more. Sorry for the inconvenience, this might have caused. Feel free to contact support@docker.com if you have  further questions, you don't want to discuss in public.

**Comment by jakirkham** [comment]
Thanks for the update.

**Comment by jakirkham** [comment]
Alright, at least in my cases, it appears that this has gone away.

**Comment by kencochrane** [comment]
Sorry for the lack of updates, we rolled out some changes, and the problem should be resolved. If you are still seeing an issue, please contact support so we can dig in further. support@docker.com

**Comment by jakirkham** [comment]
Thanks for the update. I'm going to go ahead and close this.
