### ISSUE TITLE
Search too strict

### ISSUE THREAD

**Issue by mcandre** [docker/hub-feedback#414]
Steps to reproduce:
1. Login to Docker Hub.
2. Search for `chef` among my images.

Expected:

My `docker-chefdk` image appears in the results.

Observed:

Empty set.

**Comment by oryband** [comment]
:+1:

**Comment by oryband** [comment]
@ofir-petrushka

**Comment by ChristopherBiscardi** [comment]
@mcandre Are you referring to the "Quick Filter" on the Dashboard page:

![screenshot 2015-11-06 13 22 38](https://cloud.githubusercontent.com/assets/551247/11009061/7816df7e-8489-11e5-98ef-e38ee98e7786.png)

If so, I was unable to reproduce the issue.

**Comment by oryband** [comment]
i think this is more of an issue with private repos

**Comment by oryband** [comment]
related to #32 #198
