### ISSUE TITLE
BUG: Failed to clone repository

### ISSUE THREAD

**Issue by jakirkham** [docker/hub-feedback#416]
Got this for a public repository in one out of several active builds.

**Comment by lmikelionis** [comment]
Same here.
Two of my public repos are building ok, but one repo from same git hub account is failing with message:
Failed to clone source repository: Please ensure the correct public key is added to the list of trusted keys for this repository and the remote branch exists.

GOOD: https://hub.docker.com/r/vtech/docker-phpfpm7/builds/
GOOD: https://hub.docker.com/r/vtech/docker-phpfpm5/builds/
BAD: https://hub.docker.com/r/vtech/all-laravel-box/
BAD: https://hub.docker.com/r/vtech/docker-laravel-step2/builds/

**Comment by jyounus** [comment]
I have the same issue, anyone got any updates on this? For me it's failing because of a submodule that I have in my main Bitbucket repo.

```
Starting to clone
Cloning into 'bokyrk3hkhspby5smhf6kby'...
Warning: Permanently added the RSA host key for IP address 'xxx.xxx.xxx' to the list of known hosts.
Submodule 'lib/shared' (https://xxx@bitbucket.org/xxx/xxx_sharedlibs.git) registered for path 'lib/shared'
Cloning into 'lib/shared'...
fatal: could not read Password for 'https://xxx@bitbucket.org': No such device or address
Clone of 'https://xxx@bitbucket.org/xxx/xxx_sharedlibs.git' into submodule path 'lib/shared' failed
please ensure the correct public key is added to the list of trusted keys for this repository and the remote branch exists. (1)
```

**Comment by metal3d** [comment]
Exactly the same issue on my Github project;
https://hub.docker.com/r/metal3d/pandoc-server/

```
Building in Docker Cloud's infrastructure...
Starting to clone
Cloning into '.'...
Submodule 'pandoc-server' (git@github.com:metal3d/pandoc-server.git) registered for path 'pandoc-server'
Cloning into 'pandoc-server'...
Warning: Permanently added the RSA host key for IP address '192.30.252.131' to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Clone of 'git@github.com:metal3d/pandoc-server.git' into submodule path 'pandoc-server' failed
please ensure the correct public key is added to the list of trusted keys for this repository (1)
```

**Comment by rafdouglas** [comment]
Here you can find a workaround for the key issue:

https://github.com/docker/hub-feedback/issues/669

**Comment by metal3d** [comment]
@rajat-docker excuse me, I'm really sorry to say that but... removing the submodule is not a solution for me. And maybe because it's not a docker private repository I don't have any key to add or maybe I'm wrong.

Submodules worked well 1 month ago, today I'm not able to build images with submodules. And removing submodules to add a complete repository content in my project is (IMHO) a bad workaround. 

Thanks

**Comment by metal3d** [comment]
@rajat-docker and you can see that my previous comment mentionned the #633 issue ;)

**Comment by chytreg** [comment]
@metal3d & @jyounus I've managed to configure the build properly without removing submodules.
GitHub doesn't allow to duplicate deploy keys across repositories. https://help.github.com/articles/error-key-already-in-use Instead of adding deploy keys to repository add them to the user keys. So first remove any `Docker Hub Registry Automated Builds` from https://github.com/ORG/REPO/settings/keys (main and submodule included), next add `Deploy key` from DockerHub, you can find it on this site: https://hub.docker.com/r/ORG/REPO/~/settings/automated-builds/ to one of your GitHub user https://github.com/settings/ssh (GitHub user has to be linked with DockerHub and be a collaborator of DockerHub repository)
It work's for me and hopes will work in your case too.

**Comment by metal3d** [comment]
@chytreg thanks. I will try it !

**Comment by luheeslo** [comment]
I have the same problem.

@chytreg How I do for the github user be a collaborator in dockerhub repository?

**Comment by xiaods** [comment]
I have the same problem.

<img width="1080" alt="2017-07-18 9 36 15" src="https://user-images.githubusercontent.com/37678/28319681-27596bfe-6c01-11e7-8dd4-dc2ca8f2eb96.png">

**Comment by CicoZhang** [comment]
Actually I also have the same problem. Hub lacks my private key to access the repo, though I have bound my Github account to Docker hub, which has the read/write access already.

**Comment by vhosakot** [comment]
I saw the same error when I triggered automated build for my private GitHub repo.

```
Building in Docker Cloud's infrastructure...
Cloning into '.'...
Warning: Permanently added the RSA host key for IP address '192.30.253.112' to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.

please ensure the correct public key is added to the list of trusted keys for this repository (128)
```

Adding the deploy Key in “Build Settings” in Docker Hub to my GitHub account at https://github.com/settings/keys resolved this issue for me and the automated build passed for my private GitHub repo.

**Comment by qqbuby** [comment]
I have the same issue.

```none
Building in Docker Cloud's infrastructure...
Cloning into '.'...
Warning: Permanently added the RSA host key for IP address '192.30.253.112' to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.
please ensure the correct public key is added to the list of trusted keys for this repository (128)
```

**Comment by huezo** [comment]
```
Building in Docker Cloud's infrastructure...
Cloning into '.'...
Warning: Permanently added the RSA host key for IP address '192.30.253.112' to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.
please ensure the correct public key is added to the list of trusted keys for this repository (128)
```

![Captura de pantalla de 2019-03-27 16-33-58](https://user-images.githubusercontent.com/15940634/55116814-34178900-50ae-11e9-95be-4a04923061c2.png)

**Comment by Sherry-Lin** [comment]
same issues for me. How to find the deploy key in docker hub?

**Comment by meticulous-dft** [comment]
Not surfacing deploy key is a mistake. I am working on it right now.

**Comment by meticulous-dft** [comment]
The deploy key now shows up in the build configuration in case needs to update it in the source provider.

**Comment by ulrichSchreiner** [comment]
hi,

i have exactly the same problem
~~~
Building in Docker Cloud's infrastructure...
Cloning into '.'...
Warning: Permanently added the RSA host key for IP address '192.30.253.112' to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.
please ensure the correct public key is added to the list of trusted keys for this repository (128)
~~~

but my build is public and my github repo is public. the last build a few days ago worked without any problem.

**Comment by yanqd0** [comment]
The Docker Cloud should not clone public repositories by SSH. Instead, HTTPS should be the default protocol for better performance. And this kind of errors will never occur again.

**Comment by faicker** [comment]
relinked the github repo and changed the dockerhub password solved the problem for me.

**Comment by ritiek** [comment]
I fixed mine by going to https://cloud.docker.com/repository/docker/your_username/your_repository/builds/edit and copied the Deploy Key at the bottom. And pasted it under https://github.com/your_username/your_repository/settings/keys/new.

(make sure you replace "your_username" and "your_repository" in the URLs as appropriate)

Now I manually triggered a build for my repository on Dockerhub from https://cloud.docker.com/repository/docker/your_username/your_repository/builds
and it seems to have been working properly for me now.

**Comment by schmunk42** [comment]
@yanqd0 Right on spot! Who had the idea to clone repos for building via SSH?!

**Comment by zh794390558** [comment]
redo [this](https://docs.docker.com/docker-hub/builds/link-source/ ) maybe work.

**Comment by moyvera** [comment]
For those who don't depend on submodules may this work for you

- Make sure your account is well connected to Docker Hub
- I mean, Your Github or Bitbucket account 

In my case I changed the name of my account and that was causing the issue
