### ISSUE TITLE
BUG: Log unrecoverable.

### ISSUE THREAD

**Issue by jakirkham** [docker/hub-feedback#417]
Some automated builds fail with an exception and the message "Log unrecoverable". No other information is provided. The error is not even specified, but the build status is marked as "exception".

**Comment by cswarth** [comment]
+1 
An instance of this type of error can be seen here - 
https://hub.docker.com/r/cswarth/docker-beast/builds/baxmsqhfggamamfgjtdg8xm/

Even stranger, when not logged, the area marked "Logs" is completely blank, but shows "Log unrecoverable." when I am logged in to dockerhub.

**Comment by ChristopherBiscardi** [comment]
This is an old bug now. There is new code out which should not exhibit this error.

**Comment by jakirkham** [comment]
So, saw this bug again today. Sounds like it is not completely fixed. ( https://hub.docker.com/r/jakirkham/ubuntu_conda/builds/bb7hdepa8bveptbxsgbtykk/ )

<img width="1554" alt="screen shot 2015-11-20 at 8 57 56" src="https://cloud.githubusercontent.com/assets/3019665/11301395/d0bd2b5c-8f64-11e5-85c6-ec82da51055f.png">

**Comment by bcwalrus** [comment]
@jakirkham Sorry about that. We had to roll back to an older system environment to avoid some weird networking connectivity issues to our CDN. That CDN issue caused massive build failures on Mon & Tue. Until we figure that out with our CDN provider, we're staying on the older system, which unfortunately has this bug.

**Comment by jakirkham** [comment]
Ok, thanks for clarifying, @bcwalrus. Yes, I also prefer this bug to the massive build failures we were experiencing previously. Could this bugfix be backported to the older system though or is that not feasible?
