### ISSUE TITLE
Full description not fetched from github

### ISSUE THREAD

**Issue by bobrik** [docker/hub-feedback#419]
[My automated build](https://hub.docker.com/r/bobrik/zoidberg-tcp/) doesn't have full description populated, even though README.md is present on Github. It used to work automatically.

![image](https://cloud.githubusercontent.com/assets/89186/10710846/88354b5c-7a61-11e5-94e8-d0140530c939.png)

**Comment by frioux** [comment]
This is a big bummer; please fix

**Comment by whophil** [comment]
Same issue here. Here is a response from Docker support:

> HI whophil,
> 
> I believe this has something to do with your GitHub repo whereby it is forked from another repo.
> I will need to file this as an internal ticket for our engineers to work on.
> 
> Another workaround is for you to recreate a new GitHub repo and copy the source files to it.
> Then, use the new GitHub repo as a source for the Docker Automated Build.
> 
> Regards,
> Fauzan Ariffin
> Support Engineer
> Docker

**Comment by frioux** [comment]
For what it's worth, none of mine are forked.

**Comment by janeczku** [comment]
None of mine are forked. Please fix this! :+1:
