### ISSUE TITLE
Takes a long time to update the web UI after pushing a tag

### ISSUE THREAD

**Issue by brunzefb** [docker/hub-feedback#422]
Hi,

I had to wait for almost 10 minutes for my tag to show up in the dockerhub UI.  Is this normal???  I was getting worried, so I did a docker pull with the tag name, and that worked fine.  So I am pretty sure it is just a long lag.

The UI is a nice way to verify that a push actually worked.  When the tag does not show up in a "reasonable" amount of time, it is worrysome.

Best,

Friedrich Brunzema

**Comment by TabberGit** [comment]
Same issue.

Seems it can't be pulled either.

Also having issues with repo deletion lag.

**Comment by carrchang** [comment]
Using automated build, 3 repositories with 14 tags, about 10 hours after automated build, tags not show in docker hub ui, I can't using images in Kitematic, pull worked fine.

**Comment by HariSekhon** [comment]
I'm also frustrated by the slowness of automated builds on DockerHub. Perhaps more capacity needs to be added?

**Comment by crunis** [comment]
Same is happening in our team, we push tags and the DockerHub UI takes a long time to show them up, more than ten minutes. It is frustrating because it is our automation that pushes the tags so it makes people thing there has been a problem while pushing the tag but there has not.

**Comment by HariSekhon** [comment]
.
