### ISSUE TITLE
Recently built tags do not show in tags tab

### ISSUE THREAD

**Issue by timlinux** [docker/hub-feedback#424]
# Problem

I just triggered a new build of https://hub.docker.com/r/kartoza/qgis-desktop/tags/

When I look at the ``build details`` tab in the hub, I can see that tag **2.12** built ok:

![screenshot from 2015-10-28 16-20-01](https://cloud.githubusercontent.com/assets/178003/10791180/efe86df2-7d8f-11e5-91f5-4413b8901ec1.png)

https://hub.docker.com/r/kartoza/qgis-desktop/builds/bf6ap8jijxjbgr8yvf69eyx/

![screenshot from 2015-10-28 16-20-34](https://cloud.githubusercontent.com/assets/178003/10791182/f284ae86-7d8f-11e5-8fa2-6c49ab940f87.png)

When I flip over to the ``tags`` tab though, it is not listed:

https://hub.docker.com/r/kartoza/qgis-desktop/tags/

![screenshot from 2015-10-28 16-19-14](https://cloud.githubusercontent.com/assets/178003/10791191/fa2c8b54-7d8f-11e5-9892-c65a8ca9347d.png)

# Expected outcome

On successful builds, new tags should be listed in the ``tags`` tab.

**Comment by timlinux** [comment]
Follow up.

Ok I see this is really just confusion caused by #281 and similar tickets. In the  ``Build Status`` column it would be nice to have e.g. 'Building', 'Error', 'Done' as status (something visual would be nice too) as the current system is pretty cryptic....

**Comment by nathan-osman** [comment]
I'm seeing a similar problem - no tags are showing up after builds:

https://hub.docker.com/r/hectane/hectane/tags/
