### ISSUE TITLE
Long description imported from README.md does not honor comments

### ISSUE THREAD

**Issue by awilson-cloudpassage** [docker/hub-feedback#425]
### Problem:

Comments delimited in README.md using

```
<!--   -->
```

are literally rendered in long description, when imported through automated build process.  Example: https://hub.docker.com/r/awilson/where-are-they-now/
### Desired behavior:

Comments do not appear in long description when rendered from README.md during automated build process.

**Comment by ChristopherBiscardi** [comment]
I've confirmed this behavior on Hub. Additionally, GitHub removes html comments entirely from README files so we should have the same behavior so as to be less surprising to our users.

Thanks for reporting @awilson-cloudpassage
