### ISSUE TITLE
Can't subscribe organisation to paid plan

### ISSUE THREAD

**Issue by tibolami** [docker/hub-feedback#433]
Hi there,

I'm currently unable to subscribe my organisation to the 'micro' plan : Filling up the subscription form, and the submit button turns red.
Debugging web requests show that the POST https://hub.docker.com/v2/billing/subscriptions/ returns an http error 400.
Tried with 2 different browsers (chrome/safari) and 2 different credit cards

**Comment by thaJeztah** [comment]
@tibolami I "pinged" someone on the internal Slack channel, but perhaps contacting  support@docker.com (or sales@docker.com) would be good if you're having trouble

**Comment by tibolami** [comment]
Thanks @thaJeztah for following up ! I'm forwarding the case to support email

**Comment by thaJeztah** [comment]
@tibolami great! hope you get it resolved, feel free to "ping" me here if needed, then I can try to find the right people :+1:

**Comment by ChristopherBiscardi** [comment]
Thanks @thaJeztah @tibolami 

Closing this since it's going to support@
