### ISSUE TITLE
Automated build is successful but Dockerfile is unchanged

### ISSUE THREAD

**Issue by mkjsix** [docker/hub-feedback#434]
Hi,
We have triggered a new automated build by changing the Dockerfile in Github, however we still see the old Dockerfile.

The build details are correct:
https://hub.docker.com/r/softinstigate/restheart/builds/bf2rsfsc8csdawwto8dn3hf/

Here is the source Dockerfile:
https://github.com/SoftInstigate/restheart-docker/blob/master/Dockerfile

You can verify the Hub's Dockerfile hasn't been updated yet:
https://hub.docker.com/r/softinstigate/restheart/~/dockerfile/

Usually I see an almost immediate update after a successful build.

**Comment by ChristopherBiscardi** [comment]
Please contact support@docker.com for this.
