### ISSUE TITLE
Email notifications of automated build failure intermittently lost 

### ISSUE THREAD

**Issue by mato** [docker/hub-feedback#435]
I have enabled "Notify me when an automated build fails" on https://hub.docker.com/account/notifications/. Despite this, I don't always get an email notification when an automated build fails.

I've been using `mato/rumprun-ci-testing` as a guinea pig, as you can see from the list of commits to its associated Dockerfile: https://github.com/mato/rumprun-docker-builds/commits/master/ci-testing/Dockerfile. However, the issue seems to be affecting all my automated builds equally.

The builds in question are any of these: https://hub.docker.com/u/mato/.

**Comment by marcusmartins** [comment]
cc @bcwalrus
