### ISSUE TITLE
Feature request: Improved email notifications

### ISSUE THREAD

**Issue by mato** [docker/hub-feedback#436]
I currently use a shell script to parse emails from Docker Hub about automated build failures and forward them to a project mailing list. It'd be most helpful if the email notifications could be improved to look something like this (using my `mato/rumprun-ci-testing` build as an example):

```
Subject: [mato/rumprun-ci-testing] Docker Hub build failed

Hi Martin Lucina,

There seems to have been an issue with your Automated Build
"mato/rumprun-ci-testing" (VCS repository: mato/rumprun-docker-builds) during
the build step.

Last XXX lines of build log follows:
----
(Last XXX lines of build log)
----

You can find more information on
https://hub.docker.com/r/mato/rumprun-ci-testing/builds/bp3dw4h5amdatl9nwspymb4/
```

It would also be useful to get notifications when a build is fixed/successful, much like Travis and other CI systems do. Some kind of integration with "which Git commit this build is related to" is another nice to have.

**Comment by marcusmartins** [comment]
cc @bcwalrus
