### ISSUE TITLE
Feature request: Raw download links for automated build logs

### ISSUE THREAD

**Issue by mato** [docker/hub-feedback#437]
Example: On https://hub.docker.com/r/mato/rumprun-toolchain-hw-x86_64/builds/, I'd like to have a "raw" link in the "Build Code" column that _downloads_ the log as `text/plain` when accessed from a browser, or can be used directly with wget/curl/...

The problem this solves is that the build logs can get quite large, and rendering them in the browser takes forever.

**Comment by mato** [comment]
Related: I can't cut and paste from the build log without getting mangled text and U001B characters instead of newlines. This makes it *hard* to e.g. paste a log snippet into a Github issue.

**Comment by marcusmartins** [comment]
cc @bcwalrus
