### ISSUE TITLE
Public automated build logs only visible to logged in hub users

### ISSUE THREAD

**Issue by mato** [docker/hub-feedback#438]
Steps to reproduce:
1. Ensure you're not logged in to Docker Hub.
2. View any public automated build log, e.g. one of mine: https://hub.docker.com/r/mato/rumprun-toolchain-hw-x86_64/builds/b3u4gqiyudlpzzlcd5oukym/

Observed resukt:

The "logs" box is empty.

Expected result:

The "logs" box contains the build log.

**Comment by marcusmartins** [comment]
Thanks for the report. We are aware of this issue and we hope to have a fix soon. cc @rrarunan
