### ISSUE TITLE
New automated build repositories will not build

### ISSUE THREAD

**Issue by DJBnjack** [docker/hub-feedback#439]
I have created two new automated builds linked to GitHub repositories.

Both of the times the automated build does not start, even after triggering it manually.
There is only the "Success" toast, but no build is added to the list.

Steps to reproduce:
1. Create a new automated build
2. Trigger a new build
3. Nothing shows up in the build list

Previously defined automated build repositories still work, new repositories fail.

OS: Windows 10
Browser: Chrome
URL: The "Builds" and "~/settings/automated-builds/" pages
Screenshots shown in comment below
Date-Time: Been happening for nearly 2 hours now.
Now is: 23:00 GMT+1 (Amsterdam timezone) on the 4th of November 2015
Hub username: djbnjack

Update: also tried this with BitBucket, same result.

**Comment by DJBnjack** [comment]
Just reproduced this with a GitHub repository that I have used with the Docker Hub before, still nothing showing up in the build list.

![1](https://cloud.githubusercontent.com/assets/315946/10953497/ade4315c-8348-11e5-9c5b-e430f5bfedbc.png)
![2](https://cloud.githubusercontent.com/assets/315946/10953496/ade282e4-8348-11e5-964b-fd0fd4aeb0c4.png)

**Comment by DJBnjack** [comment]
Ok, this seems to work again now.

**Comment by ChristopherBiscardi** [comment]
@DJBnjack Over the last day or so we rolled out Automated Builds changes.  Please contact support if there are any further disruptions for you.

**Comment by DJBnjack** [comment]
Thanks! I was slightly in shock as I was giving a demo on the Docker Hub auto-build system the day afterwards :+1:
