### ISSUE TITLE
Availability of docker 1.9 on Hub

### ISSUE THREAD

**Issue by dg-ratiodata** [docker/hub-feedback#440]
Hi,

when will docker 1.9. available on DockerHub? This [build](https://hub.docker.com/r/feduxorg/centos/builds/bfhdfbsrppmbhovhcuwpd4p/) fails with `Unknown instruction: STOPSIGNAL`.

**Comment by ChristopherBiscardi** [comment]
Currently builds are running with 1.8.3; 1.9 is planned, but does not have a specific date.

**Comment by dg-ratiodata** [comment]
Ok. Would be great to see it shipped. I'm would like to use the new `STOPSIGNAL` command.

**Comment by dg-ratiodata** [comment]
kkk

**Comment by ChristopherBiscardi** [comment]
Tracking 1.9 on #460

**Comment by garex** [comment]
Should we create a petition on change.org to speed up such basic feature as ARG support in automatic builds?
