### ISSUE TITLE
Markdown: H1 and H2 headers are formatted as normal text

### ISSUE THREAD

**Issue by janeczku** [docker/hub-feedback#446]
```markdown
# Title H1
## Title H2
```
is formatted as normal text.

Example: https://hub.docker.com/r/janeczku/alpine-haproxy/

**Comment by benbc** [comment]
We're seeing this for our image too, in both [our own repo](https://hub.docker.com/r/neo4j/neo4j/) and [the official library](https://hub.docker.com/_/neo4j/).

**Comment by jakirkham** [comment]
Also, seeing this.

**Comment by ChristopherBiscardi** [comment]
I fixed this tonight in the relevant package. It will go out soon.

**Comment by mfischer-zd** [comment]
ETA?

**Comment by kevinchabreck** [comment]
+1, looks like this is still an issue.

**Comment by geirgp** [comment]
Yep, still an issue

**Comment by Starefossen** [comment]
+1

**Comment by janeczku** [comment]
This trivial to fix bug has been lingering for almost two months now. Just wow.

**Comment by frioux** [comment]
Signal boost.

**Comment by janeczku** [comment]
Hyperdrive... Engage! :rocket:

**Comment by ChristopherBiscardi** [comment]
This one ended up getting rolled up into a larger change that will be going out this week ideally. It's fixed in master now:

<img width="831" alt="screenshot 2016-01-04 15 39 36" src="https://cloud.githubusercontent.com/assets/551247/12103703/62d1cca2-b2f9-11e5-9167-faef5ace6d0d.png">

**Comment by Starefossen** [comment]
Looking forward to it @ChristopherBiscardi :100: :+1:

**Comment by nhsiehgit** [comment]
Sorry everyone, we've been working on a big change that's caused a freeze in deployments the past few weeks. Aiming to get things rolled out by this week, which will solve a lot of these issues.

Thanks for your patience everyone!

**Comment by kristiehoward** [comment]
Closing as this issue should be fixed now :star2: 

![image](https://cloud.githubusercontent.com/assets/7132362/12247295/3b75fb78-b868-11e5-9df9-759a084ba70b.png)

**Comment by janeczku** [comment]
:tada: :dancers: :heart_eyes:
