### ISSUE TITLE
Markdown: Images not rendered in descpription

### ISSUE THREAD

**Issue by janeczku** [docker/hub-feedback#447]
```Markdown
[![Docker Pulls](https://img.shields.io/docker/pulls/janeczku/alpine-haproxy.svg)](https://hub.docker.com/r/janeczku/alpine-haproxy/)
```
Image is not shown. This was working before.

**Comment by jakirkham** [comment]
Simply another case of this ( https://github.com/docker/hub-feedback/issues/104 ). It was compiled into a list, but has yet to be fixed.

**Comment by janeczku** [comment]
@jakirkham 
 > @rrarunan: The issue of images not loading should be fixed

Sounds like the opposite of 'has yet to be fixed'. This is a regression.

**Comment by jakirkham** [comment]
I am mere linking it to the original issue opened regarding this problem.

"Has yet to be fixed" is correct as Docker Hub was rewritten and released under a beta, which now has become the only Docker Hub. It seems to share very little in common with the original Docker Hub so regression sounds inaccurate.

In either case, this is a known issue.

**Comment by ChristopherBiscardi** [comment]
@janeczku @jakirkham

A known issue that is now fixed in prod :) thanks for reporting.

**Comment by ChristopherBiscardi** [comment]
<img width="848" alt="screenshot 2015-11-09 18 09 54" src="https://cloud.githubusercontent.com/assets/551247/11052475/191d3cb2-870d-11e5-95b4-b4fa8597d58c.png">

**Comment by janeczku** [comment]
Nice! :-)

**Comment by jakirkham** [comment]
Thanks.

**Comment by jakirkham** [comment]
This still seems to miss some images. For instance, there should be two images as in the Github [repo]( https://github.com/jakirkham/docker_centos_drmaa_conda ), but only one of them shows up on the [hub]( https://hub.docker.com/r/jakirkham/centos_drmaa_conda/ ).
