### ISSUE TITLE
Unable to change Github source repo

### ISSUE THREAD

**Issue by samos123** [docker/hub-feedback#448]
I renamed my repo from docker-tutum-drupal to docker-drupal, but this causes automated builds to fail and there is no way to change the source repo to the new name from docker hub...

Feature request: ability to rename or totally edit source repo in docker hub.

**Comment by jakirkham** [comment]
You could delete and recreate it. Admittedly not as nice, but may help for the moment.

**Comment by samos123** [comment]
Yea that would work, but not acceptable... I don't want to loose current comments, stars and download counts etc... Thanks for your suggestion though :)

**Comment by lynndotconfig** [comment]
Any improvement for that? It is not convenient.

**Comment by tomdee** [comment]
I'm also having this problem

**Comment by aerth** [comment]
this issue exists :+1:
