### ISSUE TITLE
BUG: Cloning git submodules is not working

### ISSUE THREAD

**Issue by jakirkham** [docker/hub-feedback#449]
It had been the case that if your repo contained a git submodule, the git submodule would be cloned too. However, this appears to not be happening anymore.

It appears there was a recent update to Docker Hub. I am guessing somebody just forgot the `--recursive` or `--recurse-submodules` option to `git clone` or took it out by accident.

Here is a simple [example]( https://github.com/jakirkham/docker_449_test ) that reproduces this [problem]( https://hub.docker.com/r/jakirkham/docker_449_test/builds/b4k8sfjqdnypafs8asw7ap9 ). Builds fine locally.

**Comment by sfate** [comment]
Same to me.
Submodules from private repos didn't work from today.
Deploy keys for user with read permission to that repos are in place.

**Comment by ekan** [comment]
Yep, same here. Images that built Friday (3 days ago) no longer build:

```
=> Errors while initializing project:

While selecting package versions:
error: unknown package in top-level dependencies: redpost:app
unknown package in top-level dependencies: redpost:contents
unknown package in top-level dependencies: justinventuri:flash
```

**Comment by retog** [comment]
The problem seems to affect both private and public repos.

**Comment by jakirkham** [comment]
Sorry to pushy, but this is really crushing my build pipeline. Any chance we could see a fix @ChristopherBiscardi?

**Comment by jakirkham** [comment]
Seeing this [error]( https://github.com/docker/hub-feedback/issues/457 ) in association with this problem.

**Comment by jakirkham** [comment]
Added example code referenced in the issue description above that reproduces this problem and a build on Docker Hub to demonstrate the issue. This builds fine locally.

**Comment by jakirkham** [comment]
I believe this might be fixed. I was able to rebuild one of my automated builds that has a git subrepo today. The test image shown above is queued to rebuild. I would be curious if others have also noticed the same improvement I have seen.

**Comment by jakirkham** [comment]
The test image was able to build fine. I believe this is fixed. If you haven't tried, please rebuild your images. Please post the outcome.

**Comment by sfate** [comment]
Approved. Today builds passing slower, but submodules are present. 
Thanks for feedback @jakirkham

**Comment by jakirkham** [comment]
Agreed. Initially, this was running reasonably quickly. Now, it appears builds that took a few minutes drag on for hours.

**Comment by jakirkham** [comment]
Should add that they frequently fail part way with no explanation hence the link to https://github.com/docker/hub-feedback/issues/455

**Comment by jakirkham** [comment]
So, this has picked up for me a bit in the last day or two. Are other people still struggling with this?
