### ISSUE TITLE
Feature Request: Able to link the existing docker hub repos to their source github repos

### ISSUE THREAD

**Issue by bhalothia** [docker/hub-feedback#450]

**Comment by jakirkham** [comment]
I think this already exists, no? On Docker Hub, it should show in the right column near the bottom the "Source Repository" with a link that can be clicked on. See below.

If this is not what you are asking for, could you please clarify?

<img width="1554" alt="screen shot 2015-11-09 at 8 26 43" src="https://cloud.githubusercontent.com/assets/3019665/11034711/a57879da-86bb-11e5-9614-2bcf0a79cca7.png">

**Comment by bhalothia** [comment]
@jakirkham Actually, I wanted it for the docker hub repos where images were directly pushed before the automated build feature came in. 

Consider this scenario -

I've a github repo, with a dockerfile to build my docker image but I pushed the image before the automated build feature came. Now, I would want my docker hub repo to be connected to the github repo I have. Do I need to delete it and create a new one for automated build?

**Comment by jakirkham** [comment]
Yes, you will need to delete it and create a new one for the automated build.

**Comment by cleung2010** [comment]
Would it be possible to add the option to use automated build to an existing project that was started with manual builds?

**Comment by flaccid** [comment]
Bye bye stars, pulls etc.! :(

**Comment by brettt89** [comment]
+1 for being able to add automated builds to an existing image without deleting

**Comment by aymhce** [comment]
+1 for this feature ! :)

**Comment by tiagomtotti** [comment]
+1 !!!

**Comment by angelo-moreira** [comment]
++++++1

**Comment by allan-mlpe** [comment]
+1
