### ISSUE TITLE
Tags not showing up for new /.*/ autobuild on website.

### ISSUE THREAD

**Issue by xamox** [docker/hub-feedback#452]
It appears that the new /.*/ is setup and working for autobuilds to sync with github branches and will even pull down.

For instance this works:
```
git checkout -b new-branch
git commit -am "some changes"
git push origin new-branch
# Autobuild is kicked off on docker hub and finishes
docker pull myorg/mybuild:new-branch
```

But on the website page I do not see the tag reflected at:
https://hub.docker.com/r/myorg/mybuild/tags/

**Comment by mudler** [comment]
:+1: 

In my case, i can't even pull it, i changed in settings to tag it as "latest" but is neither tagged nor available for pull.

**Comment by hainesr** [comment]
I'm seeing this too: autobuild works fine, tags don't show, I can still pull the tags (including latest).

Would be nice to know what's going on, because even though I know things are actually there, others don't so think there's nothing to pull.

**Comment by rrarunan** [comment]
@hainesr can you give us the repository link, if it is a public repository so, we can take a look?

**Comment by hainesr** [comment]
Hi @rrarunan,

https://hub.docker.com/r/idinteraction/base/ is an automated build I created yesterday. Both the latest and 2.0 tags have built and can be pulled but don't show up in the tags page.

https://hub.docker.com/r/idinteraction/object-tracking/ is an automated build I set up a while back with just a default latest tag, which does show up in the tags page. I set up a 1.0 tag in that repo just today and it doesn't show up, but can be pulled.

Thanks for having a look at this, much appreciated.

**Comment by rrarunan** [comment]
@hainesr Thanks for the details. We are investigating this and provide an update as soon as we can.

**Comment by hainesr** [comment]
@rrarunan interestingly I just created another automated build today and the latest tag *is* showing up: https://hub.docker.com/r/hainesr/tdd-fibonacci-example/

**Comment by xamox** [comment]
Thanks for following up @rrarunan

**Comment by rrarunan** [comment]
@hainesr @xamox Yes, we see this particular issue only in a select few builds. We will provide an update soon.

**Comment by waj** [comment]
Any update on this? It seems I'm having the same problem: https://hub.docker.com/r/instedd/nuntium/
For example, tags 1.6-pre1 and 1.6-pre2 can be pulled, but they are not showing up.

**Comment by hassan-k** [comment]
I've seen this on all my auto build repositories.
https://hub.docker.com/u/createkio/
:+1:  to fix this soon

**Comment by bcwalrus** [comment]
A fix is on the way. It took us a while to pin this down. It has to do with some new interactions that impacts organization accounts.

**Comment by xamox** [comment]
Cool beans, thanks for not letting it die on the vine.

**Comment by dkador** [comment]
Any updates? I think I ran into this today. Thanks!

**Comment by pkennedyr** [comment]
Fix has been released for this issue.

**Comment by meonkeys** [comment]
To get this to work I had to de-auth github from Docker Hub and re-auth, allowing all permissions.
