### ISSUE TITLE
can't push image

### ISSUE THREAD

**Issue by gerardo8a** [docker/hub-feedback#454]
I tried to push an image for the first time and it was pushed successfully to my username/image_name repo.
I went to the UI and deleted this because I wanted to upload it to a private repo and I realized I need to add the repo name when tagging

So I tagged mi image and still trying to upload the image but I get the following error every time

The push refers to a repository [docker.io/my_username/repo/my_image] (len: 1)
f311b390c866: Image push failed
unauthorized: access to the requested resource is not authorized

I already logged off and logged in via docker login, and also I removed the config.json with the keys and log in but still having the same issue

**Comment by ChristopherBiscardi** [comment]
A fully qualified image identifier is comprised of three elements.

1. A `namespace` (your hub username)
2. A repository name (The place where your images will be stored)
3. A tag

The format is `namespace/name:tag`

An example image for myself, tagged as version 1.0 would be:

1. biscarch
2. bot
3. v1.0

`biscarch/bot:v1.0`


----

Please contact support@docker.com, who will be able to help you debug further.
