### ISSUE TITLE
Build failing on dockerfile with ARG 

### ISSUE THREAD

**Issue by Tritlo** [docker/hub-feedback#456]
Greetings,

My build seems to be failing on an ARG, with very little info.
Up until that point, it is very standard.

See:
https://hub.docker.com/r/tritlo/murmur/builds/bxqnhrqjp8whz5tmhtmfcfk/

**Comment by Tritlo** [comment]
From the log, it appears as if docker hub is using docker 1.8.4. Is that the case? When will it be updated?

**Comment by thaJeztah** [comment]
Yes, I think Docker Hub automated builds are still on 1.8.x. I don't have an ETA as to when they will be updated at this moment (don't have that information)

**Comment by thaJeztah** [comment]
Just got informed that they're working on the schedule for 1.9. Apologies for the inconvenience you're having right now

**Comment by ChristopherBiscardi** [comment]
Thanks @thaJeztah ; Closing to use a centralized 1.9 ticket at #460

**Comment by garex** [comment]
#460 is closed for +1!! It's a violation of freedom of plus-one!!

**Comment by theodorosploumis** [comment]
+1

**Comment by esmail** [comment]
+1 to this/#460.

**Comment by mitar** [comment]
Still not support for ARG and #460 locked but not closed?
