### ISSUE TITLE
Automatic build fails. Error in "/common/highland/utils.py"

### ISSUE THREAD

**Issue by alpegon** [docker/hub-feedback#457]
Hi, this error appears when trying to create a docker image using the automated build options:

Encountered error: Traceback (most recent call last): File "/common/highland/utils.py", line 35, in build_update_context yield File "/common/highland/monitor.py", line 137, in monitor if self.build_finished(): File "/common/highland/monitor.py", line 111, in build_finished raise Exception("Non-zero exit code: %r" % exit_code) Exception: Non-zero exit code: 1

![dockerhub_error](https://cloud.githubusercontent.com/assets/8695439/11068012/a730da64-87cf-11e5-92b7-78ba9d44ebdc.jpg)

The dockerfile used is the following https://github.com/grycap/im/blob/tosca/docker-tosca/Dockerfile

Whit previous dockerfiles I had no issues, so I don't know what could be causing this.

Thanks

**Comment by binhex** [comment]
yep, add me to this issue as well, im seeing the exact same thing on two different repositories now:-

https://hub.docker.com/r/binhex/arch-plexpass/builds/bscpmtf4mbglqzupurecqyq/
https://hub.docker.com/r/binhex/arch-sabnzbd/builds/bxhukaimj4utvgftxlviuma/

**Comment by davidsketchdeck** [comment]
+1

**Comment by adnanabh** [comment]
+1

**Comment by hyukim2013** [comment]
:+1:

**Comment by flrngel** [comment]
+1

**Comment by jakirkham** [comment]
Also, seeing this. Builds fine locally. Built fine last week.

**Comment by alpegon** [comment]
I have been doing tests all morning and now it's working fine.
As final test I used the same Dockerfile and build configuration that was causing the error and it also worked fine.
I'm not having this issue anymore, but it seems that some other users are.
Check your builds again and if they are working I will close this issue.

**Comment by jakirkham** [comment]
Sorry @alpegon, this is definitely still an issue for me and I can reliably reproduce it. I strongly recommend this remain open until it is fixed.

**Comment by alpegon** [comment]
Ok, not a problem

**Comment by jakirkham** [comment]
Thanks.

**Comment by jakirkham** [comment]
I created a simple example that reproduces this issue. See the message in this build ( https://hub.docker.com/r/jakirkham/docker_449_test/builds/b4k8sfjqdnypafs8asw7ap9/ ).

**Comment by shift** [comment]
+1

**Comment by jakirkham** [comment]
Seeing a variant on this.

<img width="1554" alt="screen shot 2015-11-14 at 14 16 38" src="https://cloud.githubusercontent.com/assets/3019665/11165365/66290b00-8ada-11e5-9ac9-6267a4ed24f1.png">
