### ISSUE TITLE
table on "Tags" page should display more than name/size

### ISSUE THREAD

**Issue by n0mer** [docker/hub-feedback#458]
Hi,

please add more information to "Tags" page https://hub.docker.com/r/_user_/_project_/tags/ , at least build timestamp and image ID.

Ideally it should display "docker inspect _image_id" results, but please at least display ID and timestamp first.

**Comment by n0mer** [comment]
linking #139 #344

**Comment by ChristopherBiscardi** [comment]
Consolidating to #139
