### ISSUE TITLE
spurious build failures, tags not showing up

### ISSUE THREAD

**Issue by clehene** [docker/hub-feedback#459]
We're seeing random failures which seem to be specific to the hub infrastructure rather than the images being built

Same build hasn't been working in the last 24 hours:
error state https://hub.docker.com/r/mesosphere/marathon/builds/bf8rmw5mpslele4hm2hccsb/
In this state we can actually pull the tag, although it doesn't show up in the tags list.

exception state https://hub.docker.com/r/mesosphere/marathon/builds/bscozmieto4kbscbxh9ruwt/
in this state the tag couldn't be pulled at all

**Comment by jakirkham** [comment]
Also, seeing this problem to. Builds seem to end in the midst of the build process without any warning or exception. Additionally, builds seem to take far longer than normal. For example, builds that took several minutes now take several hours. It would be nice to see this resolved.
