### ISSUE TITLE
Beta Docker Hub not fully responsive on smartphone

### ISSUE THREAD

**Issue by javierprovecho** [docker/hub-feedback#46]
Hello,

Just noticed that some elements break each other when using the webpage from Safari's iPhone. As far I debugged, it is more related to the position of the elements rather than an error from the browser. Also, I can't toggle top right menu. Seems that touch events are disabled.
- _OS_: iOS 8.3
- _Browser_: Safari
- _URL_: https://hub-beta.docker.com/#
- _Time/Date_: 19:10 UTC 06/12/2015
- _Username_: javierprovecho
- _Screenshot_:

![img_1426](https://cloud.githubusercontent.com/assets/2457529/8137910/fa3f74fe-1146-11e5-8a27-cdfcc3aa7ef6.PNG)

**Comment by ChristopherBiscardi** [comment]
The site is not currently built to be responsive to phone-sized devices (and that is not currently marked as a priority). We have, however, built the site in a way that lets us address this issue in the future and intend to improve this over time.

**Comment by tavisto** [comment]
This also happens when you resize your browser portal size. The top menu goes away and the toggle menu button does not work with mouse events either. All browsers and all sized less than a full desktop size.

**Comment by github-peter** [comment]
I vote for increased priority of fixing this issue.
