### ISSUE TITLE
Issue introduced in the automated builds (cap_set_file on centos7)

### ISSUE THREAD

**Issue by lvlie** [docker/hub-feedback#461]
Hi,

I wasnt sure to post this as a comment to https://github.com/docker/docker/issues/6980, to which this is related, or here. This seemed like the best place as it relates to automated builds on the hub :) 

I am facing the mentioned issue with cap_set_file on the docker hub (automated builds) today. Strange thing is, installing httpd on the same centos7 based image worked 19 days ago (also on the hub). 

19 days ago:
```
Installing : mailcap-2.1.41-2.el7.noarch                                  7/9
Installing : httpd-2.4.6-31.el7.centos.1.x86_64                           8/9
Installing : 1:mod_ssl-2.4.6-31.el7.centos.1.x86_64                       9/9
```

Today:
```
  Installing : mailcap-2.1.41-2.el7.noarch                                  7/9 
  Installing : httpd-2.4.6-31.el7.centos.1.x86_64                           8/9[91mError unpacking rpm package httpd-2.4.6-31.el7.centos.1.x86_64[0m[91m
[0m 
error: unpacking of archive failed on file /usr/sbin/suexec: cpio: cap_set_file
  Installing : 1:mod_ssl-2.4.6-31.el7.centos.1.x86_64                       9/9 
error: httpd-2.4.6-31.el7.centos.1.x86_64: install failed
```

The centos7 docker image itself has not been updated in the meantime, has this issue perhaps been re-introduced on the systems running the automated builds? 

The only info I could find related to changes in the docker build logs where:
19 days ago:
```
Server:
 Version:      1.8.3-rc4
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   9f1606a
 Built:        Fri Oct  2 23:36:50 UTC 2015
 OS/Arch:      linux/amd64
```

Today:
```
KernelVersion: 3.13.0-40-generic
Os: linux
BuildTime: Mon Oct 12 05:37:18 UTC 2015
ApiVersion: 1.20
Version: 1.8.3
GitCommit: f4bf5c7
Arch: amd64
GoVersion: go1.4.2
```

Thanks for your help!

Kind regards,
Leon

**Comment by dlord** [comment]
We are getting the same issue with our automated repos that user `centos:centos7` as the base image, and `httpd` is being pulled in as a dependency of another package.

**Comment by dg-ratiodata** [comment]
My images are affected as well. Would be great if some has a look into this.

**Comment by RonWilliams** [comment]
Experiencing the same issue with https://github.com/usda-ocio-eas/gov-drupal

Hub url: https://hub.docker.com/r/usdaeas/gov-drupal/

**Comment by xrow** [comment]
We have the same issue. This is quite a blocker. https://hub.docker.com/r/xrowgmbh/systemd/builds/

**Comment by dg-ratiodata** [comment]
I opened a support ticket with a mail to support@docker.com: Ticket 10523 - Automate Build fails due to "cap_set_file"-error for "httpd" on "CentOS 7"

**Comment by kizbitz** [comment]
See https://github.com/docker/docker/issues/6980#issuecomment-50176875
and thaJeztah's comment: https://github.com/docker/docker/issues/8966#issuecomment-94210446

**Comment by lvlie** [comment]
Yes we found the issue and the comment, but that would mean the hub build-farm uses an outdated version of aufs... (issue got reintroduced on the hub) 
If I build the images myself I do not run into these issues since I am not using aufs

**Comment by kizbitz** [comment]
Update: An internal ticket (HIGH-355) has been created internally and teams notified.

Note: In my testing temp work-arounds (caution: this is not Docker provided software) suggested by jnweiger I was able to get successful builds: https://github.com/owncloud/core/issues/12967#issuecomment-83064397

Specifically: https://github.com/owncloud/administration/blob/master/docker/tools/obs-docker-install.py#L190-L192

**Comment by lvlie** [comment]
Hmm, I dont like tricking it with a dummy libcap. If you search on the internet it seems the package is not well built and causes some issues for owncloud users with regards to yum updates.

**Comment by xrow** [comment]
@kizbitz Is there any update on the topic? Thanks so far.

**Comment by callahant** [comment]
Seeing this bug on recent install:

Server Version: 1.10.2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 36
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Plugins:
 Volume: local
 Network: bridge null host
Kernel Version: 3.13.0-79-generic
Operating System: Ubuntu 14.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 47.16 GiB

**Comment by RonWilliams** [comment]
This continues to affect the main CentOS repository:
https://github.com/CentOS/CentOS-Dockerfiles/blob/master/httpd/centos7/Dockerfile

https://hub.docker.com/r/centos/httpd/builds/

**Comment by xrow** [comment]
Hi all,
can someone let us know what the general status is? How was HIGH-355 resolved? I need to point out that not updating centos base container cause serious security implications for those containers of that branch.

**Comment by jtgasper3** [comment]
This clearly needs more comments to raise it to a high enough level to warrant a comment back, or perhaps a fix. :)

This is seriously hampering anyone trying to build CentOS 7 based images... 

#payingDockerHubOrganization

**Comment by tanhaa** [comment]
is there any update on this?  I just had a build-failure on docker-hub because of this error.  Centos:7 image that is trying to install httpd: 
```  Installing : httpd-2.4.6-40.el7.centos.x86_64                         216/237[91mError unpacking rpm package httpd-2.4.6-40.el7.centos.x86_64
[0m 
error: unpacking of archive failed on file /usr/sbin/suexec: cpio: cap_set_file```

Of course, the image building works fine when done locally on my laptop, the automated build fails however.

**Comment by radykal-com** [comment]
Another one with all centos7 images failing to build on docker hub due to this problem. Does anyone has news on this? Any feedback?

**Comment by dg-ratiodata** [comment]
@kizbitz Can you help use with an update?

**Comment by asuwarnapati** [comment]
Docker version 1.10.3, build 20f81dd

same issue when it was 1.6, then i upgraded to 1.10.3. still same issue.

strangely, my colleague pc has no problem, his version is 10.x also.

**Comment by devantoine** [comment]
Same issue here, using Ubuntu 15.10 using docker 1.6.2.
That's a real blocker here.

**Comment by lysender** [comment]
I have this issue too. I have to build the image locally to bypass docker hub temporarily.

**Comment by pkennedyr** [comment]
We are currently investigating this issue (HIGH-355) and will post an update as soon as the resolution is available.

**Comment by dg-ratiodata** [comment]
@pkennedyr Thanks a lot.

**Comment by Oloremo** [comment]
Any updates?

**Comment by sam9046** [comment]
Having the same issue here...

**Comment by lgibelli** [comment]
+1

**Comment by dg-ratiodata** [comment]
Sorry @pkennedyr to bother you again. Any updates for the issue? Seems to be a rather complicated one. Can we help you?

**Comment by choppedcode** [comment]
Having the same issue here:
`Installing : httpd-2.4.6-40.el7.centos.x86_64 8/10 [91mError unpacking rpm package httpd-2.4.6-40.el7.centos.x86_64`

**Comment by jperrin** [comment]
So what can be done here? This issue on the dockerhub is a bit of a blocking issue, as many things rely on capabilities flags set on files.

**Comment by ausil** [comment]
A lot of packages in modern distros have replaced setuid/setgid binaries with filesystem capabilities, this problem will only get worse unless not addressed properly. filesystem capabilities need to be a first class citizen.

**Comment by probonopd** [comment]
+1

Is there any known workaround, e.g., a way to tell `yum` not to set the flags?

**Comment by lgibelli** [comment]
The simplest and dirtiest, ugliest workaround is to isolate the packages that fail to install and add:

yum -y install packagename || true

to the top of your Dockerfile.

This should be really fixed by Docker team though.

-- 
L.G. - Sent from my mobile

**Comment by dustinlacewell** [comment]
Hello. We are currently investigating this issue and would like to solicit anyone having this issue to provide a public autobuild as a reproducing case that we can test against. We'll be monitoring this thread for responses.

**Comment by jperrin** [comment]
@dustinlacewell the centos httpd container is a good example of this. https://hub.docker.com/r/centos/httpd/builds/

**Comment by probonopd** [comment]
Use the `centos:6.7` docker image and try to run

```
rpm -ivh ftp://fr2.rpmfind.net/linux/sourceforge/f/fu/fuduntu-el/el6/current/UNSTABLE/RPMS/glibc-common-2.15-60.el6.x86_64.rpm ftp://fr2.rpmfind.net/linux/sourceforge/f/fu/fuduntu-el/el6/current/UNSTABLE/RPMS/glibc-2.15-60.el6.x86_64.rpm ftp://fr2.rpmfind.net/linux/sourceforge/f/fu/fuduntu-el/el6/current/UNSTABLE/RPMS/glib2-devel-2.35.8-1.el6.x86_64.rpm ftp://fr2.rpmfind.net/linux/sourceforge/f/fu/fuduntu-el/el6/current/UNSTABLE/RPMS/glib2-2.35.8-1.el6.x86_64.rpm --replacefiles
```
The rpm command will not exit cleanly and will throw `error: unpacking of archive failed: cpio: cap_set_file`.

**Comment by jeffgeiger** [comment]
@dustinlacewell I second @jperrin.  The httpd container is probably one of the simplest cases.  If you need more examples, here is another: https://hub.docker.com/r/jeffgeiger/centos-pmwiki

**Comment by jtgasper3** [comment]
Here's another example: https://hub.docker.com/r/jtgasper3/centos-shibboleth-sp/

**Comment by dustinlacewell** [comment]
@probonopd Hmm when running this on one of our existing hosts with no changes I get:

`[root@323d01a5a585 /]# rpm -ivh ftp://fr2.rpmfind.net/linux/sourceforge/f/fu/fuduntu-el/el6/current/UNSTABLE/RPMS/glibc-common-2.15-60.el6.x86_64.rpm ftp://fr2.rpmfind.net/linux/sourceforge/f/fu/fuduntu-el/el6/current/UNSTABLE/RPMS/glibc-2.15-60.el6.x86_64.rpm ftp://fr2.rpmfind.net/linux/sourceforge/f/fu/fuduntu-el/el6/current/UNSTABLE/RPMS/glib2-devel-2.35.8-1.el6.x86_64.rpm ftp://fr2.rpmfind.net/linux/sourceforge/f/fu/fuduntu-el/el6/current/UNSTABLE/RPMS/glib2-2.35.8-1.el6.x86_64.rpm --replacefiles
Retrieving ftp://fr2.rpmfind.net/linux/sourceforge/f/fu/fuduntu-el/el6/current/UNSTABLE/RPMS/glibc-common-2.15-60.el6.x86_64.rpm
Retrieving ftp://fr2.rpmfind.net/linux/sourceforge/f/fu/fuduntu-el/el6/current/UNSTABLE/RPMS/glibc-2.15-60.el6.x86_64.rpm
Retrieving ftp://fr2.rpmfind.net/linux/sourceforge/f/fu/fuduntu-el/el6/current/UNSTABLE/RPMS/glib2-devel-2.35.8-1.el6.x86_64.rpm
Retrieving ftp://fr2.rpmfind.net/linux/sourceforge/f/fu/fuduntu-el/el6/current/UNSTABLE/RPMS/glib2-2.35.8-1.el6.x86_64.rpm
warning: /var/tmp/rpm-tmp.5dMQFL: Header V4 RSA/SHA1 Signature, key ID ea675ea0: NOKEY
error: Failed dependencies:
        /usr/bin/perl is needed by glib2-devel-2.35.8-1.el6.x86_64
        perl(File::Basename) is needed by glib2-devel-2.35.8-1.el6.x86_64
        perl(Safe) is needed by glib2-devel-2.35.8-1.el6.x86_64
        perl(warnings) is needed by glib2-devel-2.35.8-1.el6.x86_64
`

**Comment by psi-4ward** [comment]
Any updates? 
We really need Apache in our images

**Comment by jperrin** [comment]
Agreed, @dustinlacewell can you provide a status on this? It's becoming a large problem.

**Comment by xrow** [comment]
Wrote a support request https://support.docker.com/hc/en-us/requests/14669 . It is somewhat ridiculous that there is no progess since such long time for such an blocker. 

As a workaround we were forced to pull up private registries, but we can`t share our efforts nor colloborate.

**Comment by damianoneill** [comment]
+1

**Comment by PaulHughes01** [comment]
+1

**Comment by rguiliani** [comment]
+1

**Comment by kambiz-aghaiepour** [comment]
+1

**Comment by kambiz-aghaiepour** [comment]
The suggested workaround didn't work with the automatic builds on hub.docker.com (i.e. yum install -y httpd || true) since it still doesn't actually install the needed httpd package.

**Comment by crashbit666** [comment]
I have same error!

`Installing : httpd-2.4.6-40.el7.centos.1.x86_64                                                                                                                                            1/1 
Error unpacking rpm package httpd-2.4.6-40.el7.centos.1.x86_64
warning: /etc/httpd/conf/httpd.conf created as /etc/httpd/conf/httpd.conf.rpmnew
error: unpacking of archive failed on file /usr/sbin/suexec: cpio: cap_set_file
  Verifying  : httpd-2.4.6-40.el7.centos.1.x86_64  `  

My host system is Ubuntu 16.04 and I've been using LXD (LxC) with ZFS and Dir mode.
My guest system is Centos 7.

**Comment by dustinlacewell** [comment]
Hello all. Thanks for all your patience with this issue. We have finally reached a resolution we feel comfortable with. As of today, builders are running Linux 4.4 with Docker 1.11 backed by OverlayFS. We have tested the cases we were able to reproduce and the issue appears to be resolved but we're interested in subsequent feedback.

**Comment by lvlie** [comment]
Hi Dustin,
My own builds are finally working again, I presume this solved it for all so I'll close this issue. 

Thanks!

**Comment by xrow** [comment]
@dustinlacewell Works for me. Thanks.

**Comment by dg-ratiodata** [comment]
@dustinlacewell Works for me too - https://hub.docker.com/r/feduxorg/centos-apache/. Thanks a lot.

**Comment by erikpb** [comment]
@dustinlacewell Works fine here too - https://hub.docker.com/r/naqoda/centos-apache-php/. Thanks a lot Dustin!

**Comment by radykal-com** [comment]
@dustinlacewell mines works too https://hub.docker.com/r/radykal/centos7-slave-jenkins-php/

**Comment by rhoerbe** [comment]
Now this appears on a local build using  Docker version 1.11.2, build b9f10c9/Linux 3.13.0-92-generic #139-Ubuntu SMP x86_64:

    docker run -it centos:centos7 bash
    yum -y install curl httpd
  
    Installing : httpd-2.4.6-40.el7.centos.4.x86_64         6/6
    Error unpacking rpm package httpd-2.4.6-40.el7.centos.4.x86_64
    error: unpacking of archive failed on file /usr/sbin/suexec: cpio: cap_set_file
    error: httpd-2.4.6-40.el7.centos.4.x86_64: install failed

This build has been working until recently.

**Comment by rhoerbe** [comment]
Update: If I run the same build on Centos7 instead of Ubuntu (Linux 3.10.0-327.el7.x86_64 #1 SMP x86_64), the probem does not occur.

**Comment by jperrin** [comment]
What storage were you using on ubuntu? This is a known issue with AUFS.

**Comment by rhoerbe** [comment]
Yes, the Ubuntu system exhibiting the problem uses aufs, the other on does not. What would be the remedy? The target system is not a production system yet, changes are easy.

**Comment by rhoerbe** [comment]
I guess setting another storage drive would help?

**Comment by jperrin** [comment]
Yeah, you'll need to use something other than AUFS

**Comment by atishayshukla** [comment]
Hi Guys, This still doesnt work with ubuntu 14.04 LTS as host and docker in kitchen driver pulling centos 7.1 image. Please help.

`Running handlers complete
       [2016-07-31T08:05:01+00:00] ERROR: Exception handlers complete
       Chef Client failed. 1 resources updated in 31 seconds
       [2016-07-31T08:05:01+00:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out
       [2016-07-31T08:05:01+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
       [2016-07-31T08:05:01+00:00] ERROR: yum_package[httpd] (httpd::install line 12) had an error: Chef::Exceptions::Exec: yum -d0 -e0 -y install httpd-2.4.6-40.el7.centos.4 returned 1:
       STDOUT: error: unpacking of archive failed on file /usr/sbin/suexec: cpio: cap_set_file failed - Operation not supported
       
       STDERR: Error unpacking rpm package httpd-2.4.6-40.el7.centos.4.x86_64
       
       [2016-07-31T08:05:03+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Converge failed on instance <default-centos-71>.  Please see .kitchen/logs/default-centos-71.log for more details
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration`
```

**Comment by AJNOURI** [comment]
07/2017 and still the same issue, cannot install **httpd** in a **centos** container

> error unpacking rpm package httpd-2.4.6-45.el7.centos.4.x86_64
> error: unpacking of archive failed on file /usr/sbin/suexec;597bcbad: cpio: cap_set_file
> error: httpd-2.4.6-45.el7.centos.4.x86_64: install failed
