### ISSUE TITLE
Markdown level 1 & 2 headings are not displayed on Docker Hub

### ISSUE THREAD

**Issue by chriswayg** [docker/hub-feedback#463]
##### Markdown level 1 & 2 headings are not displayed correctly any more on Docker Hub.
This makes the README files harder to follow.

### Examples:
Docker Hub h1
![screen shot 2015-11-15 at 12 22 51 am](https://cloud.githubusercontent.com/assets/13681327/11164553/1f044a6e-8b2f-11e5-9d19-acece644dbd0.png)

Github h1
![screen shot 2015-11-15 at 12 24 05 am](https://cloud.githubusercontent.com/assets/13681327/11164624/cffea6b0-8b30-11e5-9dbd-4f8a44cdc8ca.png)

#### Examples with h2 headings:
https://hub.docker.com/r/chriswayg/apache-php/
https://hub.docker.com/_/mariadb/
https://github.com/docker-library/docs/tree/master/mariadb

*as noticed in latest Firefox and Safari*

**Comment by ChristopherBiscardi** [comment]
There's already a fix for this in the pipeline. Closing as dupe in favor of #446
