### ISSUE TITLE
Automatic builds taking excessively long time

### ISSUE THREAD

**Issue by jakirkham** [docker/hub-feedback#464]
It seems that all builds are now taking an extremely long time. Even builds that take only a few minutes to build manually. Even though there is a transition to individual build queues, the time spent waiting and building seems excessive. For example, the `ubuntu_conda` image can be built in `1m17.441s` including pulling the new image. Details of the build can be seen here ( https://gist.github.com/jakirkham/299df32bff3d06fdec10 ). However, I am seeing build times that take several hours even after they leave the queue and begin. Can we get this speed back up into a reasonable time frame?

Note: At the time when this screenshot was taking you can see I have 1 job pending. However, I had no other jobs pending or building. All existing jobs were done or had errors/exceptions.

<img width="1554" alt="screen shot 2015-11-14 at 14 23 42" src="https://cloud.githubusercontent.com/assets/3019665/11165391/6716d492-8adb-11e5-9723-a3e1338660d9.png">

**Comment by mghazizadeh** [comment]
@jakirkham We are aware of this issue and working on reducing the backlog. Status is updated on https://status.docker.com/ Apologies for the inconvenience. 
Also please take note of the new capabilities in autobuilds to create dynamic builds (as opposed to build all), and "control over parallelism".  http://blog.docker.com/2015/11/upgraded-autobuild-docker-hub/

**Comment by jakirkham** [comment]
Thanks for the update @mghazizadeh. Also, thanks for the link to the post. I suspected the transition happened recently due to some noted changes, but wasn't sure when it was made official.

**Comment by jakirkham** [comment]
So, now the status says, "All Systems Operational". Definitely not the case. Seeing builds that don't get status updates or complete for hours still. Could we get the status changed back so as to be more accurate, at least?

**Comment by jakirkham** [comment]
I think this has improved. Thanks for looking into this. Closing...

**Comment by jakirkham** [comment]
Yeah, this is definitely back. Reopening...

**Comment by jakirkham** [comment]
Any news? Really eager to get a build done.

**Comment by jakirkham** [comment]
Also, an updated status would be nice. ( http://status.docker.com/ )

**Comment by degaray** [comment]
?

**Comment by jnordberg** [comment]
Still slow 😶

**Comment by hamelsmu** [comment]
Still slow

**Comment by brantje** [comment]
![image](https://user-images.githubusercontent.com/2758767/38105709-14dafff2-338d-11e8-98b8-65073cf24968.png)
Even my rPI3 can build faster than this.

**Comment by SkeLLLa** [comment]
The same on docker-cloud. Simple test builds that on local machine take 1-3s could be stuck in a queue for 3-6 hours. Also bringing up own build node has very limited distributives support and even there it doesn't work well.

**Comment by stepansib** [comment]
My builds are stuck with 'Queued' status for 3 (!!!) days and i cant cancel em. Also cant trigger new builds from github (

**Comment by jnordberg** [comment]
I wrote this as a drop in replacement for docker hub: https://github.com/jnordberg/leeroy
