### ISSUE TITLE
For automated builds, the root README.md always being used for the full description on Docker Hub

### ISSUE THREAD

**Issue by gchan** [docker/hub-feedback#467]
Previously, for automated builds the `README.md` being used for the full description on Docker Hub was the one in the same directory as the `Dockerfile`. This behaviour is described at https://docs.docker.com/docker-hub/builds/

> The build process looks for a README.md in the same directory as your Dockerfile. If you have a README.md file in your repository, it is used in the repository as the full description

However, this behaviour has changed recently (2-3 days ago) and the automated build process seems to use the `README.md` from the root of the git repository (rather than the one in the directory of the `Dockerfile`).

This is important to users who manage many `Dockerfile`s in a single git repository where each directory represents an image with its own `Dockerfile` and `README.md`.

You can observe the reported behaviour on my Docker Hub (https://hub.docker.com/u/gordonchan/). The corresponding git repository is (https://github.com/gchan/dockerfiles)

**Comment by Kaixhin** [comment]
Related bug at https://github.com/docker/hub-feedback/issues/402 (where I noted *this* issue in my comment).

**Comment by gchan** [comment]
Thanks @Kaixhin, glad it's just not me. I reported the issue on the #docker IRC channel in the weekend before realising this feedback channel was available.

**Comment by gchan** [comment]
This seems to be semi-resolved now. Sometimes the automated build system will still use the top-level README file.

**Comment by LeandroGuillen** [comment]
The same with our project (https://hub.docker.com/r/fiware/orion/), except that the randomness seems to be out: it is always the wrong top-level README.

**Comment by dsander** [comment]
This happens for us as well, except the base image does not show any readme at all https://hub.docker.com/r/cantino/huginn-single-process/ the one that derives from the base image shows the root readme (even though that might still be an old one) https://hub.docker.com/r/cantino/huginn/

**Comment by victorhcm** [comment]
+1

**Comment by FedericoFdez** [comment]
Same thing happening to us at https://hub.docker.com/r/ging/fiware-idm/.

Docker Hub is not only ignoring the `README.md` file placed in the Dockerfile repository, but also using one with a **different extension**: our `README.rst` file (placed in the root of the [git repository](https://github.com/ging/fiware-idm)).

Hope this is fixed soon :) Thanks!

**Comment by caervs** [comment]
Thank you for reporting this bug. We plan to have this issue resolved with the next release of autobuilds on the 15th.

**Comment by dsander** [comment]
Awesome, thank you @caervs!

**Comment by jakirkham** [comment]
Seems like this is fixed or are people still having issues with this.

**Comment by FedericoFdez** [comment]
At least for me it is.

Thanks!

**Comment by LeandroGuillen** [comment]
It seems to be working for us now. Thanks!

**Comment by dsander** [comment]
Works for us as well. Thanks for fixing it!

**Comment by jakirkham** [comment]
Should probably close this out. Thoughts @gchan? Is it now working for you?

**Comment by gchan** [comment]
Seems to be resolved now. Thanks @caervs!

**Comment by gavieira** [comment]
Apparently, the issue is back. Had to delete root README.md in order to use other files in Docker Hub description during autobuild.

**Comment by jrfaller** [comment]
> Apparently, the issue is back. Had to delete root README.md in order to use other files in Docker Hub description during autobuild.

Issue back for me also :( https://hub.docker.com/r/gumtreediff/gumtree

@gavieira It still works when you put back the root README file?

**Comment by gavieira** [comment]
> I haven't tried persevere I am not very happy to delete the main README of my github repo

My repo's root directory does not really require documentation, so I guess I will just leave it alone for now. 

Maybe you could try renaming (or at least changing the extension) of your root README. While this is by no means a definitive solution, you'll manage to keep your root documentation if it works.

**Comment by xezpeleta** [comment]
Hello,

Is this issue still unresolved?

I have an automated build with the following configuration:

```
Dockerfile location: /docker/Dockerfile
Build context: /
```
After the automated build Docker Hub chooses the root README, instead of choosing the one inside the `/docker` directory.

**Comment by riceyrice** [comment]
@federicofdez @jrfaller it looks like your builds are now using the correct README.md - can you remember how you fixed this? Thanks!
