### ISSUE TITLE
Suggestion: default master branch to `latest` tag

### ISSUE THREAD

**Issue by adamkdean** [docker/hub-feedback#472]
When you create an automated build, now that there is a branch matching, the default (and only) label will be master, to match the master branch. This means you have to manually create a master branch -> latest tag.

Can we get this to be default, so that `master => :latest`, which is generally the case?

If not, can we change the way that docker defaults to `:latest` in the way that web servers default to `index.*`?

**Comment by jakirkham** [comment]
:+1:

**Comment by rrarunan** [comment]
This is done. Right now, we have both the static rule `master -> latest` and the dynamic tag to match all branches by default. Both can be modified as needed.

**Comment by adamkdean** [comment]
Great, thanks!
