### ISSUE TITLE
DockerToolbox in windows Login/push doesnt works properly (With a workaround)

### ISSUE THREAD

**Issue by ppadial** [docker/hub-feedback#473]
Hi all,

My Use case is the following:
 I have a DockerHub account and I want to push an image to my repository.

So, the order to do this (having the image ready locally with the same name that my user/repo):
  1. Login using docker login
  2. Docker push

The First Error is when I tried to login automatically:
```
$ docker login --username=myuser --password=mypasswd --email=myemail
Error response from daemon: Unexpected status code [403] : <html><body><h1>403 Forbidden</h1>
Request forbidden by administrative rules.
</body></html>
```
Looking with a network monitor is trying to connect to https://registry-win-tp3.docker.io/v2/ and its getting this error.

If I specify the default index registry of docker io, the login is OK and creates the ~/.docker/config.json file propery with the following content
```
docker login --username=myuser --password=mypassword --email=myemail https://index.docker.io/v1/
WARNING: login credentials saved in C:\Users\myuser\.docker\config.json
Login Succeeded
```
The file content is the following:
```
{
	"auths": {
		"https://index.docker.io/v1/": {
			"auth": "MYHASH",
			"email": "myemail"
		}
	}
}
```
Ok, first sorted.
But everytime that I tried to push an image to my repos:
```
$ docker push index.docker.io/myuser/myrepo:latest
The push refers to a repository [docker.io/myuser/myrepo] (len: 1)
e9917e246cb6: Preparing
unauthorized: access to the requested resource is not authorized
```
After a bit of research, I had the suspicious that he is not using my Login credentials because he is trying to connect against the win registry so, i modified my config.json adding the same credentials for index.docker.io for the registry-win.. like this:
```
{
	"auths": {
		"https://index.docker.io/v1/": {
			"auth": "myhash",
			"email": "myemail"
		},
		"https://registry-win-tp3.docker.io/v1/": {
			"auth": "myhash",
			"email": "mydomain"			
		}
	}
}
```

And doing this, everything start to working properly.

Hope it helps

My Docker Installation Details are:
Operating System: Windows 10

**$ docker info**
```
Containers: 2
Images: 115
Server Version: 1.9.0
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 119
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.1.12-boot2docker
Operating System: Boot2Docker 1.9.0 (TCL 6.4); master : 16e4a2a - Tue Nov  3 19:49:22 UTC 2015
CPUs: 1
Total Memory: 7.696 GiB
Name: default
ID: IDUNNOIFTHISISIMPORTANT
Debug mode (server): true
 File Descriptors: 24
 Goroutines: 88
 System Time: 2015-11-18T16:13:52.691740338Z
 EventsListeners: 1
 Init SHA1:
 Init Path: /usr/local/bin/docker
 Docker Root Dir: /mnt/sda1/var/lib/docker
Username: myuser
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
```
**$ docker version**
```
Client:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   76d6bc9
 Built:        Tue Nov  3 19:20:09 UTC 2015
 OS/Arch:      windows/amd64

Server:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   76d6bc9
 Built:        Tue Nov  3 19:20:09 UTC 2015
 OS/Arch:      linux/amd64
```

**Comment by lvendrame** [comment]
Thanks, this worked for me!

**Comment by Nejuf** [comment]
Encountered the same issue, and the workaround worked for me as well.

**Comment by pradhanrak** [comment]
Worked for me. Thanks!

**Comment by jojuva** [comment]
Thanks for sharing the workaround!

**Comment by heli-tradedoubler** [comment]
worked quite nice! Thanks a  lot!

**Comment by brunomanzo** [comment]
++!!

**Comment by cespujunk66** [comment]
Hi! after trying the workaround i've this 
WARNING: Error loading config file:illegal base64 data at input byte 8
and the login problem persists

Any suggestions? Thx 




**Win 8.1**

**docker info**
WARNING: Error loading config file:illegal base64 data at input byte 8
Containers: 0
Images: 0
Server Version: 1.9.0
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 0
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.1.12-boot2docker
Operating System: Boot2Docker 1.9.0 (TCL 6.4); master : 16e4a2a - Tue Nov  3 19:
49:22 UTC 2015
CPUs: 1
Total Memory: 996.2 MiB
Name: default
ID: ZPHP:JH7P:7YES:75IR:LKYO:MJRZ:GJTQ:YFYN:MZJX:VC7H:JK7U:HST6
Debug mode (server): true
 File Descriptors: 11
 Goroutines: 19
 System Time: 2015-11-27T09:25:07.527909061Z
 EventsListeners: 0
 Init SHA1:
 Init Path: /usr/local/bin/docker
 Docker Root Dir: /mnt/sda1/var/lib/docker
Labels:
 provider=virtualbox

**docker version**
WARNING: Error loading config file:illegal base64 data at input byte 8
Client:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   76d6bc9
 Built:        Tue Nov  3 19:20:09 UTC 2015
 OS/Arch:      windows/amd64

Server:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   76d6bc9
 Built:        Tue Nov  3 19:20:09 UTC 2015
 OS/Arch:      linux/amd64

**Comment by cespujunk66** [comment]
Hi, 
 apparently after launching Kitematic everything  started to  behave in the right way.
Bye

**Comment by ppadial** [comment]
@cespujunk66: sometimes docker login fails, so in this case, my workaround is create the config.json entry manually adding in the auth parameter using YOURUSER:YOURPASSWORD in base64 (using a b64 encode) this usually works for me.

**Comment by amar-sanakal** [comment]
I'm on Windows 10. I have the same issue and the workaround did not help in my case, even after I manually created the jason file. I did see the base64 error which I fixed by updating the hash as recommended by @ppadial

**Comment by mrcaron** [comment]
Worked for me too. Thanks!

**Comment by cespujunk66** [comment]
@ppadial : thx! that was the problem.. the launch of  kinematic created  part of the json file for me, so i could figure out what i was missing out of the workaround .. the password in base64 ..( shame on me! ) 
hope this could help
bye

**Comment by karansinghkjs346** [comment]
Thanks , worked for mee too :)

**Comment by vinaydate** [comment]
Worked for me too. Thanks

**Comment by adrianeguez** [comment]
Great Thanks!

**Comment by kopax** [comment]
I have the same problem with  1.9.1 and this didn't worked for me

    Client:
     Version:      1.9.1
     API version:  1.21
     Go version:   go1.4.2
     Git commit:   a34a1d5
     Built:        Fri Nov 20 12:59:02 UTC 2015
     OS/Arch:      linux/amd64

    Server:
     Version:      1.9.1
     API version:  1.21
     Go version:   go1.4.2
     Git commit:   a34a1d5
     Built:        Fri Nov 20 12:59:02 UTC 2015
     OS/Arch:      linux/amd64

**Comment by lazarch** [comment]
Thanks , worked for me too :)

**Comment by countvidal** [comment]
this worked for me thanks

**Comment by uSide** [comment]
Thanks!

**Comment by shib1000** [comment]
https://github.com/docker/hub-feedback/issues/473

**Comment by shib1000** [comment]
Worked for me as well. Awesome help. Thanks

**Comment by cs94njw** [comment]
This wasn't quite as smooth for me.  I had to mess around with Kitematic - starting/stopping it, clicking on "Start", etc, etc, etc.  But eventually it worked.  Well... it's uploading the repository...

**Comment by anhhh11** [comment]
+1 work for me. Thanks.

**Comment by hranicka** [comment]
+1

Thank you @ppadial ! You saved me a lot of time a nerves :)

**Comment by thinkitdata** [comment]
Thank you for posting this.  I just ran into this issue and you saved me debugging time.  :-)

**Comment by hoangvuit** [comment]
Hi, could someone explain for me what the 'myhash' in the 'auth' property is?
How can I input username and password?

**Comment by hoangvuit** [comment]
Never mind, I used this:

### docker login --username=myuser --password="mypass" --email=myemail@gmail.com https://index.docker.io/v1/

and it works.

Thanks!

**Comment by DevNIX** [comment]
@hoangvuit Lol. Your workaround is working for me on Win10. Also you can keep it simpler with 
```
docker login https://index.docker.io/v1/
```
and get the same results. Do anybody know why? :/

**Comment by blachniet** [comment]
:+1: Workaround worked for me. This is a super annoying issue for a docker newcomer like me.

**Comment by BonnieSong** [comment]
Awesome!!! Thank you!!!

**Comment by askdaddy** [comment]
also work for me !!

MARK!!

**Comment by MaximCrabbe** [comment]
Thx for workaround!!!!

**Comment by mlushpenko** [comment]
+1 for the workaround, thanks :)

**Comment by thedole** [comment]
+1 for this workaround, it saved the day!

**Comment by cleggypdc** [comment]
+1 for the workaround, thanks!

**Comment by houtianze** [comment]
Thanks, it works. I feel Windows is a second class citizen in the Docker world.

**Comment by hayatbiralem** [comment]
Thank you, it works for me too :)

**Comment by vnarayan13** [comment]
You the man!

**Comment by introkun** [comment]
+1 for this workaround, it saved the day!

**Comment by moklas** [comment]
A huge thank you for the help!

**Comment by Soleferry** [comment]
Thank you so much for this :)

**Comment by ayushpratap** [comment]
It is not working for me.
unexpected error 403 is resolved but whenever i try to push the image it by saying "unauthorized: access to the requested resource is not authorized"
i tried your workaround but it didn't work .
And what I am suppose to write in "mydomain" my email-ID or username ?

**Comment by nutto** [comment]
Thanks you so much, this worked for me too! :)

**Comment by K-You** [comment]
Thanks a lot !

**Comment by wereldbolt** [comment]
Works for me too! Thanks a lot!

**Comment by tyagian** [comment]
make sure your config.jason file looks like this:
{
"auths": {
"https://index.docker.io/v1/": {
"auth": "<hash value>",
"email": "<email-d>"
},
"https://registry-win-tp3.docker.io/v1/": {
"auth": "<hash value>",
"email": "<hash value>"
}
}
}
<a href="http://networkengg.com/docker-login-failed-on-windows-403-forbidden-error/
">www.NetworkEngg.com</a>

**Comment by tyagian** [comment]
It works for me also after changing config.jason file.


<a href="http://networkengg.com/docker-login-failed-on-windows-403-forbidden-error/
">www.NetworkEngg.com</a>

**Comment by kaicarver** [comment]
thank you!

**Comment by cipriantepes** [comment]
It worked for me as well, thanks a lot. This command `docker login --username=myuser --password=mypassword --email=myemail https://index.docker.io/v1/`
successfully wrote the config.json file so I'd say that `https://index.docker.io/v1/` is essential.

After successfully logging in I had to add the extra code `https://registry-win-tp3.docker.io/v1` to be able to push.

**Comment by stevenrouk** [comment]
Thank you! Worked for me as well.

**Comment by tshepotema** [comment]
Worked for me as well...

![docker-push](https://cloud.githubusercontent.com/assets/4511288/12641902/0ba1df56-c5bb-11e5-8e48-b35c3d6af657.JPG)

**Comment by ppiatek** [comment]
Thanks. Worked for me as well!

**Comment by arctwelve** [comment]
Tested on Win10. There's a better workaround that doesn't require you make changes to `config.json`. Also, with the first workaround on this thread, using `$ docker logout` deletes your repo credentials. Use this instead if you don't want to keep changing the config.json:

1. Initially, make sure `c:\users\<username>\.docker\config.json` is blank (you only need to do this once).
2. Open up the Docker quickstart terminal
3. Login with `$ docker login https://index.docker.io/v2` (note the v2)
4. You'll be warned that the config doesn't exist the first time
5. At the 3 prompts, enter your Username, Password, and Email 
6. Login Succeeded - Your login credentials will be saved in `config.json` automatically.

Then every time after:
A. Login with `$ docker login https://index.docker.io/v2`
B. It will show your username in parenthesis
C. Hit enter. 
D. That's it!

Works for push and pull without any other credentials, and there is only one credential in `config.json` that doesn't need to be changed.

**Comment by nicky-lenaers** [comment]
@ppadial Adding the ``https://registry-win-tp3.docker.io/v1/`` made it work for me on Windows 10. Thanks!

**Comment by tcdev00** [comment]
Thanks @ppadial , worked for me as well.

The only thing is, the index.docker.io address should be written everytime?

**Comment by poonam-mscit** [comment]
Works for me. Thank you.

**Comment by thaJeztah** [comment]
We just merged a pull request,1 which should resolve this issue in docker 1.10; https://github.com/docker/docker/issues/19891.

**Comment by zhoukekestar** [comment]
Thanks.

**Comment by friism** [comment]
1.10 is out now and fixes this problem: https://github.com/docker/toolbox/releases/tag/v1.10.0

I move to close this issue.

**Comment by rrarunan** [comment]
As per @friism's comment, closing this issue.

**Comment by rtrujillor** [comment]
Works for me too!
Thanks!

**Comment by gusemery** [comment]
That worked for me as well

**Comment by mathiasconradt** [comment]
@friism @thaJeztah  Neither the workaround nor the Release 1.10 works on **Windows Server 2016 TP4** for "`docker push`", it only works for "`docker login`":

This is the result with **Docker version 1.10.0-dev, build 18c9fe0**, which was standard for TP4 as per documentation (https://aka.ms/tp4/New-ContainerHost).

```
PS C:\mysorba-build> docker -v
Docker version 1.10.0-dev, build 18c9fe0
PS C:\mysorba-build> docker login
Username (mathiasconradt):
Error response from daemon: Unexpected status code [403] : <html><body><h1>403 Forbidden</h1>
Request forbidden by administrative rules.
</body></html>
PS C:\mysorba-build> docker login https://index.docker.io/v1/
Username (mathiasconradt):
WARNING: login credentials saved in C:\Users\mlin\.docker\config.json
Login Succeeded
PS C:\mysorba-build> docker push mathiasconradt/mysorba
The push refers to a repository [docker.io/mathiasconradt/mysorba] (len: 1)
eba0bba1a3b1: Preparing
Error parsing HTTP response: invalid character '<' looking for beginning of value: "<html><body><h1>403 Forbidden</h1>\nRequest forbidden by administrative rules.\n</body></html>\n\n"
PS C:\mysorba-build>
```

I then downloaded the Docker Toolbox tagged 1.10 (**Docker version 1.10.0, build 590d5108**) and tried again, same 403 error:

```
PS C:\Windows\system32> & 'C:\Program Files\Docker Toolbox\docker.exe' -v
Docker version 1.10.0, build 590d5108
PS C:\Windows\system32> & 'C:\Program Files\Docker Toolbox\docker.exe' login
Username (mathiasconradt):
Password:
Error response from daemon: Unexpected status code [403] : <html><body><h1>403 Forbidden</h1>
Request forbidden by administrative rules.
</body></html>
```

My .docker/config.json contains:

```
{
	"auths": {
		"https://index.docker.io/v1/": {
			"auth": "<token>",
			"email": "mathias.conradt@gmail.com"
		},
		"https://registry-win-tp3.docker.io/v1/": {
			"auth": "<token>",
			"email": "mathias.conradt@gmail.com"
		}
	}
}
```

(I had added the https://registry-win-tp3.docker.io/v1/ section manually as per workaround mentioned in this ticket.)

@tshepotema I also tried your approach for `docker push` and prepended `index,docker.io/` before my image id, but it doesn't help.

```
PS C:\Program Files\Docker Toolbox> .\docker -v
Docker version 1.10.0, build 590d5108
PS C:\Program Files\Docker Toolbox> .\docker login https://index.docker.io/v1/
Username (mathiasconradt):
Password:
WARNING: login credentials saved in C:\Users\mlin\.docker\config.json
Login Succeeded
PS C:\Program Files\Docker Toolbox> .\docker push index.docker.io/mathiasconradt/mysorba
The push refers to a repository [docker.io/mathiasconradt/mysorba] (len: 1)
eba0bba1a3b1: Preparing
Error parsing HTTP response: invalid character '<' looking for beginning of value: "<html><body><h1>403 Forbidden</h1>\nRequest forbidden by administrative rules.\n</body></html>\n\n"
```

**Comment by ppadialitrs** [comment]
Is possible get your network traffic for this reques + response?

**Comment by mathiasconradt** [comment]
@ppadialitrs Not sure how to get the Docker traffic. No idea how to use [Wireshark](https://www.wireshark.org/) to actually see request and response bodies. I tried [Fiddler](http://www.telerik.com/fiddler), but I don't see Docker traffic (i.e. from login request via powershell). Not sure how to configure the Docker daemon (in my case the Docker daemon is on Windows as a service using C:\Windows\system32\nssm.exe) to go through a http proxy - from my understanding that's what I would need to do to see the Traffic in Fiddler. Do you have any advice what's the best way? I managed to see traffic via browser, wget and git; I could get git traffic by using a http.proxy parameter; looking for something similar for the Docker daemon. I guess I just wait for Windows 2016 TP5 and check again.

**Comment by mathiasconradt** [comment]
@ppadial 

When I try to push with my old **Docker version 1.10.0-dev, build 18c9fe0**, which came with Windows2016 TP4, but using the **workaround** mentioned above to adjust the config.json:

`docker push mathiasconradt/mysorba`

it still tries to push to "https://registry-win-tp3.docker.io v2" as I can see in the log (complete log: http://pastebin.com/CLUbYazq):

```
time="2016-03-31T11:12:40.688736700+02:00" level=debug msg="Calling POST /v1.22/images/mathiasconradt/mysorba/push"
time="2016-03-31T11:12:40.691737800+02:00" level=info msg="POST /v1.22/images/mathiasconradt/mysorba/push?tag="
time="2016-03-31T11:12:40.695738200+02:00" level=debug msg="Trying to push docker.io/mathiasconradt/mysorba to https://registry-win-tp3.docker.io v2"
time="2016-03-31T11:12:41.124763100+02:00" level=debug msg="Checking \"\" against graph.repository{\"latest\":\"4c2ab095db038c449e77e22abf2419be001a60370a3d16650a34b3850ed76bc5\"}"
time="2016-03-31T11:12:41.132762900+02:00" level=debug msg="Pushing repository: mathiasconradt/mysorba:latest"
[...]
time="2016-03-31T11:12:41.739801700+02:00" level=debug msg="hcsshim::DestroyLayer succeeded flavour=1 id=4c2ab095db038c449e77e22abf2419be001a60370a3d16650a34b3850ed76bc5-837938234"
time="2016-03-31T11:12:41.793801300+02:00" level=debug msg="Not continuing with error: Error parsing HTTP response: invalid character '<' looking for beginning of value: \"<html><body><h1>403 Forbidden</h1>\\nRequest forbidden by administrative r
body></html>\\n\\n\""
time="2016-03-31T11:12:41.786800100+02:00" level=debug msg="Can't close tar writer: io: read/write on closed pipe"
```

even though I have https://index.docker.io/v1/ added to my config.json:

```
{
	"auths": {
		"https://index.docker.io/v1/": {
			"auth": "bWF0aGlhc2NvbnJhZHQ6U3VubnkyMDEyIQ==",
			"email": "mathias.conradt@gmail.com"
		},
		"https://registry-win-tp3.docker.io/v1/": {
			"auth": "bWF0aGlhc2NvbnJhZHQ6U3VubnkyMDEyIQ==",
			"email": "mathias.conradt@gmail.com"
		}
	}
}

```

I downloaded the updated **Docker version 1.10.0, build 590d5108** mentioned above, but I can't get it started as daemon. When I run

`.\docker.exe daemon -D -b "Virtual Switch"`

the daemon does not stay alive but exits, without any error though (complete log of daemon startup: http://pastebin.com/u3NQAFpP).

```
time="2016-03-31T11:17:35.664900100+02:00" level=warning msg="/!\\ DON'T BIND ON ANY IP ADDRESS WITHOUT setting -tlsverify IF YOU DON'T KNOW WHAT YOU'RE DOING /!\\"
time="2016-03-31T11:17:35.676900300+02:00" level=debug msg="Server created for HTTP on tcp (127.0.0.1:2375)"
time="2016-03-31T11:17:35.682901200+02:00" level=debug msg="Using default logging driver json-file"
time="2016-03-31T11:17:35.687900900+02:00" level=debug msg="WindowsGraphDriver InitFilter at C:\\ProgramData\\docker\\windowsfilter"
time="2016-03-31T11:17:35.694902300+02:00" level=info msg="[graphdriver] using prior storage driver \"windowsfilter\""
time="2016-03-31T11:17:35.699903400+02:00" level=debug msg="Using graph driver windowsfilter"
time="2016-03-31T11:17:35.688901600+02:00" level=debug msg="Stackdump - waiting signal at Global\\docker-daemon-7560"
time="2016-03-31T11:17:35.713908000+02:00" level=debug msg="Calling proc"
time="2016-03-31T11:17:35.717901000+02:00" level=debug msg="hcsshim::GetSharedBaseImages  - succeeded output={\"Images\":[{\"CreatedTime\":\"2015-10-30T09:57:20.0990000Z\",\"Path\":\"C:\\\\ProgramData\\\\Microsoft\\\\Windows\\\\Images\\\\CN=Microsoft_NanoServer_10.0.1058
6.0\",\"Name\":\"NanoServer\",\"Version\":\"10.0.10586.0\",\"Size\":748048187}\n,{\"CreatedTime\":\"2015-10-30T10:46:12.5490000Z\",\"Path\":\"C:\\\\ProgramData\\\\Microsoft\\\\Windows\\\\Images\\\\CN=Microsoft_WindowsServerCore_10.0.10586.0\",\"Name\":\"WindowsServerCore
\",\"Version\":\"10.0.10586.0\",\"Size\":9653475340}\n]}"
[...]
[...]
time="2016-03-31T11:17:37.358997600+02:00" level=debug msg="hcsshim::NameToGuid Name e6b70823968ae43750efb9b70fb740e8fec54c18145548d5f56628cfe90bf7a9"
time="2016-03-31T11:17:37.365996100+02:00" level=debug msg="Calling proc"
time="2016-03-31T11:17:37.369996700+02:00" level=debug msg="hcsshim::NameToGuid Name e138026187340d52a13487f14e2cf079ce3811e3ede3622e43eb77597cf5b344"
time="2016-03-31T11:17:37.382997900+02:00" level=debug msg="Calling proc"
PS C:\docker-versionen\1.10.0>
```
