### ISSUE TITLE
Issue with docker login & push with Docker Default Registry - Windows ENV - 1.9.1-RC1

### ISSUE THREAD

**Issue by Miguel-Fontes** [docker/hub-feedback#477]
# Description of problem
Issues with ‘docker login’ on Windows.
The command returns Status Code 403 – Request forbidden by administrative rules.

# Docker version
1.9.1-rc1

# Docker info

<img width="742" alt="docker_meta" src="https://cloud.githubusercontent.com/assets/15656072/11188137/8fcff33c-8c70-11e5-93e1-dadfa0446683.png">

# Environment details (AWS, VirtualBox, physical, etc.):
Vritual Box Provider

# How reproducible:
Just input ‘docker login’ into CLI without adding any providers.

# Steps to Reproduce:
1. open CLI on Windows
2. docker login <your login info>
3. check return

### Actual Results:

    Error response from daemon: "Unexpected status code [403] - <html><body><h1> 403 Fobidden</h1> Request forbidden by administrative rules. </body></html>"

<img width="742" alt="login_forbidden_all" src="https://cloud.githubusercontent.com/assets/15656072/11188201/dbcf76b8-8c70-11e5-9f07-e66c4d50b1b5.png">

### Expected Results:
Successful login into Docker default registry for Windows and full integration with docker hub.

# Additional info:
After some analysis of the source code I’ve detected that we have different registry URLs for Windows and UNIX.

* Windows: https://registry-win-tp3.docker.io/v1/
* Unix: https://index.docker.io/v1/

I’m using the freshly baked 1.9.1-rc1

While both urls are responding to requests, playing with docker login and those data, i could notice two different behaviors.
- Environment Windows + Docker Login with https://registry-win-tp3.docker.io/v1/
  - Returns Request forbidden by administrative rules
- Environment Windows + Docker Login with https://index.docker.io/v1/
  - Login succeeds.
  - Still can’t docker push. Command returns: unauthorized: access to the requested resource is not authorized.

Actually, checking the code, I could not detect an actual problem with the docker/docker but maybe it’s an registry issue.

**Important:** I've opened this [same issue at Docker/Docker](https://github.com/docker/docker/issues/18019) early but after some tests we find out that this happens ONLY with the dockerHub Service. Tests with Tutum and Quay.io were successful.

**Comment by JigSawFr** [comment]
Related to : https://github.com/docker/hub-feedback/issues/473 :arrow_right: 
With work around

**Comment by kanthamashokreddy** [comment]
docker login --username=xxxxxxxxx --email=xxxxxxx@xxx.com https://index.docker.io/v1/

try adding this https .... after email it will work in windows

**Comment by abobwhite** [comment]
Another one of the random things that does not work on Windows. So many little pieces to jiggle after googling and spending hours reading through threads like this one. Nonetheless, @kanthamashokreddy your solution worked as helped me over at least one more Docker hurdle. Holy cow this was supposed to be easy!

**Comment by JimyRyan** [comment]
@kanthamashokreddy For me too, your solution work. Before I change my config.json, I 2 identical configuration for "https://index.docker.io/v1/"

**Comment by thaJeztah** [comment]
We just merged a pull request,1 which should resolve this issue in docker 1.10 (to be released soon) https://github.com/docker/docker/issues/19891.

**Comment by friism** [comment]
1.10 is out now and fixes this problem: https://github.com/docker/toolbox/releases/tag/v1.10.0

I move to close this issue.

**Comment by rrarunan** [comment]
As per @friism closing this issue.

**Comment by mathiasconradt** [comment]
@friism Neither the workaround nor the Release 1.10 works on **Windows Server 2016 TP4**:

This is the result with **Docker version 1.10.0-dev, build 18c9fe0**, which was standard for TP4 as per documentation (https://aka.ms/tp4/New-ContainerHost).

```
PS C:\mysorba-build> docker -v
Docker version 1.10.0-dev, build 18c9fe0
PS C:\mysorba-build> docker login
Username (mathiasconradt):
Error response from daemon: Unexpected status code [403] : <html><body><h1>403 Forbidden</h1>
Request forbidden by administrative rules.
</body></html>
PS C:\mysorba-build> docker login https://index.docker.io/v1/
Username (mathiasconradt):
WARNING: login credentials saved in C:\Users\mlin\.docker\config.json
Login Succeeded
PS C:\mysorba-build> docker push mathiasconradt/mysorba
The push refers to a repository [docker.io/mathiasconradt/mysorba] (len: 1)
eba0bba1a3b1: Preparing
Error parsing HTTP response: invalid character '<' looking for beginning of value: "<html><body><h1>403 Forbidden</h1>\nRequest forbidden by administrative rules.\n</body></html>\n\n"
PS C:\mysorba-build>
```

I then downloaded the Docker Toolbox tagged 1.10 (**Docker version 1.10.0, build 590d5108**) and tried again, same 403 error:

```
PS C:\Windows\system32> & 'C:\Program Files\Docker Toolbox\docker.exe' -v
Docker version 1.10.0, build 590d5108
PS C:\Windows\system32> & 'C:\Program Files\Docker Toolbox\docker.exe' login
Username (mathiasconradt):
Password:
Error response from daemon: Unexpected status code [403] : <html><body><h1>403 Forbidden</h1>
Request forbidden by administrative rules.
</body></html>
```

My .docker/config.json contains:

```
{
	"auths": {
		"https://index.docker.io/v1/": {
			"auth": "<token>",
			"email": "mathias.conradt@gmail.com"
		},
		"https://registry-win-tp3.docker.io/v1/": {
			"auth": "<token>",
			"email": "mathias.conradt@gmail.com"
		}
	}
}
```

(I had added the https://registry-win-tp3.docker.io/v1/ section manually as per workaround mentioned in this ticket.)
