### ISSUE TITLE
Automated Build Not updating Dockerfile & Not triggering WebHooks

### ISSUE THREAD

**Issue by gregkeys** [docker/hub-feedback#478]
Our build ran as expected when we updated our github repo, but when the build completed it did not update the dockerfile visible at hub.docker.com and it did not trigger the webhooks at all, last webhook triggered was 6 hours ago.

**Comment by bcwalrus** [comment]
@gregkeys Could you give the repo name so we can look into it?

**Comment by ephillipe** [comment]
I have same problem. I updating my Dockerfile's in Github but the automated build of Docker not firing.

**Comment by karalabe** [comment]
Same issue, neither do the automatic builds run, nor can I trigger any repos manually. (e.g. https://hub.docker.com/r/karalabe/xgo-base/)

**Comment by nakedpony** [comment]
the same issue for me. I have a private repo: https://github.com/cryptogates/docker But the ssh keys were deployed successfully.

**Comment by etiennebatise** [comment]
I am having a similar problem here : https://github.com/etiennebatise/docker-hyde . Public repo, simple really simple dockerfile.

**Comment by AllYourBase** [comment]
Similar problem: the automated build for [my image](https://hub.docker.com/r/allyourbase/imagemagick-q8/) *was* triggered, but the [Dockerfile](https://hub.docker.com/r/allyourbase/imagemagick-q8/~/dockerfile/) on hub.docker.com wasn't updated to match the [Dockerfile](https://github.com/AllYourBase/docker-imagemagick-q8/blob/master/6.8.9-10_q8/Dockerfile) on Github.

No webhooks configured.

**Comment by abuisine** [comment]
Same thing here, I created a bunch of automatic builds and, although my images are build and available, the Dockerfile do not show up

**Comment by davidjbrewer** [comment]
My Dockerfile is not showing up either on automated builds. I'm sure you're on this by now, but I chimed in anyway.

**Comment by gezims** [comment]
Similar to me: the automated build for my images was triggered successfully, but the Dockerfile which is under '/somerepo' on dockerhub was not showed up.

**Comment by salimane** [comment]
I'm having the same problem for https://github.com/meltwater/docker-cleanup
Thanks

**Comment by joschne** [comment]
the same issue for me. I have a private repo: https://github.com/joschne/geovistory. Automated Build worked before, but not anymore. When clicking on "Manually trigger a build" it shows "triggered" but nothing happens. Thx

**Comment by antitree** [comment]
Seems like the same issue for me. When I originally setup the repo, it was fine but now the tags and branches do not sync and builds do not automatically run for changes in the branches. https://hub.docker.com/r/antitree/private-tor/builds/

**Comment by bcwalrus** [comment]
Looking into the issue of builds not triggering.

@antitree The branch/tag issue is a weird one since I see it auto-building for `master`.

**Comment by bcwalrus** [comment]
@antitree I see that your push to `release-0.2.8` etc today triggered builds automatically. But I have a hard time tracing what happened on July 10, since I don't know what the build rules were at that time. Did you modify the build configuration since?

**Comment by bcwalrus** [comment]
@joschne On May 10, the build service had very high load, which caused delay in build submission, thus giving the impression that nothing happened. Builds seems to be triggering after that. I guess you noticed a similar issue on June 10, following an EC2 partial outage. Sorry about the bad user experience. We know that build reliability is super important, and our near-term focus is all about that.

**Comment by klingtnet** [comment]
The triggered build on pushes to the github repo has never worked for none my docker containers, either. I always have to trigger the manually.

**Comment by bcwalrus** [comment]
@klingtnet Using https://github.com/klingtnet/docker-cherrymusic as an example, DockerHub has not been getting any webhook notifications about its pushes. Could you check the GH repo webhooks (or service hook integration) to see whether that is configured?

**Comment by klingtnet** [comment]
@bcwalrus This was my fault, I haven't setup the github service hook.
The *build settings* page on docker hub looked fine to me  so I wasn't aware that I had to add the docker webhook manually.
![hub](https://cloud.githubusercontent.com/assets/1538057/17691409/8c503928-6394-11e6-9928-94e24ab090eb.png)

**Comment by bcwalrus** [comment]
@klingtnet Glad it's working!

**Comment by digas** [comment]
Hey i found this searching for the almost the same problem but i have the tick box active .
My problem is the yesterday the first build worked successfully . The second build had a very newbie :D erro and it failed with error , but when it was build i forgot that the trigger was still on Master repo and i just updated the README file. 
When i have tried to cancel it ... it got stuck so i have now a 1- successful   2 - fail e the 3 - is Queued ... for a long time :D
My repo is public (both)
https://hub.docker.com/r/diogoserra/freeswitch/
Thanks for the help
