### ISSUE TITLE
Automated docker build fails with exception, docker client/server API version mismatch

### ISSUE THREAD

**Issue by d4goxn** [docker/hub-feedback#482]
The logged error is identical to #392, but the cause must be different:

```
Client: Version: 1.8.1 API version: 1.20 Go version: go1.4.2 Git commit: d12ea79 Built: Thu Aug 13 02:49:29 UTC 2015 OS/Arch: linux/amd64
Server: Version: 1.8.3-rc4 API version: 1.20 Go version: go1.4.2 Git commit: 9f1606a Built: Fri Oct 2 23:36:50 UTC 2015 OS/Arch: linux/amd64
```

What do "Client" and "Server" refer to? I triggered a build through the web interface, so Client couldn't possibly be my own Docker client.

There are no non-utf8 chars in the Dockerfile or readme. This was the first (and second) run of an automated build that is associated with a private Github repository. This container is based on a private container, which is owned by an organization that I belong to, although this image is under my account. Dockerhub was able to fetch the deployment key automatically. The container builds fine locally.

Does anyone see a reason for failure, or have any suggestions for further troubleshooting?

**Comment by RongxinZhang** [comment]
+1 having the same issue.

**Comment by cle1994** [comment]
+1 same issue

**Comment by guillaumegiordana** [comment]
+1
