### ISSUE TITLE
docker autobuilde

### ISSUE THREAD

**Issue by fusengine** [docker/hub-feedback#484]
my build block to 1hour to pushed is normal??
and status is started to 1 hour.

<img width="820" alt="capture d ecran 2015-11-24 a 13 59 33" src="https://cloud.githubusercontent.com/assets/7295655/11367393/af4f13e8-92b3-11e5-8839-de5d6aac444b.png">

**Comment by rippinrobr** [comment]
Autobuild and manaul builds are not working for me. They don't start.

**Comment by fusengine** [comment]
me to

**Comment by daniel-dihardja** [comment]
same problems here

**Comment by fusengine** [comment]
3 hour pending :S

**Comment by dustinlacewell** [comment]
We had an issue where a node erroneously filled up our queue backend overtime. We've increased the size of the queue database ten-fold and are investigating the behavior which we've identified. There's a substantial backlog of builds in the queue now, however things are operational.

Sorry for the trouble.

**Comment by fusengine** [comment]
Are you sure ?

**Comment by fusengine** [comment]
Is not resolve i push if to trigger and not run why ?

**Comment by dustinlacewell** [comment]
To clarify, there is a substantial backlog that may take a hours to process. Adding additional build requests to the end of that queue will not speed up your service availability.

Again, sorry for such trouble.

**Comment by kentmw** [comment]
Not a big surprise, but I'm having this issue as well

**Comment by fusengine** [comment]
I local my images is up and i push it to automated build i have error why?

**Comment by paulopez78** [comment]
No working at all here! Any feedback from the maintainers?

**Comment by dnorth98** [comment]
My build has been "pending" for approx 5 hours now....how big is the queue??!

**Comment by juicelink** [comment]
not working too
