### ISSUE TITLE
Proposal: Send email if autobuild fails

### ISSUE THREAD

**Issue by aanm** [docker/hub-feedback#494]
I usually use 2 different Dockerfiles, one for development and other for productions, unfortunately I didn't realize the automatic build was failing in dockerhub. It would be a good idea to add something that could sent an email in case a autobuild fails.

**Comment by envygeeks** [comment]
@aanm it does email you if a build fails.  I've had a repo failing for days and I get a note every time it's parent repository updates and it builds from that parent repository. Enable the notifications at: https://hub.docker.com/account/notifications/

**Comment by aanm** [comment]
@envygeeks You're right! I had that option unset. Thank you!
