### ISSUE TITLE
Search for docker images is slow/does not work

### ISSUE THREAD

**Issue by Brett55** [docker/hub-feedback#495]
When searching for a docker image within my org, it works half the time. Often returning wrong results

**Comment by bcwalrus** [comment]
@Brett55 Could you provide some examples or screenshots?

**Comment by Brett55** [comment]
Basically, when you type a known image, it does not filter the results
correctly. It works half the time, if I type really slow. Or if I hit the
"X" in the search dialog and try again, it sometimes works.
In this screenshot, we have an image called roadtracker. It doesn't come up
even after waiting.

[image: Inline image 1]

**Comment by rrarunan** [comment]
@bcwalrus @Brett55 I have a fix coming up soon, for this.

**Comment by nebuk89** [comment]
Long since fixed. Closing
