### ISSUE TITLE
Delete tag link is hidden/doesn't display

### ISSUE THREAD

**Issue by posita** [docker/hub-feedback#498]
From @ruffsl's <https://github.com/docker/hub-feedback/issues/68#issuecomment-162010161>:

> I saw the blue text "Delete" last night when I check the deploy, but you seem to be right in that it appears to be oddly hidden currently:

> ![https://cloud.githubusercontent.com/assets/2293573/11594656/35507410-9a79-11e5-84dc-96f40a91ed3a.gif](https://cloud.githubusercontent.com/assets/2293573/11594656/35507410-9a79-11e5-84dc-96f40a91ed3a.gif)

**Comment by yoanisgil** [comment]
Maybe a CSS issue?

![opacity](https://cloud.githubusercontent.com/assets/918271/11595339/e105e2b0-9a7c-11e5-9dde-5b6084f57fe1.png)

**Comment by nhsiehgit** [comment]
Hi all 

Sorry for the persistent bugginess. We had rushed a patch last night that overlooked this.
This should be fixed now.

Closing this issue

**Comment by yoanisgil** [comment]
Thanks. LGTM now.

**Comment by ruffsl** [comment]
Thanks

**Comment by jakirkham** [comment]
So, this seems to be kind of fixed. The text doesn't appear to be there when the mouse isn't there. Then when the mouse appears in the right row. The delete text appears and turns red on mouseover. Would be nice if the text was always there.

**Comment by JeremJR** [comment]
@posita thanks for reporting
@nhsiehgit thanks for the fix

**Comment by ruffsl** [comment]
@jakirkham I think that this is intentional, a sort of UI design to only reveal the option when you mouse over. I sort of like it as its clean. Although might prove troublesome if you don't have a mouse, like when monitoring from tablet.

**Comment by nhsiehgit** [comment]
Hey guys,

Thanks for all the comments. We've been going back and forth on this with our designers. Currently we just wanted to get it out since it's been a highly requested feature, and felt that having the delete displayed for every tag would be a bit noisy and we didn't want to make that the focus of the page. 

We'll be moving towards persistent delete icons for each tag which will be deployed soon so keep tuned.

Thanks again

**Comment by jakirkham** [comment]
I like the trash icon that was added. :+1:
