### ISSUE TITLE
default visibility of repositories is public in my organization

### ISSUE THREAD

**Issue by madeleineth** [docker/hub-feedback#499]
In my organization, the default repository visibility (Settings > Default Visibility) is set to private.

However, if I click "Create Repository," the default value of the "Visibility" dropdown is "public."

I created the organization today and upgraded it immediately to a "Micro" plan. There are fewer than five repositories in it.

Google Chrome 47.0.2526.73, Mac OS X

**Comment by ChristopherBiscardi** [comment]
@madeleineth I was unable to reproduce this issue. Is it possible that the namespace when you went to create a repo was your user namespace?

**Comment by madeleineth** [comment]
@ChristopherBiscardi I would've sworn I'd checked that, but I can't reproduce now, either. My best guess is that I selected the organization in the dropdown below the whale logo, clicked "Create Repository," and missed the fact that the dropdown on https://hub.docker.com/add/repository/ is my personal account, regardless of what repository was selected below the whale.

**Comment by nhsiehgit** [comment]
@ChristopherBiscardi - I was able to repro. will look into it
