### ISSUE TITLE
Support RegEx pattern capture groups for build settings

### ISSUE THREAD

**Issue by wernight** [docker/hub-feedback#501]
Currently it's possible for example to build all branches/tags matching a pattern and reuse that entire tag/branch name as the Docker tag, but it's not possible (or not described) how to capture part of it.

My main use case is to have all Git tags like `v1.1.0` generate Docker tags `1`, `1.1` and `1.1.0` via for example 3 build rules:

 * Tag `/$v(\d+)/` builds *Docker Tag Name* `\1`
 * Tag `/$v(\d+\.\d+)/` builds *Docker Tag Name* `\1`
 * Tag `/$v([0-9.]+)/` builds *Docker Tag Name* `\1`

PS: On Docker Hub side, it should make use of caching or smartness to avoid doing really 3 full builds.

**Comment by nlf** [comment]
+1 I'd love to see this

**Comment by bcwalrus** [comment]
When specifying the docker tag name, try using `{\1}`, `{\2}`, etc to refer to your capture groups. #UndocumentedFeature

**Comment by wernight** [comment]
Try using? You mean it's working and you've tested it?

**Comment by rrarunan** [comment]
@wernight thanks for the update! Closing this issue.
