### ISSUE TITLE
Double pushing of parent image layers when inherit

### ISSUE THREAD

**Issue by rsutormin** [docker/hub-feedback#503]
I have a problem with Dockerhub. I made two images: testimg1 and testimg2 inheriting first one.
Dockerfile for testimg1:
```
FROM ubuntu:14.04
RUN apt-get update
RUN apt-get -y install git
RUN apt-get -y install default-jdk
RUN mkdir -p /work
ENTRYPOINT [ "ls", "-l" ]
CMD [ "/" ]
```
Then I build it with ```docker build --rm -t <dockerhub-user>/testimg1:latest .``` and push it to dockerhub. It takes some time to push about 700 megabytes.
Dockerfile for testimg2:
```
FROM <dockerhub-user>/testimg1:latest
WORKDIR /work
RUN git clone https://github.com/danfang/Algorithms
WORKDIR /work/Algorithms
RUN mkdir -p bin
RUN javac ./src/problem07/*.java -d ./bin
ENTRYPOINT [ "java", "-cp", "./bin", "problem07.PrimeNumbers" ]
CMD [ "0" ]
```
Then I build it too with ```docker build --rm -t <dockerhub-user>/testimg2:latest .``` and push it too. At this time I expect to skip layers from first image since they were already pushed. It's supposed to be helper image I'm going to use for other inheriting images (they use git/java). But pushing process includes parent layers too. So instead of pushing about 1 meg I have to wait for several minutes until 700 megs are pushed again.

**Comment by aaronlehmann** [comment]
It's currently not possible to share layer data between multiple repositories. The protocol needs some adjustments to do this in a secure way - your Docker instance would prove to the registry that it has access to `testimg1`, and is allowed to reuse those layers for `testimg2`. There's been a lot of discussion about implementing this, so hopefully this will be fixed soon.

Note that this is not a Hub-specific issue. It applies to any registry that uses the v2 protocol.

As a workaround, using the same repository name with different tags (such as `<dockerhub-user>/testimg1:tag1` and `<dockerhub-user>/testimg1:tag2`) should avoid the need to repush layers. Also, after the first time the layers are pushed to any given repository, it shouldn't be necessary to push them again.

**Comment by rsutormin** [comment]
Thanks a lot for your answer. Is there any open discussion or open issues related to prove of access between repos (I mean your phrase "...your Docker instance would prove to the registry that it has access...")? I would like to refer them in the project I'm working in.

**Comment by aaronlehmann** [comment]
@rsutormin: There's some discussion about this in https://github.com/docker/distribution/issues/634 and https://github.com/docker/distribution/issues/908

**Comment by rrarunan** [comment]
Thanks for the issue. Please follow the discussion at https://github.com/docker/distribution/issues/634 & https://github.com/docker/distribution/issues/908 for this issue.
