### ISSUE TITLE
Creating automated build for bitbucket repo containing a slash returns 404

### ISSUE THREAD

**Issue by jheander** [docker/hub-feedback#505]
Hi,

I'm trying to create an automated build for one of my bitbucket repos, but since the repo contains a slash "/" in its name, I just get a 404 from Docker Hub instead of the configuration form. Maybe you should quote or sanitize the bucket names so it does not interfere with your paths?

Regards
Johan

**Comment by fxdgear** [comment]
@jheander Thanks for reporting. We'll get on this.
