### ISSUE TITLE
Select an image tag and update the pull command accordingly

### ISSUE THREAD

**Issue by oncletom** [docker/hub-feedback#51]
![screen shot 2015-06-12 at 21 31 55](https://cloud.githubusercontent.com/assets/138627/8139338/b140d000-114a-11e5-8261-7fbf3a8ad1f2.png)

It might be a simple thing but giving the ability to click/tag on a tag to copy/paste the appropriate pull command and/or image name (like `library/tomcat:6.0-jre7`, to paste after a `FROM` instruction) would be a cute time saver.

What do you think about it?

**Comment by ChristopherBiscardi** [comment]
I really like this idea. We've been discussing something similar in which the `docker pull command` on the right would update but having it "on the tag" seems more useful. The display of Tags is going to undergo a change in the near future, so we'll try to work this in.
