### ISSUE TITLE
Only first ten collaborators displayed in collaborators page

### ISSUE THREAD

**Issue by eNcacz** [docker/hub-feedback#513]
I have private repo and I add there twelve collaborators but only first ten collaborators is displayed in web UI. I can add another collaborator. No error is displayed but newly added collaborator is not visible in UI. When I watch network communication in google chrome then I see that number of collaborators is 12:
`{"count": 12, "next": "https://hub.docker.com/v2/repositories...`
It seems that the page length is set to 10 but there is no option to display next page.

**Comment by rrarunan** [comment]
@eNcacz Thanks for the report. We will plan a fix for this.

**Comment by ahnick** [comment]
@rrarunan What is the status on this issue?  I just ran across this today and I thought there was a limit at 10 people, so I ended up removing old individuals.  It seems like this should be a relatively simple fix.

**Comment by stefanmet** [comment]
@rrarunan Same here, I almost deleted existing users in order to test, but luckily found this issue page before doing so. This issue has been reported for a while - is there any fix in sight already? It would be much appreciated. Thanks!
