### ISSUE TITLE
Markdown header 1 & 2 not rendered properly

### ISSUE THREAD

**Issue by marcelstoer** [docker/hub-feedback#515]
Compare 
https://github.com/marcelstoer/docker-nodemcu-build
with
https://hub.docker.com/r/marcelstoer/nodemcu-build/

and you'll see that on Docker Hub the Markdown headers 1 & 2 are not rendered as headers. For header 3+ it seems fine. I also tried to use the `==`/`--` and `# header #` notation  but that makes no difference.

**Comment by janeczku** [comment]
Duplicate of #446

**Comment by marcelstoer** [comment]
Thanks for the dup report.

**Comment by janeczku** [comment]
:sunglasses: NP
