### ISSUE TITLE
Docker Hub timeout in automated build

### ISSUE THREAD

**Issue by neo-apz** [docker/hub-feedback#519]
I'm using automated build to create docker images for a benchmark suite. In one of the benchmarks, which is web search, I have to use a very big index file (11GB). My image is not being built, and I'm receiving this error :`The build has timed out.`

But when I check the build log, which is very long, in the last line I can see that it has actually built successfully: `Successfully built 4c84c7ec04c6`

It seems that the worker responsible for creating this image, loses its connection with its master (registry node), while it is still processing and building the image. It's probably due to the fact that it takes a couple of hours to download the index file.

What can I do to prevent this from happening?

For more information, you can check the build log [here][1].

Thanks.

  [1]: https://hub.docker.com/r/cloudsuite/websearch/builds/bjprlfzauigahk9sj4vt5zu/

**Comment by OrangeCrush** [comment]
+1 
I also have a similar issue... ( see #512 )

Have you been able to find any documentation on how long a build is allowed to run?

**Comment by neo-apz** [comment]
@OrangeCrush,
I've contacted their support team, and according to their response, the current limits on Automated Builds are:

  -  2 hours
  -  2 GB RAM
  -  1 CPU
  -  30 GB Disk Space

So, for larger builds you have to either break them into several Automated Builds connected by `FROM` statements and Repository Links, or build them locally on your machine and push them to the repository.

**Comment by jakirkham** [comment]
I am seeing this, but I am seeing it for a build well within these specs. I can't understand what the issue is.

**Comment by dkarchmer** [comment]
+1
I used to be able to build my image, but now, it doesn't build anymore. Did something change and I didn't get the memo?

**Comment by arava** [comment]
restart-service docker 
Would help you complete the build sometimes
