### ISSUE TITLE
Unable to get tags with automated build working

### ISSUE THREAD

**Issue by strarsis** [docker/hub-feedback#520]
Concerning automated build repository [golang-nightly](https://hub.docker.com/r/strarsis/golang-nightly/).

Ideally, I would just push a new tag with name starting with 'build-' 
(see https://github.com/strarsis/docker-golang-nightly/releases)

I tried many approaches, like using a regexp that only matches build-* (using regexp /build-*/)
or even all tag names (just to get it working) - but then the field is empty again and nothing happens.
Either nothing happens at all when I push to git repository - 
or mangled input/image tag names result from this.

Currently I have to manually copy + paste the last tag name as tag name and trigger the build.

Thank you and
with best regards

**Comment by dwburke** [comment]
we're also having what sounds like the same problem with builds on regex tags that were working fine before the holidays.  The automated build seems to be using the 'latest' tag instead of our "release-xxx" tag, even though the build history says it's using that tag.  And the webhook we have setup to post to slack had the "latest" tag in its payload instead of "release-xxx"

**Comment by matglas** [comment]
I'm unable to get the configuration saved. When I return to the settings page for build it shows Build in again instead of Tag in the Type field.

**Comment by cleung2010** [comment]
I am also having issues with this.

**Comment by phudekar** [comment]
Regex in tags is not working for Automated builds. It does not even show the `Trigger` button if tag name has `/` at the beginning or end of the RegEx

**Comment by tonypujals** [comment]
Can confirm this is still not working. The leading `/` causes the `Trigger` button to disappear.

**Comment by rrarunan** [comment]
I see ~2 different issues being discussed in this one. 
@tonypujals @phudekar The rules with a regex defined for automated builds, do not have the ability to do a trigger manually in the UI yet. Pushing to a repo or tagging a repo based on which option (Branch/Tag) is chosen, should still work as expected.

Regarding the other comments, please let us know if you still see issues with regex tags and we can look into it.

**Comment by tonypujals** [comment]
@rrarunan Thank you for that clarification. The UI did not make it clear (at least not to me) that posting a trigger and pushing to the repo will still trigger, even if it can't be triggered from the UI. But that's great to hear -- it really simplifies things to be able to use a regex. Thanks!

**Comment by rrarunan** [comment]
Thanks @tonypujals. Noted :+1:

**Comment by sagikazarmark** [comment]
@rrarunan I have a this issue too. Even if I push tags, the builds are not triggered. I have to add that I tried force pushing tags.

If I try the webhook with build: true (which should trigger all branches/tags according to the documentation) still the same: branches are triggered, tags are not. I have to trigger tags manually, but the webhook only accepts a call in 1-3 minutes, so I have to wait some time between manually invoking tags which is annoying.

**Comment by sagikazarmark** [comment]
Talking about this repo BTW: https://github.com/webplates/docker-symfony-nginx

**Comment by bcwalrus** [comment]
@sagikazarmark I see autobuilds getting kicked off as a result of git tags being updated (e.g. `1.10.1-alpine`, `1.10-alpine`, `1.10`).

Btw, when you use a build trigger, try specify the source type and the source name. Without them, it won't trigger the regex build rules, because it doesn't know what to evaluate. (And kicking off a build for each git tag you have is unreasonable.)

**Comment by sagikazarmark** [comment]
@bcwalrus it seems to work when I don't update many tags at the same time. eg. updating 3-4 tags works, but updating all the ~10 simply does not trigger the builds.

About the webhook: I thought so, makes sense.

**Comment by bcwalrus** [comment]
@sagikazarmark That is a GitHub limitation. https://developer.github.com/v3/activity/events/types/#createevent

> Additionally, webhooks will not receive this event for tags if more than three tags are pushed at once.

**Comment by sagikazarmark** [comment]
@bcwalrus Oh, thanks for pointing.
