### ISSUE TITLE
Payment issues

### ISSUE THREAD

**Issue by agarwalyashash** [docker/hub-feedback#521]
Hey there!

I'm based out of India and I'm trying to get a few private repos. Docker doesn't have two-factor authentication for payments, and no Indian debit card (under rules from the Central Bank of the country) is allowed to transact without 2-factor authentication.

Credit card penetration is low in the country. Even if people want to pay for your services, they can't. You've only got to integrate with the right Payment Gateways / Mobile wallets in the country and that will allow a LOT more customers to be able to pay for your products. 

Thanks
Yashash

---

If this isn't the right place for this feedback, it'd be great if someone could point me to where I should go from here.

**Comment by thaJeztah** [comment]
Thanks for reporting @agarwalyashash! I posted a link to this issue on the internal Slack channel, so that the team can have a look at this issue :+1:

**Comment by kencochrane** [comment]
@agarwalyashash Thanks for the information, unfortunately our current payment processor doesn't support 2 factor authentication for payments. 

Can you give us a list of payment options that do work for you, so that we can investigate if any one of those would work for us?

**Comment by agarwalyashash** [comment]
Hey Ken,

When I tried make a payment on GitHub, or on Google Play with my VISA Debit
Card, the payment was processed. However, the same didnt happen in case of
Docker.

Otherwise, in India, a sync with Paytm or Mobikwik wallet will make
accepting payments much much easier. Even Paypal is an easy option.
Regulations are strict here and it's a country full of developers. People
are building software like never before and you don't want to lose out on
these payments.

I made a payment from my credit card temporarily, but not many in the
country have access to one.

Thanks
Yashash


On 29 December 2015 at 05:38, Ken Cochrane <notifications@github.com> wrote:

> @agarwalyashash <https://github.com/agarwalyashash> Thanks for the
> information, unfortunately our current payment processor doesn't support 2
> factor authentication for payments.
>
> Can you give us a list of payment options that do work for you, so that we
> can investigate if any one of those would work for us?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/docker/hub-feedback/issues/521#issuecomment-167682032>
> .
>



-- 
Yashash Agarwal

Now that it's all over, what did you really do yesterday that's worth
mentioning? ~Coleman Cox

**Comment by kencochrane** [comment]
@agarwalyashash thank you for the information, we will look into adding a better way to accept payments from people in India. I agree, we don't want to restrict anyone from giving us money if they want to use our service :)

**Comment by dijam** [comment]
I tried several times and waited a week and tried again, I cannot change my plan to paid one because of an error in payment form. it says:

> There was an error when submitting your billing information. Please check your information and try again.

Completely general message! Can you please guide me? I was trying to do the payment from Sweden via Business Master Card.

**Comment by thaJeztah** [comment]
@dijam can you contact support@docker.com ? they should be able to look into your issue

**Comment by amcorreia** [comment]
I'm interested to know when Paypal will be added as payment option.

**Comment by kibertoad** [comment]
Does Docker Hub still doesn't support 2 factor authentication for payments?

**Comment by nebuk89** [comment]
Closing as initial question was answered. We have no timeframe for non-credit card payments right now feel free to add this as a request on our public roadmap :) https://github.com/docker/roadmap/issues

Thanks!

**Comment by sumanthkumarc** [comment]
+1 we want to pay but the payment options are not working for us.
