### ISSUE TITLE
Builds do not trigger with new tags pushed to Bitbucket

### ISSUE THREAD

**Issue by kizbitz** [docker/hub-feedback#522]
When creating new tags with a Bitbucket repository builds are not triggered.

Zendesk ticket: 9617

**Comment by trkoch** [comment]
I'm having the same issue. Tags seem to be recognized, manually triggering a build does work. Any news on this?

**Comment by simonbrady** [comment]
Same issue here: the build works once I manually trigger it, although to get the Trigger button to appear in the UI I have to match an explicit tag rather than the default regex.
