### ISSUE TITLE
Visible stacktrace in error message

### ISSUE THREAD

**Issue by Scorpil** [docker/hub-feedback#525]
I've just re-created my automated build (removed old repository and created new one with the same name), and I've got an error looking like stacktrace.

![Stacktrace error](https://i.imgur.com/q6nztl9.png)

Obviously, there is unhandled exception somewhere that leaks data about environment to clients.

OS: Mac OS X 10.11.1
Browser: Firefox 43.0.3
URL: https://hub.docker.com/r/scorpil/rust/builds/bczvc88gb2ghwcx4gseh5hd/
Screenshot: above
Error messages: on screenshot, in console couple of Strict-Transport-Security errors and this:

```
mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create client.4d31c60c086a290f40a0.js:19:31763
"Warning: Each child in an array or iterator should have a unique "key" prop. Check the render method of t. See https://fb.me/react-warning-keys for more information."
```

Time: 2016-01-04 at 15.31.34 UTC+01
Hub Username: scorpil

**Comment by rrarunan** [comment]
@Scorpil Please let us know if a re-trigger or push to the repo, succeeds. This is in fact an error encountered in our build systems and thanks for reporting.

**Comment by Scorpil** [comment]
It's one time thing, re-triggering build fixes it.

**Comment by rrarunan** [comment]
Thank you, @Scorpil.
