### ISSUE TITLE
Email invites for users without Docker Hub accounts.

### ISSUE THREAD

**Issue by kizbitz** [docker/hub-feedback#526]
Feature request - Zendesk Ticket: 9677

"I'm trying to add teammates to our Hub organisation, but I can only invite users by email if they already have an account. Do you have plans to add this functionality soon?

It makes it difficult for us to onboard new engineers, every other platform (like Github) allows us to invite _new_ users by email and new hires just go through those invites in their inbox when they start. Obviously we don't want to create a user on their behalf, since they may already be using Docker Hub.

It's also a pain in the ass introducing it to an engineering team of approaching 100, most of whom do not have experience with Docker or Docker Hub, never mind already have an account."

**Comment by gcperrin** [comment]
+100 for this thought, it's an extremely costly issue.

**Comment by gelbander** [comment]
+1 ...

**Comment by meticulous-dft** [comment]
We are working on this feature at the moment.

**Comment by Verhaeg** [comment]
Hi, 
Honestly it is kind of disapointing for DockerHub not having this feature. The documentation clearly shows a way  to invite other users (https://docs.docker.com/docker-hub/orgs/#add-a-member-to-a-team) but there is simply no way to  do so.

We had an account and just changed it to an Organization and now all team members will have to manually create an account to later add  them to the org team. And also there is no way to set default permission for a team.

Is there another way to invite members that do not have an account yet?

**Comment by meticulous-dft** [comment]
Hi, invitation by email is available now. Simply use email address when adding member to a team. Will send invitation if the email address does not have a docker id.

There is no default permission for team except owners. You can change team permissions at individual repo's page.
