### ISSUE TITLE
official slack integration

### ISSUE THREAD

**Issue by jonathanong** [docker/hub-feedback#529]
using https://github.com/neonadventures/slack-docker-hub-integration, which is kind of silly right now. any plans for slack integration?

**Comment by browserslab-md5** [comment]
I agree having an official integration would be great. 

I ended up building a smaller version of the slack-docker-hub-integration 
https://hub.docker.com/r/browserslab/docker-hub-slacker/

Its container size is only 75mb and runtime it uses 25mb. Gives you more details about your build.

I hope that Docker Hub adds this integration natively
