### ISSUE TITLE
Build-details missing / build-time = UTC - "Build Created"

### ISSUE THREAD

**Issue by dynnamitt** [docker/hub-feedback#531]
Better UI for the Build-details 

a) UTC is useless as a header text, change to "build-finished" .. or equal
b) New column "Build-time" , calculation of  "build-finished" - "Build Created"

**Comment by sesceu** [comment]
+1
Would be nice to have a feeling about how long the build will take. This would also give people some data on where (which of his builds) to optimize, which in turn would lower the load on the docker hub.
