### ISSUE TITLE
docker push keeps failing with 500 internal server error

### ISSUE THREAD

**Issue by mbhandek** [docker/hub-feedback#533]
Hi,

My first push of docker image has been successful. My docker host is RHEL 7.

I am trying to push new version of my image to docker hub keeping same tag names.

When I issue docker push docker.io/mbhandek/***\* , it completes pushing of fifth set '349a7278758f' and then fails giving 500 Internal Server Error. I tried deleting the tags thinking using same tags for new version might be the issue, but still same issue. I tried deleting the repo on docker hub and push... but that fails too.

Has someone got similar issue? Can you please tell me how to push the repo on docker hub successfully?

Regards,
Manish

The push refers to a repository [docker.io/mbhandek/****](len: 2)
6cb22ca6001e: Image already exists
346fd91d4d51: Image already exists
aff37b73ef47: Image already exists
f3f1686a42f0: Image already exists
349a7278758f: Pushing [==================================================>] 7.256 GB
Received unexpected HTTP status: 500 Internal Server Error

**Comment by SlimeQ** [comment]
:+1: :+1: :+1:

**Comment by SlimeQ** [comment]
this is happening here too

**Comment by jakirkham** [comment]
We see this as well. Would be nice to solve this somehow.

**Comment by Jared-Prime** [comment]
+1 I'm also seeing increased `HTTP 500` responses on push

**Comment by bolencki13** [comment]
Receiving this error as well. I am experiencing this when trying to push to docker hub from within a Gitlab CI/CD pipeline. Prior to 03/08/2019 this was working.
