### ISSUE TITLE
A Docker Hub changelog would help when builds that used to work no longer do. 

### ISSUE THREAD

**Issue by dperetti** [docker/hub-feedback#539]
My "webapp" builds use to work fine a couple days ago.
They now fail at an unexpected place with a Meteor related issue that usually arises in conditions that are not met here. (wrong architecture, or files in .meteor/local that are shouldn't be there).

I'm puzzled by the fact that it used to work a couple days ago in the same conditions.

A detailed changelog change of Docker Hub build process would help figure out why.

**Comment by jakirkham** [comment]
:+1: Ran into the requirements change recently. Was very unhappy that this was not explicitly stated somewhere and that I had to hunt around for an answer.

They changed their specs from 2 CPUs to 1 CPU. The also changed from 2GB RAM to 4GB RAM. Also, they have a 30GB disk space limit (not sure what it was before). Unfortunately, these are the only details I know.
