### ISSUE TITLE
hub.docker search and `docker search` command return 0 results

### ISSUE THREAD

**Issue by charlespina** [docker/hub-feedback#540]
To reproduce:
1. Go to hub.docker.com
2. Type `whale-say`, `node`, or `ubuntu` into the search bar
3. Search.
4. Observe 0 results.

Similarly, for `docker search`:
1. Open a terminal
2. Run `docker search ubuntu`
3. Observe 0 results

However, `docker run ubuntu` appears to be unaffected, and will correctly find and run the image.

**Comment by gamename** [comment]
ditto

**Comment by Lochnair** [comment]
Yep, I'm seeing the same behavior.

**Comment by brikeyes** [comment]
I can see all of the things you are looking for now .

However I am having issues getting containers that I need to install the Docker UCP

**Comment by rajat-docker** [comment]
@brikeyes what is your hub account id?

**Comment by akshayvyas** [comment]
@charlespina I am able to search for the items you listed.  There was a new version released yesterday.  Can you please confirm you are able to search now in Docker Hub?

**Comment by dynaxis** [comment]
In my case, the search doesn't respond at all as if I didn't submit any search with Firefox, IE11, and Edge, which are all at the most up-to-date version. Only Chrome works.

**Comment by dynaxis** [comment]
Initially IE11/Edge didn't work at all too. But now it seems sometimes works and sometimes not.

**Comment by charlespina** [comment]
all good for me, thanks @akshayvyas (chrome on osx)

**Comment by asampal** [comment]
Using Firefox 64 bit on Windows 10 64 bit, no search results are returned for any search terms I try. The Edge browser seems fine.

When I try a search, the console shows:
`too much recursion` in `https://hub.docker.com/public/js/client.81c87edb2eb0ba936c8a.js:21:2253`
