### ISSUE TITLE
Hub doesn't render markdown titles properly

### ISSUE THREAD

**Issue by alex** [docker/hub-feedback#541]
**Github:** https://github.com/alex/letsencrypt-aws
![screen shot 2016-01-10 at 10 30 34 pm](https://cloud.githubusercontent.com/assets/772/12226427/d8ca4b4c-b7e9-11e5-9e14-6a758b098795.png)

**Docker Hub**: https://hub.docker.com/r/alexgaynor/letsencrypt-aws/
![screen shot 2016-01-10 at 10 30 40 pm](https://cloud.githubusercontent.com/assets/772/12226428/d8caf218-b7e9-11e5-8a8e-ff1a8ee2fa5b.png)

**Comment by nhsiehgit** [comment]
duplicate: closing this ticket in preference for https://github.com/docker/hub-feedback/issues/446
