### ISSUE TITLE
README.mdwn not shown for (some?) automated builds at all

### ISSUE THREAD

**Issue by frioux** [docker/hub-feedback#545]
I suspect that maybe `README` or `README.md` are hardcoded as the readme.  My repos use `README.mdwn` and while github shows them, docker no longer does since the UI refresh.  An example of a repo that I had to manually fix the README of is [here](https://hub.docker.com/r/frew/hugo/).

**Comment by cron410** [comment]
where does .mdwn come from? I'm not too experienced with Git, but maybe you could make a symlink of some kind? Or maybe a script/hook on your end that renames .mdwn to .md before it is pushed?
