### ISSUE TITLE
"Link GitHub" security error

### ISSUE THREAD

**Issue by morsik** [docker/hub-feedback#546]
I can't link my account anymore (which was previously linked, then unlinked) with GH. I'm getting:
> There was a security error during the github account linking process.

Only change I had on GH account was that I was added to GH organization that other guy is in it too, and it had linked account with DockerHub.

**Comment by nhsiehgit** [comment]
Hi @morsik 

Sorry about that, we've noticed this bug and are addressing it.

For now, you can try linking in an incognito window which should work.

Thanks for reporting

**Comment by rrarunan** [comment]
@morsik I was trying to track this down. Can you clear your cookies and try linking from this page: `https://hub.docker.com/account/authorized-services/`. It should work as expected. Let us know if this worked. Thanks!

**Comment by morsik** [comment]
@rrarunan: I revoked Docker Hub on GitHub, cleared cookies from hub.docker.com, linked again and it works.
Thanks, but strange.

**Comment by vdboor** [comment]
I'm also getting this error. Removing cookies (tried a private session) and the OAuth application doesn't work for me.

In my GitHub organisation I have "Third-party access" policies enabled, but explicitly allowed "Docker Hub Registry" there on the first attempt to authenticate.

**Comment by grihabor** [comment]
I get the same error:
```
There was a security error during the github account linking process.
```
I tried every suggested solution — nothing worked
