### ISSUE TITLE
Automated build: Timeout when pushing

### ISSUE THREAD

**Issue by hettling** [docker/hub-feedback#547]
I get a timeout during my automated build after 2 hours.
My image is successfully built in about 45 minutes but then the push times out since my image has a virtual size of ~ 12GB (due to a large sqlite database file that needs to be included in the image).

A similar issue was reported here: https://github.com/docker/hub-feedback/issues/519 reporting that
the limits are 2 hours, 2GB RAM, 1CPU and 30 GB disk space, which is, in general, sufficient for my project. However, there seem to be practical issues with too large images.

The Dockerfile of my project can be found [here](https://github.com/naturalis/supersmart/blob/master/conf/docker/Dockerfile)

The log output of my latest timed-out build can be found [here](https://hub.docker.com/r/naturalis/supersmart/builds/bwncthcexljgrgwati8olka/)

Is there any possibility I can perform an automated build of an image that is 12 GB large?

Any help and information is highly appreciated, 
thanks in advance!

**Comment by aliceminotto** [comment]
same problem here! https://hub.docker.com/r/cyverseuk/polymarker_wheat/builds/bdvn2mtrjnqdxzt5vemegyv/

**Comment by cekees** [comment]
@hettling I noticed you got your automated builds to push. Was there a trick to this?

**Comment by hettling** [comment]
Hi @cekees, reason for timing out are apparently the unit tests for our pipeline which however only take 5 minutes on my laptop computer.
I tried an automated build including the unit tests and have a timeout again, although the tests finish successfully, below the end of the build log:

```
All tests successful.
Files=26, Tests=394, 2439 wallclock secs ( 0.33 usr  0.04 sys + 1306.78 cusr 772.84 csys = 2079.99 CPU)

Result: PASS

 ---> 078248669f34

Removing intermediate container e9e32dfd3d28

Successfully built 078248669f34

Pushing index.docker.io/naturalis/supersmart:devel...
Build canceled.
```

**Comment by Cactusbone** [comment]
same error for me. 
https://hub.docker.com/r/cactusbone/postgres-postgis-sfcgal/builds/bdsr6d2qctkqkzvksxwmlvj/
looks like solution is to split dockerfile... as stated in #519
