### ISSUE TITLE
Automated builds fails with error: GoVersion: go1.4.2

### ISSUE THREAD

**Issue by miltondp** [docker/hub-feedback#549]
Automated builds are failing for these repositories:
 * sinclab/webdemobuilder
 * mpividori/webdemo-diversity-control

The error reported is "GoVersion: go1.4.2". The logs are:

    adding changesets
    adding manifests
    adding file changes
    added 6 changesets with 7 changes to 2 files
    updating to branch default
    2 files updated, 0 files merged, 0 files removed, 0 files unresolved
    KernelVersion: 3.13.0-40-generic
    Os: linux
    BuildTime: Mon Oct 12 05:37:18 UTC 2015
    ApiVersion: 1.20
    Version: 1.8.3
    GitCommit: f4bf5c7
    Arch: amd64
    GoVersion: go1.4.2

**Comment by hassan-k** [comment]
got the same issues on a number of private and public repos. For now I've build locally and push the tags manually but this isn't great specially for private repos

 - createkio/gocd-agent
 - createkio/gocd-server

**Comment by drGrove** [comment]
:+1: 
I'm facing the same issue with my private builds

**Comment by thaJeztah** [comment]
Can you open a ticket for this via support@docker.com? That makes sure the team supporting Docker Hub / automated builds is on it. Thanks!

**Comment by miltondp** [comment]
Done!

Milton Pividori

**Comment by sedenko** [comment]
Unfortunately we have the same issue:

```
KernelVersion: 3.13.0-40-generic
Os: linux
BuildTime: Mon Oct 12 05:37:18 UTC 2015
ApiVersion: 1.20
Version: 1.8.3
GitCommit: f4bf5c7
Arch: amd64
GoVersion: go1.4.2
```

**Comment by miltondp** [comment]
A workaround consists in setting the "Docker location", in the Build Settings, to /
That fixed the problem for me.

**Comment by sedenko** [comment]
@miltondp Thanks that did work! Thumbs up!

**Comment by guruvan** [comment]
Hmm - maybe there's a bunch of outdated workers in the fleet? 

just hit this on [maza/gitian-travis](https://github.com/guruvan/gitian-docker) - would like to be able to build the Dockerfile.travis in this project, but ....this is not working for some reason.

Dockerfile is FROM ubuntu:15.10 if that's of any consequence

**Comment by kizbitz** [comment]
Hi All,

A fix for the original issue has been pushed to our prod stack. If you're still having issues could you please open a support ticket at https://support.docker.com

@guruvan We currently have an open support request for this issue. You can add your +1 comments here: https://github.com/docker/hub-feedback/issues/292
