### ISSUE TITLE
two factor authentication

### ISSUE THREAD

**Issue by carljmosca** [docker/hub-feedback#551]
I am guessing I have missed this...is it supported directly?

**Comment by kajmagnus** [comment]
Hi, see https://github.com/docker/hub-feedback/issues/358

**Comment by mlissner** [comment]
This issue is a dup and this was announced a few months ago: https://github.com/docker/hub-feedback/issues/358#issuecomment-544758150.

This issue should be closed, but I don't have permission to do so.

**Comment by thaJeztah** [comment]
Thanks for linking the other issue; yes this one can be closed 👍
