### ISSUE TITLE
Connect to GitHub Fine-Grain Permissions

### ISSUE THREAD

**Issue by RyPeck** [docker/hub-feedback#552]
The "Connect to GitHub" Public and Private requests access to each and every Organization it can. It would be great if it didn't ask/require permissions to everything.

**Comment by kytrinyx** [comment]
This should be possible using GitHub Apps (https://developer.github.com/apps/). In general Apps are a better fit when you want to create a service that is typically scoped to an organization or a repository as Docker Hub is.

The permissions for GitHub Apps are much more granular than the scopes on OAuth apps.

**Comment by kytrinyx** [comment]
Actually—it looks like the deploy keys endpoints are not yet enabled for GitHub Apps: https://developer.github.com/v3/repos/keys/

But as soon as they are, then I could see GitHub Apps being a great alternative to the OAuth integration that is currently used.
