### ISSUE TITLE
Error for Automated Build: Push failed: {"status":"Buffering to Disk","progressDetail":{},"id":"e61ebc8924ac"}

### ISSUE THREAD

**Issue by jazzdd86** [docker/hub-feedback#553]
Hi, I am trying to do an automated build for a bigger image (2.1GB). Locally on my hardware it runs without problems. With an automated build it seems to build successfully but fails to write it to the docker hub registry, with the message:
```
Push failed: {"status":"Buffering to Disk","progressDetail":{},"id":"e61ebc8924ac"}
```

The build log can be found at:
https://hub.docker.com/r/jazzdd/sharelatex/builds/bucjbaxcmff7ryyzaemuzzs/

**Comment by kizbitz** [comment]
Hi jazzdd86,

Could you open a support ticket at https://support.docker.com so we can track/resolve this issue there? I'm currently working with our backend team trying to get this resolved.

Apologize for the inconvenience.

Thanks,
