### ISSUE TITLE
Tags type cannot be selected in Build Settings

### ISSUE THREAD

**Issue by moifort** [docker/hub-feedback#555]
Hey I have a little problem here (and I dont see other issue talking about).  I cannot save `Tag`in the  Build Settings screen. 

My docker is defined like:
- Public
- Automated Build
- Using Github repo

How to produce it:
- Go to **Build Settings** screen
- Select **Tag** type to define the trigger 
- Save
- Refresh **Tag** is not saved, still **Branch**

Tested with:
- Safari (last version)
- Firefox (last version)

![generator-jhipster-bootstrap-material-design-demo](https://cloud.githubusercontent.com/assets/4958079/12567162/cfdbb004-c3bd-11e5-94a6-5d316b44b1d6.gif)

PS: I already configure the **Tag** type in my older docker, but now they are configured in **Branch** type

**Comment by nhsiehgit** [comment]
Thanks for reporting moifort, this is definitely a bug we shouldn't have.

Will look into it.

**Comment by nhsiehgit** [comment]
A fix has been deployed to production.

Closing this issue now. If you're still seeing problems please reopen and let us know!

**Comment by moifort** [comment]
:+1: It's work for me!

Thanks!
