### ISSUE TITLE
Dockerfile tab not updated

### ISSUE THREAD

**Issue by FireFart** [docker/hub-feedback#558]
It looks like the Dockerfile tab is currently not updated.

See here for example:
https://hub.docker.com/r/wpscanteam/wpscan/ (and select the `Dockerfile` tab)

and compare it with the latest build dockerfile:
https://hub.docker.com/r/wpscanteam/wpscan/builds/

**Comment by Red54** [comment]
I met the same problem.

**Comment by FireFart** [comment]
seems fixed
