### ISSUE TITLE
Scheduled builds not shown in Build Details

### ISSUE THREAD

**Issue by strarsis** [docker/hub-feedback#559]
Edit: The triggered builds were built indeed, they weren't listed as scheduled/running in Build Details tab.

Dockerhub Repository: https://hub.docker.com/r/strarsis/golang-nightly/

Trigger button confirms with "Triggered", but no new builds appear scheduled in build details.
I logged into Dockerhub and retried with latest Firefox and Chrome.

Thank you and
With best regards

**Comment by goesta** [comment]
Same thing here.
https://hub.docker.com/r/goesta/xmage/

**Comment by strarsis** [comment]
This seemed to have been a temporary issue.
