### ISSUE TITLE
Automated Build fails with error Push failed

### ISSUE THREAD

**Issue by goesta** [docker/hub-feedback#560]
Hi,
my automated build failed with the following error:

Push failed: {"status":"Buffering to Disk","progressDetail":{},"id":"32322133dcb5"}

https://hub.docker.com/r/goesta/xmage/builds/bzc76pfyeagkumexfvbqwva/

**Comment by kizbitz** [comment]
@goesta - Could you open a support ticket for this error? - https://support.docker.com

**Comment by goesta** [comment]
Ok thx
