### ISSUE TITLE
Still getting billed for the FREE plan!

### ISSUE THREAD

**Issue by reiz** [docker/hub-feedback#561]
I canceled my payed plan already in December 2015 and switched to the FREE plan. But I'm still getting billed. Just received the PDF receipt for January. Can you please stop billing me!

**Comment by reiz** [comment]
The last invoice ID is 53326.

**Comment by thaJeztah** [comment]
Can you please contact support@docker.com? They should be able to look into this

**Comment by reiz** [comment]
Just did it. Many Thanks for the fast response!

**Comment by thaJeztah** [comment]
@reiz you're welcome! Feel free to "ping" me here if needed (I'm not part of the "hub" team, but I can try to reach the right people if needed; support@docker.com should be the right channel though)
