### ISSUE TITLE
Automatic build triggered with 3-4 min delay

### ISSUE THREAD

**Issue by let4be** [docker/hub-feedback#562]
When I'm doing git push hub.docker.com instantly picks up and queues a build but it takes up to 3-4 min to actually start the build
I need real-time(or near real time) builds, any ideas?
Are things any different on paid plans(cloud, private repos only)

**Comment by mghazizadeh** [comment]
do you have a subscriptions for private repos or is this a public repo?

**Comment by let4be** [comment]
I first tried on a free account(1 private repo) and it was ~3-5 min delay,
next I tried with 10 private repo subscription - delay is less around ~2-3 min
Still I opted out to use hub.docker.com solely as hosting as such delay is not in my interests, It's much-much faster to simply spin up a cheap ec2(nano/micro), build there instantly and upload to docker hub
As a bonus you get properly working docker cache so builds are faster

**Comment by mghazizadeh** [comment]
we are working on a features to make it faster to start the builds.. even during peak times and adding docker cache to speed up the build run time..

**Comment by Starefossen** [comment]
I purchased a plan for my organisation if the hope that this would speed things up. I am still seeing 3-4 min before triggered builds starts to build.

**Comment by bf** [comment]
We have the same issue and are a bit disappointed by docker hub. We expected it to be quicker than our private setup, but actually it takes 20 minutes for builds to finish which sucks big time.

We're a paid customer.

**Comment by hamelsmu** [comment]
Yeah I'm not happy either.  The service is still slow
