### ISSUE TITLE
Delete an organization

### ISSUE THREAD

**Issue by fvilarinho** [docker/hub-feedback#563]
Hi,

I need to delete the Organization fvilarinho under the account concepting.
One more thing. Is it possible to transfer the private repositories from an organization to another?

Rgs

**Comment by alec-c4** [comment]
+1, i'd like to be able to delete Organisation

**Comment by kizbitz** [comment]
Hi fvilarinho and alec-c4,

This is on our roadmap but hasn't been implemented yet. In the meantime you can create a request to have your organization deleted at https://support.docker.com

Closing as duplicate. You can track progress/status at: https://github.com/docker/hub-feedback/issues/12
