### ISSUE TITLE
Tag name not sorted in descending order

### ISSUE THREAD

**Issue by kyloon** [docker/hub-feedback#569]
![capture](https://cloud.githubusercontent.com/assets/8691956/12814708/3fc842c2-cb95-11e5-9478-855d7eaebe58.PNG)

**Comment by lglick** [comment]
I have the same change proposal. Could be nice to have an ability to sort by Header name:

[http://cl.ly/2o0i47383P2z](url)

**Comment by kristiehoward** [comment]
Tags are sorted by `Last Updated`, with the most recently updated at the top

![image](https://cloud.githubusercontent.com/assets/7132362/13160459/61557484-d64c-11e5-986c-c76d282b4ad8.png)

**Comment by kyloon** [comment]
Awesome thanks.
