### ISSUE TITLE
Multiple builds triggered

### ISSUE THREAD

**Issue by johnmorrell** [docker/hub-feedback#578]
I think this has been caused by added and deleting an automated build by the same name a couple of times, but I now see three builds line up and run for each trigger event.

**Comment by kizbitz** [comment]
Hi,

Could you open a support ticket for this issue at https://support.docker.com and include the link to your hub repository?

We'll get it resolved and track the process from there.

Thanks,

Jerry

**Comment by Nobody84** [comment]
I got the same behaviour with a brand new docker hub repository.
