### ISSUE TITLE
Disable Comments for Official Repositories

### ISSUE THREAD

**Issue by Starefossen** [docker/hub-feedback#579]
Hi,

I am one of the maintainer of the Official Repository for Node.js https://hub.docker.com/_/node/. I see there are a lot of comments that we as the maintainers have missed over the years. ~~~Is it possible for us to subscribe to notifications for these comments?~~~

What we as maintainers would like is to disable comments on our official image and point users to the well established issue-tracker on GitHub: https://github.com/nodejs/docker-node/issues

**Comment by chorrell** [comment]
+1

**Comment by tianon** [comment]
Definitely a big +1 from me -- the official images all have pointers to GitHub or Bugzilla which is where we prefer users comment about problems so that our maintainers can keep track of them appropriately.

**Comment by yosifkit** [comment]
I would be -1 on a subscribing to the comments for a couple reasons:
- increased inbox overload
  - superfluous comments
- no easy feedback mechanism for users to see resolutions
- may not fit with some maintainers' bug/issue tracking flow

**Comment by Starefossen** [comment]
I agree with @yosifkit, email notifications is a bad idea. I have changed the proposal to "Disable Comments for Official Repositories".

**Comment by LongLiveCHIEF** [comment]
I'd rather see some sort of integration with github issues, rather than have them disabled.  But I don't see how that's possible with the current format of github issues threads.

The comments as they are on the hub page, really don't provide any value. Maybe get rid of comments all together, and instead display a list of issues titles and the metadata about each issue?

**Comment by Starefossen** [comment]
Keep it simple - remove comments (at least for official images) and link to the official issue tracker.

**Comment by Starefossen** [comment]
@marcusmartins I am sorry if you are not the right person to cc on this issue, but any chance we could get an official Docker Hub opinion regarding the possibility to disable comments for official Docker Images and instead linking to the official issue tracker for the image?

**Comment by gissehel** [comment]
Actually, I see no reasons to do that only for official repositories.

I see the same problem for every public repositories. Wether I'm maintaining them, or I just use them, I'm reading a lot of comments directed to the image maintainer, and I'm pretty sure he will never read them, or will read them much too late. 

This is especially true for automated builds where there is a github project, so there is an official github issue page. Every image maintainer expects comments/feedback through that point (or the bitbucket equivalent).

It may take the form:
- of a link on the "settings" page, that would both disable comments and provide a link for feedback, 
- or a link on the "settings" page, and a checkbox on the "settings" page if you want to give more control.

So I would change the title of this issue from "Disable Comments for Official Repositories" to "Let comments be disabled" (for all repositories).

**Comment by tianon** [comment]
This is definitely still relevant and desirable. :innocent: 

Any chance it could get some attention? :pray:

**Comment by thaJeztah** [comment]
> Any chance it could get some attention? 🙏

Coincidentally, I brought this up a couple of weeks ago after a wave of spam in the comments, and a little birdie tells me they're actively looking into this (but 🤐 😉 😃)

**Comment by tianon** [comment]
The "Comments" functionality appears to now be completely gone from Docker Hub, which renders this issue obsolete! :tada: :heart:
