### ISSUE TITLE
Did you integrate tutum on last week?

### ISSUE THREAD

**Issue by yurtaev** [docker/hub-feedback#581]
My [builds](https://hub.docker.com/r/crystalnix/omaha-server/builds/) are failing because contains `docker-compose.test.yml` file in repo.

**Comment by pchico83** [comment]
@yurtaev Yes, we are working on integration both autobuild solutions. Although it is not documented yet, hub is now using the same hooks as Tutum (now Docker Cloud). If you want to ignore the "test" phase, you can add a "test" hook that does nothing.
