### ISSUE TITLE
automated build fails while removing intermediate container

### ISSUE THREAD

**Issue by bastiaanb** [docker/hub-feedback#583]
In repository `bastiaanb/consul`, automated build https://hub.docker.com/r/bastiaanb/consul/builds/bbvqfq5lnphei8cvvvcoyak/ fails in step 13:

```
Step 13 : COPY client.json /consul/config/client
Removing intermediate container 1134ab16189c
stat /var/lib/docker/aufs/mnt/1134ab16189cb4d716e371d422aa880f93d1a1821cd2f6cc3c040121abf5d177/consul/config/client/client.json: not a directory
```

The error occurs during removal of an intermediate container, which suggests the problem is not in the Dockerfile but the underlying build environment. 

A local build with Docker 1.9.1 on Fedora 22 succeeds.

**Comment by thaJeztah** [comment]
Can you open an issue through support@docker.com? That's usually the fastest way to get support for specific issues

**Comment by bastiaanb** [comment]
for reference: this issue was resolved per suggestion by support@docker.com by replacing
```
COPY client.json /consul/config/client
COPY server.json /consul/config/server
```

with
```
COPY client.json /consul/config/client/
COPY server.json /consul/config/server/
```

**Comment by thaJeztah** [comment]
Oh, makes sense, yes. Good to hear it's resolved!

**Comment by bastiaanb** [comment]
Yes, thanks.
Preferably the inconsistent behavior will be fixed too: the Dockerfile specs are a bit ambiguous. It says a dest directory *must* end with a trailing slash, but gives a counter example in the same section:
```
COPY test /absoluteDir   # adds "test" to /absoluteDir
```

**Comment by thaJeztah** [comment]
@bastiaanb good catch, agreed; would you be interested in opening a pull request to fix that? The Markdown file to generate that part of the documentation can be found here; https://github.com/docker/docker/blob/master/docs/reference/builder.md

Let me know, otherwise I can take care of that

**Comment by bastiaanb** [comment]
@thaJeztah documentation done. https://github.com/docker/docker/pull/20373
I guess it would even be better if Docker build actually enforces this and fails builds if dest has no trailing slash but the path already exists as a directory. I'll see if I have time to write a PR for that later.

**Comment by thaJeztah** [comment]
@bastiaanb perhaps; we should be really careful with changes like that though; it may break existing Dockerfiles for users, so sometimes making those changes are not as trivial (unfortunately)
