### ISSUE TITLE
Automated Build DDoS with Repository Links

### ISSUE THREAD

**Issue by Starefossen** [docker/hub-feedback#586]
It would be great if you could specify one or more tags for a given Repository Link for an Automated Build, like this:

<img width="951" alt="screen shot 2016-02-17 at 21 57 05" src="https://cloud.githubusercontent.com/assets/968267/13124575/6cc9e56a-d5c1-11e5-920a-369caba9c246.png">

Currently we are getting flooded by rebuilds for each tag new, or updated, tag in the linked repository, even though the tag we may be using in the Dockerfile has not been updated.

<img width="830" alt="screen shot 2016-02-17 at 21 55 40" src="https://cloud.githubusercontent.com/assets/968267/13124615/8de58826-d5c1-11e5-927a-e2df561a2421.png">

All of these new builds are in turn deployed to Docker Cloud in a very rapid succession – which does not result in the greatest experience for us and our users:

<img width="954" alt="screen shot 2016-02-17 at 21 59 17" src="https://cloud.githubusercontent.com/assets/968267/13124660/c2ce77f0-d5c1-11e5-9900-954e94fee124.png">

**Comment by Kaixhin** [comment]
Ideally linked repos should allow tag -> tag builds. For example, `library:7.0` triggers `software:7.0`, whilst `library:7.5` triggers `software:7.5`. The tags don't necessarily have to correspond, but even matching tags would be a great first step.

**Comment by Starefossen** [comment]
Thank you for the response @mghazizadeh, looking forward to it 👍🏼

**Comment by rfc1459** [comment]
This is not just an issue with Docker Cloud per-se, the current linking method makes using official images with Alpine variants a pain.
Linking a single tag (or detecting the base image using the `FROM` directive of the Dockerfile?) would at least cut down useless builds and subsequent webhook triggers "misfires".

**Comment by sheerun** [comment]
You're wasting a lot of resources, docker!

**Comment by tokyowizard** [comment]
I've ran into this issue, too.

I'd be happy with the matching tag suggestion in https://github.com/docker/hub-feedback/issues/586#issuecomment-186568273

Is there some environment variable that can be used to determine the tag from the repository link that triggered the build?
