### ISSUE TITLE
Deleted tags reappear (with recent 'updated' date)

### ISSUE THREAD

**Issue by matevarga** [docker/hub-feedback#587]
- I a private repo with multiple tags (let's say :A, :B, :C). 
- I delete all of them on the web UI. 
- I push an image with tag A
- tags :A, :B, :C appear on the web UI, and they can be pulled. The modification date is the same on all tags.

This is confusing because for example if I have a 'development' and a 'master' tag, then whenever I push 'development', it seems that 'master' has been updated, which would be dangerous for us.

**Comment by rrarunan** [comment]
@matevarga can you elaborate a little more on how you have the rules setup etc. A screenshot of your build rules page will help. Please contact support@docker.com so we can help you further.

**Comment by matevarga** [comment]
Eh, this is a bug on our side. We push like:
docker push teamname/image:$TAG
.. and TAG is not substituted properly. 
Thanks.
