### ISSUE TITLE
No build log

### ISSUE THREAD

**Issue by victorv** [docker/hub-feedback#591]
Build has error but logs not visible.

https://hub.docker.com/r/10imaging/jenkins-android/builds/bfunxue7nihy6hlsu7txcuy/

**Comment by etspaceman** [comment]
+1. Has happened twice now:

https://hub.docker.com/r/etspaceman/elastic-docker/builds/btuydgeu5yvhbibkdxvnv8s/
https://hub.docker.com/r/etspaceman/elastic-docker/builds/bawlgl6nxn5vf42mebrxraa/

**Comment by thaJeztah** [comment]
can you contact support@docker.com? they should be able to look into individual cases and check what's wrong

**Comment by victorv** [comment]
I will contact support.

**Comment by etspaceman** [comment]
So, in my case, I believe the issue was due to having a call to a process (kibana) that started in the foreground and Docker couldn't continue to the next step. So, basically Dockerhub sat on that step for 3 hours or so and eventually bombed out. I assume the log was too big to transfer because of all of the logging from the foreground kibana process. 

Moving that call to an entrypoint script and piping the kibana logs to a log file resolved this for me.

**Comment by bbimber** [comment]
+1 on this issue.  I've seen this a couple times without a clear explanation.  After the failure I kicked off another build and it worked.  Here's one example of failure with no log:

https://hub.docker.com/r/bbimber/discvr-seq/builds/b6qdzzo9q5geqyutmb5u7y3/

**Comment by peterjc-dk** [comment]
plus one from here!! https://hub.docker.com/r/peterjc/ubuntu-ruby-texlive/ builds with error, but show no error message and no log.

I have experience that on my local machine it sometimes fail do to lack of resources, after images clean up it works, it takes a long time!!! The strange thing is it was working, and nothing was really changed

**Comment by ferrarimarco** [comment]
+1 for https://hub.docker.com/r/ferrarimarco/open-development-environment-ansible

Contacted support via mail minutes ago...

**Comment by Hammarn** [comment]
I have the same issue. My builds just fails with no message, no error and no logs. Repo in question;
https://hub.docker.com/r/hammarn/ngi-rnafusion/builds/

**Comment by coreorm** [comment]
i concur. https://hub.docker.com/r/copyright/docker-node-php-npm-aws/builds/bumdpx9hs4uunh3ahpfhca8/ error with no build logs.

i had to spin up an EC2 and try all commands there, but they all worked :(

**Comment by atrauzzi** [comment]
There definitely needs to be a way to review or monitor builds.

**Comment by juicelink** [comment]
all my builds fail with no message.
they directly switch from queued to failed
Triggered again a past working build and now it fails too...
It is very annoying

**Comment by stevearc** [comment]
I am seeing the same issue. All builds fail with no logs

**Comment by RedactedProfile** [comment]
> all my builds fail with no message.
> they directly switch from queued to failed
> Triggered again a past working build and now it fails too...
> It is very annoying

Getting this too @juicelink right now. Public repo, deploy key installed, everything, but no dice on the matter

**Comment by RedactedProfile** [comment]
This issue was resolved lately here: https://github.com/docker/hub-feedback/issues/1996#issuecomment-634335423 

Perhaps this issue should be closed now?

**Comment by thaJeztah** [comment]
Yes, let's close this one per https://github.com/docker/hub-feedback/issues/1996#issuecomment-634335423
