### ISSUE TITLE
automated build stuck in queued state for 3 days. 

### ISSUE THREAD

**Issue by AnalogJ** [docker/hub-feedback#594]
Hi
I have an automated build that has been stuck in a queued state for 3 days, and is no longer being built when I make commits to my repo:

https://hub.docker.com/r/analogj/capsulecd/builds/b9qevqztkt3gvptj4ykvhsy/

Any help would be appreciated.

**Comment by thaJeztah** [comment]
Can you contact support@docker.com? They should be able to look into this

**Comment by bf** [comment]
Builds are also slow for us, we've contacted support as well.

**Comment by stepansib** [comment]
Me too( Cant build image(

**Comment by chpio** [comment]
yeap, me too, several builds are in "queued" state, canceled them 3 days ago and they are still queued.

**Comment by anurbol** [comment]
+
