### ISSUE TITLE
Automated build fails on various reasons

### ISSUE THREAD

**Issue by buehler** [docker/hub-feedback#596]
Hey team docker

I'm experiencing some kind of an inconvenience. My automated build, which I set up yesterday, has no chance of being built.

https://hub.docker.com/r/buehler/go-elastic-twitterbeat/

All it does, is running into network timeouts and other registry related errors. If I build the image locally, everything works fine.

It would be nice if this feature actually runs fine :wink:

Cheers
Chris

**Comment by thaJeztah** [comment]
can you contact support@docker.com, they should be able to look into this

**Comment by buehler** [comment]
Alright, will do :)
