### ISSUE TITLE
"Link Github" apparently broken.

### ISSUE THREAD

**Issue by DDN-Shep** [docker/hub-feedback#597]
I cannot link to my GitHub account
- Browsed to Profile -> Settings -> Linked Accounts & Services
- Clicked "Link Github"
- Selected "Public & Private"

In a new window am able to login (via two-factor authentication) and approve the connection. Window closes and Docker Hub displays the following error:

"There was an error during the github account link. Please ensure, you do not have the same github account linked to another dockerhub account"

This error appears in spite of the application being authorised by GitHub. 

I have tried on & off for months now, clearing my browser cache, revoking GitHub access and retrying. Also tried using other browsers (FireFox Dev Edition, Chrome and Chrome in incognito mode).

**Comment by yossisolomon** [comment]
Also having trouble linking accounts - in my case, after clicking the link "select" button I get a GitHub page with their 404 page, although the link itself seems legit (having oauth parameters etc.)

![image](https://cloud.githubusercontent.com/assets/12303057/13479156/c189483a-e0dd-11e5-86e5-c5782f8f80ec.png)

**Comment by marcusmartins** [comment]
@DDN-Shep I apologize for the slow response. Could you contact support@docker.com and we can fix your account - It looks like you have 2 accounts linked with the same Github account.

@yossisolomon Can you confirm if you're still facing the same problem? Your issue is unrelated to the problem @DDN-Shep is facing.

**Comment by yossisolomon** [comment]
@marcusmartins Sorry, didn't get the message - I'm still having this problem (tried again today and remembered I posted this and got back here).
Could this be some kind of corruption in my user profile?

**Comment by marcusmartins** [comment]
Hi @yossisolomon, to troubleshoot I would require more information that we should share on a public issue. Can you email support@docker.com referencing this issue and we can help you from there?

I will close this issue for now.
