### ISSUE TITLE
Automated build fails without error message or log

### ISSUE THREAD

**Issue by schuhschuh** [docker/hub-feedback#604]
The build of the project locally on my machine using ```docker build``` works fine. However, the build on Docker Hub fails without any error message and with no log file content. It is thus hard to know what the problem is with the build. Could it be a time out? But I would expect a respective error message in this case.

Docker Hub user: schuhschuh
Docker Hub organization: biomedia
Docker Hub build details: https://hub.docker.com/r/biomedia/mirtk/builds/bx7u47xjapnbolvrjbjtuq/

**Comment by thaJeztah** [comment]
@schuhschuh can you contact support@docker.com, they should be able to look into individual issues

**Comment by schuhschuh** [comment]
Thanks @thaJeztah, I've sent them a message.

**Comment by The-Compiler** [comment]
I have the same issue, and someone at https://github.com/docker/docker/issues/21093 too - I'll mail support.

**Comment by schuhschuh** [comment]
In my case it was a build time out. The solution was to build manually a
custom base image FROM with the dependencies of the software project
preinstalled.

**Comment by The-Compiler** [comment]
Thanks for the follow-up - I can't imagine it's that in my case, as it builds in 5 minutes locally.
