### ISSUE TITLE
Cannot download docker images

### ISSUE THREAD

**Issue by htammen** [docker/hub-feedback#607]
Hi,
I'm not able to download any docker image from hub.docker.com. Tried it with three different images and getting the same error with each of them:

```
Network timed out while trying to connect to 
https://index.docker.io/v1/repositories/library/wordpress/images. 
You may want to check your internet connection or if you are behind a proxy.
```

My internet connection is fine and I'm not behind a proxy.
Any hints or is dockerhub down at the moment?

Regards
Helmut

**Comment by jofan** [comment]
Had the same issue but after running `docker-machine restart default` from the Docker CLI it worked fine for me again.
