### ISSUE TITLE
Linked GitHub Service widget displays wrong access level

### ISSUE THREAD

**Issue by dsheets** [docker/hub-feedback#610]
I am told that I have given Docker Hub read/write access to my GitHub account when I have only given it public read access:

<img width="910" alt="screen shot 2016-03-12 at 17 30 51" src="https://cloud.githubusercontent.com/assets/59918/13730566/ba7daa3e-e94a-11e5-88cb-7b99469f11c1.png">

**Comment by laneb** [comment]
Same problem here. I tried setting up a private link a couple of times with the same result. Github confirms that only public read access has been granted.
