### ISSUE TITLE
website takes over 1minute to load your client js - meaning I cant search 

### ISSUE THREAD

**Issue by pvdvreede** [docker/hub-feedback#613]
Oh dear, it took over a minute to download your client javascript file when I went to `hub.docker.com`. So any attempts to search for a docker image - which is what most people would want to do the second they hit your site - were met with nothing happening.

The client js file is over 2.8mb so maybe it is worth breaking it up and loading from multiple subdomains, or with http/2 around the corner not concatenating it at all...

![screen shot 2016-03-16 at 10 14 50 am](https://cloud.githubusercontent.com/assets/647975/13797252/4828c370-eb60-11e5-966a-56ac0d311b5f.png)

**Comment by francois2metz** [comment]
The bundle has now grown to 3.8mb. And it's **uncompressed**. And yes, these 3.8mb, even on my gigabit connection, took 30s to download. The mininum things to do would be to activate gzip compression for javascript files.

**Comment by spantaleev** [comment]
Indeed. I've often-times wondered why the search is broken until the loading indicator finishes "spinning". The number of times that I have had trouble searching and wait for a long long time..

Now I finally took a look as to why is that and saw that 3.8MB javascript file situation.. Insane! 😮 

Having so much Javascript for a portal which seemingly does nothing special is very surprising.
But once you're at the point of carrying so much weight, it's probably hard to trim it down.

Anyway, it's probably better if that search form is made to degrade nicely and work without Javascript.. Just add some `action=..` to the form and a `name` attribute to the search input field. That way, we'd be able to search even while that still-gigantuous file is loading.

**Comment by jarischaefer** [comment]
This is by far the most annoying issue I have faced so far. Are there any plans to fix this (or at least a wontfix statement)?

**Comment by liweinan0423** [comment]
+1
It takes longer than 1 minute to load the client bundle.

![image](https://user-images.githubusercontent.com/646159/29866459-0a82e278-8dab-11e7-92fe-80d3dda81dc9.png)

**Comment by Luzifer** [comment]
Still nothing changed… 2.5MB taking 44.09s to load… And I wondered why the page isn't usable quite often…

![image](https://user-images.githubusercontent.com/20142/34643731-8b471a94-f329-11e7-9790-4c34289f1cb2.png)
