### ISSUE TITLE
Repositories view for organizations cuts off the most important part of the repository name

### ISSUE THREAD

**Issue by pdu-avaleo** [docker/hub-feedback#614]
If organization name is long enough there is no space for the actual name of the image

**Comment by mrbar42** [comment]
+1
the new arrangement is impractical.

**Comment by jsonfry** [comment]
I also have a similar problem. I'm now staring at a list of several repos, which all start with the same 6 characters as they're part of the same project...

**Comment by koxon** [comment]
+1 this was just fine before. Now I need to click on each repo to find the one I'm looking for.

**Comment by vegasbrianc** [comment]
+1 This is very difficult to use at the moment. At least allow users to select multiple views.

**Comment by haswalt** [comment]
+1 This is the same for all search results now. The results are now pretty useless and very hard to navigate.

**Comment by connormanning** [comment]
+1 I only get two characters of the actual repository name with the current view and my relatively long username.

**Comment by geekmush** [comment]
+1 at least put a "long listing" option so we can see the full repo names.  cute UI be damned, we need to be able to actually find our repos quickly.

**Comment by emreboga** [comment]
Repositories view has been reverted back to the previous look. Sorry for the inconvenience this may have caused. We'll iterate over this design a bit more before any further changes.
