### ISSUE TITLE
hub.docker.com mobile issues

### ISSUE THREAD

**Issue by crowne** [docker/hub-feedback#618]
When browsing on my mobile chrome 49.0 on android 5.1.1, I can't log in or search repositories.
I can only browse official repositories.

**Comment by yegle** [comment]
Please drop the responsive design. I'd rather like a non-mobile-friendly website instead of mobile-*friendly* but completely unusable website.

![screenshot_20160524-085042](https://cloud.githubusercontent.com/assets/146133/15510587/ea486e1e-218c-11e6-9807-4c02a777e540.png)

**Comment by rmrf** [comment]
+1 for yegle's suggestion.

**Comment by marcusmartins** [comment]
cc @akshayvyas

**Comment by javabrett** [comment]
I went to raise an issue that the mobile site doesn't allow login but found this issue from 18 months ago first.

I am forced to tell my browser to Request Desktop Site.

Could we just unhide the login option at least, even if it switches to non- mobile for login?

Daft to have a mobile Sign Up with no Sign In!
