### ISSUE TITLE
Can't downgrade from Micro to Free

### ISSUE THREAD

**Issue by devyn** [docker/hub-feedback#619]
I click "Remove Plan" and then "Confirm" but nothing happens at all.

**Comment by jgoulah** [comment]
I had this problem until I disabled my ad blocker, then it worked

**Comment by xizhao** [comment]
Also have this issue, disabling ad blocker doesn't help.

**Comment by tescherm** [comment]
@devyn @jgoulah @xizhao can you contact support@docker.com describing the issue? They should be able to investigate further. You can include my gh handle (@tescherm) in the email.
