### ISSUE TITLE
Change the user ID

### ISSUE THREAD

**Issue by nukos** [docker/hub-feedback#622]
I create account.
But, The wrong ID.
Is it possible to change the user ID?

**Comment by LongLiveCHIEF** [comment]
I opened a ticket by logging in using the [Docker ID Login](https://cloud.docker.com/login) page, and then [opening a support ticket](https://success.docker.com/Get_Help/Open_a_Support_Ticket) (🔐 ).

I hope to hear back from someone this week, but we'll see. I have spent more than an hour searching and digging through every nook and cranny, and I only found that "you should contact support" responses in the forums... and no other mention of this ability anywhere else.

I image there could be complications if you have many images in your account, or if you have automated builds setup.

**Comment by shyamchen** [comment]
duplicate #11

**Comment by Shyam-Chen** [comment]
duplicate #11

**Comment by augustoproiete** [comment]
Do not close, please :)
