### ISSUE TITLE
Several of builds per repo push

### ISSUE THREAD

**Issue by willseward** [docker/hub-feedback#627]
When using regex to select the tag name from a tagged git repo, an automated docker repo starts around 20 build jobs.

![screen shot 2016-03-29 at 10 44 05 pm](https://cloud.githubusercontent.com/assets/5386568/14131337/caa76ffa-f5ff-11e5-9833-4b19d1b8ee90.png)

**Comment by armmen** [comment]
I am seeing 2 builds on default trigger
<img width="841" alt="screen shot 2016-04-16 at 11 36 45 am" src="https://cloud.githubusercontent.com/assets/956011/14579770/9c2a0cde-03c7-11e6-9e2e-cf7b1b90aa51.png">

**Comment by willseward** [comment]
I wonder if #578 got resolved.
