### ISSUE TITLE
Unable to drop Private repo plan

### ISSUE THREAD

**Issue by donniev** [docker/hub-feedback#629]
I want to change from the $7/mo plan back to the free plan but that option is not available on site or at least I can't make it work.

**Comment by mghazizadeh** [comment]
that option is here.. https://hub.docker.com/account/billing-plans/ 
You should be able to click on the "remove plan" link above where it says "current" plan. 
Let us know if that doesn't work.

**Comment by donniev** [comment]
i click on that and then click on confirm but nothing happens.
It generates a javascript error.
console:   BillingPlans.jsx:109 Uncaught ReferenceError: MktoForms2 is not defined

**Comment by alfred-landrum** [comment]
Hi @donniev - we're sorry that you hit this. While you're on the billing-plans page, after you see the error, reload the page and try removing the subscription again; we believe that will work around the problem. It's a bug we recently introduced that should be addressed soon.

Please let us know if that does or does not work for you; I just confirmed that reloading the page & retrying worked around the issue for a test account.

**Comment by donniev** [comment]
I was able to use workaround

**Comment by alfred-landrum** [comment]
Thank you @donniev . I've confirmed from our end that you are back to the free plan, have been refunded for the unused portion, and won't be charged further. Please let us know if you run into any further problems!

**Comment by akshayvyas** [comment]
a fix for this issue has been pushed to production.  closing.
