### ISSUE TITLE
Can't find deploy keys

### ISSUE THREAD

**Issue by zh99998** [docker/hub-feedback#633]
I have submodules in my github repo via ssh protocol, and then can't auto build

it says 

```
Build failed: please ensure the correct public key is added to the list of trusted keys for this repository and the remote branch exists. (1)
```

but I can't find deploy keys as documented in Build Details / Build Settings page

my repo and submodules are all **public**.

build logs

```
Starting to clone
Cloning into '.'...
Submodule 'magicseteditor' (git@github.com:mycard/magicseteditor.git) registered for path 'magicseteditor'
Submodule 'ygopro-database' (git@github.com:mycard/ygopro-database.git) registered for path 'ygopro-database'
Submodule 'ygopro-images' (git@github.com:mycard/ygopro-images.git) registered for path 'ygopro-images'
Submodule 'ygopro-images-raw' (git@github.com:mycard/ygopro-images-raw.git) registered for path 'ygopro-images-raw'
Cloning into 'magicseteditor'...
Warning: Permanently added the RSA host key for IP address '192.30.252.122' to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Clone of 'git@github.com:mycard/magicseteditor.git' into submodule path 'magicseteditor' failed
please ensure the correct public key is added to the list of trusted keys for this repository and the remote branch exists. (1)
```

**Comment by ambodi** [comment]
Same here!

**Comment by pchico83** [comment]
@zh99998 could you share the name of the repo?

**Comment by zh99998** [comment]
mycard/ygopro-images-generator

**Comment by pchico83** [comment]
@zh99998 Docker Hub works a little different than Docker Cloud and we plan to encourage our users to move to Docker Cloud, where you can do autobuilds and also do other things like testing pull requests or defining environment variables for your build.
Docker Cloud uses a different mechanism to clone the git repository, I think it will work for your case, could you give it a try?

**Comment by zh99998** [comment]
it not works, I don't know why. just empty log http://postimg.org/image/6wq6o6cc7/
I tried trigger a new build it's still empty log.

and btw

encourage users to move to Docker Cloud is a DISASTER for individual developers and non-profits. it's tooooooooo expensive.
for my project I'm using 4 servers in different locations and cost only $35 / month ($5 + $20 + $10 + free). then I need to pay docker cloud $45 / month !!
I do like Docker Cloud a lot. It's I've been dreaming of. But my project is open source and non-profit. I can't afford it definitely.

**Comment by pchico83** [comment]
@zh99998 It is blocking your builds because looks like there is a pending payment in your account. We are investigating the real reason.
The Docker Cloud Build service charges the same as Docker Hub autobuilds and it is free while in beta. You don't need nodes to use this service. And it has more features than the Hub counter part, like ENV variables and tests for pull requests.

**Comment by pchico83** [comment]
@zh99998 We have fixed the issue in your account.
Could you try to build from Docker Cloud to see if it works now?

**Comment by BlueHotDog** [comment]
Where can i find the deploy keys? so frustrating

**Comment by metal3d** [comment]
See https://github.com/docker/hub-feedback/issues/416 that is the same issue it seems. We cannot build images sometimes when submodules are in use

**Comment by zh99998** [comment]
closing this since long time inactive

**Comment by jsandersrocks** [comment]
I got this issue when I had an empty subdirectory in my repo

**Comment by 0xcaff** [comment]
How did you add an empty subdirectory to your repo @jsandersrocks? https://stackoverflow.com/questions/115983/how-can-i-add-an-empty-directory-to-a-git-repository

**Comment by jsandersrocks** [comment]
.gitignore can be used to do that

**Comment by vhosakot** [comment]
I saw the same error when I triggered automated build for my private GitHub repo.

```
Building in Docker Cloud's infrastructure...
Cloning into '.'...
Warning: Permanently added the RSA host key for IP address '192.30.253.112' to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.

please ensure the correct public key is added to the list of trusted keys for this repository (128)
```

Adding the deploy Key in “Build Settings” in Docker Hub to my GitHub account at https://github.com/settings/keys resolved this issue for me and the automated build passed for my private GitHub repo.

**Comment by FedericoBiccheddu** [comment]
@vhosakot where did you find "Build settings"?

**Comment by vhosakot** [comment]
@FedericoBiccheddu After logging into Docker Hub and setting up automated build, you'll see "Build Setting" in the menu at the top:

![screen shot 2018-04-03 at 9 25 53 am](https://user-images.githubusercontent.com/8882663/38252110-58b90a1a-3721-11e8-9a4e-ea029edf0099.png)

**Comment by darkpixel** [comment]
There's no deploy key under Build Settings...
![dockerhub-builds](https://user-images.githubusercontent.com/158380/38264274-551bda58-3727-11e8-9538-75dd019882ab.png)

**Comment by vhosakot** [comment]
@darkpixel I see "Deploy Key" below "Build Triggers" in "Build Settings" in Docker Hub. Is the source repo a private repo? Mine is private repo.

![screen shot 2018-04-03 at 1 49 30 pm](https://user-images.githubusercontent.com/8882663/38266284-45ef5a0e-3746-11e8-99af-fe7106abd98d.png)

**Comment by darkpixel** [comment]
I didn't see that.  I had to blow away by automated build and re-create it.
I think the problem was that the github repo was created as a public repo back in the day, then the automated build was created, then the github repo was converted to private.  It would be nice to have a 'generate key' or 'regenerate key' button or something like that for people who might actually mind blowing away their build history. ;)

**Comment by oerp-odoo** [comment]
> I didn't see that. I had to blow away by automated build and re-create it. I think the problem was that the github repo was created as a public repo back in the day, then the automated build was created, then the github repo was converted to private. It would be nice to have a 'generate key' or 'regenerate key' button or something like that for people who might actually mind blowing away their build history. ;)

I had to change user that was connected with docker hub. And old key used was lost.

I deleted docker hub repository and recreated it. And I still see same public key after re-creating repo.. How is that even secure?..
Also how am I supposed to generate new key? There is no "re-generate" button or something..
