### ISSUE TITLE
Docker Ignore File can fail build

### ISSUE THREAD

**Issue by kilpatty** [docker/hub-feedback#636]
If docker-compose.test.yml is included in the .dockerignore file, a build will fail automatically due to hub.docker not finding the service "sut" in docker-compose.test.yml. 

This should be documented somewhere as previously we had a docker-compose.test.yml file for testing our image, and it took us a while to find out that by including that file in the dockerignore (with no effect on the actualy build process) it would kill the build everytime.

See: https://hub.docker.com/r/zzrot/alpine-ghost/builds/bnlqhvct8hn2unvdtq5w9fg/
and : https://hub.docker.com/r/zzrot/alpine-caddy/builds/bpt4t2jsjc9wvfysjvpapjj/

**Comment by caervs** [comment]
Thank you @Skilgarriff. We will be sure to make that clear in the documentation.
