### ISSUE TITLE
API Support

### ISSUE THREAD

**Issue by richburdon** [docker/hub-feedback#637]
The V1 API seems to be deprecated, but the V2 API still in "spec" mode. Are there up-to-date docs on the HTTP API? Does Docker still support this?

**Comment by richburdon** [comment]
The current API requires user/password. This isn't a good option for orgs (e.g., ability to build an admin dashboard showing automated build status for an organization.)

Typically this kind of auth is provided by an API-KEY, such as was implemented by Tutum (now Docker Cloud), which has a pretty good API.

**Comment by everett-toews** [comment]
@richburdon Do you have a link to the "spec" for the v2 API?

The v1.7 API is documented [here](https://docs.docker.com/v1.7/reference/api/docker-io_api/). Comically the v1.8 API is "deprecated as of 1.7" [here](https://docs.docker.com/v1.8/reference/api/docker-io_api/). Normally one would expect 1.9 to deprecated 1.8.

**Comment by thaJeztah** [comment]
@richburdon what exactly do you mean with "still in spec mode"? The V2 specification is documented here; https://github.com/docker/distribution/blob/master/docs/spec/api.md. Docker Hub uses this specification, but adds some additional endpoints from the V1 specs (e.g. The "search" endpoint). I agree this should be documented better (perhaps someone of the Docker Hub team can help with that)

@everett-toews the "as of 1.7" refers to the Docker Engine release, not the API version, yes, may need to be tweaked a bit

**Comment by thaJeztah** [comment]
Update to my last comment (in case people arrive here); Docker's API spec was donated to the OCI, and used for the OCI distribution spec, which now reached `v1.0.0`: https://github.com/opencontainers/distribution-spec/tree/v1.0.0


For Docker-Hub specific APIs, we also started publishing documentation for those specific endpoints, which can be found in the reference section at https://docs.docker.com: https://docs.docker.com/docker-hub/api/latest/
