### ISSUE TITLE
Please mark HHVM/HHVM as official

### ISSUE THREAD

**Issue by Webysther** [docker/hub-feedback#639]
The repository is official of facebook team: https://hub.docker.com/r/hhvm/hhvm/

https://twitter.com/HipHopVM/status/705063018606886912

**Comment by thaJeztah** [comment]
Can you open this request in https://github.com/docker-library/official-images ? I think that's the place to ask this

**Comment by Webysther** [comment]
docker-library/official-images/issues/1638

**Comment by thaJeztah** [comment]
Awesome, thanks!
