### ISSUE TITLE
Too many failed login attempts

### ISSUE THREAD

**Issue by svenmueller** [docker/hub-feedback#642]
We are using Travis to build and push Docker container to Docker Hub. We have huge problems with running the build since the Docker API behaves weird when using `docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"` (the environment variables are set as encrypted variables in `.travis.yml`).

We run multiple builds using the `matrix` directive of travis. Each run triggers a `docker login.` For lots of builds in matrix build we are seeing the following error response (credentials are correct.)

```
Error response from daemon: Login: Too many failed login attempts. You have been locked out for one hour. Try again later or contact support. (Code: 429; Headers: map[Content-Type:[application/json] Vary:[Cookie] X-Frame-Options:[SAMEORIGIN] Strict-Transport-Security:[max-age=31536000] Server:[nginx/1.6.2] Date:[Tue, 12 Apr 2016 20:37:05 GMT]])
```

The next build in the travis matrix might work again (login successfull, image is pushed) following by the same error again.

```
Error response from daemon: Login: Too many failed login attempts. You have been locked out for one hour. Try again later or contact support. (Code: 429; Headers: map[Content-Type:[application/json] Vary:[Cookie] X-Frame-Options:[SAMEORIGIN] Strict-Transport-Security:[max-age=31536000] Server:[nginx/1.6.2] Date:[Tue, 12 Apr 2016 20:44:02 GMT]])
```

**Comment by svenmueller** [comment]
This completly breaks our build pipeline since nearly all builds in the builds matrix fail (which causes the build fail in total). The travis build matrix only triggers 8 builds (using `docker login`). So i can't imagine that we are hitting any API rate limit here already.

**Comment by mcgeeco** [comment]
Why doesn't the error message say how long I'm locked out for? What am I supposed to do now? Surely resetting your password should reset the login attempts? This is nuts.

**Comment by DinisCruz** [comment]
I'm having the same problem (using travis for the builds)

@svenmueller , @mcgeeco How did you solved this issue?

**Comment by marcusmartins** [comment]
@DinisCruz Can you email support@docker.com with more details and we can help you from there?

**Comment by marcusmartins** [comment]
@svenmueller Are you still experiencing issues with too many login attempts? We have made some changes to our brute force protection that should help with the travis ci use case.

**Comment by DinisCruz** [comment]
@marcusmartins the problem solved itself in the morning

At the moment all is good (thx)

**Comment by svenmueller** [comment]
In my case the problems originated from a problem in image `dockercloud/haproxy`. The problem was solved for me by using the image `dockercloud/haproxy` with tag >= `1.4.2`.

**Comment by svenmueller** [comment]
see https://github.com/docker/dockercloud-haproxy/issues/33
