### ISSUE TITLE
This server does not respond to non-GET requests

### ISSUE THREAD

**Issue by sleewoo** [docker/hub-feedback#644]
Did not receive confirmation email so went to Help / Support.
"Resend Confirmation" button redirects to https://hub.docker.com/account/resend-email-confirmation/?next=/account/jwt page which says "This server does not respond to non-GET requests".

Can you please resend the confirmation email to crudle at sleewoo.com

Thank you.

**Comment by thaJeztah** [comment]
@sleewoo can you send an email to support@docker.com? They should be able to look into your issue

**Comment by sleewoo** [comment]
thanks
