### ISSUE TITLE
Can push an image past the private repo limit

### ISSUE THREAD

**Issue by danmx** [docker/hub-feedback#648]
I have one private repository and defaults set to create new private repos. When I pushed new image to the hub server didn't check the limit and created another private repo. Result was:

> Private Repositories:Using 2 of 1

I didn't get any information about being charged extra nor trial didn't kicked in.

**Comment by bcwalrus** [comment]
Yeah, the current design optimizes for not failing `docker push`. The newly created repo will be "locked", and can't be pulled. You can unlock it by making it public, or by upgrading your subscription plan.

Closing for now. Let me know if that doesn't work for you. Thanks!
