### ISSUE TITLE
Cannot browse hub.docker.com

### ISSUE THREAD

**Issue by ve3** [docker/hub-feedback#650]
Logged in to hub.docker.com
Click on explore
 - Nothing happens, I must reload that page then the list showup.
Click on page 2
 - Nothing happens. Can't go to page2.

Most link on hub.docker.com are broke and cannot go anywhere.
Cannot search cannot browse anywhere.

Browser: Firefox 45.0.2
OS: Windows 10

**Comment by akshayvyas** [comment]
@ve3 is this still broken for you?  For us, using Win 10, Firefox 45.x, the "Explore" link works properly and I can see the list.  Are you using any Ad Blockers by chance?  If yes, what vendor?

**Comment by ve3** [comment]
Yes, it works fine now. 
Please notice that I was reported this issue since April 22.

**Comment by akshayvyas** [comment]
@ve3 apologies for the extremely delayed response and action.  We are committed to address some of the long reported issues in the coming days and weeks.  Really appreciate your patience as we catch up.

**Comment by ve3** [comment]
:-) No problem.

Thank you for your response.
