### ISSUE TITLE
Cannot push locally built docker image to public repo in dockerhub

### ISSUE THREAD

**Issue by cristina-grosu** [docker/hub-feedback#651]
Steps to reproduce:

- build docker image from github project
- login into dockerhub
- tag docker image
- try to push tagged image to dockerhub

Error:
Please login prior to push:
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x29 pc=0x686108]

goroutine 1 [running]:
github.com/docker/docker/api/client.(*DockerCli).clientRequestAttemptLogin(0xc208506000, 0x13a2270, 0x4, 0xc20850a720, 0x30, 0x0, 0x0, 0x7f5435c6c3d8, 0xc20803e008, 0x0, ...)
	/builddir/build/BUILD/docker-78ee77d1ede95dcbc0c021ec722ed85178dc38ed/_build/src/github.com/docker/docker/api/client/utils.go:182 +0x258
github.com/docker/docker/api/client.func·016(0x0, 0x0)
	/builddir/build/BUILD/docker-78ee77d1ede95dcbc0c021ec722ed85178dc38ed/_build/src/github.com/docker/docker/api/client/push.go:69 +0x16e
github.com/docker/docker/api/client.(*DockerCli).CmdPush(0xc208506000, 0xc20800a020, 0x1, 0x1, 0x0, 0x0)
	/builddir/build/BUILD/docker-78ee77d1ede95dcbc0c021ec722ed85178dc38ed/_build/src/github.com/docker/docker/api/client/push.go:78 +0xb25
reflect.callMethod(0xc20850a270, 0xc208505c60)
	/usr/lib/golang/src/reflect/value.go:605 +0x179
reflect.methodValueCall(0xc20800a020, 0x1, 0x1, 0x1, 0xc20850a270, 0x0, 0x0, 0xc20850a270, 0x0, 0x4e37df, ...)
	/usr/lib/golang/src/reflect/asm_amd64.s:29 +0x36
github.com/docker/docker/cli.(*Cli).Run(0xc2084dbf50, 0xc20800a010, 0x2, 0x2, 0x0, 0x0)
	/builddir/build/BUILD/docker-78ee77d1ede95dcbc0c021ec722ed85178dc38ed/_build/src/github.com/docker/docker/cli/cli.go:89 +0x38e
main.main()
	/builddir/build/BUILD/docker-78ee77d1ede95dcbc0c021ec722ed85178dc38ed/docker/docker.go:71 +0x624

goroutine 5 [syscall]:
os/signal.loop()
	/usr/lib/golang/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
	/usr/lib/golang/src/os/signal/signal_unix.go:27 +0x35

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:2232 +0x1

goroutine 11 [runnable]:
net/http.(*persistConn).readLoop(0xc2080a04d0)
	/usr/lib/golang/src/net/http/transport.go:928 +0x9ce
created by net/http.(*Transport).dialConn
	/usr/lib/golang/src/net/http/transport.go:660 +0xc9f

goroutine 12 [select]:
net/http.(*persistConn).writeLoop(0xc2080a04d0)
	/usr/lib/golang/src/net/http/transport.go:945 +0x41d
created by net/http.(*Transport).dialConn
	/usr/lib/golang/src/net/http/transport.go:661 +0xcbc

I also tried to pull an existing image and i get the same error.

docker version
Client:
 Version:         1.9.1
 API version:     1.21
 Package version: docker-1.9.1-25.el7.centos.x86_64
 Go version:      go1.4.2
 Git commit:      78ee77d/1.9.1
 Built:           
 OS/Arch:         linux/amd64

Server:
 Version:         1.9.1
 API version:     1.21
 Package version: docker-1.9.1-25.el7.centos.x86_64
 Go version:      go1.4.2
 Git commit:      78ee77d/1.9.1
 Built:           
 OS/Arch:         linux/amd64

ocker info
Containers: 2
Images: 165
Server Version: 1.9.1
Storage Driver: devicemapper
 Pool Name: docker-8:2-203595977-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 107.4 GB
 Backing Filesystem: 
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 26.49 GB
 Data Space Total: 107.4 GB
 Data Space Available: 6.393 GB
 Metadata Space Used: 26.7 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.121 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.107-RHEL7 (2015-12-01)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.10.0-229.el7.x86_64
Operating System: CentOS Linux 7 (Core)
CPUs: 24
Total Memory: 94.1 GiB
Name: instance-15533.bigstep.io
ID: VUZ4:YJG4:J2Z7:6LFH:Q4QG:WRPQ:E4RQ:Q4M6:77SV:YROJ:XMI6:WPTZ
Username: mcristinagrosu
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled

Any ideas?

**Comment by sylnsr** [comment]
Are you using AWS anywhere?  (GO AWS SDK)

**Comment by bcwalrus** [comment]
This sounds like an engine bug. Could you file it under https://github.com/docker/docker? Thanks!
