### ISSUE TITLE
Unexpected error on automated build

### ISSUE THREAD

**Issue by RikuXan** [docker/hub-feedback#655]
I'm trying to let my Image build on Docker Hub and getting a failed build with the message `Build failed: Unexpected error`. 

The complete output is:

    Starting to clone
    Cloning into '.'...
    Note: checking out '2def0101328c9ac33ef7cf405ca04b2c5f60778a'.
    
    u are in 'detached HEAD' state. You can look around, make experimental
      changes and commit them, and you can discard any commits you make in this
    state without impacting any branches by performing another checkout.
    
    If you want to create a new branch to retain commits you create, you may
    do so (now or later) by using -b with the checkout command again. Example:
    
      git checkout -b new_branch_name
    
    Cloning done
    Starting Build
    KernelVersion: 3.13.0-40-generic
    Os: linux
    BuildTime: 2016-02-22T21:37:01.910365059+00:00
    ApiVersion: 1.22
    Version: 1.10.2
    GitCommit: c3959b1
    Arch: amd64
    GoVersion: go1.5.3
    Starting build of index.docker.io/itsecur/seafile:5.1.0...
    Unexpected error

The build code is `b6tyavbu9yfho3qlcqqn5gn`. It seems not to be an issue with the Dockerfile/Scripts itself, since the build seems to fail before even looking at any of those.

**Comment by stocks29** [comment]
What was the issue?

**Comment by RikuXan** [comment]
There actually was an error in the Dockerfile (a missing backslash IIRC), building it locally actually gave a useful error message.

**Comment by stocks29** [comment]
Thank you!
