### ISSUE TITLE
ubuntu:latest (16.04) image does not contain 'sudo', breaking old Dockerfile builds

### ISSUE THREAD

**Issue by priestlyemu** [docker/hub-feedback#656]
I have a number of Dockerfiles that are based on a plain 'FROM ubuntu'. These containers depend on 'sudo' being installed, which up until 14.04.4 the latest image had.

When 16.04 became the latest, my containers broke. While I understand I can modify my containers to use 14.04 specifically or install sudo, it seems this change might cause problems for others, so I thought I'd report it.

% docker run ubuntu:14.04.4 sudo echo foo
foo

% docker run ubuntu:16.04 sudo echo foo
docker: Error response from daemon: Container command 'sudo' not found or does not exist..

**Comment by rafaelsoaresbr** [comment]
I think the right place to submit a issue is here: https://github.com/tianon/docker-brew-ubuntu-core

**Comment by priestlyemu** [comment]
Done - thanks, didn't really understand where to best report it.
