### ISSUE TITLE
github auto builds no perms

### ISSUE THREAD

**Issue by xcrezd** [docker/hub-feedback#659]
Hi, im trying to setup git hub auto builds and get the error(i see it only in debug console - not in UI)

{"detail": "You do not have permission to perform this action."}

I dont have reached limits with private repo yet, so its look like a bug.
![screenshot_2016-05-01_09-03-06](https://cloud.githubusercontent.com/assets/1153266/14940442/f68199e2-0f7d-11e6-8e5b-fe52e34e70a0.png)

This is the Request Payload:
![screenshot_2016-05-01_09-23-41](https://cloud.githubusercontent.com/assets/1153266/14940450/6af79826-0f7e-11e6-8277-d94965d1ae92.png)

**Comment by valerybugakov** [comment]
@xcrezd have you managed to resolve this issue?

**Comment by xcrezd** [comment]
@valerybugakov Typically, the link should be https://hub.docker.com/add/automated-build/github/form/<your-GitHub-repo-namespace>/<GitHub-repo-name>/?namespace=<your-namespace-on-Hub>
