### ISSUE TITLE
Windows images not visible

### ISSUE THREAD

**Issue by StefanScherer** [docker/hub-feedback#660]
I have pushed some Windows Docker images to Docker Hub with TP5, but they aren't visible at https://hub.docker.com/r/stefanscherer/

<img width="1440" alt="docker-images" src="https://cloud.githubusercontent.com/assets/207759/15006939/e239c924-11d4-11e6-95ca-66710c104232.png">

From another TP5 machine I cannot pull them, but after a `docker login` I can pull them. So they seem to be there. It seems to me that they are some kind of private?

**Comment by uday-shetty** [comment]
The issue was fixed yesterday. When did you push the image?

**Comment by StefanScherer** [comment]
I've pushed them two days ago. Today I was able to pull them without a login. And yes, I can see my swarm-windows image with all the tags. So I just should push again to make them visible.
Thanks!

**Comment by uday-shetty** [comment]
Thanks!
