### ISSUE TITLE
Could not link create automated build for Github team repo

### ISSUE THREAD

**Issue by Hainish** [docker/hub-feedback#664]
I'm trying to create an automated build for a github repo I admin and belongs to a team:

https://github.com/efforg/phantom-of-the-capitol

But when I link my account, I'm only able to create autobuilds for repos  that belong to me.

**Comment by afeld** [comment]
If your GitHub organization has [third-party app restrictions](https://help.github.com/articles/about-third-party-application-restrictions/) enabled, you may need to [request](https://help.github.com/articles/requesting-organization-approval-for-your-authorized-applications/)/[grant](https://help.github.com/articles/approving-third-party-applications-for-your-organization/) access to the Docker Hub "application" so it can access those GitHub repositories.

**Comment by caervs** [comment]
Thanks for your response @afeld. That is correct. @Hainish please let us know if you continue to have problems.
