### ISSUE TITLE
Repository does not exist

### ISSUE THREAD

**Issue by clashdot** [docker/hub-feedback#666]
After proper login, and checking in the web page that the repo is declared, the docker push command 
      $ docker push [user]/[repo-name]:[tag]
returns  
     The push refers to a repository [docker.io/[user]/[repo-name]]
     Repository does not exist: [user]/[repo-name]

Here is the client info
$ docker version
Client:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:44:17 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Wed Apr 27 00:34:20 2016
 OS/Arch:      linux/amd64

$ docker info
Containers: 19
 Running: 0
 Paused: 0
 Stopped: 19
Images: 9
Server Version: 1.11.1
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 62
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: host bridge null
Kernel Version: 4.4.8-boot2docker
Operating System: Boot2Docker 1.11.1 (TCL 7.0); HEAD : 7954f54 - Wed Apr 27 16:36:45 UTC 2016
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.955 GiB
Name: default
ID: DBHS:HX3Q:XCOY:O4SV:DHYP:DE5H:EY3Q:TPP3:E5RE:ORHB:X4FO:CBOC
Docker Root Dir: /mnt/sda1/var/lib/docker
Debug mode (client): false
Debug mode (server): true
 File Descriptors: 12
 Goroutines: 29
 System Time: 2016-05-09T18:12:43.749102472Z
 EventsListeners: 0
Username: [user]
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
$

**Comment by marcusmartins** [comment]
@clashdot if you're still experiencing the issue, could you send more details to support@docker.com so we can troubleshoot the issue?
