### ISSUE TITLE
I'm trying to pay you, but you don't let me

### ISSUE THREAD

**Issue by orlando** [docker/hub-feedback#667]
I'm getting this error message when trying to update my subscription

![httpshub docker comaccountbilling-planscreate-subscriptionplanindex_personal_medium_2016-05-10_21-40-16](https://cloud.githubusercontent.com/assets/849872/15148541/369d3604-16f8-11e6-8209-72e0f2635a33.png)

**Comment by marcusmartins** [comment]
@orlando if it's still issue for you, can you contact support@docker.com?

**Comment by orlando** [comment]
@marcusmartins yes, I contacted support and they solved it really quickly. Thanks!
