### ISSUE TITLE
Typo in Trusted Registry CTA

### ISSUE THREAD

**Issue by gordonsyme** [docker/hub-feedback#668]
![screen shot 2016-05-11 at 12 02 52](https://cloud.githubusercontent.com/assets/1714741/15178896/6e813160-1770-11e6-9526-31d6ade55850.png)

This should read "Need an on-premises registry?"

"premises" is used in the singular to mean the collection of buildings, land etc that are considered a property.
A "premise" is an assumption used for a logical argument.

**Comment by thaJeztah** [comment]
Can you provide the URL where you found that typo?

**Comment by gordonsyme** [comment]
It's literally just my Docker Hub dashboard which has a URL of https://hub.docker.com/ according to my browser.

The CTA shows on the right, but only shows when you've created at least one repository.

**Comment by thaJeztah** [comment]
oh thanks! I wasn't logged in :smile:

I'll pass it on to the team

**Comment by marcusmartins** [comment]
Thanks for the report.
