### ISSUE TITLE
Cannot build from public github project

### ISSUE THREAD

**Issue by evantahler** [docker/hub-feedback#669]
re: https://hub.docker.com/r/evantahler/actionhero

I'm trying to set up an automatic build from https://github.com/evantahler/actionhero, but I keep getting an error: `Build failed: please ensure the correct public key is added to the list of trusted keys for this repository and the remote branch exists. (1)`.  

<img width="1165" alt="screen shot 2016-05-14 at 12 33 19 pm" src="https://cloud.githubusercontent.com/assets/303226/15270322/3f1ef094-19d0-11e6-97ed-f5cfcefa5331.png">

What key are you referring too? I've configured  docker to have full access.  Perhpas the oAuth permissions also need public repositories?

<img width="770" alt="screen shot 2016-05-14 at 12 35 14 pm" src="https://cloud.githubusercontent.com/assets/303226/15270326/61d121a2-19d0-11e6-9cf4-b4c84ca90c97.png">

**Comment by mghazizadeh** [comment]
Hi, have you been able to resolve this, or does the issue still persist?

**Comment by evantahler** [comment]
Not really... I believe that I've isolated to the fact that there is a submodule in the project, but it is referential.  The error message doesn't make much sense, but it is indicating that "git-submodle cannot be loaded".

You can see the self-reference here https://github.com/evantahler/actionhero/tree/master/site

**Comment by evantahler** [comment]
Removing the submodule reference fixed it.

**Comment by vhosakot** [comment]
I saw the same error when I triggered automated build for my private GitHub repo.

```
Building in Docker Cloud's infrastructure...
Cloning into '.'...
Warning: Permanently added the RSA host key for IP address '192.30.253.112' to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.

please ensure the correct public key is added to the list of trusted keys for this repository (128)
```

Adding the deploy Key in “Build Settings” in Docker Hub to my GitHub account at https://github.com/settings/keys resolved this issue for me and the automated build passed for my private GitHub repo.

**Comment by nirodg** [comment]
For `fatal: no submodule mapping found in .gitmodules for path 'src'` the solution it was to properly define the git submodule `git submodule add the_repo`

https://git-scm.com/book/en/v2/Git-Tools-Submodules

**Comment by smilerc** [comment]
> I saw the same error when I triggered automated build for my private GitHub repo.
> 
> ```
> Building in Docker Cloud's infrastructure...
> Cloning into '.'...
> Warning: Permanently added the RSA host key for IP address '192.30.253.112' to the list of known hosts.
> Permission denied (publickey).
> fatal: Could not read from remote repository.
> Please make sure you have the correct access rights
> and the repository exists.
> 
> please ensure the correct public key is added to the list of trusted keys for this repository (128)
> ```
> 
> Adding the deploy Key in “Build Settings” in Docker Hub to my GitHub account at https://github.com/settings/keys resolved this issue for me and the automated build passed for my private GitHub repo.

where did you find Key? in which Build Settings?
