### ISSUE TITLE
notifications@docker.com spam filtered out by gmail

### ISSUE THREAD

**Issue by keizie** [docker/hub-feedback#670]
"Why is this message in Spam? It has a from address in docker.com but has failed docker.com's required tests for authentication.  Learn more" message shows up on top of mail body.
"Learn more" link goes https://support.google.com/mail/answer/1366858?hl=en&authuser=1&expand=5

Mail subject is "There's been an issue with your automated build" which failed with my first hub experience. (that means mail itself is not a spam)

**Comment by pkennedyr** [comment]
We are currently investigating this issue (HUB-2351) and will post an update as soon as the resolution is available.

**Comment by marcusmartins** [comment]
The issue has been fixed, new notifications will arrive from `no-reply@notify.docker.com`
