### ISSUE TITLE
"Log in to Docker Hub" fails from support.docker.com, beta.docker.com, etc

### ISSUE THREAD

**Issue by theGrue** [docker/hub-feedback#672]
I can log in fine at hub.docker.com, but when I try to access support.docker.com or beta.docker.com, I'm prompted with a "Log in to Docker Hub" screen that asks me to enter my username/password again. Using the same credentials I used at hub.docker.com, I receive an error stating "Please enter a correct username and password."

Sorry if this isn't the right place, I'd love to be able to open a proper support ticket, but I'm not able to log in to the support page.

**Comment by thaJeztah** [comment]
Can you send an email to support@docker.com? They should be able to look into this

**Comment by marcusmartins** [comment]
@theGrue can you confirm if your issue was resolved?

**Comment by theGrue** [comment]
Yes, I noticed that hub.docker.com (the page that worked) was lowercasing my username in between clicking the login button and submitting the form, while the "Log in to Docker Hub" pages were not. Typing my username in all lowercase letters was able to get me in to those sites.

**Comment by marcusmartins** [comment]
@theGrue Thanks for reporting the lowercase issue, we have created an internal ticket for it.
