### ISSUE TITLE
Pushing more than three tags at once fails

### ISSUE THREAD

**Issue by mhart** [docker/hub-feedback#673]
If you perform a `git push` and more than three tags are pushed up, none of these tags are picked up by Docker Hub.

It seems that three tags is the most you can push at once.

This is reproducible, not sporadic

**Comment by marcusmartins** [comment]
@mhart thanks for the report, I am investigating it.

**Comment by marcusmartins** [comment]
@mhart can you confirm if you're using bitbucket or github?

**Comment by mhart** [comment]
@marcusmartins github

**Comment by marcusmartins** [comment]
thanks @mhart we are working with GitHub on the issue. I will update the issue when we get a resolution.

**Comment by marcusmartins** [comment]
Hi @mhart, Docker Hub uses Github webhooks to start builds and Github doesn't send any webhook if the push contained more than 3 tags (https://developer.github.com/v3/activity/events/types/#createevent)

We will document that limitation on our side but I hope you can adjust your workflow to avoid pushing more than 3 tags at once.
