### ISSUE TITLE
Running into checksum error during yum install

### ISSUE THREAD

**Issue by jakirkham** [docker/hub-feedback#675]
Encountering this issue on DockerHub only. Note that we are doing CI with CircleCI and are not encountering this issue. Log snippet below from a recent [log](https://hub.docker.com/r/condaforge/linux-anvil/builds/bpo92gub7cudu6hmnthwxtd/). This has happened with the last 3 builds.

```
Rpmdb checksum is invalid: dCDPT(pkg checksums): centos-release-scl-rh.noarch 0:2-1.el6.centos - u
[0m 
Removing intermediate container 76a26421f715
The command '/bin/sh -c yum update -y &&     yum install -y                    centos-release-scl                    yum-utils &&     yum-config-manager --add-repo http://people.centos.org/tru/devtools-2/devtools-2.repo &&     yum update -y &&     yum install -y                    devtoolset-2-binutils                    devtoolset-2-gcc                    devtoolset-2-gcc-c++ &&     yum clean all' returned a non-zero code: 1
```

**Comment by tianlai** [comment]
I'm running into the same symptom by just do `yum install -y openssh-server` based on centos7 image. Successfully built with local docker engine consistently.
