### ISSUE TITLE
Extremely high lag between builds

### ISSUE THREAD

**Issue by HariSekhon** [docker/hub-feedback#678]
I've noticed extremely high wait times for builds to start (often 10 hours). I know this issue is not new but wanted to raise it again as it's quite surprising considering it only takes a couple mins to do a build and if you look at other online systems like Travis it usually only takes a few mins to trigger a build from GitHub.

**Comment by marcusmartins** [comment]
@HariSekhon thanks for the report. Can you contact support@docker.com with more details?
