### ISSUE TITLE
Add ability to delete tags

### ISSUE THREAD

**Issue by cgswong** [docker/hub-feedback#68]
I sometimes refactor code and completely change my tagging style (from say `v4.0` to `4.0`), or just want to remove a `beta` tag once the code is released so that is no longer available. I understand this may impact downstream users using the previous tags but I think it would still be good to delete tags without making a support request.

**Comment by jakirkham** [comment]
+1

**Comment by posita** [comment]
This functionality was at least available in the old UI. It has always (frustratingly) been manual-only (see docker/docker#8759), but not even that is available in the beta. :disappointed:

**Comment by kunickiaj** [comment]
+1

**Comment by pward123** [comment]
+1

**Comment by thiagozs** [comment]
+1

**Comment by yveshwang** [comment]
+1

**Comment by sebest** [comment]
+1

**Comment by michaelgruber** [comment]
+1

**Comment by jgkamat** [comment]
+1

**Comment by kunickiaj** [comment]
Seems like some older tags are being automatically wiped out? Is there some undocumented limit? Since it's still not possible to manage your own tags this is a huge problem.

**Comment by rrarunan** [comment]
@kunickiaj See #194. We show only 100 tags at a time in the web interface. Is the assumption of older tags not available coming from just the UI or does your pull not work for example with the older tags? And, this should discussed in a different issue, if #194 is not the case for you.

**Comment by schmunk42** [comment]
+1 - very important feature

**Comment by aayore** [comment]
+1

**Comment by arnau** [comment]
+1

**Comment by n0mer** [comment]
+1

**Comment by jawaid** [comment]
+1

**Comment by feedthefire** [comment]
+1

**Comment by arangamani** [comment]
+1

**Comment by yoanisgil** [comment]
Who many +1 it takes before we get at least an initial feedback? Anyhow:

+1

**Comment by jakirkham** [comment]
I think this is the relevant issue for implementing this feature ( https://github.com/docker/distribution/issues/422 ).

**Comment by yoanisgil** [comment]
@jakirkham docker/distribution#461 and docker/distribution#462 are the actual issues to keep track of progress. Still I think it would be nice if there is feedback from hub-*feedback* :)

**Comment by jakirkham** [comment]
I lifted that from this comment here ( https://github.com/docker/docker/issues/8759#issuecomment-103963545 ). I assumed he knew what he meant.

**Comment by onizo** [comment]
+1

**Comment by adambiggs** [comment]
+1

**Comment by StudioEtrange** [comment]
+1

**Comment by DerekRoberts** [comment]
+1

**Comment by jamesdbloom** [comment]
+1

**Comment by cacti77** [comment]
+1. I can't believe this isn't in the UI already! I'd accidentally included some security credentials in a tag (luckily a private repo!). My only recourse was to delete the repo and recreate it; or to upload 'dummy' tagged images to overwrite the old ones already there.

**Comment by posita** [comment]
For anyone seeking to delete tags, it can apparently be done by submitting a request to support@docker.com (see [this](https://github.com/docker/hub-feedback/issues/368#issuecomment-147577966)).

Not to get too punchy here, but I suspect if everyone subscribed to this thread sent such requests when needed, there might be a greater incentive to provide an automated solution. [Jus' sayin'.](http://www.urbandictionary.com/define.php?term=jussayin%27&defid=6321356) :wink:

**Comment by posita** [comment]
FYI, one can also use https://support.docker.com/hc/en-us/requests/new to request manual tag deletion instead of e-mailing requests to support@docker.com.

**Comment by nhumrich** [comment]
+1

**Comment by polds** [comment]
+1

**Comment by thepont** [comment]
+1

**Comment by SebastianStiehl** [comment]
+1

**Comment by drwatson32** [comment]
+1

**Comment by JeremJR** [comment]
+1

**Comment by nathan-osman** [comment]
+1

**Comment by ohjames** [comment]
+1

**Comment by earldouglas** [comment]
+1

**Comment by SolomonShorser-OICR** [comment]
:+1:

**Comment by vassilvk** [comment]
+1

**Comment by faubertin** [comment]
+1

**Comment by jochenehret** [comment]
+1

**Comment by sylwit** [comment]
+1

**Comment by n0mer** [comment]
@rrarunan any updates on this?

**Comment by rrarunan** [comment]
@n0mer we are working on it. We should be able to provide an update real soon. Thanks for checking.

**Comment by faceleg** [comment]
@rrarunan could you please lock this thread until you have an update? Infinity +1 are one +1 too many

**Comment by jakirkham** [comment]
@rrarunan, or could you just ping us so we don't have to be subscribed to know about an important update? (thus avoiding +1 noise)

**Comment by wernight** [comment]
+1 it's more important than ever now that it auto tag-builds any branch.

**Comment by 34code** [comment]
+1

**Comment by nhsiehgit** [comment]
Hey all - Locking this thread to avoid the noise.

Sorry for the wait everyone. We've got the feature merged, just waiting a deploy.

Thank you for your patience!

**Comment by nhsiehgit** [comment]
We've just deployed the delete tags feature, thank you all for your patience!

**Comment by posita** [comment]
Just curious, but what is the default sort order for tags?

**Comment by posita** [comment]
@nhsiehgit, is this UI only, or is there a corresponding API?

**Comment by nhsiehgit** [comment]
@posita Just UI for now.

**Comment by JeremJR** [comment]
@nhsiehgit I'm sorry but I don't see the way to do that into https://hub.docker.com/r/foo/bar/tags could you please point me the good path?

**Comment by posita** [comment]
@JeremJR, it took me a while to find it as well. Try hovering over the right side of the row for the tag you want to delete. A `Delete` link should appear. When you click it, you should be given a new choice of links to `Confirm` or `Cancel`.

It's not a very intuitive interface. :disappointed: It's also two clicks per delete. With no batch option, and no API, if one has hundreds of tags to delete, it's going to take awhile. I guess it's better than nothing though. :persevere:

**Comment by ruffsl** [comment]
I saw the blue text "Delete" last night when I check the deploy, but you seem to be right in that it appears to be oddly hidden currently:
![anim](https://cloud.githubusercontent.com/assets/2293573/11594656/35507410-9a79-11e5-84dc-96f40a91ed3a.gif)

**Comment by posita** [comment]
@ruffsl, I just noticed the same thing. Filed as #498.

**Comment by jakirkham** [comment]
Looks like there is now a cool trash icon. :+1:

**Comment by ricoli** [comment]
so what about the ability to delete a tag using the API @nhsiehgit, is it being worked on?

**Comment by nhsiehgit** [comment]
hey @ricoli,

There's a lot of changes coming up this year, and a publicly available api library is one of them on the list. Unfortunately I can't say that this (in particular delete tags) will be arriving anytime within the next few months, but you should start seeing other endpoints coming up.

**Comment by jakirkham** [comment]
@nhsiehgit, is there a roadmap for the features that are coming up? If it could be shared publicly, it would be nice if it could be added to this repo. I think it would help a lot of us in our planning to know what things to expect when. Also, if there are changes to the schedule, it would help us track and understand a bit more why something gets planned later.

**Comment by vassilvk** [comment]
@nhsiehgit, I second @jakirkham's post.

**Comment by posita** [comment]
@nhsiehgit wrote:
> ... There's a lot of changes coming up this year, and a publicly available api library is one of them on the list. ...

@nhsiehgit, can you reference any open issues (if they exist)? If not, is there a publicly visible road map, where we can track progress?

**Comment by jakirkham** [comment]
As it seems there are a few people interested in having a roadmap beyond myself, I have made it a formal issue ( https://github.com/docker/hub-feedback/issues/601 ) feel free to subscribe, +1, or add any other relevant details that I may have missed.

**Comment by lindsaymacvean** [comment]
So is there a separate issue/request for an api call to remove tags from a dockerhub image repo?

**Comment by VincenzoFerme** [comment]
@lindsaymacvean here you find the way we do it in [ASQ](https://github.com/ASQ-USI/ASQ): https://github.com/ASQ-USI/ASQ/blob/devel/lib/support/docker/hub/delete-tags.js

**Comment by schasse** [comment]
+1

**Comment by sbrunner** [comment]
+1

**Comment by lindsaymacvean** [comment]
@VincenzoFerme  thanks. 

For other people reading this, its the npm package https://www.npmjs.com/package/docker-hub-api which has a ready made js object for interacting with the docker hub api.

**Comment by amcp** [comment]
+1

**Comment by mathstuf** [comment]
Not really. There's no official API for it. You can do some minor scripting in the browser developer console to help select tags to delete in the interface, but you're stuck with 15 images at a time on a page, so any bulk deletion is limited to 15 items at a time (assuming you can even get 15 eligible tags at a time; you may be stuck with fewer items per page if you need to keep some around). Using JS to select checkboxes speeds things up, but is still molasses.

You can also poke around and find the internal API that is being used on the management page and script around *it*, but it seems that the token or cookie involved expires after an hour. As I mentioned in #2448, getting proper APIs for this would bypass any UX design work required on the web and allow users to make their own tools as needed. There's already an API, just make it official. Gate it behind specially-permissioned tokens if needed or whatever, just don't make things like this have to go through the web interface.
