### ISSUE TITLE
Push Repo Organizations is visibility on private

### ISSUE THREAD

**Issue by nutchaitat** [docker/hub-feedback#682]
### Expected behavior
Push Repo Organizations is visibility on private

![screenshot from 2016-05-30 22 52 51](https://cloud.githubusercontent.com/assets/8242227/15653887/09a4f3cc-26ba-11e6-823c-273239e08ed5.png)

**Comment by marcusmartins** [comment]
@nutchaitat I am sure what is the bug you're reporting here. Can you give me steps to reproduce or a longer explanation of the issue?

**Comment by marcusmartins** [comment]
@nutchaitat I am closing this ticket for now. Please reopen if you have more details or steps to reproduce.
