### ISSUE TITLE
Automated Builds sharing 1 GitHub repo rebuilds ALL images instead of only changed Dockerfile / build context dir

### ISSUE THREAD

**Issue by HariSekhon** [docker/hub-feedback#683]
This is basically the same issue as #403 but I'm re-raising it as it needs more attention among the other 365 issues as this issue results in extremely long build times across all automated builds linked to the same github repo as it rebuilds ALL docker images every time anything in the github repo changes and is surely costing DockerHub money to leave it so inefficient.

**Comment by pkennedyr** [comment]
@HariSekhon: Thanks for feedback. We have prioritized this FR in our backlog and will post an update as soon as the the feature is available. In the meantime, please refer to https://github.com/docker/hub-feedback/issues/403 for updates as this is a dup.
