### ISSUE TITLE
Docker Push images not showing up in repository

### ISSUE THREAD

**Issue by jeremymills** [docker/hub-feedback#684]
Images are failing to be updated/show up in docker hub after a docker push:

I get a successful message that it has been pushed but don't see it in the repository.

```sh
docker push IMAGE/NAME:latest
The push refers to a repository [docker.io/IMAGE/NAME]
af93a2375e12: Pushed 
1b8174d1387d: Pushed 
363b36bab54a: Pushed 
efe24b28f1e3: Pushed 
7876b2fc1a61: Pushed 
5f70bf18a086: Pushed 
5433617a39a5: Pushed 
5f70bf18a086: Pushed 
7876b2fc1a61: Pushed 
6ac717e42869: Layer already exists 
91f74371a1cf: Layer already exists 
05dbef3c79d9: Layer already exists 
0e6095a19b91: Layer already exists 
8e1ac573880e: Layer already exists 
68bf10b691d4: Layer already exists 
79d2abbb4495: Layer already exists 
816f1903c60f: Layer already exists 
c12ecfd4861d: Layer already exists 
latest: digest: sha256:cacb54b5d8059231415ea8835af2ecb3gt3s09a4c640a10d13aec56b2f6527d5 size: 21577
```

NOTE: it's been 30min since my last push and still nothing has shown up.

**Comment by jeremymills** [comment]
Update: I can however pull the image down from docker hub, I just can't see it within the dashboard

**Comment by marcusmartins** [comment]
@jeremymills today we experienced a high volume of push and pull operations and we were taking longer to process new repositories and tags. Can you confirm if you can see your repository now?

**Comment by jeremymills** [comment]
@marcusmartins I can see them now, thank you
