### ISSUE TITLE
Cannot create new organization on hub.docker.com

### ISSUE THREAD

**Issue by yurishkuro** [docker/hub-feedback#685]
When I click Create button, the boundary of the textbox with organization name turns red, but no error message or anything. Looking at the network traffic in inspector I see a failure:

![image](https://cloud.githubusercontent.com/assets/3523016/15720866/4484463c-2804-11e6-9aac-cc2bbf3921fc.png)

I tried different names (one word, hyphen-separated and underscore-separated names), and different browsers (Chrome, Safari), always the same result.

**Comment by yurishkuro** [comment]
* Operating system - MacOS 10.11.4
* Browser and Browser version - Chrome 50.0.2661.102 (64-bit)
* URL for the page in question - https://hub.docker.com/organizations/add/
* Any error messages (on screen or in browser console)
![image](https://cloud.githubusercontent.com/assets/3523016/15721255/2025b576-2806-11e6-8c90-ff514d1b5cec.png)
* The rough date and time the error occurred (be sure to include your time zone) - right before ticket
* Your hub username - javajumbo

**Comment by marcusmartins** [comment]
@akshayvyas @emreboga can you check this issue?

**Comment by emreboga** [comment]
I tried the same and the response is:
`{"orgname": ["Invalid value."]}`
I tried without the hyphens or underscores and it worked.
@yurishkuro can you validate that?

**Comment by yurishkuro** [comment]
I dug down more into the Inspect tool and found the server response saying "name already in use". So I can get by now, but ideally the UI would show this error message somewhere, rather than just marking the textbox in red border without explanation.

**Comment by emreboga** [comment]
@yurishkuro I created a org with a totally random name (sdfghjkloiuytr_1) but it still failed and I think it's because of the underscore, not because the org exists. I tried without the underscore and it succeeded. I think there might be a problem with the API's error reporting in the first place.

**Comment by jimmycuadra** [comment]
Same problem here, it's rejecting org names with dashes or underscores. Are these actually not allowed or is it a mistake?

**Comment by bcwalrus** [comment]
Special characters are not allowed. Org names and user names have the same syntax limit: alphanumeric between 4 and 30 characters. We'll work on better error messages.

**Comment by dmr** [comment]
I have the same issue with the name "netsyno"

**Comment by niiamon** [comment]
@bcwalrus this issue still persists. The form fails with the organisation namespace highlighted without any explanatory text or hint of what the allowable names are or whether the selected name is already in use. Complete trial and error to actually get it to work.

**Comment by giorgiosironi** [comment]
As of today, same problem, thanks for the pointers about looking into the browser console.

**Comment by leighghunt** [comment]
Same problem exists for me too - error console gives feedback `{orgname: ["An organization with the same name already exists."]}`, which is valid, but there's no visual feedback on screen - only red text box.

**Comment by gtirloni** [comment]
When trying to create an organization, I only get "POST https://hub.docker.com/v2/orgs/ 400 (BAD REQUEST)"

The org name has no special characters and searching for it doesn't show any results either.

**Comment by tjwenger** [comment]
Same problem here for me in the GUI - I get the unique namespace, but several combinations do not work - that don't exist.

**Comment by typpo** [comment]
@bcwalrus This issue should be reopened.  Org creation is still failing silently and in a way that is clearly not intended.  Very frustrating.  My name fits the requirements - alphanumeric, no special characters.  No error is shown - the page is just unresponsive when I click "Create"

**Comment by devx** [comment]
This issue should be reopened as the issue is still exists.

**Comment by bw2** [comment]
Also seeing this issue

**Comment by paulfwilliams** [comment]
Getting mysterious error with 3-letter organization (company initials).  Chrome reports: "Failed to load resource: the server responded with a status of 400 (BAD REQUEST)".  I assume this is a duplicate organization error, because I am able to create an organization with a longer name.

**Comment by akhalili** [comment]
The problem still exists

**Comment by Labibme** [comment]
Hello, i have same issue from ui

**Comment by jorgelimafeitosa** [comment]
yeah, fix it!
