### ISSUE TITLE
api calls do not return the same list of tags as the web interface (missing tags)

### ISSUE THREAD

**Issue by ssbarnea** [docker/hub-feedback#687]
We have a private docker registry at hub.docker.io and we discovered that the api does not return all the tags that are visible in the web interface.

API call like https://index.docker.io/v1/repositories/company/reponame/tags returns a list that is not the same as the one we are seeing on https://hub.docker.com/r/company/reponame/tags/

Some tags are not returned by the API even after 16h from when they were changes. My impression is that the ones that are not returned are the ones that were added later, as aliases.

I already raised this problem on http://stackoverflow.com/questions/37590442/hub-docker-io-reports-tags-in-the-web-interface-but-we-cannot-some-of-them-using because I was not sure it was bug, but now I think is a bug, a severe one.

**Comment by samuelsinayoko** [comment]
I've had the same problem.

**Comment by earnaway** [comment]
I noticed this last week and again it's happening now. I can see the tags in the web interface, but they're missing from the API.

**Comment by goowikns** [comment]
Same for me... This is really bad timing :(

**Comment by ssbarnea** [comment]
Here are some insights: it seems that you can get the correct list of tags if you are using the v2 API but the v1 API returns an incomplete list of them. 

I was able to port the code to use the v2 API but it was a real PITA - the fact that the v2 API is marketed as simple or easy to use is just a big joke. The only authentication that I've seen to be more complicated than the docker one was the kerberos one. So many API calls only to perform basic tasks.

**Comment by goowikns** [comment]
So i guess the docker package used in Synology uses the API v1 instead of 2.

I truly hope they can just hotfix their web api service in time ^^

**Comment by chevdor** [comment]
Same issue, same conclusion here.
Synology seems to be still running API v1. It still remains strange that v1 does not return the same results than v2. I could see that v1 returns the OLD tags but not the newer. That means that more and more people will run into the issue overtime. Especially, if one rebuild the 'latest' tag of an image, it will not longer be visible...

**Comment by TheTwist76** [comment]
I've had the same problem.

**Comment by nivong** [comment]
yep same issue here, have any reported it to synology yet? I have done just now if everyone does it they may consider it

**Comment by chevdor** [comment]
I find Synology VERY unresponsive, especially when it comes to handling issues reported via their support system. I suggest, if you want a change as I do, is to use twitter. It seems that they don´t like the bad publicity and it is also much easier for people seeing your tweet to +1 or RT to add their voice publicly. This is unfortunate but seems to be how it is...
Here is my original Tweet, feel free to RT: https://twitter.com/chevdor/status/749280932239183872

**Comment by nivong** [comment]
I got a respons from synology:
```
Dear Customer,

Thank you for contacting Synology support.

Not every registry/repo support v2, so our plan in the future is to implement a way to obtain tag using v1 first and use v2 as a failover if tag could not be obtained.

For now, you can pull images via command to mitigate this issue.

docker pull <image>:<tag>

Hope this helps.

Best Regards,
Allen C.
Synology Technical Support

**Comment by kellenarb** [comment]
Just to share a workaround, you can SSH into your synology and run:

`docker pull <user/image>:latest`

This will grab the latest tag for the Image and it will show up under "Image" in the Docker GUI.

**Comment by ghusta** [comment]
Still having the same problem with registry API v1 today : 
"I could see that v1 returns the OLD tags but not the newer."

Tested on this image : "ghusta/jboss-as" which should return at least 2 tags but returns none with API v1.

**Comment by ssbarnea** [comment]
Some teams need to learn the meaning of *API contract*.... Everywhere you ask about docker you hear about people that hate that each update breaks everything.

**Comment by awaissindhu** [comment]
Hey guys,

Any resolution on this? I am hitting the same issue. Is there a work around?

**Comment by chevdor** [comment]
Since this will get closed, I would recommend anyone to simply stay away from using Synology's Docker. Like many of the stuff they do, they will likely drop it...
You will save time installing (you probably need the command line to map the .sock) portainer or something equivalent and using that instead of the over-buggy and barely maintained Synology option.

**Comment by bruvv** [comment]
No need to keep this open since this specific issue has been fixed ;)
