### ISSUE TITLE
Cannot add email address with dot separators before the @

### ISSUE THREAD

**Issue by danielgraf** [docker/hub-feedback#688]
If I try to add an email address with a dot in the part before the @, it fails validation.

firstname.lastname@organisation.com fails

If I remove the dot it works

firstnamelastname@organisation.com works

but my email does have a dot in there - weird eh ?

<img width="719" alt="dockerhub" src="https://cloud.githubusercontent.com/assets/9585750/15761867/6bf7a394-2912-11e6-96d1-45a9114591ca.png">

**Comment by bcwalrus** [comment]
Dots should be ok. I suspect that the email is associated with another account already. I'll add a task to improve error reporting.

**Comment by bcwalrus** [comment]
@danielgraf Please reopen if necessary.

Btw, you can find out the account associated with the email via the reset password flow. https://hub.docker.com/reset-password/

**Comment by bcwalrus** [comment]
Fixed and improved error message.

**Comment by AndreyLebedenko** [comment]
An issue is still there.
