### ISSUE TITLE
Cancel individual Automated queued builds

### ISSUE THREAD

**Issue by HariSekhon** [docker/hub-feedback#692]
Considering how slow DockerHub is to build automated builds and there ends up being a backlog of builds in the queue we need an ability to cancel queued builds so that only the latest ones are left in the queue.

**Comment by bcwalrus** [comment]
@HariSekhon, thanks for reporting this. As a workaround, build cancellation will be available on cloud.docker.com very soon (next week-ish).

**Comment by rkrug** [comment]
Any news on this? Is it implemented?

**Comment by pkennedyr** [comment]
@rkrug Build cancelation is currently available on Docker Cloud (cloud.docker.com):

> To view active builds, go to the repository view and click Timeline. The Timeline displays the pending, in progress, successful and failed builds for any tag of the repository. Click to expand a timeline entry to check the build logs. You can click the Cancel button for pending builds and builds in progress. If a build fails, the cancel button is replaced by a Retry button.

For more information on automated builds with Docker Cloud, check out: [https://docs.docker.com/docker-cloud/builds/automated-build/](https://docs.docker.com/docker-cloud/builds/automated-build/)

Also, we are actively building support for build cancelation within Docker Hub.

**Comment by rkrug** [comment]
Thanks - I think I will wait than.

Rainer

**Comment by pkennedyr** [comment]
We are happy to announce that build cancelation is now available on Docker Hub.

To cancel a build, navigate to the Build Details tab of a repository and click the Cancel button for a given queued or in progress build.

**Comment by rkrug** [comment]
Thanks a lot.
