### ISSUE TITLE
Issues building with apt commands with several packages

### ISSUE THREAD

**Issue by wikier** [docker/hub-feedback#693]
I've observed an issue when building images (automated builds) with `apt-get install` commands with several packages. Sometimes I'm getting the following [error](https://hub.docker.com/r/redlinkgmbh/search-ci-env/builds/bujvruh4zqrrf3pgojp62uj/):

```
Build failed: The command 
'/bin/sh -c apt-get update -qq && apt-get install -y nodejs-legacy npm ruby-compass ghostscript imagemagick openjdk-8-jdk maven mongodb' 
returned a non-zero code: 100`
```

Just moving to individual commands per package (which is not optimal for Docker layers) fixes the issue (see for instance [this commit](https://github.com/redlink-gmbh/search-ci-env/commit/ce14e8755b1eb2fd45258977ce8f10d9c914bd17) to get the build working).

Where could be the issue? Does Docker Hub have any APT cache or something that could be causing such issue?

**Comment by marcusmartins** [comment]
Hi @wikier thanks for the report. We will investigate the issue with networking between our build infrastructure and the deb packages.

**Comment by wikier** [comment]
OK, thanks @marcusmartins, let me how how I can help debugging the issue.
