### ISSUE TITLE
DockerHub badly broken bug trying to build ALL Git Branches and ignoring Dockerfile location settings

### ISSUE THREAD

**Issue by HariSekhon** [docker/hub-feedback#694]
DockerHub seems broken after I switched from Git tags to branches for my builds and is referencing branches from other repos when failing a build when that branch isn't even referenced in the build settings of the currently failing repo build!

See this build for an example (update: this has now become blank since fixing see further below)

https://hub.docker.com/r/harisekhon/pytools/builds/b3lojepnjrcca9ssbefjejq/

It looks like it's started building all branches for a github repo instead of just the configured branch of master - and on top of that it's not respecting the Dockerfile location which I specified in build settings.

This problem is being multiplied across all repos, related to issue #403.

Looking at the Build Details page it's trying to do a build for every branch and due to #692 I can't canel them either. 

Looking back it seems as though the repos may have a blank branch line which is causing this - removing it seems to remove the queue builds too.

There should be a protection against a blank line matching everything and trying to build all branches... I don't even know how that is supposed to work - how would it tag them when it's not been specified.

Seems like an input validation error. Also if you really do want to build all branches surely it should require an explicit .* regex or something. This might go unnoticed on smaller repos...

**Comment by bcwalrus** [comment]
Hi Hari, thanks for reporting the bug. I managed to reproduce with the source name set to `//` (an empty regex). Fixing that. Could you confirm that's what happened?

**Comment by bcwalrus** [comment]
Fixed.

**Comment by HariSekhon** [comment]
In my case it was a single slash as per the default when you click the plus sign on the right to get a new line.
