### ISSUE TITLE
Git tag/branch regex group captures for auto DockerHub tag naming - {groupN} variables similar to {sourceref}

### ISSUE THREAD

**Issue by HariSekhon** [docker/hub-feedback#695]
Feature Request to support regex group capture variables from Git tags/branches, similar to ```{sourceref}``` which captures the whole thing, ```{groupN}``` can be used to capture a subset using standard regex brace capture.

I've been using git tags and branches heavily for Docker tags, but sharing my Dockerfiles in a single repo to avoid cluttering up my GitHub with tonnes of tiny repos. This means I can't make tags as simple as ```1.0``` but must specify ```name-1.0``` to disambiguate.

However I don't want all my DockerHub tags to come out as ```name-1.0``` as that would make it ```harisekhon/name:name-1.0``` which is silly so right now I'm stuck having to enter the mappings of the different git refs vs the manually specified DockerHub tags in the build settings page for each repo.

**Comment by bcwalrus** [comment]
Try `{\1}`, `{\2}`, etc.

**Comment by HariSekhon** [comment]
This gives me the following error:
```
{\1}: Invalid 'name' field: Unknown variable '\1' at position 2
```

**Comment by bcwalrus** [comment]
That could be because your regex doesn't have any capture group. What's your regex value? (You can specify capture groups with parans in the regex.)

**Comment by HariSekhon** [comment]
I was using parens in the regex to capture the number version at the end of the branch name field, eg. ```name-(\d+\.\d+)``` in the branch name field (I've been using regex extensively for over 10 years). I also tried ```{$1}``` as well as ```{\1}``` in the tag field but neither worked, giving the same error. The only other detail is that I'm using a Dockerfile /directory path in the Dockerfile location field.

**Comment by bcwalrus** [comment]
Hi Hari, could you try using `/name-(\d+\.\d+)/` in the source name field? The leading and trailing slashes are important. Otherwise, it's not considered a regex, and will do a verbatim full-string match.

**Comment by HariSekhon** [comment]
Ah, yes that does work with the regex slashes, thanks.
