### ISSUE TITLE
gitlab-ci.yml-style image/tag specification

### ISSUE THREAD

**Issue by peredin** [docker/hub-feedback#697]
I'm using Docker Hub to store a few repositories of commonly used base images, for example a build-base repository setting up make and CMake in multiple environments.

Linking Git tags and branches to Docker tags is quite painful. I want to keep my Git repository clean and well organized and I can't accomplish that. Currently I have two options:
1. Create a branch for each docker tag and add a Dockerfile to that branch in the root.
2. Place Dockerfiles in subdirectories (e.g. `/debian/Dockerfile`), commit everything to master and manually setup Dockerfile paths in Docker Hub.

Option 1 makes the Git repository non-linear. Unless one compares the dates of commits it would not be possible to see that Debian Wheezy was added after Alpine 3.4 (see my example). It's also impossible to checkout master and see the latest Dockerfiles for all images at the same time.

Option 2 makes the Git repository linear but the addition of new distros and/or versions isn't automatic, as I would have to add a rule in the Hub for each new distro. A fix in `/debian/Dockerfile` for Wheezy after Jessie has been added would also make the commit diffs really ugly if not useless. Fixing that by placing files in `/debian/jessie/Dockerfile` means even more manual messing with Docker Hub Build Settings.

Instead I would like to specify the names of tags and the Dockerfile to build them in a single file inside my Git repository, e.g. `.docker-hub.yml`. Just like builds are configured in GitLab CI and other CI-systems.

When a change is pushed to Git, Docker would checkout `master` and re-build all images based on the contents of the `.docker-hub.yml` file.

I have created a sample Git repository demonstrating how I would like to be able to specify tags and Dockerfiles. It can be found at https://github.com/peredin/docker-hub-wish.

**Comment by rafaelsoaresbr** [comment]
It would be an even more interesting feature if this problem were also implemented #500
