### ISSUE TITLE
Build queued for ever since added ENV HOME=/root in Dockerfile

### ISSUE THREAD

**Issue by chariut** [docker/hub-feedback#698]
Build says Queued for the past 3 hours. 
Latest change is added the entry "ENV HOME=/root" to Dockerfile to fix the following error:
[INFO] Building image bla/bla-bla
[91mJun 09, 2016 6:11:44 PM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (java.io.IOException) caught when processing request to {}->unix://localhost:80: No such file or directory 

Dockerfile:
FROM maven:3.2-jdk-7-onbuild
EXPOSE 8080
ENV HOME=/root
CMD mvn clean install

**Comment by mghazizadeh** [comment]
We're actively addressing the issue - please refer to  http://status.docker.com  for latest updates. Apologies for the inconvenience.
