### ISSUE TITLE
openshift failed to pull any docker image

### ISSUE THREAD

**Issue by habeeb1985** [docker/hub-feedback#700]
I created a sample project on openshift origin v1.2.0 and tried then to make a new app from sample docker image hello-world and it failed to pull the docker image with only this error message "Err image pull" , this issue started to happen from last Thursday or Wednesday, it was working before that date.

oc Command I ran:

oc new-app --name=hello --docker-image=hello-world:latest --insecure-registry=true

console output:
--> Found Docker image 2cc4873 (4 days old) from Docker Hub for "hello-world:latest"

```
* An image stream will be created as "hello:latest" that will track this image
* This image will be deployed in deployment config "hello"
* The image does not expose any ports - if you want to load balance or send traffic to this component
  you will need to create a service with 'expose dc/hello --port=[port]' later
* WARNING: Image "hello-world" runs as the 'root' user which may not be permitted by your cluster administrator
```

--> Creating resources with label app=hello ...
    imagestream "hello" created
    deploymentconfig "hello" created
--> Success
    Run 'oc status' to view your app.

But on web console I got this error "Err image pull" and the app failed to be deployed, please give me advice why docker image pull failed from openshift origin.

**Comment by rvernica** [comment]
I have the same problem. I contacted OpneShift support. Here is their answer:
> It looks like the actual manifest error could be caused by pulling a Docker image that is not built with Docker engine 1.9. OpenShift Origin 1.2 that is deployed in OpenShift Online developer preview, depends on Docker 1.9. As a consequence of the recent change to the DockerHub to stop supporting pull-by-digest for images pushed by newer Docker clients, users of OpenShift running Docker 1.10 may experience problems pulling images from the Hub. We are working on addressing this issue in an upcoming patch release. I'm unable to provide any timeline on the patch at this moment, unfortunately.
