### ISSUE TITLE
DockerHub builds so slow that Perl IO::Tty build times out after 60 secs

### ISSUE THREAD

**Issue by HariSekhon** [docker/hub-feedback#702]
```
Fetching http://backpan.perl.org/authors/id/T/TO/TODDR/IO-Tty-1.12.tar.gz ... OK
Configuring IO-Tty-1.12 ... Timed out (> 60s). Use --verbose to retry.
make:  make[1]: wait: No child processeswait: No child processes.  Stop.
.  Stop.
make[1]: make: Waiting for unfinished jobs.... Waiting for unfinished jobs....

make: *** make[1]:  wait: No child processeswait: No child processes.  Stop.
.  Stop.
```

https://hub.docker.com/r/harisekhon/nagios-plugins/builds/bgvkp3u3lsr5vjyzmtwwdfz/

**Comment by HariSekhon** [comment]
Several more failing builds:

https://hub.docker.com/r/harisekhon/spotify-tools/builds/brqmwtvsuqfs7z5bdabc9pr/

https://hub.docker.com/r/harisekhon/tools/builds/bzz9weacvhssn23qqqv8pih/

https://hub.docker.com/r/harisekhon/debian-github/builds/b6qucqh7ssymbgneiczpxv6/

https://hub.docker.com/r/harisekhon/nagios-plugins/builds/b2cydyxgu3wjgnbt3d7umec/

**Comment by pchico83** [comment]
@HariSekhon We use `m3.medium` EC2 instances, which should suffice in the majority of the cases. Would you able to increase that timeout?
We are also working on providing larger build instance types.

**Comment by HariSekhon** [comment]
I don't think it's the instance size that's an issue... it's the fact that too many builds are running concurrently... I'm having several issues with DockerHub's builds, I get a lot of out of disk space build failures too, see #677.

I'm not sure if I can increase the timeout as it's a CPAN library and is pulled with that timeout setting embedded.

**Comment by HariSekhon** [comment]
comment to keep open
