### ISSUE TITLE
debian:jessie - Failed to pull Docker image

### ISSUE THREAD

**Issue by jadbox** [docker/hub-feedback#703]
Just hit this issue today on aws Beanstalk:

`Pulling repository docker.io/library/debian
Tag jessie not found in repository docker.io/library/debian
Failed to pull Docker image debian:jessie-backports: 1: Download complete
17bd2058e0c6: Verifying Checksum
17bd2058e0c6: Download complete
Pulling repository docker.io/library/debian
Tag jessienot found in repository docker.io/library/debian. Check snapshot logs for details.`

**Comment by thaJeztah** [comment]
What version of Docker are you running? I'm not able to reproduce;

```
docker pull debian:jessie
jessie: Pulling from library/debian
5c90d4a2d1a8: Pull complete
Digest: sha256:8b1fc3a7a55c42e3445155b2f8f40c55de5f8bc8012992b26b570530c4bded9e
Status: Downloaded newer image for debian:jessie
```

Could you add the output of `docker version` and `docker info`?

**Comment by gracig** [comment]
Hi, The same problem here:

GersonMacPro:goenv gerson$ docker version
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   a34a1d5
 Built:        Fri Nov 20 17:56:04 UTC 2015
 OS/Arch:      darwin/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   a34a1d5
 Built:        Fri Nov 20 17:56:04 UTC 2015
 OS/Arch:      linux/amd64
GersonMacPro:goenv gerson$ docker pull debian:jessie
jessie: Pulling from library/debian
17bd2058e0c6: Verifying Checksum 
f854eed3f31f: Verifying Checksum 
Pulling repository docker.io/library/debian
Tag jessie not found in repository docker.io/library/debian

**Comment by gracig** [comment]
Now it is working. But don't know what was happening

**Comment by Tuuleh** [comment]
I'm seeing this same issue on Elastic Beanstalk since yesterday, with a few different tags. There's an i/o timeout after some layers. I haven't been able to reproduce locally. 

```
Jul 01 10:51:17 champaign-staging eb-activity.log:    Pulling repository soutech/champaign_web
Jul 01 10:51:17 champaign-staging eb-activity.log:    Get https://registry-1.docker.io/v1/repositories/soutech/champaign_web/tags: read tcp 52.72.94.105:443: i/o timeout
Jul 01 10:51:17 champaign-staging eb-activity.log:    Failed to pull Docker image soutech/champaign_web:e0d627281835bf762f1774328fb0c5729f82f272: . Check snapshot logs for details.
Jul 01 10:51:17 champaign-staging eb-activity.log:    Traceback (most recent call last):
Jul 01 10:51:17 champaign-staging eb-activity.log:      File "/usr/bin/eventHelper.py", line 55, in <module>
Jul 01 10:51:17 champaign-staging eb-commandprocessor.log:  [2016-07-01T17:51:17.309Z] ERROR [12627] : Command execution failed: Activity failed. (ElasticBeanstalk::ActivityFatalError)
Jul 01 10:51:17 champaign-staging eb-commandprocessor.log:  caused by: e0d627281835bf762f1774328fb0c5729f82f272: Pulling from soutech/champaign_web
```

**Comment by navinamin** [comment]
while running docker/run on macos

following error comes

Unable to find image 'hc-dev-tools:jessie' locally
docker: Error response from daemon: pull access denied for hc-dev-tools, repository does not exist or may require 'docker login'.
See 'docker run --help'.

And 
:holochain $ make
go get -u github.com/whyrusleeping/gx
package github.com/blang/semver: mkdir /Users/kanchankuber/go/src/github.com/blang/: permission denied
package github.com/mitchellh/go-homedir: mkdir /Users/kanchankuber/go/src/github.com/mitchellh/: permission denied
package github.com/urfave/cli: mkdir /Users/kanchankuber/go/src/github.com/urfave/: permission denied
# cd .; git clone https://github.com/ipfs/go-ipfs-api /Users/kanchankuber/go/src/github.com/ipfs/go-ipfs-api
fatal: could not create work tree dir '/Users/kanchankuber/go/src/github.com/ipfs/go-ipfs-api': Permission denied
package github.com/ipfs/go-ipfs-api: exit status 128
# cd .; git clone https://github.com/jbenet/go-os-rename /Users/kanchankuber/go/src/github.com/jbenet/go-os-rename
fatal: could not create work tree dir '/Users/kanchankuber/go/src/github.com/jbenet/go-os-rename': Permission denied
package github.com/jbenet/go-os-rename: exit status 128
# cd /Users/kanchankuber/go/src/github.com/multiformats/go-multiaddr; git pull --ff-only
error: cannot open .git/FETCH_HEAD: Permission denied
package github.com/multiformats/go-multiaddr: exit status 1
# cd /Users/kanchankuber/go/src/github.com/multiformats/go-multiaddr-net; git pull --ff-only
error: cannot open .git/FETCH_HEAD: Permission denied
package github.com/multiformats/go-multiaddr-net: exit status 1
# cd /Users/kanchankuber/go/src/github.com/multiformats/go-multihash; git pull --ff-only
error: cannot open .git/FETCH_HEAD: Permission denied
package github.com/multiformats/go-multihash: exit status 1
package github.com/sabhiram/go-git-ignore: mkdir /Users/kanchankuber/go/src/github.com/sabhiram/: permission denied
make: *** [/Users/kanchankuber/go/bin/gx] Error 1

So cant run hcadmin ,hcd  ,hcdev  commands

**Comment by thaJeztah** [comment]
The `hc-dev-tools:jessie` is not an image on Docker hub; https://hub.docker.com/_/hc-dev-tools/, so it's expected that you get that error if you don't have that image locally and docker attempts to pull it.

The "permission denied" errors seem to be commands you run locally on your machine, and you don't have permissions?

**Comment by navinamin** [comment]
Thanks for your reply.
Ok,
Yes i am running on my mac locally
But because of rest of errors  So cant run hcadmin ,hcd ,hcdev commands
I have attached my sequence of commands issued. If you can go thru and help me out.
It would be great
[ERROR HOLA.txt](https://github.com/docker/hub-feedback/files/1631518/ERROR.HOLA.txt)

**Comment by thaJeztah** [comment]
It's failing because it's attempting to add a new user with `uid 0`, which fails because `uid 0` is the user-id for `root` and the `root` user already exists.

```
Step 6/8 : RUN useradd -mUu $uid holochain && adduser holochain sudo && sed -i -e'/%sudo/s/(ALL:ALL) ALL/(ALL:ALL) NOPASSWD: ALL/' /etc/sudoers
 ---> Running in 1959c666e566
useradd: UID 0 is not unique
The command '/bin/sh -c useradd -mUu $uid holochain && adduser holochain sudo && sed -i -e'/%sudo/s/(ALL:ALL) ALL/(ALL:ALL) NOPASSWD: ALL/' /etc/sudoers' returned a non-zero code: 4
```

Likely because either you're running the build as root (and their script attempts to pass the current user's `uid` to the `docker build` command), or they set `uid` to `0` as a default somewhere;

https://github.com/metacurrency/holochain/blob/a3e2f6992a9b33b6ab7e7953cfec9afa97588321/docker/build.sh#L9-L14

In any case, this is not a bug in Docker nor an issue with Docker Hub, so it's best to report this issue in the https://github.com/metacurrency/holochain issue tracker

**Comment by navinamin** [comment]
Thank you so much. Yes I was running as Admin User. I Created a standard user it worked fine.
Thanks
