### ISSUE TITLE
Feature Request: Tag images of same git reference rather than duplicating automated builds (wasting builds + downloads)

### ISSUE THREAD

**Issue by HariSekhon** [docker/hub-feedback#707]
Feature request to tag images of the same git reference in the same repo instead of building each and duplicating images in automated builds.

Currently each tag gets it's own build even when they are pointing to the same git branch, leading them to have different hashes (probably due to the entropy of different builds, different timestamps etc) and subsequently clients who download both tags (as I often do to test again multiple versions) end up pulling effectively the exact same software version generated with the exact same Dockerfile and git reference twice for no good reason that I can think of.

For example, I may have a tag ```2``` for the 2.x series of software as well as ```2.0``` and ```2.1``` tags. The ```2``` represents the latest version in 2.x but when testing you can pull ```2``` or ```2.1``` or both as you may want to test the latest as well as testing ```2.1``` should latest ```2``` move beyond it.

De-duplicating docker automated builds when they point to the exact same git reference would save Docker money and time in not having to build both things which are exactly the same git revision as well as saving bandwidth for Docker and clients who don't have to download separate images containing identical software versions.

**Comment by bcwalrus** [comment]
Hari, if you could specify multiple tags in the autobuild rule (https://github.com/docker/hub-feedback/issues/341), would that address this use case?

**Comment by HariSekhon** [comment]
Yes it would, right now I'm having to build and download basically the same images multiple times when in reality their git refs and Dockerfile paths are the same. If we could specify multiple tags per build line in the Build Settings page this would address this.

**Comment by bcwalrus** [comment]
Thanks! Closing as dup of https://github.com/docker/hub-feedback/issues/341
