### ISSUE TITLE
Trigger button for regex matched branches / tag in Build Settings

### ISSUE THREAD

**Issue by HariSekhon** [docker/hub-feedback#708]
Feature request to add a Trigger button for regex matched branches / tags on the Build Settings page.

When using branch regex matching there is no Trigger button to be able to trigger builds.

This means when builds fail I have no way to test them without modifying the git branch with pointless changes.

**Comment by thasmo** [comment]
Also the Docker Cloud is not able to do this but it is so much needed.

**Comment by bcwalrus** [comment]
The workaround is to use a build trigger, e.g.

    $ curl -H "Content-Type: application/json" --data '{"source_type": "Tag", "source_name": "v1.1"}' -X POST <trigger_url>

The specified source branch/tag will be evaluated according to the configured build rules, and kick off any matching ones. 
![triggers](https://cloud.githubusercontent.com/assets/171078/17529451/21a0dea0-5e28-11e6-922a-d91dfcf4f697.png)

**Comment by tsarna** [comment]
The curl command returns a successful response for me, with various bits of data, but nothing happens as a result.
