### ISSUE TITLE
Add support for AsciiDoc in 'Full Description' of automated builds.

### ISSUE THREAD

**Issue by sboekhoff** [docker/hub-feedback#709]
As a maintainer of an automated build, I'd like my README-file (in AsciiDoc format) from the linked GitHub repository to be rendered correctly.

Therefore I propose that all README-files with the file extensions `.adoc`, `.asciidoc` and `.ascii` should be processed using http://asciidoctor.org .
## Current behaviour

Currently only Markdown seems to be supported, which results in a 'Full Description' that is hard to read:
![docker-asciidoc-current](https://cloud.githubusercontent.com/assets/10683690/16148443/ed52fe5c-3489-11e6-9b80-a742bc8f7280.png)
## Expected behaviour

Using a file named `README.adoc` with the content:

```
= jekyll-asciidoc-docker
:link-docker: https://www.docker.com/[Docker]
:link-jekyll: https://jekyllrb.com/[Jekyll]
:link-asciidoctor: http://asciidoctor.org/[AsciiDoctor]

{link-docker} image for creating static sites from Asciidoc files using {link-jekyll} and {link-asciidoctor}.
```

should produce the following output:

![docker-asciidoc-expected](https://cloud.githubusercontent.com/assets/10683690/16148091/950f8a78-3487-11e6-847d-15cd2e1ed6b8.png)

**Comment by hakdogan** [comment]
It would have been really nice to support asciidoc.

**Comment by juligreen** [comment]
I'd also love asciidoctor support as it's my preferred documentation method
