### ISSUE TITLE
Downgrade account/billing fails silently when you have too many repos

### ISSUE THREAD

**Issue by russmatney** [docker/hub-feedback#710]
Hit this today, probably not a high priority b/c I was able to work around it, but I wanted to get it reported.

I haven't used docker hub in a while and realized I was still getting invoiced – when I went to downgrade, it was consistently failing silently. Kudos to the error message – I saw a 400 in the inspector that read `{non_field_errors: ["Number of private repos exceeds the amount allotted for the new plan."]}`.

![screenshot 2016-06-19 18 56 33](https://cloud.githubusercontent.com/assets/1596350/16179022/35eed2b2-3651-11e6-876d-6befaf4af19a.png)

When I deleted my private repos, it downgraded fine. Displaying the error message in the browser would solve it immediately.

I'm happy to take a crack at a PR if you are open to one, especially if someone can point me in the right direction.

**Comment by bcwalrus** [comment]
@russmatney Thanks for the bug report! We're tracking it internally.
