### ISSUE TITLE
Occasional "unauthorized: incorrect username or password" when trying to access public repositories anoynmously

### ISSUE THREAD

**Issue by guss77** [docker/hub-feedback#711]
I have an automated build system that pulls publicly accessible images using anonymous access (i.e. just running `docker build` with `FROM ubuntu:<some version>` in the `Dockerfile`), this occasionally breaks with the error message:

    Step 1 : FROM ubuntu:12.04
    Get https://registry-1.docker.io/v2/library/ubuntu/manifests/12.04: unauthorized: incorrect username or password

I believe this is the same issue that was discussed in the closed and locked issue #630 .

Simply running the same configuration again will usually fix the problem, though at times the error will be consistent, requiring to kill the Jenkins VPS slave and re-running the job on a new VPS.

**Comment by guss77** [comment]
This looks like a conflict with another subsystem that logs into a private registry and also sets the login details for the official docker repo. This can be seen in the `~/.docker/config.json` file.

I'm not sure why it does this, but if its a docker issue I'd open a different bug.

**Comment by bcwalrus** [comment]
I see that you've closed the issue. `./docker/config.json` is supposed to have different entries for different registries. One interesting note is that if you have the wrong creds in `config.json`, it'll fail auth before realizing that you're trying to pull a public repo.
