### ISSUE TITLE
Facing issue to fetch latest docker images from nirmata .

### ISSUE THREAD

**Issue by sachinkarale** [docker/hub-feedback#715]
I am facing issue to fetch docker images from nirmata , this images were showing in docker hub and I pulled and tested those from CLI . some of the images are showing in fetch list and some are not , I talked with nirmata support they are telling issue is not from their site .
It's kind request to you , please fix this issue as soon as possible .

**Comment by marcusmartins** [comment]
@sachinkarale can you contact support.docker.com for general support questions?

**Comment by sachinkarale** [comment]
Thank you for your reply , our issue has been resolved.















Regards ,

Sachin Karale ,
System Engineer ,
Bizruntime IT services pvt. Ltd.
