### ISSUE TITLE
Why you can not add a button for 10 months? (issues/355)

### ISSUE THREAD

**Issue by pahaz** [docker/hub-feedback#716]
We are a team, and we do a lot of commits. 
Why do I have to wait to build all containers?

I want stop build process =/ 

10 month! Realy? 
Are you forcing us to use own private registry? 
Do you really want that?

**Comment by pahaz** [comment]
https://github.com/docker/hub-feedback/issues/355

**Comment by mghazizadeh** [comment]
Docker Cloud automated builds and CI have this capability and more. Your Docker Hub repositories are already accessible there as well. Login to cloud.docker.com with the same DockerID to check it out. 

https://docs.docker.com/docker-cloud/builds/automated-build/

There are no plans currently to bring this capability (cancel builds) to Docker Hub autobuilds.

**Comment by mghazizadeh** [comment]
Also, if you are using Docker Hub autobuilds under Orgs/Teams structure provided on Docker Hub, this functionality as well as you existing Team/Org structure in Hub will soon be available in Docker Cloud.

**Comment by yurii-github** [comment]
just started with docker.. lack of this button is real pain.
maybe you can also add something like TravicCI [skip build] or something, for example, when I just want to change comments etc. Right now I have to remember to check/uncheck autobuild on commit.

p.s.
thanks for nice stuff
