### ISSUE TITLE
get trial license page is 404 error

### ISSUE THREAD

**Issue by hailong1004** [docker/hub-feedback#720]
when I access https://hub.docker.com/account/licenses/ , click Get a Trial，it say 404 error https://hub.docker.com/bundles/docker-datacenter/purchase?plan=free-trial

**Comment by marcusmartins** [comment]
Thanks for the report.

**Comment by victor-yarema** [comment]
Looks like this bug might be related to https://github.com/docker/hub-feedback/issues/193.
