### ISSUE TITLE
docker build failing for '/bin/sh -c yum update -y libselinux'

### ISSUE THREAD

**Issue by pjfanning** [docker/hub-feedback#724]
Works on my laptop but fails when run dockerhub automated build:
https://hub.docker.com/r/pjfanning/docker-hadoop-jdk8/builds/brbrefrhjvmkte6aagdcnsn/

Rpmdb checksum is invalid: dCDPT(pkg checksums): libselinux-utils.x86_64 0:2.0.94-7.el6 - u
Removing intermediate container e269fda26c88
The command '/bin/sh -c yum update -y libselinux' returned a non-zero code: 1

**Comment by RohitBarnwal** [comment]
How did you removed this error?

**Comment by pjfanning** [comment]
The issue is still there but I'm not using the image any more.
