### ISSUE TITLE
Centos7 :: Error unpacking rpm package httpd-2.4.6-40.el7.centos.1.x86_64

### ISSUE THREAD

**Issue by Profysseur** [docker/hub-feedback#725]
Hello everyone.

I have to build an Image Docker for the solution of my company.
This Image have to contains some dependencies and have to based on centos7. Among these dependencies, there is httpd.

So, I built an image of CentOS 7 with systemd with this Dockerfile according to these explainations : https://hub.docker.com/_/centos/

My centos7/Dockerfile
> `FROM centos:centos7`
> 
> `ENV container docker`
> 
> `RUN (cd /lib/systemd/system/sysinit.target.wants/; for i in *; \`
> `do [ $i == systemd-tmpfiles-setup.service ] || rm -f $i; done); \`
> `rm -f /lib/systemd/system/multi-user.target.wants/*;\`
> `rm -f /etc/systemd/system/*.wants/*;\`
> `rm -f /lib/systemd/system/local-fs.target.wants/*; \`
> `rm -f /lib/systemd/system/sockets.target.wants/*udev*; \`
> `rm -f /lib/systemd/system/sockets.target.wants/*initctl*; \`
> `rm -f /lib/systemd/system/basic.target.wants/*;\`
> `rm -f /lib/systemd/system/anaconda.target.wants/*;`
> 
> `RUN yum -y install deltarpm && yum clean all`
> `RUN yum -y update && yum clean all`
> `RUN yum -y install vim wget tar && yum clean all`
> 
> `VOLUME ["/sys/fs/cgroup"]`
> 
> `CMD ["/usr/sbin/init"]`

And I push this image on my repository "agilium/centos7" And I wrote an other Dockerfile for httpd according to the same explainations : My httpd/Dockerfile
> `FROM agilium/centos7`
> 
> `RUN yum -y update && yum clean all`
> `RUN yum -y install httpd; yum clean all; systemctl enable httpd.service`
> 
> `EXPOSE 80`
> 
> `CMD ["/usr/sbin/init"]`

And I have this error when I built my image :
![capture](https://cloud.githubusercontent.com/assets/10080065/16517077/e3b9a9e8-3f7b-11e6-8cdc-dbf98c96666f.PNG)

I also tried to localinstall the rpm package, but with the same error, like this :
> `COPY ./install/* ./install/`
> `RUN yum -y localinstall ./install/httpd-2.4.6-40.el7.centos.1.x86_64.rpm`

I search for solutions and I find this issue https://github.com/docker/hub-feedback/issues/461 but it seems there was no solution found and the problem has solved itself. =/

Thanks for help.

**Comment by Profysseur** [comment]
I found the problem and a solution ! The problem was I had my Docker Storage Driver configure with "aufs". I just had to change the "Storage Driver" to devicemapper. Apparently it's a problem on Ubuntu 15 and more and some Debian distributions.

**Comment by vanh23** [comment]
I'm having the same issue, and I'm new to linux. Could anyone help me?
![image](https://user-images.githubusercontent.com/50006158/56782859-8d90e600-681b-11e9-8aec-715d5326b04b.png)
