### ISSUE TITLE
Incorrect status returned when attempting to pull private image and not logged in

### ISSUE THREAD

**Issue by bradym** [docker/hub-feedback#728]
When a user is not logged in and they try to pull a private image they get the following error message:

```
Pulling postgres (exampleUser/privateRepo:latest)...
Pulling repository docker.io/exampleUser/privateRepo
Error: image exampleUser/privateRepo not found
```
This causes confusion and frustration because the image DOES actually exist. 

It would be much more clear if the message was along these lines:

```
Pulling postgres (exampleUser/privateRepo:latest)...
Pulling repository docker.io/exampleUser/privateRepo
Error: image exampleUser/privateRepo not authorized please login.
```

The same thing happens when trying to visit the URL of a private registry (ie: https://hub.docker.com/r/exampleUser/privateRepo) a 404 is returned instead of a 401 or 403 creating the same confusion.

Can these error messages be changed to be more accurate?

**Comment by marcusmartins** [comment]
@bradym That's by design. We return 404 when when your client fail authentication to avoid disclosing **any** information about private repositories.
