### ISSUE TITLE
Create multiple tags from a single build

### ISSUE THREAD

**Issue by theHilikus** [docker/hub-feedback#729]
It would be useful to be able to specify multiple tags associated to a build. For now, the workaround is to create two build configurations but this runs two jobs so it takes longer and it is wasteful. Something like a comma-separated list in the `Docker Tag Name` field would be simple enough.

The use case is having an image both be tags `1.0` and `latest` for example

**Comment by lukeorland** [comment]
Duplicate of #341, right?

**Comment by pkennedyr** [comment]
Closing as duplicate of [#341](https://github.com/docker/hub-feedback/issues/341)
