### ISSUE TITLE
integrate with GitHub PRs, show Docker Hub build status in PR (like Travis)

### ISSUE THREAD

**Issue by jokeyrhyme** [docker/hub-feedback#730]
When a GitHub project is integrated with Travis CI and other services, we can see little amber circles, green checks, or red crosses next to commits, etc depending on their build status. Further, Pull Requests in GitHub show the status of the build against each integrated service down by the Merge button.

Integration with Docker Hub causes commits to trigger a Docker Hub build, but there's no integration coming back in the other direction, but Docker Hub to tell GitHub whether the build was successful.

It would be terrific if we could use Docker Hub integration in this manner, because it would mean we would not have to run Docker build tests in other services (e.g. Travis).

- related: #41 #372 ??

**Comment by pchico83** [comment]
@jokeyrhyme Most of these features are supported in Docker Cloud, the evolution of the Docker Hub autobuild feature. In Docker Cloud you are able to:
- run tests for PRs
- github status are integrated
- cancel and retry for build actions
- slack integration
- ability to define build env variables
You can find more information here:
https://docs.docker.com/docker-cloud/builds/automated-build/
https://docs.docker.com/docker-cloud/builds/automated-testing/

**Comment by jokeyrhyme** [comment]
@pchico83 oh, thanks!

Oh, I just now noticed that I'm getting sent to Cloud instead of Hub now. I'll give this integration a try and see how I go. Cheers!

**Comment by jokeyrhyme** [comment]
I hope free (but slower) builds become available for open-source projects. Currently, it looks like builds are free for the Beta, but not necessarily so once Cloud goes gold?

**Comment by pkennedyr** [comment]
Correct, we will always ensure there is an option to run builds on Docker Cloud for free. :)
