### ISSUE TITLE
Trying to pull : layers from manifest don't match image configuration

### ISSUE THREAD

**Issue by caiges** [docker/hub-feedback#731]
I am attempting to pull an image from our private Docker Hub repository and am getting this output:

``` bash
$ docker pull our/private:image
latest: Pulling from our/private:image
03e1855d4f31: Already exists
a3ed95caeb02: Pull complete
d73da93964bd: Pull complete
de7e62aa874c: Pull complete
fd094327f24a: Pull complete
9e9f27c61394: Pull complete
f256bf343d9d: Pull complete
82d9f1d73e17: Pull complete
33f3943b8d9c: Pull complete
f3b0f0ec2ff3: Pull complete
6a2c00b55137: Pull complete
0d727dbe1d4a: Pull complete
40a4133a0508: Pull complete
layers from manifest don't match image configuration
```

We're running Docker `1.11.1` on the box that cannot pull this image but are able pull from one of our older Docker hosts which is running `1.6.2`. I realize there is a related issue open against the main docker repo, https://github.com/docker/distribution/issues/1439, regarding this very same issue but I wanted to track this here as well until the problem is properly diagnosed.

**Comment by marcusmartins** [comment]
@caiges Thanks for the report, we're investigating.

**Comment by maxpowa** [comment]
Running into this same problem with https://hub.docker.com/r/maxpowa/npomf/ . The same pull is working correctly on another server running `Docker version 1.9.1-cs2, build 4ade326`.

```
$ docker version
Alias tip: d version
Client:
 Version:      1.10.0
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   590d5108
 Built:        Thu Feb  4 18:25:18 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.0
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   590d5108
 Built:        Thu Feb  4 18:25:18 2016
 OS/Arch:      linux/amd64

$ dc pull
Pulling npomf (maxpowa/npomf:latest)...
latest: Pulling from maxpowa/npomf
674ded4e0a75: Already exists
a3ed95caeb02: Already exists
3fe37ed373c9: Already exists
ddf1745d8563: Already exists
b9ef83e0e547: Already exists
dd3aa96c04c5: Already exists
3daa46d253bf: Already exists
2a194524d7f1: Already exists
abb3e486ff65: Pull complete
cbcddc314f9d: Pull complete
5cc9c8a0fbbf: Pull complete
ERROR: layers from manifest don't match image configuration	
```

cc @RX14

**Comment by marcusmartins** [comment]
@maxpowa @caiges Can you reproduce the issue with Docker 1.10.3 or higher?

**Comment by caiges** [comment]
@marcusmartins I am on `1.11.1` and was unable to pull.

**Comment by maxpowa** [comment]
@marcusmartins I can confirm it's pulling correctly on on a different machine running `1.12.0-rc4`. Unfortunately I couldn't test the newer version on the machine experiencing the problem because it's partially a production server.

```
$ docker version
Client:
 Version:      1.12.0-rc4
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   e4a0dbc
 Built:        Wed Jul 13 03:28:51 2016
 OS/Arch:      darwin/amd64
 Experimental: true

Server:
 Version:      1.12.0-rc4
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   e4a0dbc
 Built:        Wed Jul 13 03:28:51 2016
 OS/Arch:      linux/amd64
 Experimental: true
```

**Comment by marcusmartins** [comment]
@caiges Can you contact support.docker.com and we can help you from there?

**Comment by Ducatel** [comment]
I have also the same problem.
```
> docker --version
Docker version 1.11.2, build b9f10c9
> lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.1 LTS
Release:        16.04
Codename:       xenial
```
 It exist any workaround ?

**Comment by xiemeilong** [comment]
I have the same issue. My image is pulled from private  registry. The version of docker is 1.12.1.

**Comment by hpejustin** [comment]
I met this problem today. My docker is : 
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.6.3
 Git commit:   9e83765
 Built:
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.6.3
 Git commit:   9e83765
 Built:
 OS/Arch:      linux/amd64
and os info : 
LSB Version:	n/a
Distributor ID:	SUSE LINUX
Description:	SUSE Linux Enterprise Server 12 SP1
Release:	12.1
Codename:	n/a
I am not sure what's wrong.

**Comment by anshbansal** [comment]
Trying to deploy on DC/OS does the same problem
