### ISSUE TITLE
Unauthorized: incorrect username or password (while building with Jenkins)

### ISSUE THREAD

**Issue by npetrovski** [docker/hub-feedback#732]
**Step 1 : FROM jboss/keycloak:2.0.0.Final**

**Get https://registry-1.docker.io/v2/jboss/keycloak/manifests/2.0.0.Final: unauthorized: incorrect username or password**

Any ideas?

**Comment by marcusmartins** [comment]
@npetrovski thanks for the report. We will investigate.

**Comment by marcusmartins** [comment]
@npetrovski We haven't experienced any authentication problem on our end that would explain your issue. If you're still experiencing issue, can you contact support.docker.com?

**Comment by npetrovski** [comment]
Thank you and yes - I still have that issue with Jenkins and Docker pull. I will contact the support.
