### ISSUE TITLE
outdated docker version on hub (1.11.1 instead of 1.11.2)

### ISSUE THREAD

**Issue by icewind1991** [docker/hub-feedback#733]
I'm running into https://github.com/docker/docker/issues/22304 when trying to build an image on hub.
This is supposed to be fixed with 1.11.2 but hub still run 1.11.1

**Comment by thasmo** [comment]
I'm also facing a sudden error when trying to install SteamCMD on the Docker Hub. This has worked before, some time ago. It's also working on Travis CI, which runs Docker 1.9 and on my local machine, which runs 1.11.2.

**Comment by thasmo** [comment]
Is there any chance this will be updated to 1.11.2 soon or will an update be postponed to 1.12?

**Comment by pkennedyr** [comment]
UPDATE: The Docker Hub automated build system has been updated to Docker version 1.11.2.

**Comment by thasmo** [comment]
Awesome, thanks a lot!
