### ISSUE TITLE
bug: can't create  build triggers in new ui

### ISSUE THREAD

**Issue by stefanfoulis** [docker/hub-feedback#737]
I created a new automated build. But it seems there is no way to add any build triggers:

![screen shot 2016-07-15 at 16 48 51](https://cloud.githubusercontent.com/assets/14330/16878443/dc729550-4aac-11e6-80ca-a0dc3a566ebb.jpg)

Previously there was a "+" next to every existing line. But now that I have no lines... I can't do anything.

OT: I always found the "+" on the line confusing and would have preferred it at the bottom of the form anyway.

**Comment by bcwalrus** [comment]
Thanks for the report. Looking into it.

**Comment by bcwalrus** [comment]
@stefanfoulis At a quick glance, I don't see anything wrong. I'm assuming that by "build triggers", you meant you can't create any build rules.

If this is a public repo, could you let me know the repo name? Or if it's a private repo, could you write to support@docker.com, and reference this GH issue? Thanks!

**Comment by stefanfoulis** [comment]
@bcwalrus it is a private repo. I'll send a message to support@docker.com.

**Comment by stefanfoulis** [comment]
I can't reproduce the bug anymore. You guys seem to have fixed it :-)
