### ISSUE TITLE
Unable to link Github account

### ISSUE THREAD

**Issue by nusnewob** [docker/hub-feedback#738]
I have my github account linked to docker hub more than 1 year ago. When I tried to create a new automated build, it prompts me to link to github account, I follow the instruction and get error message, 

"There was an error during the github account link. Please ensure, you do not have the same github account linked to another dockerhub account"

I've tried revoke OAuth application from my github and re-auth it, couldn't get it working.

**Comment by bcwalrus** [comment]
Are you `zmakki` on Docker Hub? You can go to your Hub user settings page -> Linked Accounts & Services, to unlike your GH account, in order to re-auth.

**Comment by petemcw** [comment]
I can verify the problem as well. For months now I've not been able to link my Docker Hub and Github accounts. I have unlinked and re-authed numerous times and each time I get the same error mentioned above.

**Comment by bcwalrus** [comment]
@petemcw Your problem might be different, since I don't see an existing link with the `petemcw` GH account. What is the Hub account you're trying to like to?

**Comment by nusnewob** [comment]
@bcwalrus It's not my docker hub username, I don't recognise the username and it shouldn't linked to my GitHub account. Would you be able to unlink? Thanks.

**Comment by petemcw** [comment]
@bcwalrus Both accounts are "petemcw".

**Comment by bcwalrus** [comment]
@nusnewob Ok. Please try again.

**Comment by bcwalrus** [comment]
@petemcw Your account status looks correct. I suspect browser caching issue. Could you try again in an incognito window, with the browser developer window open to keep an eye on any potential errors?

**Comment by nusnewob** [comment]
@bcwalrus Working. Thanks so much!

**Comment by petemcw** [comment]
@bcwalrus Using an Incognito tab did the trick!

**Comment by BeOleg** [comment]
I have the same issue. an incognito tab does not help
![image](https://user-images.githubusercontent.com/3058791/63330419-7763e400-c33c-11e9-83e4-c7aedc469be5.png)
