### ISSUE TITLE
Option to only build images when the Dockerfile changes

### ISSUE THREAD

**Issue by jasonmccallister** [docker/hub-feedback#740]
We currently have one repository that builds our base images for developers. Each image is defined by a Dockerfile in a separate directory. However, when we setup the build settings to use those directories (see the image attached) every push to master auto builds each of the images.

It would be great if the builds only monitored the changes in the repository, or better yet - if this behavior could be controlled through the Docker hub.

<img width="1297" alt="screenshot 2016-07-19 10 23 00" src="https://cloud.githubusercontent.com/assets/5354908/16953447/15718f46-4d9b-11e6-842a-d3d33d62f945.png">

**Comment by rafaelsoaresbr** [comment]
I have a similar setup, but I've disabled automated builds because the same reason and #500 
I had to create another repository on Hub that uses the first image as a base.
