### ISSUE TITLE
not able to create a repo from an organizations namespace

### ISSUE THREAD

**Issue by jkurz** [docker/hub-feedback#745]
I am part of the turner organization in dockerhub. I am trying to create a repo under that namespace. It is not showing up in the dropdown for me, thus not allowing me to create it.

Is there a workaround I can use? 
<img width="1544" alt="screen shot 2016-07-22 at 12 43 25 pm" src="https://cloud.githubusercontent.com/assets/10718991/17064317/0ccb557c-500a-11e6-9180-152a1a8d89c3.png">

**Comment by marcusmartins** [comment]
Currently only owners of an organization are able to create new repositories.

**Comment by jkurz** [comment]
ok, so is it possible for the owner to make me an owner? 

If not how can the owner give more than one person access to the organization?

**Comment by jkurz** [comment]
ok looks like I have been made an owner. Thanks for commenting on this so quickly.
