### ISSUE TITLE
Weird forum login behaviour

### ISSUE THREAD

**Issue by iainhouston** [docker/hub-feedback#746]
So I can log directly in to Docker Hub with my password just fine.

But I can't log into the Docker forum.

Here's what happens:
-  Forum login fails my usual Docker Hub user id & password
- I click on  "Forgot password?" and get logged into my Docker Hub account.    
   But this does not give me write access to Docker (For Mac) forum.

Browser: Safari 9.1.1 OS X 10.11.5

**Comment by bcwalrus** [comment]
Does your login work on Docker Cloud or Docker Hub? And does forum login work with private browsing mode?

**Comment by iainhouston** [comment]
I can log into https://hub.docker.com but when I go to https://forums.docker.com and click *Login* >>  *Login*  and the same user/password fails; so I click  *Forgotten password?* on fail page and am magically logged into https://hub.docker.com .... which is pretty weird I thought 😳  Anyway I can't log into the docker forums. 

Actually the fail page url is this: https://hub.docker.com/account/login/?next=/account/discourse_sso/%3Fsso%3Dbm9uY2U9ZjgxZjEwNWZhYzZkMWIxNTM0ZjE5ZTEzODUzYjY5NWImcmV0dXJu%250AX3Nzb191cmw9aHR0cCUzQSUyRiUyRmZvcnVtcy5kb2NrZXIuY29tJTJGc2Vz%250Ac2lvbiUyRnNzb19sb2dpbg%253D%253D%250A%26sig%3D7793c9a85f7502267f9a86efc03186e1951ff8.... (Truncated in case this is a secret)

**Comment by iainhouston** [comment]
FWIW I *can* log into Docker Forums as long as I use my email address (rather than my username) .... but otherwise still see weird behaviour

**Comment by thaJeztah** [comment]
@iainhouston just some random thought; does your login have uppercase letters? I think Docker Hub automatically lowercases usernames, perhaps forums.docker.com doesn't

**Comment by iainhouston** [comment]
@thaJeztah that could well be it! my username is `iainH`

**Comment by thaJeztah** [comment]
@iainhouston Docker Hub usernames are always lowercase, so possibly using lowercase on the forum works

**Comment by iainhouston** [comment]
Thanks @thaJeztah that works. I'll close this. Although it's a bit weird being forwarded from Forum "Forgotten password?" link to Docker Hub it's probably not worth bothering about.

**Comment by thaJeztah** [comment]
@iainhouston good to hear; not sure about the "forgotten password" redirect (I'm not part of the Docker Hub team), but there may be an existing issue for that here
