### ISSUE TITLE
Automated Build raises "Unknown instruction: HEALTHCHECK"

### ISSUE THREAD

**Issue by amancevice** [docker/hub-feedback#749]
I updated my Dockerfiles to use the HEALTHCHECK command but the automated builds do not succeed:

```
Removing intermediate container xxxx
Step 10 : HEALTHCHECK 
Unknown instruction: HEALTHCHECK
```

**Comment by marcusmartins** [comment]
@amancevice We're testing 1.12 support in our automated build infrastructure and we will update you when it's ready to be used.

**Comment by syepes** [comment]
+1 Would be a great addition!

**Comment by ndegory** [comment]
I just tried an automated build with a HEALTHCHECK in the Dockerfile, it works for me now.
I see "Version: 1.12.0" in the build log indicating Docker 1.12, but I don't know if it has been rolled out for everybody.

**Comment by marcusmartins** [comment]
We have upgraded our autobuild infrastructure to Docker 1.12.
