### ISSUE TITLE
Orgs with more than 25 teams do not display

### ISSUE THREAD

**Issue by rickalm** [docker/hub-feedback#757]
Our org has more than 25 teams defined and apparently it's a known UI bug that only 25 will show with no pagination.

I know internally we've been aware of it for 6+ months and were informed by an agent from hub.docker.com this was being dealt with but its aparently still an issue

What is the status and when will this be fixed ?

**Comment by akshayvyas** [comment]
@rickalm, apologies for the long delay in resolving this issue.  We are targeting a patch this week with an increase of the limit until we have pagination in place.  Thank you for your patience, I will update this ticket when it's ready for you.

**Comment by akshayvyas** [comment]
@rickalm can you confirm you can see all your teams now?

**Comment by rickalm** [comment]
@akshayvyas I had not seen your reply I was on vacation. We are still having the same problem not being able to see more than 25 groups

**Comment by mkobit** [comment]
It looks like the dropdown when creating a `repository` is broken too. It only shows a subset of unordered groups so we cannot select the group we want to give permissions to.
