### ISSUE TITLE
Dockerfile Location cannot support regex

### ISSUE THREAD

**Issue by twang2218** [docker/hub-feedback#759]
In my repo: https://github.com/twang2218/gitlab-ce-zh, I created subdirectory for each version branch, such as `./8.5`, `./8.6` and `./8.7`, which contains the `Dockerfile`, and use `tag` for each patch version update, so, there will be tags such as `v8.5.8`, `v8.6.7`, `v8.7.6`.

I expected the Dockerfile Location to support regex sourceref, so, I can use `/^v([0-9]+)\.([0-9]+)\.([0-9]+)$/` to parse the `tag`, and use `/{\1}.{\2}/` as the Dockerfile Location. However, it doesn't work that way, and raise error:

``` bash
Build path does not exist: ./{\1}.{\2}/
```

Could you fix or implement regex sourceref on the Dockerfile Location field? otherwise, I have no idea how to support `tag` in automated build.

**Comment by bcwalrus** [comment]
@twang2218 Got some background question about your use case. Since the Dockerfile is version controlled, why do you create a subdirectory for every version? Why not just have one `/Dockerfile`, and update that as you create new versions? That way, regardless of which branch you're on, `docker build .` would just work.

**Comment by twang2218** [comment]
My use case is something similar to Docker official image git repo, such as, <https://github.com/docker-library/mysql/tree/master>

I used to create multiple branches for each minor version, Docker Hub can handle that, however, I found it's not a trivial job to sync some common files across the branches, such as `README.md`. 

Every time I published a new version, I need to update the `README.md` file, which will be fetched to Docker Hub. Instead of just modify the master branch, I have to update the `README.md` for every branch, as in the `README.md`, I also have links to other branches `Dockerfile`. This kind of sync is not a pleasant job to do.

Then, I learnt from the official image Git repo, just have a single master branch, and put the `Dockerfile` of supported software versions to the sub-directories, so I can just maintain a single `README.md`. It solved my problem, perfectly, except the `tag`.

The software version number is a 3 parts schema, `<major>.<minor>.<patch>`. I created sub-dir for each supported `minor` version, `<major>.<minor>`. And I `tag` each patch versions release as `v<major>.<minor>.<patch>`. 

And then, the Docker Hub failed here. It can recognise the new `tag`, however, it cannot go to the `<major>.<minor>` sub-directory to find the right `Dockerfile`, if the regex sourceref is not supported.

So, please support using regex sourceref in Dockerfile Location field, otherwise, I have to manually push each tag by myself.

**Comment by cperrin88** [comment]
I have a similar usecase and a feature like this would be very useful to me as well.

**Comment by ruruiye** [comment]
same problem here.
