### ISSUE TITLE
Unable To Connect BitBucket Account

### ISSUE THREAD

**Issue by ElusiveMind** [docker/hub-feedback#760]
When click the option on the hub to connect my bitbucket account, all it does is refresh the page or white screen depending on the browser.  I have attached a link so you can see what happens.

http://screencast.com/t/NsA00Yryi

**Comment by bcwalrus** [comment]
@ElusiveMind I've seen it occasionally as well. As a workaround, could you try click on the "Bitbucket" link again in the refreshed page?

**Comment by ElusiveMind** [comment]
No. I did get it to work by connecting via Settings > Linked accounts, but trying from the Create Automated Build failed every time.
