### ISSUE TITLE
Can't reset password

### ISSUE THREAD

**Issue by npearson72** [docker/hub-feedback#762]
For some reason I can't seem to login today. I tried to reset my password, but the link redirects back to the home page:

https://hub.docker.com/account/password-reset-confirm/

Anyone else having this issue?

**Comment by bcwalrus** [comment]
@npearson72 Did you get the password reset email, and manage to reset your password?

**Comment by npearson72** [comment]
I did get the reset email, but clicking on the link redirected me to the
docker hub home page. Today however I tried using incognito and it worked.

**Comment by bcwalrus** [comment]
@npearson72 Thanks for the update. I usually run into that when I'm logged into Hub as another user. It's also possible that you have a stale cookie from a while back. Would recommend you clearing the browser cookies for *.docker.com.
