### ISSUE TITLE
Cannot leave organisation

### ISSUE THREAD

**Issue by victorgama** [docker/hub-feedback#763]
Currently, I'm part of an organisation in which I do not want to continue in. When clicking the remove button, the server responds with a 403 error. I'm not the organisation admin. Is this the expected behaviour?

**Comment by marcusmartins** [comment]
@victorgama it's not the expected behavior. Can you contact https://support.docker.com and we will help you from there?

**Comment by victorgama** [comment]
@marcusmartins Sure thing. Should I close this issue?

**Comment by marcusmartins** [comment]
Closing it now. Thanks @victorgama
