### ISSUE TITLE
Automated builds not triggering

### ISSUE THREAD

**Issue by F21** [docker/hub-feedback#767]
I have this image set to automatically build every time a new tag is pushed: https://hub.docker.com/r/boostport/hbase-phoenix-all-in-one/

I just pushed a new tag to the corresponding git repo on github: https://github.com/Boostport/hbase-phoenix-all-in-one/releases, but the automated build does not trigger.

I tried deleting the tag on the remote and repushing it, but still no go.

**Comment by F21** [comment]
It appears to be building now. Not sure what was causing the issue previously.

**Comment by bcwalrus** [comment]
@F21 Sorry you were having issues. Btw, make sure you don't push more than 3 tags at the same time. GH doesn't send out an event for that. https://developer.github.com/v3/activity/events/types/#createevent
