### ISSUE TITLE
"Machine user" fails as a deployment mechanism for private submodules

### ISSUE THREAD

**Issue by TeaSeaLancs** [docker/hub-feedback#769]
I'm attempting to do an automated build which uses private git submodules.

I've been following the guide at https://github.com/programmerq/docker/blob/master/docs/sources/docker-hub/builds.md but it just doesn't work. Every build fails with the error:

```
Building in Docker Cloud's infrastructure...
Starting to clone
Cloning into '.'...
Warning: Permanently added the RSA host key for IP address '***.**.***.***' to the list of known hosts.
Submodule 'common' (https://github.com/***/common) registered for path 'common'
Cloning into 'common'...
fatal: could not read Username for 'https://github.com': No such device or address
Clone of 'https://github.com/***/docker-common' into submodule path 'common' failed
please ensure the correct public key is added to the list of trusted keys for this repository and the remote branch exists. (1)
```

**Comment by pchico83** [comment]
Hi @TeaSeaLancs 
We are working on updating the docs, you can configure an autobuild with private submodules by doing:
- Create a github machine user.
- Create a pair of private/public ssh keys
- Upload the public SSH key to the github machine user account.
- Add and environment variable in your autobuild called `SSH_PRIVATE` whose value is the private ssh key.

**Comment by TeaSeaLancs** [comment]
Hi @pchico83 thanks for the update.

Just to clarify (Although i'm sure i'll find this out during configuring this), this environment variable should be put into the dockerfile as an ENV statement?

**Comment by pchico83** [comment]
@TeaSeaLancs You don't need it in the dockefile, you need to add it in the Docker Cloud UI, as part of your autobuild configuration.

**Comment by TeaSeaLancs** [comment]
And therein lies the issue: I was using Docker Hub autobuilds.

I've just switched to Docker Cloud so I will give that a shot and let you know.

**Comment by pchico83** [comment]
This could be interesting to you, talks about the future direction of Docker Cloud and Docker Hub:
https://forums.docker.com/t/future-updates-on-docker-hub-docker-cloud/20498

**Comment by TeaSeaLancs** [comment]
Thanks for that, it looks like good reading.

Having followed your instructions above, unfortunately the build still fails with the same error message. I have ensured that the public key is attached to the machine user, the machine user has read & write access to the private repo `common` (Plus the actual private repo that we're building!), and added the private key as `SSH_PRIVATE` under the autobuild environment settings, and it still doesn't work.

Is there anything I could be doing to help figure out what's going on?

**Comment by TeaSeaLancs** [comment]
This is a screenshot of how it's set up, this all seems correct?

![No worky](https://cloud.githubusercontent.com/assets/3225866/18129022/b4e473de-6f80-11e6-8d27-c93daba49151.jpg)

**Comment by TeaSeaLancs** [comment]
Also, does it matter if the machine user is the user that is linked to Github in Docker Cloud? (Mine currently is)

**Comment by pchico83** [comment]
@TeaSeaLancs No, it doesn't. But you will still need to add the `SSH_PRIVATE` env variable. This is because the same deploy key (which is what Docker Cloud use to clone repositories) can be only added to a single repo in github. The only way to clone several repositories using SSH is a user SSH key.

**Comment by TeaSeaLancs** [comment]
Ok. I did that, as shown in the screenshot above, and it still doesn't work, so i'm at a loss as to what to do :)

**Comment by pchico83** [comment]
@TeaSeaLancs From the errors, looks like your git private submodules are using `https` instead of ssh.

**Comment by TeaSeaLancs** [comment]
And that could explain a few things! Thanks for bearing with me on this, this could be a massive facepalm on my side here.

**Comment by pchico83** [comment]
I opened an internal issue to document all this. It is a recur-rely question how to set up private submodules, and we don't have it documented anywhere.

**Comment by TeaSeaLancs** [comment]
Yeah I think mentioning the SSH thing in setting up the submodules could be a good idea as well, practically everyone just says to use the `https://` format when adding submodules when you google about it.

I swapped the format to be `git@github.com:organisation/repo` in the submodules and now it's working great, thanks so much for the help.

**Comment by TeaSeaLancs** [comment]
One final question, is the `SSH_PRIVATE` mechanism exclusively for docker cloud, or is it possible to reuse this for manual builds?

**Comment by pchico83** [comment]
By "manual" do you mean for local builds? As long as you are using SSH keys to clone git repos in your local environment, it will work locally too.
In a nutshell, Docker Cloud uses `SSH_PRIVATE` to clone your git repo and from there, it executes a `docker build` command the same way it is executed locally.

**Comment by TeaSeaLancs** [comment]
Ah yes that makes sense.

I was thinking of a slightly different usecase: We also have git private submodules which are used as part of an `npm install` during the build process. I was wondering if there was any Docker best-practice regarding how to do that as well.

**Comment by pchico83** [comment]
You could use the instruction `ARG` in your dockerfile to pass the SSH keys, but this is not recommended since the SSH key will be kept in the layers of your image.
For these cases, I recommend a two-phase build. You can generate all the content (clone every git module) before executing `docker build` and use the `ADD` instruction to inject the content on your image without needing credentials or SSH keys as part of your build process.
In Docker Cloud, you can make use of hooks to accomplish these scenarios:
https://docs.docker.com/docker-cloud/builds/advanced/#/custom-build-phase-hooks

**Comment by TeaSeaLancs** [comment]
That's excellent advice, thanks so much!

**Comment by vhosakot** [comment]
I saw the same error when I triggered automated build for my private GitHub repo.

```
Building in Docker Cloud's infrastructure...
Cloning into '.'...
Warning: Permanently added the RSA host key for IP address '192.30.253.112' to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.

please ensure the correct public key is added to the list of trusted keys for this repository (128)
```

Adding the deploy Key in “Build Settings” in Docker Hub to my GitHub account at https://github.com/settings/keys resolved this issue for me and the automated build passed for my private GitHub repo.

**Comment by benjaminluo** [comment]
@kajisaap Did you ever figure out a solution? I'm experiencing the same kind of issue

**Comment by kajisaap** [comment]
Sorry, we never could figure out and Docker community couldn't also help.
