### ISSUE TITLE
Paying for 10 Private Repositories, but can only use 5

### ISSUE THREAD

**Issue by kalain** [docker/hub-feedback#770]
![image](https://cloud.githubusercontent.com/assets/19394215/17900170/2d1b63f4-692c-11e6-87d3-63c0ff88a1a3.png)

![image](https://cloud.githubusercontent.com/assets/19394215/17900224/6986ab5a-692c-11e6-85ce-9f1889f6600a.png)

**Comment by marcusmartins** [comment]
Hi @kalain, can you contact support.docker.com and we will help you from there?

**Comment by kalain** [comment]
# Closing:

Issue was so if you have one user that was added to the team but he forgot to confirm after 2 days the whole account gets blocked.

**Comment by bcwalrus** [comment]
Actually, such users can still use the "can't login" -> "reset password" functionality to get a new confirmation email.

@kalain IIUC, you ran into a bug where there's an unconfirmed user in the owners team of the org, which has been fixed. Sorry about that.
