### ISSUE TITLE
Basic question on container stack

### ISSUE THREAD

**Issue by matt3224** [docker/hub-feedback#771]
Hi,

Sorry if this is a basic question im new to docker. I would like to know how to go about recreating my server environment, which is as follows:

- CentOS 7
- PHP 7
- MariaDB 10
- PHPMyAdmin
- WHM/cPanel

Im not sure if i get these all separate and install them or if i need a specific premade setup.

Any help or hand holding would be much appreciated!

Thanks,

**Comment by bcwalrus** [comment]
@matt3224 This is intended for Docker Hub feedback. Could you post general usage questions on https://forums.docker.com? Thanks!
