### ISSUE TITLE
Are my docker pushes being rate-limited? 

### ISSUE THREAD

**Issue by jslusher** [docker/hub-feedback#776]
Lately I have not been able to very easily push docker images to our private repo. I don't get an error, it just seems to hang indefinitely and eventually, if the image is small enough (< 10MB), it will complete. Uploading to other sources seems to work fine.

**Comment by jslusher** [comment]
Restarting my docker daemon seems to have at least temporarily improved push performance.

**Comment by fideloper** [comment]
Restarting Docker on Mac seems to help for me as well, wonder if it's related to the virtualization on the Mac client?

**Comment by mghazizadeh** [comment]
Thanks for the feedback. The Docker for Mac team is aware of this issue and working to address it.
