### ISSUE TITLE
Unable to reset password?

### ISSUE THREAD

**Issue by zacharykane** [docker/hub-feedback#778]
I recently tried to recover my account on Docker Hub but I can't get the reset to send me an email. I tried to re-signup but it tells me my address is already in use with an existing account. Please advise?

**Comment by bcwalrus** [comment]
@zacharykane Sorry about that. Could you email support@docker.com with your username, and mention me? We'll help you fix it.

**Comment by zacharykane** [comment]
Sent!

**Comment by bcwalrus** [comment]
Looks like it's resolved. Let us know if you run into problems again.

**Comment by panickervinod** [comment]
I am having exactly the same problem what is the work around?
