### ISSUE TITLE
dockerhub not building

### ISSUE THREAD

**Issue by gear2000** [docker/hub-feedback#779]
anybody experiencing dockerhub not building?  i hit the trigger button and it's been 3 hours and it's still just queued.

**Comment by pkennedyr** [comment]
We are experiencing heavy usage of the autobuild service and are scaling up the service. For the latest updates, please refer to: http://status.docker.com

We apologize for the inconvenience.

**Comment by gear2000** [comment]
no worries.  i just wasn't sure if it was just my repo :)  thanks for the prompt response!

**Comment by pkennedyr** [comment]
The automated build service is operational as of Tues (8/30) 11:45pm (PT): http://status.docker.com

**Comment by mghazizadeh** [comment]
This is an update the root cause and the follow up actions we are taking as a result. Apologies for the service disruption and degradation. https://forums.docker.com/t/post-mortem-for-automated-build-service-disruption-on-aug-30th/21442
