### ISSUE TITLE
parallel builds not being honored?

### ISSUE THREAD

**Issue by johnnagro** [docker/hub-feedback#780]
hello. i pay for the 10 parallel build plan, but i only ever see 1 concurrent build. what gives?

**Comment by bcwalrus** [comment]
Hi @johnnagro. The parallelism is across all of the repos owned by you. It seems that the most recent builds on the following repos happened concurrently:

- https://hub.docker.com/r/johnnagro/atom/
- https://hub.docker.com/r/johnnagro/thunderbird/
- https://hub.docker.com/r/johnnagro/letsencrypt/
- https://hub.docker.com/r/johnnagro/scudcloud/
- ... (There seems to be a few more, but I didn't confirm those.)

Is that what you're expecting?

**Comment by johnnagro** [comment]
well, at the time only one was building and the rest were marked queued, however i went back to try and reproduce it and wasn't able to. looks like it is working.

thanks for reviewing my case!
