### ISSUE TITLE
Unable to delete an organization

### ISSUE THREAD

**Issue by geektortoise** [docker/hub-feedback#782]
I know I can send an email to the team but it will be more efficient to have a button "Delete Organization" when we are the last user in this organization.

I am currently stuck because I want to convert my user into an organization but this user is the only one into another organization ("User must first leave all organizations and groups.").

Operating system : Ubuntu 14.04 (64-bit)
Browser and Browser version : Chromium Version 51.0.2704.79
URL for the page in question.:
https://hub.docker.com/organizations
https://hub.docker.com/account/convert-to-org/

The rough date and time the error occurred (be sure to include your time zone) : Now. 7 September 2016 11h30
Your hub username : cytomine

**Comment by EarthmanWeb** [comment]
I have this same problem 

- cannot convert user to organization ("User must first leave all organizations and groups.")
- as org. creator and sole user, I still cannot leave or delete organization

Please advise

**Comment by johnbusbice** [comment]
same issue

**Comment by Cryptophobia** [comment]
The year is 2017 and this has been an issue since 2015. Over 2 years.

**Comment by egenov** [comment]
The year is 2018... and issue open yet (

**Comment by Cryptophobia** [comment]
@egenov : I had to send email to Docker Hub support and they converted my user to an organization.

**Comment by pmontrasio** [comment]
Please, let the owners delete organizations. I have the same problem of EarthmanWeb one year and half ago: I created an organization before realizing that I should convert the account into an organization, to keep the repository and the paid plan.
