### ISSUE TITLE
New account: resend confirmation failing

### ISSUE THREAD

**Issue by CeeBeeUK** [docker/hub-feedback#785]
I attempted to sign up to docker hub, but no verification email was received.
Two paths I have tried:-
## First

I tried using the [reset-password page](https://hub.docker.com/reset-password/)
## Second

Then, in an attempt to get help I went to the [help page](https://hub.docker.com/help/)
If I click on paid support it knows the name I entered and displays a Resend confirmation link
<img width="981" alt="screen shot 2016-09-13 at 08 57 20" src="https://cloud.githubusercontent.com/assets/7482902/18465731/28a3a718-7990-11e6-80af-14a5e916610b.png">
If I click on the link it displays the following
<img width="421" alt="screen shot 2016-09-13 at 08 58 09" src="https://cloud.githubusercontent.com/assets/7482902/18465745/3d15dfa4-7990-11e6-8ff7-d857823c3199.png">
For searching purposes the text displayed is `This server does not respond to non-GET requests`
# 

Any ideas on how I can unlock/verify my account?

**Comment by vdzundza** [comment]
I've the same issue. Looks like email server does not work

**Comment by andergmartins** [comment]
I have the same issue. Please, could you double check what is happening?

**Comment by pkennedyr** [comment]
Thanks for the feedback. Please contact Docker support for assistance with account registration issues and they will be able to help: https://success.docker.com/Account_Support

Also, make sure to check your spam folder to ensure the verification email has not been marked as spam by your email provider.
