### ISSUE TITLE
Too many failed login attempts for username or IP address

### ISSUE THREAD

**Issue by hpohl** [docker/hub-feedback#786]
I cannot log into docker hub for over 3 days now:

```
$ docker login
....
Error response from daemon: Get https://registry-1.docker.io/v2/: toomanyrequests: too many failed login attempts for username or IP address
```

```
$ docker push ...
....
unauthorized: incorrect username or password
```

Logging in via the web interface works.

As far as I can remember, I never failed a login. Password reset didn't change anything. The only thing I'm automating are the pulls, which are still working.

**Comment by marcusmartins** [comment]
@hpohl Can you contact support@docker.com and we can help you from there?

**Comment by hpohl** [comment]
Sorry for not updating, 3-4 hours after the password reset the issue got solved (maybe) by itself. I did a clean reinstall as well. I was using docker on a Raspberry Pi, I cannot confirm if the issue occured on my desktop. Everything is working now, but the error message is still incorrect. Do you still want me to contact support? I will reopen when the issue comes back with more precise information.

**Comment by FortisFortuna** [comment]
We fixed this by removing the $ characters in our password.

**Comment by cyclic-reference** [comment]
@FortisFortuna Thanks that fixed my issue as well.

**Comment by PTC-JoshuaMatthews** [comment]
Apparently it doesn't like the @ symbol either

**Comment by artpar** [comment]
```!``` is in the blacklist as well

**Comment by C-Fu** [comment]
I just did a password reset, and now my (temporary) password is just numbers and small caps. still no go

**Comment by Afrokk** [comment]
Here's how I resolved this issue without changing the password:

- Removed the Docker config: `rm -rf ~/.docker/config.json`
- Logged out from multiple Docker registry servers:
  - `docker logout [registry-1.docker.io](http://registry-1.docker.io/)`
  - `docker logout [hub.docker.com](http://hub.docker.com/)`
  - `docker logout [index.docker.io](http://index.docker.io/)`
-  Then I was able to log in again normally using:
    - `docker login`
