### ISSUE TITLE
Ability to convert repository to automated build

### ISSUE THREAD

**Issue by mikehaertl** [docker/hub-feedback#794]
It would be great if you could convert a repository to an automated build. I don't want to delete the repository and start from scratch, because I'd like to preserve my stars (favourites) and d/l counter.

**Comment by poum** [comment]
+1

**Comment by mikehaertl** [comment]
@pkennedyr Quting you from #341 :

> Support for specifying multiple tags from a single build is now available in Docker Cloud. We encourage you to try out Docker Cloud as this is where you will find support for specifying multiple tags per build and many other auto-build features.

I've now tried out Docker Cloud and found an option to add automated builds even for existing "standard" repos. But to be honest I have some problems to understand the relation between Docker Cloud and Docker Hub. It seems that Docker Cloud duplicates some (all?) features of Docker Hub - and adds some more on top. So on the long run will Docker Cloud completely replace Docker Hub at some point?

And if we create automated builds on Docker Cloud, will this change also appear on Docker Hub? If so, it would be a solution for this issue here.

**Comment by pkennedyr** [comment]
@mikehaertl Thanks for the feedback. We are in the process of updating Docker Cloud so that all existing Docker Hub automated builds are synchronized and seamlessly available in Docker Cloud.

You are correct, Docker Cloud builds on the features of Docker Hub to provide a fully-managed hosted Docker registry, Continuous Integration (CI) and Continuous Deployment (CD) services, as well as infrastructure deployment and container management services to help teams build, ship, and run Docker applications in the cloud.

We'll be posting an update in the coming weeks about the upcoming plans for both Docker Cloud and Docker Hub. Stay tuned!

**Comment by toblerpwn** [comment]
@pkennedyr - Can you provide a link to this article when it's available? Thanks!

**Comment by sanscontext** [comment]
Hey @toblerpwn there's an existing post here: https://forums.docker.com/t/future-updates-on-docker-hub-docker-cloud/20498/3

But generally you can follow the forums topic: forums.docker.com/c/docker-cloud

**Comment by vhosakot** [comment]
**Huge** +1

**Comment by awesomescot** [comment]
This is still not available in docker hub.  +1

**Comment by new-guy** [comment]
It would be extremely useful if this was an option in docker hub.  I don't want to have to delete repos and recreate them as automated builds if at all avoidable

**Comment by DaveVoyles** [comment]
+1

**Comment by smgogarten** [comment]
+1

**Comment by Gargam** [comment]
+1

**Comment by MicahZoltu** [comment]
Unfortunately Docker Cloud has been end-of-lifed, which means the previous workaround of using Docker Cloud no longer applies.  Are there plans to revisit this issue?

**Comment by gkorland** [comment]
Are there any plans to add this support?

**Comment by jeffheaton** [comment]
+1

**Comment by luthramanisha** [comment]
+1

**Comment by coady** [comment]
> Have you tried changing the URL segment from /repository/docker/{org}/{project}/hubbuilds to /repository/docker/{org}/{project}/**builds** ? Seems like I was able to convert one this way.

It's official: https://blog.docker.com/2018/12/the-new-docker-hub/.

**Comment by amcsi** [comment]
@coady that's great, but none of the new Automated Builds stuff is visible from the UI in projects that have been using the Classic automated builds.
