### ISSUE TITLE
Splunk loggind driver

### ISSUE THREAD

**Issue by venkatavelpuri** [docker/hub-feedback#797]
i am trying the splunk loggind driver , i got https event collector enabled on splunk . i am receiving the below error. Thanks 

Command issued : 

sudo docker run --publish 80:80 --log-driver=splunk --log-opt splunk-token=XXXXXXXXXXXXXXXXXXXXXX  --log-opt splunk-url=https://http-inputs-venkat.splunkcloud.com/services/collector/event:8088/services/collector/event  --log-opt splunk-insecureskipverify=true nginx

---

docker: Error response from daemon: Failed to initialize logging driver: splunk: expected format schema://dns_name_or_ip:port for splunk-url.

**Comment by hridyeshpant** [comment]
@venkatavelpuri did you get it resolved.
I am also having same issue, We are using splunk collector configured with URL "https://splunk-ec.test.xyz.com:8088/services/collector/event" and i am able to send log using curl command but getting below same error when i used docker run with same url.

but when try without  "/services/collector/event" in URL path using command, command is working but no logs in spluks.

docker run --publish 80:80 --log-driver=splunk --log-opt splunk-token=XXXXXXX  --log-opt splunk-url=https://splunk-ec.test.xyz.com:8088 --log-opt splunk-insecureskipverify=true nginx

does splunk driver automatically add "/services/collector/event" when sending the request?

**Comment by swaroopkundeti** [comment]
+1

**Comment by alcidessd37** [comment]
+1
