### ISSUE TITLE
Automated build fails when COPY from lib/

### ISSUE THREAD

**Issue by kkurian** [docker/hub-feedback#799]
In automated builds, when COPY is invoked in the Dockerfile, source directories named `lib` appear to receive erroneous treatment.

Given this Dockerfile:

```
FROM python:2.7
... irrelevant steps removed ...
COPY bin/start.sh /usr/local/frostbite/bin/start.sh
COPY lib/gateway.py /usr/local/frostbite/lib/gateway.py
```

located relative to the repository root at `ansible/roles/gateway/files/Dockerfile`; and

Given the source `bin` and `lib` directories located at `ansible/roles/gateway/files/bin` and `ansible/roles/gateway/files/lib`.

The build copies the files from `bin` as expected but fails to copy files from `lib`:

```
...
Step 8 : COPY bin/start.sh /usr/local/frostbite/bin/start.sh
 ---> 6ecbc832b155
Removing intermediate container cac91d3fe8cc
Step 9 : COPY lib/gateway.py /usr/local/frostbite/lib/gateway.py
lstat lib/gateway.py: no such file or directory
```

Renaming the source `lib` directory to `lib_` and then updating the Dockerfile to reflect the change works around this issue.

```
$ cd ansible/roles/gateway/files
$ mv lib lib_
```

Updated line in Dockerfile:

`COPY lib_/gateway.py /usr/local/frostbite/lib/gateway.py`

Results in a successful build.

```
...
Step 8 : COPY bin/start.sh /usr/local/frostbite/bin/start.sh
 ---> c81e8e538c3d
Removing intermediate container 56380c062c3d
Step 9 : COPY lib_/gateway.py /usr/local/frostbite/lib/gateway.py
 ---> 9ef8c256f296
Removing intermediate container d309c252f147
```

**Comment by domibarton** [comment]
Hi

I think I've the same issue. See #811 

Cheers
Domi

**Comment by dwhitz** [comment]
I'm facing the same issue, and [you can fix it as described here](https://forums.docker.com/t/docker-build-failing-on-docker-hub/76191)

> The solution is to set the build context appropriately so that the relative path in the Dockerfile COPY is correct. In your Docker Hub repository go to “Builds” and click on “Configure Automated Builds”. There you can set the “Build Context” for each build rule.
