### ISSUE TITLE
Dockerfile view needs highlighting

### ISSUE THREAD

**Issue by smougenot** [docker/hub-feedback#80]
It would be nice to display the content of the docker file with highligting.
(it was the case in the former version of the hub)

Now
![new](https://cloud.githubusercontent.com/assets/1217669/8201429/3e3670f8-14d1-11e5-8002-9c35f5c56d8c.png)

Before
![old](https://cloud.githubusercontent.com/assets/1217669/8201432/40590bd4-14d1-11e5-9a6f-2b514d8754b4.png)

**Comment by jakirkham** [comment]
Looks like this has sort of happened, but it still highlight some things incorrectly.
