### ISSUE TITLE
Unable to update a credit card

### ISSUE THREAD

**Issue by petrjanda** [docker/hub-feedback#805]
Hi,

I know this might not be the best place to put this but:
1. we are not able to update our credit card
2. I am not able to access the email support (This server does not respond to non-GET requests)

this is ultimately blocking some streams of our development. Attaching error message on credit card update (that field doesn't seem to be in the form, and error i get accessing email support).

Any idea would be appreciated!

Error on card update:
<img width="607" alt="screen shot 2016-09-28 at 16 00 58" src="https://cloud.githubusercontent.com/assets/419414/18919088/d0bfb13e-8594-11e6-9b6a-422c30b6ded3.png">

Then i try to open support:
<img width="537" alt="screen shot 2016-09-28 at 15 52 18" src="https://cloud.githubusercontent.com/assets/419414/18919089/d0d25ac8-8594-11e6-80ad-bf7437bc0e1f.png">

Clicking verify yields:
<img width="746" alt="screen shot 2016-09-28 at 15 52 24" src="https://cloud.githubusercontent.com/assets/419414/18919091/d0e11d10-8594-11e6-8897-ef4c5fd4ebae.png">

**Comment by akshayvyas** [comment]
@petrjanda , did you click the "Get more..." link to get to the Billing page?  Can you try using the menu in the upper right connected to your Hub User name.  Click on Settings in the menu, then click on Billing & Plans and try to update your Billing Info.  Does that work?

**Comment by petrjanda** [comment]
No it doesn't help. Also tried different journey to go through "Upgrade Plan". It works on my private account but if i try company one, i get this:

![screen shot 2016-09-29 at 11 49 27](https://cloud.githubusercontent.com/assets/419414/18951074/02aec684-863b-11e6-8c96-41e43abca736.png)

**Comment by petrjanda** [comment]
Just to be sure ... i can't contact support anywhere else but here given there is another bug in a way :(

**Comment by alfred-landrum** [comment]
Hi @petrjanda - I've sent an email to the address we have on file with a couple of questions & description of a temporary workaround. Would you please reply to that email so that we can note your email address is verified, please?
