### ISSUE TITLE
changing settings for docker/ucp-swarm

### ISSUE THREAD

**Issue by danielsand** [docker/hub-feedback#809]
Hey,

im searching for a way to change the settings for the ucp-swarm container.

seems like under some conditions on pulling new images we get:

---
## ERROR: No elected primary cluster manager

and then the docker-compose tasks aborts.

based on this GH Issue:

https://github.com/docker/swarm/issues/2157

i want to tweak the swarm setting --replication-ttl "4s" for swarm.

seems like we run into a time out if the system is under more stress.

is there any way to change this permanent ?

**Comment by funkydorian** [comment]
Seems still not fixed, sometimes it happens, at my second trial it was ok:

Deryas-MacBook-Pro:voting-app-docker dsezen$ docker-compose up -d
Pulling redis (redis:latest)...
ucpclus0-ucpnode: Pulling redis:latest... : downloaded
ucpclus0-ucpdtrnode: Pulling redis:latest... : downloaded
ucpclus1-ucpctrl: Pulling redis:latest... : downloaded
ucpclus2-ucpctrl: Pulling redis:latest... : downloaded
ucpclus0-ucpctrl: Pulling redis:latest... : downloaded
ucpclus1-ucpnode: Pulling redis:latest... : downloaded
ucpclus2-ucpdtrnode: Pulling redis:latest... : downloaded
ucpclus1-ucpdtrnode: Pulling redis:latest... : downloaded
Pulling worker (dockercond2/dockercon-worker:latest)...
ucpclus2-ucpctrl: Pulling dockercond2/dockercon-worker:latest... : downloaded
ucpclus1-ucpdtrnode: Pulling dockercond2/dockercon-worker:latest... : downloaded
ucpclus1-ucpnode: Pulling dockercond2/dockercon-worker:latest... : downloaded
ucpclus2-ucpdtrnode: Pulling dockercond2/dockercon-worker:latest... : downloaded
ucpclus0-ucpdtrnode: Pulling dockercond2/dockercon-worker:latest... : downloaded
ucpclus0-ucpnode: Pulling dockercond2/dockercon-worker:latest... : downloaded
ucpclus1-ucpctrl: Pulling dockercond2/dockercon-worker:latest... : downloaded
ucpclus0-ucpctrl: Pulling dockercond2/dockercon-worker:latest... : downloaded
ERROR: No elected primary cluster manager

**Comment by danielsand** [comment]
@funkydorian seems like a timeout issue with UCP <-> swarm. 
I couldnt pin it down - most of the time a second run fixed the issue - sometimes a third. In the end i ended up creating a wrapper around the docker-compose run which checks the exit code and if its not right will re-run the compose command. Ugly but works
