### ISSUE TITLE
Github push does not trigger automated build - why?

### ISSUE THREAD

**Issue by hholst80** [docker/hub-feedback#813]
I have pushed to master on my public github.com repository but there is no build triggered. 

![image](https://cloud.githubusercontent.com/assets/6200749/19032211/bfd11170-8958-11e6-98db-fa915ccbebc4.png)

![image](https://cloud.githubusercontent.com/assets/6200749/19032231/d757f656-8958-11e6-933a-13ff3c992231.png)

**Comment by hholst80** [comment]
Triggering it manually seems to work just fine.

**Comment by hholst80** [comment]
I think the problem was that the Docker Hub integration was not activated on the Github account. Maybe it should be more clear that you have to do this manually and just allowing Docker Hub to read the repo does not activate automatic rebuilds?

![image](https://cloud.githubusercontent.com/assets/6200749/19213736/eba266c2-8d73-11e6-86bb-88ff9058090f.png)

**Comment by lukemcgregor** [comment]
I think the problem is that you only linked your account to public repos. This doesn't give dockerhub enough permissions to add webhooks to repos.

It says this on the link screen (which to be fair I totally didn't read either)

![image](https://user-images.githubusercontent.com/1284608/31572807-8f12d282-b10a-11e7-8d97-400ee3c44fb3.png)

**Comment by vmarkovtsev** [comment]
In my case it was Public and Private access yet still the hook was not triggered. @hholst80 solution worked, thanks a lot!

**Comment by danielquinn** [comment]
Surely, there must be a way to enter these hooks manually rather than give Docker the right to write to all of my private repos?

**Comment by danielquinn** [comment]
I've managed to work around this *without* having to give Docker Hub write access to my other repos:

1. Link my Github account with read-only access
2. Go to my Github repo > settings > Integrations & services
3. Select "add service"
4. Choose `Docker` from the list

That was it :-)

**Comment by vmarkovtsev** [comment]
@danielquinn Yeah, this is exactly what @hholst80 proposed in https://github.com/docker/hub-feedback/issues/813#issuecomment-252427342

**Comment by timc13** [comment]
Yes, please make this clearer on Dockerhub.  You need to add the Docker integration service for automated builds to work.

**Comment by tgpfeiffer** [comment]
Also, while it says "GitHub Services are being deprecated" when adding the service integration, using a webhook instead does not seem to work when tags are used, only for "latest".

**Comment by glensc** [comment]
> https://github.com/example/project/settings/installations
> 
> Note: [GitHub Services are being deprecated](https://developer.github.com/changes/2018-04-25-github-services-deprecation/). Please contact your integrator for more information on how to migrate or replace a service with [webhooks](https://developer.github.com/webhooks/) or [GitHub Apps](https://developer.github.com/apps/differences-between-apps/#about-github-apps/).
> 

By [Deprecation timeline](https://developer.github.com/changes/2018-04-25-github-services-deprecation/#deprecation-timeline) It's impossible to setup automated builds for new projects:
- May 31, 2018: Submit your intentions for migrating or replacing your GitHub Service.
- October 1, 2018: GitHub discontinues allowing users to install services. GitHub Services will be removed from the GitHub.com UI.
- January 31, 2019: GitHub stops delivering installed services' events on GitHub.com.

**Comment by glensc** [comment]
What is more confusing is that there are two systems, which seem to do same thing, use same docker registry but their settings are not shared

- https://hub.docker.com/r/glen/gitlab-registry-cleanup-hook/builds/
- https://cloud.docker.com/repository/docker/glen/gitlab-registry-cleanup-hook/builds

i've setup both, and pushing does not trigger build in neither

**Comment by timc13** [comment]
what's the plan when github services become deprecated?
