### ISSUE TITLE
dockerhub down?

### ISSUE THREAD

**Issue by nojo** [docker/hub-feedback#815]
I received the following while trying to push to docker hub: "received unexpected HTTP status: 500 Server Error".

I'm also unable to pull an image from AWS ECS.

(edit: adding details)  This is occurring at Oct 3, 2016, 4:12 PM Mountain Daylight Time (22:12 UTC).

**Comment by pkennedyr** [comment]
Docker Hub is currently experiencing a service disruption (operations such as docker login, push, pull are not functioning correctly). 

The team is actively addressing the issue. For the latest updates, please see: status.docker.com

**Comment by nojo** [comment]
Thanks.  FWIW, a link to status.docker.com on the "help" page would be useful.

**Comment by pkennedyr** [comment]
@nojo Thanks for the feedback!
