### ISSUE TITLE
Cannot convert user to organization with that user as owner.

### ISSUE THREAD

**Issue by derekssmith** [docker/hub-feedback#818]
I want to convert my Hub account to an organization account because that is more accurate.  However when I try to complete the form I get the error 'Cannot convert user to organization with that user as owner.'

Not sure what to do?

**Comment by risinglf** [comment]
+1

**Comment by derekssmith** [comment]
I think the issue I am having is that I named my current Docker Hub account with my organizations name.  Now I want that name to be assigned to my organization instead of me.

**Comment by Heedster** [comment]
+1

**Comment by bluesockets** [comment]
+1

**Comment by supersnager** [comment]
+1

**Comment by fabdouglas** [comment]
Explanation there : 
https://success.docker.com/api/articles/How_do_I_convert_my_Docker_Hub-Cloud_user_account_into_an_organization_account/pdf

> This error refers to the second prerequisite explained above. You would have to enter the Docker ID of an existing user to assign it as the owner of the organization. This Docker ID can not be the same as the account you are trying to convert.

**Comment by eztalks** [comment]
> s docker ID will not be visible for doc

Yes. I did the same as you said. But it still said, "Transform requires an owner." I think that's so stupid. the note is very clear. I choose the owener as another users account, didn't work. Tried many times.

**Comment by vkarinen** [comment]
Hello, this is a user interface issue/bug - i was fighting with this as well, until i found this advice:
https://stackoverflow.com/questions/26117356/transforming-a-github-user-into-an-organization
where it says you have to click the "Choose" button on the far right BEFORE proceeding. It could be there is a bug as the button below is active, even the user is not fully chosen to the new organisation.

**Comment by future-mastermind** [comment]
+1
