### ISSUE TITLE
Docker hub fails with: "lchown /var/lib/docker/overlay/.... : no such file or directory" - local and CI doesn't report errors

### ISSUE THREAD

**Issue by madskonradsen** [docker/hub-feedback#822]
Docker-hub fails with

```
Step 4 : COPY dockerfiles /
Removing intermediate container eb2aea603206
lchown /var/lib/docker/overlay/9ff7b3de8df5ac1dab6a3d53c5d6dbc0dd2fdeb4d9e5273d10869c6e4d7942d5/merged/config: no such file or directory
```

This error is in no way present on neither local-machine or CircleCI when building things there

**Comment by madskonradsen** [comment]
Looks like an issue that starting to appear a few weeks ago: https://www.google.com/search?q=%22Build+failed%3A+lchown+%2Fvar%2Flib%2Fdocker%2Foverlay%2F%22

**Comment by madskonradsen** [comment]
Closing this! I think the issue comes from having an empty .gitkeep file in on of it's sub-folders.

**Comment by frekele** [comment]
same issue that: #811
