### ISSUE TITLE
Cannot delete empty repository

### ISSUE THREAD

**Issue by hholst80** [docker/hub-feedback#823]
Problem: Cannot delete empty repository. 

Workaround: Upload something, then delete.

**Comment by hholst80** [comment]
See also #819

**Comment by pkennedyr** [comment]
Closing as this is a dup of #819. 

Note: the team is able to repro and is working on a fix.

**Comment by pkennedyr** [comment]
@hholst80 A fix for this issue has been deployed and repositories can now be deleted.

**Comment by hholst80** [comment]
```
There was an error. The repository was not deleted.
```

Is this the same error or something else @pkennedyr ?
