### ISSUE TITLE
No way to delete pearlmilktea/emailsender2

### ISSUE THREAD

**Issue by pearlmilktea** [docker/hub-feedback#824]
When i try to delete,
it prompt the message :
"There was an error. The repository was not deleted."

**Comment by pkennedyr** [comment]
@pearlmilktea Thanks for the feedback - the team is able to reproduce the error and is working on a fix.

Closing this issue as it is a dup of #819.

**Comment by pkennedyr** [comment]
@pearlmilktea A fix for this issue has been deployed and repositories can now be deleted.
