### ISSUE TITLE
Unable to delete repositories

### ISSUE THREAD

**Issue by turbopape** [docker/hub-feedback#825]
Hey,

I am unable to delete any repository.

After I confirm the name of the repository, I get the following error:
"There was an error. The repository was not deleted."

Thanks for your assistance,

Cheers !

**Comment by pkennedyr** [comment]
@turbopape Thanks for the feedback - the team is able to reproduce the error and is working on a fix.

Closing this issue as it is a dup of #819.

**Comment by pkennedyr** [comment]
@turbopape A fix for this issue has been deployed and repositories can now be deleted.

**Comment by turbopape** [comment]
Yes indeed I was able to delete the repositories,
Thank you!

**Comment by hholst80** [comment]
I think there is still an issue with deleting empty *private* repositories @pkennedyr

**Comment by asheshambasta** [comment]
I'm stuck with repositories that are overrunning our plan limit and I cannot delete them and I cannot push to them (even though I'm now under the limit for my plan).

**Comment by chriscapetown** [comment]
Having this issue still - getting "There was an error. The repository was not deleted."

Compressed size of tag is 0B, supports @hholst80's comment above.

**Comment by pkennedyr** [comment]
Please open a ticket with support and they will be able to investigate your issue: support.docker.com

**Comment by lindsaymacvean** [comment]
was this resolved?
