### ISSUE TITLE
docker pull with proxy authentication not working

### ISSUE THREAD

**Issue by mkessler1** [docker/hub-feedback#826]
Hi, I am really stuck on this one... I have an Ubuntu 16.04 VM running inside VMware WS on Win10. I have docker setup to use a corporate proxy to connect to the docker hub. 

/etc/systemd/system/docker.service.d/http-proxy.conf :
[Service]
Environment="HTTP_PROXY=http://XXX:YYY@proxy.net:8080/"
Environment="HTTPS_PROXY=http://XXX:YYY@proxy.net:8080/"

and also

/etc/default/docker :
export http_proxy="http://XXX:YYY@proxy.net:8080/"
export https_proxy="http://XXX:YYY@proxy.net:8080/"

"docker info" gives me

Http Proxy: http://XXX:YYY@proxy.net:8080/
Https Proxy: http://XXX:YYY@proxy.net:8080/

I can open https://index.docker.io/v1/repositories/library/hello-world/images in a web browser and can see the JSON.
But "docker pull hello-world" gives me:
Using default tag: latest
Pulling repository docker.io/library/hello-world
Error while pulling image: Get https://index.docker.io/v1/repositories/library/hello-world/images: Proxy Authentication Required

So obviously docker respects that there is a proxy but does not recognize the user:password syntax. How can I go on from here?

Thanks,
Martin

**Comment by CastleW** [comment]
Hi.  I'm having the same problem.  Did you get anywhere with solving this?

**Comment by iMarv** [comment]
From my recent experiences: Make sure that your username and password are typed in correctly. If one does not match, you will always get the "Authentication required" error.

@mkessler1 @CastleW

**Comment by sanjar** [comment]
Any solutions to it??? I am also getting same issue..

**Comment by souravpatnaik** [comment]
**Solution :**

[root@xx ~]# docker pull hello-world
Using default tag: latest
Pulling repository docker.io/library/hello-world
**Error while pulling image: Get https://index.docker.io/v1/repositories/library/hello-world/images: authenticationrequired**


earlier i have set docker proxy in file   /etc/systemd/system/docker.service.d/https-proxy.conf
#[Service]
#Environment="HTTPS_PROXY=http://xxx:8080/"

then i commented this, and sys-reloaded
#sudo systemctl daemon-reload
#sudo systemctl restart docker

then i tried to pull hello-world and i got it.

sometime docker works with proxy also without proxy :(

**Comment by mirandarfsm** [comment]
It's work for me.

I referenced a file in _systemd_
/etc/systemd/system/docker.service.d/http-proxy.conf :
[Service]
EnvironmentFile=/etc/default/docker

and also I put password encode ASCII letter

/etc/default/docker :
http_proxy="http://myusername:MyAw3s0m3p%5E%24%24.%21@proxy.example.com:80/"

**References**: 
https://mikemylonakis.com/unix/docker-proxy/
https://www.url-encode-decode.com/
