### ISSUE TITLE
BROKEN: Automated Builds not working - error on "COPY entrypoint.sh /"

### ISSUE THREAD

**Issue by HariSekhon** [docker/hub-feedback#828]
This is quite a serious breakage which is preventing many different automated builds, see also ticket #821.

**Comment by hholst80** [comment]
I'm still seeing this on our production images from time to time.

```
Step 5 : ADD entrypoint.sh /
Removing intermediate container 26ac4f2f0c81
stat /var/lib/docker/overlay/eee02a6408b9b78ffef442379b085b572e526c701f9d28ee39ea96fa99339447/merged/entrypoint.sh: no such file or directory
```

**Comment by hitokiri82** [comment]
+ 1 We are having this issue as well. Our builds randomly fail with this error sometimes.

**Comment by HariSekhon** [comment]
Comment to keep open.
