### ISSUE TITLE
Intermittent build failure on docker hub

### ISSUE THREAD

**Issue by ecsousa** [docker/hub-feedback#830]
Hello,

I have create this [github repository](https://github.com/ecsousa/docker-dotnet) with some docker build definitions.

I've set up `ecsousa/dotnet:make` image to build from `/make` on my repository.

Sometimes it fails, with a message like this:

    Build failed: stat /var/lib/docker/overlay/1e7dd04758333107c33ee1d4887a9d56c47019e244dbc9bbf3af81cb069d40f1/merged/build.sh: no such file or directory`

But then I trigger build again, without touching build definition, and then it succeeded.

**Comment by hholst80** [comment]
Probably a duplicate of #821

**Comment by pkennedyr** [comment]
@ecsousa Indeed, the issue you are experiencing appears similar to #821 and we will be posting updates via that thread as soon as further information / the fix is available. Apologies for the inconvenience.

**Comment by ecsousa** [comment]
Ok, thanks! I will be following up #821 and close this issue.
