### ISSUE TITLE
Cannot login to docker hub from command line

### ISSUE THREAD

**Issue by natke** [docker/hub-feedback#831]
I can log into docker hub through a browser with no issues

I changed my password 3 days ago

I have tried restarting (and deleting and recreating) the default machine

O/S: Mac OS X 10.11.4

Docker: Docker version 1.11.1, build 5604cbe

```
docker login
Login with your Docker ID to push and pull images from Docker Hub. If you don't have a Docker ID, head over to https://hub.docker.com to create one.
Username: nkershaw@impinj.com
Password: 
Error response from daemon: Get https://registry-1.docker.io/v2/: unauthorized: incorrect username or password
```

I tried upgrading to docker version 1.12 and still have the same issue.

I have replicated this issue on ubuntu 4.4.0-45-generic #66-Ubuntu

I have tried changing my password on docker hub again.

I can copy other credentials into my ~/.docker/config.json file and pull down images from docker hub without any issues.

Would really appreciate some help on this issue

**Comment by natke** [comment]
Is this project monitored at all? Is there a better place to lodge issues?

I fixed the original problem by specifying http://hub.docker.com as an argument to the login command. But when I try and pull images (that I can see on docker hub) I get the following error message:

```
Pulling repository docker.io/<<image name>>
ERROR: Error: image <<image name>> not found
```

i.e. it's looking at docker.io instead of hub.docker.com

Is this a config option that I can set?

**Comment by flimzy** [comment]
Don't use your email address to log in--just your docker ID.

**Comment by natke** [comment]
Brilliant, thanks - I was sure I tried that, but it is working now.

**Comment by JasonLunn** [comment]
Why does it work sometimes with the email? Why doesn't it consistently fail?

**Comment by RobinsChens** [comment]
Don't use your email address to log in--just your docker ID

**Comment by RobinsChens** [comment]
if you forget you docker id ,just login from hub.docker.com ,then you should find your docker id

**Comment by ryanaslett** [comment]
Additional thing to note. If you sign up with a dockerid that has mixed case like "UserName" the cli login is expecting it all in lowercase as in "username".

**Comment by natke** [comment]
Good to know, thanks

**Comment by charliwest** [comment]
Thanks for this @flimzy, this feels badly done though, on macOS with the app running it is automatically filling in the email address in the cli. Glad I found this post though, working now.

**Comment by josejayesh** [comment]
Good to know . Thanks @flimzy

**Comment by manmedia** [comment]
The solution worked for me when I logged in using "Username" not email address. It's not straightforward since it prints the email address on the screen, which gives an impression "My Email is My Username".

**Comment by venky1575** [comment]
hi when i was trying to login from command prompt ,it is asking username and password,i enterd correctly,but it will not going to login in command prompt ,it is show something like this" **Error response from daemon: Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)**
"

please help me out, i am trying to resolve this since 3 hours,but it won't

**Comment by Raven0us** [comment]
@venky1575 and whoever might be looking for a solution to **Timeout**.

If you are behind a firewall or VPN, see https://github.com/docker/kitematic/wiki/Common-Proxy-Issues-&-Fixes
If you are already logged in @ **Docker for Windows**, sign out and retry logging in via CLI.

**Comment by liapretorius** [comment]
Suddenly, I can no longer log into DockerHub via CLI, which is essential for what I'm doing.  
I can log into UI just fine with email address and password, but when using my dockerID/username with  password I get Error saving credentials: error storing credentials - err: exit status 1, out: `The user name or passphrase you entered is not correct.`
Strange because I'd been logged in all day with the same credentials and working fine and then all of the sudden I wasn't logged in and I can't log in.
Any ideas?
I'm NOT using my email address to login via CLI, so it's not that.
Thanks

**Comment by alencar** [comment]
I am getting the same error message from my docker

Environment
...
Server Version: 18.06.1-ce
…
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 468a545b9edcd5932818eb9de8e72413e616e86e
runc version: 69663f0bd4b60df09991c08812a60108003fa340
init version: fec3683
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.15.0-36-generic
Operating System: Ubuntu 18.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 4.732GiB
…
Registry: https://index.docker.io/v1/
…
Insecure Registries:
 127.0.0.0/8
...

**Comment by alencar** [comment]
A workaround for this problem is to manually create the ~/.docker/config.json file with the content below.  If docker pull from an authenticated repository don't work, you now will be able to enter your login credentials.

{
        "auths": {
                "https://index.docker.io/v1/": {
                        "auth": "base64 encoded user:pass string"
                }
        },
        "HttpHeaders": {
                "User-Agent": "Docker-Client/18.09.0 (linux)"
        }
}

**Comment by awadheshkk** [comment]
I am using Windows7 and I am trying to connect docker hub  using my docker id and password, but getting error 

**error during connect: Post http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.30/auth: open //./pipe/docker_engine: The system cannot find the file specified. I
n the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon
is not running.**

while earlier iwas able to connect docker hub,
could anybody tell me why sudden it stopped login while using ducker hub ui or from ui local docker I am able to login using same credential.

**Comment by amirajoodani** [comment]
hi everyone
if you get error with command : docker login -username YOURNAME you can try docker login --username 
it works for me 
thanks
