### ISSUE TITLE
DockerHub search is broken

### ISSUE THREAD

**Issue by Brett55** [docker/hub-feedback#832]
When searching for a repo by name here: https://hub.docker.com/u/<'your_org'>/dashboard/

It returns zero results, when the search terms are the exact repo name or partial name. I brought this up before and was told it was fixed

I also want to add, from here  https://hub.docker.com/u/<'your_org'>/dashboard/
It says "showing 100 of 100 repos" when our org has 250 repos.

**Comment by mjnovice** [comment]
Any updates on this ?
