### ISSUE TITLE
Unable to open repository collaborators page

### ISSUE THREAD

**Issue by moshebs** [docker/hub-feedback#833]
When editing a repository settings and choosing the collaborators tab, the view does not change and there is no access to the collaborators settings.

**Comment by ysle** [comment]
yep, gives 502 there.

**Comment by Roconda** [comment]
Same here but I'm getting a 400 with the following response

```
{"detail": "Org repositories do not have collaborators. Use the `groups` url."}
```

**Comment by mandrean** [comment]
Came here to create an issue for this. Glad(?) to see I'm not the only one. Maybe this will be prioritized then!

**Comment by miro-ur** [comment]
I'm having the same issue - was able to access the tab fine last night  - broken as of this morning.

**Comment by emeacham** [comment]
Same issue here--collaborators tab is not loading.

**Comment by rcschettino** [comment]
There is same error on my docker hub organization account.

**Comment by rcschettino** [comment]
As a temporary solution, I got all headers of GET /collaborators using Chrome DevTools (network tab) and  replicate using endpoint /groups.

```
GET https://hub.docker.com/v2/repositories/<username-or-organization>/<image-name>/groups/
Headers: Copy from Chrome Network
```

If you need to add some permission, you can GET groups of another repository and do POST in `https://hub.docker.com/v2/repositories/<username-or-organization>/<image-name>/groups/`

Example:
```
POST https://hub.docker.com/v2/repositories/<username-or-organization>/<image-name>/groups/

{
  "group_name": "developers",
  "permission": "read",
  "group_id": 11111111
}
```

**Comment by Dexyon** [comment]
@rcschettino Thanks! Will try that tomorrow! I noticed the same issue today with all our organisation dockers as well.

**Comment by olegdulin-la** [comment]
@rcschettino thanks for the workaround, but has anyone from Docker Hub responded to this yet ? It's preventing work from proceeding.

I'll give them till eod to respond and will try workaround in the AM, but we have a ton of people using docker hub and this is kinda silly.

**Comment by pkennedyr** [comment]
Thanks for the feedback. We are aware of the issue and currently working on a fix. We'll update this thread as more information is available.

**Comment by nikhilo** [comment]
@rcschettino I'm trying your workaround, but I get an error when I POST a new group to that URL
```
{
  "detail": "Authentication credentials were not provided."
}
```
Since I was able to GET the results using the same headers, I think I did provide authentication credentials. Any help would be appreciated!

**Comment by nikhilo** [comment]
@rcschettino nvm, I was missing the Authorization header in my POST request. It works now. Thanks!

**Comment by rcschettino** [comment]
You need copy all headers, including cookies.

Get Outlook for Android<https://aka.ms/ghei36>



On Tue, Oct 18, 2016 at 7:35 PM -0200, "Nikhil Owalekar" <notifications@github.com<mailto:notifications@github.com>> wrote:


@rcschettino<https://github.com/rcschettino> I'm trying your workaround, but I get an error when I POST a new group to that URL

{
  "detail": "Authentication credentials were not provided."
}


Since I was able to GET the results using the same headers, I think I did provide authentication credentials. Any help would be appreciated!

-

**Comment by brorbw** [comment]
Same issue. Just FYI

**Comment by APorsgaard** [comment]
Any solution to remove collaborators?

**Comment by Supernomad** [comment]
this just bit me as well, any progress on fixing this? As I am now basically completely blocked, because my boss wants to know why the only thing we are using the docker hub for (managing who can access what) is broken.

**Comment by tsmgodoi** [comment]
We're trying to put an user as owner of an organization as a workaround to this problem until it is solved.

**Comment by joelesalas** [comment]
@pkennedyr Any update? This is causing a number of issues.

**Comment by olegdulin-la** [comment]
My manager is pushing me to migrate off of docker hub to AWS container registry; I told him let's give them till EOD and if it is still a problem tomorrow we will start moving our images. I am sorry, @pkennedyr  but like others have said, the ONE thing Dockerhub is useful for is managing who can access what and it is broken.

**Comment by victorgama** [comment]
In order to avoid just posting "I'm facing the same problem" and clobbering the discussion, I just hit the _Subscribe_ button and voted with 👍 on some comments, but just like @olegdulin-la, things are getting critical where I work as well.

I wonder if @pkennedyr could at least give us an ETA.

**Comment by pkennedyr** [comment]
UPDATE: A fix for this issue has now been deployed to prod, which restores access to the collaborators settings. Again, we apologize for the inconvenience and please let us know if you experience any further issues.
