### ISSUE TITLE
Can't change collaborators of repository

### ISSUE THREAD

**Issue by am813nt** [docker/hub-feedback#835]
'Collaborators' tab doesn't show up. 400 Bad Request in response: "{"detail": "Org repositories do not have collaborators. Use the `groups` url."}"

**Comment by moshebs** [comment]
It's a duplicate of https://github.com/docker/hub-feedback/issues/833

**Comment by pkennedyr** [comment]
@am813nt A fix for this issue has now been deployed to prod, which restores access to collaborators settings. We apologize for the inconvenience and please let us know if you experience any further issues.
