### ISSUE TITLE
Unable to access Collaborators Tab

### ISSUE THREAD

**Issue by ashishgupta1989** [docker/hub-feedback#837]
Hi,

There is some error while accessing Collaborators tab in http://hub.docker.com.

**Comment by pkennedyr** [comment]
@ashishgupta1989 Thanks for the feedback. We are aware of the issue and currently working on a fix. We'll update #833 as more information is available.

**Comment by pkennedyr** [comment]
A fix for this issue has now been deployed to prod, which restores access to collaborators settings. We apologize for the inconvenience and please let us know if you experience any further issues.
