### ISSUE TITLE
dockerhub collaborator feature not working

### ISSUE THREAD

**Issue by a-mueller** [docker/hub-feedback#838]
unable to modify collaborators. getting a 400 in the console when clicking on that feature on dockerhub.

payed plan / private repo.

**Comment by fortune-juggle** [comment]
unable to modify collaborators, too. We have a XX-large plan and get a bad gateway 500

**Comment by pkennedyr** [comment]
Thanks for the feedback. We are aware of the issue and currently working on a fix. We'll update #833 as more information is available.

**Comment by pkennedyr** [comment]
@a-mueller A fix for this issue has now been deployed to prod, which restores access to collaborators settings. We apologize for the inconvenience and please let us know if you experience any further issues.
