### ISSUE TITLE
Without changes a new rebuild show: no such file or directory

### ISSUE THREAD

**Issue by moylop260** [docker/hub-feedback#844]
Using the following Dockerfile: https://github.com/Vauxoo/docker-odoo-image/tree/master/odoo-shippable

I have configured a automated build: 
 - Type: Branch
 - Name: master
 - Dockerfile Location: odoo-shippable
 - Docker Tag Name: latest

The last build was fine from 19 days ago!
I don't have changes but now I force run a `trigger` to rebuild and now I see the [following error](https://hub.docker.com/r/vauxoo/odoo-80-image-shippable-auto/builds/bwvkhinvd2panv34tl8e6ti/
) in docker hub:

```bash
Building in Docker Cloud's infrastructure...
Starting to clone
Cloning into '.'...
Cloning done
Getting README
Getting Dockerfile
KernelVersion: 4.4.0-38-generic
Os: linux
BuildTime: 2016-10-11T18:29:41.366230153+00:00
ApiVersion: 1.24
Version: 1.12.2
GitCommit: bb80604
Arch: amd64
GoVersion: go1.6.3
Starting build of index.docker.io/vauxoo/odoo-80-image-shippable-auto:latest...
Step 1 : FROM vauxoo/odoo-80-image
 ---> 57b49dd09a43
Step 2 : MAINTAINER Tulio Ruiz <tulio@vauxoo.com>
 ---> Running in 9e2a44f73673
 ---> 742546cfc826
Removing intermediate container 9e2a44f73673
Step 3 : ENV RUN_COMMAND_MQT_10_ENTRYPOINT_IMAGE "/entrypoint_image" INSTANCE_ALIVE "1" PSQL_VERSION "9.3" REPO_REQUIREMENTS "/.repo_requirements" WITHOUT_DEPENDENCIES "1" OCA_RUNBOT "1" REPO_CACHED "/.repo_requirements"
 ---> Running in b25d25ec3ecf
 ---> d69c06316891
Removing intermediate container b25d25ec3ecf
Step 4 : COPY scripts/entrypoint_image /
Removing intermediate container a1c0987b6368
stat /var/lib/docker/overlay/eecc0dc599132752cfe8fb3f969881057df2e719fcbc7328585c5515249d0909/merged/entrypoint_image: no such
```

Locally works fine with:
```bash
git clone git@github.com:Vauxoo/docker-odoo-image.git -b master dkr
cd dkr/odoo-shippable
docker build -t test .
# finish fine!
```

**Comment by j3k0** [comment]
Same issue on my repositories (all of those I tested so far, all are linked to GitHub)

**Comment by maran** [comment]
Having the same issue, is there any known work-around expect a manual push?

**Comment by pkennedyr** [comment]
The issue you are experiencing is similar to #811, which we are treating as a top priority across Docker and are actively working to address a fix. 

We will be posting updates via that thread as soon as further information / the fix is available. Apologies for the inconvenience.
