### ISSUE TITLE
Trying to convert account to organization fails with "User must first leave all organizations and groups."

### ISSUE THREAD

**Issue by telmich** [docker/hub-feedback#845]
Even though user is in no organization or group

**Comment by megastef** [comment]
+1 - is there any solution for this error? I used a fresh account, for sure it is not in any group or organization.

**Comment by Lansatac** [comment]
For me, this was due to the account I was trying to convert belonging to another organization.

**Comment by nrupendesai** [comment]
+1 I am having same issue

**Comment by lozanet2005** [comment]
So no fix for this error after almost 4 years?

**Comment by idrissneumann** [comment]
Yeah, and there is more than one issue that is opened about it: https://github.com/docker/hub-feedback/issues/1208

**Comment by cgoIT** [comment]
It's really stupid. It can't be that complex to offer a solution for it.

**Comment by SureshVarad** [comment]
Still not fixed.. oh Docker
