### ISSUE TITLE
Github push is not trigger automatic builds

### ISSUE THREAD

**Issue by kuruoujou** [docker/hub-feedback#848]
Yup, another one of these. Except, I have checked that all of my settings seem to be correct, unless I'm missing something. This is a new project, and I haven't yet tried triggering a manual build, but I plan to do that after making this issue.

The problem seems to be with the integration on the github side, as github claims the service has never been triggered.

Here are some relevant screen shots:
![screenshot from 2016-10-24 14-59-05](https://cloud.githubusercontent.com/assets/749389/19659565/7a20cf82-99fa-11e6-95db-552fb339fa41.png)
Notice that the icon next to "Docker" is still grey - if you hover it, it says the hook has never been triggered.

![screenshot from 2016-10-24 15-00-49](https://cloud.githubusercontent.com/assets/749389/19659629/acde0246-99fa-11e6-976c-6dc2f4de4f8a.png)
The hook is enabled on the github side, though...

![screenshot from 2016-10-24 15-01-37](https://cloud.githubusercontent.com/assets/749389/19659648/c9757b00-99fa-11e6-9c14-0f799a68fc54.png)
As expected though, it doesn't seem to have ever been triggered here. And it's also enabled on the docker side, though if it's never been triggered on the github side, that might not matter.

Looking at it, it looks like I can't add a push trigger, which might be the problem. I also can't trigger a manual build.

**Comment by kuruoujou** [comment]
I deleted and recreated the docker hub repository, and renamed it "alux" instead of "a.lux". That seems to have fixed the problem, and seeing one that actually works makes me think the "no push triggers to show" box should probably have a "+" in it somewhere, that's probably the only bug.

I'll leave this open in case you want to track this here, but if not feel free to close.

Thank you.

**Comment by MetalArend** [comment]
This bug is still present, and there seems to be no easy workaround.

**Comment by dwickern** [comment]
The "+" and "Trigger" buttons didn't appear for me on the "Build Settings" page. Deleting and re-creating the repository seemed to fix it.
