### ISSUE TITLE
Docker (+AWS) very slow compared to localhost

### ISSUE THREAD

**Issue by ghost** [docker/hub-feedback#851]
# **Hello everyone,**

I'm working on a NodeJS app that is connected to a external database (Couchdb).
Some features of this app allow users to automatically Push code on Github repository (or heroku).When I'm running my app in **localhost**, this PUSH action takes approximately **1 minute**, but when I run on local **docker**, it takes **~3 minutes**... (extremely slow, 3x)

I read others post saying that **docker network is slow**. That can be the issue, because this NodeJS app request external DB and external services. I also tried to deploy my docker on **AWS EC2 servers**, I chose a **micro.T2** instance, and this PUSH action takes more than **5 minutes**, that's extremely long.

I don't know If i missconfigured something, or just doing something wrong.  

**DOCKERFILE**
`FROM debian:jessie`

RUN apt-get update \
&& apt-get -y install sudo \
&& apt-get -y install apt-utils  \
&& apt-get -y install curl \
&& curl -sL https://deb.nodesource.com/setup_5.x | bash -

RUN apt-get -y install nodejs \
&& apt-get -y install wget \
&& sudo wget -O- https://toolbelt.heroku.com/install-ubuntu.sh | sh \
&& apt-get -y install git \
&& mkdir -p /usr/src/app \

WORKDIR /usr/src/app
COPY . /usr/src/app
RUN cat /usr/src/app/.heroku_cred | heroku login
RUN npm install
ENV NODE_ENV=production
RUN nodejs /usr/src/app/server/config/environment.js initialize

CMD [ "nodejs", "/usr/src/app/bin/www" ]`  

**COMMANDS I DID:**
`docker build -t joliejuke:app .`
`docker run -d -p 80:80 --name app joliejuke:app`

**AWS EC2 CONFIG:**
instance: micro.t2
region: eu-west-1 (Irelan)
(I'm from France)

Thx

**Comment by joliejuke** [comment]
**AWS HOST**
`Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 9
Server Version: 1.12.2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 7
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host null bridge overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.2.0-42-generic
Operating System: Ubuntu 15.10
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 991.1 MiB
Name: takofront
ID: SFN2:WOGJ:6VQC:M26U:J26F:VFVD:JCFH:3K3E:75WP:2QMN:7RR2:XNEW
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Labels:
 provider=amazonec2
Insecure Registries:
 127.0.0.0/8`

**LOCAL DOCKER**
`Containers: 4
 Running: 1
 Paused: 0
 Stopped: 3
Images: 48
Server Version: 1.12.1
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 58
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host null bridge overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.17-boot2docker
Operating System: Boot2Docker 1.12.1 (TCL 7.2); HEAD : ef7d0b4 - Thu Aug 18 21:18:06 UTC 2016
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 995.9 MiB
Name: default
ID: JEE6:2HVM:YXTJ:QTXB:CXMC:EDJJ:2BRE:DSET:3QRF:UGWN:K56G:BC46
Docker Root Dir: /mnt/sda1/var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 18
 Goroutines: 30
 System Time: 2016-10-27T10:48:57.676892185Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
Insecure Registries:
 127.0.0.0/8`

**Comment by manuks** [comment]
Anybody got any clue on this?

**Comment by bigonha** [comment]
Having the same issue here. Has anyone got any clue on this?
