### ISSUE TITLE
Docker Cloud, cannot pull from public quay.io repo

### ISSUE THREAD

**Issue by lpgeiger** [docker/hub-feedback#853]
Docker Cloud, cannot pull from public quay.io repo, even when username and password  have been registered on docker cloud.

Building a public images from quay.io, fails with: unauthorized:
authentication required.

However I have my quay.io credentials configured on docker-cloud, AND
this is a public image. Please advise how to correct this.

Error code:

```
web-1: Pre-pulling image ImageTag:quay.io/keyscores/wire:latest in
9ccf2ee3-b3cf-453e-9cbc-ab46a8c047c9.node.dockerapp.io
ERROR: web-1: Get https://quay.io/v2/keyscores/wire/manifests/latest:
unauthorized: authentication required
ERROR: Service Redeploy action on 'web' (using
'quay.io/keyscores/wire:latest') has failed

```

**Comment by pchico83** [comment]
@keyscores could you open a ticket in docker cloud support?

**Comment by keyscores** [comment]
@pchico83 I've sent multiple request to support@docker.com over the last week, and no response, or acknowledgement. Can you please check?
