### ISSUE TITLE
Markdown link to anchor

### ISSUE THREAD

**Issue by ivan-pinatti** [docker/hub-feedback#857]
Hi,

I've declared an anchor in my README.md like this:

`## [1 - SonarQube Plugins](#plugins)`

Then I'm trying to reference to it in various ways, but none of them worked.

`<a name="plugins"> Plugins</a>`

`<a name="#plugins"> Plugins</a>`

`<a id="#plugins"> Plugins</a>`

`<a id="plugins"> Plugins</a>`

Testing in Markdown Preview in Atom all of them work.

Is there a problem on Docker Hub parser?

Thank you,

Ivan Pinatti

**Comment by wbuczak** [comment]
Eh.. long time, but did you find solution for that ? I'm struggling with it right now :)

**Comment by ivan-pinatti** [comment]
Not that I remember @wbuczak. :/

**Comment by ivan-pinatti** [comment]
Bumping the issue so it won't close as it wasn't solved.
