### ISSUE TITLE
Unable to delete tag - error Deletion Failed

### ISSUE THREAD

**Issue by MichaelSimons** [docker/hub-feedback#865]
**Repo Steps**

1. Navigate to a Docker Hub repository you own.
2. Navigate to the `Tags` tab
3. Press the trash can icon for one of the tags you would like to delete
4. Select `Confirm` when prompted

**Expected Results**
The tag would be deleted

**Actual Results**
`Deletion Failed` red text appears at the trash can icon location.

**Environment**
Google Chrome Version 54.0.2840.71 m (64-bit)
I also tried a version of IE and Edge with the same results.

**Comment by tyranron** [comment]
Facing same issue.
Really annoying.

**Comment by perrysk-msft** [comment]
Same issue here - Any update on this issue?

**Comment by pkennedyr** [comment]
Thanks for the feedback. Please reach out to support.docker.com and they will be able to investigate any specific issues with your account.

**Comment by MichaelSimons** [comment]
FWIW, I have only been seeing this issue with organizational repos.

**Comment by pkennedyr** [comment]
After further investigation, this appears to be a bug in Hub which the team is actively working on a fix for and is targeting for release by EOW.

**Comment by pkennedyr** [comment]
UPDATE: A fix for this issue has been deployed.
