### ISSUE TITLE
token based pushed

### ISSUE THREAD

**Issue by miton18** [docker/hub-feedback#868]
I'm looking for a way to push a built image to dockerHub, without MY credentials.

Actually, I make and test my project on Travis. This first step is OK.
next, I want to build the docker on succeed tests (also on Travis), Travis as the possibility to do that.

But if I want to push my image to dockerHub, I have to log in do docker hub using

```
after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push USER/REPO;
    fi
```

So if I don't want to give my username, email and password to Travis, I can't push images.

Is it an easy thing to implement tokens generators on dockerHub repos. By this way, I could generate a token on dockerHub, in a specific repo and give it to Travis.

I want this for security, I don't want to give my credentials to Travis and if I lose my token or give it to someone, I can revoke it.

Do you think it's possible and easy to implement ?

**Comment by flx42** [comment]
+1, I want to do something similar, with a GitLab CI pipeline pushing to DockerHub after build.

**Comment by julien-lecomte** [comment]
I'm looking for a similar solution where I wouldn't need to set a DOCKER_PASSWORD in an insecure variable.

I'm guessing by the age of this issue that this isn't on any roadmap or priority list.

**Comment by meticulous-dft** [comment]
It is on our roadmap, we are actively look into this for H1 this year.

**Comment by julien-lecomte** [comment]
@github-actions It's on their roadmap, they're looking actively into it since H1 2019.
