### ISSUE TITLE
Read-only access to organization repos

### ISSUE THREAD

**Issue by bobrik** [docker/hub-feedback#873]
Currently there are two modes of github integration:

<img width="731" alt="screen shot 2016-11-22 at 17 04 44" src="https://cloud.githubusercontent.com/assets/89186/20548163/f8c196e0-b0d5-11e6-80bd-f9bb9b59fa83.png">

I'd like to have an option to only allow access to public repos for orgs. Currently I can only have it for my own orgs. It looks like it's a matter of using `read:org` scope.

**Comment by afeld** [comment]
Duplicate of #552.
