### ISSUE TITLE
Automatic build: 1 push triggers 3 builds

### ISSUE THREAD

**Issue by anphung** [docker/hub-feedback#877]
Each time I push to bitbucket, docker hub triggers 3 builds.
Shouldn't it be 1 build, or am I missing something?

[https://hub.docker.com/r/henho/docker-erlang/builds](https://hub.docker.com/r/henho/docker-erlang/builds)

**Comment by bjornuppeke** [comment]
I'm getting the same behavior. @anphung, did you find out why?

**Comment by anphung** [comment]
Nope, maybe some internal issue.

**Comment by snebjorn** [comment]
I'm getting the same
