### ISSUE TITLE
Will dockerhub automatic build support split-image?

### ISSUE THREAD

**Issue by abcfy2** [docker/hub-feedback#891]
From this tip: https://www.fpcomplete.com/blog/2015/12/docker-split-images

To build minimized docker image, I need two Dockerfiles such as `Dockerfile.compile`, `Dockerfile.runtime`. Copy the compiled files from `Dockerfile.compile` image to `Dockerfile.runtime`. But Dockerhub automatic build seems not support this case.

**Comment by pchico83** [comment]
This can be accomplished using hooks:
https://docs.docker.com/docker-cloud/builds/advanced/#/custom-build-phase-hooks
