### ISSUE TITLE
Docker Image push issue to private repository .

### ISSUE THREAD

**Issue by lntskyvang** [docker/hub-feedback#900]
Hi Team 

1) I have created private repo with name of "skyvanga/auditserver. 
2) I have created tag without any issue. 
3) docker images 
root@CloudieBase:~# docker images 
REPOSITORY                               TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
skyvanga/auditserver-application/image   latest              83531e5a0fed        6 days ago          542 MB
auditserver-application/image            latest              83531e5a0fed        6 days ago          542 MB
auditserver-app/image                    latest              2abc59a0419a        8 days ago          542 MB
audit-couchdb/image                      latest              b34f80328d7c        8 days ago          236.4 MB
node                                     latest              8c2705d4d660        12 days ago         659.8 MB
couchdb                                  1.6.1               c8ada0a94e7d        2 weeks ago         224.5 MB
centos                                   centos6             9c95139afb21        8 weeks ago         194.6 MB

4) Then I try to pus the image in to repo i see below issue (authentication required). 

root@CloudieBase:~# docker push skyvanga/auditserver-application/image
The push refers to a repository [docker.io/skyvanga/auditserver-application/image] (len: 1)
83531e5a0fed: Preparing 
unauthorized: authentication required
root@CloudieBase:~# 

5) Even I logout and login back but still I see same issue. DO needful here. thanks.

**Comment by thaJeztah** [comment]
Images on Docker Hub only have _two_ "components"; username, and repository-name. It looks like you're trying to push an image with _three_ components; `skyvanga/auditserver-application/image`.

Try tagging it as (for example) `skyvanga/auditserver-application`, then push

**Comment by lntskyvang** [comment]
No... skyvanga is my docker hub login name and "skyvanga/auditserver-application/image" this is repository name after tag with existing image ID.
