### ISSUE TITLE
new collaborator not able to access private repo

### ISSUE THREAD

**Issue by ghost** [docker/hub-feedback#901]
i am the owner for a private repo via free account. need help troubleshooting access for team collaborator. collaborators definitely lists him for the private repo. new collaborator does not see the repo displayed when logged in. please advise.

**Comment by filiptepper** [comment]
I'm seeing the same thing.

Did you manage to get it working, @lynnf?

**Comment by lady-wanderer** [comment]
I'm having the same issue, We added someone as a collaborator on a private repo but when they log in the dashboard doesn’t show them any Repo’s. However if we give them this link https://cloud.docker.com/repository/docker/xxxxx/xxxx/tags they are able to access the page and see all the tags and from there they have access to the rest of the repo

**Comment by phagedorn** [comment]
in 2019 the issue is still present. I added a private repo and 2 collaborators and they cant browse the repo page

**Comment by IKOBH** [comment]
Same issue here

**Comment by tourist-C** [comment]
same here

**Comment by Corasonn** [comment]
Same here in 2020.

**Comment by PawlowskiAdrian** [comment]
2021 and still you have to access by direct link:
`https://hub.docker.com/r/` + `user_name/repo_name`

**Comment by cabral450** [comment]
This is still a thing, I had to manually share the link

**Comment by Lerring** [comment]
I'm unable to view a repository I'm added to in the dashboard without manually finding the link!!

**Comment by herrdommel** [comment]
This is still a thing...

**Comment by Emilprivate** [comment]
Also happening for me
