### ISSUE TITLE
unable to authenticate for docker pull from private repo

### ISSUE THREAD

**Issue by lynnf** [docker/hub-feedback#902]
i am the owner for a free docker hub account. i have a successful automated build image im trying to pull via linked github account.

im getting an error message (see below) when running the docker login command. i believe the format is correct. ive tried the -u -p format and --username --password format as well. also, tried deleting and recreating the repo. the server url doesnt seem to be configurable. ive verified the username/password many times through various ways.

please advise.

docker login --username="username" --password="password"
Error response from daemon: Get https://registry-1.docker.io/v2/: unauthorized: incorrect username or password

**Comment by jeroenbourgois** [comment]
I am having the same issue. I am using the latest Docker Edge:
`Version 17.06.0-ce-rc5-mac16 (18400)`
