### ISSUE TITLE
Impossible to upgrade account

### ISSUE THREAD

**Issue by fishandphil** [docker/hub-feedback#905]
Good afternoon,

We are desperately trying to upgrade our Docker account from free to paid as we need a second private respository. 

While we do have all our details entered (e.g credit card, verified email..). When we click on the "Upgrade Plan" button, "Confirm"/"Cancel" shows. When we click on "Confirm", it goes back to "Upgrade Plan" without any error which is very frustrating. 

We have tried in both Docker Hub & Docker Cloud. None works. 

Our account username is "infltr" 
You can write us here: hello@infltr.com

Cheers
Philippe

**Comment by raybogman** [comment]
Having same issue, is there a fix to update private repo ?

**Comment by fishandphil** [comment]
@raybogman we got in touch with docker's support and they upgraded our account manually... we did it through here: https://support.docker.com

Good luck
