### ISSUE TITLE
Docker Hub not reflecting changes

### ISSUE THREAD

**Issue by GBM-Noor** [docker/hub-feedback#906]
Hi All, 

I am new to docker so this might sound stupid. 
I created a public repository in my docker account and then I pushed an image to this repository. 

The push goes through, but when I go the web interface for docker hub, in the repository, Last pushed is still set to never and I cannot see anything under Tags. However if I use a second docker node to pull from this repository the pull request works just fine and I am able to download the image from docker hub. 

Is it normal for the docker hub web interface to take a while before it updates ? 

Regards, 
Nooruddin

**Comment by rostved** [comment]
My repository views on Docker Hub aren't getting updated correctly either and I'm pretty sure it's not supposed to be like that. 

"Last pushed" and the details listed on the "Tags" tab are wrong (not up to date).

**Comment by GBM-Noor** [comment]
@rostved You are right. I just returned from lunch and now the repository is updated. It was similar yesterday. Seems to be a lag between the push and the update to the web interface.

**Comment by kaelumania** [comment]
https://status.docker.com/

**Comment by chad-autry** [comment]
I came here this morning to suggest that it would be helpful to show status issues from the repository view itself.

Last night it wasn't even the view that was behind, I couldn't pull new images. Spent > 45 minutes trying to tweak my CI build to see what my be wrong (contributing to the overload!)

It would have saved time and wasted resources if the repo view had simply had a highlighted link to the status page while there are issues affecting performance.

**Comment by pkennedyr** [comment]
The repository service used by Docker Hub is currently experiencing degraded performance, which is causing longer than normal wait time to display tag information in the UI for newly pushed images and repositories.

We are actively processing a large backlog of repositories updates and have added additional capacity to address the issue.

We apologize for the inconvenience and will provide updates on http://status.docker.com as more information is available and as soon as the issue is resolved.

**Comment by pkennedyr** [comment]
[UPDATE] The repository service is operational and we are processing new repositories and tags as normal.

**Comment by vmahadev** [comment]
@pkennedyr My case is different, the repos which were created and were showing up. Was not logged in for few months. When I logged in few days ago I did not see some of the repos created by me which were missing. I stated that is there a history log where we can find out the repos created and removed/deleted. 

I had spent some good time to create the repos but do not see them now.
