### ISSUE TITLE
Is there possiable to create multi tags on a single automatic building config line (a same image)?

### ISSUE THREAD

**Issue by liuchong** [docker/hub-feedback#908]
My config is like:
branch master /path/to/Dockerfile latest
branch master /path/to/Dockerfile v1
branch master /path/to/Dockerfile v1.1

It will cause at least 2 problems:
1. build 3 times
2. pull multi times if I use different tags

Is there any possiable to build once and create 3 tags on the single image?
Thanks! :joy_cat:

**Comment by pchico83** [comment]
@liuchong It is possible, by separating them by commas, on the same build rule.

**Comment by pchico83** [comment]
@liuchong Just to be more specific, it is available in Docker Cloud plus lots of other CI features. More details about the relation between Hub and Docker Cloud here:
https://forums.docker.com/t/future-updates-on-docker-hub-docker-cloud/20498

**Comment by liuchong** [comment]
Thanks, but when I'm setting like this in the "Docker Tag Name":
```
latest, test1, test1.1
```
it thrown the below error message:
```
latest, test1, test1.1: Invalid 'name' field: Illegal Docker tag character ',' at position 7. Valid values are ^[A-Za-z0-9_][A-Za-z0-9_.-]{0,127}$
```

**Comment by liuchong** [comment]
I'm using docker hub, am I need to switch docker cloud so I could use this feature?

**Comment by liuchong** [comment]
Yes, I successfully configured it on docker cloud, let me switch here, thanks a lot @pchico83 
ps: after some more tries, it seems cannot do this on docker hub, anyway, closing :cat:
