### ISSUE TITLE
docker hub repository not showing repository info and tag 

### ISSUE THREAD

**Issue by paramanandd** [docker/hub-feedback#909]
I have crated repository in docker hub,and after pushing new tag or image version to repository,it is not reflecting tag info on respective DockerHub repository.

**Comment by kaelumania** [comment]
@paramanandd https://status.docker.com/

>[Investigating] Our repository service is experiencing degraded performance and users are experiencing longer wait time to display tag information for newly pushed images and repositories.

**Comment by pkennedyr** [comment]
This issue is being tracked via #906, so closing this duplicate issue.
