### ISSUE TITLE
Sort Ordering of Official Images on Explore Page

### ISSUE THREAD

**Issue by ChristopherBiscardi** [docker/hub-feedback#91]
It's pretty borked. Should _at least_ be alphabetical.

![screenshot 2015-06-18 21 59 06](https://cloud.githubusercontent.com/assets/551247/8247465/544bf9fe-1606-11e5-9504-aac8d9fa58db.png)

**Comment by tianon** [comment]
:heart: :+1:

Something that people can glance at and say "it is very clear to me that this is sorted by X" would be a good default, IMO.

**Comment by tianon** [comment]
(whether that's pulls, stars, alphabetical, etc -- something that isn't "last updated")

**Comment by jeromelaurens** [comment]
yep, definitely would like sort feature

**Comment by ChristopherBiscardi** [comment]
@jeromelaurens This ticket is for the inital sort ordering of the Official Repos on the Explore page. Please open another issue for sort/filter controls (on the explore page) as that will bleed into a discussion about what this page becomes in the future.
