### ISSUE TITLE
Convert Your Account to an Wrong Organisation By Mistake! Important Bug

### ISSUE THREAD

**Issue by LamsaWorld** [docker/hub-feedback#917]
We converted our account to randomly organisation and lost all our repositories and all our emails deleted and the credit card now can access from this organisation!

How we can recover our repositories and access?!

*** Urgent Bug ***
*** Advise for Docker Hub Team To Solve The Bug ***
When the user convert to organisation at least send him email to Accept this converting,
So now i can make a lot of repositories and convert them to any organisation and they can't remove it for now!

**Comment by pkennedyr** [comment]
If an incorrect Docker ID was inputted during the account conversion process, please contact Docker Support at success.docker.com/Account_Support for assistance.
