### ISSUE TITLE
"Powershell was not found in the path", when using hyperv driver : Docker for Mac

### ISSUE THREAD

**Issue by lmsanch** [docker/hub-feedback#918]
I am trying to create a Docker machine, using Docker for Mac. 

```
docker-machine create --driver hyperv --hyperv-disk-size "50000" --hyperv-cpu-count "4" --hyperv-memory "8092" MyDocker
Running pre-create checks...
Error with pre-create check: "Powershell was not found in the path"
```

My physical machine has all the requirements:

OS X El Capitan 10.11.6
16GB RAM
Docker version 1.12.6, build 78d1802

Any solution? Do I need to install VirtualBox and change the driver to VirtualBox? I thought the whole improvement of Docker for Mac vs Docker ToolBox was hyperv driver.

**Comment by londoncalling** [comment]
@lmsanch ,thanks for writing in. 

Actually,  you don't need to use the `hyperv` driver on Docker for Mac, only on Docker for Windows. In the [Docker Machine docs](https://docs.docker.com/machine/get-started/#/create-a-machine) per step 3:

"If you are using Toolbox on Mac, Toolbox on older Windows systems without Hyper-V, or Docker for Mac, use virtualbox as the driver, as shown in this example."

The example command is:

`docker-machine create --driver virtualbox default`

So to create your machine `MyDocker`, the command is:

`docker-machine create --driver virtualbox MyDocker`

That said, _**one of the benefits of Docker for Mac is that you do not need to use Docker Machine to run Docker on your Mac.**_ (We provide Docker Machine in case you want to create multiple Docker  nodes locally to run a quick test of Swarm on a single system, or for a few other use cases.)

Once you install and start up Docker for Mac, you can simply open up a terminal window and start typing Docker commands. This process is described here in the [Docker for Mac Getting Started](https://docs.docker.com/docker-for-mac/#/step-1-install-and-run-docker-for-mac). 

Full details on the differences between the old (Toolbox) and the new (Docker for Mac) setup are provided [here](https://docs.docker.com/docker-for-mac/docker-toolbox/).

Please have a look at that documentation (along with the trying  out the Docker Machine commands and links provided above).
