### ISSUE TITLE
Unable to change Github username/repo for automated build

### ISSUE THREAD

**Issue by mkheck** [docker/hub-feedback#919]
I recently changed my GH username and need to repoint a Docker Hub image automated build to the "new" GH repo. I've tried unlinking/relinking my GH account (at the Docker Hub account level), but I don't see a way to delete/re-add or edit the source GH repo info in my image settings, build settings, etc. Help?  😬 

TIA!

**Comment by arnavs** [comment]
Yeah, how do you do this? It seems like a pretty useful feature... two years later.

**Comment by mkheck** [comment]
This was never fixed and remains broken...for over 3 years. 😞
