### ISSUE TITLE
Haven't received email for creating docker account

### ISSUE THREAD

**Issue by bholagabbar** [docker/hub-feedback#921]
I signed up for an account with the username 'wolfbeacon' on Docker Hub. Haven't recieved the signup email. Even tried forgot password, didn't work. We need access asap, could anything be done? The email I entered was dev.shreyans96@gmail.com

**Comment by trevorpay** [comment]
I'm encountering the same problem: tried two different email accounts and in both cases, no email.
In light of the fact bholagabbar wrote his post 16 days ago without any response implies no one at Docker is actually taking much notice.

**Comment by pkennedyr** [comment]
@bholagabbar Our records indicate that an email was successfully delivered to your specified email address, so it's possible that the verification email has gone to your spam folder. 

For assistance with account registration issues, please contact Docker support and they will be able to help: https://success.docker.com/Account_Support

**Comment by bholagabbar** [comment]
@pkennedyr  You still haven't addressed Docker Support Ticket 00016644 for over a week

**Comment by pkennedyr** [comment]
Hi @bholagabbar, Our records show that ticket 16644 was responded to and resolved on 1/30. If you are still encountering issues, please feel free to open another issue and the team will investigate.
