### ISSUE TITLE
Feature Request: Add option to search/filter by type and platform option

### ISSUE THREAD

**Issue by twang2218** [docker/hub-feedback#923]
## Search by Type

As Docker 1.13 is about to release, the plugins feature will out of the experimental https://github.com/docker/docker/pull/28226 . If I understand correctly, the `docker plugin install` will download the `plugin` from Docker Hub by default.

So, it would be handy we can search the Docker Hub by type: `image` or `plugin`.

## Search by Platform/OS

Most repos on Docker Hub are target Linux x64, however, some repos are target Windows platform, or Linux ARM platform. Currently there is no way to search image for specific platform on Docker Hub, so it would be great Docker Hub implement such feature.

**Comment by laktak** [comment]
also see #615
