### ISSUE TITLE
Unable to delete empty private repositories

### ISSUE THREAD

**Issue by puhoy** [docker/hub-feedback#924]
Hi,
i am unable to delete private repositories from the docker hub that were pushed over the repository limit.
All those repos have a tagged image with a 0 Byte size which i also cant delete. 

Steps to reproduce:

 - go to the repo settings on the docker hub
 - click delete and confirm

This results in "There was an error. The repository was not deleted."

**Comment by mbrk** [comment]
An option is to make the repository public and delete it afterwards.

**Comment by efx** [comment]
Affected me also. +1 for being able to delete a private repository

**Comment by npearce** [comment]
I cannot delete it when marked Public either. Tried to push an image to it, keeps retrying. Tried 'docker pull' just to see if anything would happen, keeps retrying... Totes hosed!

**Comment by hleeanexinet** [comment]
I cannot delete any or my repositories no matter it's public or private. I get the following and I'm the owner.

> Error deleting repository. Please verify if you have permissions.

**Comment by hleeanexinet** [comment]
It looks like the system is down at this moment. See http://status.docker.com/.

**Comment by efx** [comment]
thanks @hleeanexinet  that must have been it. Only now was I able to delete my private repository.
