### ISSUE TITLE
Create automated build cause Chrome hanging

### ISSUE THREAD

**Issue by donchh** [docker/hub-feedback#927]
Hi, 

I use Chrome Version 55.0.2883.95 (64-bit) on macOS sierra.
When i create an automated build, then i click on "Create" button, Chrome freeze and consume all the CPUs.
All is ok after killing/re-opening Chrome.

Dockerhub username : donch
Date : Wed Jan 18 15:30 CET 2017
url : https://hub.docker.com/add/automated-build/github/form/donchh/net-tools/?namespace=donch

**Comment by idlerun** [comment]
I can second this. Running Chrome on macOS El Capitan.

Browser freezes completely and needs to be force quit. The build does still get created in spite of the freeze

**Comment by pkennedyr** [comment]
Thanks for the feedback - we are able to reproduce the issue and the team is looking into a fix.

**Comment by reypm** [comment]
@pkennedyr is also happening on Firefox (latest) and Edge, any ETA on the fix?

**Comment by coolcow** [comment]
It's happening on Chrome Version 56.0.2924.76 (64-bit) @ Linux Mint 18.1 too.
Sometimes, there is a weird mouse flickering too in addition to the freeze.

**Comment by pkennedyr** [comment]
UPDATE: An update has been deployed to Docker Hub which introduces a fix for this issue.

Thank you for the feedback and if you continue to experience related issues, please let us know.
