### ISSUE TITLE
Oauth error when linking bitbucket

### ISSUE THREAD

**Issue by hemanth7787** [docker/hub-feedback#928]
I am trying to link my bitbucket account to Dockerhub from https://hub.docker.com/account/authorized-services/

When i click on the  link bitbucket button , i am redirected to bitbucket where i grant all permissions to dockerhub, but after that i am coming back to dockerhub page and  getting **OAuth timeout** and sometimes **Invalid OAuth verifier.**

I am on Chrome (Version 53.0.2785.143 (64-bit)  on Ubuntu 14.04)

**Comment by gwosty** [comment]
I get the same issue.

**Comment by sirdiego** [comment]
Uh, does no one use the hub with bitbucket, oder does this magically work for some? Because I have the same issue.

**Comment by ProProgrammer** [comment]
Just faced this issue for a few minutes when trying to link my bitbucket account to a docker hub account after unlinking the same bitbucket account with another (different) docker hub account.
Basically, my official bitbucket was linked to my personal docker hub so I unlinked it from there and linked it to my official docker hub account.

But this error went away a few minutes later and I was able to link it without any issues
