### ISSUE TITLE
Procedure for repository space re-allocation

### ISSUE THREAD

**Issue by keeganwitt** [docker/hub-feedback#929]
The Groovy [space](https://hub.docker.com/u/groovy/) was created by someone outside the Groovy team, and I just [learned](https://discuss.gradle.org/t/official-docker-images/21159/5) Gradle has the same [problem](https://hub.docker.com/u/gradle/).  Gradle is particularly concerning since the link on the profile seem that it is affiliated with the Gradle team, although it isn't.  Is there a way to contact the owners of the spaces to request they be transferred?  There's no images published on either.

**Comment by sanscontext** [comment]
Hey @keeganwitt your best bet (and for the Gradle team as well) is to contact support using the [Account Support form](http://success.docker.com/Account_Support). They can help you with squatting issues, afaik.

**Comment by keeganwitt** [comment]
That looks like the right place.  I looked everywhere and couldn't seem to find that.  Thank you!

**Comment by keeganwitt** [comment]
For those who might have found this issue through Google later, their policy for claiming spaces is [here](http://success.docker.com/Cloud/Solve/How_can_I_claim_ownership_of_an_existing_Docker_ID%3F).
