### ISSUE TITLE
:-1: custom login form

### ISSUE THREAD

**Issue by brycefisher** [docker/hub-feedback#93]
Because the login form is customized, it doesn't work well with LastPass. A lot of very smart people have figured out some great defaults on html inputs. IMHO, it's to improve the overall experience for everyone when tweaking standard form elements.

**Comment by ChristopherBiscardi** [comment]
This is an issue which we are aware of. I have a potential fix in mind which will solve the "over-customization" defect and play much nicer with tools like LastPass.

**Comment by brycefisher** [comment]
Yay!! Thanks so much. It is REALLY pretty -- everything in the Beta. Thanks for inviting me.

**Comment by ChristopherBiscardi** [comment]
inputs are no longer "special", closing

**Comment by phemmer** [comment]
This still doesn't work with things like the chrome built-in password manager (dunno about lastpass).

**Comment by mbentley** [comment]
I haven't tried Chrome's password manager but I can at least confirm LastPass works (used it yesterday).

**Comment by phemmer** [comment]
It looks like we're tracking each browser/password manager separately (found a few issues created after this one was). Opened one to track chrome at #386
