### ISSUE TITLE
CRITICAL BUG: Unable to link new GitHub account

### ISSUE THREAD

**Issue by bartimar** [docker/hub-feedback#934]
Hi,
yesterday we split our GitHub organization into several new orgs. I transfered all the repos in the new org. Docker Hub was showing the link to the old one. I tried to remove the link and add a link to the new one.
I'm getting error:
`There was a security error during the github account linking process.`
and sometimes an error:
`Your Github account is already associated with the Docker Hub account 'bartimar'.`
Now our organization can't even add new Automated builds, because there is no link to github and can't be created. 
Also, the linked repo is still the old one showing there https://hub.docker.com/r/ackee/jenkins-android-docker-slave/
Webhooks are no working either anymore :(

**Comment by bartimar** [comment]
Guys, I can't use my account anymore. The webhooks are not working. I need to build everything manually. Also, I can't add new Automated builds because of this :(

**Comment by pkennedyr** [comment]
@bartimar Thanks for the feedback. If you want to remove, or change the level of linking between your GitHub account and the Docker Hub, you need to do this in two places. 

First, remove the “Linked Account” from your Docker Hub “Settings”. Then go to your GitHub account’s Personal settings, and in the “Authorized applications” section, click “Revoke access” for "Docker Hub Registry". 

You should then be able to re-link your account.

If you still are experiencing issues, please reach out to support.docker.com and they will be able to investigate the issues with your account.

**Comment by bartimar** [comment]
Hi, thanks! I got it working already.
