### ISSUE TITLE
BUG: duplicate triggers w/ automated builds

### ISSUE THREAD

**Issue by willfarrell** [docker/hub-feedback#936]
If you create multiple automated build from on repo w/ `When active, builds will happen automatically on pushes.` enabled on each. When a git commit is pushed, a build is trigged multiple times equaling the total number of builds connected to the repo.

**Comment by pietschy** [comment]
We're seeing this as well but the number of builds being triggered seems random.  One repository has a single trigger on master and builds 3 times every push.  The other has 2 triggers (master and a tag) and fires twice.

**Comment by eroak** [comment]
+1

**Comment by housser** [comment]
Also seeing multiple builds on each commit pushed to our source repository. We have it set to build "master" branch to the "latest" Docker hub tag, and also build any Tags (from the repo) to corresponding Docker tags. When I push one commit to master that has one tag, I get two builds for the "latest" build from master, and two builds for the tagged build.

**Comment by DunklerPhoenix** [comment]
+1 Same here [yeah i'm lazy]

**Comment by matthewadams** [comment]
I get two builds for each trigger, period.  I'll guess I'll be ok warming the earth unnecessarily until Docker Hub fixes this issue...  :)

**Comment by andrewnicols** [comment]
I'm also seeing two builds for each branch on one of our repos (https://hub.docker.com/r/moodlehq/moodle-php-apache/builds/).

This is our build configuration, and we have no webhooks at all.

<img width="1261" alt="hub-duplicate-trigger-936" src="https://user-images.githubusercontent.com/370047/45734176-1a384d80-bc16-11e8-8584-17a1d92f70d9.png">

**Comment by nSimonFR** [comment]
As I was have having the same problem, I have switched to [Docker Cloud](https://cloud.docker.com/); no issue since.

**Comment by syedhassaanahmed** [comment]
I have one dockerhub webhook in my GitHub repo, yet I'm still seeing exactly 2 builds.

**Comment by TheUltimateC0der** [comment]
Same here. 2 builds

**Comment by doruchiulan** [comment]
+1

**Comment by oppminh** [comment]
+1 (2 builds per trigger, no webhooks)

**Comment by frize** [comment]
+1

**Comment by yurykovshov** [comment]
experiencing the same issue. I have no webbhooks. 
![Capture](https://user-images.githubusercontent.com/7525042/80802915-1110b000-8bb1-11ea-8060-3cc035748ae8.PNG)

**Comment by mbelang** [comment]
+1

**Comment by jnovack** [comment]
Developers, what do you need from us, the community to solve this issue?

I fear that my duplicate builds are running out my daily allotted server time twice as fast.

**Comment by abitmore** [comment]
> If you are using automated builds, **you can see in your repo if there are 2 or more webhooks linked to it from Docker Hub**. In my case, my repo had 2 Webhooks and it was building twice for every push; so, I removed 1 and it solved the problem.
> 
> In Github and also in Bitbucket you can go to the repo -> Settings -> Webhooks (and delete 1 if there are more than 1 from dockerhub). I saw it in this post: https://success.docker.com/article/why-are-there-multiple-automated-builds-triggered-when-a-single-push-is-made-on-bitbucket. It solved the problem in my case.

I found there are 2 webhooks in my repo settings, one is `https://cloud.docker.com/api/build/...` and the other is `https://hub.docker.com/api/build/`. Not sure if they're the same thing. Recently I've been updating the auto-build settings via hub.docker.com, perhaps it led to the duplicates.

**Comment by alex-envoy** [comment]
Thanks @abitmore - I verified that this was indeed the situation in my repo - 2 otherwise identical hooks, the only difference being the domain of the URI. I'm not seeing any meta info about these webhooks (when they were originally created, updated, etc) but my guess is that the `cloud.docker.com` hook was added after `hub.docker.com` since that subdomain came into use more recently. Either way, thank you!!

**Comment by romainr** [comment]
We are seeing the same issue consistently https://hub.docker.com/repository/docker/gethue/hue/builds

**Comment by mbelang** [comment]
same here, double webhook

**Comment by romainr** [comment]
We only have one circleci webhook though:

![image](https://user-images.githubusercontent.com/17945/96576616-4a37fc00-1287-11eb-9fea-28271914c045.png)
