### ISSUE TITLE
clkao/postgres-plv8 builds timing out

### ISSUE THREAD

**Issue by ruimarinho** [docker/hub-feedback#937]
Hi,

I'm one of the maintainers of the [clkao/postgres-plv8](https://github.com/clkao/docker-postgres-plv8) image on GitHub and the following build keeps failing - https://hub.docker.com/r/clkao/postgres-plv8/builds/bae8dt5uskx7ixgpdpgnr8h/

It builds fine on my machine, so my guess is that compiling V8 really takes a huge amount of time and Docker Hub decides kill it.

Would it be possible to take a look at this issue? Thanks.

**Comment by pchico83** [comment]
@ruimarinho Could you give it a try in Docker Cloud? The timeout for Docker Cloud builds is 4h. Also, you will get some more nice features like the ability to run tests on PRs, streaming build logs, or better github integrations. You can find more information about the relation between Docker Hub and Docker Cloud here: https://forums.docker.com/t/future-updates-on-docker-hub-docker-cloud/20498

**Comment by ruimarinho** [comment]
I'm giving it a try on a personal open source project, but I found two issues:

- The build fails with a message that it can't find the [Dockerfile](https://github.com/ruimarinho/docker-openvpn-monitor/blob/master/Dockerfile): build id is `5aa4f1a7-8e4e-43f9-bfe8-3ca1d557a066`.
- I can't find the setting to add a linked repository (e.g. `python` in this case).

**Comment by ruimarinho** [comment]
```
Building in Docker Cloud's infrastructure...
Cloning into '.'...
Warning: Permanently added the RSA host key for IP address '192.30.253.113' to the list of known hosts.
Reset branch 'master'
Your branch is up-to-date with 'origin/master'.
Dockerfile not found at ./Dockerfile
ERROR: Build failed: Dockerfile not found at ./Dockerfile
ERROR: Build failed with exit code 2
ERROR: Build in 'master' (4615cdee) failed in 0:03:03
```

**Comment by pchico83** [comment]
@ruimarinho The error is because the github repo does not have a Dockerfile. Note that you have linked https://github.com/ruimarinho/openvpn-monitor, instead of https://github.com/ruimarinho/docker-openvpn-monitor.
You can go to the "Build" tag again and configure the source git repo again clicking in "Configure Build" (top right corner).
About repo links, they are not implemented in Docker Cloud yet, and I cannot give an estimate about when they will be available.

**Comment by ruimarinho** [comment]
My apologies, I did not remember I had forked openvpn-monitor too 🤦‍♂️ do I need to disable Docker Hub for each project I migrate to Docker Cloud? Also, will there be any tool to automatically do this for users?

**Comment by pchico83** [comment]
@ruimarinho The migration process to Docker Cloud is manual and you need to deactivate the autobuild in Docker Hub too.
We are actively working on providing a way to automatically do all this, but it is not ready yet.

**Comment by ruimarinho** [comment]
Ok. Thanks for the help. Waiting for the repository owner to enable builds on Docker Cloud.

**Comment by ruimarinho** [comment]
@pchico83 is there a public URL for repositories under Docker Cloud?

**Comment by pchico83** [comment]
@ruimarinho Repositories share the same database between Docker Hub and Docker Cloud, therefore, any operation in Cloud/Hub is bidireccional. This is not the case for autobuild configurations, which is what we are working on to solve it.
Docker Cloud repositories, even if they are public, are only visible for people with access to them, although we are working on fixing that too.

**Comment by ruimarinho** [comment]
Ok, then I think this ticket can be closed. Thank you so much for the feedback!
