### ISSUE TITLE
How long does it take to expire an unconfirmed account?

### ISSUE THREAD

**Issue by Zaijo** [docker/hub-feedback#940]
Hello, today I registered my account on hub.docker.com with my desired username. 
Somehow I can't get the confirmation e-mail. I might have **mistyped the e-mail address**. 

How long does it take to expire this account so I can try to register again? The username is currently "taken". **When is the right time to try again?**

Or could someone, please expire it manually?

**Comment by stoyandimov** [comment]
I'm running into the exact same situation. If I got it right, the email expires in 2 days. Does that mean that the account get removed if not activated within 2 days?

**Comment by Zaijo** [comment]
@stoyandimov Well, for me the account wasn't deleted so  it's still "locked out" 🔒:( I chose a different name and try to live with that.

And yes, the confirmation email expires in 2 day. But that's probably all that's gonna happen. And no one from Docker replied yet.
