### ISSUE TITLE
DockerHub pull count should ignore cached image attempts

### ISSUE THREAD

**Issue by LuisBosquez** [docker/hub-feedback#942]
We are trying to use Docker pulls from DockerHub as a KPI to measure adoption of our images. While this can't be directly related to customer usage, it's the best number we can use for now. 

The usefulness of this metric could improve if the pull count didn't include attempts where the image is already cached and up-to-date. This could be related to first-time downloads or updates, which provides better confidence as a metric for adoption.

**Comment by 00hello** [comment]
Is this what's causing the pull count to update everytime a user pushes to their repo?

I asked this question before (https://github.com/docker/hub-feedback/issues/948). But I don't seem to have an answer.
