### ISSUE TITLE
Linking to Bitbucket requires overly broad permissions

### ISSUE THREAD

**Issue by shirshir** [docker/hub-feedback#944]
When you link to Bitbucket as described on https://docs.docker.com/docker-hub/builds/#link-to-a-hosted-repository-service Docker Hub requires a lot of broad permissions. 

Is it possible to reduce this?

![Permissions](https://docs.docker.com/docker-hub/images/bitbucket_creds.png)

**Comment by LosD** [comment]
Completely agreed. For automated builds, they need access to read public repositories, not a single thing more.
