### ISSUE TITLE
docker login：Error response from daemon

### ISSUE THREAD

**Issue by lijiuyi** [docker/hub-feedback#954]
#docker login
Login with your Docker ID to push and pull images from Docker Hub. If you don't have a Docker ID, head over to https://hub.docker.com to create one.
Username: xxxxx
Password:
Error response from daemon: Get https://index.docker.io/v1/users/: dial tcp: lookup index.docker.io on [::1]:53: read udp [::1]:58466->[::1]:53: read: connection refused

what should I do?

**Comment by songyanren** [comment]
i see the same questions
