### ISSUE TITLE
Missing buttons in Safari 10 (user interface is broken)

### ISSUE THREAD

**Issue by fguillot** [docker/hub-feedback#957]
In build settings, the add/remove buttons are missing with Safari 10:

![docker_hub](https://cloud.githubusercontent.com/assets/323546/22863043/c36bf0a4-f107-11e6-8277-4b89e70f39fb.png)

However this is working with Firefox:

![docker_hub_firefox](https://cloud.githubusercontent.com/assets/323546/22863056/de8134b2-f107-11e6-9ce0-3f00859ab8b6.png)

**Comment by pkennedyr** [comment]
Thanks, @fguillot. Can you confirm the specific version of Safari that you're using?

**Comment by fguillot** [comment]
"Safari Version 10.0.3 (12602.4.8)" on Mac OS Sierra 10.12.3. The only extension enabled is Adblock.
