### ISSUE TITLE
Signup allows mixes case username, but login must be all lowercase

### ISSUE THREAD

**Issue by BenUniqcode** [docker/hub-feedback#960]
I signed up for a hub account with a mixed case username 'UniqCode', but then found I could not login as that after verifying my email. On a hunch, I tried signing in as 'uniqcode' instead, and that worked. It seems  usernames are silently forced to lowercase on signup, but the login form incorrectly looks up the username  case-sensitively.

**Comment by NealHumphrey** [comment]
Bump. Same thing happened to me. The password reset email tipped me off, as it prints out the username "in case you forgot" and it's been forced to lowercase.

**Comment by MalikKillian** [comment]
I reset my password three times before I realized my username was wrong (i.e. mixed-case).

**Comment by BenUniqcode** [comment]
It looks like the signup form now forces lowercase, so this can be closed.
