### ISSUE TITLE
Removed images still exists and can be pulled

### ISSUE THREAD

**Issue by nicolas-albert** [docker/hub-feedback#961]
We have a set of tags here : [convertigo/tags](https://hub.docker.com/r/convertigo/convertigo/tags/)
We mirror on a local server with :  `docker pull -a convertigo/convertigo`
We retrieve all tags, existing but also deleted tags (and images), like : `7.4.2` `mbaas-7.4.2` ...
We can also pull an individual deleted tag : `docker pull convertigo/convertigo:7.4.2`

This is the expected behavior ?
The documentation doesn't mention that.
Thank you :)

**Comment by varun-da** [comment]
Hi,

Facing similar issues.

Thanks!
