### ISSUE TITLE
Cannot activate my DockerHub account!

### ISSUE THREAD

**Issue by sofianito** [docker/hub-feedback#962]
Today, I just signed up to DockerHub but didn't receive the activation email. I tried to reset the login but I still didn't receive any email. When I try to sign in I get the error: Account not active yet. Please check your email to activate your account.

Help!
Thanks

**Comment by MartinLamby** [comment]
I have the exact same problem. 
Please help!

**Comment by pkennedyr** [comment]
Thanks for the feedback. Please contact Docker support for assistance with account registration issues and they will be able to help: https://success.docker.com/Account_Support

Also, make sure to check your spam folder to ensure the verification email has not been marked as spam by your email provider.

**Comment by sharath-yml** [comment]
@pkennedyr That link is 404 now. Is there some other place?

**Comment by antelopehi** [comment]
https://success.docker.com/support
@sharath-yml  maybe you can send msg in this page.

**Comment by shiMingZheng** [comment]
plase use this url: https://cloud.docker.com/

**Comment by Anishmourya** [comment]
I have received mail but could not verify in 2 days. My link has been expired and i'm trying to login but still its showing me "Account not active yet. Please check your email to activate your account".
Any Idea how can i resend activation link again ? 
Thanks in advance

**Comment by Anishmourya** [comment]
i did solve ^^^^ issue , clicked on forgot password , once password has been changed its automatically confirmed and activated my account . thanks

**Comment by mufaddalmandvi** [comment]
i had the same problem. you can click on forgot password, then sign in again. your problem will be solved
