### ISSUE TITLE
trigger URL stopped working

### ISSUE THREAD

**Issue by musketyr** [docker/hub-feedback#966]
we have an automated build at https://hub.docker.com/r/metadata/registry/ and as we renamed the GitHub repository we must rely on notifying docker hub using the trigger URL but it stopped working this morning. if we issue a POST request

```
curl -v -H "Content-Type: application/json" --data '{"source_type": "Tag", "source_name": "2.1.29"}' -X POST https://registry.hub.docker.com/u/metadata/registry/trigger/the-secret-hash/
```
we got `200: OK` response but it does not appear in the `Last 10 Trigger Logs` nor the automated build is triggered

**Comment by jarrold** [comment]
Same issue for me. But strangely affected 4 out of 6 Repositories.

**Comment by musketyr** [comment]
Feel free to close now
