### ISSUE TITLE
Can I give read only (pull only) access to a specific user in private repository

### ISSUE THREAD

**Issue by raghav135** [docker/hub-feedback#967]
Can I give read only (pull only) access to specific user(s) in private repository?

Want to evaluate Docker Hub for our project, but we definitely need this feature.

**Comment by rommik** [comment]
Yes,

1. Go To Teams
2. Create a Team
3. Add the user to that team.

4. Go to your repositories 
5. Click on  repository
6. Clock on Collaborators
7. Choose the team created from step 3 and Access rights.

**Comment by GerrysAppstech** [comment]
is there any video related to this ?
