### ISSUE TITLE
Signup - never times out if validation link never clicked

### ISSUE THREAD

**Issue by instantlinux** [docker/hub-feedback#969]
I registered a new account with email / password / account-name. But I made a typo in the email address.

Days later, then weeks later, I went back in and tried to access that account-name. It always rejects my attempts, saying the account-validation link was never clicked.  I can't log in to change the bad email address: I'm not able to use the account name that I want.

Solution would be to prune the database of non-validated accounts after 1 or 2 days if the validation link was never clicked.

**Comment by instantlinux** [comment]
The email address I typed incorrectly "richb@instantlinx.net". The error message when I log in with that address is "Account not active yet. Please check your email to activate your account".

**Comment by instantlinux** [comment]
As this issue languished for a couple months, I went and bought the mistyped domain name so I could receive the password-reset email. The issue still exists though for anyone who make a similar mistake.

**Comment by logicethos** [comment]
I confident I typed in the e-mail address correctly, but never received the validation e-mail.
