### ISSUE TITLE
Can't copy repo names

### ISSUE THREAD

**Issue by duglin** [docker/hub-feedback#97]
When viewing a list of repos, either after I login or after a search, I can't highlight ANY of their names to copy it. Each appears to be something I can drag though, not sure why. Please allow me to copy the text there so I can easily then paste it into my "docker pull" command.

**Comment by duglin** [comment]
Same is, sort of, true for the list of tags when you get more info on a repo.

**Comment by nhsiehgit** [comment]
On the current hub you're not able to click and highlight either.
Could be a useful feature enhancement down the line.

**Comment by duglin** [comment]
yep - noticed it on current hub a while ago, just never got around to opening an issue  :-)
