### ISSUE TITLE
Unable to delete repository or tag in docker hub

### ISSUE THREAD

**Issue by dmasilamani** [docker/hub-feedback#970]
I have a public repository with a bunch of images named with build number from Jekins. Since bunch of images, I am not able to push to repository and could not even delete the repository. It keeps throwing the error saying "Error deleting repository. Please verify if you have permissions." I have logged in with my credentials but the same error.
![Uploading docker-hub-error1.PNG…]()
![Uploading docker-hub-error2.PNG…]()

Please find attached the screen shot.

**Comment by nahammervold** [comment]
Are you able to pull? I'm not able to pull any images from docker hub right now. AWS is having S3 issues right now that may be related.

**Comment by dmasilamani** [comment]
Yeah, I too was not able to pull or push anything. AWS s3 could be a problem but I was not able to delete any repository from docker hub directly. Now, I can delete the repository.
