### ISSUE TITLE
Automated build succeeded, but tag was not created. 

### ISSUE THREAD

**Issue by derwasp** [docker/hub-feedback#971]
[Here](https://hub.docker.com/r/derwasp/jenkins-jnlp/builds/brsgvj4zh6gbqu5np9mrmcp/) and [here](https://hub.docker.com/r/derwasp/jenkins-jnlp/builds/bbnmcbzjv53wsprthzgff7n/) are examples of the build.
They are green (not failed), but contain no logs and no tags were created from it.

**Expected result**
If there was an issue with the build process, it should actually say that it errored out. If everything is okay, the tag should be created.

**Comment by walkerk1980** [comment]
I'm having the same issue with an automated build. I created 2 automated builds, one gets tagged latest just fine, the other has no tags after successful builds.

https://hub.docker.com/r/walkerk1980/kali-inter/tags/
https://hub.docker.com/r/walkerk1980/freenas-kali/tags/
