### ISSUE TITLE
can't create org with my namespace of choice

### ISSUE THREAD

**Issue by aaronmarkham** [docker/hub-feedback#972]
I'm trying to get our org setup for releasing Caffe2 docker images, but can't create an org using any variation of caffe2/Caffe2/Caffe 2 and there's no feedback other than a red box, so what should I do? I don't see any other organization show up in search, and since our team is the primary maintainer of Caffe2 it would be awesome if we could use that name.

Thanks.

**Comment by michield** [comment]
I have the same issue.

**Comment by thaJeztah** [comment]
could you send an email to support@docker.com they may have more insight into this

**Comment by michield** [comment]
I have emailed support and provided a screencast. I'm on FF on Ubuntu 16.04, not sure if that matters.

**Comment by bw2** [comment]
I ran into the same issue because that namespace name was already taken.
