### ISSUE TITLE
Unable to upgrade billing plan

### ISSUE THREAD

**Issue by adi-raghavendra** [docker/hub-feedback#974]
Currently, we are on small(10 repos) billing plan.  I tried to update it to medium. When I click on confirm, nothing happens. 
<img width="1144" alt="screen shot 2017-03-03 at 12 54 09 pm" src="https://cloud.githubusercontent.com/assets/15131600/23568697/8c4b1d30-0010-11e7-8b67-237605abab3e.png">

**Comment by pkennedyr** [comment]
@adi-raghavendra Thanks for the feedback - we are working on a fix for this bug now.

**Comment by pkennedyr** [comment]
@adi-raghavendra A fix for upgrade/downgrade issue you were experiencing on the Hub billing page is now live.

**Comment by erickpece** [comment]
I'm seeing this too.
