### ISSUE TITLE
Same or different private repository for production and development?

### ISSUE THREAD

**Issue by anisolankure** [docker/hub-feedback#979]
Configuration for repository:
Docker version 17.03.0-ce
LINUX Ubuntu 16.04

We are in process of deploying our systems in docker environment at the moment. We have all the images ready and stored on repository which is not secured and now we are trying to build secure repository to push and pull our images securely. 

I have question, is it good practice having two different repositories, one for development/QA/UAT and other one for production. My understanding says it will be more complicated, but to keep everything secure I don't mind making things bit complicated. 

Any help will be highly appreciated.

**Comment by rommik** [comment]
We have two repositories. One for Dev/QA which is only accessible by the team. The second repository is also private, but the login/pwd is shared with production ops. In there we have releases and betas.

It is slightly complicated, but it works for us. The production teams don't have access to our development and tests.

**Comment by anisolankure** [comment]
Thank you for the reply. 

That make sense for me as well, having two different repositories will make our builds more secure. But, there is one issue with our architecture as we have two different domains for development/testing and other for production. If we get registry server in production domain and other one in development then we need some intermediate between two domains to push the images from development domain to  the registry in production domain. 
We are using TFS and that can act as intermediate but will that work cross domain to push the images?
