### ISSUE TITLE
Automated builds cancelled after finishing

### ISSUE THREAD

**Issue by koral--** [docker/hub-feedback#983]
https://hub.docker.com/r/droidsonroids/bitrise-android/builds/bwcoab84fprqmxkk6jvcgfk/
Relevant log part:
```Pushing index.docker.io/droidsonroids/bitrise-android:sdk_tools_25.2.5...
Done!
Build finished
Build canceled.
```
Issue is reproducible in other builds as well: https://hub.docker.com/r/droidsonroids/bitrise-android/builds/

**Comment by bgruening** [comment]
I have a similar issue here:
https://hub.docker.com/r/bgruening/galaxy-rna-workbench/builds/b9umumw5mkvczf424mwqzmd/

```
Successfully built b85e40bd33c9

Pushing index.docker.io/bgruening/galaxy-rna-workbench:latest...
Build canceled.
```

**Comment by dborgesr** [comment]
Same here:
 Successfully built ee41b9ee3ee8 
Pushing index.docker.io/dborgesr/euplotid:euplotid... 
Build canceled

**Comment by matt-deboer** [comment]
And it still continues, today:
```
Successfully built f49d9dda52a6
Pushing index.docker.io/mattdeboer/mesos-module-development:1.0.3...
Build canceled.
```

**Comment by pkennedyr** [comment]
Thanks for the feedback. It appears that the displayed error message is not reflecting the actual state. In the above cases, the build cancellation is due to a build time out error. We will update the build log message to more accurately reflect this error.

**Comment by andrewssobral** [comment]
Hi @pkennedyr 

I had the same issue:
```
Successfully built a709bc0e2910

Successfully tagged andrewssobral/dlm3:latest

Pushing index.docker.io/andrewssobral/dlm3:latest...
Build canceled.
```
Please, see: https://hub.docker.com/r/andrewssobral/dlm3/builds/bngt7mcqcl5eugnzquljrle/

There is some solution for this?

**Comment by verajosemanuel** [comment]
same here. Build is cancelled with no error.

https://hub.docker.com/r/jvera/tidyviz/builds/bx6bpy8ndq2m2ka5blt9byg/

any hint?

**Comment by andrewssobral** [comment]
Hi @verajosemanuel ,
I did a re-build and it worked fine later.
I think the build process is canceled automatically when it takes very long time to finish.

**Comment by Cactusbone** [comment]
same issue:
```
Pushing index.docker.io/cactusbone/postgres-postgis-sfcgal:pg9.4...
Build canceled.
```
https://hub.docker.com/r/cactusbone/postgres-postgis-sfcgal/builds/bz3skavlrwrww2rgci6dyrt/

It takes approximately 2 hours to build my image since a lot of compilation is involved. 
I can totally understands timeouts are needed, but is there a way to configure timeouts ? or apply a timeout per build step ?

**Comment by Cactusbone** [comment]
this is the exact same bug as #547

**Comment by koral--** [comment]
It does not seem to be the same issue, it differs by presence of `Build finished` log entry.
In #547 build seems to be cancelled perhaps due to timeout. 
Here build is cancelled **after** finishing.

**Comment by imimsri** [comment]
Same here https://hub.docker.com/r/csoriano/r3.4.0_plink1.09/builds/bzancklabp4cnnu6c9twfjs/
Is there anything we can do?

**Comment by pchico83** [comment]
Automated builds are cancelled is they take longer than 2 hours, including the pushing phase.

**Comment by verajosemanuel** [comment]
I think in that case the message is confusing because informs of an error, but it's not

**Comment by imimsri** [comment]
I see... so there is no way I can automatically build this image? The problems with this is that when installing R packages  it has to download and compile them, which takes quite a lot.... Not sure what I can do....

**Comment by imimsri** [comment]
Well, what I've read is that I can split the image into several and linked the based on FROM....that is something not very useful for automation..... or even build it in my server and push it to the hub, but still, we are breaking automation.....

**Comment by verajosemanuel** [comment]
or not setting an automated build. Just offer your Docker file

**Comment by mkenney** [comment]
This is particularly frustrating when the same build only takes about 20 minutes on my 3 year old laptop but can't complete on hub builds. And just offering my Dockerfile isn't a great solution.

**Comment by jacknlliu** [comment]
Same here 
```
Successfully tagged jacknlliu/tiago-ros:indigo

Pushing index.docker.io/jacknlliu/tiago-ros:indigo...
Build canceled.
```
https://hub.docker.com/r/jacknlliu/tiago-ros/builds/bubuqlnfuzlzcfck3rpcgea/

**Comment by approximatenumber** [comment]
https://stackoverflow.com/a/34588866/5980797
2 hours is a limit. Including push phase. (
