### ISSUE TITLE
Multiple tags for the same built image

### ISSUE THREAD

**Issue by nazar-pc** [docker/hub-feedback#984]
I've seen a few issues like this, but a bit different.
My automated builds are configured to produce different tags from different Dockerfiles within the same repository:
![2017-03-16 03-57-01](https://cloud.githubusercontent.com/assets/928965/23978449/b8f9e1ae-09fc-11e7-9b37-f2648db7ee9c.png)

What I want to achieve is what I've set on the first line - build image once and assign tags to it. Unfortunately Docker Hub doesn't support this, but hopefully one day it will (should be pretty straightforward to implement).

There is a workaround, I can add more build options, but I already have 12 images there and multiplying them by 2 makes maintenance painful.

**Comment by pchico83** [comment]
@nazar-pc This is already supported in Docker Cloud, using the syntax that you propose.
This post is a little out of date now, but you can find more reasons to switch to Docker Cloud here:
https://forums.docker.com/t/future-updates-on-docker-hub-docker-cloud/20498

**Comment by nazar-pc** [comment]
Looks interesting and... confusing. I've heard about it a few times, will try to use it now.

**Comment by gonadarian** [comment]
Tried this just now myself on Docker Cloud. Comma-separated list of tags works in Docker Tag input box.
