### ISSUE TITLE
Style of <pre> tag

### ISSUE THREAD

**Issue by FranklinYu** [docker/hub-feedback#988]
The `<pre>` tag should have gray background, not just `<code>`. Currently it's like (taking [Postgres](https://hub.docker.com/_/postgres/) as example)

![wrong](https://cloud.githubusercontent.com/assets/3153452/24015001/67a4db5e-0a5d-11e7-8c1e-9d84273d0d1a.png)

but it should be like

![right](https://cloud.githubusercontent.com/assets/3153452/24015045/8a3e7b84-0a5d-11e7-8d44-52f83b1e47e2.png)

Solution: simply add this to style sheet:

```css
pre {
	background-color: #f8f8f8;
}
```

**Comment by franklinyu** [comment]
Anyone? Or shall this issue go somewhere else?

**Comment by geerlingguy** [comment]
See also: https://github.com/docker/hub-feedback/issues/124

I've noticed this as well, finally got annoyed enough to look in the issue queue!

**Comment by febLey** [comment]
The current style annoys me more than it should.

**Comment by ibnesayeed** [comment]
Also, the padding should be applied to `pre` not the `code` tag, which is causing the first line of code to be indented and not the following lines.

**Comment by FranklinYu** [comment]
This issue no-longer exists somehow.
