### ISSUE TITLE
Someone (maybe from my company) made a user name with our company name

### ISSUE THREAD

**Issue by jminardi** [docker/hub-feedback#990]
Can someone at Docker give me the email address associated with the account? I want to find out if it is someone from our company.

I was trying to make a new organization for our company (Voxel8) and found out someone already made a user account with that name.

I asked everyone on my team and no one seems to remember it, but one of our former employees could have made it.

**Comment by urugang** [comment]
+1

**Comment by urugang** [comment]
i have same problem.

**Comment by thaJeztah** [comment]
I'd recommend contacting support@docker.com

**Comment by sebaacuna** [comment]
Same problem here
