### ISSUE TITLE
When commenting on a docker image, the textarea is really small

### ISSUE THREAD

**Issue by mdelapenya** [docker/hub-feedback#994]
The CSS class for the textarea container is `large-6`, making its child elements to be really small, compared with the already present comments. Changing that CSS class to `large-12` will solve the UX problem.

Actual behaviour:
<img width="1382" alt="screen shot 2017-03-24 at 09 13 16" src="https://cloud.githubusercontent.com/assets/951580/24285822/3a5dab42-1072-11e7-87b6-fbfdd5b32991.png">

Expected behaviour:
<img width="1376" alt="screen shot 2017-03-24 at 09 13 41" src="https://cloud.githubusercontent.com/assets/951580/24285821/3a5cff4e-1072-11e7-9fe9-a1021197fa2b.png">

**Comment by tianon** [comment]
The "Comments" functionality appears to now be completely gone from Docker Hub, which renders this issue obsolete! :tada: :heart:

**Comment by mdelapenya** [comment]
Closing as per @tianon comment
