### ISSUE TITLE
Unable to login on mac - signal: abort trap

### ISSUE THREAD

**Issue by ericmelz** [docker/hub-feedback#996]
I'm new to docker.  When I try executing "docker login"  I see the following:

Erics-MBP:~ eric$ docker login
error getting credentials - err: signal: abort trap, out: ``

I'm running Docker Community Edition on Mac
Version 17.03.0-ce-mac2 (15654)
Channel: stable
1d7d97bbbd

Help is appreciated!

Thanks

**Comment by reydelleon** [comment]
Hi there,

Did you ever solve this? I'm going through the same after updating Docker and haven't found any answers.

**Comment by ericmelz** [comment]
I just retried and it worked without any errors.  Weird.  Not sure if there
was a system update in the meantime of some sort.  Wish I could be more
helpful!

**Comment by reydelleon** [comment]
I haven't been that lucky, hehe. Thanks for your time though. I appreciate it.

**Comment by ericmelz** [comment]
The problem has resurfaced.  I'll post if there's a resolution.

**Comment by ericmelz** [comment]
Found this in /var/log/system.log
`Jun  8 16:35:41 Erics-MBP com.apple.xpc.launchd[1] (com.apple.ReportCrash[566]): Endpoint has been activated through legacy launch(3) APIs. Please switch to XPC or bootstrap_check_in(): com.apple.ReportCrash`

**Comment by reydelleon** [comment]
In my case, the issue got solved when I switched to the AWS credentials helper. You can find it here: https://aws.amazon.com/blogs/compute/authenticating-amazon-ecr-repositories-for-docker-cli-with-credential-helper/

**Comment by ericmelz** [comment]
Ok, so you're using ECR?

**Comment by reydelleon** [comment]
I am.

**Comment by sameerbhadouria** [comment]
I had to sudo it.
